### ISSUE TITLE
Rinkeby Faucet has not been working for the past one week or more

### ISSUE THREAD

**Issue by ravisriv** [ethereum/go-ethereum#22062] opened 2020-12-23 08:50 UTC
#### System information

Rinkeby Faucet

#### Expected behaviour

Rinkeby Faucet should send Rinkeby ETH for testing at the wallet address.

#### Actual behaviour
When a twitter URL is entered, the response is always "No Ethereum Address Found to Fund"

Probably, Rinkeby Faucet is failing to read the contents of the URL.

#### Steps to reproduce the behaviour

Make a tweet with the public address of your wallet (connected to Rinkeby network). Get the URL of the tweet and post it in the Rinkeby Faucet. Press "Give Me Ether". The response will be "No Ethereum Address Found to Fund". 

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment] 2020-12-23 16:41
We are really sorry about this - unfortunately the only person who can solve this at the moment is in his earned holiday. When he comes back we will care for this problem and try to reduce the bus-factor of this problem.
also duplicate of #22031

**Comment by ravisriv** [comment] 2020-12-23 17:54
@ligi Thank you very much. I understand. Happy holidays! You are always very helpful!!

**Comment by cn4941** [comment] 2021-01-05 02:23
hello fine sirs, can you please send 18 test eth to 0x0901fC18745A9515e2733d74bb3005cA76dEf33E thank you

**Comment by karalabe** [comment] 2021-01-05 12:08
This was fixed yesterday.

**Closed by karalabe** 2021-01-05 12:08 UTC
Labels: type:bug

**Comment by cn4941** [comment] 2021-01-05 15:05
> This was fixed yesterday.

still not working for me using FB link :(

**Comment by parnaa** [comment] 2021-04-02 16:00
> > This was fixed yesterday.
> 
> still not working for me using FB link :(

I have tried today several times, it's not working here too ..
