### ISSUE TITLE
Etherscan inconsistent

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#30593] opened 2024-10-14 06:32 UTC
This might not be a problem with go-ethereum, but I'm raising it here because issues are a pretty good discussion format. Also because it may turn out to be related to geth anyway, if geth is used under the hood. 

Is an internal transfer `0.1 ETH` or `0.01 ETH`?

The transaction [`0x96dfd56413baf7ee53483d5d6788ea5faa621ee6bb7d4b8808408d1f07f72bf8`](https://etherscan.io/tx/0x96dfd56413baf7ee53483d5d6788ea5faa621ee6bb7d4b8808408d1f07f72bf8) to contract [`0x897a96deb94291b785faff64088f7202a019f38e`](https://etherscan.io/address/0x897a96deb94291b785faff64088f7202a019f38e), shows on etherscan as if it makes an internal tx to "MevRefunder" of `0.01 ETH`. 

![Screenshot 2024-10-14 at 08-25-39 Ethereum Transaction Hash (Txhash) Details Etherscan](https://github.com/user-attachments/assets/4469c705-e123-4e62-bac8-99c96e187895)
 
Also the "internal transactions" show the same

![Screenshot 2024-10-14 at 08-27-35 Ethereum Transaction Hash (Txhash) Details Etherscan](https://github.com/user-attachments/assets/b1ceb2fe-4bb8-4340-a430-34fad2740fda)

-----------

However, looking at the state changes, it becomes clear that `0.1` has been transferred: 

![Screenshot 2024-10-14 at 08-27-03 Ethereum Transaction Hash (Txhash) Details Etherscan](https://github.com/user-attachments/assets/b98dbe04-b220-487d-a116-d02778ef2da7)

Also, checking the parity-style trace shows `0.1`.: 

![Screenshot 2024-10-14 at 08-28-45 Etherscan Transaction VMTrace And Debug](https://github.com/user-attachments/assets/5eb29cd1-a5ad-4025-8b1c-96eb7e391625)

**Comment by Enigmatic331** [comment] 2024-10-14 09:35
On cursory glance seems like our Geth nodes are returning this for tracing: https://etherscan.io/vmtrace?txhash=0x96dfd56413baf7ee53483d5d6788ea5faa621ee6bb7d4b8808408d1f07f72bf8&type=gethtrace2

(will be back on this a bit later)

**Comment by Enigmatic331** [comment] 2024-10-14 11:11
Ok... So dumping this from Erigon between debug_* and trace_* endpoints:

debug_traceTransaction
`{"jsonrpc":"2.0","id":1,"result":{"from":"0xc13ced137e90bc695cb77288962280516a2f9b8b","gas":"0x30d40","gasUsed":"0x906f","to":"0x897a96deb94291b785faff64088f7202a019f38e","input":"0x9103de440000000000000000000000000000000000000000000000000080949c79f1c2dc","calls":[{"from":"0x897a96deb94291b785faff64088f7202a019f38e","gas":"0x297fb","gasUsed":"0x10e0","to":"0x000f3df6d732807ef1319fb7b8bb8522d0beac02","input":"0x0000000000000000000000000000000000000000000000000000000067082fe7","output":"0xb593042853e5fedd7a92fa7607244cbf8825dd63298e52b8286ed61368c4699b","value":"0x0","type":"CALL"},{"from":"0x897a96deb94291b785faff64088f7202a019f38e","gas":"0x8fc","gasUsed":"0x0","to":"0xc13ced137e90bc695cb77288962280516a2f9b8b","input":"0x","value":"0x2386f26fc10000","type":"CALL"}],"value":"0x0","type":"CALL"}}`

trace_transaction
`{"jsonrpc":"2.0","id":1,"result":[{"action":{"from":"0xc13ced137e90bc695cb77288962280516a2f9b8b","callType":"call","gas":"0x2ba24","input":"0x9103de440000000000000000000000000000000000000000000000000080949c79f1c2dc","to":"0x897a96deb94291b785faff64088f7202a019f38e","value":"0x0"},"blockHash":"0x04ccbbad4bdee79a5f000e30969561b61aa61c5a081f0562dc7722fbbf32b31f","blockNumber":20937412,"result":{"gasUsed":"0x4796","output":"0x"},"subtraces":2,"traceAddress":[],"transactionHash":"0x96dfd56413baf7ee53483d5d6788ea5faa621ee6bb7d4b8808408d1f07f72bf8","transactionPosition":87,"type":"call"},{"action":{"from":"0x897a96deb94291b785faff64088f7202a019f38e","callType":"call","gas":"0x297fb","input":"0x0000000000000000000000000000000000000000000000000000000067082fe7","to":"0x000f3df6d732807ef1319fb7b8bb8522d0beac02","value":"0x0"},"blockHash":"0x04ccbbad4bdee79a5f000e30969561b61aa61c5a081f0562dc7722fbbf32b31f","blockNumber":20937412,"error":"Reverted","result":{"gasUsed":"0x89c","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x96dfd56413baf7ee53483d5d6788ea5faa621ee6bb7d4b8808408d1f07f72bf8","transactionPosition":87,"type":"call"},{"action":{"from":"0x897a96deb94291b785faff64088f7202a019f38e","callType":"call","gas":"0x8fc","input":"0x","to":"0xc13ced137e90bc695cb77288962280516a2f9b8b","value":"0x16345785d8a0000"},"blockHash":"0x04ccbbad4bdee79a5f000e30969561b61aa61c5a081f0562dc7722fbbf32b31f","blockNumber":20937412,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[1],"transactionHash":"0x96dfd56413baf7ee53483d5d6788ea5faa621ee6bb7d4b8808408d1f07f72bf8","transactionPosition":87,"type":"call"}]}`

**Comment by mtbitcoin** [comment] 2024-10-14 11:21
using geth and with the debug_traceTransaction end point , data matches what is displayed on the https://etherscan.io/tx/0x96dfd56413baf7ee53483d5d6788ea5faa621ee6bb7d4b8808408d1f07f72bf8 (main tab)

curl http://localhost:8545 -X POST --data "{\"jsonrpc\":\"2.0\",\"method\":\"debug_traceTransaction\",\"params\":[\"0x96dfd56413baf7ee53483d5d6788ea5faa621ee6bb7d4b8808408d1f07f72bf8\", {\"tracer\":\"callTracer\", \"timeout\":\"5s\"}],\"id\":1}" -H "Content-Type: application/json" 

![image](https://github.com/user-attachments/assets/c74c7c0f-eef9-4eb3-ad85-9dc8bdcaab2c)

**Comment by s1na** [comment] 2024-10-15 06:52
Another repro for the issue: 0x395c82b4fd16307eb98d7d96be21f043d36ff5f1247c43bdbe643dbd296163d4 from the same address.

**Comment by s1na** [comment] 2024-10-15 07:17
It's weird that they should be disagreeing on the call value. That is not a derived field. Only difference I see between Geth and Erigon is that Geth uses `*big.Int` for its `OnEnter` hook whereas Erigon uses `*uint256.Int`.

Because Erigon's debug_ API differs from its trace_ API we could also take a look there for clues. I believe these are the sources. Debug_ API: 
https://github.com/erigontech/erigon/blob/586af3dd7bdf9601ea7c03ca02047ab28aefc11d/eth/tracers/native/call.go#L160

Trace_ API:
https://github.com/erigontech/erigon/blob/586af3dd7bdf9601ea7c03ca02047ab28aefc11d/turbo/jsonrpc/trace_adhoc.go#L387

**Comment by Maliksb11** [comment] 2024-10-17 20:35
ok

**Comment by s1na** [comment] 2024-10-25 03:32
It seems like the issue is with the beacon root system call not being applied prior to tracing. Closing here as it is not on our side.

**Closed by s1na** 2024-10-25 03:32 UTC
Labels: type:bug
