### ISSUE TITLE
Geth fails to build with go version 1.10 (new version of go)

### ISSUE THREAD

**Issue by pschlump** [ethereum/go-ethereum#16119] opened 2018-02-17 22:06 UTC
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
1.8.1 - unstable
OS & Version: Windows/Linux/OSX
Mac OS 10.11.6
Commit hash : (if `develop`)

#### Expected behaviour
With go 1.9.4 and earlier you could cd to cmd/geth and `go build` and get an executable.

#### Actual behaviour
# github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
../../vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51: cannot use refZero (type int) as type *_Ctype_struct___CFAllocator in argument to func literal
../../vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:165: cannot use refZero (type int) as type *_Ctype_struct___CFAllocator in argument to func literal
../../vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:166: cannot use refZero (type int) as type *_Ctype_struct___CFAllocator in argument to func literal

No executable is generated

#### Steps to reproduce the behaviour
Install go 1.10 - go compile it.

#### Backtrace

````
[backtrace]
````

**Comment by pschlump** [comment] 2018-02-17 22:13
This seems to be a duplicate with #16118 - (only 1 minute apart) - and #16118 has a fix in it.

**Comment by RobinJayaswal** [comment] 2018-02-17 22:13
It just needs to use the latest `notify` version, as a work around you can build from source by replacing `notify` in vendor package with newer version

**Comment by ligi** [comment] 2018-02-17 22:16
Closing as it is a duplicate of #16118

**Closed by ligi** 2018-02-17 22:16 UTC
