### ISSUE TITLE
bzzup: optionally generate index.html files for manifests

### ISSUE THREAD

**Issue by homotopycolimit** [ethereum/go-ethereum#3401] opened 2016-12-04 15:14 UTC
The bzzup uploader can recursively upload directories to swarm. All files in all subdirectories end up being listed in some manifests but it is not easy to navigate the directory tree on swarm. 
The two options available right now are to load the root manifest in a swarm filemanager or to download the manifests by hand (using bzzr) and inspecting the json.

We do not want the bzzd http daemon generating html listings for manifest assets (in the way an apache webserver might generate directory listings); However there is no reason we could not generate a simple file-listing html file during bzzup upload and register it as the empty path in each manifest that would not otherwise have an empty path.
This enhancement would make onboarding of new users easier, it would potentially vastly decrease the number of errors of the form "manifest entry for ' ' not found" (which has to be confusing).

**Comment by fjl** [comment] 2016-12-04 15:17
Another idea:

The 404 response could include a link to a listing page generated by bzzd,
i.e. "list files in this manifest".

**Comment by homotopycolimit** [comment] 2016-12-04 15:18
this seems to overlap with https://github.com/ethereum/go-ethereum/issues/3380

> The 404 response could include a link to a listing page generated by bzzd,
> i.e. "list files in this manifest".

I like that too.

**Comment by fjl** [comment] 2016-12-04 15:18
> errors of the form "manifest entry for ' ' not found" (which has to be confusing)

It would be less confusing if the error said "manifest <short hash>... does not contain <path>".

**Comment by zelig** [comment] 2016-12-04 15:48
this could possibly be a special feature maybe as part of configurable swarm-fs mappings https://github.com/ethereum/go-ethereum/issues/2437
but i do not support it being generated by default.

in fact i would like to see a javascript lib that renders an index page by traversing the manifest with a series of bzzr calls (similarly to the file manager)

**Comment by fjl** [comment] 2016-12-04 15:52
What I meant is that the HTTP gateway could support a special URL, e.g. `/bzzlist:<hash>` which would output a listing of files in the manifest.

**Comment by zelig** [comment] 2016-12-04 16:52
there is no notion of  listing of files any more than what the manifest
specifies. and that says it all.
no need to put application logic into lower levels or?

**Comment by fjl** [comment] 2016-12-04 16:54
It's a convenience thing. You can ignore the idea, I suggested it because it would make my life easier.

**Comment by fjl** [comment] 2016-12-04 16:58
Alternative suggestion: output the manifest pretty-printed if requested directly and make entries links if the client's Accept header indicates preference for HTML.

**Comment by homotopycolimit** [comment] 2016-12-05 17:39
I would also favor some kind of mechanism in which the user is presented with the contents of a manifest.

I understand the reluctance to put this user interface into the lower level - that is why I suggested it as part of the uploader. It would make all those manifests that were uploaded with bzzup more navigable while not changing anything in the underlying system.

Having said that, I still think it would be a good idea to have better error pages for swarm in general. @zelig How would you suggest we get there? A separate (optional) proxy server sitting on top of bzzd?

**Comment by fjl** [comment] 2016-12-06 01:03
Bzzd can output better errors without a proxy. They don't need to look fancy for now. These pages will be seen by users if swarm fails to retrieve something and should contain a small amount of debugging info that may hint at the cause.

The ideas I suggested here were meant as alternatives to the originally proposed bzzup feature (generating HTML listings at upload time). The feature is still useful and I'd love to see it implemented, but IMHO it won't help with the error. Having some amount of support for manifest exploration in bzzd (as part of the HTTP API) would help more, might just be good enough for basic listings.

An issue I foresee is that dapps uploading
might structure the manifest incorrectly. Built in support for pretty printing a manifest as a listing could help debug this and might be of value to users of such buggy applications ("I see your app is generating entries as foo/.bar, creating a broken link").

I remain convinced of my original suggestion for the error page: output `manifest at <hash> does not contain <path>`, with the hash being a link to a very basic listing of the manifest entries.

Again, sorry for derailing this issue to discuss the error page. The issue is actually about a bzzup feature, and the feature is a good idea

**Comment by zelig** [comment] 2016-12-06 21:44
@fjl are you aware of the swarm explorer (running under the terrible misnomer 'file manager'). that is exactly that. Mist could have an 'explore site' or 'sitemap' button that brings up the explorer dapp with the current manifest like in this scizzofrenic case browsing itself :)

http://swarm-gateways.net/bzz:/filemanager/#/3f9a163ede6952c87f5fd1df173e2571e1ba01d7fe4e4542b067eca0b432b658/

https://github.com/ethereum/swarm-dapps/tree/master/examples/filemanager

in general static listing is not scalable.
just magine the manifest for wikipedia.   you wanna list that and be user friendly wont work

the deign of swarm allows you to extend existing sites.
You can now write a browser dapp which displays as normal but offers explorer view or renders proper (branded) error pages

speaking of which lets start a convo on error messages and timouts and using go context.
@fjl i really want to use it, but havent fully grasped it

**Comment by jmozah** [comment] 2017-01-02 11:14
How about a "swarm --list <hash>" command which can list the directory and its manifest contents like filesystem "ls" command.

**Comment by zelig** [comment] 2017-01-10 06:11
@jmozah now that is a very good idea. I close this issue in favour of a new one explicitly on that 
#3540

**Closed by zelig** 2017-01-10 06:11 UTC
Labels: swarm
