### ISSUE TITLE
Rinkeby faucet offline for a couple of weeks

### ISSUE THREAD

**Issue by ccolorado** [ethereum/go-ethereum#24108] opened 2021-12-14 18:36 UTC
Have been monitoring the faucet for some test ether for a couple of weeks. Haven't seen the faucet online for a while now. 
Unfortunately we need a whole lot more than the 0.1 eth other faucets give away for our tests and deployments.

**Comment by holiman** [comment] 2021-12-15 08:49
Duplicate of #24049 (and probably a few more)

**Closed by holiman** 2021-12-15 08:49 UTC
Labels: type:bug

**Comment by ccolorado** [comment] 2021-12-15 15:31
Any word on when the rinkeby faucet be back online?

**Comment by speqtovijay** [comment] 2022-02-22 07:44
faucet server started but how start faucet web application with the goal of distributing small amounts of Ether in private and test networks please assisist me command?
