### ISSUE TITLE
Sync constantly crashes on raspberry pi 3 with geth 1.3.5

### ISSUE THREAD

**Issue by ericterpstra** [ethereum/go-ethereum#2332] opened 2016-03-14 01:16 UTC
Just set up a Raspberry Pi 3 with the latest Raspbian (Debian Jesse Feb 2016).

Compiled geth, and it will run for about an hour before crashing.  Here's what I could get from the most recent dump:

https://gist.github.com/ericterpstra/e81e7c4d11476214d34c

`go version go1.5.3 linux/arm`
geth 1.3.5

EDIT: I've also tried --fast and --cache "128".  Each gives the same result

**Comment by karalabe** [comment] 2016-03-14 08:58
Please send us the head of the crash log too. That contains the actual crash itself.

**Comment by ericterpstra** [comment] 2016-03-16 01:00
Unfortunately I do not have the head of that log, as I was only running geth in the console and not writing to a file. The gist is what was left in my console buffer.

I've tried to reproduce this a couple times today. Now it syncs for a little over an hour and simply freezes (no output like before).  I'll try a few more times to see if I can reproduce.

**Comment by emosto** [comment] 2016-03-25 16:49
I can confirm the exact same behavior that ericterpstra describes. Geth either freezes at sync time or crashes. Running from the console. At first possibility I will post the log as well.

pi@raspberrypi:~ $ geth version
Geth
Version: 1.3.5
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/local/go

**Comment by emosto** [comment] 2016-03-25 19:08
Please find attached a complete log of what happens on a raspberry pi 3, geth 1.3.5. I wanted to see if the switch --cache "128" will help, but it crashed again. I will try to collect log without the --cache "128" option if that helps you.

[geth-crash-raspberrypi3.txt](https://github.com/ethereum/go-ethereum/files/189930/geth-crash-raspberrypi3.txt)

**Comment by karalabe** [comment] 2016-03-25 19:10
Whoah, how did you build geth? Where gig you get the arm binaries from? This is some extremely funky error.

**Comment by fjl** [comment] 2016-03-25 19:13
This was fixed in Go 1.6. See https://github.com/golang/go/issues/13143.

**Comment by karalabe** [comment] 2016-03-25 19:13
Seems to be built using quite an old version of Go (1.5.1, we're at 1.6 already). There was a bug in Go that was supposedly fixed way back in december.

**Comment by fjl** [comment] 2016-03-25 19:15
The crash reported by @ericterpstra is likely something else, though, he is using go 1.5.3.

**Comment by emosto** [comment] 2016-03-25 19:16
I really didnt build it myself but followed the instructions here:

https://github.com/ethereum/wiki/wiki/Raspberry-Pi-instructions

and downloaded the pre-built binaries.
.

**Comment by karalabe** [comment] 2016-03-25 19:33
@tgerring Seems the arm build server's not running Go 1.6. I thought we've updated all of them. Could you double check?

**Comment by tgerring** [comment] 2016-03-25 22:17
Pinging @caktux

**Comment by caktux** [comment] 2016-03-27 02:54
Both the build server and PPA are still on 1.5.1, the former should be easy to update but the latter is a total pita, having to backport 1.6 from Xenial (which seems to have been moved to the golang-defaults package also) and requiring a 1.4.3 package for bootstraping. I'll be looking into it this week.

**Comment by karalabe** [comment] 2016-03-27 08:27
You only need a bootstrap installation if you build from source. Assuming
that's what you need, the bootstrap kit can be anything above 1.4.3 (i.e.
you can use the currently installed 1.5.1).

**Comment by darkikari** [comment] 2017-07-04 00:24
Hi, i re-open it because i have the same issue with Geth 1.6.6 (last one).... how can still happend? 

How can i help you to solve this issue?

Me it's appears after 2 - 5min of

 geth --fast --cache=512 console

**Comment by karalabe** [comment] 2017-07-04 06:20
@darkikari Please open a new issue and provide the details. Without a log there's no way to know what happened on your machine. Closing this issue as it's about 30 releases old now.

**Closed by karalabe** 2017-07-04 06:20 UTC
