### ISSUE TITLE
Rinkeby faucet not working

### ISSUE THREAD

**Issue by Ramarti** [ethereum/go-ethereum#17721] opened 2018-09-20 15:46 UTC
Hello there!

Visiting https://faucet.rinkeby.io/

This happens:
<img width="815" alt="captura de pantalla 2018-09-20 a las 17 45 24" src="https://user-images.githubusercontent.com/2632384/45830255-0a476900-bcfd-11e8-807c-020e9000d66d.png">

Previously the message was about not finding peers.

Cheers!

**Comment by ligi** [comment] 2018-09-20 20:42
thanks for reporting 
duplicate of #17596

**Closed by ligi** 2018-09-20 20:42 UTC

**Comment by alexandrabelzon** [comment] 2018-10-03 09:27
This is the most recent issue regarding the faucet and I couldn't find any further info.
Is the faucet still down? It seems to be stuck with new requests being added but none being processed. There's no error message though.
