### ISSUE TITLE
Getting events twice or more when subscribing using Watchxxxx methods

### ISSUE THREAD

**Issue by hhio618** [ethereum/go-ethereum#22576] opened 2021-03-25 20:51 UTC
#### System information
Geth version: `1.10.1-stable`
OS & Version: GNU/Linux

#### Expected behaviour
Not getting same NewChallenge event twice or more!

#### Actual behaviour
When subscribing to [Tellor oracle](https://rinkeby.etherscan.io/address/0x88df592f8eb5d7bd38bfef7deb0fbc02cf3778a0) events, sometimes we received same NewChallenge event twice or more even if there is no duplicate event in the oracle.

#### Steps to reproduce the behaviour
Snippet to reproduce:
```
package main

import (
	"bytes"
	"fmt"
	"log"
	"time"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/event"
	"github.com/pkg/errors"
	"github.com/tellor-io/telliot/pkg/contracts/tellor"
)

func main() {
	client, err := ethclient.Dial("...........")
	if err != nil {
		log.Fatal(err)
	}

	// Subscribe and wait until the context cancellation event.
	var sink chan *tellor.ITellorNewChallenge
	var sub event.Subscription
	var challenge *tellor.ITellorNewChallenge
	for {
		select {
		case err := <-sub.Err():
			if err != nil {
				fmt.Printf("subscription error: %v", err)
			}
			// Trying to resubscribe until it succeeds.
			for {
				sink, sub, err = getNewChallengeChannel(client)
				if err != nil {
					fmt.Printf("re-subscribing to NewChallenge events failed")
					time.Sleep(1 * time.Second)
					continue
				}
				break
			}
			fmt.Println("re-subscribed to NewChallenge events")
		case newChallenge := <-sink:
			if challenge != nil && bytes.Equal(challenge.CurrentChallenge[:], newChallenge.CurrentChallenge[:]) {
				fmt.Printf("same challenge received twice")
			}
                        challenge = newChallenge
		}
	}
}

func getNewChallengeChannel(client *ethclient.Client) (chan *tellor.ITellorNewChallenge, event.Subscription, error) {
	sink := make(chan *tellor.ITellorNewChallenge)
	var tellorFilterer *tellor.ITellorFilterer
	tellorFilterer, err := tellor.NewITellorFilterer(common.HexToAddress("0x88df592f8eb5d7bd38bfef7deb0fbc02cf3778a0"), client)
	if err != nil {
		return nil, nil, errors.Wrap(err, "getting ITellorFilterer instance")
	}
	sub, err := tellorFilterer.WatchNewChallenge(&bind.WatchOpts{}, sink, nil)
	if err != nil {
		return nil, nil, errors.Wrap(err, "getting NewChallenge channel")
	}
	return sink, sub, nil
}
```
cc @krasi-georgiev

**Comment by MariusVanDerWijden** [comment] 2021-03-26 14:03
The problem with events  is that in the case of a reorg, two events can be fired. 
E.g. if the transaction is included in a block, which later gets reorged and the transaction is included again in the next block.
Then two events are (rightfully so) fired. It is up to the user to deduplicate these events as we can't really un-send the event once we pushed it out. To be safe, you need to wait for multiple blocks anyway until you can be sure that the event happened. 
If you experience multiple events even if no reorg happened, then something is wrong on our side that we need to fix.
Can you check if the multiple events coincide with reorgs?

**Comment by krasi-georgiev** [comment] 2021-03-26 14:29
Waiting for multiple blocks sound a reasonable solution. 

How would that look like in code?

**Comment by krasi-georgiev** [comment] 2021-03-27 23:51
I did a bit more reading and testing and can confirm that this is due to reorg.
Added some code to use the event only when the tx that emitted the event is confirmed and it all now looks great.

@hhio618 you can close it.

**Comment by hhio618** [comment] 2021-03-28 18:07
Thanks @MariusVanDerWijden @krasi-georgiev.

**Closed** 2021-03-28 18:07 UTC
Labels: type:bug
