### ISSUE TITLE
Is it possible to get the event logs when using eth_call?

### ISSUE THREAD

**Issue by or2008** [ethereum/go-ethereum#20694] opened 2020-02-19 13:43 UTC
Hi there,

I wonder if there is a way to run a local transaction using eth_call, and besides the return value, get the full event logs or debug trace?

**Comment by adamschmideg** [comment] 2020-07-09 08:12
It's not supported for various reasons. What's the problem you're trying to solve? So maybe we could suggest an alternative approach.

**Comment by or2008** [comment] 2020-07-09 10:04
@adamschmideg parity has a feature called trace_call, it basically allows you to send a custom transaction (not necessarily mined one), execute it without affecting the state, and return the output, call stack etc..
https://openethereum.github.io/wiki/JSONRPC-trace-module

I wonder if Geth has a similar ability, I saw the 'debug_traceTransaction' but unfortunately, it can trace only mined transactions.

**Comment by coinwalletdev** [comment] 2020-07-27 08:37
Seems like a duplicate of https://github.com/ethereum/go-ethereum/issues/20515 to me

**Comment by karalabe** [comment] 2020-08-20 08:29
Retrieving the logs is fairly simple, the issue is that eth_call is specced to return only a binary blob and we can't add the logs in there without breaking the API. However, extending tracing for custom calls is a completely valid request and @MariusVanDerWijden was alreayd working on it. Wrt call stack, you can already do that if you specify `{tracer: 'callTracer'}` as a second argument to a trace method.

**Closed by karalabe** 2020-08-20 08:29 UTC
Labels: status:triage
