### ISSUE TITLE
geth out of memory

### ISSUE THREAD

**Issue by FantomJoker** [ethereum/go-ethereum#21278] opened 2020-06-30 14:55 UTC
Geth killed because of out of memory;
````
[1276584.844268] Out of memory: Kill process 13181 (geth) score 772 or sacrifice child
[1276584.844943] Killed process 13181 (geth) total-vm:8796292kB, anon-rss:6144964kB, file-rss:0kB, shmem-rss:0kB
````
Appears when multiple transfer requests are initiated. About 20 transfer requests at the same time.
In the beginning, when this problem occurs with geth1.9.11, then I use geth1.9.15 instead.
The problem remains unsolved. 
Even occurs after trying to use 16g of memory.
Has anyone been in the same situation?

This is the log, I replaced the address.
````
INFO [06-30|17:38:59.816] Setting new local account                address=0x.....
INFO [06-30|17:38:59.817] Submitted transaction                    fullhash=0x..... recipient=0x....
INFO [06-30|17:39:00.671] Setting new local account                address=0x....
INFO [06-30|17:39:00.672] Submitted transaction                    fullhash=0x.... recipient=0x...
INFO [06-30|17:39:01.520] Setting new local account                address=0x....
INFO [06-30|17:39:01.521] Submitted transaction                    fullhash=0x.... recipient=0x...
INFO [06-30|17:39:02.373] Setting new local account                address=0x....
INFO [06-30|17:39:02.374] Submitted transaction                    fullhash=0x.... recipient=0x...
INFO [06-30|17:44:42.947] Starting Geth on Ethereum mainnet... 
INFO [06-30|17:44:42.950] Maximum peer count                       ETH=70 LES=0 total=70
WARN [06-30|17:44:42.950] The flag --rpc is deprecated and will be removed in the future, please use --http 
WARN [06-30|17:44:42.951] The flag --rpcaddr is deprecated and will be removed in the future, please use --http.addr 
WARN [06-30|17:44:42.951] The flag --rpcport is deprecated and will be removed in the future, please use --http.port 
WARN [06-30|17:44:42.951] The flag --rpcapi is deprecated and will be removed in the future, please use --http.api 
````

#### command
geth --maxpeers 70 --cache 1024 --txpool.globalslots 1024 --syncmode fast --datadir /home/.ethereum -rpcapi debug,txpool,admin,net,personal,eth,web3 --rpc --rpcport 8549 --rpcaddr 127.0.0.1 --allow-insecure-unlock

#### System information

Geth version: `v1.9.15-stable-0f77f34b`
OS & Version: `Linux version 3.10.0-693.2.2.el7.x86_64`
Ram: 8g

**Comment by rjl493456442** [comment] 2020-07-02 07:30
> About 20 transfer requests at the same time.

Do you mean that you are sending the transactions with TPS as 20?

**Comment by karalabe** [comment] 2020-07-02 07:37
If you are using personal_sendTransaction (where you supply the password too), then each call will decrypt the private key individually (security). Decrypting the private key is explicitly made CPU intensive and memory hard, so it takes about 1 second and 256MB RAM / decrypt. With 20 concurrent sends, that's 5GB RAM just for the barebone decryption.

That said, you are also running with `--allow-insecure-unlock`, so you are perhaps unlocking once and then doing eth_sendTransaction? That shouldn't take any memory at all. (mind you, please take care with that flag/unlock to avoid someone else accessing your node via RPC, otherwise they could access your funds).

Could you provide some more details about your use case? Might help us pin point what might be off.

**Comment by FantomJoker** [comment] 2020-07-02 11:38
> Could you provide some more details about your use case? Might help us pin point what might be off.

This is an operation to aggregate the balances of multiple addresses into a single address;
Using java `org.web3j.core 4.2.0` access wallet;

A single transfer will be executed to the following wallet operations:
````
personal_unlockAccount
eth_gasPrice
eth_getTransactionCount
eth_sendTransaction
````
The content of the transfer is usdt token contract transaction;
This process uses the for loop to execute the transfer without any interval;

This problem has not occurred before using geth's light mode; The fast mode appears later.
It is not inevitable OOM, but it usually appears after running for 2-3 days;
Before operation, geth takes up about 4G of memory.

**Comment by FantomJoker** [comment] 2020-07-02 11:40
> > About 20 transfer requests at the same time.
> 
> Do you mean that you are sending the transactions with TPS as 20?

This process uses the for loop to execute the transfer without any interval;

**Comment by rjl493456442** [comment] 2020-07-03 11:30
We have merged one PR for fixing one issue in the txpool. Perhaps this issue is relevant. 

Maybe you can try the next release to see whether the issue is resolved.

**Comment by adamschmideg** [comment] 2020-08-26 10:49
I assume this issue is resolved. If you have this problem again, please open a new issue.

**Closed by adamschmideg** 2020-08-26 10:49 UTC
Labels: need:check-with-current-version
