### ISSUE TITLE
Invalid hex number error for valid address

### ISSUE THREAD

**Issue by MrHash** [ethereum/go-ethereum#14682] opened 2017-06-22 22:25 UTC
#### System information

Geth version: 1.6.5-stable
OS & Version: OSX

#### Expected behaviour
Transaction is sent when receiver address is "0x088e62f69884781eb458e64b8d4e24c08a6ed9b5"

#### Actual behaviour
Transaction fails with:
`Error: invalid argument 0: hex number has leading zero digits after 0x`

#### Steps to reproduce the behaviour
...
var receiver = "0x088e62f69884781eb458e64b8d4e24c08a6ed9b5"
eth.sendTransaction({from:sender, to:receiver, value:amount, gas:limit, gasPrice:price});

#### Backtrace

````
Error: invalid argument 0: hex number has leading zero digits after 0x
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
````

**Comment by karalabe** [comment] 2017-06-23 07:47
@fjl ping

**Comment by fjl** [comment] 2017-06-23 08:08
The issue is related to "gas", "gasPrice" or "value" field.

**Comment by MrHash** [comment] 2017-06-23 10:39
These were my values copied direct from the console.
```
> sender
"0x914ef49db7caf5e4683e671cb6caf96db73bb93b"
> receiver
"0x088e62f69884781eb458e64b8d4e24c08a6ed9b5"
> amount
"0.859867396"
> limit
"21000"
> price
"25000000000"
> eth.sendTransaction({from:sender, to:receiver, value:amount, gas:limit, gasPrice:price});
Error: invalid argument 0: hex number has leading zero digits after 0x
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
```

I tried sending again today to the `0x0...` address with a restarted console and different values and it worked. Strange.

**Comment by karalabe** [comment] 2017-06-23 10:41
I'm unsure about the amount being a fractional number. I though it must be an int in Wei. Perhaps that could have been the issue?

**Comment by MrHash** [comment] 2017-06-23 12:42
Yeh must be the amount not being an int. But in any case the error was misleading.

**Comment by inlinechan** [comment] 2017-07-06 06:39
FYI, here is error message from master

```
eth.sendTransaction({from: eth.coinbase, to: "0x0166be393b7ded951d9c171d1241312a588014d2", value: "0.85"});
Error: invalid argument 0: json: cannot unmarshal hex number with leading zero digits into Go struct field SendTxArgs.value of type *hexutil.Big
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:11
```

**Comment by fjl** [comment] 2017-08-08 11:34
Closing because the error message is improved now.

**Closed by fjl** 2017-08-08 11:34 UTC

**Comment by SCBuergel** [comment] 2017-08-11 10:39
Just leaving a note here cause I ran into this on an old machine: `value` should be an integer (in Wei) and not a fraction of an Ether.

**Comment by TechnoFer** [comment] 2018-03-12 08:26
invalid argument 0: json: cannot unmarshal hex number with leading zero digits into Go struct field CallArgs.value of type *hexutil.Big

**Comment by caochao** [comment] 2018-06-19 06:20
cannot unmarshal hex number with leading zero digits into Go struct field CallArgs.gas of type hexutil.Uint64   
what is this

**Comment by karalabe** [comment] 2018-06-19 12:00
Don't pass number arguments with leading zero digits.
