### ISSUE TITLE
How to sign array with eip712 

### ISSUE THREAD

**Issue by macchain** [ethereum/go-ethereum#23335] opened 2021-08-05 09:25 UTC
```
var Types = core.Types{
    "EIP712Domain": {
        {
            Name: "name",
            Type: "string",
        },
        {
            Name: "version",
            Type: "string",
        },
        {
            Name: "chainId",
            Type: "uint256",
        },
        {
            Name: "verifyingContract",
            Type: "address",
        },
    },
    "Claim": {
        {
            Name: "users",
            Type: "address[]",
        },
        {
            Name: "amounts",
            Type: "uint256[]",
        },
        {
            Name: "user",
            Type: "address",
        },
        {
            Name: "nonce",
            Type: "uint256",
        },
        {
            Name: "deadline",
            Type: "uint256",
        },

    },

}



func Sign(key *ecdsa.PrivateKey, data *core.TypedData) (hexutil.Bytes, error) {
    domainSeparator, err := data.HashStruct("EIP712Domain", data.Domain.Map())
    if err != nil {
        return nil, err
    }
    typedDataHash, err := data.HashStruct(data.PrimaryType, data.Message)
    if err != nil {
        return nil, err
    }
    rawData := []byte(fmt.Sprintf("\x19\x01%s%s", string(domainSeparator), string(typedDataHash)))
    dataHash := crypto.Keccak256(rawData)

    signature, err := crypto.Sign(dataHash, key)
    if err != nil {
        return nil, err
    }

    if signature[64] < 27 {
        signature[64] += 27
    }

    return signature, nil
}


type Message struct {
    Users []string
    Amounts []string
    User string
    Nonce string
    Deadline string
}


    contents := utils.Message{
        Users: []string {"0x111da67948Ef5Ed1f82D707B8cd7e3B1DFa87AEa"},
        Amounts:  []string{"1"},
        User:     address,
        Nonce:    nonce,
        Deadline: strconv.Itoa(int(duration)),
    }
```
set value with utils.Message,When I run it, report `data '[0x111da67948Ef5Ed1f82D707B8cd7e3B1DFa87AEa]' doesn't match type 'address[]`,How can I modify the code?

**Comment by MariusVanDerWijden** [comment] 2021-08-16 07:19
From another issue:
`eth_signTypedData` was proposed in EIP-712 (https://eips.ethereum.org/EIPS/eip-712) But it was never really adopted by anyone, so we don't have it in go-ethereum either. We have eth_sign to sign arbitrary data with the ethereum prefix.
I don't think we should implement 712 given that almost no one is using it.

Basically EIP-712 is not implemented in geth.

Will close as a duplicate of https://github.com/ethereum/go-ethereum/issues/23348

**Comment by MariusVanDerWijden** [comment] 2021-08-16 07:34
I don't know where you get the `utils,Message` type from. Your `Sign` function looks okay to me, 
The error you get is because the data you provide is not the type you specified in types. There you specified `[]common.Address` but you provided a `[]string` You need to convert the address from sting to address type, e.g. `Users: []common.Address{ common.HexToAddress("0x111da67948Ef5Ed1f82D707B8cd7e3B1DFa87AEa") }`

**Closed by MariusVanDerWijden** 2021-08-16 07:34 UTC
Labels: type:docs
