### ISSUE TITLE
24h no syncro no found waiting for block; i love this project but ... help pls : )

### ISSUE THREAD

**Issue by andres1968** [ethereum/go-ethereum#14400] opened 2017-05-02 09:21 UTC
#### System information

Geth version: `geth version
![siempreasi1](https://cloud.githubusercontent.com/assets/28282284/25611777/a6977b4c-2f28-11e7-8754-5c8389fe38f9.jpeg)
![siempreasi2](https://cloud.githubusercontent.com/assets/28282284/25611790/b07650ac-2f28-11e7-9127-ef70296b3b63.jpeg)

macOSSierra

https://etherscan.io/address/0xafa3cab838307e88989574e48e0aa85f6251aef6

`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment] 2017-05-03 07:11
Please provide some logs from Geth. We have no way to know what's happening looking at a UI screenshot from mist.

**Comment by andres1968** [comment] 2017-05-03 11:39
!Thank you very much for answering!

[nodelog.pdf](https://github.com/ethereum/go-ethereum/files/973137/nodelog.pdf)

**Comment by karalabe** [comment] 2017-05-03 12:33
It does seem to work based on the logs. I'm guessing you have an HDD right? Ethereum is a bit heavy on HDDs at the moment, so such machines will need quite a bit of time to sync up.

**Comment by andres1968** [comment] 2017-05-03 13:16
Version: `0.8.9` Mist
OS & Version: macOS Sierra 10.12.4
Node type: `G eth 1.6.0 (Go)`

[node.log.actual.pdf](https://github.com/ethereum/go-ethereum/files/973366/node.log.actual.pdf)

-1,956,323 block left 3 peers 

it work : )  

I go two hours to play the violin ... I'll inform on back. 

thank you very much

**Comment by andres1968** [comment] 2017-05-03 15:18
-659,223 blocks left

**Comment by andres1968** [comment] 2017-05-03 15:51
-73 blocks left

**Comment by karalabe** [comment] 2017-05-04 14:39
Where does it stand now? It needs to import about 3.65M blocks.

**Comment by andres1968** [comment] 2017-05-04 14:47
-3,453,501 blocks left, 10 peers, 5%

**Comment by andres1968** [comment] 2017-05-04 17:57
Wednesday at 15.30 began to run fast and reached 99%, but stayed for 30 seconds and started to synchronize.
(Thanks for the support! We're going to solve it!)

**Comment by karalabe** [comment] 2017-05-04 21:44
I'm really curious about the logs around when it restarted from 0. That's the interesting question as to what happened there. Also how fast is your internet connection?

**Comment by andres1968** [comment] 2017-05-04 22:29
[nodelog 5 may.pdf](https://github.com/ethereum/go-ethereum/files/977692/nodelog.5.may.pdf)

![test fast1](https://cloud.githubusercontent.com/assets/28282284/25727379/362c9254-3129-11e7-9259-621ad0a9e011.jpeg)

![fastest2](https://cloud.githubusercontent.com/assets/28282284/25727382/3db4bb46-3129-11e7-9124-3a3dd3c131ff.jpeg)

(if you need more info, here I am)

**Comment by karalabe** [comment] 2017-05-09 12:23
Found the issue. It's a regression from https://github.com/ethereum/go-ethereum/commit/f1069a30b9ca13769ace154ff25dfabc83f25485 which made some part of the downloader block on database IO. This causes the queue to block and a separate goroutine drop peers for "being unresponsive".

**Comment by karalabe** [comment] 2017-05-09 12:37
Fixed in https://github.com/ethereum/go-ethereum/pull/14449

**Comment by andres1968** [comment] 2017-05-10 21:52
I got, thanks to the tips of @karalabe, sync mist using geth

geth --light --cache=1024

¡hasta la próxima!

**Comment by fjl** [comment] 2017-05-13 00:54
We have a few issues about sync right now, closing this one because there is nothing new here.

**Closed by fjl** 2017-05-13 00:54 UTC
