### ISSUE TITLE
Nodes can't be added as peers when node are running in different physical machine

### ISSUE THREAD

**Issue by 0xadeeb** [ethereum/go-ethereum#27061] opened 2023-04-07 06:35 UTC
#### System information

Geth version: 
```
Version: 1.10.26-stable
Architecture: amd64
Go Version: go1.19.3
Operating System: linux
```
OS & Version: Linux, NixOS 22.04

#### Expected behavior
I expect the 2 nodes to connect and when I query `admin.peers` in any of the nodes using `geth attach` I expect to see the details of other node. This works exactly like this when I have both my nodes in 2 virtual machines.

#### Actual behavior
In 2 physical machines in a LAN, eventhough `geth attach` cli gives output **true**, when I query `admin.peers` in any of the nodes i get the result `[]`. I've checked if one machine is reachable from other machine using the commands `ping` and `telnet` so it does seem to be the problem the network.

#### Steps to reproduce the behavior
First I created a new directory called `node` and in there I created 5 new accounts using `geth` using this command
```
for i in {0..5} do
  geth --datadir . account new --password ./pass{i}.txt
done
```
I've created 2 geth nodes in 2 different physical machines which are connected to the same LAN using this genesis block
```
{
  "config": {
    "chainId": 5777,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "clique": {
      "period": 0,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x63eca70b",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000265066c91b13ccab6d727df2ece1f76478978ddc0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b76000",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "1113c673dd46a047374ce90dd73e3bbc2d80d515": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "265066c91b13ccab6d727df2ece1f76478978ddc": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "a3cb5baef5659afaaac6945ef2fdb80ab06f8076": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "b1e7ca3709f963382117965f38ee25b90b95f5ce": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "c9b51df0896e49a7ad19581cba2ff8d5132583fc": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "baseFeePerGas": null
}
```
Inside node directory I initialized the blockchain using the command `geth init --datadir . supplychain.json`. 
After the setup this is the directory structure of node directory in both the machines
```
node
├── accounts
│  ├── passwords
│  │  ├── pass0.txt
│  │  ├── pass1.txt
│  │  ├── pass2.txt
│  │  ├── pass3.txt
│  │  └── pass4.txt
│  ├── pub_keys
│  │  ├── pubKey0.txt
│  │  ├── pubKey1.txt
│  │  ├── pubKey2.txt
│  │  ├── pubKey3.txt
│  │  └── pubKey4.txt
│  └── details.txt
├── geth
│ 
.
.
.
├── keystore
.
. private key of 5 accounts
.
├── .gitignore
├── Dockerfile
├── run ( script to run the node)
├── shell.nix
└── supplychain.json (genesis block)
```
I wanted to setup 2 nodes in which one of them is a miner and other is not. Node 1 - miner, Node 2 - not miner
In machine one I ran the command
```
#!/usr/bin/env sh
geth --datadir . --networkid 5777 --mine --http --http.addr "localhost" --http.port "8545" --http.api "web3,eth,miner,personal,net" --http.corsdomain "*" --nat "none" --unlock 0x265066C91B13cCAb6D727Df2ece1F76478978Ddc --password "accounts/passwords/pass0.txt" --ipcpath "~/.ethereum/geth.ipc" --netrestrict "192.168.1.0/24" --allow-insecure-unlock --verbosity 4
```
and in machine 2 I used this command to run the node

```
#!/usr/bin/env sh
geth --datadir . --networkid 5777  --http --http.addr "localhost" --http.port "8545" --http.api "web3,eth,miner,personal,net" --http.corsdomain "*" --nat "none" --ipcpath "~/.ethereum/geth.ipc" --netrestrict "192.168.1.0/24" --allow-insecure-unlock --verbosity 4
```
Now I opened another terminal in machine one and I ran `geth attach` and from there I got node 1's enode value using `admin.nodeInfo.enode` and I get it's ip address using `ifconfig` commnad
After this I go to machine 2, open a new terminal and ran `geth attach` and ran `admin.addPeers("enode://f8c3219c5aeab5f9ca31cfaaf0bdf9d646bdb9d179b27591f859f6b706da08034d23a19eec8c25a5ef62bd89e437ea6695645001414ff5e87220c8827a63403d@192.168.1.39:30303")` which gives the output **true** in CLI.

#### Backtrace
This is the logs while starting the node
````
INFO [04-07|12:04:01.956]  
INFO [04-07|12:04:01.958] Initialising Ethereum protocol           network=5777 dbversion=8
INFO [04-07|12:04:01.982] Loaded most recent local header          number=35 hash=fc463e..c7495f td=71 age=1mo2w6d
INFO [04-07|12:04:01.982] Loaded most recent local full block      number=35 hash=fc463e..c7495f td=71 age=1mo2w6d
INFO [04-07|12:04:01.982] Loaded most recent local fast block      number=35 hash=fc463e..c7495f td=71 age=1mo2w6d
DEBUG[04-07|12:04:01.995] Reinjecting stale transactions           count=0
INFO [04-07|12:04:01.996] Loaded local transaction journal         transactions=0 dropped=0
INFO [04-07|12:04:01.996] Regenerated local transaction journal    transactions=0 accounts=0
WARN [04-07|12:04:01.997] Switch sync mode from snap sync to full sync 
INFO [04-07|12:04:01.997] Gasprice oracle is ignoring threshold set threshold=2
WARN [04-07|12:04:01.998] Engine API enabled                       protocol=eth
WARN [04-07|12:04:01.998] Engine API started but chain not configured for merge yet 
INFO [04-07|12:04:01.998] Starting peer-to-peer node               instance=Geth/v1.10.26-stable/linux-amd64/go1.19.3
DEBUG[04-07|12:04:02.331] UDP listener up                          addr=[::]:30303
DEBUG[04-07|12:04:02.331] TCP listener up                          addr=[::]:30303
INFO [04-07|12:04:02.373] New local node record                    seq=1,676,453,745,396 id=db6031f3662acc3a ip=127.0.0.1 udp=30303 tcp=30303
INFO [04-07|12:04:02.375] Started P2P networking                   self=enode://f8c3219c5aeab5f9ca31cfaaf0bdf9d646bdb9d179b27591f859f6b706da08034d23a19eec8c25a5ef62bd89e437ea6695645001414ff5e87220c8827a63403d@127.0.0.1:30303
DEBUG[04-07|12:04:02.378] IPCs registered                          namespaces=admin,debug,web3,eth,txpool,personal,clique,miner,net,engine
INFO [04-07|12:04:02.378] IPC endpoint opened                      url=/home/adeeb/.ethereum/geth.ipc
INFO [04-07|12:04:02.379] Loaded JWT secret file                   path=/home/adeeb/node/geth/jwtsecret crc32=0xf9613d50
DEBUG[04-07|12:04:02.380] Allowed origin(s) for WS RPC interface [localhost] 
INFO [04-07|12:04:02.380] HTTP server started                      endpoint=127.0.0.1:8545 auth=false prefix= cors=* vhosts=localhost
INFO [04-07|12:04:02.381] WebSocket enabled                        url=ws://127.0.0.1:8551
INFO [04-07|12:04:02.381] HTTP server started                      endpoint=127.0.0.1:8551 auth=true  prefix= cors=localhost vhosts=localhost
INFO [04-07|12:04:03.654] Unlocked account                         address=0x265066C91B13cCAb6D727Df2ece1F76478978Ddc
INFO [04-07|12:04:03.654] Transaction pool price threshold updated price=0
INFO [04-07|12:04:03.654] Updated mining threads                   threads=0
INFO [04-07|12:04:03.654] Transaction pool price threshold updated price=1,000,000,000
INFO [04-07|12:04:03.654] Etherbase automatically configured       address=0x265066C91B13cCAb6D727Df2ece1F76478978Ddc
INFO [04-07|12:04:03.654] Commit new sealing work                  number=36 sealhash=613046..1d2774 uncles=0 txs=0 gas=0 fees=0 elapsed="110.004µs"
WARN [04-07|12:04:03.654] Block sealing failed                     err="sealing paused while waiting for transactions"
INFO [04-07|12:04:03.654] Commit new sealing work                  number=36 sealhash=613046..1d2774 uncles=0 txs=0 gas=0 fees=0 elapsed="265.593µs"
DEBUG[04-07|12:04:11.618] Revalidated node                         b=12 id=d34b942e0a9f32f5 checks=1
INFO [04-07|12:04:13.370] Looking for peers                        peercount=0 tried=0 static=0
DEBUG[04-07|12:04:18.425] Revalidated node                         b=13 id=cb0040bc0bb65afd checks=1
````

**Comment by jsvisa** [comment] 2023-04-10 15:50
Seems you have set not restrict, are the two nodes on the same subnet(CIDR)?

> --netrestrict "192.168.1.0/24"

**Comment by jsvisa** [comment] 2023-04-11 01:48
Sorry, I can't reproduce this issue in my env. BTW, maybe you can check both the tcp/udp port 30303 on both nodes were dual-connected, eg:

```sh
root@n0:~# nc -vz 192.168.122.21 30303
Connection to 192.168.122.21 30303 port [tcp/*] succeeded!
root@n0:~#
root@n0:~# nc -vz -u 192.168.122.21 30303
Connection to 192.168.122.21 30303 port [udp/*] succeeded!
```

**Comment by 0xadeeb** [comment] 2023-04-11 09:52
> maybe you can check both the tcp/udp port 30303 on both nodes were dual-connected

I've used `nc` and both the machines can connect to each other 
Machine 1 to Machine 2
```
➜ nc -vz 192.168.1.45 30303
Connection to 192.168.1.45 30303 port [tcp/*] succeeded!
➜ nc -vz -u 192.168.1.45 30303
Connection to 192.168.1.45 30303 port [udp/*] succeeded!
```
Machine 2 to machine 1
```
node@node:~/node$ nc -vz 192.168.1.39 30303
Connection to 192.168.1.39 30303 port [tcp/*] succeeded!
node@node:~/node$ nc -vz -u 192.168.1.39 30303
Connection to 192.168.1.39 30303 port [udp/*] succeeded!
```
So that doesn't seem to be the reason.
> I can't reproduce this issue in my env

Would you need more information to reproduce this issue?
Basically I just want multiple nodes running (initialized using the same genesis block) in different physical machines to be connected. So if there is some other better (or standard) way to do it please let me know.

**Comment by holiman** [comment] 2023-04-26 13:43
Try bumping the verbosity to `5` (and perhaps log to file), and then try to do the peering.

**Comment by holiman** [comment] 2023-12-04 15:43
Seems abandoned by reporter. Closing

**Closed by holiman** 2023-12-04 15:43 UTC
Labels: type:bug
