### ISSUE TITLE
Not enough light peers available on the network

### ISSUE THREAD

**Issue by c0deright** [ethereum/go-ethereum#15454] opened 2017-11-10 10:00 UTC
#### System information

Geth version:
```
Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9
```
OS & Version: Ubuntu 16.04 Xenial LTS

#### Command line

`geth --cache 512 --syncmode light --rpc --rpcaddr 0.0.0.0 --rpcapi "eth,net,web3" --maxpeers 60 --verbosity 3`

#### Expected behaviour
geth being connected to at least a handful of peers and importing/syncing

#### Actual behaviour
geth javascript console (`geth attach`) often reports an empty result set for command `admin.peers` indicating that geth isn't connected to any peers at all.
Even when syncing geth is connected to only 1 peer.

#### Steps to reproduce the behaviour
Start geth on Ubuntu Linux with the command mentioned above and then run `admin.peers` in `geth attach` periodically.

**Comment by sgehrman** [comment] 2017-11-14 21:42
had the same problem, I have been unable to do any Eth dev since testnet sync is so slow I have never gotten the full chain after days of letting it run.  Light mode has no peers.  I'm a noob and can't even get past step one.  Anyone have suggestions?

**Comment by KainniaK** [comment] 2017-12-16 03:40
Can we please get a fix for this? Is it to much to ask to use a application based ethereum wallet? I don't want an online wallet and I don't always have internet acces. I want my laptop to sync to the network in light mode when I go online, right now this just does not work properly. FIX THIS PLEASE!!!!!!

**Comment by lmars** [comment] 2017-12-16 22:35
FYI I am running a few light servers at my own expense, and my nodes get saturated with light client peer connections. The "fix" here is more people in the community running nodes and enabling the light server (see [here](https://ethereum.stackexchange.com/questions/11014/how-to-run-a-server-for-light-clients)), please consider helping the cause and running a light server too :smile:.

**Comment by heikomat** [comment] 2017-12-16 23:21
@lmars i read about the issue on reddit today and started a light server on my vps that was otherwise idling. I'm however not sure what good values for `maxpeers` and `lightpeers` are. i currently have set them to `300` and `270` respectively. could i go higher? should i go lower? (i have 6 cores and 30 GB ram available)

**Comment by alexksso** [comment] 2017-12-17 04:53
@heikomat thanks! I just started up a light node - it still hasn't found your server as a peer. Is there a way to specify a set of bootstrap nodes?
 It looks like it's taking forever for the node to crawl the nodes and find one that runs with --lightserv .... 
all the nodes I locate are reported "invalid neighbour" which I guess means they are not LES 
(Making it default in the next release would be the way to go to increase mechanically the density of LES nodes)

**Comment by heikomat** [comment] 2017-12-17 10:37
@alexksso i don't think you can specify bootstrap-nodes without recompiling geth. You can however manualy add peers in the geth console, see [here](https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network#static-nodes)

I'm trying to test how many peers i can handle, so i set `maxpeers` to 1000 and `lightpeers` to 900. currently about 600 peers are connected. This is the node, if you want to try `admin.addPeer`: https://www.ethernodes.org/node/54d90cfae24d462e42f2aa3babed3022cdce7ba03a0e5c554dc1c31329f94c5fc050d8129395b4cbf7925ecd6bdede54af27d7e7c84bd3f93355f1a0ca945dd4

**Comment by alexksso** [comment] 2017-12-17 19:00
@heikomat I tried and let it run for a while but it never connected - is there a latency constraint (you being in Germany and me on the West Coast? )

**Comment by alexksso** [comment] 2017-12-17 23:59
@heikomat funny I just did it again and it worked - did you change anything ?

**Comment by heikomat** [comment] 2017-12-18 06:22
@alexksso i didn't change anything. A couple less peers were connected she you wrote that it worked. Maybe I can't have more than about 650-700 connections at once for some reason.

**Comment by GoodMirek** [comment] 2018-01-13 17:02
I would love to help addressing this issue #15454 with my cloud node, but there are various issues while trying to run full node in fast mode and serving light peers. E.g. issue #15689 is known for four weeks already and still not fixed, it seems geth lacks developing/testing resources, even though getting a lot of consumer attention. I am happy to help with testing, please let me know if I can provide more info.

**Comment by UGatgithub** [comment] 2018-01-20 14:21
Also with geth 1.8.0 beta waiting for peers forever ...

**Comment by AndreyPatseiko** [comment] 2018-03-02 13:47
When trying run geth  1.7.3-stable with this settings: geth --syncmode "light" --datadir "/.data" --rpc --rpcaddr "localhost" --rpcport "8545"
it just stopped and it don't do nothing!

**Comment by palasinio** [comment] 2018-04-17 15:43
Also with geth 1.8.2 waiting for peers forever ...

**Comment by c0deright** [comment] 2018-04-26 12:03
Restating geth in light mode takes a long time (minutes) to get connected to at least 1 peer. after more time has passed peer count is somewhat stable between 5 and 12. Since some days it's constantly above 10 peers.

**Comment by fjl** [comment] 2019-01-22 09:53
Sorry, closing this because the report isn't actionable. There is no single bug in geth that causes sync failures. We are aware that sync may sometimes fail for networking reasons.

**Closed by fjl** 2019-01-22 09:53 UTC
Labels: status:triage

**Comment by FrankSzendzielarz** [comment] 2019-01-22 09:57
@heikomat It is actually possible to specify the bootnode on the command line. You could actually run a lightserver and specify the bootnode on your light client. The scope of the task to increase the number of LES servers is very broad, and efforts are underway.
