### ISSUE TITLE
geth attach over SSL:certificate signed by unknown authority

### ISSUE THREAD

**Issue by dylanpoe** [ethereum/go-ethereum#18363] opened 2018-12-25 02:40 UTC
Hi,I configured a nginx proxy for one of my wss ,here is my nginx 
```
    upstream websocket {
	#ip_hash;
	server 127.0.0.1:443;  
       }
    server {
        listen       443 ssl http2 default_server;
        listen       [::]:443 ssl http2 default_server;
       server_name  ssl.eash.io;
        root         /usr/share/nginx/html;
         ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;	
	ssl_certificate      /etc/letsencrypt/live/ssl.eash.io/cert.pem; 
        ssl_certificate_key /etc/letsencrypt/live/ssl.eash.io/privkey.pem;
        include /etc/nginx/default.d/*.conf;
        location / {
 		proxy_set_header        Host $host;
    		proxy_http_version      1.1;
    		proxy_set_header        Upgrade $http_upgrade;
   		proxy_set_header        Connection "upgrade";
    		proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_set_header        X-Real-IP $remote_addr;
    		proxy_set_header        X-Forwarded-Proto $scheme;
    		proxy_pass              https://127.0.0.1:9647;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
```
,and when i try to connect ssl.eash.io ,it failed 
```
~/go-etherzero/build/bin/geth   attach https://ssl.eash.io/
Fatal: Failed to start the JavaScript console: api modules: Post https://ssl.eash.io/: x509: certificate signed by unknown authority
```
,my crt is encrypted by https://letsencrypt.org ,my geth is 1.8.17

**Comment by holiman** [comment] 2019-06-19 19:13
This is pretty interesting. Your cert has expired, 
```
[user@work go-ethereum]$ build/bin/geth attach https://ssl.eash.io/
INFO [06-19|21:11:34.051] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [06-19|21:11:34.051] Sanitizing cache to Go's GC limits       provided=4096 updated=2571
Fatal: Failed to start the JavaScript console: api modules: Post https://ssl.eash.io/: x509: certificate has expired or is not yet valid
```

I tried some other ones
```
[user@work go-ethereum]$ build/bin/geth attach https://github.com/go-ethereum
INFO [06-19|21:08:06.594] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [06-19|21:08:06.594] Sanitizing cache to Go's GC limits       provided=4096 updated=2571
Fatal: Failed to start the JavaScript console: api modules: 422 Unprocessable Entity <!DOCTYPE html>
<html>
  <head>
... the entire page
```

```
[user@work go-ethereum]$ build/bin/geth attach https://letsencrypt.org
INFO [06-19|21:10:01.524] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [06-19|21:10:01.524] Sanitizing cache to Go's GC limits       provided=4096 updated=2571
Fatal: Failed to start the JavaScript console: api modules: 403 Forbidden <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;letsencrypt&#46;org&#47;" on this server.<P>
Reference&#32;&#35;18&#46;4ebe7a5c&#46;1560971402&#46;5968bf20
</BODY>
</HTML>
```

It may have been fixed. Early on, letsencrypt was maybe not supported as a CA in your setup -- and I'm not sure if that's a golang-specific CA-store, or if it uses your local OS trusted CA store or something else. 

I'll close this, since I can't reproduce, but feel free to reopen if you see this again.

**Closed by holiman** 2019-06-19 19:13 UTC
