### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vpants** [ethereum/go-ethereum#18488] opened 2019-01-22 02:32 UTC
Hi there,
#### System information

Geth version: `1.8.19-stable-dae82f09`
OS & Version:  CentOS-7.5
Commit hash : (if `develop`)

#### Expected behaviour
the go-ethereum  do'not  throw the info about panic on runtime

#### Actual behaviour

```
INFO [01-20|12:25:18.288] Imported new chain segment               blocks=1  txs=155 mgas=7.996  elapsed=4.172s    mgasps=1.916   number=7096458 hash=26fc80…00b83f age=15m
3s  cache=214.24mB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51876e]

goroutine 5374090 [running]:
math/big.(*Int).Cmp(0xc058565d20, 0x0, 0xf0a9af180e0e0f58)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/math/big/int.go:319 +0x2e
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSidechain(0xc00a784000, 0xc0a97f1530, 0xc00003f5d0, 0xc00003f501, 0x1, 0x1, 0xc0306423c0, 0x1, 0x1, 0xc09ad4b5c0,
...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1328 +0x10b2
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc00a784000, 0xc01e05f050, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1134 +0x2e15
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc00a784000, 0xc01e05f050, 0x1, 0x1, 0x8, 0x8, 0xe03580)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1083 +0xb89
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func6(0xc01e05f050, 0x1, 0x1, 0x1e97701, 0xc098823170, 0x3459e398c6051c72)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/handler.go:180 +0x30b
github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).insert.func1(0xc000093860, 0x8750b5781db2e057, 0x3c4fbbe3b095198c, 0x3459e398c6051c72, 0x4466c34da7a2382f, 0xc07dc2b
9e0, 0xc0e58a69e0, 0x10)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:669 +0x53d
created by github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).insert
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:643 +0x2ad

```

**Comment by rjl493456442** [comment] 2019-01-22 04:39
The PR #18436 possibly fix this issue, you could upgrade your geth to latest version or you can wait for stable release.

**Comment by holiman** [comment] 2019-01-22 09:07
This is on an old version, and this error was fixed by https://github.com/ethereum/go-ethereum/pull/18436 . 
Duplicate of https://github.com/ethereum/go-ethereum/issues/18421 and https://github.com/ethereum/go-ethereum/issues/18388

**Closed by holiman** 2019-01-22 09:07 UTC
