### ISSUE TITLE
HELP! My main adress from my Ledger Nano S is not showing up in MEW or mycrypto!

### ISSUE THREAD

**Issue by Falsetto286** [ethereum/go-ethereum#20944] opened 2020-04-19 12:15 UTC
Need you help guys.

MY main wallet adress is not showing in MEW/my crypto/ledger live. It is like it has never existed on my ledger allthough I have been using it for the past 2 years. I tried different derivation paths but it still doesn't show up.

Hope you guys can help me out or all my eth will be lost in nirvana......

**Comment by Out-Sider1** [comment] 2020-04-19 20:08
Look it up on the nano blockchain.  do you have your wallet address or API
key?  I think that's what it's called.  I leave you the address, I hope you
solve your problem, greetings from Mexico.
https://nanocrawler.cc/explorer/block/( put here the direction Chaín)

**Comment by Falsetto286** [comment] 2020-04-19 21:30
it is ethereum not nano

________________________________
Von: Out-Sider1 <notifications@github.com>
Gesendet: Sonntag, 19. April 2020 22:09
An: ethereum/go-ethereum <go-ethereum@noreply.github.com>
Cc: Falsetto286 <ryan_stalder@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [ethereum/go-ethereum] HELP! My main adress from my Ledger Nano S is not showing up in MEW or mycrypto! (#20944)


Look it up on the nano blockchain. do you have your wallet address or API
key? I think that's what it's called. I leave you the address, I hope you
solve your problem, greetings from Mexico.
https://nanocrawler.cc/explorer/block/( put here the direction Chaín)

**Comment by ligi** [comment] 2020-04-20 00:48
closing as duplicate of #20945

**Closed by ligi** 2020-04-20 00:48 UTC
