### ISSUE TITLE
ERROR[08-24|07:12:40] Invalid receipt array RLP

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#15032] opened 2017-08-24 12:18 UTC
#### System information
Windows 10  64bit 

Geth version: `geth version`
v1.7.0-unstable-68955ed2/windows-amd64/go1.8.3"

#### Actual behaviour
INFO [08-24|07:12:34] Imported new chain segment               blocks=4  txs=320  mgas=25.413 elapsed=9.574s  mgasps=2.654 number=4197698 hash=79b5e3â€¦001e4d
ERROR[08-24|07:12:37] Invalid receipt array RLP                hash=789115â€¦acfaf5 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:37] Invalid receipt array RLP                hash=773823â€¦59a045 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:38] Invalid receipt array RLP                hash=242eceâ€¦85003a err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:38] Invalid receipt array RLP                hash=5aa4e1â€¦aec04d err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:40] Invalid receipt array RLP                hash=1925bcâ€¦0faf06 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:40] Invalid receipt array RLP                hash=958d3bâ€¦6865b6 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:43] Invalid receipt array RLP                hash=1355b2â€¦f3c666 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:43] Invalid receipt array RLP                hash=ebff7câ€¦35f494 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
INFO [08-24|07:12:44] Imported new chain segment               blocks=6  txs=376  mgas=19.139 elapsed=9.164s  mgasps=2.088 number=4197704 hash=c0d78bâ€¦1262ab
ERROR[08-24|07:12:45] Invalid receipt array RLP                hash=3e08a7â€¦40800e err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:45] Invalid receipt array RLP                hash=da49beâ€¦30314f err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:45] Invalid receipt array RLP                hash=297eabâ€¦fd9475 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:45] Invalid receipt array RLP                hash=02c3b0â€¦ba7035 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:48] Invalid receipt array RLP                hash=631af8â€¦2e1802 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:48] Invalid receipt array RLP                hash=8efd0dâ€¦e01e39 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:51] Invalid receipt array RLP                hash=3b2ef7â€¦2842ce err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:51] Invalid receipt array RLP                hash=aa132bâ€¦d38711 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:51] Invalid receipt array RLP                hash=7b0fb0â€¦21a5d8 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:51] Invalid receipt array RLP                hash=dff004â€¦cd6e28 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
INFO [08-24|07:12:53] Imported new chain segment               blocks=4  txs=403  mgas=13.571 elapsed=9.656s  mgasps=1.405 number=4197708 hash=e95a38â€¦42b5e8
ERROR[08-24|07:12:54] Invalid receipt array RLP                hash=05c47dâ€¦d0122e err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|07:12:54] Invalid receipt array RLP                hash=e0c398â€¦54dca0 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"

#### Steps to reproduce the behaviour
Run Geth latest version

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment] 2017-08-24 20:35
Possible duplicate of: https://github.com/ethereum/go-ethereum/issues/15031

**Comment by rfikki** [comment] 2017-08-24 20:51
This error only seems to occur on the main net.

**Comment by fjl** [comment] 2017-08-24 21:35
This is a regression on the master branch. We're fixing it, but you'll need to resync when the fix is committed.

**Comment by mi2zha** [comment] 2017-08-25 02:44
@fjl hi,when can you fix it? thank u

**Comment by karalabe** [comment] 2017-08-25 07:32
This should be fixed on master now. Sorry about the issue.

**Closed by karalabe** 2017-08-25 07:32 UTC

**Comment by mi2zha** [comment] 2017-08-25 08:35
@karalabe
hi, 
How do you tell if the result of postState is out of gas, thank u
