### ISSUE TITLE
block can't syncing  Error: invalid difficulty: have 2584526037287456, want 2584251159642656

### ISSUE THREAD

**Issue by liuhuanhui** [ethereum/go-ethereum#18492] opened 2019-01-22 08:51 UTC
### geth version: 1.9
```
[root@eth eth-node]# geth --syncmode "fast" --maxpeers 100  -datadir /node/eth-node/ --rpc --rpcapi eth,web3,personal --rpcport 8545 --rpcaddr "127.0.0.1"
INFO [01-22|16:48:56.940] Maximum peer count                       ETH=100 LES=0 total=100
INFO [01-22|16:48:56.941] Starting peer-to-peer node               instance=Geth/v1.9.0-unstable-73534343/linux-amd64/go1.10
INFO [01-22|16:48:56.941] Allocated cache and file handles         database=/node/eth-node/geth/chaindata cache=512 handles=32767
INFO [01-22|16:48:57.707] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7080000 Engine: ethash}"
INFO [01-22|16:48:57.707] Disk storage enabled for ethash caches   dir=/node/eth-node/geth/ethash count=3
INFO [01-22|16:48:57.707] Disk storage enabled for ethash DAGs     dir=/root/.ethash              count=2
INFO [01-22|16:48:57.707] Initialising Ethereum protocol           versions="[63 62]" network=1
WARN [01-22|16:48:57.783] Head state missing, repairing chain      number=7080006 hash=213c72…c5358b
INFO [01-22|16:49:03.259] Rewound blockchain to past state         number=7066271 hash=c4e646…7553e2
INFO [01-22|16:49:03.260] Loaded most recent local header          number=7080006 hash=213c72…c5358b td=8757915281947813094117 age=5d1h50m
INFO [01-22|16:49:03.261] Loaded most recent local full block      number=7066271 hash=c4e646…7553e2 td=8721424076094749350612 age=1w13h52m
INFO [01-22|16:49:03.261] Loaded most recent local fast block      number=7080006 hash=213c72…c5358b td=8757915281947813094117 age=5d1h50m
INFO [01-22|16:49:03.261] Loaded local transaction journal         transactions=0 dropped=0
INFO [01-22|16:49:03.261] Regenerated local transaction journal    transactions=0 accounts=0
WARN [01-22|16:49:03.261] Blockchain not empty, fast sync disabled 
INFO [01-22|16:49:03.320] New local node record                    seq=15 id=04b343863c889d39 ip=127.0.0.1 udp=30303 tcp=30303
INFO [01-22|16:49:03.321] Started P2P networking                   self=enode://1e820842032ca8726c811da541a26ddee5fbde4cf431db8eb018571326c46b3909dffea9d26881be9615ec5dfc95e279cea3fa8d2b037ec6b595b8838c1a10e1@127.0.0.1:30303
INFO [01-22|16:49:03.322] IPC endpoint opened                      url=/node/eth-node/geth.ipc
INFO [01-22|16:49:03.322] HTTP endpoint opened                     url=http://127.0.0.1:8545   cors= vhosts=localhost
INFO [01-22|16:49:06.832] New local node record                    seq=16 id=04b343863c889d39 ip=47.75.39.83 udp=30303 tcp=30303
INFO [01-22|16:49:43.321] Block synchronisation started 
ERROR[01-22|16:49:48.402] 
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7080000 Engine: ethash}

Number: 7080000
Hash: 0x30f1e707150171df122488ffac94a7c165ea5d2cb7136e18aa1bae37f069ebc9


Error: invalid difficulty: have 2584526037287456, want 2584251159642656
##############################
 
WARN [01-22|16:49:48.402] Synchronisation failed, dropping peer    peer=0726b6c40af4ba04 err="retrieved hash chain is invalid"

```

**Comment by holiman** [comment] 2019-01-22 10:38
Duplicate of https://github.com/ethereum/go-ethereum/issues/18488 , 
This error was fixed by https://github.com/ethereum/go-ethereum/pull/18436 . 
Duplicate of https://github.com/ethereum/go-ethereum/issues/18421 and https://github.com/ethereum/go-ethereum/issues/18388

**Closed by holiman** 2019-01-22 10:38 UTC

**Comment by liuhuanhui** [comment] 2019-01-22 10:46
> 重复[＃18488](https://github.com/ethereum/go-ethereum/issues/18488)，
> 此错误由[＃18436](https://github.com/ethereum/go-ethereum/pull/18436)修复。
> 重复[＃18421](https://github.com/ethereum/go-ethereum/issues/18421)和[＃18388](https://github.com/ethereum/go-ethereum/issues/18388)

How can I repair it?

**Comment by relaxbao** [comment] 2019-02-19 08:47
> > 重复[＃18488](https://github.com/ethereum/go-ethereum/issues/18488)，
> > 此错误由[＃18436](https://github.com/ethereum/go-ethereum/pull/18436)修复。
> > 重复[＃18421](https://github.com/ethereum/go-ethereum/issues/18421)和[＃18388](https://github.com/ethereum/go-ethereum/issues/18388)
> 
> How can I repair it?

请问您解决这个问题了吗？

**Comment by liuhuanhui** [comment] 2019-02-23 10:07
no 

> > > 重复[＃18488](https://github.com/ethereum/go-ethereum/issues/18488)，
> > > 此错误由[＃18436](https://github.com/ethereum/go-ethereum/pull/18436)修复。
> > > 重复[＃18421](https://github.com/ethereum/go-ethereum/issues/18421)和[＃18388](https://github.com/ethereum/go-ethereum/issues/18388)
> > 
> > 
> > How can I repair it?
> 
> 请问您解决这个问题了吗？
no

**Comment by liuhuanhui** [comment] 2019-02-23 10:08
> > 重复[＃18488](https://github.com/ethereum/go-ethereum/issues/18488)，
> > 此错误由[＃18436](https://github.com/ethereum/go-ethereum/pull/18436)修复。
> > 重复[＃18421](https://github.com/ethereum/go-ethereum/issues/18421)和[＃18388](https://github.com/ethereum/go-ethereum/issues/18388)
> 
> How can I repair it?

I reinstalled the get version, resynchronized, and everything was fine

**Comment by oslivan** [comment] 2019-03-01 04:48
I also have this error after upgrading `1.8.23`, but it will be fine after synchronization for a while, I think it may be the reason to synchronize the block from the lower version of the node. When the old node is automatically cleared, it is normal.
