### ISSUE TITLE
geth panic

### ISSUE THREAD

**Issue by mmitech** [ethereum/go-ethereum#18983] opened 2019-02-02 10:07 UTC
#### System information

Geth version: v1.9.0-unstable-a89170cf
OS & Version: Ubuntu server 18.04
Commit hash : a89170cf

crash with the log:
```
Feb 01 19:57:48 geth[38727]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 01 19:57:48 geth[38727]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5192ce]
Feb 01 19:57:48 geth[38727]: goroutine 4497096 [running]:
Feb 01 19:57:48 geth[38727]: math/big.(*Int).Cmp(0xc050fd99e0, 0x0, 0xc215c9509d3700dc)
Feb 01 19:57:48 geth[38727]:         /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/math/big/int.go:319 +0x2e
Feb 01 19:57:48 geth[38727]: github.com/ethereum/go-ethereum/core.(*BlockChain).insertSidechain(0xc0425f8000, 0xc05264d530, 0xc0000bf5c0, 0xc0000bf501, 0x1, 0x1, 0xc061638b90, 0x1, 0x1, 0xc089af7320, ...)
Feb 01 19:57:48 geth[38727]:         /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1340 +0x108b
Feb 01 19:57:48 geth[38727]: github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0425f8000, 0xc05364a710, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Feb 01 19:57:48 geth[38727]:         /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1146 +0x2e1e
Feb 01 19:57:48 geth[38727]: github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc0425f8000, 0xc05364a710, 0x1, 0x1, 0x8, 0x8, 0xe4a960)
Feb 01 19:57:48 geth[38727]:         /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1095 +0xb89
Feb 01 19:57:48 geth[38727]: github.com/ethereum/go-ethereum/eth.NewProtocolManager.func6(0xc05364a710, 0x1, 0x1, 0x1f34a01, 0xc048a00090, 0x7bb03dceace80c2)
Feb 01 19:57:48 geth[38727]:         /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/handler.go:183 +0x30b
Feb 01 19:57:48 geth[38727]: github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).insert.func1(0xc0000c5e10, 0x16178ab3b3c3d0f3, 0x5dfe0eb9e5ba4ece, 0x7bb03dceace80c2, 0xc5d7d573c1ba13ee, 0xc194476cf0, 0xc00bbbbb50, 0x10)
Feb 01 19:57:48 geth[38727]:         /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:667 +0x53a
Feb 01 19:57:48 geth[38727]: created by github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).insert
Feb 01 19:57:48 geth[38727]:         /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:641 +0x2ad
```

**Comment by holiman** [comment] 2019-02-02 11:03
What chain was this on? Ropsten or mainnet?

**Comment by mmitech** [comment] 2019-02-02 11:05
Sorry forgot to mention that, it was ropsten.

**Comment by holiman** [comment] 2019-02-02 11:14
This is a duplicate of https://github.com/ethereum/go-ethereum/issues/18977

**Comment by holiman** [comment] 2019-02-02 11:14
Thanks for the report, btw!

**Comment by holiman** [comment] 2019-02-02 11:18
Oh, another thing: do you have the logs preceding the panic? Would be great if we could take a look at those and see the chain of events that led to this

**Comment by holiman** [comment] 2019-02-02 11:18
(can add to the other ticket)

**Comment by holiman** [comment] 2019-02-05 20:37
This is fixed on master

**Closed by holiman** 2019-02-05 20:37 UTC
