### ISSUE TITLE
I cannot sycn now 

### ISSUE THREAD

**Issue by pureland** [ethereum/go-ethereum#1514] opened 2015-07-23 15:29 UTC
I was have this problem may,because kill geth but I have this problem which geth is runing ,
and I recover block but also cannot though block 969701
I0723 23:25:40.495803   16451 chain_manager.go:794] Bad block #969701 (1c52e04fe751b08892d594c21c59faac1492f24a75c338803adef54b7c0c5242)
I0723 23:25:40.495865   16451 chain_manager.go:795] Transaction w/ invalid nonce. tx=79012  state=0)

**Comment by pureland** [comment] 2015-07-23 15:42
I recover the block to 960000  and resycn again ,but I cannot though this bad block ,


I0723 23:40:35.970724   16564 chain_manager.go:678] imported 0 block(s) (0 queued 128 ignored) including 0 txs in 66.37807ms. #969582 [4b66c820 / 328d3ab4]
I0723 23:40:38.807654   16564 chain_manager.go:794] Bad block #969701 (1c52e04fe751b08892d594c21c59faac1492f24a75c338803adef54b7c0c5242)
I0723 23:40:38.807717   16564 chain_manager.go:795] Transaction w/ invalid nonce. tx=79012  state=0)
I0723 23:40:38.808021   16564 downloader.go:253] Synchronisation failed: block downloading canceled (requested)
I0723 23:40:41.781529   16564 chain_manager.go:678] imported 0 block(s) (0 queued 1 ignored) including 0 txs in 3.48891ms. #960000 [789769b5 / 789769b5]
I0723 23:40:41.871131   16564 chain_manager.go:678] imported 0 block(s) (0 queued 2 ignored) including 0 txs in 3.536112ms. #960002 [7553b986 / 7d65e9c4]

**Comment by tcoulter** [comment] 2015-07-23 18:11
See my bug here: https://github.com/ethereum/go-ethereum/issues/1513

I've included a workaround in comments. This looks like a dupe of #1513

**Comment by karalabe** [comment] 2015-07-24 09:17
Did geth crash or did you force kill it at a certain point? These suggest database corruptions, which should never happen during clean shutdowns.

**Comment by pureland** [comment] 2015-07-24 17:05
no kill , no crack ,, just cannot sycn while geth is runing ,

**Comment by fortier** [comment] 2015-07-25 04:40
Same happen to me today. 

Problem started at block #980308, **immediately after** that same node mined block #980307 (coincidental?).
 
Geth was not being restarted when that happen.
 
Also, geth recover to early blocks attempts always fails. Example:
$ ./geth recover 980300
F0725 00:09:35.683453    4381 main.go:517] block not found. Recovery failed
 
 
logs
===========
I0724 23:31:32.201672    4030 downloader.go:277] Block synchronisation started
I0724 23:31:36.163170    4030 chain_manager.go:794] Bad block #980308 (5ec36dd54e982aa48c4e327e31cefcf21c67b69e350fe12a82ea5941a34d4b53)
I0724 23:31:36.163239    4030 chain_manager.go:795] Transaction w/ invalid nonce. tx=474188  state=0)
I0724 23:31:36.163331    4030 downloader.go:253] Synchronisation failed: block downloading canceled (requested)
I0724 23:31:46.248250    4030 chain_manager.go:794] Bad block #980308 (5ec36dd54e982aa48c4e327e31cefcf21c67b69e350fe12a82ea5941a34d4b53)
I0724 23:31:46.248316    4030 chain_manager.go:795] Transaction w/ invalid nonce. tx=474188  state=0)
I0724 23:31:46.248407    4030 downloader.go:253] Synchronisation failed: hash fetching canceled (requested)
...
 
Info
====
$ ./geth version
Geth
Version: 0.9.39
Git Commit: d1d45aa8390731ad9d0422e6bbf2d451d11dab4d
Protocol Versions: [61 60]
Network Id: 0
Go Version: go1.4.2
OS: linux

**Comment by obscuren** [comment] 2015-07-25 09:26
Some time ago on both your system the database failed to write due to one of the following reasons:

1. it crashed halfway of writing data
2. it didn't have disk space to write more than half the data
3. there was a level db internal error

Usually setting head or restarting doesn't fix the problem. Do you recall any of the of the above events?

**Comment by obscuren** [comment] 2015-07-25 09:27
See https://github.com/ethereum/go-ethereum/issues/1513

**Closed by obscuren** 2015-07-25 09:27 UTC
Labels: duplicate
