### ISSUE TITLE
miner.start(1) return null !! need help

### ISSUE THREAD

**Issue by eka051103** [ethereum/go-ethereum#30060] opened 2024-06-24 16:56 UTC
Drag the installation packages for go and geth to the desktop

cd /opt
tar -zxvf /root/desktop/go1.21.6.linux-amd64.tar.gz
 echo 'export GOPATH=/opt/Go' >> /etc/profile
 echo 'export GOROOT=/opt/go' >> /etc/profile
 echo 'export PATH=$PATH:$GOROOT/bin' >> /etc/profile
source /etc/profile
go version 
tar -zxvf /root/desktop/geth-linux-amd64-1.11.6-ea9e62ca.tar.gz
cd geth-linux-amd64-1.11.6-ea9e62ca/
mv geth /usr/local/bin
cd /usr/local/bin
echo 'export PATH=$PATH:/usr/local/bin ' >> /etc/profile 
source /etc/profile
geth version 
root@root1-VMware-Virtual-Platform:/opt/geth-linux-amd64-1.11.6-ea9e62ca# geth version
	Geth
	Version: 1.11.6-stable
	Git Commit: ea9e62ca3db5c33aa7438ebf39c189afd53c6bf8
	Git Commit Date: 20230420
	Architecture: amd64
	Go Version: go1.20.3
	Operating System: linux
	GOPATH=/opt/Go
	GOROOT=/opt/go

vim genesis.json
{
  "config": {
    "chainId": 666,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0
  },
  "alloc": {},
  "coinbase": "0x0000000000000000000000000000000000000000",
  "difficulty": "0x200",
  "extraData": "",
  "gasLimit": "0x2fefd8",
  "nonce": "0x0000000000000042",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
geth init genesis.json
	INFO [06-25|00:36:55.796] Maximum peer count                       ETH=50 LES=0 total=50
INFO [06-25|00:36:55.798] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [06-25|00:36:55.805] Set global gas cap                       cap=50,000,000
INFO [06-25|00:36:55.808] Using leveldb as the backing database 
INFO [06-25|00:36:55.808] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=16.00MiB handles=16
INFO [06-25|00:36:55.825] Using LevelDB as the backing database 
INFO [06-25|00:36:55.845] Opened ancient database                  database=/root/.ethereum/geth/chaindata/ancient/chain readonly=false
INFO [06-25|00:36:55.845] Writing custom genesis block 
INFO [06-25|00:36:55.847] Successfully wrote genesis state         database=chaindata                      hash=52a9c3..27a7c2
INFO [06-25|00:36:55.847] Using leveldb as the backing database 
INFO [06-25|00:36:55.847] Allocated cache and file handles         database=/root/.ethereum/geth/lightchaindata cache=16.00MiB handles=16
INFO [06-25|00:36:55.855] Using LevelDB as the backing database 
INFO [06-25|00:36:55.874] Opened ancient database                  database=/root/.ethereum/geth/lightchaindata/ancient/chain readonly=false
INFO [06-25|00:36:55.874] Writing custom genesis block 
INFO [06-25|00:36:55.876] Successfully wrote genesis state         database=lightchaindata                      hash=52a9c3..27a7c2

geth --datadir ethchain --nodiscover console 2>>eth_output.log --rpc.enabledeprecatedpersonal
> personal.newAccount("qwe")
"0xc9427e318ce27d654fef94bdd5da3b3aa24378a8"
>personal.unlockAccount("0xc9427e318ce27d654fef94bdd5da3b3aa24378a8")
>true
>miner.setEtherbase("0xc9427e318ce27d654fef94bdd5da3b3aa24378a8")
>true
>miner.start(1)
null

These are some runtime reports:
INFO [06-25|00:51:02.231] HTTP server stopped                      endpoint=127.0.0.1:8551
INFO [06-25|00:51:02.232] IPC endpoint closed                      url=/opt/geth-linux-amd64-1.11.6-ea9e62ca/ethchain/geth.ipc
INFO [06-25|00:51:02.232] Ethereum protocol stopped 
INFO [06-25|00:51:02.232] Transaction pool stopped 
INFO [06-25|00:51:02.232] Writing snapshot state to disk           root=d7f897..0f0544
INFO [06-25|00:51:02.232] Persisted trie from memory database      nodes=0 size=0.00B time="23.698µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [06-25|00:51:02.232] Writing clean trie cache to disk         path=/opt/geth-linux-amd64-1.11.6-ea9e62ca/ethchain/geth/triecache threads=6
INFO [06-25|00:51:02.242] Persisted the clean trie cache           path=/opt/geth-linux-amd64-1.11.6-ea9e62ca/ethchain/geth/triecache elapsed=9.123ms
INFO [06-25|00:51:02.242] Blockchain stopped 
INFO [06-25|00:51:42.523] Starting Geth on Ethereum mainnet... 
INFO [06-25|00:51:42.524] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [06-25|00:51:42.525] Maximum peer count                       ETH=50 LES=0 total=50
INFO [06-25|00:51:42.526] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [06-25|00:51:42.529] Sanitizing cache to Go's GC limits       provided=4096 updated=1289
INFO [06-25|00:51:42.529] Set global gas cap                       cap=50,000,000
INFO [06-25|00:51:42.531] Allocated trie memory caches             clean=193.00MiB dirty=322.00MiB
INFO [06-25|00:51:42.531] Using leveldb as the backing database 
INFO [06-25|00:51:42.531] Allocated cache and file handles         database=/opt/geth-linux-amd64-1.11.6-ea9e62ca/ethchain/geth/chaindata cache=644.00MiB handles=524,288
INFO [06-25|00:51:42.557] Using LevelDB as the backing database 
INFO [06-25|00:51:42.558] Opened ancient database                  database=/opt/geth-linux-amd64-1.11.6-ea9e62ca/ethchain/geth/chaindata/ancient/chain readonly=false
INFO [06-25|00:51:42.561] Disk storage enabled for ethash caches   dir=/opt/geth-linux-amd64-1.11.6-ea9e62ca/ethchain/geth/ethash count=3
INFO [06-25|00:51:42.561] Disk storage enabled for ethash DAGs     dir=/root/.ethash count=2
INFO [06-25|00:51:42.561] Initialising Ethereum protocol           network=1 dbversion=8
INFO [06-25|00:51:42.625]  
INFO [06-25|00:51:42.625] --------------------------------------------------------------------------------------------------------------------------------------------------------- 
INFO [06-25|00:51:42.625] Chain ID:  1 (mainnet) 
INFO [06-25|00:51:42.625] Consensus: Beacon (proof-of-stake), merged from Ethash (proof-of-work) 
INFO [06-25|00:51:42.625]  
INFO [06-25|00:51:42.625] Pre-Merge hard forks (block based): 
INFO [06-25|00:51:42.625]  - Homestead:                   #1150000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md) 
INFO [06-25|00:51:42.625]  - DAO Fork:                    #1920000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/dao-fork.md) 
INFO [06-25|00:51:42.625]  - Tangerine Whistle (EIP 150): #2463000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md) 
INFO [06-25|00:51:42.625]  - Spurious Dragon/1 (EIP 155): #2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md) 
INFO [06-25|00:51:42.625]  - Spurious Dragon/2 (EIP 158): #2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md) 
INFO [06-25|00:51:42.625]  - Byzantium:                   #4370000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md) 
INFO [06-25|00:51:42.625]  - Constantinople:              #7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md) 
INFO [06-25|00:51:42.625]  - Petersburg:                  #7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md) 
INFO [06-25|00:51:42.625]  - Istanbul:                    #9069000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md) 
INFO [06-25|00:51:42.625]  - Muir Glacier:                #9200000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/muir-glacier.md) 
INFO [06-25|00:51:42.625]  - Berlin:                      #12244000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md) 
INFO [06-25|00:51:42.625]  - London:                      #12965000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md) 
INFO [06-25|00:51:42.625]  - Arrow Glacier:               #13773000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/arrow-glacier.md) 
INFO [06-25|00:51:42.625]  - Gray Glacier:                #15050000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/gray-glacier.md) 
INFO [06-25|00:51:42.625]  
INFO [06-25|00:51:42.625] Merge configured: 
INFO [06-25|00:51:42.625]  - Hard-fork specification:    https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md 
INFO [06-25|00:51:42.625]  - Network known to be merged: true 
INFO [06-25|00:51:42.625]  - Total terminal difficulty:  58750000000000000000000 
INFO [06-25|00:51:42.625]  
INFO [06-25|00:51:42.625] Post-Merge hard forks (timestamp based): 
INFO [06-25|00:51:42.625]  - Shanghai:                    @1681338455 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md) 
INFO [06-25|00:51:42.625]  
INFO [06-25|00:51:42.625] --------------------------------------------------------------------------------------------------------------------------------------------------------- 
INFO [06-25|00:51:42.625]  
INFO [06-25|00:51:42.626] Loaded most recent local block           number=0 hash=d4e567..cb8fa3 td=17,179,869,184 age=55y3mo1w
INFO [06-25|00:51:42.626] Loaded local transaction journal         transactions=0 dropped=0
INFO [06-25|00:51:42.626] Regenerated local transaction journal    transactions=0 accounts=0
INFO [06-25|00:51:42.627] Chain post-merge, sync via beacon client 
INFO [06-25|00:51:42.627] Gasprice oracle is ignoring threshold set threshold=2
WARN [06-25|00:51:42.627] Engine API enabled                       protocol=eth
INFO [06-25|00:51:42.628] Starting peer-to-peer node               instance=Geth/v1.11.6-stable-ea9e62ca/linux-amd64/go1.20.3
WARN [06-25|00:51:42.641] Deprecated personal namespace activated 
INFO [06-25|00:51:42.642] IPC endpoint opened                      url=/opt/geth-linux-amd64-1.11.6-ea9e62ca/ethchain/geth.ipc
INFO [06-25|00:51:42.643] Loaded JWT secret file                   path=/opt/geth-linux-amd64-1.11.6-ea9e62ca/ethchain/geth/jwtsecret crc32=0x6274c945
INFO [06-25|00:51:42.643] New local node record                    seq=1,719,247,044,250 id=962bdb97a18e3e58 ip=127.0.0.1 udp=0 tcp=30303
INFO [06-25|00:51:42.643] Started P2P networking                   self="enode://5d618254e5dd22a7bb31c44c321a7f129bdb1517ed07f44cbbf67d0611bd01bf3607c361dedb9e65f8a304c17c9e70faadf65110da9d6ee725fb076f843b7d82@127.0.0.1:30303?discport=0"
INFO [06-25|00:51:42.643] WebSocket enabled                        url=ws://127.0.0.1:8551
INFO [06-25|00:51:42.643] HTTP server started                      endpoint=127.0.0.1:8551 auth=true prefix= cors=localhost vhosts=localhost
WARN [06-25|00:51:42.681] Enabling deprecated personal namespace 
WARN [06-25|00:51:42.682] Served eth_coinbase                      reqid=3 duration="42.1µs" err="etherbase must be explicitly specified"
INFO [06-25|00:52:13.172] Updated mining threads                   threads=1
INFO [06-25|00:52:13.172] Transaction pool price threshold updated price=1,000,000,000
INFO [06-25|00:52:13.173] Commit new sealing work                  number=1 sealhash=d0be28..31cab7 uncles=0 txs=0 gas=0 fees=0 elapsed="664.693µs"
INFO [06-25|00:52:13.174] Commit new sealing work                  number=1 sealhash=d0be28..31cab7 uncles=0 txs=0 gas=0 fees=0 elapsed=1.068ms
INFO [06-25|00:52:13.846] Updated mining threads                   threads=1
INFO [06-25|00:52:14.553] Updated mining threads                   threads=1
WARN [06-25|00:52:17.630] Post-merge network, but no beacon client seen. Please launch one to follow the chain!

**Comment by lightclient** [comment] 2024-06-24 17:21
Duplicate of #27607

**Closed by lightclient** 2024-06-24 17:21 UTC
Labels: type:docs
