### ISSUE TITLE
history file location isn't configurable

### ISSUE THREAD

**Issue by tom-seddon** [ethereum/go-ethereum#1841] opened 2015-09-22 22:10 UTC
Shouldn't --datadir influence where the history file goes?

    root@508700517ebc:/# geth --datadir /data attach ipc:/data/geth.ipc
    unable to open history file: open /root/.ethereum/history: no such file or directory

(The "unable to open history file" error message also gets printed to stdout.)

--Tom

**Comment by karalabe** [comment] 2015-09-23 10:12
The issue is that when only attaching, we create a lightweight JS interpreter (https://github.com/ethereum/go-ethereum/blob/develop/cmd/geth/main.go#L429), and we do not pass an ethereum configuration (which contains the actual datadir parameter) to it. Hence setting the data dir (https://github.com/ethereum/go-ethereum/blob/develop/cmd/geth/js.go#L439) never happens. The solution would be to extract the needed configuration options manually and pass them to the lightweight JSRE too.

**Comment by karalabe** [comment] 2015-09-23 10:12
If/when you have time, @bas-vk, could you look at this?

**Comment by tgerring** [comment] 2015-10-08 17:54
@tom-seddon Can you check against latest `develop` to see if your problem is now resolved? The fix should now be merged in

**Comment by zelig** [comment] 2016-02-10 07:43
this has been fixed. closing

**Closed by zelig** 2016-02-10 07:43 UTC
Labels: **, bug, I, in progress
