### ISSUE TITLE
Not able to create contract address & transaction with sync mode light

### ISSUE THREAD

**Issue by osiztechnologies** [ethereum/go-ethereum#19424] opened 2019-04-09 15:21 UTC
We have used 

geth 1.8.23 , sync mode - light

We are not able to execute fund withdraw from my address to another address

and also we are not able to create contract address.

Today afternoon we have faced this type of issue repeatedly.

Kindly guide us how to resolve this.

**Comment by ChinmayRai** [comment] 2019-04-09 17:17
I am facing similar issue when trying to make send a data payload to a Smart contract
#### System information

Geth version: 1.8.25-stable-14ae1246   (Rinkeby Network ; syncmode=light)
OS & Version: Linux Ubuntu 18.04

#### Expected behaviour
Transaction should be submitted for validation and eventually the data get added to the chain

#### Actual behaviour
Geth Crashes abruptly without even broadcasting the transaction

#### Steps to reproduce the behaviour
Try submitting a transaction (with a data payload) to a smart contract.

#### Backtrace
INFO [04-09|22:26:16.381] Submitted transaction                    fullhash=0x9da1edd01e180d7a56d89fc14f45818f98b04e7a89b3cbf5e99abdb67a27ea1c recipient=0x3aA893B62B371fddB6f0305acd33106Aa113155F
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb105c0]

goroutine 15 [running]:
github.com/ethereum/go-ethereum/les.(*peer).GetRequestCost(0xc42670c790, 0xc, 0x1, 0x0)
	/build/ethereum-3tTh57/ethereum-1.8.25+build18425+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/les/peer.go:166 +0xa0
github.com/ethereum/go-ethereum/les.(*LesTxRelay).send.func1(0x11134e0, 0xc42670c790, 0xc4380b6d01)
	/build/ethereum-3tTh57/ethereum-1.8.25+build18425+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/les/txrelay.go:121 +0x4e
github.com/ethereum/go-ethereum/les.(*requestDistributor).nextRequest(0xc4200d7090, 0x0, 0x0, 0x0, 0x0)
	/build/ethereum-3tTh57/ethereum-1.8.25+build18425+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/les/distributor.go:195 +0x296
github.com/ethereum/go-ethereum/les.(*requestDistributor).loop(0xc4200d7090)
	/build/ethereum-3tTh57/ethereum-1.8.25+build18425+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/les/distributor.go:129 +0x7f
created by github.com/ethereum/go-ethereum/les.newRequestDistributor
	/build/ethereum-3tTh57/ethereum-1.8.25+build18425+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/les/distributor.go:80 +0x10b

**Comment by OliverBui** [comment] 2019-04-09 18:40
@osiztechnologies i have same issue with `geth 1.8.23 , sync mode - light`
when i create a transaction from my node, the transaction is not publish to blockchain and the `peer` down from 8 to 0.

**Comment by ligi** [comment] 2019-04-09 19:08
thanks for the reports! As far as I see it only happens in sync mode light - correct? cc @zsfelfoldi

**Comment by zsfelfoldi** [comment] 2019-04-09 19:14
Found the cause, this is a 1.8 specific bug, old client versions are still sending the LES/1 version of SendTx through LES/2 protocol. It did work until now when we removed LES/1 support. So the bug surfaces now if you connect an old client to a server running latest master. I can make the server accept old SendTx again but some servers are already out there not supporting it. Until we figure out the best way to handle the situation the quickest fix is to compile your client from latest master too.

**Comment by ChinmayRai** [comment] 2019-04-09 20:17
@zsfelfoldi  Do you mean that instead of the 1.8.25 whiteBall stable release we should use the master repo (version : 1.9.0-unstable-33d28f37) ?

Thanks in Advance

**Comment by dannieb** [comment] 2019-04-10 07:55
@zsfelfoldi @karalabe Do you know if this issue will arise with a fast sync node?  Also, is this isolated to only connecting to peer nodes running the latest master branch?  So if we were to connect strictly to peers run a 1.8 version of geth, we wouldn't experience this issue?

**Comment by OliverBui** [comment] 2019-04-10 10:25
I see the updated release, is this issues is fixed?

**Comment by trueshura** [comment] 2019-04-10 10:35
> I see the updated release, is this issues is fixed?

geth bult from master branch works (just send TX).

**Comment by OliverBui** [comment] 2019-04-10 10:40
@trueshura I get PPA from `https://launchpad.net/~ethereum/+archive/ubuntu/ethereum` and install `ethereum-unstable`, but can not send TX, issue `context canceled`

**Comment by osiztechnologies** [comment] 2019-04-10 11:07
same error.

**Comment by OliverBui** [comment] 2019-04-10 11:26
@osiztechnologies did you use PPA or build from master?

**Comment by osiztechnologies** [comment] 2019-04-10 11:42
@OliverBui build from master - geth-linux-amd64-1.9.0-unstable

**Comment by OliverBui** [comment] 2019-04-10 11:43
@osiztechnologies and it do not resolve this issue?

**Comment by osiztechnologies** [comment] 2019-04-10 11:45
@OliverBui    No. If you have any solution share here.

**Comment by OliverBui** [comment] 2019-04-10 11:48
@osiztechnologies Nope, I am waiting the solutions. Waiting...

**Comment by osiztechnologies** [comment] 2019-04-10 11:50
OliverBui  +1

**Comment by Instantbitex** [comment] 2019-04-10 12:37
When it is going to be fixed

**Comment by holiman** [comment] 2019-04-10 12:51
It's merged into 1.8 now: https://github.com/ethereum/go-ethereum/pull/19437. Official release binaries are in the pipeline, should be available in a little while.

**Comment by osiztechnologies** [comment] 2019-04-10 12:59
@Instantbitex We have checking other solution to fix. otherwise we want to wait for bug fixed release package.

**Comment by karalabe** [comment] 2019-04-10 12:59
This issue has been fixed in https://github.com/ethereum/go-ethereum/pull/19437, and just shipped in [Geth v1.8.26](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.26). Please allow half an hour or so for the binaries to be built and pushed out. Sorry for any inconvenience.

**Closed by karalabe** 2019-04-10 12:59 UTC
