### ISSUE TITLE
 always notice me there is a bad block ,

### ISSUE THREAD

**Issue by pureland** [ethereum/go-ethereum#1445] opened 2015-07-09 07:33 UTC
Bad block #829744 (6c9fc7a652d6bcc608ec40c0deee95529e7006891af4973ade254749f703d481)
I0709 15:32:48.662698    2681 chain_manager.go:783] invalid receipt root hash. received=be9843b1b4867d2e24f92be16005c8d692cd0b2b4a924037996f166daf04961f calculated=a37d0d92dcd8ffb93919254980975b7f22fc1017b3bbe5b6880c164af618807c

**Comment by karalabe** [comment] 2015-07-09 20:21
I've printed that block from my chain and is seems valid.

```
'Block(#829744): Size: 7.76 kB TD: 7002459198976889 {
MinerHash: 820e033f987081466fe246cbed650f8f686e19a689beb350028b827bb049492b
Header(6c9fc7a652d6bcc608ec40c0deee95529e7006891af4973ade254749f703d481):
[
        ParentHash:         007df6390708a49ed14c704515b6ac0cd171eff1ae4bdcc49f1654aa860e9343
        UncleHash:          2ba364886decf5c0b666b423cdf72712c660eb7faa27c6a722eb8753cf6623f6
        Coinbase:           dc471c2659b55785d60d389f02c5d5433ba0b8d5
        Root:               2bd737080607350d3d935d2c9288f4cdb0501587b7ebf9c064100077b9dab0db
        TxSha               5ff4da25887d3e11c90725bd46f0b7701e5b9768a79787542c57c79eeea8ee6f
        ReceiptSha:         be9843b1b4867d2e24f92be16005c8d692cd0b2b4a924037996f166daf04961f
        Bloom:              00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        Difficulty:         16327501456
        Number:             829744
        GasLimit:           3141592
        GasUsed:            1292709
        Time:               1436356537
        Extra:              
        MixDigest:      4163c6aab3bdc568744149647870fe6eaf2b435bab38509d6e477a6e1754bf19
        Nonce:              2d4905826f140872
]
```

Did you by any chance kill geth? Power outage, reboot, etc that might have prematurely stopped it? It seems a corrupt database. If the problem persists, you could try reverting back a few blocks (i.e. 50) and retry from there (`geth recover 829700`).

**Comment by pureland** [comment] 2015-07-12 07:43
yes I kill geth 
but now resync chain

**Comment by karalabe** [comment] 2015-07-28 12:33
I will close this issue if it was caused by killing geth. There's a few variations of fixes that we're considering to prevent scenarios like this, but they will be only done post Frontier.

**Closed by karalabe** 2015-07-28 12:33 UTC
