### ISSUE TITLE
evm command line interface adds leading zeros in odd-length input

### ISSUE THREAD

**Issue by omelancon** [ethereum/go-ethereum#24711] opened 2022-04-18 16:39 UTC
I am executing the following dummy (smart) contract with `evm` command line.

    60003500
    PUSH1 0x00
    CALLDATALOAD
    STOP

If I provide `0x101` as input I get the expected result (EDIT: see comments below, it turns out this is _not the expected_ result):

    >>> evm --code 60003500 --input 101 --debug run
    0x
    #### TRACE ####
    PUSH1           pc=00000000 gas=10000000000 cost=3
    
    CALLDATALOAD    pc=00000002 gas=9999999997 cost=3
    Stack:
    00000000  0x0
    
    STOP            pc=00000003 gas=9999999994 cost=0
    Stack:
    00000000  0x101000000000000000000000000000000000000000000000000000000000000  # AS EXPECTED

Although, if I input `0x001`, the heading zeros seem to be dropped by the `evm` (see stack state on last line).

    >>> evm --code 60003500 --input 001 --debug run
    0x
    #### TRACE ####
    PUSH1           pc=00000000 gas=10000000000 cost=3
    
    CALLDATALOAD    pc=00000002 gas=9999999997 cost=3
    Stack:
    00000000  0x0
    
    STOP            pc=00000003 gas=9999999994 cost=0
    Stack:
    00000000  0x1000000000000000000000000000000000000000000000000000000000000   # NOT AS EXPECTED

I am using `evm version 1.10.17-stable-25c9b49f` on Linux (Pop!_OS). Why does the `evm` drops the leading zeros? It seems like a bug to me.

**Comment by karalabe** [comment] 2022-04-20 08:25
The stack currently seems to print decimals, not entire word slots. e.g.

```
Stack:
00000000  0x0
```

^ this was also in your trace that does the same thing as the truncation you didn't like.

I *think* this is deliberate to easier interpret numbers, but maybe I'm wrong? CC @holiman

**Comment by jwasinger** [comment] 2022-04-20 08:28
Weird that it accepts odd-length input (`0x101` is interpreted as `0x010100000...0` which seems strange).  would it make sense to explicitly disallow this?

**Comment by holiman** [comment] 2022-04-20 08:40
The problem is that `101` is three nibbles. We might do something "wonky" on wonky input. I agree we should just exit with "please provide full bytes input"

**Comment by s1na** [comment] 2022-04-26 11:13
@jwasinger was this fixed by https://github.com/ethereum/go-ethereum/pull/24721? can I close?

**Closed** 2022-04-27 08:24 UTC
Labels: type:bug
