### ISSUE TITLE
nonce conflicts are still happening

### ISSUE THREAD

**Issue by richiela** [ethereum/go-ethereum#14478] opened 2017-05-16 03:41 UTC
#### System information

Geth version:  Geth/v1.6.1-stable-021c3c28/linux-amd64/go1.8
OS & Version: Linux Ubuntu 16.04
Commit hash : (if `develop`)

#### Expected behaviour
Sending out tx's in succession causes nonce conflicts and transactions to orphan

#### Actual behaviour
lock and increment nonce in the client.  I understand you have to watch the network as well, but the local client should be keeping tracking of what its handed out instead of relying on the network.

#### Steps to reproduce the behaviour
Multithread sends a geth client coming from the same source account

Example - only one of these 3 transactions confirmed:

INFO [05-15|23:31:01] Imported new chain segment               blocks=1  txs=20  mgas=3.292 elapsed=193.204ms mgasps=17.037  number=3713339 hash=b8f5bb…59d9a6
INFO [05-15|23:31:04] Submitted transaction                    fullhash=0x73559b01da7d5d43e318edc2cb5c8c9472fd762589fdc35bf0e48e6cea17424d recipient=0x776a32e6ae37fe92af9f2b44a1b61858ee2e3545
INFO [05-15|23:31:04] Submitted transaction                    fullhash=0x69d8b5621895195fb4eed3622f68a88c37d979f7f2c5f1fd77f03519918ece3f recipient=0x6531f133e6deebe7f2dce5a0441aa7ef330b4e53
INFO [05-15|23:31:04] Submitted transaction                    fullhash=0x9cf4e0629d639065b7b04c2a139dd2c04069a8457ba2abc85c2d1edf3f7a90e8 recipient=0xf8f64c4b6f4a3545ede8909073aa9ff39e97563e
INFO [05-15|23:31:08] Imported new chain segment               blocks=1  txs=19  mgas=0.760 elapsed=32.041ms  mgasps=23.721  number=3713340 hash=1419c5…66dd1e

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment] 2017-05-16 07:44
This is a duplicate of https://github.com/ethereum/go-ethereum/issues/14375

**Closed by holiman** 2017-05-16 07:44 UTC
