### ISSUE TITLE
blocking issues found at test TestInteractive

### ISSUE THREAD

**Issue by charlesxsh** [ethereum/go-ethereum#23356] opened 2021-08-08 21:56 UTC
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
all goroutines/channels properly exit/close

#### Actual behaviour
During or at the exit of  test `TestInteractive` at file `console/console_test.go`
Three blocked issues:

1. github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db_compaction.go:773
```go
for {
  select {      <------ line 773
  case x = <-db.mcompCmdC:
	  switch x.(type) {
	  case cAuto:
		  db.memCompaction()
		  x.ack(nil)
		  x = nil
	  default:
		  panic("leveldb: unknown command")
	  }
  case <-db.closeC:
	  return
  }
}
```
2. github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db_compaction.go:91
```go
	for {  
		select {   <------ line 91
		case err = <-db.compErrSetC:
			switch {
			case err == nil:
			case err == ErrReadOnly, errors.IsCorrupted(err):
				goto hasperr
			default:
				goto haserr
			}
		case <-db.closeC:
			return
		}
	}
```
3. github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db_compaction.go:836
```go
select {  <------- line 836
			case x = <-db.tcompCmdC:
			case ch := <-db.tcompPauseC:
				db.pauseCompaction(ch)
				continue
			case <-db.closeC:
				return
			}
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by gballet** [comment] 2021-08-11 07:01
Possible duplicate of #23330

**Comment by karalabe** [comment] 2021-08-12 08:47
We can't really reproduce this. Adding a `defer panic` on top doesn't print any leaked goroutines. The test also seems to properly close all resources.

**Closed by karalabe** 2021-08-12 08:47 UTC
Labels: type:bug, status:triage
