### ISSUE TITLE
Build failed: 'TARGET_OS_MAC' is not defined

### ISSUE THREAD

**Issue by yiyanwannian** [ethereum/go-ethereum#22037] opened 2020-12-18 13:32 UTC
#### System information

Geth version: `geth version`
1.9.12.unstable

OS & Version: Windows/Linux/OSX
macOS Big Sur
11.1

Commit hash : (if `develop`)
commit: 3c46f5570bd674cf49c0113352ff79a4e026a5b8

#### Expected behaviour
generate geth binary

#### Actual behaviour
build failed:
# github.com/shirou/gopsutil/cpu
../../../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/cpu/cpu_darwin_cgo.go:13:5: error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_MAC
    ^
1 error generated.
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:23:13: warning: unused function '_duk_debugger_attach' [-Wunused-function]

#### Steps to reproduce the behaviour
git clone https://github.com/ethereum/go-ethereum.git
cd ethereum
go mod tidy
go build github.com/ethereum/go-ethereum/cmd/geth

#### Backtrace

````
[backtrace] 
````

**Comment by ligi** [comment] 2020-12-19 20:54
seems to be a duplicate of #22024

**Comment by gballet** [comment] 2021-01-21 10:05
Closing, this is due to using a version of clang not supported by Apple, for which there is nothing we can do.

**Closed by gballet** 2021-01-21 10:05 UTC
Labels: type:bug

**Comment by tanter** [comment] 2021-02-08 16:13
# github.com/shirou/gopsutil/cpu
/Users/user/go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/cpu/cpu_darwin_cgo.go:13:5: error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_MAC
    ^
1 error generated.
make[1]: *** [telegraf] Error 2
make: *** [build/drone] Error 2
