### ISSUE TITLE
Build errors on latest (develop and master)

### ISSUE THREAD

**Issue by tcoulter** [ethereum/go-ethereum#1143] opened 2015-05-28 16:47 UTC
I'm getting build errors trying to build the latest `develop` (edit: and `master`). Commit is in the output below:

```
desktop@steamos:~/workspace/go-ethereum$ git checkout develop
Already on 'develop'
desktop@steamos:~/workspace/go-ethereum$ git rev-parse HEAD
12b90600eb96c86ba1b5b80478be437d02b70891
desktop@steamos:~/workspace/go-ethereum$ make clean
rm -fr build/_workspace/pkg/ Godeps/_workspace/pkg build/bin/*
desktop@steamos:~/workspace/go-ethereum$ make geth
build/env.sh go install -v -ldflags '-X main.gitCommit 12b90600eb96c86ba1b5b80478be437d02b70891' ./cmd/geth
github.com/codegangsta/cli
github.com/kardianos/osext
github.com/rakyll/goini
github.com/rakyll/globalconf
github.com/ethereum/go-ethereum/common
code.google.com/p/go-uuid/uuid
golang.org/x/crypto/pbkdf2
golang.org/x/crypto/ripemd160
golang.org/x/crypto/scrypt
github.com/syndtr/goleveldb/leveldb/util
github.com/syndtr/goleveldb/leveldb/cache
github.com/ethereum/go-ethereum/crypto
github.com/ethereum/go-ethereum/logger
github.com/syndtr/goleveldb/leveldb/comparer
github.com/syndtr/goleveldb/leveldb/storage
github.com/ethereum/go-ethereum/trie
github.com/ethereum/go-ethereum/compression/rle
github.com/syndtr/goleveldb/leveldb/errors
github.com/syndtr/goleveldb/leveldb/filter
github.com/ethereum/go-ethereum/core/state
github.com/syndtr/goleveldb/leveldb/iterator
github.com/syndtr/goleveldb/leveldb/journal
github.com/syndtr/goleveldb/leveldb/memdb
github.com/syndtr/goleveldb/leveldb/opt
github.com/syndtr/gosnappy/snappy
github.com/ethereum/go-ethereum/accounts
github.com/syndtr/goleveldb/leveldb/table
gopkg.in/fatih/set.v0
github.com/ethereum/go-ethereum/core/vm
github.com/syndtr/goleveldb/leveldb
gopkg.in/karalabe/cookiejar.v2/collections/prque
github.com/huin/goupnp/httpu
github.com/huin/goupnp/scpd
github.com/huin/goupnp/soap
github.com/huin/goupnp/ssdp
golang.org/x/net/html/atom
github.com/ethereum/go-ethereum/ethdb
golang.org/x/net/html
github.com/ethereum/go-ethereum/core/types
github.com/ethereum/go-ethereum/pow
github.com/ethereum/ethash
github.com/ethereum/go-ethereum/eth/downloader
golang.org/x/text/transform
golang.org/x/text/encoding
golang.org/x/text/encoding/internal/identifier
golang.org/x/text/encoding/internal
golang.org/x/text/encoding/charmap
golang.org/x/text/encoding/japanese
golang.org/x/text/encoding/korean
golang.org/x/text/encoding/simplifiedchinese
golang.org/x/text/encoding/traditionalchinese
golang.org/x/text/encoding/unicode
github.com/jackpal/go-nat-pmp
github.com/ethereum/go-ethereum/common/compiler
github.com/robertkrimen/otto/file
github.com/robertkrimen/otto/token
github.com/robertkrimen/otto/ast
github.com/robertkrimen/otto/dbg
github.com/robertkrimen/otto/parser
golang.org/x/net/html/charset
github.com/huin/goupnp
github.com/huin/goupnp/dcps/internetgateway1
github.com/huin/goupnp/dcps/internetgateway2
github.com/robertkrimen/otto/registry
github.com/robertkrimen/otto
github.com/ethereum/go-ethereum/p2p/nat
github.com/ethereum/go-ethereum/p2p/discover
github.com/ethereum/go-ethereum/p2p
github.com/ethereum/go-ethereum/core
github.com/ethereum/go-ethereum/miner
github.com/ethereum/go-ethereum/event/filter
github.com/ethereum/go-ethereum/whisper
github.com/ethereum/go-ethereum/eth
github.com/ethereum/go-ethereum/xeth
github.com/ethereum/go-ethereum/jsre
github.com/rs/cors
github.com/peterh/liner
github.com/ethereum/go-ethereum/rpc
github.com/ethereum/go-ethereum/common/docserver
github.com/ethereum/go-ethereum/common/resolver
github.com/ethereum/go-ethereum/common/natspec
github.com/ethereum/go-ethereum/tests
github.com/ethereum/go-ethereum/cmd/utils
github.com/mattn/go-colorable
github.com/mattn/go-isatty
_/home/desktop/workspace/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth
# _/home/desktop/workspace/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth
cmd/geth/chaincmd.go:55: undefined: utils.MakeChain
cmd/geth/chaincmd.go:69: undefined: utils.MakeChain
cmd/geth/chaincmd.go:99: undefined: utils.MakeChain
cmd/geth/chaincmd.go:117: undefined: utils.MakeChain
cmd/geth/chaincmd.go:130: undefined: utils.MakeChain
cmd/geth/js.go:109: not enough arguments in call to rpc.NewJeth
cmd/geth/main.go:235: undefined: utils.NoDiscoverFlag
cmd/geth/main.go:257: undefined: utils.SetupLogger
cmd/geth/main.go:397: undefined: utils.MakeAccountManager
cmd/geth/main.go:439: undefined: utils.MakeAccountManager
cmd/geth/main.go:439: too many errors
make: *** [geth] Error 2
```

**Comment by tcoulter** [comment] 2015-05-28 16:53
Same thing on `master`, actually.

**Comment by fjl** [comment] 2015-05-28 17:32
Please try running make clean before building.

**Comment by tcoulter** [comment] 2015-05-28 17:33
I did, unfortunately. It's in the output I posted above.

**Comment by fjl** [comment] 2015-05-28 17:35
Sorry, I overlooked that. But it looks like the commit in your log is not the latest commit.

**Comment by tgerring** [comment] 2015-05-28 17:38
Does it build if you `godep go install ./cmd/geth` manually?

**Comment by tcoulter** [comment] 2015-05-28 17:39
Ya, it's like second to latest.

I just tried it on the latest (0e703d92ac9df61e2ededa8c895c70ded101a607), re-cloning the whole repository. I still get the same issue. I'm following these instructions: https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

**Comment by tcoulter** [comment] 2015-05-28 17:47
@tgerring godep isn't currently working on my system because (at least previously) it wasn't needed for the Ubuntu install. Trying to get it working now -- figuring out path problems.

**Comment by tgerring** [comment] 2015-05-28 17:49
https://github.com/ethereum/go-ethereum/wiki/Installing-Go

Then `go get github.com/tools/godep`

**Comment by tcoulter** [comment] 2015-05-28 18:01
@tgerring That method, using the Windows install instructions along with the final command (`godep go install ./cmd/geth`) seemed to work.

**Comment by fjl** [comment] 2015-05-29 19:27
I cannot reproduce the build failure with make.

**Comment by tgerring** [comment] 2015-06-19 11:25
@fjl Has this issue been addressed or do we have more information about when this occurred? Seems to have been less of a problem lately

**Comment by fjl** [comment] 2015-08-09 20:45
This has not been adressed because I could not reproduce the failure. I have no clue about what it could be either. But this issue is old. Let's close it.

**Closed by fjl** 2015-08-09 20:45 UTC
