### ISSUE TITLE
Singleton swarm node discovers peers anyway

### ISSUE THREAD

**Issue by petyaracz** [ethereum/go-ethereum#17708] opened 2018-09-19 15:48 UTC
#### System information

Geth version: 1.8.16-unstable
Swarm version: 0.3.4-unstable
OS & Version: OSX 10.13.2

#### Expected behaviour

I run a singleton node:

`swarm --bzzaccount $BZZKEY --datadir $DATADIR --maxpeers 0 --nodiscover`

No peer nodes are loaded.

#### Actual behaviour

When I check in the geth console

`geth attach $BZZIPC
admin.peers`

It lists a bunch of peers -- I matched an id to a node running on swarm-gateways.net.

This has come up before -- apparently, even with --nodiscover, I need to delete bzz-peers.json so that my node doesn't pull in peers.

I can't find `bzz-peers.json` anywere. It should be in `$DATADIR/swarm/$BZZKEY` but it isn't.

When I run `geth` with the same parameters (`--maxpeers 0 --nodiscover`) it finds no nodes (works as expected).

#### Steps to reproduce the behaviour

`swarm --bzzaccount $BZZKEY --datadir $DATADIR --maxpeers 0 --nodiscover`

and then see if it found peers.

**Comment by nolash** [comment] 2018-09-20 15:52
duplicate of https://github.com/ethersphere/go-ethereum/issues/864

**Closed by nolash** 2018-09-20 15:52 UTC
Labels: bug, network, swarm
