### ISSUE TITLE
not catching up

### ISSUE THREAD

**Issue by jpritikin** [ethereum/go-ethereum#968] opened 2015-05-13 22:19 UTC
geth v0.9.20 on Tanglu Linux (Debian derivative)

````
I0513 18:15:55.541110   32360 backend.go:239] Protocol Version: 60, Network Id: 0
I0513 18:15:55.541152   32360 backend.go:249] Blockchain DB Version: 2
I0513 18:15:55.542061   32360 chain_manager.go:235] Last block (#321210) 483f39c2e40e5fee9ccf77c326b8031db49e055d8979fb120e258a04488b6bc9 TD=26520852245630
I0513 18:15:55.997477   32360 cmd.go:107] Starting  Geth/v0.9.20-8e24378c/linux/go1.4.2
I0513 18:15:55.997575   32360 server.go:209] Starting Server
2015/05/13 18:15:57 ssdp: got unexpected search target result "urn:schemas-upnp-org:device:WANConnectionDevice:1"
2015/05/13 18:15:57 ssdp: got unexpected search target result "urn:schemas-upnp-org:device:WANConnectionDevice:1"
2015/05/13 18:15:57 ssdp: got unexpected search target result "urn:schemas-upnp-org:device:WANConnectionDevice:1"
I0513 18:15:57.652844   32360 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered
I0513 18:15:57.675485   32360 udp.go:189] Listening, enode://b820c9f02cf880d162e24e42a55f868c3e69bd92324476eec675a52ca2bea43bdbc0be2def6be900b6d1a851c1724f11d48514dcb4cdadee53788fea47796729@73.171.34.52:30303
I0513 18:15:57.675560   32360 backend.go:456] Server started
I0513 18:15:57.675554   32360 server.go:349] Listening on [::]:30303
I0513 18:15:57.675616   32360 miner.go:52] Starting mining operation (CPU=8 TOT=8)
I0513 18:15:57.675882   32360 worker.go:337] commit new work on block 321211 with 0 txs & 0 uncles
I0513 18:15:57.675996   32360 ethash.go:185] Generating DAG for epoch 10 (9b2baad7528ecec612c5751a6bd525905892d7892e155c3b05e61363154a940b)
I0513 18:15:58.508046   32360 ethash.go:202] Done generating DAG for epoch 10, it took 832.086167ms
I0513 18:16:28.660640   32360 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 1.559410846s. #321211 [222656fb / 222656fb]
I0513 18:16:28.660703   32360 worker.go:226] 🔨  Mined block #321211
I0513 18:16:28.661350   32360 worker.go:337] commit new work on block 321212 with 0 txs & 0 uncles
````

Then it just sits there for a long time. According to https://stats.ethdev.com/, The best block is 325,833.

**Comment by tgerring** [comment] 2015-05-13 22:35
Can you quantify "long"? Sometimes it takes a few minutes to get peers and start sync'ing.

Check the peer count with `net.peetCount` on the console

**Comment by jpritikin** [comment] 2015-05-13 23:04
I guess "undefined" means zero?

**Comment by jpritikin** [comment] 2015-05-13 23:07
D'oh! You spelled it wrong. It's `net.peerCount` and its 4 just now.

````
I0513 19:06:57.862774    1932 chain_manager.go:558] INVALID block #321211 (b8012b269c9d090b8c0dbd179d91fd171cd0245fba765617530c4c6e8ed12556)
I0513 19:06:57.862932    1932 chain_manager.go:559] invalid merkle root. received=489cc3aae274995a9dc72a77f4306b2ffcf4d0b615aed5d9ebd92ab306941f98 got=3a1dff3d9a86856d0cd8259ab0095c5bc56b9bffe7934ed13c6323fe90d1b523
I0513 19:06:57.863040    1932 sync.go:104] Synchronisation failed: block downloading cancelled (requested)
````

**Comment by jpritikin** [comment] 2015-05-13 23:26
Almost 20 minutes of the same messages,

````
I0513 19:26:14.366563    1932 chain_manager.go:558] INVALID block #321211 (b8012b269c9d090b8c0dbd179d91fd171cd0245fba765617530c4c6e8ed12556)
I0513 19:26:14.366617    1932 chain_manager.go:559] invalid merkle root. received=489cc3aae274995a9dc72a77f4306b2ffcf4d0b615aed5d9ebd92ab306941f98 got=3a1dff3d9a86856d0cd8259ab0095c5bc56b9bffe7934ed13c6323fe90d1b523
I0513 19:26:14.366734    1932 sync.go:104] Synchronisation failed: block downloading cancelled (requested)
````

**Comment by jpritikin** [comment] 2015-05-13 23:51
Well, I'm going to give up for now. I am happy to restart geth if you have some new ideas.

**Comment by karalabe** [comment] 2015-05-14 10:23
I've encountered a similar issue yesterday night but didn't have time to debug it and by today it sorted itself out. A wild guess is that one of you peers is sending an invalid block, and since only a handful of connections, you always retry to fetch from the same peer.

We should definitely look into penalizing the peer (or even completely dumping it it it sends invalid blocks). I'll look into this but I'll have to come up with a test that can consistently reproduce this otherwise it's just fiddling in the dark.

**Comment by jpritikin** [comment] 2015-05-14 11:48
I didn't run geth all night. This morning I tried again with v0.8.5-2-2128-g7fa7409

````
I0514 07:46:13.146478   17705 chain_manager.go:558] INVALID block #321211 (b8012b269c9d090b8c0dbd179d91fd171cd0245fba765617530c4c6e8ed12556)
I0514 07:46:13.146547   17705 chain_manager.go:559] invalid merkle root. received=489cc3aae274995a9dc72a77f4306b2ffcf4d0b615aed5d9ebd92ab306941f98 got=3a1dff3d9a86856d0cd8259ab0095c5bc56b9bffe7934ed13c6323fe90d1b523
I0514 07:46:13.146622   17705 sync.go:104] Synchronisation failed: block downloading cancelled (requested)

> net.peerCount
12
````

Should I wait longer? It just seems to stay stuck at this point.

**Comment by obscuren** [comment] 2015-05-14 11:59
Which version is this?

**Comment by jpritikin** [comment] 2015-05-14 12:11
What is `upgradedb`? How do I run it?

**Comment by obscuren** [comment] 2015-05-14 12:19
There was a bug with everything below `0.9.20`. Please run `geth upgradedb` and continue normal operation when it's done.

**Comment by jpritikin** [comment] 2015-05-14 13:36
Well, I'm not sure `upgradedb` saved any time over starting from scratch, but I geth is caught up again. Thanks.

**Comment by karalabe** [comment] 2015-05-14 15:30
I'll close this issue then, but please reopen if the issue appears.

**Closed by karalabe** 2015-05-14 15:30 UTC
Labels: bug
