### ISSUE TITLE
Importing presale wallet creates files twice

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#1440] opened 2015-07-08 12:53 UTC
I just imported my presale wallet as test and it creates twice the same key file.
Both a few seconds after each other.

I guess it creates a file once on running (`geth wallet import ...`), and then after i entered my password.

<img width="597" alt="screen shot 2015-07-08 at 14 47 54" src="https://cloud.githubusercontent.com/assets/232662/8570482/d19406ac-2580-11e5-9157-925f898d36e4.png">

**Additionally i think file or folder names should never contain `/` as this is a path separator character and will only lead to odd problems on some OS!**
And the `UTC--` i not necessary as `Z` says UTC. I would name it as follows:
`2015-07-08T12-44-25-579996753Z--b1a2b43a7433dd150bb82227ed519cd6b142d382`

**Comment by frozeman** [comment] 2015-07-08 12:56
And i hope the first file is not my key without password! :|

**Comment by jorisbontje** [comment] 2015-07-08 14:16
Duplicate of #1411

**Comment by zelig** [comment] 2015-07-09 16:26
fixed in #1453

**Closed by zelig** 2015-07-09 16:26 UTC
Labels: bug
