### ISSUE TITLE
rpc.Client#Unsubscribe blocks indefinitely when shutdown w node

### ISSUE THREAD

**Issue by dimroc** [ethereum/go-ethereum#17837] opened 2018-10-04 11:22 UTC
Hi there!
While developing [Chainlink](https://github.com/smartcontractkit/chainlink), which uses go-ethereum's rpc.Client libraries, we were unable to gracefully shutdown our node. We've traced it back to our inability to [`Unsubscribe`](https://github.com/ethereum/go-ethereum/blob/127553253e8d21cfbcd38edf3119ce81275c0454/rpc/client.go#L749) our websocket rpc.Client. We've reproduced the problem using exclusively `go-ethereum` code and appreciate any insight. We're also open to fixing the bug ourselves if pointed in the right direction.

Thanks in advance for any help.

#### System information

Geth version:
Version: 1.8.16-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11
Operating System: darwin
GOPATH=/Users/dimroc/go
GOROOT=/usr/local/Cellar/go/1.11/libexec

OS & Version: OSX

#### Expected behaviour
[`*rpc.Client#Unsubscribe`](https://github.com/ethereum/go-ethereum/blob/127553253e8d21cfbcd38edf3119ce81275c0454/rpc/client.go#L749) returns and does not block indefinitely.

#### Actual behaviour
[`*rpc.Client#Unsubscribe`](https://github.com/ethereum/go-ethereum/blob/127553253e8d21cfbcd38edf3119ce81275c0454/rpc/client.go#L749) blocks indefinitely.

#### Steps to reproduce the behaviour

[![asciicast](https://asciinema.org/a/204548.png)](https://asciinema.org/a/204548)

For a preconfigured reproduction, please see: https://github.com/dimroc/geth-blocks-unsubscribe

1. Run geth 
2. Run and attach a go-ethereum client
3. subscribe to newHeads and logs
4. Listen to a handful of heads and logs
5. Kill all processes simultaneously
6. Run `ps` and notice the client is blocked.
7. Use [dlv](https://github.com/derekparker/delve) to investigate.

Again, this is set up and done for you in https://github.com/dimroc/geth-blocks-unsubscribe.

This issue is spurious, but in practice it reproduces 75% of the time.

#### Backtrace

```
(dlv) stack
 0  0x000000000402fa3b in runtime.gopark
    at /usr/local/Cellar/go/1.11/libexec/src/runtime/proc.go:303
 1  0x000000000403ef1d in runtime.selectgo
    at /usr/local/Cellar/go/1.11/libexec/src/runtime/select.go:313
 2  0x000000000430dcc7 in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*Client).send
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:460
 3  0x000000000430c965 in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*Client).CallContext
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:301
 4  0x000000000430c5ff in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*Client).Call
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:283
 5  0x000000000431095d in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*ClientSubscription).requestUnsubscribe
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:832
 6  0x000000000431327d in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*ClientSubscription).quitWithError.func1
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:761
 7  0x0000000004070403 in sync.(*Once).Do
    at /usr/local/Cellar/go/1.11/libexec/src/sync/once.go:44
 8  0x000000000430ff55 in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*ClientSubscription).quitWithError
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:755
 9  0x000000000430fe98 in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*ClientSubscription).Unsubscribe
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:750
10  0x00000000043148a6 in main.main
    at ./main.go:47
11  0x000000000402f647 in runtime.main
    at /usr/local/Cellar/go/1.11/libexec/src/runtime/proc.go:201
12  0x000000000405b381 in runtime.goexit
    at /usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333
````

**Comment by dimroc** [comment] 2018-10-04 11:37
Code to reproduce the issue is here: https://github.com/dimroc/geth-blocks-unsubscribe/blob/master/main.go

```golang
func main() {
	eth := connectToEth()

	var wg sync.WaitGroup
	logs := make(chan types.Log)
	heads := make(chan types.Header)
	done := make(chan struct{})

	wg.Add(1)
	go listen(logs, heads, done, &wg)
	headsSub := subscribeToHeads(eth, heads)
	logsSub := subscribeToLogs(eth, logs, filterQueryFor(nil))

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	<-sigs

	headsSub.Unsubscribe() // When called simultaneously with eth node shutdown, blocks indefinitely.
	logsSub.Unsubscribe()  // When called simultaneously with eth node shutdown, blocks indefinitely.
	close(done)            // In successful repro, this never gets called.
	wg.Wait()              // In successful repro, this never gets called.
	close(logs)
	close(heads)
}
```

**Comment by fjl** [comment] 2018-10-11 11:28
Thank you for the reproducer! The issue is fixed in the linked PR.

**Comment by dimroc** [comment] 2018-10-11 13:04
Thanks @fjl

**Closed** 2018-10-15 08:56 UTC

**Comment by dimroc** [comment] 2019-06-28 20:10
Hi all, it seems like this bug has reappeared in the latest release 1.8.27: https://asciinema.org/a/lc2VEuz0zhCLWE4dkkoBdd4Hg

https://github.com/dimroc/geth-blocks-unsubscribe
