### ISSUE TITLE
error: no suitable peers available docker ethereum light sync mode 

### ISSUE THREAD

**Issue by encryptblockr** [ethereum/go-ethereum#26247] opened 2022-11-24 01:30 UTC
I am having issues running an ethereum node with `light` sync mode

tested with this test curl command

```
$ curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x407d73d8a49eeb85d32cf465507dd71d507100c1", "latest"],"id":1}' 10.10.10.201:8545
```

here is what shows up in the docker logs

```
INFO [11-23|18:25:26.732] Looking for peers                        peercount=2 tried=3  static=0
INFO [11-23|18:25:37.223] Looking for peers                        peercount=2 tried=6  static=0
INFO [11-23|18:25:48.657] Looking for peers                        peercount=2 tried=5  static=0
INFO [11-23|18:25:58.659] Looking for peers                        peercount=2 tried=6  static=0
INFO [11-23|18:26:08.674] Looking for peers                        peercount=2 tried=5  static=0
INFO [11-23|18:26:18.732] Looking for peers                        peercount=2 tried=5  static=0
INFO [11-23|18:26:28.733] Looking for peers                        peercount=2 tried=3  static=0
INFO [11-23|18:26:38.734] Looking for peers                        peercount=2 tried=8  static=0
INFO [11-23|18:26:48.815] Looking for peers                        peercount=2 tried=6  static=0
INFO [11-23|18:26:59.019] Looking for peers                        peercount=2 tried=4  static=0
INFO [11-23|18:27:09.165] Looking for peers                        peercount=2 tried=6  static=0
INFO [11-23|18:27:19.399] Looking for peers                        peercount=2 tried=5  static=0
INFO [11-23|18:27:31.070] Looking for peers                        peercount=2 tried=3  static=0
INFO [11-23|18:27:42.390] Looking for peers                        peercount=2 tried=5  static=0
INFO [11-23|18:27:52.736] Looking for peers                        peercount=2 tried=6  static=0
INFO [11-23|18:28:02.822] Looking for peers                        peercount=2 tried=6  static=0
INFO [11-23|18:28:12.990] Looking for peers                        peercount=2 tried=6  static=0
INFO [11-23|18:28:23.091] Looking for peers                        peercount=2 tried=2  static=0
INFO [11-23|18:28:34.400] Looking for peers                        peercount=2 tried=8  static=0
INFO [11-23|18:28:46.152] Looking for peers                        peercount=2 tried=4  static=0
INFO [11-23|18:28:56.155] Looking for peers                        peercount=2 tried=5  static=0
INFO [11-23|18:29:06.395] Looking for peers                        peercount=2 tried=6  static=0
INFO [11-23|18:29:17.098] Looking for peers                        peercount=2 tried=4  static=0
INFO [11-23|18:29:27.812] Looking for peers                        peercount=2 tried=6  static=0
INFO [11-23|18:29:37.823] Looking for peers                        peercount=2 tried=7  static=0
INFO [11-23|18:31:27.689] New local node record                    seq=1,669,180,663,206 id=7ca42d1e4c722429 ip=99.111.251.102 udp=17809 tcp=30303
INFO [11-23|18:40:58.023] New local node record                    seq=1,669,180,663,207 id=7ca42d1e4c722429 ip=99.111.251.102 udp=30303 tcp=30303
INFO [11-23|18:53:19.328] New local node record                    seq=1,669,180,663,208 id=7ca42d1e4c722429 ip=99.111.251.102 udp=10268 tcp=30303
INFO [11-23|19:00:17.267] New local node record                    seq=1,669,180,663,209 id=7ca42d1e4c722429 ip=99.111.251.102 udp=44235 tcp=30303
WARN [11-23|19:01:40.701] Served eth_getBalance                    conn=192.168.1.253:56707 reqid=1 duration=3.011071545s err="getDeleteStateObject (407d73d8a49eeb85d32cf465507dd71d507100c1) error: no suitable peers available"
INFO [11-23|19:04:12.909] New local node record                    seq=1,669,180,663,210 id=7ca42d1e4c722429 ip=99.111.251.102 udp=30303 tcp=30303
INFO [11-23|19:05:59.984] New local node record                    seq=1,669,180,663,211 id=7ca42d1e4c722429 ip=99.111.251.102 udp=15257 tcp=30303
INFO [11-23|19:14:28.254] New local node record                    seq=1,669,180,663,212 id=7ca42d1e4c722429 ip=99.111.251.102 udp=30303 tcp=30303
INFO [11-23|19:18:50.457] New local node record                    seq=1,669,180,663,213 id=7ca42d1e4c722429 ip=99.111.251.102 udp=11345 tcp=30303
INFO [11-23|19:27:42.528] New local node record                    seq=1,669,180,663,214 id=7ca42d1e4c722429 ip=99.111.251.102 udp=30303 tcp=30303
INFO [11-23|19:47:22.732] New local node record                    seq=1,669,180,663,215 id=7ca42d1e4c722429 ip=99.111.251.102 udp=34844 tcp=30303
INFO [11-23|19:57:51.474] New local node record                    seq=1,669,180,663,216 id=7ca42d1e4c722429 ip=99.111.251.102 udp=8414  tcp=30303
WARN [11-23|20:15:29.782] Served eth_getBalance                    conn=192.168.1.253:57028 reqid=1 duration=3.001515781s err="getDeleteStateObject (407d73d8a49eeb85d32cf465507dd71d507100c1) error: no suitable peers available"
INFO [11-23|20:34:55.544] New local node record                    seq=1,669,180,663,217 id=7ca42d1e4c722429 ip=99.111.251.102 udp=30303 tcp=30303
INFO [11-23|20:48:14.415] New local node record                    seq=1,669,180,663,218 id=7ca42d1e4c722429 ip=99.111.251.102 udp=37247 tcp=30303
INFO [11-23|21:02:04.256] New local node record                    seq=1,669,180,663,219 id=7ca42d1e4c722429 ip=99.111.251.102 udp=29414 tcp=30303
INFO [11-23|21:15:00.222] New local node record                    seq=1,669,180,663,220 id=7ca42d1e4c722429 ip=99.111.251.102 udp=30303 tcp=30303
INFO [11-23|21:30:54.213] New local node record                    seq=1,669,180,663,221 id=7ca42d1e4c722429 ip=99.111.251.102 udp=50185 tcp=30303
INFO [11-23|21:36:04.607] New local node record                    seq=1,669,180,663,222 id=7ca42d1e4c722429 ip=99.111.251.102 udp=38676 tcp=30303
INFO [11-23|21:46:14.511] New local node record                    seq=1,669,180,663,223 id=7ca42d1e4c722429 ip=99.111.251.102 udp=30303 tcp=30303
INFO [11-23|21:54:13.919] New local node record                    seq=1,669,180,663,224 id=7ca42d1e4c722429 ip=99.111.251.102 udp=43642 tcp=30303
INFO [11-23|22:00:40.354] New local node record                    seq=1,669,180,663,225 id=7ca42d1e4c722429 ip=99.111.251.102 udp=30303 tcp=30303
INFO [11-23|22:03:22.743] New local node record                    seq=1,669,180,663,226 id=7ca42d1e4c722429 ip=99.111.251.102 udp=55468 tcp=30303
INFO [11-23|22:14:55.174] New local node record                    seq=1,669,180,663,227 id=7ca42d1e4c722429 ip=99.111.251.102 udp=30303 tcp=30303
INFO [11-23|22:41:59.846] New local node record                    seq=1,669,180,663,228 id=7ca42d1e4c722429 ip=99.111.251.102 udp=47655 tcp=30303
WARN [11-23|22:43:51.510] Served eth_getBalance                    conn=192.168.1.253:57802 reqid=1 duration=3.004127109s err="getDeleteStateObject (407d73d8a49eeb85d32cf465507dd71d507100c1) error: no suitable peers available"
```

here is the docker-compose file i used

```
version: '3.9'

services:
  ethereum-node:
    image: ethereum/client-go
    restart: always
    container_name: ethereum-node
    command: ["--syncmode=light","--ws", "--ws.addr=0.0.0.0", "--ws.origins=*", "--http", "--http.addr=0.0.0.0", "--http.vhosts=*", "--graphql", "--graphql.vhosts=*", "--metrics", "--mainnet", "--maxpeers=32", "--datadir=/root/.ethereum"]
    volumes:
      - ethereum-node-data:/root/.ethereum
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      
volumes:
  ethereum-node-data:
    name: ethereum-node-data
```

what do i need to do to get this node running?

**Comment by ligi** [comment] 2022-11-27 01:47
duplicate of #25623

**Closed by ligi** 2022-11-27 01:47 UTC
Labels: type:docs
