### ISSUE TITLE
eth.getBlock('pending').number always returns the same as eth.BlockNumber

### ISSUE THREAD

**Issue by SimonOrdo** [ethereum/go-ethereum#23207] opened 2021-07-13 20:50 UTC
I'm running a private GETH node (BSC).  Anytime I check `eth.getBlock('pending').number` it always returns the same as `eth.BlockNumber` .  Is it required for a node to be mining in order to see gossipped pending transactions like this?

**Comment by rjl493456442** [comment] 2021-07-14 02:47
I can't reproduce your issue. 

```
> eth.blockNumber
12818989

> eth.getBlock("pending")
{
  difficulty: 6227054657967480,
  extraData: "0xd883010a05846765746888676f312e31352e32856c696e7578",
  gasLimit: 14970672,
  gasUsed: 0,
  hash: null,
  logsBloom: "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: null,
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: null,
  number: 12818990,
  parentHash: "0x0a9bb75585ced6f9c49945ca57fc1b4cd219f6e7face3b30ad38d481fc7477a5",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 543,
  stateRoot: "0xaad2de71012eec5cfa31b9411ba9c99e034af7b10a55ed0375160dd02a5537e0",
  timestamp: 1626230722,
  totalDifficulty: 0,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
```

The console API works for me. Since you are running the BSC they may introduce some changes in the miner package. Would be nice to open the issue at their repo.

**Comment by rjl493456442** [comment] 2021-07-14 02:48
Close it now. Feel free to reopen it if it's an issue in the Geth.

**Closed by rjl493456442** 2021-07-14 02:48 UTC
Labels: type:docs

**Comment by SimonOrdo** [comment] 2021-07-14 06:13
> I can't reproduce your issue.
> 
> ```
> > eth.blockNumber
> 12818989
> 
> > eth.getBlock("pending")
> {
>   difficulty: 6227054657967480,
>   extraData: "0xd883010a05846765746888676f312e31352e32856c696e7578",
>   gasLimit: 14970672,
>   gasUsed: 0,
>   hash: null,
>   logsBloom: "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
> 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
> 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>   miner: null,
>   mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
>   nonce: null,
>   number: 12818990,
>   parentHash: "0x0a9bb75585ced6f9c49945ca57fc1b4cd219f6e7face3b30ad38d481fc7477a5",
>   receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
>   size: 543,
>   stateRoot: "0xaad2de71012eec5cfa31b9411ba9c99e034af7b10a55ed0375160dd02a5537e0",
>   timestamp: 1626230722,
>   totalDifficulty: 0,
>   transactions: [],
>   transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   uncles: []
> }
> ```
> 
> The console API works for me. Since you are running the BSC they may introduce some changes in the miner package. Would be nice to open the issue at their repo.

@rjl493456442 Thank you.  Can you tell me if the node is required to be "mining" in order for `eth.getBlock('pending')` to function as per your example?  Requesting pending transactions via `txpool_content` and PendingTransactionFilter works, but this particular call does not.

**Comment by rjl493456442** [comment] 2021-07-14 06:25
@SimonOrdo It's not required. Even if the mining is not enabled, the pending block is always available for other purposes.
