### ISSUE TITLE
Why do i get "nonce too high" on debug.traceTransaction

### ISSUE THREAD

**Issue by moda20** [ethereum/go-ethereum#23160] opened 2021-07-05 08:48 UTC
I am trying to trace a transaction using the geth js console with `debug.traceTransaction`.  and all the time I do that I get the error :

```
<OtherTxHash> failed: nonce too high: address <OtherAddress>, tx: 938 state: 0
``` 
the other transaction just happens to be part of the same block as my transaction. and I get this error all the time with any transaction I try to trace.  Am I missing something?

**Comment by MariusVanDerWijden** [comment] 2021-07-05 09:22
Could you add a transaction/block that this happens on? Also which version of geth are you using?

**Comment by moda20** [comment] 2021-07-09 13:41
i am trying with this transaction : 0x838065e907fa27d9a5ac836b04939d5d2559f74b811c3cc0e62bd4164a11d87f
and this is my payload : 
```
payload={"id":1,"jsonrpc":"2.0","method": "debug_traceTransaction", "params": [transactionHash, {"tracer":"callTracer"}]}
```

**Comment by s1na** [comment] 2021-07-20 11:45
I can't find this txhash in any of the networks. Can you post the block hash too?

In your first comment you say you get this error all the time for different transactions. Is the address which has "nonce too high" the same or different too?

**Comment by xloem** [comment] 2021-08-03 13:47
I am getting this error.  The transaction i am trying to trace is 0xd10128eeda98d108e1f5bf7d1877343256e589503b6ad507b782303e98dbe833 in block 0x5089d03f409176fed70c8c40e8efd5ad2ddd6557f4d78f4659caf5d7d4887169 .

**Comment by MariusVanDerWijden** [comment] 2021-08-16 05:46
Hmm can repro with @xloem's transaction.
```
 debug.traceTransaction("0xd10128eeda98d108e1f5bf7d1877343256e589503b6ad507b782303e98dbe833")
WARN [08-16|07:41:16.593] Served debug_traceTransaction            reqid=8 t=4.989119256s err="transaction 0x4e103f863667acd2711691cb659e039e52319dc6dbf9928560021e45c63e22cc failed: nonce too high: address 0xb7aB1DE5b259a880c4BB5451bDbE6f80F3798538, tx: 7926 state: 0"
Error: transaction 0x4e103f863667acd2711691cb659e039e52319dc6dbf9928560021e45c63e22cc failed: nonce too high: address 0xb7aB1DE5b259a880c4BB5451bDbE6f80F3798538, tx: 7926 state: 0
	at web3.js:6357:37(47)
	at web3.js:5091:62(37)
	at <eval>:1:23(4)
```

**Comment by holiman** [comment] 2021-11-03 15:32
Tracing in lightclient mode is flaky. Is it supposed to work, though, @rjl493456442 ?

**Comment by shekhirin** [comment] 2021-11-04 19:56
I think I figured it out. I can reproduce the same error with
```javascript
> eth.getStorageAt("0x407d73d8a49eeb85d32cf465507dd71d507100c1", 0, 12951935)
Error: getDeleteStateObject (407d73d8a49eeb85d32cf465507dd71d507100c1) error: no suitable peers available
	at web3.js:6357:37(47)
	at web3.js:5091:62(37)
	at <eval>:1:17(6)
```

It happens while geth is trying to query for block's state. Since this block is too far in the past (more than 600k blocks before current one), not every peer can process the request because non-archive nodes doesn't have all versions of state data.

Here's the place where `serveRecentState` variable is set:
https://github.com/ethereum/go-ethereum/blob/854f068ed60918c624857594a703a6724b8efb3a/les/peer.go#L1059-L1065

And here's the place where check for availability of peer's state at block N happens:
https://github.com/ethereum/go-ethereum/blob/854f068ed60918c624857594a703a6724b8efb3a/les/peer.go#L538-L555

---

The only thing I can propose now is to improve the error message because now it doesn't say anything about the reason why no suitable peers were found. @holiman what do you think, will it be useful?

**Comment by bglmmz** [comment] 2022-06-07 01:45
here is my error messsage 
`
> debug.traceTransaction("0x1ca0c1aa96e07aecb4793d0b7168bcea127c0a97c483f6d8bd28f36cde77e7ec")
Error: tracing failed: nonce too high
    at web3.js:3456:20
    at web3.js:6304:15
    at web3.js:5410:36
    at <anonymous>:1:1
`

**Comment by gzliudan** [comment] 2023-04-27 06:05
Is this bug fixed now ?

**Comment by holiman** [comment] 2023-04-27 07:42
Geth currently does not even support light clients, post-merge. 

> Reproduced using debug_traceBlockByNumber rpc in bnb-chain, block 26613398.

And we don't support bnb-chain.

**Closed by holiman** 2023-04-27 07:42 UTC
Labels: type:docs
