### ISSUE TITLE
looping around invalid block and unable to sync blockchain

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#693] opened 2015-04-10 20:36 UTC
develop f047699

```
Welcome to the FRONTIER
I0410 13:30:21.010953   32223 backend.go:180] Protocol Version: 60, Network Id: 0
I0410 13:30:21.012009   32223 chain_manager.go:186] Last block (#67042) fd257c7081307ffe29345eb1a3a779c7e94fc3399f68e2acd7da101f49d74732 TD=103303377364
I0410 13:30:21.377061   32223 ethash.go:94] Making cache
I0410 13:30:22.507225   32223 ethash.go:99] Took: 1.130094339s
I0410 13:30:22.511881   32223 cmd.go:116] Starting  Geth/v0.9.9/linux/go1.4.2
I0410 13:30:22.511977   32223 server.go:170] Starting Server
I0410 13:30:23.085759   32223 udp.go:157] Listening, enode://c3bd9a1fc3964a9744ed290e903f4cdf525df8b78396f0e0e07d82bc1c9007a445b5331ab3b78d3d29c2f7ce5423bbc3a1ecdfc08e47d4036972d57edde73901@[::]:30304
I0410 13:30:23.085994   32223 nat.go:94] mapping error: no devices discovered
I0410 13:30:23.086029   32223 blockpool.go:269] Blockpool started
I0410 13:30:23.086040   32223 whisper.go:72] Whisper started
I0410 13:30:23.086034   32223 nat.go:94] mapping error: no devices discovered
I0410 13:30:23.086053   32223 backend.go:383] Server started
I0410 13:30:23.086106   32223 server.go:286] Listening on [::]:30304
I0410 13:30:46.697359   32223 chain_manager.go:480] INVALID block #67043 (e3b7195c)
I0410 13:30:46.697386   32223 chain_manager.go:481] gas used error (114540 / 114097)
I0410 13:30:46.697401   32223 errors.go:82] [Blockpool] Invalid block: [gas used error (114540 / 114097)]
2015/04/10 13:30:46 [Blockpool] invalid block d248a85d3fae0573c0ac021ecb18b13d0279c6539a01de6d54429de42a7ef9cd
2015/04/10 13:30:46 [Blockpool] penalise peers d5b16a8cb954ce5d (hash), d5b16a8cb954ce5d (block)
I0410 13:30:53.783222   32223 chain_manager.go:480] INVALID block #67043 (e3b7195c)
I0410 13:30:53.783264   32223 chain_manager.go:481] gas used error (114540 / 114097)
I0410 13:30:53.783278   32223 errors.go:82] [Blockpool] Invalid block: [gas used error (114540 / 114097)]
2015/04/10 13:30:53 [Blockpool] invalid block d248a85d3fae0573c0ac021ecb18b13d0279c6539a01de6d54429de42a7ef9cd
2015/04/10 13:30:53 [Blockpool] penalise peers d5b16a8cb954ce5d (hash), d5b16a8cb954ce5d (block)
I0410 13:30:59.706763   32223 chain_manager.go:480] INVALID block #67043 (e3b7195c)
I0410 13:30:59.706798   32223 chain_manager.go:481] gas used error (114540 / 114097)
I0410 13:30:59.706814   32223 errors.go:82] [Blockpool] Invalid block: [gas used error (114540 / 114097)]
2015/04/10 13:30:59 [Blockpool] invalid block d248a85d3fae0573c0ac021ecb18b13d0279c6539a01de6d54429de42a7ef9cd
2015/04/10 13:30:59 [Blockpool] penalise peers d5b16a8cb954ce5d (hash), d5b16a8cb954ce5d (block)
I0410 13:31:05.704960   32223 chain_manager.go:480] INVALID block #67043 (e3b7195c)
I0410 13:31:05.704996   32223 chain_manager.go:481] gas used error (114540 / 114097)
I0410 13:31:05.705010   32223 errors.go:82] [Blockpool] Invalid block: [gas used error (114540 / 114097)]
2015/04/10 13:31:05 [Blockpool] invalid block d248a85d3fae0573c0ac021ecb18b13d0279c6539a01de6d54429de42a7ef9cd
2015/04/10 13:31:05 [Blockpool] penalise peers d5b16a8cb954ce5d (hash), d5b16a8cb954ce5d (block)
I0410 13:31:51.818546   32223 chain_manager.go:480] INVALID block #67043 (e3b7195c)
I0410 13:31:51.818583   32223 chain_manager.go:481] gas used error (114540 / 114097)
I0410 13:31:51.818610   32223 errors.go:82] [Blockpool] Invalid block: [gas used error (114540 / 114097)]
2015/04/10 13:31:51 [Blockpool] invalid block 2ed210fbd72c51c5952f4da3c60c93cb5b298794c46641b0c98e8310edb59f8d
2015/04/10 13:31:51 [Blockpool] penalise peers 487611428e6c99a1 (hash), 487611428e6c99a1 (block)
I0410 13:32:23.225143   32223 chain_manager.go:480] INVALID block #67043 (e3b7195c)
I0410 13:32:23.225187   32223 chain_manager.go:481] gas used error (114540 / 114097)
I0410 13:32:23.225200   32223 errors.go:82] [Blockpool] Invalid block: [gas used error (114540 / 114097)]
2015/04/10 13:32:23 [Blockpool] invalid block 153faa89af19ee185b6e2c5cc926c9d67cd03b52dcc49ffe108212f38abe8d00
2015/04/10 13:32:23 [Blockpool] penalise peers bf1d38bbe00f43d3 (hash), bf1d38bbe00f43d3 (block)
I0410 13:32:37.041239   32223 chain_manager.go:480] INVALID block #67043 (e3b7195c)
I0410 13:32:37.041284   32223 chain_manager.go:481] gas used error (114540 / 114097)
I0410 13:32:37.041304   32223 errors.go:82] [Blockpool] Invalid block: [gas used error (114540 / 114097)]
2015/04/10 13:32:37 [Blockpool] invalid block 153faa89af19ee185b6e2c5cc926c9d67cd03b52dcc49ffe108212f38abe8d00
2015/04/10 13:32:37 [Blockpool] penalise peers e7746bc09a0bd0b4 (hash), e7746bc09a0bd0b4 (block)
```

I will delete my blockchain dir, but eventually probably should have some friendlier fix for user.  Sending obscuren my blockchain dir.

**Comment by ethers** [comment] 2015-04-10 21:02
killed the chain and resynced and stuck on 70625 for 5+ mins

```
I0410 13:54:30.693268    1302 chain_manager.go:544] imported 256 block(s) 0 queued in 1.099538999s. #70107 [20e30a38 / 0967fd5f]
I0410 13:54:31.784567    1302 chain_manager.go:544] imported 256 block(s) 0 queued in 1.091084362s. #70363 [209d058b / 24789c37]
I0410 13:54:32.860330    1302 chain_manager.go:544] imported 257 block(s) 0 queued in 1.075536411s. #70620 [48a75001 / 76b45384]
I0410 13:54:32.860527    1302 chain_manager.go:480] INVALID block #70625 (dbbe2726)
I0410 13:54:32.860540    1302 chain_manager.go:481] Block's parent unknown d9302e74374e9bdb5ce0971ad3a4319ec1db3b79c4335965f039239ee9281084
I0410 13:54:32.860557    1302 errors.go:82] [Blockpool] Invalid block: [Block's parent unknown d9302e74374e9bdb5ce0971ad3a4319ec1db3b79c4335965f039239ee9281084]
2015/04/10 13:54:32 [Blockpool] invalid block 9116c564e617d57d8e9fb26ebb9ac9fb4e24c9ccb2989b22b98913dcea0321f1
2015/04/10 13:54:32 [Blockpool] penalise peers d5b16a8cb954ce5d (hash), d5b16a8cb954ce5d (block)
```

**Comment by obscuren** [comment] 2015-04-10 22:18
The two errors do not relate

**Comment by zelig** [comment] 2015-04-12 13:04
ok so the first issue of looping is caused by not disconnecting the offending peer .
this is because @obscuren commented out https://github.com/ethereum/go-ethereum/blob/f047699afbf4773cc9ab37e61af7d72564a12008/eth/protocol.go#L386
the unknown parent issue is real caused by a stupid forgotten lock, to be fixed in the next PR.
it's an intermittent datarace issue, so you should be able to restart geth and pray :)

**Comment by obscuren** [comment] 2015-04-13 19:18
Closing. Is fixed in https://github.com/ethereum/go-ethereum/pull/702

**Closed by obscuren** 2015-04-13 19:18 UTC
