### ISSUE TITLE
Snapshots cannot be disabled via TOML, only via CLI arguments

### ISSUE THREAD

**Issue by du2zy** [ethereum/go-ethereum#22571] opened 2021-03-25 09:25 UTC
I use geth.toml to configure the node.

After updating to 1.10.1 version I executed command:

```
geth --snapshot=false ... dumpconfig > geth.toml
```

After that I started the node.

Flag `--snapshot=false` affects one line in config, I didn't notice any other changes:

```
SnapshotCache = 0
```

After yesterday's fork (Berlin), my node is not available and I see the following:

```
INFO [03-25|08:20:25.693] Generating state snapshot                root="8fb9ce…b7b2aa" in="5e3c85…cedbc9" at="aa0694…11cc66" accounts=1929027 slots=46069585 storage=3.54GiB    elapsed=185h26m16.681s eta=318h19m3.436s
```

This brought me to a thought that my node generates snapshots now despite that I've disabled it earlier. I don't want to use this feature untill it starts to work correctly.

Snapshot generating will take many hours.

What did I do wrong? How can I guarantee myself not to face such problems using production node?

**Comment by du2zy** [comment] 2021-03-25 11:13
I started the node like this (listed arguments of a command line without using configuration file):

```
geth --snapshot=false --rinkeby ...
```

It seems that it worked. Anyway, I don't see any messages on snapshot generating.

There's some error in geth code or do I do something wrong?

What should I do next? I am wary of that after mainnet fork, I'll get my node stopped. Should I reject using configuration file but use command line arguments instead?

**Comment by karalabe** [comment] 2021-03-25 14:24
You'll need to provide some more logs. Generating state snapshot isn't something bad, it takes a while. Your node should still be functional in the mean time.

**Comment by du2zy** [comment] 2021-03-26 09:05
RPC was available, but the transactions were not sent to the network until I turned off snapshot generation.

The problem I want to report is that it is impossible to disable snapshots in the configuration file.

What additional logs do I need to attach?

**Comment by MariusVanDerWijden** [comment] 2021-04-07 06:41
Yeah, I can't reproduce this issue. The dumpconfig correctly sets `SnapshotCache = 0` which disables snapshot generation. 
```
./build/bin/geth --snapshot=false dumpconfig  2>/dev/null  > test.conf && ./build/bin/geth --config test.conf dumpconfig 2>/dev/null | grep "Snap"
SnapDiscoveryURLs = []
SnapshotCache = 0
```
It's a bit unfortunate that the SnapshotCache flag has two different responsibilities, but afaict the logic is correct.
The flag gets read normally and it disables snapshot generation on my node. Maybe it was a fluke, or the node was started with some half generated snapshot in memory. 
I'll close the issue for now, If you @du2zy, or someone else can reproduce it, feel free to reopen!

**Closed by MariusVanDerWijden** 2021-04-07 06:41 UTC
Labels: status:triage, type:bug

**Comment by Johnny0song** [comment] 2023-03-10 10:38
SnapshotCache是geth-config.toml中的一个参数，它指定了以太坊节点在处理快照（Snapshots）时所使用的缓存大小。

快照是以太坊区块链的一种状态的快照，它可以让节点在重新同步区块链时更快地进行。节点可以使用快照来避免从创世块开始重新下载整个区块链。

SnapshotCache参数指定了快照缓存的大小，以MB为单位。如果快照缓存大小为0，则表示节点不会使用快照缓存。

在默认情况下，SnapshotCache参数的值为1024MB。如果您的节点有足够的可用内存，您可以增加该值以提高快照处理的性能。然而，如果您的节点的内存较小，那么您应该降低该值以避免节点崩溃或出现其他性能问题。
