### ISSUE TITLE
The number of pending transactions is always equal to 1

### ISSUE THREAD

**Issue by sontol** [ethereum/go-ethereum#1387] opened 2015-07-03 04:50 UTC
Normally after sending some tx eth.getBlockTransaction("pending") will increase until the tx is mined. Currently the functions always return 1 even after a tx was sent locally. Affecting 0.9.32 and 0.9.35. Not sure where the bug is first introduced. Stats.ethdev.com confirms the observation. Judging by the number of tx mined per block (also=1) seems like the issue is real and not limited to reporting problem

**Comment by sontol** [comment] 2015-07-03 05:13
Correction: 0.9.32 is not affected

**Comment by obscuren** [comment] 2015-07-03 07:46
The amount of pending transaction for the next block is 1 because someone spams 1m gas txs and other txs won't fit in. I'm thinking about changing this simply to the max numbers of transactions in the transaction pool rather than whatever fits in the next block.

**Comment by sontol** [comment] 2015-07-03 08:02
Still very strange though, isn't the minimum gasLimit is pi million? I'm sending a tx with a few thousand gas into the block and it still won't go in.

**Comment by sontol** [comment] 2015-07-03 08:05
Oh, is that because of sorted by nonce thing? Shouldn't 2 1m gas tx fits into the block?

**Comment by obscuren** [comment] 2015-07-03 08:20
That's odd indeed. I'll test

**Comment by obscuren** [comment] 2015-07-03 09:34
So I just double checked, private chain, 3 transactions:

```
> eth.getBlock("pending").transactions
['0xa8987396423db68d188090bb5ee923f75ee7e8d809166d420dd1702d3014b8d0', '0x645b47b2a6f52e9874f9908c597560d8dfa8842c3b35d677a2d7aed484481be8', '0xb6a5a903f5d5ac762df4d5327013042d16cb51aa68880c5f71a6a569323e75f1' ]
```

When you're mining yourself and you create transactions, please know that transactions won't show up after the current block has been mined.

**Comment by obscuren** [comment] 2015-07-03 09:35
If you have any test case that reproduces the above mentioned behaviour please let me know and I'll test it.

**Comment by obscuren** [comment] 2015-07-03 15:35
Closing this issue. See discussion in #1376

**Closed by obscuren** 2015-07-03 15:35 UTC
