### ISSUE TITLE
mine on Frontier

### ISSUE THREAD

**Issue by pureland** [ethereum/go-ethereum#1532] opened 2015-07-27 07:44 UTC
I0727 07:42:54.304841    2935 remote_agent.go:107] Work was submitted for ebb155decb947f6108253a1d8c1ec6ea6bd584cb9d500797f2d4d5b3fafee3a4 but no pending work found
I0727 07:42:55.506471    2935 worker.go:281] Invalid header on mined block: GasLimit check failed for block 5000 (5000 > 0)
I0727 07:42:55.681407    2935 remote_agent.go:107] Work was submitted for ebb155decb947f6108253a1d8c1ec6ea6bd584cb9d500797f2d4d5b3fafee3a4 but no pending work found
I0727 07:42:56.731337    2935 worker.go:281] Invalid header on mined block: GasLimit check failed for block 5000 (5000 > 0)
I0727 07:42:57.601083    2935 worker.go:281] Invalid header on mined block: GasLimit check failed for block 5000 (5000 > 0)
I0727 07:42:57.870532    2935 worker.go:281] Invalid header on mined block: GasLimit check failed for block 5000 (5000 > 0)
I0727 07:42:58.739969    2935 worker.go:281] Invalid header on mined block: GasLimit check failed for block 5000 (5000 > 0)
I0727 07:42:59.036920    2935 worker.go:281] Invalid header on mined block: GasLimit check failed for block 5000 (5000 > 0)
I0727 07:43:00.151032    2935 worker.go:281] Invalid header on mined block: GasLimit check failed for block 5000 (5000 > 0)
I0727 07:43:00.626926    2935 worker.go:281] Invalid header on mined block: GasLimit check failed for block 5000 (5000 > 0)

**Comment by tgerring** [comment] 2015-07-27 09:11
Duplicate of #1530

**Closed by tgerring** 2015-07-27 09:11 UTC
