### ISSUE TITLE
export transaction evm trace via test rpc

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#20223] opened 2019-10-30 12:27 UTC
geth retesteth

during the test creation/debug it is required to have evm trace to see what is happening with memory/storage and which instructions are called. we need a client to export that log via test RPC 
Martin mentioned that there is a software console GUI to view that log, so following that format would be great. 

since the log might be too huge, the method should ask for a range of evm steps. 
Something like this: 

`test_traceTransaction( blockNumber, transactionHash, evmPosStart, evmPosLength)`

this is essential to new state test development as the debug is a key feature for test development

the evm debug flag might be transfered in set_chainParams method

**Comment by holiman** [comment] 2019-11-17 14:17
I still think a better option would be to use the proper geth, and have it dump out the trace to files: `debug.standardTraceBlockToFile`. If you build the testing tools using docker images, you could use that instead of retesteth. 

Alternatively, if executed via commandline, geth today already supports dumping out the trace: `./evm --json --statetest x.json`

The problem is that retesteth will require more and more synthetic addons that "mimic" what the real node does, and mimics the real node API behaviour, but it won't actually _be_ the real node. 

Anyway, if we were to add this, how would the results be used in practice? I mean, it's not really feasible to include all traces for all testcases, right?

**Comment by winsvega** [comment] 2019-11-26 12:08
The evm trace here is essential when writing and generating a new test to trace the transaction execution. 

```
./retesteth -t GeneralStateTests/stExample -- --singletest add11 --filltests --trace 15 20 -d 1 -g 0
```

so the command trace transaction execution of a specified test from evm pointer 15  for the next 20 steps. to see what code is actually being executed

**Comment by holiman** [comment] 2019-11-26 14:13
Today, both `evm`, `testeth` and `nethtest` already support outputting traces for statetests, so why not use the existing support?
You could build a docker image and pull e.g. `evm` directly from the geth `alltools` docker image, and it would work out of the box. 

> Am I getting this right that what client devs want is actually a node rather then a test tool. A node that would generate the blocks and send it over the network to test the clients connected to this test node?

No.. we need something which can generate tests, but I don't think the architecture of `retesteth` -- as it's implemented in go-ethereum, is the correct approach.

**Comment by holiman** [comment] 2019-11-26 14:15
@karalabe @fjl any thoughts about this?

**Comment by holiman** [comment] 2019-11-26 14:21
The thing is, yes, we already have this method on the debug api. However, it's really a pretty large feature, and we'd have to copy-paste the entire implementation over to retesteth -- because retesteth is implemented totally standalone -- it basically shares nothing of the common codepaths. 

So it adds quite a large overhead and maintenance.

**Comment by winsvega** [comment] 2019-12-02 13:57
https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracetransaction  looks interesting. 
However I discovered that geth retesteth implementation is just copy the existing method's code. 
If there is a way to call original debug methods from `geth retesteth` that is what is needed. 

rewriting each individual method required is not nice.

**Comment by holiman** [comment] 2020-05-24 17:35
Closing this, since we're going with `statet8n` tool instead

**Closed by holiman** 2020-05-24 17:35 UTC
Labels: retesteth
