### ISSUE TITLE
Geth restarting : panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by HamidullahMuslih** [ethereum/go-ethereum#26338] opened 2022-12-09 15:27 UTC
#### System information

Geth version: `1.10.26-stable`
CL client & version: prysm@v3.1.2.
OS & Version: Linux/Ubuntu 20.04

#### Expected behaviour
should sync the blocks without any issue

#### Actual behaviour
Throwing below logs and restarting 

#### Backtrace

````

```
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xa9bbe8]
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]: goroutine 56117 [running]:
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]: github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findBeaconAncestor(0xc000170780)
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]:         github.com/ethereum/go-ethereum/eth/downloader/beaconsync.go:220 +0xe8
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]: github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc000170780, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]:         github.com/ethereum/go-ethereum/eth/downloader/downloader.go:527 +0x911
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]: github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc0633d04b0?, {0x0, 0x0}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]:         github.com/ethereum/go-ethereum/eth/downloader/downloader.go:439 +0x505
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]: github.com/ethereum/go-ethereum/eth/downloader.(*beaconBackfiller).resume.func1()
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]:         github.com/ethereum/go-ethereum/eth/downloader/beaconsync.go:108 +0x96
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]: created by github.com/ethereum/go-ethereum/eth/downloader.(*beaconBackfiller).resume
Dec 09 15:13:41 ip-10-0-29-185 geth[477242]:         github.com/ethereum/go-ethereum/eth/downloader/beaconsync.go:98 +0x132
Dec 09 15:13:41 ip-10-0-29-185 systemd[1]: geth.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 09 15:13:41 ip-10-0-29-185 systemd[1]: geth.service: Failed with result 'exit-code'.
Dec 09 15:13:46 ip-10-0-29-185 systemd[1]: geth.service: Scheduled restart job, restart counter is at 161.
```
````

When submitting logs: please submit them as text and not screenshots.

**Comment by MariusVanDerWijden** [comment] 2022-12-15 09:18
duplicate of https://github.com/ethereum/go-ethereum/issues/26300

**Comment by holiman** [comment] 2023-01-09 10:59
Root issue fixed by https://github.com/ethereum/go-ethereum/pull/26451

**Closed by holiman** 2023-01-09 10:59 UTC
Labels: type:bug
