### ISSUE TITLE
Implement JSON-RPC error codes

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20117] opened 2019-09-24 08:35 UTC
As per [EIPs/eip-1474.md at master · ethereum/EIPs](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md). For details see [this PR discussion](https://github.com/ethereum/EIPs/pull/1474)

**Comment by hjlee9182** [comment] 2019-09-28 10:38
Are you want to add -32005 error in docs?

**Comment by jacklightChen** [comment] 2019-12-11 13:52
try to add -32006 ^_^

**Comment by johnson73A** [comment] 2020-01-04 22:29
Gjjgdjnk @jacklightChen

**Comment by MariusVanDerWijden** [comment] 2021-03-10 12:10
We're currently trying to create a new standard for the JSON-RPC api which would also include better error codes, the progress of it can be found here: https://github.com/ethereum-oasis/eth1.x-JSON-RPC-API-standard/issues
Once we have a good api, we can start to implement this, until then this issue is on hold

**Comment by duongxuantuan154** [comment] 2021-07-01 09:36
Duplicate of #

**Comment by duongxuantuan154** [comment] 2021-07-01 09:36
> Theo [EIPs / eip-1474.md tại master · ethereum / EIPs](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md) . Để biết chi tiết, hãy xem [thảo luận PR này](https://github.com/ethereum/EIPs/pull/1474)

**Comment by lhendre** [comment] 2022-05-02 06:40
@MariusVanDerWijden Checked the link and nothing has been updated in awhile, is this still needed?

**Comment by MariusVanDerWijden** [comment] 2022-05-02 08:05
This issue? not really, but more json-rpc error codes should be standardized (we've added more in the engine api)

**Closed by MariusVanDerWijden** 2022-05-02 08:05 UTC
Labels: type:feature, help wanted, good first issue
