### ISSUE TITLE
getTransactionCount on pending-block: nonce incorrectly returned as 0

### ISSUE THREAD

**Issue by leevlad** [ethereum/go-ethereum#21459] opened 2020-08-18 18:43 UTC
## System information

Geth version:  `1.9.15-stable`
Operating System: `Linux (ubuntu 18.04)`

#### Expected behaviour

Calling `eth_getTransactionCount(["<Address>", "pending"])` returns `0x10`.

#### Actual behaviour

Calling `eth_getTransactionCount(["<Address>", "pending"])` returns `0x0`.

I restarted `geth` and it looks like it somehow got into a bad state. Saw the following log line after it started:
```
Head state missing, repairing chain
```

After that it rewound the chain to a known state, synced back up, and the issue disappeared.

#### Additional Context

- When I call the same endpoint with "latest" parameter, it returns a non-zero (and correct) nonce (in this case it was `0x10`).
- Additionally, I'm running a few more instances of geth on other machines, and they were all returning correct non-zero values for the pending nonce (in this case it was `0x10`).
- Checking the account on Etherscan I verified that the nonce of `0x10` was also correct.
- Calling `geth --exec 'eth.blockNumber' attach` returns the correct latest block height
- Calling `geth --exec "eth.syncing" attach` returns `false`
- No errors in the syslog
- The machine had ample memory and disk space, system load nominal (~0.8), CPU utilization nominal (~10%), IO wait nominal (<1%)

#### Question

Is there a metric that could've been monitored to detect an issue such as this? 

Perhaps it's worth checking if the pending nonce is lower than the latest nonce, which might indicate a problem?

**Comment by karalabe** [comment] 2020-08-19 10:17
It's hard to debug these issues without some logs as to what Geth was doing while you were calling it's RPC. Could happen that it was already reimporting some old blocks? Was it recently restarted from a crash? "Head state missing" usually means that either Geth crashes, or it was forcefully stopped and you didn't allow it to flush it's buffers to disk gracefully.

**Comment by ang-st** [comment] 2020-08-31 09:02
Hi 
I get the same here... It happened overnight


```
node@prod-gw2-gateway-797646cfd8-gcn72:/usr/src/app$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0x67d3839f3e45bd6b68eb2787a5f02b784a0e59bb","latest"],"id":83}' http://prod-ethereum:8545 -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":83,"result":"0xb"}
node@prod-gw2-gateway-797646cfd8-gcn72:/usr/src/app$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0x67d3839f3e45bd6b68eb2787a5f02b784a0e59bb","pending"],"id":83}' http://prod-ethereum:8545 -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":83,"result":"0x0"}
```

attached log here : [geth.log](https://github.com/ethereum/go-ethereum/files/5149383/geth.log)

**Comment by ang-st** [comment] 2020-08-31 09:41
a node restart fixed the issue

**Comment by leevlad** [comment] 2020-08-31 14:32
Thanks @karalabe, unfortunately I don't have more information to provide, but hopefully the log dump from another user above will help in debugging this.

I also believe that the "Head state missing" error after restart was a red herring. I use `systemd` to run geth, and doing a `systemctl restart geth` just didn't wait long enough for `geth` to shut down cleanly before sending a `SIGKILL`, which probably corrupted some database.

**Comment by ang-st** [comment] 2020-09-04 07:32
Actually,  i can see this behavior at least twice a day.
i'm currently running : `Geth/v1.9.14-stable-6d74d1e5/linux-amd64/go1.14.2` .

I'll increase log level as at info level there is no error message standing out

**Comment by ang-st** [comment] 2020-09-04 11:05
@karalabe any hint which part i should focus on ?  i intend to use `debug.vmodule` so i can be more specific that just increasing log verbosity...
Thanks in advance.

**Comment by ang-st** [comment] 2020-09-04 11:24
kind of related :  I sometime have some transactions that get stuck as `sendRawTransaction` timeout. 
from there the transaction is present in "mempool" of the node and is not broadcasted ... it can stay for hours here even upon node restarting.
The only option i found is to rebroadcast it from a third party node.

from there i have 
`eth_getTransactionCount(["<Address>", "pending"])` returning `eth_getTransactionCount(["<Address>") -1 `

```
> eth.getTransactionCount('0x...')
71
> eth.getTransactionCount('0x..','pending')
70
```

**Comment by amyodov** [comment] 2020-09-07 22:52
See the same behaviour on my 1.9.13 and 1.9.15 geths:

~~~
> eth.getTransactionCount('0xd701edf8f9c5d834bcb9add73ddeff2d6b9c3d24', 'pending')
0
> eth.getTransactionCount('0xd701edf8f9c5d834bcb9add73ddeff2d6b9c3d24')
17559
~~~

There is no transactions pending from this address,

~~~
> txpool.content.pending['0xd701eDF8f9C5d834Bcb9Add73ddefF2D6B9C3D24']
undefined
~~~
, and I suspect this can be related.

As far as I understand, previously (around 1.9.11 or earlier) the “get transaction count(..., pending)” has always returned the nonce which is at least higher than the  “latest” nonce. Moreover, some third-party libraries expect that and often use the `eth.getTransactionCount(address, 'pending')` as a de facto way to get the nonce for the next transaction.

**Comment by MariusVanDerWijden** [comment] 2020-11-26 08:43
This issue is getting pretty stale now @amyodov or @leevlad do you see the same behaviour with one of the current releases too?

**Comment by leevlad** [comment] 2020-11-26 14:33
Haven't seen this issue in months at this point. I am confident it has been fixed.

**Comment by amyodov** [comment] 2020-11-26 15:02
Haven't seen it since then, either; but I am not sure that was an “issue easily reproducible” – that may have been a random moment/corruption to see that, and it just never occurred for me.

**Comment by karalabe** [comment] 2020-11-26 18:26
Thx all, I'll close this, please reopen if it reappears.

**Closed by karalabe** 2020-11-26 18:26 UTC

**Comment by leevlad** [comment] 2021-01-31 21:14
Hey, just wanted to drop a line here as follow-up. I was running `v1.9.20` on Linux and ran into a similar issue where pending nonces for one heavily used account (10k+ outgoing transactions) were being sporadically returned very stale. Sometimes the nonce value was 20-30 lower than it should've been, and other times they were being returned correctly.

The issue seems to have gone away after a few hours. I have upgraded to latest version (`v1.9.25`) since then, and the issue  has not recurred yet.

When it was happening I wasn't able to reproduce the issue deterministically, but I do want to provide some additional context in case it might hint at the possible root cause:
- I was sending about 100 transactions per hour out of that wallet when this started happening
- It seemed to have started happening only after I had a transaction with a very low gasPrice (7.5gwei while network average was 120gwei) in the mempool for about 20 minutes. Pending nonces after this one transaction's nonce started intermittently being returned incorrectly.

I don't believe this merits reopening the issue just yet, but I will keep an eye on how it performs on `v1.9.25` and report back with more details if it recurs.
