### ISSUE TITLE
"write: broken pipe" (1.4.14)

### ISSUE THREAD

**Issue by ntpeters** [ethereum/go-ethereum#3060] opened 2016-09-28 15:12 UTC
#### System information

Geth version: `1.4.14`
OS & Version: macOS Sierra
Commit hash : geth-1.4.14-prerelease-f88bca7-darwin-10.6-amd64
#### Actual behaviour

Geth was running, then started outputting this error. My terminal scrollback is set to 1000 lines, and it filled that up in a couple seconds with this error. Then it started syncing correctly again.
#### Steps to reproduce the behaviour

All I was doing at the time was viewing my wallet in Mist (0.8.3), but I don't think that's related as I can't reproduce.
I didn't lose internet connection, and wasn't doing any other "heavy" tasks at the time. (only things open were Mist and Safari with a couple tabs)
#### Backtrace

```
// many more instances of this error above
I0928 11:05:01.960619 rpc/server.go:376] write unix /Users/nate/Library/Ethereum/geth.ipc->: write: broken pipe
I0928 11:05:01.960625 rpc/server.go:349] write unix /Users/nate/Library/Ethereum/geth.ipc->: write: broken pipe
I0928 11:05:01.960633 rpc/server.go:376] write unix /Users/nate/Library/Ethereum/geth.ipc->: write: broken pipe
I0928 11:05:01.960643 rpc/server.go:349] write unix /Users/nate/Library/Ethereum/geth.ipc->: write: broken pipe
I0928 11:05:11.628157 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 9 txs in 25.715057ms. #2343012 [a311556a / a311556a]
```

**Comment by karalabe** [comment] 2016-09-28 18:15
This seems like the connection between Geth and Mist broke for some reason, though I'm not sure why Geth would cause this. The builds were cross compiles so there might be some anomaly there, but it could be worth checking with the Mist team too to see how they handle the IPC socket?

@luclu Any ideas on this one? Have you seen this before?

**Comment by ntpeters** [comment] 2016-09-28 18:20
I'll build from the `v1.4.14` tag and run with that for awhile to hopefully rule out any issues with the cross compilation. I'll try playing around in Mist again with that, but as I said I'm not able to reliably reproduce this currently.

**Comment by ntpeters** [comment] 2016-09-28 18:53
Hmm, okay, so I finished that build and just started geth again, and I saw two instances of this error without Mist running at all. I'm now running a locally built geth from tag `v1.4.14` (last commit hash `f88bca7ba96a16e10b9feee453dbdb4f81962f34`). Go version: `go1.7.1 darwin/amd64`.

Here's the full output of this run so far:

```
$ ./geth --cache 2048 --targetgaslimit 1500000 --gasprice 20000000000 console
I0928 14:37:55.986401 ethdb/database.go:83] Alloted 2048MB cache and 1024 file handles to /Users/nate/Library/Ethereum/chaindata
I0928 14:37:56.749624 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0928 14:37:56.749643 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0928 14:37:56.749649 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0928 14:37:56.749653 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0928 14:37:56.749658 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0928 14:37:56.750554 ethdb/database.go:171] closed db:/Users/nate/Library/Ethereum/chaindata
I0928 14:37:56.754267 ethdb/database.go:83] Alloted 2048MB cache and 1024 file handles to /Users/nate/Library/Ethereum/chaindata
I0928 14:37:57.355574 ethdb/database.go:83] Alloted 16MB cache and 16 file handles to /Users/nate/Library/Ethereum/dapp
I0928 14:37:57.359161 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0928 14:37:57.359337 eth/backend.go:201] Blockchain DB Version: 3
I0928 14:37:57.362224 core/blockchain.go:214] Last header: #2343894 [620d5139…] TD=66794344462262166023
I0928 14:37:57.362244 core/blockchain.go:215] Last block: #2343894 [620d5139…] TD=66794344462262166023
I0928 14:37:57.362250 core/blockchain.go:216] Fast block: #2343894 [620d5139…] TD=66794344462262166023
I0928 14:37:57.363595 p2p/server.go:313] Starting Server
I0928 14:37:58.111473 p2p/discover/udp.go:217] Listening, enode://0f52004fb86442ffaebd6300a654d34db466cf99bb91b83d7df4b95f00e2f8f4de1cd3a1499af4a7811f864da647597adb5ca49baf66b554727131200edb2906@[::]:30303
I0928 14:37:58.112545 p2p/server.go:556] Listening on [::]:30303
I0928 14:37:58.113395 node/node.go:296] IPC endpoint opened: /Users/nate/Library/Ethereum/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/v1.4.14-prerelease-f88bca7b/darwin/go1.7.1
coinbase: 0x6269b5809067fa9b234eab7dacd42cafa7a3b952
at block: 2343894 (Wed, 28 Sep 2016 14:37:36 EDT)
 datadir: /Users/nate/Library/Ethereum
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> I0928 14:38:13.912829 eth/handler.go:290] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I0928 14:40:20.335467 eth/handler.go:290] Peer 575759525eece037 [eth/63]: timed out DAO fork-check, dropping
I0928 14:43:48.112850 eth/downloader/downloader.go:319] Block synchronisation started
I0928 14:44:53.029668 core/blockchain.go:975] imported 30 block(s) (0 queued 0 ignored) including 100 txs in 1.590362348s. #2343924 [9659e8e7 / c6f67491]
I0928 14:44:58.065957 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.158693ms. #2343925 [e55a8147 / e55a8147]
I0928 14:44:58.096325 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 26.719575ms. #2343926 [188049f4 / 188049f4]
I0928 14:46:12.669025 eth/downloader/downloader.go:611] Peer 8b2b1cfa7679a39d [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 11.961747259s]: head header set (item 0) broke chain ordering: requested 2343734, got 2343934
I0928 14:47:11.028580 eth/handler.go:290] Peer 9fa79b095b70776b [eth/63]: timed out DAO fork-check, dropping
I0928 14:47:44.641758 rpc/server.go:349] write unix /Users/nate/Library/Ethereum/geth.ipc->: write: broken pipe
I0928 14:47:44.641802 rpc/server.go:349] write unix /Users/nate/Library/Ethereum/geth.ipc->: write: broken pipe
I0928 14:47:58.670892 core/blockchain.go:975] imported 4 block(s) (0 queued 0 ignored) including 12 txs in 68.683315ms. #2343930 [8a295766 / fec4bfea]
I0928 14:47:59.115051 core/blockchain.go:975] imported 12 block(s) (0 queued 0 ignored) including 55 txs in 413.296118ms. #2343942 [8c393c00 / 35b4995e]
I0928 14:47:59.119072 core/blockchain.go:975] imported 0 block(s) (0 queued 1 ignored) including 0 txs in 3.967586ms. #2343931 [8c393c00 / 8c393c00]
I0928 14:48:27.645251 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 6.026659ms. #2343943 [e557d1fd / e557d1fd]
I0928 14:48:27.844257 core/blockchain.go:975] imported 3 block(s) (0 queued 0 ignored) including 11 txs in 136.841794ms. #2343946 [fc0524c8 / 75bc1974]
I0928 14:48:31.339549 core/blockchain.go:975] imported 3 block(s) (0 queued 0 ignored) including 7 txs in 54.112487ms. #2343949 [3da7a762 / 16f6d05c]
I0928 14:48:31.462066 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.612025ms. #2343950 [f0e02cdb / f0e02cdb]
I0928 14:48:46.965010 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 7.083093ms. #2343951 [7b9b3fcb / 7b9b3fcb]
I0928 14:48:51.785691 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 9.698077ms. #2343952 [f1150f23 / f1150f23]
I0928 14:49:00.918017 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 16.345168ms. #2343953 [182bdaee / 182bdaee]
I0928 14:49:15.251152 rpc/server.go:349] write unix /Users/nate/Library/Ethereum/geth.ipc->: write: broken pipe
I0928 14:49:15.252021 rpc/server.go:349] write unix /Users/nate/Library/Ethereum/geth.ipc->: write: broken pipe
I0928 14:49:15.253628 rpc/server.go:349] write unix /Users/nate/Library/Ethereum/geth.ipc->: write: broken pipe
I0928 14:49:15.257009 rpc/server.go:349] write unix /Users/nate/Library/Ethereum/geth.ipc->: write: broken pipe
I0928 14:49:50.530176 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.360476ms. #2343954 [1133f7df / 1133f7df]
I0928 14:49:53.898759 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 8 txs in 11.82603ms. #2343955 [4d4797e9 / 4d4797e9]
I0928 14:50:03.244046 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.173215ms. #2343956 [cc79edc3 / cc79edc3]
I0928 14:50:06.574747 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.166444ms. #2343957 [f8b51daf / f8b51daf]
```

**Comment by karalabe** [comment] 2016-09-28 19:00
That's very weird indeed. Are you sure there isn't some program trying to
access you IPC channel? Perhaps @bas-vk or @fjl any ideas on what might
cause this? I don't have an osx to try to repro.

**Comment by ntpeters** [comment] 2016-09-28 19:20
Not that I know of. I'll reboot and run only geth for awhile to see if there may have been something interfering.

**Comment by ntpeters** [comment] 2016-09-28 22:01
I haven't been able to reproduce for the past few hours after a reboot. I'm not sure if this is actually meaningful since I never found a reliable way to reproduce, but now I'm thinking maybe this should be closed unless someone else also reports the same issue?

**Comment by bas-vk** [comment] 2016-09-29 12:07
This is caused when the node tries to write a response/notification to the client and the connection was closed for some reason (most likely closed by the client). What is strange is that you mentioned this error is also happening without mist or any other application running that connects to the endpoint (that includes the geth console through attach).

It would be nice if you start geth with `vmodule=rpc/*=6`. This might give some additional info what is going on.

When this happens could you execute the following command and see if there are more applications using the ipc endpoint `sudo lsof | grep geth.ipc`.

**Comment by ntpeters** [comment] 2016-09-30 02:26
Okay, this just happened again a bit ago with Mist open. 

Here is the output of `sudo lsof | grep geth.ipc`:
```
geth      61009            nate   46u     unix 0x5af5870778e22afb        0t0          /Users/nate/Library/Ethereum/geth.ipc
geth      61009            nate   49u     unix 0x5af58707934ca903        0t0          /Users/nate/Library/Ethereum/geth.ipc
geth      61009            nate  118u     unix 0x5af5870778e2296b        0t0          /Users/nate/Library/Ethereum/geth.ipc
geth      61009            nate  126u     unix 0x5af58707934ccc2b        0t0          /Users/nate/Library/Ethereum/geth.ipc
geth      61009            nate  418u     unix 0x5af58707934cc45b        0t0          /Users/nate/Library/Ethereum/geth.ipc
geth      61009            nate  613u     unix 0x5af58707934cc9d3        0t0          /Users/nate/Library/Ethereum/geth.ipc
geth      61009            nate  684u     unix 0x5af587079501ffab        0t0          /Users/nate/Library/Ethereum/geth.ipc
```

**Comment by bas-vk** [comment] 2016-09-30 08:54
Thanks for reporting back.

Could you start Mist with the loglevel set to debug and capture the output? If you installed Mist into the Applications directory the command should look like:
`/Applications/Mist.app/Contents/MacOS/Mist --loglevel debug --logfile /tmp/mist.log`

Both the Geth and Mist logfiles have a timestamp in them. When you see the broken pipe error in the Geth logs could you post the part of the Mist file around that time?

**Comment by RFVenter** [comment] 2016-12-21 12:04
same here:

I1221 20:04:04.294273 rpc/server.go:344] write unix /home/rfv/.ethereum/geth.ipc->@: write: broken pipe
I1221 20:04:04.791435 rpc/server.go:344] write unix /home/rfv/.ethereum/geth.ipc->@: write: broken pipe
I1221 20:04:05.287157 rpc/server.go:344] write unix /home/rfv/.ethereum/geth.ipc->@: write: broken pipe
I1221 20:04:05.783588 rpc/server.go:344] write unix /home/rfv/.ethereum/geth.ipc->@: write: broken pipe
I1221 20:04:06.281220 rpc/server.go:344] write unix /home/rfv/.ethereum/geth.ipc->@: write: broken pipe
I1221 20:04:06.777337 rpc/server.go:344] write unix /home/rfv/.ethereum/geth.ipc->@: write: broken pipe
I1221 20:04:07.273612 rpc/server.go:344] write unix /home/rfv/.ethereum/geth.ipc->@: write: broken pipe
I1221 20:04:07.769954 rpc/server.go:344] write unix /home/rfv/.ethereum/geth.ipc->@: write: broken pipe
I1221 20:04:08.266843 rpc/server.go:344] write unix /home/rfv/.ethereum/geth.ipc->@: write: broken pipe
I1221 20:04:08.764141 rpc/server.go:344] write unix /home/rfv/.ethereum/geth.ipc->@: write: broken pipe

**Comment by bas-vk** [comment] 2017-01-03 08:42
This is probably also caused by a client that closes the connection before geth is able to reply.
What application connected on the ipc endpoint? If it was Mist, do you use the latest version because there where some bugs in the connectivity layer that have been fixed.

**Comment by jpritikin** [comment] 2017-05-03 16:16
I am able to reproduce similar behavior on Debian/Linux with geth 1.6.0, Mist 0.8.9, using a Ledger Nano S wallet with https://oasisdex.com/

Oasisdex works fine with a regular geth/Mist wallet, but I get
`
ERROR[05-03|12:06:05] write unix /home/joshua/.ethereum/geth.ipc->@: write: broken pipe
`
when trying to sign transactions with a Ledger Nano S wallet. Anything I can try to provide more information?

**Comment by karalabe** [comment] 2017-05-03 17:05
Perhaps that Dapp has a signing timeout, so while you are confirming, the
Dapp thinks something went wrong and tears down the connection?

**Comment by jpritikin** [comment] 2017-05-03 17:29
> Perhaps that Dapp has a signing timeout, so while you are confirming, the
> Dapp thinks something went wrong and tears down the connection?

How might I test whether your diagnosis is correct? When I try to execute a transaction, it prompts me for my regular wallet password. As soon as I enter it, there is an error message. I am never prompted to approve the transaction on the Ledger Nano S. When I do simple transfer tokens in Mist, I am prompted for my geth wallet password then prompted for approval on the Ledger Nano S.

**Comment by jpritikin** [comment] 2017-05-04 13:16
After I installed geth 1.6.1, I no longer get a broken pipe. Instead, I am asked again and again to "Enter a password to confirm the transaction". When I enter it, I immediately get "reply lacks signature" and am asked again for the password. I am never asked to confirm the transaction on the Ledger Nano S. The "Execute contract" does not time-out. The same dialog box stays up and keeps waiting to get confirmed.

**Comment by karalabe** [comment] 2017-05-04 14:20
Ah wait. Did you enable data on the Ledger? By default the Lerger nano is shipped with data disabled, so all such transactions are insta-denied by it.

**Comment by jpritikin** [comment] 2017-05-04 14:37
On Thu, May 04, 2017 at 07:20:33AM -0700, Péter Szilágyi wrote:
>    Ah wait. Did you enable data on the Ledger? By default the Lerger 
>    nano is shipped with data disabled, so all such transactions are 
>    insta-denied by it.

Ah, that was it. I swear I had data enabled, but maybe it got disabled 
when I went through the Ledger recovery process or something.

In any case, it would be really helpful if Mist or geth provided a hint 
about what might be wrong.

-- 
Joshua N. Pritikin, Ph.D.
Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
PO Box 980126
800 E Leigh St, Biotech One, Suite 1-133
Richmond, VA 23219
http://exuberant-island.surge.sh

**Comment by karalabe** [comment] 2017-05-04 14:43
The problem is that the Ledger doesn't tell us what's wrong so I can't output a meaningful error message. At least not in the version I implemented the protocol for.

**Comment by jpritikin** [comment] 2017-05-04 14:52
On Thu, May 04, 2017 at 07:43:40AM -0700, Péter Szilágyi wrote:
>    The problem is that the Ledger doesn't tell us what's wrong so I can't
>    output a meaningful error message. At least not in the version I
>    implemented the protocol for.

Could you distinguish using the amount of time before receiving a 
disconfirm? If it's less than 100ms then you can assume it wasn't 
because the user pushed the cancel button.

-- 
Joshua N. Pritikin, Ph.D.
Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
PO Box 980126
800 E Leigh St, Biotech One, Suite 1-133
Richmond, VA 23219
http://exuberant-island.surge.sh

**Comment by karalabe** [comment] 2017-05-04 14:54
I'll look into it.

**Comment by adyshimony** [comment] 2018-09-11 23:16
Happening for me
ERROR[09-12|02:12:44.176] write unix /home/adys/.ethereum/geth.ipc->@: write: broken pipe

Restarting geth is not helping

**Comment by fjl** [comment] 2019-01-22 09:36
This error is just a case of geth logging the write error when it wants to send a response, but the connection is already closed. We can't fix this without losing logging for all write errors, so nothing will happen here.

**Closed by fjl** 2019-01-22 09:36 UTC
Labels: status:triage
