### ISSUE TITLE
Why not use the block hash returned by backend of ethclient but recalculate it?

### ISSUE THREAD

**Issue by jongrun** [ethereum/go-ethereum#27456] opened 2023-06-12 07:41 UTC
https://github.com/ethereum/go-ethereum/blob/281e8cd5abaac86ed3f37f98250ff147b3c9fe62/ethclient/ethclient.go#L184
The block hash returned from backend is ignored here. When we call block.Hash(), the block hash is recalculated.

**Comment by lightclient** [comment] 2023-06-12 07:54
The cache isn't accessible outside the package, so we can't really set it from `ethclient`. It isn't too expensive to compute the hash, so it doesn't seem necessary to change the interface so it can be loaded.

**Comment by jongrun** [comment] 2023-06-12 08:19
> The cache isn't accessible outside the package, so we can't really set it from `ethclient`. It isn't too expensive to compute the hash, so it doesn't seem necessary to change the interface so it can be loaded.

This also happens in HeaderByHash/HeaderByNumber/eth_subscribe(newHead) because there is no Hash field in Header and the Header.Hash() recalculate it every time.
Besides the consideration of cost to compute the hash, there is another compatibility issue in my project. When I implement ethereum client JSON RPC in my project where the block structure is not totally the same as ethereum, I convert(copy) the fields in my block to the ones in ethereum block, including the block hash. But algorithm of the block hash is not the same as ethereum, so when user uses ethclient to access my chain, the block hash is always wrong.
Is it possible to use the block hash returned by backend?

**Comment by lightclient** [comment] 2023-06-12 08:36
The `ethclient` is designed to an Ethereum RPC client, so again I'm not sure we should be modifying the interface to support non-Ethereum-based interactions. If you've modified the block structure, you should also modify `ethclient` in your project or rely on a lower level interface like straight JSON-RPC.

**Comment by lightclient** [comment] 2023-06-12 09:08
>  ethclient should get origin block hash from backend because the ethclient may calculate the hash incorrectly

The failure model for the backend does not allow it to return incorrect information. The ethclient _trusts_ the backend to return correct information. This is why users should run nodes - so that they don't need external trust assumptions. For that reason, we do not need to check the integrity of the response. Therefore, the only reason to use the block hash from the backend is to avoid a small amount of additional computation, which I'm not sure is worth it here.

> The goal of an EVM-compatible project is to make developers more convenient to clone their project in etherem to a new environment

Agree with this, but as you've said, you have a different block structure than Ethereum. So I would say this is no longer "EVM compatible".

**Comment by jongrun** [comment] 2023-06-12 09:31
> The ethclient _trusts_ the backend to return correct information. This is why users should run nodes - so that they don't need external trust assumptions.

As you say, the ethclient trusts the backend, so it's uneccesary to recalculate the hash, which may even get a wrong hash that inconsistent with the backend.

> Agree with this, but as you've said, you have a different block structure than Ethereum. So I would say this is no longer "EVM compatible".

We try our best to make all the RPCs are compatible, but the block structure can't because of some historical reasons. Even so, the data format returned by eth_getBlockxxx is also the same as ethereum, only some hashes in it can't be verified.

**Comment by holiman** [comment] 2023-06-14 06:43
The ethclient uses the same datatypes as the backend. And the backend is 'mainnet ethereum' so using ethclient on projects which have different datatypes, e.g. different blockhash definition, won't work well. 

You need to either modify ethclient along with your other types, or use a more generic / less ethereum-specialized client, which just takes the returnvalues at face value and doesn't try to parse them.  

This issue is by design, in the case of ethclient, and it's not going to change. Closing as wontfix.

**Closed by holiman** 2023-06-14 06:43 UTC
