### ISSUE TITLE
Estimate gas chooses wrong instruction set at genesis

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#29404] opened 2024-03-29 18:04 UTC
## Bug
```console
$ geth --dev dumpgenesis > genesis.json
$ geth --dev --datadir=data init genesis.json
$ geth --dev --datadir=data console
> eth.estimateGas({from: "0xd67dC7d443C902bd6ABfBc91C9E2E6906f55Ca46", data: "0x5959f3"})
Error: invalid opcode: PUSH0
        at web3.js:6382:9(39)
        at send (web3.js:5116:62(29))
        at <eval>:1:16(7)
```

## Culprit

We determine `random` value based on if `difficulty` is set:
https://github.com/ethereum/go-ethereum/blob/a3829178af6cec64d6def9131b9340a3328cc4fc/core/evm.go#L62-L64

But then here we use it as `isMerge` for creating the chain rules.
https://github.com/ethereum/go-ethereum/blob/a3829178af6cec64d6def9131b9340a3328cc4fc/core/vm/evm.go#L148

The chain rules then dictate the instruction set, so we choose London instructions instead of Shanghai.

## Resolution

I guess the main question is should we support this behavior. Is the genesis block technically considered post-merge? A simple fix would be to change the value that goes into `Rules(..)` to be `blockCtx.Random != nil || chainConfig.TerminalTotalDifficultyPassed`. But this doesn't feel too great either.

**Comment by lightclient** [comment] 2024-03-29 18:06
h/t @fselmo for reporting

**Comment by fselmo** [comment] 2024-03-29 20:16
For more context, I am trying to set up a geth `--dev` with a config that turns on `cancunTime`. Setting `shanghaiTime` in genesis config works for me but setting `cancunTime` will use the difficulty that is set in the gensis file. So even if I set `terminalTotalDifficulty=0` and `difficulty=1` (since there's a validation that requires genesis `difficulty` be >= `terminalTotalDifficulty`), when I turn on `cancunTime: 0` it will use the genesis difficulty and, as stated in the description, will not pick up the proper config rules.

I'm actually able to hack a way around this to coax the config into no longer raising the `PUSH0` related error, which I'm assuming means it at least clicks into Shanghai rules. I can do that by setting `terminalTotalDifficulty=-1` and `difficulty=0` in genesis conig. This seems to somehow work and it will pull `difficulty=0` into the block 1 header and no longer raises with `invalid opcode: PUSH0`.

Obviously this isn't ideal but it gets me past that and into another situation where the first block won't seal due to `invalid parameters`. If I'm assuming that `--dev` mode never enters Cancun here, and I've only wiggled my way into Shanghai, then all of the errors I now see see should make sense. Sealing a Shanghai block would not recognize Cancun's invalid parameters and when I try to send any transaction it hangs on transaction indexing forever.

So it seems that even when I get around the `PUSH0` issue, tricking the config to use `difficulty=0`, I am still not in the expected EVM state (or at least I think that's the issue related to `invalid parameters`.

**Comment by fselmo** [comment] 2024-04-04 23:09
@lightclient looks like the latest `master` of geth resolves the EVM rules correctly. I didn't pinpoint exactly what commit or PR resolved it but I believe this can be closed.

**Comment by fselmo** [comment] 2024-04-05 00:57
Correction, when I don't supply gas and the library has to call `eth_estimateGas`, it still errs out with `PUSH0` not supported. However, in current `master`, if I do provide `gas` for every transaction it does find the correct EVM rules.

**Comment by jwasinger** [comment] 2024-04-18 00:53
Resolved in https://github.com/ethereum/go-ethereum/pull/29469 .

**Closed by jwasinger** 2024-04-18 00:53 UTC
Labels: type:bug

**Comment by fselmo** [comment] 2024-04-18 15:41
I'm still seeing this running against geth `master` branch

```
WARN [04-18|09:34:02.022] Served eth_estimateGas                   reqid=3 duration="419.912µs" err="invalid opcode: PUSH0"
```

**Comment by fselmo** [comment] 2024-04-18 16:09
I opened #29579 that resolves things for me. Perhaps just a better message when difficulty > TTD and we are post-merge at genesis would make for better UX.

**Comment by jwasinger** [comment] 2024-04-18 17:00
> @jwasinger I'm still seeing this running against geth `master` branch
> 
> ```
> WARN [04-18|09:34:02.022] Served eth_estimateGas                   reqid=3 duration="419.912µs" err="invalid opcode: PUSH0"
> ```
> 
> I specify `terminalTotalDifficulty` in my genesis at `0` but since `difficulty` has to be greater than TTD, I have to put something other than `0` which might render that change (in #29469) obsolete. If a user specifies TTD = `0`, I believe `difficulty` should also be allowed to be set to `0`, no?
> 
> With the `-1` "hack" I mentioned above, `master` branch works perfectly. So I think it's a matter of being able to set both values to `0` and also perhaps validating that TTD cannot be negative.

That's weird that master is still broken for you.  Trying the example that Matt posted in the issue description of https://github.com/ethereum/go-ethereum/issues/29404#issue-2215783668 works for me.

**Comment by jwasinger** [comment] 2024-04-18 17:09
Yes, I tested with the default geth dev mode config.  Genesis TTD/difficulty are both 0, which I agree seems wrong as this would make the genesis block the last pre-merge block.

But post-merge features are activated at genesis, and the withdrawal shim functionality still works so... 🤷‍♂️ .

**Comment by jwasinger** [comment] 2024-04-18 17:22
> If I use my own genesis I can't set them both to 0 is what I think the problem is.

The default genesis config for dev mode (`geth --dev dumpgenesis`) sets these both to 0.  So a custom configuration based on this should work.  But it doesn't and emits an error for you?

**Comment by fselmo** [comment] 2024-04-18 17:27
Correct but if a custom genesis is used, it enters that validation block where `difficulty > TTD` is validated. Which is why I submitted that PR to allow both of them to be `0` in a custom genesis. That validation is not triggered when the default is used.

**Comment by jwasinger** [comment] 2024-04-18 17:38
> that validation block where difficulty > TTD is validated.

Can you link this in the code?  And if setting TTD/difficulty to 0 is still breaking with your config, can you post a reproducable example (as this would indicate another bug at this point)?

If I `geth --dev dumpgenesis` and `geth init` against that configuration, it works fine for me locally.

**Comment by fselmo** [comment] 2024-04-18 17:51
> Can you link this in the code?

It's that code block both you and I ended up making the same exact change. I'm almost to my computer and can try to post a quick example. But it actually looks like that whole block is triggered if the DataDir flag is set?

Starts at `flags.go` line 1864. I'm not sure the default configuration enters that validation block because if it did it wouldn't allow difficulty to be the same as TTD (both `0`).

**Comment by jwasinger** [comment] 2024-04-18 18:03
Ah whoops.  You are correct, we will fail to start up when a custom dev genesis block is used (https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L1880) .

I forgot to switch my branch from https://github.com/ethereum/go-ethereum/pull/29566 ..

**Comment by fselmo** [comment] 2024-04-18 18:06
Yep, that's the spot. At my computer now, should we continue the conversation in #29579?
