### ISSUE TITLE
geth Synchronisation failed

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1941] opened 2015-10-28 18:38 UTC
Version: 1.3.0-dev
Git Commit: 57ab147

Are these Synchronisation failed messages expected?
If yes, pls close issue.
If not, to reproduce try connect Geth to Morden testnet (and possibly close #1933)
Thanks
```
I1027 00:37:30.386295    1594 backend.go:332] Protocol Versions: [63 62 61], Network Id: 2
I1027 00:37:30.387164    1594 genesis.go:89] Genesis block already in chain. Writing canonical number
I1027 00:37:30.387237    1594 backend.go:344] Successfully wrote genesis block. New genesis hash = c31c07282c5f803da583b8b65f3aa0b5cce411f3ffa6ae11c5e0adb3e057ef4a
I1027 00:37:30.387922    1594 genesis.go:89] Genesis block already in chain. Writing canonical number
I1027 00:37:30.388011    1594 backend.go:380] Blockchain DB Version: 3
I1027 00:37:30.388356    1594 blockchain.go:189] Last header: #0 [c31c0728…] TD=131072
I1027 00:37:30.388392    1594 blockchain.go:190] Last block: #0 [c31c0728…] TD=131072
I1027 00:37:30.388406    1594 blockchain.go:191] Fast block: #0 [c31c0728…] TD=131072
I1027 00:37:30.404663    1594 cmd.go:124] Starting Geth/v1.3.0-dev-57ab1473/linux/go1.5.1
I1027 00:37:30.404881    1594 server.go:311] Starting Server
I1027 00:37:32.990293    1594 udp.go:204] Listening, enode://7eda046cc8180bc56d9d16483e5870628094fe2a8bdfe524de45b09f5f17cb897500a4e28ce0c78513eb7b506cc141a6a5845dbb249e4b0ef9ec0cc6acc5ead0@[::]:30303
I1027 00:37:32.990467    1594 backend.go:598] Server started
I1027 00:37:32.990725    1594 ipc_unix.go:109] IPC service started (/home/user/geth.ipc)
I1027 00:37:32.990794    1594 server.go:552] Listening on [::]:30303
I1027 00:38:52.991084    1594 downloader.go:289] Block synchronisation started
I1027 00:48:45.486789    1594 downloader.go:269] Synchronisation failed: block body download canceled (requested)
I1027 00:48:59.163417    1594 downloader.go:269] Synchronisation failed: state data download canceled (requested)
I1027 00:49:09.658922    1594 downloader.go:269] Synchronisation failed: state data download canceled (requested)
I1027 00:51:52.178428    1594 downloader.go:269] Synchronisation failed: no peers to keep download active
I1027 00:52:29.744087    1594 downloader.go:269] Synchronisation failed: block body download canceled (requested)
I1027 01:00:02.953065    1594 downloader.go:269] Synchronisation failed: no peers to keep download active
I1027 01:04:07.710831    1594 downloader.go:269] Synchronisation failed: block body download canceled (requested)
I1027 01:04:15.018511    1594 downloader.go:269] Synchronisation failed: state data download canceled (requested)
I1027 01:04:25.318228    1594 downloader.go:269] Synchronisation failed: state data download canceled (requested)
I1027 01:04:37.506778    1594 downloader.go:269] Synchronisation failed: block header download canceled (requested)
I1027 01:04:45.930389    1594 downloader.go:269] Synchronisation failed: state data download canceled (requested)
I1027 01:04:57.270587    1594 downloader.go:269] Synchronisation failed: block body download canceled (requested)
I1027 01:05:08.620327    1594 downloader.go:269] Synchronisation failed: state data download canceled (requested)
```

**Comment by karalabe** [comment] 2015-10-29 09:51
Just to provide some public feedback too, it seems that the Morden test net isn't much used and the seed server got decommissioned in some weird turn of events. I'll see if we can get a Go bootnode up and running to serve the test network.

**Comment by karalabe** [comment] 2015-10-29 09:55
Ah, I see this is a duplicate of the other testnet issue. The reason why you see these errors it that there's some lone peer that seems to speak Morden, but it has a very bad internet connection and cannot keep up with sending you data in the rate that we request it. Currently we dynamically adapt to a remote peer's bandwidth capabilities (or at least try) at almost all message exchanges, but pulling the headers is still assumed to have some minimal bandwidth (otherwise it would take a really long time to sync up)... so if a peer is really *that* slow, then better switch to someone else instead of wasting time (of course, if this peer is the *only one* then there's a problem :)) ). This error should not happen (or very rarely) in a healthy network.

**Comment by karalabe** [comment] 2015-10-30 10:25
https://github.com/ethereum/go-ethereum/pull/1952 should fix this. The issue most probably was that Morden is extremely unhealthy at the moment (essentially nobody is using it), so it's very hard to find peers, and even harder to find a good peer that does send useful data. With the two seed servers added, as long as they remain operational, they should keep Morden alive.

**Closed by karalabe** 2015-10-30 10:25 UTC
