### ISSUE TITLE
Pasting into the console is **extremely** slow

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#2938] opened 2016-08-24 07:33 UTC
Pasting in average smart contracts might be berable, but pasting in a 31KB monster that I have for a benchmark will take 1-2 minutes. This is unacceptable really.

I've been wondering where the issue might be and my guess is that liner, ottovm, or something processes the copy-paste character by character, redrawing the entire line. This effect can be seen if you copy paste into the middle of the string, where the end stays always on the screen, only the front moves. Also the first character remains on the screen. This cute effect seems to kill the performance.

**Comment by Hellsegga** [comment] 2016-08-25 14:54
Yes looks like it's liner. As you describe, liner will redraw the prompt input for every new character. I tried to disable that and pasting a long input was speeded up by 5x. However then you can't see the end of your input. I think we would like it to wrap to a new line if input becomes bigger than console window width? Probably liner can be tweaked to do that, need to look a bit more into it.
With a little luck it could solve your other issue https://github.com/ethereum/go-ethereum/issues/2939 as well :) if input is not cut it will be able to be copied in its entirety

**Comment by fjl** [comment] 2016-08-25 15:07
liner has a multi-line mode and we tried enabling it in the past. it caused problems, but I can't remember what the problem was.

**Comment by Hellsegga** [comment] 2016-08-25 16:02
Yes sorry, my answer was a bit sloppy. There is the multi-line mode but it looks like it's actually not faster than the single-line mode...

**Comment by Hellsegga** [comment] 2016-08-25 21:16
Sorry for my somewhat confusing previous posts.
To summarize:
- The problem is in liner and how it refreshes the input for every new character
- I posted an [issue](https://github.com/peterh/liner/issues/81) about it on liner project. With some luck it could be optimized. For example [linenoise](https://github.com/antirez/linenoise) the C library from which liner is inspired is faster (took me a few seconds for 30KB of input), so maybe similar optimizations could be done in liner
- Single-line or multi-line edit is kind of a separate issue (they're both slow :) ). But maybe it could be worth considering switching to multiline for user-friendliness reasons (if the problems Felix mentions could be fixed), based on a very quick and unscientific review it seems to be the behavior of most similar consoles (Node, Mongo...)

**Comment by fjl** [comment] 2016-08-25 21:21
I've done some more digging and the problem with multi line mode was also related to  pasting large inputs: https://github.com/ethereum/go-ethereum/commit/cec92f59405a99a1c71d4b2e055dff92b6bfa10a

**Comment by fjl** [comment] 2016-08-25 21:24
No need to apologise for everything you say btw. Your comments are not confusing.

**Comment by Hellsegga** [comment] 2016-08-29 15:48
I took a new look at liner and it looks like 2/3 of the time is spent in a function counting the glyphs from input. It's a kind of black art where it looks at unicode characters and tries to see if they're going to take up normal width, no width (like accents that combine with previous char...) or double width (some Chinese, Japanese, Korean characters...). However linenoise which otherwise has the same features as liner has a simpler way to count the width of the input, which might be possible to mimic. However I'd rather have the author or someone familiar with the field comment on this.

If we could do the optimization above we would be at 2x what I would consider the baseline speed to be (the speed of shell or linenoise). There might still be low-level optimizations to reach nearer that baseline but maybe linenoise which is a C implementation will remain a bit faster

Even if we would reach near linenoise/shell-speed it will not be superfast, 30kb would still take maybe 15-20 seconds. It seems those things are inherently slow and don't scale linearly because of the redrawing that takes place and the fact that standard output is unbuffered. But it would be "normally slow" as in most other consoles...

Other random alternatives:
- Add some advanced feature to liner that would detect when input is pasted and do some buffering
- Switch to linenoise. It has the same API as liner, is more mature and has go binding available (but I think your policy is to use native go projects)
- Forbid users to paste content larger than let's say 10kb. It's quite brutal but it would be disciplining, leading users to work their way around it (by using the "execute js file" command instead maybe), and wouldn't lock up their terminal :)

**Comment by fjl** [comment] 2016-08-29 16:10
Does linenoise work in the Windows cmd window? AFAIK it doesn't.

I think it is OK if it takes a few seconds to paste 30kb. Why does the line need to be redrawn after every character? If redrawing could be delayed by an imperceptible amount of time (~30ms), it might be possible to redraw once after the whole input has been processed. Do you think that's possible?

**Comment by Hellsegga** [comment] 2016-09-29 16:42
You're right, linenoise doesn't support Windows.
I made a "low hanging fruit" optimization for liner [here](https://github.com/Hellsegga/liner) and was able to cut the processing time in half. It only works for the single mode as I found multiline to be buggy and didn't look further into it. I just short-circuit the path for the most common case of a new character being entered and increment a count instead of recounting the whole input (the count on which the drawing is based, i.e. which part of the full text to show when it's too large...). Tell me if it's something you'd like to use.

Doing a delayed redrawing as you suggest could work, but maybe we can bring liner down to decent performance even with more basic changes.

**Comment by fjl** [comment] 2016-09-29 20:32
Maybe you can submit your changes to the upstream liner repo. They'll be thankful ;)

**Comment by peterh** [comment] 2016-11-03 18:17
liner should be an order of magnitude faster as of a couple of minutes ago. Please test and let me know.

**Comment by fjl** [comment] 2016-11-03 19:05
Thanks!

**Comment by fjl** [comment] 2016-11-15 16:58
Fix released in 1.5.0.

**Closed by fjl** 2016-11-15 16:58 UTC
Labels: bug, fixed on develop
