### ISSUE TITLE
high clef memory usage

### ISSUE THREAD

**Issue by attila-lendvai** [ethereum/go-ethereum#22361] opened 2021-02-21 18:14 UTC
#### System information

```
/nix/store/hd5qrid1y7pawrc1l5r963miwj9fg9hx-go-ethereum-1.9.25/bin/clef --version
Clef version 0.0.0
```

OS & Version: Linux (NixOS)

#### Expected behaviour

Memory usage in the ballpark of 200MB

#### Actual behaviour

Memory usage goes up to 1-1.5GB soon after operation begins, and i've seen processes with 9GB of memory usage.

#### Steps to reproduce the behaviour

http://docs.ethswarm.org/

This is with bee-clef, which is just some integration scripts to start up a clef executable for a bee process to serve it as an automated external signer.

Due to architectural reasons, bee scales better when running multiple instances on the same machine (as opposed to increasing the provided storage capacity), and each bee instance requires an exclusive clef instance, but this quickly eats up a lot of memory.

**Comment by attila-lendvai** [comment] 2021-02-22 14:22
a wild guess: bee initiates multiple parallel requests to clef, this slows down clef's response, this results in more open requests... turning into a positive feedback loop.

**Comment by attila-lendvai** [comment] 2021-02-22 16:27
@acud i have just seen 11GB memory usage for a clef process. i stopped the bee process that was using it, which stopped gracefully. clef continued to consume 11GB for around the next 5 minutes, and sometimes also a lot of CPU, and then its memory usage started to decrease.

this very much smells like bee is sending a torrent of signing operations to clef that it has trouble processing fast enough. and the more requests come, the slower clef becomes. then stopping the source of the requests normalizes memory usage after 5-10 more minutes.

note that when this happened with one of the bee+clef pairs on my server, i had another two running on the same machine, and they were not having the same issue.

**Comment by holiman** [comment] 2021-02-22 21:21
Have you tried using --lightkdf keystores? Opening them otherwise consumes a lot of ram

**Comment by holiman** [comment] 2021-02-23 09:13
@acud the auditlog should help find what happens -- you should be able to see exactly at what times what requests were made (and figure out the response times for those that were responded to)

**Comment by attila-lendvai** [comment] 2021-02-23 09:25
i will test running with `--lightkdf`, and enable `audit.log` into `/var/lib/bee-clef/audit.log`.

will report the results here.

**Comment by holiman** [comment] 2021-02-23 10:03
Note, though, `--lightkdf` only make a change for new keystores, it doesn't affect how much mem it requires to decrypt an existing keystore

**Comment by holiman** [comment] 2021-02-23 10:04
A potential change (if this is the cause) could be to make it possible to _keep_ the decrypted keystore in memory, after the initial decryption. It would probably have to be hidden behind a flag, so it would only be available for advanced users.

**Comment by attila-lendvai** [comment] 2021-02-23 10:31
confirmed: i have recreated the keystore using `--lightkdf` and now clef's memory usage remains trivial: it's some 70kB compared to sometimes running up to 10+ GB previously.

i don't see any downsides to using `--lightkdf`: these keys will be lowsec stuff in an automated environment anyway. i'll prepare a PR to bee-clef, unless advised otherwise.

thank you for the help @holiman !

**Comment by filoozom** [comment] 2021-02-24 12:50
Is there a way to convert existing keys to the lighter version? If so, how? If not, what about older nodes?

**Comment by holiman** [comment] 2021-02-24 13:00
There's no super simple built-in way, but there is an API-method to import a keystore file, on the 'trusted' API. If you feed the keystores in via that, it would save it as lightkdf. SO basically you'd have to copy the keystore folder to a different name, and then reimport them.

**Comment by filoozom** [comment] 2021-02-24 13:59
That sounds cumbersome and hard to automate. Are there tool out there to decrypt the keystore and then encrypt it again?

**Comment by filoozom** [comment] 2021-02-24 15:34
I upgraded all my keystores with this script, and can confirm it works. I have only converted files in `keystore/` and not `masterseed.json`.

**Comment by ligi** [comment] 2021-02-25 09:36
Just to make sure you are aware of the security implications: lightkdf reduces security

**Comment by holiman** [comment] 2021-05-27 09:50
Closing this, the mem consumption is a feature of the chosen encryption format

**Closed by holiman** 2021-05-27 09:50 UTC
Labels: type:bug
