### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ulope** [ethereum/go-ethereum#18421] opened 2019-01-09 13:02 UTC
#### System information

Geth version: `1.8.20-stable`
OS & Version: Linux (official `ethereum/client-go:v1.8.20` docker image)

#### Expected behaviour

Geth doesn't crash

#### Actual behaviour

Geth crashes with 
```
Synchronisation failed, retrying         err="block download canceled (requested)"
panic: runtime error: invalid memory address or nil pointer dereference
```

#### Steps to reproduce the behaviour

**History:**

- Node was running with 1.8.17 for a few months
- Server ran out of diskspace
- Increased diskspace
- Restarted 1.8.17 and let it repair the chain
- Upgraded to 1.8.20
- Shortly after `Block synchronisation started` the below crash happens.

**Docker compose file:**
```
version: "3"

services:
  geth:
    image: ethereum/client-go:v1.8.20
    restart: always
    network_mode: host
    volumes:
      - /data/geth:/root/.ethereum
    command: >
      --syncmode full
      --rpc
      --rpcapi eth,net,web3,txpool
      --rpcaddr 10.104.6.7
      --rpcvhosts <redacted>,localhost:5001,localhost:5002,localhost:5003
      --rpccorsdomain '*'
```

#### Backtrace

```
geth_1  | INFO [01-09|12:50:33.542] Maximum peer count                       ETH=25 LES=0 total=25
geth_1  | INFO [01-09|12:50:33.542] Starting peer-to-peer node               instance=Geth/v1.8.20-stable/linux-amd64/go1.11.2
geth_1  | INFO [01-09|12:50:33.542] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=512 handles=524288
geth_1  | INFO [01-09|12:50:35.469] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7080000 Engine: ethash}"
geth_1  | INFO [01-09|12:50:35.469] Disk storage enabled for ethash caches   dir=/root/.ethereum/geth/ethash count=3
geth_1  | INFO [01-09|12:50:35.469] Disk storage enabled for ethash DAGs     dir=/root/.ethash               count=2
geth_1  | INFO [01-09|12:50:35.469] Initialising Ethereum protocol           versions="[63 62]" network=1
geth_1  | WARN [01-09|12:50:35.512] Head state missing, repairing chain      number=6456433 hash=677756…99e32f
geth_1  | INFO [01-09|12:50:36.446] Rewound blockchain to past state         number=6454439 hash=6f9f5d…bb86fb
geth_1  | INFO [01-09|12:50:36.447] Loaded most recent local header          number=6456433 hash=677756…99e32f td=7031505586948312333147 age=3mo6d6h
geth_1  | INFO [01-09|12:50:36.447] Loaded most recent local full block      number=6454439 hash=6f9f5d…bb86fb td=7024892566288512072146 age=3mo6d14h
geth_1  | INFO [01-09|12:50:36.447] Loaded most recent local fast block      number=6456433 hash=677756…99e32f td=7031505586948312333147 age=3mo6d6h
geth_1  | INFO [01-09|12:50:36.447] Loaded local transaction journal         transactions=0 dropped=0
geth_1  | INFO [01-09|12:50:36.447] Regenerated local transaction journal    transactions=0 accounts=0
geth_1  | INFO [01-09|12:50:36.518] New local node record                    seq=7 id=05d0d6bf999dc3e1 ip=127.0.0.1 udp=30303 tcp=30303
geth_1  | INFO [01-09|12:50:36.518] Started P2P networking                   self=enode://f10fad656b58e20b168fb7242d4389dd23d72751dfd7f97e057032958acadadd63381e9bc96461e0c912c059d69b1ccdcf3ae8c81429e4b36959b023c6025f36@127.0.0.1:30303
geth_1  | INFO [01-09|12:50:36.519] IPC endpoint opened                      url=/root/.ethereum/geth.ipc
geth_1  | INFO [01-09|12:50:36.519] HTTP endpoint opened                     url=http://10.104.6.7:8545   cors=* vhosts=geth.mainnet.ethnodes.brainbot.com,geth-mainnet.ams3.do.brainbot.com,localhost:5001,localhost:5002,localhost:5003
geth_1  | INFO [01-09|12:50:41.896] New local node record                    seq=8 id=05d0d6bf999dc3e1 ip=178.62.197.232 udp=30303 tcp=30303
geth_1  | INFO [01-09|12:50:46.518] Block synchronisation started
geth_1  | WARN [01-09|12:51:11.958] Synchronisation failed, retrying         err="block download canceled (requested)"
geth_1  | panic: runtime error: invalid memory address or nil pointer dereference
geth_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51736e]
geth_1  |
geth_1  | goroutine 537 [running]:
geth_1  | math/big.(*Int).Cmp(0xc00a9f20a0, 0x0, 0x4546b978c9e9aec1)
geth_1  | 	/usr/local/go/src/math/big/int.go:319 +0x2e
geth_1  | github.com/ethereum/go-ethereum/core.(*BlockChain).insertSidechain(0xc008d48000, 0xc0106eb6e0, 0xc0000635c0, 0xc000063501, 0x1, 0x1, 0xc0117f807f, 0x1, 0x1, 0xc024fd99e0, ...)
geth_1  | 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1333 +0x10b2
geth_1  | github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc008d48000, 0xc0109c2808, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
geth_1  | 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1139 +0x2e15
geth_1  | github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc008d48000, 0xc0109c2808, 0x1, 0x1, 0x0, 0x0, 0x0)
geth_1  | 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1088 +0xb89
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc00009c9c0, 0xc0109c2800, 0x1, 0x1, 0x1, 0x5)
geth_1  | 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1490 +0x40e
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc00009c9c0, 0x0, 0xc00e989798)
geth_1  | 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1464 +0x79
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent-fm(0x8, 0x1024b40)
geth_1  | 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:479 +0x2a
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc00009c9c0, 0xc027ae62a0, 0xc026901b20)
geth_1  | 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0x59
geth_1  | created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
geth_1  | 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0xaf
```

**Comment by ulope** [comment] 2019-01-09 13:47
FYI: The same is happening on a Rinkeby node after upgrading it to 1.8.20.

**Comment by brentco** [comment] 2019-01-10 07:39
Having the same issue here!

**Comment by eb08a167** [comment] 2019-01-11 13:13
I see the same backtrace when trying to sync on Rinkeby.

**Comment by karalabe** [comment] 2019-01-11 13:30
Could you all try out with https://github.com/ethereum/go-ethereum/pull/18436 ? We've found 2 potential issues that the PR fixes, but would be nice if someone who can reproduce this failure tries it out.

**Comment by ulope** [comment] 2019-01-14 07:46
Sorry, can't test it. I had to get the node up again and therefore killed the db and started a re-sync.

**Comment by PashaKlybik** [comment] 2019-01-16 18:02
@karalabe I had the same problem with panic. I'm trying to build geth from PR # 18436 and the problem is the same.

**Comment by karalabe** [comment] 2019-01-17 10:11
@PashaKlybik Could you by any change pack up and upload your entire datadir somewhere? We can't seem to reproduce it, so if someone has a datadir that fails, it'd be really helpful to take a look at.

**Comment by PashaKlybik** [comment] 2019-01-17 14:55
@karalabe I added zip file with my rinkeby folder  on IPFS. You will download it by this hash: `QmQXtbSjv4jSHBXZy8e9T3nJrvnGtRaszCVvNqgSx4Ly9R`.

**Comment by opsarno** [comment] 2019-01-19 13:38
```bash
INFO [01-19|21:34:09.172] Block synchronisation started 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5192ce]

goroutine 631 [running]:
math/big.(*Int).Cmp(0xc0362c8c00, 0x0, 0x6d92278f6916d42b)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/math/big/int.go:319 +0x2e
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSidechain(0xc00f598000, 0xc039b436a0, 0xc0000735c0, 0xc000073501, 0x1, 0x1, 0xc039adc2b0, 0x1, 0x1, 0xc038cb1320, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1333 +0x10b2
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc00f598000, 0xc037a185e8, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1139 +0x2e1e
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc00f598000, 0xc037a185e8, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1088 +0xb89
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc0000b9a00, 0xc037a185e0, 0x1, 0x1, 0x1, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1490 +0x40e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc0000b9a00, 0x0, 0xc0388a7f98)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1464 +0x79
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent-fm(0x8, 0x102e070)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:479 +0x2a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc0000b9a00, 0xc03971b200, 0xc03987e1e0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0x59
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0xaf
INFO [01-19|21:34:20.702] Maximum peer count                       ETH=25 LES=0 total=25
```
Version: `1.8.21-stable-9dc5d1a9` has same issue.

**Comment by holiman** [comment] 2019-01-19 15:07
I think the problem for @PashaKlybik is that `localTd := bc.GetTd(current.Hash(), current.NumberU64())` returns `nil`, for whatever reason, 
@opsamo  I'm not sure you're having the same error, the stacktrace however indicate that you're not running the latest version.

**Comment by mavericklin** [comment] 2019-01-28 10:10
Same thing happen to 1.8.21, too.

**Comment by tenuki** [comment] 2019-02-01 20:09
We had this same issue and master today (which includes addressed fix) prevents the crash.

**Comment by tenuki** [comment] 2019-02-04 18:03
> We had this same issue and master today (which includes addressed fix) prevents the crash.

It seems to take a little longer but still crashes the same way:

**Comment by tenuki** [comment] 2019-02-06 17:35
> This is now fixed on master (not yet on 1.8-branch)

Thanks, worked perfectly!

**Comment by holiman** [comment] 2019-02-07 08:28
This is fixed on master, and will eventually be backported to 1.8

**Closed by holiman** 2019-02-07 08:28 UTC

**Comment by sicute** [comment] 2019-06-12 04:58
for that problem , try delete folder data geth and start over againt  sync  .
go-ethereum/build/bin/geth --rinkeby --datadir /mnt/geth --nousb --syncmode full console  

> go-ethereum/build/bin/geth version
INFO [06-12|04:57:52.092] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [06-12|04:57:52.093] Sanitizing cache to Go's GC limits       provided=4096 updated=2658
Geth
Version: 1.9.0-unstable
Git Commit: 2b546660187e8b693b6bbe5ec0fc74bfc008d1d3
Git Commit Date: 20190611
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.12.6
Operating System: linux
GOPATH=/home/ubuntu/go
GOROOT=/usr/local/go
