### ISSUE TITLE
Syncing error: signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78909a

### ISSUE THREAD

**Issue by LexLuther73** [ethereum/go-ethereum#22275] opened 2021-02-05 18:40 UTC
#### System information

Version: 1.9.25-stable
Git Commit: e7872729012a4871397307b12cc3f4772ffcbec6
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: linux

#### Backtrace: Not sure what thi means..... I'm a noob, but this is my 30th node setup  :)

Installed GETH same as all other VPS units. Errors as seen in pic kept occurring periodically, then drop all peers and start again, repeat.... 

![image](https://user-images.githubusercontent.com/72816762/107075081-420cb980-67af-11eb-8517-f2a082860669.png)

**Comment by slyfoxhd** [comment] 2021-02-08 16:22
I have the same issue. Did you get any help here? I opened also a thread. In my case it says panic: runtime error on-top. My node worked fine until it crashed Sunday night. I removed db file and tried a resync but it failed like in your case.

**Comment by gballet** [comment] 2021-02-11 10:15
closing as duplicate of #22281

**Closed by gballet** 2021-02-11 10:15 UTC
Labels: status:triage, type:bug
