### ISSUE TITLE
signed recently, must wait for others

### ISSUE THREAD

**Issue by poonam8077** [ethereum/go-ethereum#26947] opened 2023-03-22 08:43 UTC
hello MariusVanDerWijden
yes i have three to four nodes on our private network ..
but i was facing issue in time of transaction ...
WARN [03-21|14:35:45.799] Block sealing failed err="signed recently, must wait for others

how to resolve this issue please let me known
thanks and regard
Poonam singh

**Comment by fjl** [comment] 2023-04-27 08:59
Duplicate of #26944

**Closed** 2023-04-27 08:59 UTC
Labels: type:docs
