### ISSUE TITLE
Possible BUG - somebody took 50 ETH from my wallet immediately after successful transaction

### ISSUE THREAD

**Issue by leonpanjtar** [ethereum/go-ethereum#17011] opened 2018-06-17 19:39 UTC
Hi guys,

Hopefully someone can explain this odd behaviour I witnessed a few minutes ago, cause it looks like a serious issue to me. I transferred 50 ETH to a wallet address on the Ropsten network that we use for testing our contracts. What happened is that immediately after successful transaction of 50 ETH there were 2 other transactions following for exact amount of 50 ETH.

Our account is visible here: [0x85a9916425960aa35b2a527d77c71855dc0215b3](https://ropsten.etherscan.io/address/0x85a9916425960aa35b2a527d77c71855dc0215b3)

My transaction for 50 ETH is: [0x9f95ae4a78b9644603bb41af878c86ab5dd8d287fd9c13a47bb60f20e2f636cb](https://ropsten.etherscan.io/tx/0x9f95ae4a78b9644603bb41af878c86ab5dd8d287fd9c13a47bb60f20e2f636cb)

The first following transaction is: [0x84896b776e721b8535d95d642c31178dc89be778a2cd484519181b18c7d81fa7](https://ropsten.etherscan.io/tx/0x84896b776e721b8535d95d642c31178dc89be778a2cd484519181b18c7d81fa7)

The second following transaction is: [0x557c0c1c554e91e386eaee79a70f84dd573728618eecdffefdbea669bf979035](https://ropsten.etherscan.io/tx/0x557c0c1c554e91e386eaee79a70f84dd573728618eecdffefdbea669bf979035)

The transactions seem to be going to a miner of some sort - [0x7097f41f1c1847d52407c629d0e0ae0fdd24fd58](https://ropsten.etherscan.io/address/0x7097f41f1c1847d52407c629d0e0ae0fdd24fd58)

I was expecting my account to have a balance of 50 ETH, but was very surprised to find it was 0. Somebody stole 50 ETH from me. Can someone please explain what is happening here?

After the first transaction I tried to make another one for 5 ETH and this one went trough as it should [0x8f4c8177fef24518d17e290478d1d6cfdc68f89579270a608873e65538a06a89](https://ropsten.etherscan.io/tx/0x8f4c8177fef24518d17e290478d1d6cfdc68f89579270a608873e65538a06a89)

#### System information

Geth
Version: 1.8.11-stable
Git Commit: dea1ce052a10cd7d401a5c04f83f371a06fe293c
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10

#### Expected behaviour
Transaction should go trough and my balance should be 50 EHT.

#### Actual behaviour
Successful transaction was followed by two instant transaction that took away everything

#### Steps to reproduce the behaviour
Can't find a way to reproduce.

**Comment by RaghavSood** [comment] 2018-06-18 01:03
You either have your RPC open to the public, or are using a private key that was leaked somehow. 

I'm leaning towards RPC being public since leaked private keys tend to have the entire amount swept in a single transaction, not split up.

An open RPC usually results in someone brute-force signing several valid transaction of varying amounts, which seems more in line with your transactions.

**Comment by smalaichami** [comment] 2018-06-18 01:15
It should be due to unsafe open RPC connection, and it's good that you have not lost the real ETH. 
Consider signing the transaction and send to Blockchain in case if you want to send from your DAPP.  

By the way, the stolen Ropsten ETHs are not going to miners but to a hacker, he would run this program in mainnet also to steal real ETHs.

**Comment by ligi** [comment] 2018-06-18 09:43
closing as it is most likely caused by an open RPC  with unlocked account - please reopen if this is not the reason.

**Closed by ligi** 2018-06-18 09:43 UTC
