### ISSUE TITLE
getTransactionReceipt() throws "Error: unknown transaction" if txn not mined

### ISSUE THREAD

**Issue by mawenpeng** [ethereum/go-ethereum#16213] opened 2018-02-28 05:40 UTC
#### System information
Geth version: 1.8.1-stable
OS & Version: Linux CentOS Linux release 7.4.1708 (Core)
Go Version: go1.10
Testnet: Rinkeby

#### Expected behaviour
eth.getTransactionReceipt() returns null if the transaction is submitted but not mined.

#### Actual behaviour
Throws "Error: unknown transaction". This confuses apps, hard to estimate the actual status of transactions. Please refer https://github.com/web3j/web3j/issues/318

#### Steps to reproduce the behaviour
Send a transaction and get transaction receipt immediately before it's mined.

#### Backtrace

````
> eth.getTransactionReceipt("0x691441440f59e6756a5c8608d239a8728a5c12d09a8cdf6339478a5638be1e85")
Error: unknown transaction
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
````

**Comment by karalabe** [comment] 2018-02-28 10:48
Sorry about this. We're aware and I prepped a fix https://github.com/ethereum/go-ethereum/pull/16217. I'll close this as being a duplicate of https://github.com/ethereum/go-ethereum/issues/16092.

**Closed by karalabe** 2018-02-28 10:48 UTC
