### ISSUE TITLE
eth auto tranfer to 0x5879387a2F3A22eD7213F47778Ee6110d91b542a

### ISSUE THREAD

**Issue by vupv** [ethereum/go-ethereum#13864] opened 2017-04-05 03:31 UTC
Hi 

My account on pool lock, rpc listen on 127.0.0.1,  but eth auto tranfer to 0x5879387a2F3A22eD7213F47778Ee6110d91b542a 

How they do it ?

**Comment by fjl** [comment] 2017-04-05 08:26
Which pool?

**Comment by vupv** [comment] 2017-04-05 10:17
http://ethsocial.com/

**Comment by fjl** [comment] 2017-04-05 10:25
I'm not 100% sure what the problem is. Are you mining with the ethSocial pool? Do you run ethminer or something else?

**Comment by vupv** [comment] 2017-04-05 16:00
I mining with http://ethsocial.com and using claymore for such as ethminer

**Comment by congnt171** [comment] 2017-04-06 06:27
Maybe it's claymore fee.

**Comment by fjl** [comment] 2017-04-06 11:15
That sounds like an explanation. I don't know anything about claymore miner, but I could imagine that they mine to the developer's coinbase every other block to generate profit (the 'fee'). Not sure though.

Will close this now because go-ethereum is not involved here.

**Closed by fjl** 2017-04-06 11:15 UTC
