### ISSUE TITLE
Clique with short period: "fat" long running transactions are never processed (always interrupted)

### ISSUE THREAD

**Issue by illya-havsiyevych** [ethereum/go-ethereum#19475] opened 2019-04-17 15:21 UTC
The issue might be related to the code
https://github.com/ethereum/go-ethereum/blob/master/miner/worker.go#L723

So "fat" long running transactions are always get interrupted, never processed and stuck in txpool as pending

But it might be expected behavior of Clique consensus :(

#### System information
```
Version: 1.8.26-stable
Git Commit: cdae1c59abc32f85debfa29577fbf1ed036ebf73
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
```
OS & Version: Windows/Linux

#### Expected behaviour
transaction processed, block mined with a delay

#### Actual behaviour
transaction is never processed, block mined within usual `clique period`

#### Steps to reproduce the behaviour
- prepare PoA network with clique period: 1s
- submit "fat" `tx` with processing time >> clique period

CC @rjl493456442 @karalabe @holiman @fjl @yuriytkach @pra-github

#### Logs of 4 authority nodes with period: 0s
```
node4 | INFO [04-17|15:28:52.942] Commit new mining work                   number=187 sealhash=e7fc76…a74a66 uncles=0 txs=1 gas=2809992  fees=0 elapsed=15.428ms
node4 | INFO [04-17|15:28:52.943] Imported new chain segment               blocks=1 txs=1 mgas=2.810  elapsed=23.087ms  mgasps=121.709  number=187 hash=57d201…62ab59 cache=10.50mB
node4 | INFO [04-17|15:28:52.944] 🔨 block reached canonical chain          number=180 hash=9e8af2…b82435
node4 | INFO [04-17|15:28:52.944] Commit new mining work                   number=188 sealhash=d38f71…3995c5 uncles=0 txs=0 gas=0        fees=0 elapsed=194.1µs
node4 | INFO [04-17|15:28:52.944] Sealing paused, waiting for transactions
node4 | INFO [04-17|15:28:52.944] Commit new mining work                   number=188 sealhash=d38f71…3995c5 uncles=0 txs=0 gas=0        fees=0 elapsed=678.1µs

node2 | INFO [04-17|15:28:53.942] Commit new mining work                   number=188 sealhash=944aa5…81d012 uncles=0 txs=0 gas=0        fees=0 elapsed=109.4µs

node4 | INFO [04-17|15:28:53.943] Commit new mining work                   number=188 sealhash=ee172c…a52450 uncles=0 txs=0 gas=0        fees=0 elapsed=333.3µs
node4 | INFO [04-17|15:28:53.948] Sealing paused, waiting for transactions

node1 | INFO [04-17|15:28:53.940] Commit new mining work                   number=188 sealhash=944aa5…81d012 uncles=0 txs=0 gas=0        fees=0 elapsed=79µs
node3 | INFO [04-17|15:28:53.940] Commit new mining work                   number=188 sealhash=944aa5…81d012 uncles=0 txs=0 gas=0        fees=0 elapsed=91.5µs
node1 | INFO [04-17|15:28:53.944] Sealing paused, waiting for transactions
node2 | INFO [04-17|15:28:53.956] Sealing paused, waiting for transactions

node3 | INFO [04-17|15:28:53.958] Sealing paused, waiting for transactions
node3 | INFO [04-17|15:28:53.958] Signed recently, must wait for others
node3 | INFO [04-17|15:28:53.958] Commit new mining work                   number=188 sealhash=c50a73…8f1ee2 uncles=0 txs=1 gas=2810184  fees=0 elapsed=18.182ms

node2 | INFO [04-17|15:28:53.959] Commit new mining work                   number=188 sealhash=c50a73…8f1ee2 uncles=0 txs=1 gas=2810184  fees=0 elapsed=16.525ms
node2 | INFO [04-17|15:28:53.959] Signed recently, must wait for others

node4 | INFO [04-17|15:28:53.965] Commit new mining work                   number=188 sealhash=d4ecde…fb3fd8 uncles=0 txs=1 gas=2810184  fees=0 elapsed=22.982ms
node1 | INFO [04-17|15:28:53.964] Commit new mining work                   number=188 sealhash=c50a73…8f1ee2 uncles=0 txs=1 gas=2810184  fees=0 elapsed=24.565ms
node4 | INFO [04-17|15:28:53.968] Successfully sealed new block            number=188 sealhash=d4ecde…fb3fd8 hash=286451…1be0e0 elapsed=19.510ms
node4 | INFO [04-17|15:28:53.968] 🔗 mined potential block                  number=188 hash=286451…1be0e0
node4 | INFO [04-17|15:28:53.977] Commit new mining work                   number=189 sealhash=fcfc3f…e92ca2 uncles=0 txs=0 gas=0        fees=0 elapsed=1.236ms
node4 | INFO [04-17|15:28:53.977] Sealing paused, waiting for transactions

node1 | INFO [04-17|15:28:53.982] Imported new chain segment               blocks=1 txs=1 mgas=2.810  elapsed=13.249ms  mgasps=212.102  number=188 hash=286451…1be0e0 cache=10.61mB
node1 | INFO [04-17|15:28:53.983] 🔗 block reached canonical chain          number=181 hash=cc5b33…1b02d3
node1 | INFO [04-17|15:28:53.984] Commit new mining work                   number=189 sealhash=eb74c1…fc0234 uncles=0 txs=0 gas=0        fees=0 elapsed=678.2µs
node1 | INFO [04-17|15:28:53.984] Sealing paused, waiting for transactions

node3 | INFO [04-17|15:28:53.990] Imported new chain segment               blocks=1 txs=1 mgas=2.810  elapsed=12.511ms  mgasps=224.608  number=188 hash=286451…1be0e0 cache=10.61mB
node3 | INFO [04-17|15:28:53.990] Commit new mining work                   number=189 sealhash=fcfc3f…e92ca2 uncles=0 txs=0 gas=0        fees=0 elapsed=128.8µs
node3 | INFO [04-17|15:28:53.991] Sealing paused, waiting for transactions

node2 | INFO [04-17|15:28:53.993] Imported new chain segment               blocks=1 txs=1 mgas=2.810  elapsed=22.739ms  mgasps=123.584  number=188 hash=286451…1be0e0 cache=10.61mB
node2 | INFO [04-17|15:28:53.997] Commit new mining work                   number=189 sealhash=fcfc3f…e92ca2 uncles=0 txs=0 gas=0        fees=0 elapsed=3.577ms
node2 | INFO [04-17|15:28:53.997] Sealing paused, waiting for transactions

node1 | INFO [04-17|15:28:55.040] Commit new mining work                   number=189 sealhash=2118cc…2a1816 uncles=0 txs=0 gas=0        fees=0 elapsed=64.8µs
node1 | INFO [04-17|15:28:55.042] Sealing paused, waiting for transactions

node3 | INFO [04-17|15:28:55.043] Sealing paused, waiting for transactions
node3 | INFO [04-17|15:28:55.043] Commit new mining work                   number=189 sealhash=bdfe1b…587ebf uncles=0 txs=0 gas=0        fees=0 elapsed=3.097ms

node4 | INFO [04-17|15:28:55.048] Commit new mining work                   number=189 sealhash=bdfe1b…587ebf uncles=0 txs=0 gas=0        fees=0 elapsed=329.7µs
node4 | INFO [04-17|15:28:55.048] Sealing paused, waiting for transactions

node2 | INFO [04-17|15:28:55.062] Commit new mining work                   number=189 sealhash=bdfe1b…587ebf uncles=0 txs=0 gas=0        fees=0 elapsed=63.9µs
node2 | INFO [04-17|15:28:55.083] Sealing paused, waiting for transactions

node3 | INFO [04-17|15:29:02.287] Commit new mining work                   number=189 sealhash=2a8f93…3c0933 uncles=0 txs=1 gas=929492232 fees=0 elapsed=7.246s
node3 | INFO [04-17|15:29:03.074] Successfully sealed new block            number=189 sealhash=2a8f93…3c0933 hash=b53a07…931275 elapsed=789.845ms
node3 | INFO [04-17|15:29:03.082] 🔗 block reached canonical chain          number=182 hash=5175b6…8a6d22
node3 | INFO [04-17|15:29:03.082] 🔨 mined potential block                  number=189 hash=b53a07…931275
node3 | INFO [04-17|15:29:03.093] Commit new mining work                   number=190 sealhash=256bbe…e51902 uncles=0 txs=0 gas=0         fees=0 elapsed=10.879ms
node3 | INFO [04-17|15:29:03.095] Sealing paused, waiting for transactions

node1 | INFO [04-17|15:29:03.805] Commit new mining work                   number=189 sealhash=79208b…319e9e uncles=0 txs=1 gas=929492232 fees=0 elapsed=8.764s

node2 | INFO [04-17|15:29:04.103] Commit new mining work                   number=189 sealhash=2a8f93…3c0933 uncles=0 txs=1 gas=929492232 fees=0 elapsed=9.041s
node2 | INFO [04-17|15:29:04.133] Signed recently, must wait for others

node1 | INFO [04-17|15:29:04.941] Successfully sealed new block            number=189 sealhash=79208b…319e9e hash=37ca74…bf043e elapsed=1.136s
node1 | INFO [04-17|15:29:04.944] 🔨 mined potential block                  number=189 hash=37ca74…bf043e
node1 | INFO [04-17|15:29:04.958] Commit new mining work                   number=190 sealhash=955bbd…136aaf uncles=0 txs=0 gas=0         fees=0 elapsed=2.261ms
node1 | INFO [04-17|15:29:05.095] Sealing paused, waiting for transactions
node1 | INFO [04-17|15:29:05.096] Commit new mining work                   number=190 sealhash=955bbd…136aaf uncles=0 txs=0 gas=0         fees=0 elapsed=140.224ms

node4 | INFO [04-17|15:29:05.319] Commit new mining work                   number=189 sealhash=2a8f93…3c0933 uncles=0 txs=1 gas=929492232 fees=0 elapsed=10.271s
node4 | INFO [04-17|15:29:05.332] Signed recently, must wait for others
```

#### Logs of 4 authority nodes with period: 1s
The same client code as above, `fat` tx got stuck in txpool as pending
Please check empty new blocks at the end
```
node3 | INFO [04-17|15:50:54.020] Signed recently, must wait for others
node4 | INFO [04-17|15:50:54.027] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=1.544ms   mgasps=0.000    number=431 hash=942cb9…d61db3 cache=8.04mB
node4 | INFO [04-17|15:50:54.036] Commit new mining work                   number=432 sealhash=d7d383…68c43c uncles=0 txs=0  gas=0        fees=0 elapsed=739.6µs

node1 | INFO [04-17|15:50:54.031] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=1.939ms   mgasps=0.000    number=431 hash=942cb9…d61db3 cache=8.04mB
node1 | INFO [04-17|15:50:54.038] Commit new mining work                   number=432 sealhash=d7d383…68c43c uncles=0 txs=0  gas=0        fees=0 elapsed=242.6µs
node4 | INFO [04-17|15:50:54.045] Signed recently, must wait for others

node3 | INFO [04-17|15:50:54.067] Commit new mining work                   number=432 sealhash=9db447…ca6c45 uncles=0 txs=1  gas=2809992  fees=0 elapsed=62.077ms
node3 | INFO [04-17|15:50:54.067] Signed recently, must wait for others

node4 | INFO [04-17|15:50:54.072] Commit new mining work                   number=432 sealhash=9db447…ca6c45 uncles=0 txs=1  gas=2809992  fees=0 elapsed=36.708ms
node4 | INFO [04-17|15:50:54.072] Signed recently, must wait for others

node2 | INFO [04-17|15:50:54.078] Commit new mining work                   number=432 sealhash=e369bb…f37008 uncles=0 txs=1  gas=2809992  fees=0 elapsed=66.565ms
node1 | INFO [04-17|15:50:54.079] Commit new mining work                   number=432 sealhash=9db447…ca6c45 uncles=0 txs=1  gas=2809992  fees=0 elapsed=41.428ms

node2 | INFO [04-17|15:50:55.009] Successfully sealed new block            number=432 sealhash=e369bb…f37008 hash=bf3c99…d17d99 elapsed=931.241ms
node2 | INFO [04-17|15:50:55.009] 🔗 mined potential block                  number=432 hash=bf3c99…d17d99
node2 | INFO [04-17|15:50:55.031] Commit new mining work                   number=433 sealhash=d3354f…087bfb uncles=0 txs=0  gas=0        fees=0 elapsed=21.626ms
node2 | INFO [04-17|15:50:55.029] Signed recently, must wait for others

node3 | INFO [04-17|15:50:55.043] Imported new chain segment               blocks=1 txs=1  mgas=2.810  elapsed=19.505ms  mgasps=144.060 number=432 hash=bf3c99…d17d99 cache=8.09mB
node3 | INFO [04-17|15:50:55.046] Commit new mining work                   number=433 sealhash=d3354f…087bfb uncles=0 txs=0  gas=0        fees=0 elapsed=621.3µs

node4 | INFO [04-17|15:50:55.062] Imported new chain segment               blocks=1 txs=1  mgas=2.810  elapsed=45.724ms  mgasps=61.455   number=432 hash=bf3c99…d17d99 cache=8.09mB
node4 | INFO [04-17|15:50:55.063] Commit new mining work                   number=433 sealhash=d3354f…087bfb uncles=0 txs=0  gas=0        fees=0 elapsed=254.1µs

node3 | INFO [04-17|15:50:55.046] Signed recently, must wait for others

node1 | INFO [04-17|15:50:55.071] Imported new chain segment               blocks=1 txs=1  mgas=2.810  elapsed=52.661ms  mgasps=53.359   number=432 hash=bf3c99…d17d99 cache=8.09mB
node1 | INFO [04-17|15:50:55.071] 🔗 block reached canonical chain          number=425 hash=b262b4…c4b26e
node1 | INFO [04-17|15:50:55.071] Commit new mining work                   number=433 sealhash=5e5991…2d8e51 uncles=0 txs=0  gas=0        fees=0 elapsed=179.2µs
node1 | INFO [04-17|15:50:55.072] Commit new mining work                   number=433 sealhash=5e5991…2d8e51 uncles=0 txs=0  gas=0        fees=0 elapsed=719µs
node1 | INFO [04-17|15:50:56.001] Successfully sealed new block            number=433 sealhash=5e5991…2d8e51 hash=ed7e3f…792d00 elapsed=929.806ms
node1 | INFO [04-17|15:50:56.001] 🔗 mined potential block                  number=433 hash=ed7e3f…792d00
node1 | INFO [04-17|15:50:56.004] Commit new mining work                   number=434 sealhash=71ccef…54abd9 uncles=0 txs=0  gas=0        fees=0 elapsed=1.926ms
node1 | INFO [04-17|15:50:56.003] Signed recently, must wait for others

node3 | INFO [04-17|15:50:56.018] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=11.785ms  mgasps=0.000   number=433 hash=ed7e3f…792d00 cache=8.09mB
node4 | INFO [04-17|15:50:56.018] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=949.8µs   mgasps=0.000    number=433 hash=ed7e3f…792d00 cache=8.09mB
node2 | INFO [04-17|15:50:56.019] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=6.291ms   mgasps=0.000   number=433 hash=ed7e3f…792d00 cache=8.09mB

node4 | INFO [04-17|15:50:56.023] 🔨 block reached canonical chain          number=426 hash=4b5cb7…f1b1ba
node4 | INFO [04-17|15:50:56.024] Commit new mining work                   number=434 sealhash=74b189…a7ff17 uncles=0 txs=0  gas=0        fees=0 elapsed=1.483ms

node2 | INFO [04-17|15:50:56.032] Commit new mining work                   number=434 sealhash=71ccef…54abd9 uncles=0 txs=0  gas=0        fees=0 elapsed=711.2µs
node3 | INFO [04-17|15:50:56.041] Commit new mining work                   number=434 sealhash=71ccef…54abd9 uncles=0 txs=0  gas=0        fees=0 elapsed=713.5µs
node2 | INFO [04-17|15:50:56.044] Signed recently, must wait for others
node3 | INFO [04-17|15:50:56.069] Commit new mining work                   number=434 sealhash=5d1298…6232fe uncles=0 txs=1  gas=2810184  fees=0 elapsed=28.926ms

node1 | INFO [04-17|15:50:56.080] Commit new mining work                   number=434 sealhash=5d1298…6232fe uncles=0 txs=1  gas=2810184  fees=0 elapsed=77.884ms
node1 | INFO [04-17|15:50:56.080] Signed recently, must wait for others

node2 | INFO [04-17|15:50:56.083] Commit new mining work                   number=434 sealhash=5d1298…6232fe uncles=0 txs=1  gas=2810184  fees=0 elapsed=52.035ms
node2 | INFO [04-17|15:50:56.083] Signed recently, must wait for others

node4 | INFO [04-17|15:50:56.083] Commit new mining work                   number=434 sealhash=54da00…be58b1 uncles=0 txs=1  gas=2810184  fees=0 elapsed=61.091ms
node4 | INFO [04-17|15:50:57.004] Successfully sealed new block            number=434 sealhash=54da00…be58b1 hash=220052…b8ce97 elapsed=920.881ms
node4 | INFO [04-17|15:50:57.004] 🔨 mined potential block                  number=434 hash=220052…b8ce97
node4 | INFO [04-17|15:50:57.006] Commit new mining work                   number=435 sealhash=add2fb…d40f3a uncles=0 txs=0  gas=0        fees=0 elapsed=651.8µs
node4 | INFO [04-17|15:50:57.006] Signed recently, must wait for others

node2 | INFO [04-17|15:50:57.038] Imported new chain segment               blocks=1 txs=1  mgas=2.810  elapsed=31.012ms  mgasps=90.615  number=434 hash=220052…b8ce97 cache=8.13mB
node2 | INFO [04-17|15:50:57.038] Commit new mining work                   number=435 sealhash=add2fb…d40f3a uncles=0 txs=0  gas=0        fees=0 elapsed=182.2µs
node2 | INFO [04-17|15:50:57.040] Commit new mining work                   number=435 sealhash=add2fb…d40f3a uncles=0 txs=0  gas=0        fees=0 elapsed=1.932ms

node3 | INFO [04-17|15:50:57.040] Imported new chain segment               blocks=1 txs=1  mgas=2.810  elapsed=25.651ms  mgasps=109.554 number=434 hash=220052…b8ce97 cache=8.13mB
node1 | INFO [04-17|15:50:57.042] Imported new chain segment               blocks=1 txs=1  mgas=2.810  elapsed=35.324ms  mgasps=79.553   number=434 hash=220052…b8ce97 cache=8.13mB

node3 | INFO [04-17|15:50:57.043] 🔨 block reached canonical chain          number=427 hash=d66672…32bf44
node3 | INFO [04-17|15:50:57.044] Commit new mining work                   number=435 sealhash=2e589f…565d97 uncles=0 txs=0  gas=0        fees=0 elapsed=3.300ms

node1 | INFO [04-17|15:50:57.046] Commit new mining work                   number=435 sealhash=add2fb…d40f3a uncles=0 txs=0  gas=0        fees=0 elapsed=577.3µs
node1 | INFO [04-17|15:50:57.046] Signed recently, must wait for others

node3 | INFO [04-17|15:50:58.000] Successfully sealed new block            number=435 sealhash=2e589f…565d97 hash=35ce59…271154 elapsed=956.772ms
node3 | INFO [04-17|15:50:58.000] 🔗 mined potential block                  number=435 hash=35ce59…271154
node3 | INFO [04-17|15:50:58.002] Commit new mining work                   number=436 sealhash=acba54…d72259 uncles=0 txs=0  gas=0        fees=0 elapsed=451.5µs
node3 | INFO [04-17|15:50:58.003] Signed recently, must wait for others

node1 | INFO [04-17|15:50:58.004] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=2.029ms   mgasps=0.000    number=435 hash=35ce59…271154 cache=8.13mB

node4 | INFO [04-17|15:50:58.005] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=818.3µs   mgasps=0.000    number=435 hash=35ce59…271154 cache=8.13mB
node4 | INFO [04-17|15:50:58.008] Commit new mining work                   number=436 sealhash=acba54…d72259 uncles=0 txs=0  gas=0        fees=0 elapsed=136.9µs

node2 | INFO [04-17|15:50:58.008] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=5.466ms   mgasps=0.000   number=435 hash=35ce59…271154 cache=8.13mB
node1 | INFO [04-17|15:50:58.009] Commit new mining work                   number=436 sealhash=acba54…d72259 uncles=0 txs=0  gas=0        fees=0 elapsed=2.416ms

node2 | INFO [04-17|15:50:58.010] 🔗 block reached canonical chain          number=428 hash=44a253…ec8445
node2 | INFO [04-17|15:50:58.010] Commit new mining work                   number=436 sealhash=771c23…18dcac uncles=0 txs=0  gas=0        fees=0 elapsed=217.5µs

node4 | INFO [04-17|15:50:58.032] Signed recently, must wait for others

node2 | INFO [04-17|15:50:59.002] Successfully sealed new block            number=436 sealhash=771c23…18dcac hash=81fcf9…1545d7 elapsed=992.109ms
node2 | INFO [04-17|15:50:59.002] 😱 mined potential block                  number=436 hash=81fcf9…1545d7

node1 | INFO [04-17|15:50:59.016] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=694.4µs   mgasps=0.000    number=436 hash=81fcf9…1545d7 cache=8.07mB
node3 | INFO [04-17|15:50:59.026] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=16.185ms  mgasps=0.000   number=436 hash=81fcf9…1545d7 cache=8.07mB
node4 | INFO [04-17|15:50:59.043] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=26.317ms  mgasps=0.000    number=436 hash=81fcf9…1545d7 cache=8.07mB

node1 | INFO [04-17|15:50:59.655] Successfully sealed new block            number=436 sealhash=acba54…d72259 hash=afe880…e58a7b elapsed=1.645s
node1 | INFO [04-17|15:50:59.655] 🔗 block reached canonical chain          number=429 hash=2ab480…408ec6
node1 | INFO [04-17|15:50:59.656] 🔨 mined potential block                  number=436 hash=afe880…e58a7b

node3 | INFO [04-17|15:50:59.657] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=160.8µs   mgasps=0.000   number=436 hash=afe880…e58a7b cache=8.07mB
node4 | INFO [04-17|15:50:59.657] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=181.8µs   mgasps=0.000    number=436 hash=afe880…e58a7b cache=8.07mB
node2 | INFO [04-17|15:50:59.658] Imported new chain segment               blocks=1 txs=0  mgas=0.000  elapsed=179.8µs   mgasps=0.000   number=436 hash=afe880…e58a7b cache=8.07mB
```

**Comment by rjl493456442** [comment] 2019-04-18 05:58
Do you broadcast the `fat` transaction to all sealer nodes?

**Comment by illya-havsiyevych** [comment] 2019-04-18 06:01
I have 4 sealer + 1 gw node
and I send it only to that gw node

**Comment by rjl493456442** [comment] 2019-04-18 06:09
The transaction should be broadcasted through the `gw` node to all sealer nodes. If so, no matter how much the clique period is, the worker will execute the tx first and then throw out the block into the network.

The interruption could only happen some sealer nodes send the empty block without including the fat tx.

**Comment by illya-havsiyevych** [comment] 2019-04-18 06:14
well, hard to comment but
- all 5 nodes have 4 peers
- all nodes have 1 pending `tx` when it stuck
- 1 node PoA network in `--dev` have same issue and I can generate more logs in this mode

**Comment by illya-havsiyevych** [comment] 2019-04-18 06:39
I also can run the same over older `geth` versions
Just point me good candidates (i.e. before some major refactorings)

**Comment by illya-havsiyevych** [comment] 2019-04-18 07:01
... and quick response `1.8.13` did not have such issue.
With period `1s` I can see blocks mined in `6-13s`

**Comment by illya-havsiyevych** [comment] 2019-04-18 07:20
Another good version to try ?

**Comment by rjl493456442** [comment] 2019-04-18 10:56
@illya-havsiyevych I think I figure out the issue here. For Pow-favour miner,  geth will generate an empty block first and send it to the consensus engine. Until the transaction execution is finished, the completed block will replace the empty block if **the PoW result hasn't been found**.

But in the Clique, if the `Fat transaction` can't be finished in the `Period`, the empty block will be broadcasted.

**Comment by illya-havsiyevych** [comment] 2019-04-18 11:02
Great, will you be able to fix it ?
I'm ready to test any new version

**Comment by rjl493456442** [comment] 2019-04-18 11:05
I'm working on this now. Probably want to provide another flag to disable the advanced sealing mechanism.

**Comment by illya-havsiyevych** [comment] 2019-04-18 11:13
I personally Ok with another flag

**Comment by rjl493456442** [comment] 2019-04-18 12:31
@illya-havsiyevych I open a PR (#19480) to fix it. Could you please have a try? Thanks.

**Comment by rjl493456442** [comment] 2019-04-19 08:57
@illya-havsiyevych Really sorry, @karalabe points out that if the transaction execution time is longer than block time, it's kind of DoS attack. The right solution is either raise the block time(clique period) or disassemble the fat transaction to several tiny ones.

**Comment by illya-havsiyevych** [comment] 2019-04-19 09:07
Fair comment 
as I said before disallowing this might `be expected behavior of Clique consensus :(`

PS. can we still keep it but rename to `allow-insecure-miner-noadvance` ?
PPS. we always can create own version based on your changes

**Comment by illya-havsiyevych** [comment] 2019-04-19 09:55
Just finished testing of PR (#19480)
- `Geth/v1.9.0-unstable-9e9062b9/linux-amd64/go1.12.4`
- docker based 4+1 PoA network
- network behavior is some mix of `usual clique` and `period=0` (i.e. no empty block sometimes)
- no issue when `fat` tx is stuck in pending forever

**Comment by rjl493456442** [comment] 2019-04-22 07:23
> no issue when fat tx is stuck in pending forever
You mean the issue is gone?

**Comment by illya-havsiyevych** [comment] 2019-04-22 07:32
I was not able to reproduce the issue with fix reverted here
https://github.com/ethereum/go-ethereum/pull/19480/commits/7233837a1cc636a8ac60a69f560373ef2e2e50ef

But original version `1.8.26-stable`
and I bet `current master` still have the issue

**Comment by rjl493456442** [comment] 2019-04-22 07:36
Yeah, I think it will be better to increase the clique period in your private chain OR implement the `allow-insecure-miner-noadvance` by yourself. It's not safe to introduce this flag into the master branch.

**Comment by karalabe** [comment] 2019-05-02 11:47
I will be closing this issue as works-as-intended/wont-fix. If a transaction takes more time to execute than the block time, that is a DoS attack, since the entire network will be stuck processing it while the chain moves forward. The same transaction will wreck havoc in the pending blocks even if not mined, since nodes will keep trying to execute it and getting interrupted (or not), causing wasted CPU usage. Lastly if multiple miners seal blocks with such a transaction, that would cause reorgs that take many many blocks to actually execute and finalize, again DoSing the chain.

Unfortunately the way Ethereum selects the best/heaviest chain is incompatible with blocks exceeding their allotted time. The best solution is to split up such huge transactions into multiple smaller ones that fit in a block: for normal contract execution, add support for yielding and continuing where a previous left off; for contract deployment split it into multiple cooperating contracts.

**Closed by karalabe** 2019-05-02 11:47 UTC
