### ISSUE TITLE
[BUG] geth contract does not save address array values across calls 

### ISSUE THREAD

**Issue by SethVgr** [ethereum/go-ethereum#2877] opened 2016-07-28 14:34 UTC
# Checklist
- [done ] built geth 1.4.10
- [done ] installed it over previous version (1.3.5.) (`sudo cp geth /usr/bin/geth`)
- [done ] compiled  and deployed the following contract:

```
contract C {
    
    address[] goodAddr;
    address[] badAddr;
    
    function initAddr() constant {
        
        if(goodAddr.length == 0) {
            goodAddr.push(0x029ddf2082bc96d321c9769ec8e27e10b3cb16ee);
        }
        
        if(badAddr.length == 0) {
            badAddr.push(0x115744603fedb255e5ab4765cc1dc6c832639fd5);
        }
        
        if(goodAddr.length == 1 && badAddr.length == 1) {
            return;
        }
        
        for(uint256 i = 0; i < goodAddr.length; i++) {
            if(goodAddr[i] == 0x029ddf2082bc96d321c9769ec8e27e10b3cb16ee)
                return;
        }
        
        for(i = 0; i < badAddr.length; i++) {
            if(badAddr[i] == 0x115744603fedb255e5ab4765cc1dc6c832639fd5)
                return;
        }
        
        goodAddr.push(0x029ddf2082bc96d321c9769ec8e27e10b3cb16ee);
        badAddr.push(0x115744603fedb255e5ab4765cc1dc6c832639fd5);
    }
    
    function getGoodAddrLocal(uint256 i) constant returns (address) {
        goodAddr.push(0x029ddf2082bc96d321c9769ec8e27e10b3cb16ee);
        return goodAddr[i];
    }
    
    function getGoodAddr(uint256 i) constant returns (address) {
        if(i < 0 || i >= goodAddr.length) {
            return 0x0000000000000000000000000000000000000000;
        } else {
            return goodAddr[i];
        }
        
    }
    
    function getBadAddr(uint256 i) constant returns (address) {
        if(i < 0 || i >= badAddr.length) {
            return 0x0000000000000000000000000000000000000000;
        } else {
            return badAddr[i];
        }
    }
}
```
The contract was compiled using [browser solidity](https://ethereum.github.io/browser-solidity/#version=soljson-latest.js) and deployed on a private test net running a single **geth** node of version 1.4.10

## System/environment

- OS: debian 8.3 Jessie x64, kernel version 3.16.0-4-amd64, virtual machine, running on VirtualBox, host machine Win7 x64, NAT network settings used

## Expected behaviour

After deployment as shown next:

```
> eth.accounts
["0x029ddf2082bc96d321c9769ec8e27e10b3cb16ee", "0x115744603fedb255e5ab4765cc1dc6c832639fd5"]
> {inputs":[{"name":"i","type":"uint256"}],"name":"getGoodAddrLocal","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":true,"inputs":[],"name":"initAddr","outputs":[],"type":"function"}]);
undefined
> var c = cContract.new(
...    {
......      from: web3.eth.accounts[0], 
...... {06001016106a4565b5090565b5b5050509190906000526020600020900160005b73115744603fedb255e5ab4765cc1dc6c832639fd5909190916101000a81548173ffffffffffffffffffffffffffffffffffffffff02191690830217905550505b5056', 
......      gas: 4700000
......    }, function (e, contract){
......     console.log(e, contract);
......     if (typeof contract.address !== 'undefined') {
.........          console.log('Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);
.........     }
......  });
null [object Object]
undefined
> null [object Object]
Contract mined! address: 0x814625bf84bfc6b64f995c2974ce9a20d85ffc38 transactionHash: 0xfe635b9b52e6e578b684cbb5ad46598c85c9079344faeecd7b3203703438b9cd
```

upon calling method **initAddr()** the two address arrays should be initialized with a default address each. 

## Observed behaviour

Contract storage does not work; the addresses are not kept in the arrays across calls:

```
> c.initAddr.call();
[]
> c.getGoodAddr(0);
"0x0000000000000000000000000000000000000000"
> c.getBadAddr(0);
"0x0000000000000000000000000000000000000000"
> c.getGoodAddrLocal(0);
"0x029ddf2082bc96d321c9769ec8e27e10b3cb16ee"
> c.getGoodAddrLocal(0);
"0x029ddf2082bc96d321c9769ec8e27e10b3cb16ee"
> c.getGoodAddrLocal(1);
"0x"
> 
```

I'm not sure if this is a solidity or a **geth** bug.

**Comment by joeb000** [comment] 2016-07-28 15:34
this happens to me when i use browser solidty as well. instead of copying and pasting straight into the geth console, first paste the web3 deploy to a notepad or text editor. then paste each command individually. that fixed my problem and is also the reason i stopped using the solidity compiler.

**Comment by SethVgr** [comment] 2016-07-28 16:01
It's pretty strange. I will try it out for the above code. So you are using a local version of the solidity compiler now?

**Comment by joeb000** [comment] 2016-07-28 17:07
```c.initAddr.call();
[]
> c.getAddr.call(0);
"0x0000000000000000000000000000000000000000"
> 
```

**Comment by joeb000** [comment] 2016-07-28 17:13
You need to send the initAddr as a transaction, not just a call()

**Comment by joeb000** [comment] 2016-07-28 17:16
Take the `constant` modifier off the initAddr and redeploy it. Then when you want to send a transaction to call initAddr do this:

`c.initAddr({from:eth.accounts[0],gas:400000})`

**Comment by joeb000** [comment] 2016-07-28 17:17
You may want to close this as this is an issue with the way you wrote your smart contract, not geth or solidity :)

**Comment by SethVgr** [comment] 2016-07-29 09:13
So the **initAddr()** has to be sent as a transaction because it changes the state of the contract and costs gas, no? Read operations are essentially free since they only query the block chain and no operations are executed by miners.

**Comment by obscuren** [comment] 2016-07-29 11:58
Yes, `initAddr` must be supplied as a transaction (i.e. use `send` instead of `call`). That initialisation method does not only read.

You can't `call` anything that changes state (well you could, but nothing happens). I'm closing this issue as it's working as intended.

**Closed by obscuren** 2016-07-29 11:58 UTC

**Comment by SethVgr** [comment] 2016-07-29 12:31
@obscuren  

> You can't call anything that changes state (well you could, but nothing happens). I'm closing this issue as it's working as intended.

So how can I call a function that takes two values and adds them to the state of the contract?
