### ISSUE TITLE
geth -pricelimit not very useful after EIP1559

### ISSUE THREAD

**Issue by Kzenox7** [ethereum/go-ethereum#23837] opened 2021-10-30 23:32 UTC
I'd like to raise a potential issue with the `geth -pricelimit` parameter and EIP1559.

From my observations it looks like this parameter only checks the value of `MaxPriorityFeePerGas` instead of something more useful like `MaxFeePerGas`. I believe that the `-pricelimit` is now fairly useless since `MaxPriorityFeePerGas` is almost always around 1 to 3 Gwei even though the total tx gas price could easily be 100+ Gwei. 

Due to this behaviour I have set this parameter to 1 Gwei which causes the geth node to receive a huge amount of low gas pre-EIP1559 tx's that have been pending for months.

It is not in alignment with the way it works for  pre-EIP1559 transactions.

**Comment by rjl493456442** [comment] 2021-11-01 05:44
It's an interesting issue! I mark it as triage to discuss with team.

**Comment by fjl** [comment] 2021-11-04 09:34
The issue is: in TxPool, the value of `-pricelimit` is stored in the field `gasLimit`. We apply this check when validating incoming transactions:

https://github.com/ethereum/go-ethereum/blob/03bc8b7858e0b019132de5fd5df6e8ec414d1dfd/core/tx_pool.go#L624-L627

However, we apply a different check when selecting transactions for mining:

https://github.com/ethereum/go-ethereum/blob/03bc8b7858e0b019132de5fd5df6e8ec414d1dfd/core/tx_pool.go#L547-L549

I think this issue could be resolved by making the check in `validateTx` also use the `EffectiveGasTipIntCmp`.

**Comment by XWJACK** [comment] 2021-12-07 01:09
> The issue is: in TxPool, the value of `-pricelimit` is stored in the field `gasPrice`. We apply this check when validating incoming transactions:
> 
> https://github.com/ethereum/go-ethereum/blob/03bc8b7858e0b019132de5fd5df6e8ec414d1dfd/core/tx_pool.go#L624-L627
> 
> However, we apply a different check when selecting transactions for mining:
> 
> https://github.com/ethereum/go-ethereum/blob/03bc8b7858e0b019132de5fd5df6e8ec414d1dfd/core/tx_pool.go#L547-L549
> 
> I think this issue could be resolved by making the check in `validateTx` also use the `EffectiveGasTipIntCmp` method.

`pool.gasPrice` is config by `pricelimit`. 
https://github.com/ethereum/go-ethereum/blob/cc87cbd70af18241f79908eec10bb3c51a9fbda4/core/tx_pool.go#L300

`baseFee` will always changed by tx pool . so if you do that, users will not able to send tx below baseFee rather than `pricelimit`. highly recommended revert this pr  #23855.
https://github.com/ethereum/go-ethereum/blob/cc87cbd70af18241f79908eec10bb3c51a9fbda4/core/tx_list.go#L424

**Comment by XWJACK** [comment] 2021-12-07 15:47
may be we should using `GasFeeCapIntCmp`?
```go
        // Drop non-local transactions under our own minimal accepted gas price or tip.
	if !local && tx.GasFeeCapIntCmp(pool.gasPrice) < 0 {
		return ErrUnderpriced
	}
```
https://github.com/ethereum/go-ethereum/blob/7f7877a02326ecace5c120ddced413880c272170/core/types/transaction.go#L308-L311
`gasFeeCap ` reference `MaxFeePerGas`
https://github.com/ethereum/go-ethereum/blob/7f7877a02326ecace5c120ddced413880c272170/core/types/transaction.go#L275-L276

**Comment by fjl** [comment] 2021-12-07 16:54
Best if we keep discussion in the new issue #24080

**Closed by fjl** 2021-12-07 16:54 UTC
Labels: type:docs, status:triage
