### ISSUE TITLE
clique snapshot show may have bugs

### ISSUE THREAD

**Issue by gtrandxiangyu** [ethereum/go-ethereum#19850] opened 2019-07-17 13:35 UTC
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

System information

Geth version: 1.8.15
OS & Version: Linux
Commit hash : (if develop)

###Expected behaviour

all blocks must have snapshot recents and have sealed account.

#### Actual behaviour
This block do not have snapshot but it really sealed by 0x22d7c2029f8624495f0fba0dee945417a6f2dbf9

> eth.getBlock(14250000)
{
  difficulty: 2,
  extraData: "0xd88301080f846765746888676f312e31302e32856c696e75780000000000000022d7c2029f8624495f0fba0dee945417a6f2dbf97cbe9ce469336374ca029762347c287bc96a5f74c71db9ce95cb7e9206d216ad8ebc5833b67dac6bd130b4d5d291f40f14c8fe920a568bf0c38473b8134eed959e66d08d5335912157ea13288cecd6a02eca7d5d9032500b98a32ae773615f675252bdb6f449d9790a4ba4bcd34878cbacf64a6c3d121d17fc2c912601",
  gasLimit: 8000000,
  gasUsed: 0,
  hash: "0x9c302aa99fecc4314d1c24b92bd822e79029902497d0b4418cf2b40803863832",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 14250000,
  parentHash: "0xca9302e806e99462597f05c04b80080d7c00b95afab483e0a96e0de59c83c226",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 689,
  stateRoot: "0x521f89076eca3178ac89dd3e4fd42607c142d121da4da303272c52038bcc58e8",
  timestamp: 1551102491,
  totalDifficulty: 28462898,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
> clique.getSnapshotAtHash('0x9c302aa99fecc4314d1c24b92bd822e79029902497d0b4418cf2b40803863832')
{
  hash: "0x9c302aa99fecc4314d1c24b92bd822e79029902497d0b4418cf2b40803863832",
  number: 14250000,
  recents: {},
  signers: {
    0x22d7c2029f8624495f0fba0dee945417a6f2dbf9: {},
    0x7cbe9ce469336374ca029762347c287bc96a5f74: {},
    0xc71db9ce95cb7e9206d216ad8ebc5833b67dac6b: {},
    0xd130b4d5d291f40f14c8fe920a568bf0c38473b8: {}
  },
  tally: {},
  votes: null
}

Why a clique block will do not have snapshot recent. How this case would be happened?

This case cause other synced node has synced issue.

**Comment by karalabe** [comment] 2019-07-18 12:34
The 1.8.15 release is pretty old (almost a year). Could you please try syncing a 1.9.0 release and tell us if you still see it exhibit this behavior?

**Comment by gtrandxiangyu** [comment] 2019-07-19 09:46
> The 1.8.15 release is pretty old (almost a year). Could you please try syncing a 1.9.0 release and tell us if you still see it exhibit this behavior?

have another synced block issue

DEBUG[07-19|09:21:29.004] Downloading transaction receipts         origin=17430001
DEBUG[07-19|09:21:29.004] Downloading block bodies                 origin=17430001
DEBUG[07-19|09:21:29.004] Directing header downloads               peer=94ab46362ee8d5bb origin=17430001
DEBUG[07-19|09:21:29.004] Fetching batch of headers                id=94ab46362ee8d5bb conn=staticdial count=128 fromnum=17430192 skip=191 reverse=false
DEBUG[07-19|09:21:29.011] Filling up skeleton                      from=17430001
DEBUG[07-19|09:21:29.111] Fetching batch of headers                id=94ab46362ee8d5bb conn=staticdial count=192 fromnum=17430001 skip=0   reverse=false
DEBUG[07-19|09:21:29.123] Fetching batch of headers                id=94ab46362ee8d5bb conn=staticdial count=192 fromnum=17430193 skip=0   reverse=false
DEBUG[07-19|09:21:29.127] Fetching batch of block bodies           id=94ab46362ee8d5bb conn=staticdial count=2
DEBUG[07-19|09:21:29.128] Inserting downloaded chain               items=106  firstnum=17430001 firsthash=5ce998…1e2a18 lastnum=17430106 lasthash=aedba9…9b8bb8
ERROR[07-19|09:21:29.129] 
########## BAD BLOCK #########
Chain config: {ChainID: 2018 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: clique}

Number: 17430001
Hash: 0x5ce99853632095b1acc73b7fc46e98b42cd1b7431c0ef090a0ae12e3a71e2a18


Error: unauthorized
##############################
 
DEBUG[07-19|09:21:29.129] Downloaded item processing failed        number=17430001 hash=5ce998…1e2a18 err=unauthorized
DEBUG[07-19|09:21:29.129] Skeleton fill terminated                 err="block header download canceled (requested)"
DEBUG[07-19|09:21:29.129] Skeleton chain invalid                   peer=94ab46362ee8d5bb err="block header download canceled (requested)"
DEBUG[07-19|09:21:29.129] Header download terminated               peer=94ab46362ee8d5bb
DEBUG[07-19|09:21:29.129] Transaction receipt download terminated  err="receipt download canceled (requested)"
DEBUG[07-19|09:21:29.129] Block body download terminated           err="block body download canceled (requested)"
DEBUG[07-19|09:21:29.129] Synchronisation terminated               elapsed=127.561352ms
WARN [07-19|09:21:29.130] Synchronisation failed, dropping peer    peer=94ab46362ee8d5bb err="retrieved hash chain is invalid"
DEBUG[07-19|09:21:29.130] Removing Ethereum peer                   peer=94ab46362ee8d5bb
DEBUG[07-19|09:21:29.130] Ethereum message handling failed         id=94ab46362ee8d5bb conn=staticdial err=EOF
DEBUG[07-19|09:21:29.130] Removing p2p peer                        id=94ab46362ee8d5bb conn=staticdial duration=5.666s       peers=0 req=false err="useless peer"
DEBUG[07-19|09:21:31.268] Recalculated downloader QoS values       rtt=18.586029568s confidence=0.625 ttl=1m0s
DEBUG[07-19|09:21:33.212] Found seed node in database              id=0f171f815aebb0e0 addr=165.227.207.29:30303  age=1h29m9.212786442s

**Comment by gtrandxiangyu** [comment] 2019-07-19 09:48
> The 1.8.15 release is pretty old (almost a year). Could you please try syncing a 1.9.0 release and tell us if you still see it exhibit this behavior?

more block info.

> eth.getBlock(17429999)
{
  difficulty: 2,
  extraData: "0xd88301080f846765746888676f312e31302e32856c696e75780000000000000083fe3d8196d49ab85c3f4890e1bd94f46d840aecb6c0834aa3f34c78a8fe9bfb73da115a827e40ac7b76138d9220be74ecd2ba2c5dc4efce6da91a411d820ac500",
  gasLimit: 8000000,
  gasUsed: 0,
  hash: "0x3cbec852b06f4335141db704d3607e6b40232b6c9eea3f21d9fc071a706163be",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 17429999,
  parentHash: "0xd7cbc2421fbfe7867eba63bf4ae32c4b83f03a78024bca8133f86cff85e3863d",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 610,
  stateRoot: "0x3499c2fe1cdcc67fcd62dcff90d64107c7bf6ccd0c4683a2efb01a003d52d24d",
  timestamp: 1554830876,
  totalDifficulty: 34812933,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
> 
> 
> 
> 
> 
> 
> clique.getSnapshotAtHash("0x3cbec852b06f4335141db704d3607e6b40232b6c9eea3f21d9fc071a706163be")
{
  hash: "0x3cbec852b06f4335141db704d3607e6b40232b6c9eea3f21d9fc071a706163be",
  number: 17429999,
  recents: {
    17429997: "0x7cbe9ce469336374ca029762347c287bc96a5f74",
    17429998: "0xc71db9ce95cb7e9206d216ad8ebc5833b67dac6b",
    17429999: "0xd130b4d5d291f40f14c8fe920a568bf0c38473b8"
  },
  signers: {
    0x22d7c2029f8624495f0fba0dee945417a6f2dbf9: {},
    0x7cbe9ce469336374ca029762347c287bc96a5f74: {},
    0xc71db9ce95cb7e9206d216ad8ebc5833b67dac6b: {},
    0xd130b4d5d291f40f14c8fe920a568bf0c38473b8: {}
  },
  tally: {},
  votes: []
}
> 
> 
> eth.getBlock(17430000)
{
  difficulty: 1,
  extraData: "0xd88301080f846765746888676f312e31302e32856c696e75780000000000000022d7c2029f8624495f0fba0dee945417a6f2dbf97cbe9ce469336374ca029762347c287bc96a5f74c71db9ce95cb7e9206d216ad8ebc5833b67dac6bd130b4d5d291f40f14c8fe920a568bf0c38473b8fa70e8b7b23741499aabe4d40859cde6f108e052c8a871fa5d40777020c0ef995e5dbec85163f85b558d928fb39ea46b48b5d4824ea8aaecc228c0147739f58000",
  gasLimit: 8000000,
  gasUsed: 0,
  hash: "0x6814d86919fefac5dc094258e4282ff2eccc63950d5165981a7dd06df9472b1b",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 17430000,
  parentHash: "0x3cbec852b06f4335141db704d3607e6b40232b6c9eea3f21d9fc071a706163be",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 690,
  stateRoot: "0x3499c2fe1cdcc67fcd62dcff90d64107c7bf6ccd0c4683a2efb01a003d52d24d",
  timestamp: 1554830877,
  totalDifficulty: 34812934,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
> 
> 
> clique.getSnapshotAtHash("0x6814d86919fefac5dc094258e4282ff2eccc63950d5165981a7dd06df9472b1b")
{
  hash: "0x6814d86919fefac5dc094258e4282ff2eccc63950d5165981a7dd06df9472b1b",
  number: 17430000,
  recents: {},
  signers: {
    0x22d7c2029f8624495f0fba0dee945417a6f2dbf9: {},
    0x7cbe9ce469336374ca029762347c287bc96a5f74: {},
    0xc71db9ce95cb7e9206d216ad8ebc5833b67dac6b: {},
    0xd130b4d5d291f40f14c8fe920a568bf0c38473b8: {}
  },
  tally: {},
  votes: null
}
> 
> 
> eth.getBlock(17430001)
{
  difficulty: 2,
  extraData: "0xd88301080f846765746888676f312e31302e32856c696e757800000000000000448ace0ae7bae8bacc5461b28d89e84f38e82b4c48df06d86fd7fde47531b6be68e4c7ab3ebf79e657cd306a03656e7048ae88a4b5cb52da806812be6830db9401",
  gasLimit: 8000000,
  gasUsed: 0,
  hash: "0x5ce99853632095b1acc73b7fc46e98b42cd1b7431c0ef090a0ae12e3a71e2a18",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 17430001,
  parentHash: "0x6814d86919fefac5dc094258e4282ff2eccc63950d5165981a7dd06df9472b1b",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 610,
  stateRoot: "0x3499c2fe1cdcc67fcd62dcff90d64107c7bf6ccd0c4683a2efb01a003d52d24d",
  timestamp: 1554830878,
  totalDifficulty: 34812936,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
> clique.getSnapshotAtHash("0x5ce99853632095b1acc73b7fc46e98b42cd1b7431c0ef090a0ae12e3a71e2a18")
{
  hash: "0x5ce99853632095b1acc73b7fc46e98b42cd1b7431c0ef090a0ae12e3a71e2a18",
  number: 17430001,
  recents: {
    17430001: "0x7cbe9ce469336374ca029762347c287bc96a5f74"
  },
  signers: {
    0x22d7c2029f8624495f0fba0dee945417a6f2dbf9: {},
    0x7cbe9ce469336374ca029762347c287bc96a5f74: {},
    0xc71db9ce95cb7e9206d216ad8ebc5833b67dac6b: {},
    0xd130b4d5d291f40f14c8fe920a568bf0c38473b8: {}
  },
  tally: {},
  votes: []
}

**Comment by fjl** [comment] 2019-08-20 08:41
We believe this is fixed in geth v1.8.16

**Closed by fjl** 2019-08-20 08:41 UTC
Labels: area:clique, need:check-with-current-version, status:triage

**Comment by holiman** [comment] 2019-08-20 08:45
More info about the cause behind this bug is availalbe in the fix here: https://github.com/ethereum/go-ethereum/pull/17620

**Comment by fjl** [comment] 2019-08-20 08:45
Fix in https://github.com/ethereum/go-ethereum/pull/17620
