### ISSUE TITLE
Geth unresponsive when "Persisted trie from memory database"

### ISSUE THREAD

**Issue by xanatos** [ethereum/go-ethereum#27262] opened 2023-05-14 07:13 UTC
I'm using Geth (v1.11.6) on Windows 11 Pro, with an Intel 10710u, 32gb of memory and a Kingston NV2 2TB M.2

Geth becomes unresponsive when it does the "Persisted trie from memory database"

    INFO [05-13|19:43:03.827] Chain head was updated                   number=17,252,604 hash=12ea30..517aef root=8546e1..a2d395 elapsed=56.3199ms
    INFO [05-13|19:43:28.564] Persisted trie from memory database      nodes=1,818,226 size=499.94MiB time=14.6651421s gcnodes=5,189,566 gcsize=1.99GiB gctime=17.3776921s livenodes=453,793 livesize=163.49MiB

and Lighthouse

    May 13 17:43:20.001 WARN Did not advance head state              reason: Err(HeadMissingFromSnapshotCache(0xb8cb201075d99f26fa95e12596977c087ed917eee01efa5f0c7ba1c5fad16f42)), service: state_advance
    May 13 17:43:21.791 WARN Execution engine call failed            error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }), service: exec
    May 13 17:43:21.791 WARN Error whilst processing payload status  error: Api { error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }) }, service: exec

This caused a lost attestation.

**Comment by karalabe** [comment] 2023-05-15 05:39
Hmm, yes, every now and again Geth does a massive store operation to entirely flush a trie to disk. While that is happening, pretty much everything's on hold. Unfortunately not a bug, rather it's how it works.

That said, soon we'll have the new trie model merged in and that should be a lot more capable and stable. Until then you'll have to bear with us.

**Closed by karalabe** 2023-05-15 05:39 UTC
Labels: type:bug

**Comment by phqb** [comment] 2024-08-22 09:44
@xanatos You can use [`debug_setTrieFlushInterval` method](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugsettrieflushinterval) with a duration parameter like this
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "debug_setTrieFlushInterval",
  "params": ["30s"]
}
```
to make `geth` "Persisted trie from memory database" more often with less data. Currently the default interval is `60m` which takes more or less a day to reach (see why in the document link). I found `30s` works well in my node. 

Note that every time you restart the node, you have to set the interval again.

@karalabe I think we should introduce a `--cache.trietimeout` flag or something to set [this config](https://github.com/ethereum/go-ethereum/blob/ab48ba42f4f34873d65fd1737fabac5c680baff6/eth/ethconfig/config.go#L124) which sets the flush interval when starting the node.
