### ISSUE TITLE
Make get error 2: installation on raspberry pi

### ISSUE THREAD

**Issue by tuytuy** [ethereum/go-ethereum#3643] opened 2017-02-03 22:27 UTC
#### System information

Geth version: don't have one yet !
OS & Version: Raspbian

#### Expected behaviour
Full installation of geth when the command is run
$ sudo make geth

#### Actual behaviour
This error:
build/env.sh go install -v -ldflags '-X main.gitCommit c541b38fb36587d23c60f5e2f2b9b3c8700ec489' ./cmd/geth
github.com/ethereum/go-ethereum/core/types
github.com/ethereum/go-ethereum/core/types
build/_workspace/src/github.com/ethereum/go-ethereum/core/types/transaction.go:39: undefined: atomic.Value
build/_workspace/src/github.com/ethereum/go-ethereum/core/types/transaction.go:40: undefined: atomic.Value
build/_workspace/src/github.com/ethereum/go-ethereum/core/types/transaction.go:41: undefined: atomic.Value
Makefile:17: recipe for target 'geth' failed
make: *** [geth] Error 2

#### Step to reproduce
Followed the exact steps of this tutorial on a raspberry pie 2
http://raspnode.com/diyEthereumGeth.html

**Comment by ubunteroz** [comment] 2017-02-05 16:16
Compiled successfully on my Raspberry Pi Model B+ using Raspbian Stretch and latest Go (from repository). Make sure that you have upgraded to latest Raspbian (testing) version, so you can install latest Go compiler.

IMO, you doesn't need `sudo` to compile Geth.

**Comment by bas-vk** [comment] 2017-02-06 17:06
Probably you are using a too old go version, `atomic.Value` was added in go 1.4.

As mentioned, normally you should not compile code with sudo. In this case it might be the cause if you have an old go installation lingering that your super users has in its path.

**Comment by obscuren** [comment] 2017-02-07 08:09
Closing this issue as it can be easily resolved using an up to date installation of the Go compiler.

**Closed by obscuren** 2017-02-07 08:09 UTC
