### ISSUE TITLE
Geth 1.4.18 Bad Block 1,837,907 on Testnet

### ISSUE THREAD

**Issue by k00ka** [ethereum/go-ethereum#3246] opened 2016-11-10 18:27 UTC
#### System information
Geth
Version: 1.4.18-stable-c72f5459
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: darwin
GOPATH=/Users/david/projects/go:/Users/david/projects/ether
GOROOT=/usr/local/Cellar/go/1.7.3/libexec

#### Expected behaviour
Geth should finish syncing blocks. 

#### Actual behaviour
Geth gets hung up on block 1,837,907.

#### Steps to reproduce the behaviour
1. Download and install Geth 1.4.18
2. Remove existing chain data (testate)
3. Run "geth --testnet --fast --cache=1024 --jitvm console"

**Comment by bas-vk** [comment] 2016-11-11 00:09
Could you post the relevant part of log? Logs around the "bad block" message.

**Comment by karalabe** [comment] 2016-11-11 12:53
Some people are pushing the non forked version of the testnet faster than the fork is going. This causes Geth to fast sync to the other chain, then fail since it's bad. We didn't implement fast sync fork protection into these hard forks because there was no incentive to keep the other chain alive. We didn't really think about the testnet being pushed by people who just don't care. Please use develop (it has added logic) to work around this.

**Comment by k00ka** [comment] 2016-11-16 22:36
@karalabe: Using develop (HEAD) fixed the issue on testnet.

**Comment by ropod7** [comment] 2016-11-17 20:18
geth update and resync helps, now everything good. Very fast resync. Real network is stable after both latest updates. )

**Comment by karalabe** [comment] 2016-11-22 08:52
I'm closing this issue as the cause was a a bad morden chain being pushed by someone who didn't care about the ecosystem. Hopefully the new testnet will behave correctly for a long while before anyone gets ideas :P

**Closed by karalabe** 2016-11-22 08:52 UTC
