### ISSUE TITLE
memory leak ,HeapIdle memory how to return to OS

### ISSUE THREAD

**Issue by friends110110** [ethereum/go-ethereum#19062] opened 2019-02-14 08:09 UTC
@karalabe geth 1.8.15 , 
console mode  debug.memStats() could help me get memory status as following. I notice **"HeapIdle:3367976960"** about 3.3G ,and geth do not return to the OS. So when I use linux command **"top"**, the geth program occupy 5G+ memory. 
So geth program often out of memory or killed by os likes logs **kernel: geth invoked oom-killer** . When use debug.freeOSMemory() it will release the idle memory to OS, after a while, it raise fast.

**So how to makes heapIdle memory how to return to OS?
And is there something introduction about memory leak in geth version 1.8.15 ?**

start script:

```
nohup $BIN_PATH/geth --datadir "$DEPLOY_PATH" \
--nodekey "$DEPLOY_PATH/nodekeys/nodekey" \
--ethash.dagdir "$DEPLOY_PATH"/ethash \
--port $port --rpc --rpcaddr $LOCAL_IP --rpcport $rpc_port --rpccorsdomain "*" \
--pprof --pprofaddr $LOCAL_IP --pprofport $ppof_port \
--rpcapi eth,personal,net,admin \
--nodiscover --syncmode "full" \
--txpool.globalslots 16000  --memprofilerate 600 \
--mine --minerthreads 1 --miner.etherbase $miner_account --gasprice 1 --extradata "0x" \
--metrics --metrics.influxdb --metrics.influxdb.endpoint http://10.xx.xx.xx:8086 --metrics.influxdb.database collectd --metrics.influxdb.host.tag 11 \
--vmdebug --verbosity 3 >> $DEPLOY_PATH/logs/chain.log 2>&1 & echo $! > $DEPLOY_PATH/logs/pid.log
```

> debug.memStats()
{
  Alloc: 1595232344,
  BuckHashSys: 16016695,
  BySize: [{
      Frees: 0,
      Mallocs: 0,
      Size: 0
  }, {
      Frees: 146250639,
      Mallocs: 146276218,
      Size: 8
  }, {
      Frees: 7852122725,
      Mallocs: 7856082539,
      Size: 16
  }, {
      Frees: 15361431248,
      Mallocs: 15365397264,
      Size: 32
  }, {
      Frees: 3780300187,
      Mallocs: 3781188475,
      Size: 48
  }, {
      Frees: 358291486,
      Mallocs: 358720665,
      Size: 64
  }, {
      Frees: 4938388963,
      Mallocs: 4938738359,
      Size: 80
  }, {
      Frees: 464037562,
      Mallocs: 464092765,
      Size: 96
  }, {
      Frees: 1143825090,
      Mallocs: 1143881555,
      Size: 112
  }, {
      Frees: 195879966,
      Mallocs: 196112765,
      Size: 128
  }, {
      Frees: 185554858,
      Mallocs: 185870054,
      Size: 144
  }, {
      Frees: 126303757,
      Mallocs: 126308080,
      Size: 160
  }, {
      Frees: 483546,
      Mallocs: 483613,
      Size: 176
  }, {
      Frees: 220519,
      Mallocs: 220589,
      Size: 192
  }, {
      Frees: 57486869,
      Mallocs: 57495150,
      Size: 208
  }, {
      Frees: 4709763,
      Mallocs: 4710323,
      Size: 224
  }, {
      Frees: 110179567,
      Mallocs: 110193368,
      Size: 240
  }, {
      Frees: 15391568,
      Mallocs: 15392556,
      Size: 256
  }, {
      Frees: 287685104,
      Mallocs: 287722584,
      Size: 288
  }, {
      Frees: 6574806835,
      Mallocs: 6575238320,
      Size: 320
  }, {
      Frees: 11898948,
      Mallocs: 11904595,
      Size: 352
  }, {
      Frees: 204964411,
      Mallocs: 205014527,
      Size: 384
  }, {
      Frees: 93594,
      Mallocs: 93636,
      Size: 416
  }, {
      Frees: 644041240,
      Mallocs: 644073946,
      Size: 448
  }, {
      Frees: 7808787,
      Mallocs: 7809737,
      Size: 480
  }, {
      Frees: 41845346,
      Mallocs: 41848505,
      Size: 512
  }, {
      Frees: 4448043,
      Mallocs: 4449421,
      Size: 576
  }, {
      Frees: 32469,
      Mallocs: 32507,
      Size: 640
  }, {
      Frees: 49016,
      Mallocs: 49037,
      Size: 704
  }, {
      Frees: 94417,
      Mallocs: 94428,
      Size: 768
  }, {
      Frees: 753664,
      Mallocs: 753712,
      Size: 896
  }, {
      Frees: 181676,
      Mallocs: 181724,
      Size: 1024
  }, {
      Frees: 142606,
      Mallocs: 142634,
      Size: 1152
  }, {
      Frees: 748132,
      Mallocs: 748169,
      Size: 1280
  }, {
      Frees: 42893,
      Mallocs: 42918,
      Size: 1408
  }, {
      Frees: 14926275,
      Mallocs: 14926293,
      Size: 1536
  }, {
      Frees: 106818,
      Mallocs: 106861,
      Size: 1792
  }, {
      Frees: 1004444,
      Mallocs: 1008482,
      Size: 2048
  }, {
      Frees: 33658,
      Mallocs: 33673,
      Size: 2304
  }, {
      Frees: 97263,
      Mallocs: 97316,
      Size: 2688
  }, {
      Frees: 42834,
      Mallocs: 42908,
      Size: 3072
  }, {
      Frees: 23665,
      Mallocs: 23668,
      Size: 3200
  }, {
      Frees: 77850,
      Mallocs: 77852,
      Size: 3456
  }, {
      Frees: 410778,
      Mallocs: 411221,
      Size: 4096
  }, {
      Frees: 33521,
      Mallocs: 33543,
      Size: 4864
  }, {
      Frees: 37863,
      Mallocs: 37891,
      Size: 5376
  }, {
      Frees: 59564,
      Mallocs: 59585,
      Size: 6144
  }, {
      Frees: 4972,
      Mallocs: 4976,
      Size: 6528
  }, {
      Frees: 5185,
      Mallocs: 5187,
      Size: 6784
  }, {
      Frees: 1489,
      Mallocs: 1489,
      Size: 6912
  }, {
      Frees: 228211,
      Mallocs: 228289,
      Size: 8192
  }, {
      Frees: 94301,
      Mallocs: 94325,
      Size: 9472
  }, {
      Frees: 4148,
      Mallocs: 4150,
      Size: 9728
  }, {
      Frees: 32470,
      Mallocs: 32474,
      Size: 10240
  }, {
      Frees: 207688655,
      Mallocs: 207716794,
      Size: 10880
  }, {
      Frees: 155195,
      Mallocs: 155215,
      Size: 12288
  }, {
      Frees: 77548,
      Mallocs: 77559,
      Size: 13568
  }, {
      Frees: 37664,
      Mallocs: 37674,
      Size: 14336
  }, {
      Frees: 159368,
      Mallocs: 165989,
      Size: 16384
  }, {
      Frees: 82297,
      Mallocs: 82332,
      Size: 18432
  }, {
      Frees: 3683,
      Mallocs: 3688,
      Size: 19072
  }],
  DebugGC: false,
  EnableGC: true,
  Frees: 48714786677,
  GCCPUFraction: 0.023186902958021248,
  GCSys: 188620800,
  HeapAlloc: 1595232344,
  HeapIdle: 3367976960,
  HeapInuse: 1744453632,
  HeapObjects: 10910658,
  HeapReleased: 1887764480,
  HeapSys: 5112430592,
  LastGC: 1550129501266508800,
  Lookups: 5414330,
  MCacheInuse: 6944,
  MCacheSys: 16384,
  MSpanInuse: 17804672,
  MSpanSys: 47087616,
  Mallocs: 48725697335,
  NextGC: 2054922816,
  NumForcedGC: 0,
  NumGC: 7627,
  OtherSys: 96916801,
  PauseEnd: [1550126791336219100, 1550126802423986400, 1550126821081402600, 1550126831841516000, 1550126843946224600, 1550126859329531100, 1550126871541474300, 1550126883050951000, 1550126901639037000, 1550126912677188000, 1550126924847978800, 1550126941801328600, 1550126951467522800, 1550126962720018200, 1550126981336917800, 1550126992091753500, 1550127004346886400, 1550127021728237800, 1550127032421527000, 1550127041784974000, 1550127053841449200, 1550127071574388000, 1550127083043949800, 1550127101335769000, 1550127112647241700, 1550127124239582700, 1550127132535336000, 1550127151636564700, 1550127162288493000, 1550127181129604000, 1550127191989870600, 1550127204334304300, 1550127219295404000, 1550127231029206800, 1550127242252898600, 1550127256507725600, 1550127271808910300, 1550127283273493500, 1550127301478534100, 1550127309455229000, 1550127321946989000, 1550127335529781800, 1550127351804868400, 1550127363135657200, 1550127381510439000, 1550127392415990500, 1550127402106797800, 1550127414556649200, 1550127431933295600, 1550127443439044400, 1550127461443985700, 1550127472615389000, 1550127489279885600, 1550127492786094000, 1550127511526918400, 1550127522824879600, 1550127541746956300, 1550127552429186600, 1550127565094086700, 1550127579328338700, 1550127591276189200, 1550127602863256600, 1550127621282423600, 1550127632275284500, 1550127645325909500, 1550127661579257900, 1550127669535542500, 1550127682046539000, 1550127701112288800, 1550127712222873000, 1550127728058646300, 1550127741979396900, 1550127752624637200, 1550127761944480500, 1550127774264458800, 1550127791867499500, 1550127804071413500, 1550127821678387700, 1550127833409525000, 1550127849320111000, 1550127853300988200, 1550127872000345600, 1550127883311867100, 1550127901648307500, 1550127912701258000, 1550127926789002200, 1550127939391020000, 1550127951472301000, 1550127963199203600, 1550127981516044000, 1550127992666491000, 1550128011193173500, 1550128022168403000, 1550128031765678800, 1550128043731929900, 1550128061515599000, 1550128072812794000, 1550128091275381800, 1550128102326979300, 1550128114153663200, 1550128123783237400, 1550128141891593000, 1550128153145321500, 1550128171689742000, 1550128182596852200, 1550128197559336000, 1550128209386545400, 1550128221994206700, 1550128234106753000, 1550128251974972700, 1550128263650389800, 1550128281500066000, 1550128292204594700, 1550128301461100800, 1550128312785694200, 1550128331611295700, 1550128342803694600, 1550128361299393300, 1550128372484035600, 1550128383757933000, 1550128392334657300, 1550128411467583000, 1550128422354315300, 1550128441224207600, 1550128452202707200, 1550128465314609200, 1550128479298360600, 1550128490994264000, 1550128502332396500, 1550128521101412400, 1550128532190143000, 1550128544102517500, 1550128561457638000, 1550128569430670300, 1550128582107447600, 1550128598416415700, 1550128611881098500, 1550128623904391000, 1550128641678470000, 1550128652293676500, 1550128661584258000, 1550128673118487600, 1550128691572769000, 1550128703184408600, 1550128721467789300, 1550128732532787500, 1550128746313925400, 1550128753642201900, 1550128771739798300, 1550128783015453700, 1550128801606839600, 1550128812526279400, 1550128825824825900, 1550128839365231400, 1550128851919132700, 1550128863380437000, 1550128881644400600, 1550128893121145300, 1550128911423086600, 1550128922177583600, 1550128931373104400, 1550128943120620800, 1550128961647902700, 1550128973142074600, 1550128991412289300, 1550129002506834000, 1550129014053142000, 1550129022553741000, 1550129041780659200, 1550129053147914200, 1550129071655302700, 1550129082708795100, 1550129098626866200, 1550129109349273000, 1550129121610764800, 1550129133418951200, 1550129151693834000, 1550129163371817200, 1550129181524790300, 1550129192148755200, 1550129201370596600, 1550129212722807600, 1550129231417374700, 1550129242563881200, 1550129261178602200, 1550129272265624800, 1550129283363183800, 1550129292266855700, 1550129311342150100, 1550129322310775800, 1550129341266335500, 1550129352118612500, 1550129364658305800, 1550129379381945300, 1550129391709500700, 1550129403064111600, 1550129421475946500, 1550129432829328000, 1550129451399349500, 1550129462293334800, 1550129471252559600, 1550129482372525600, 1550129501266508800, 1550126072689367300, 1550126091571623400, 1550126103307578400, 1550126121558556700, 1550126133233136600, 1550126151291346000, 1550126162353111600, 1550126174187356200, 1550126191911505000, 1550126203371863300, 1550126221463590700, 1550126229456318500, 1550126241898010000, 1550126254201014300, 1550126272025440000, 1550126283773462000, 1550126301547909400, 1550126312656754400, 1550126322112099300, 1550126335018888000, 1550126351586409200, 1550126363320520000, 1550126381380419000, 1550126392791182300, 1550126406100669700, 1550126412490587100, 1550126431320933600, 1550126442509640000, 1550126461307922000, 1550126472145223700, 1550126484548259300, 1550126499318610400, 1550126511026259500, 1550126522160971000, 1550126534480597800, 1550126551849811000, 1550126563232268000, 1550126581316602000, 1550126589418107000, 1550126601994013400, 1550126614111815400, 1550126631878422000, 1550126643342415000, 1550126661541519600, 1550126672425935000, 1550126681494356000, 1550126693302251300, 1550126711465554200, 1550126722611375600, 1550126741212289500, 1550126752575364000, 1550126763942037800, 1550126772379957200],
  PauseNs: [430387, 216141, 219613, 241430, 1196200, 290899, 189981, 174267, 296176, 277445, 226581, 148926, 250822, 190412, 222826, 194226, 195236, 193752, 162409, 263591, 166977, 171419, 332683, 176570, 250197, 165249, 168529, 189996, 141898, 194472, 180005, 4407046, 317546, 178252, 189594, 234506, 404598, 161945, 197363, 2601418, 293847, 140896, 161492, 225388, 1025137, 269837, 183659, 268270, 6400823, 177739, 224384, 202556, 391142, 206103, 224622, 147309, 154437, 293118, 236928, 250869, 147610, 259392, 157349, 359173, 275337, 170889, 4117145, 260348, 257666, 299620, 186092, 203862, 201783, 209878, 170117, 165554, 245734, 143581, 265785, 253498, 264477, 148313, 197389, 205892, 389975, 279921, 1147278, 188097, 218213, 203300, 261024, 162105, 207960, 237749, 309359, 184545, 131855, 313724, 165265, 232727, 230290, 209478, 222419, 288259, 164595, 956306, 1372278, 205844, 185533, 306677, 174540, 171880, 171719, 291944, 242757, 233953, 209924, 287593, 207604, 157147, 166676, 205859, 149615, 440549, 176506, 221976, 214193, 263426, 293852, 164022, 281007, 165077, 217992, 538611, 184155, 297221, 173634, 201526, 172502, 190709, 258704, 148129, 277977, 248790, 226151, 301587, 217119, 1060462, 238845, 300469, 189348, 232858, 254955, 205892, 169573, 165941, 138115, 194835, 242070, 216698, 175519, 228353, 177625, 394430, 154655, 169141, 268015, 212787, 179384, 192356, 137699, 262097, 292088, 230269, 257307, 264028, 353711, 175504, 229475, 193911, 124296, 217556, 207859, 149740, 207153, 292062, 194086, 225080, 279073, 209638, 165443, 206438, 427794, 499241, 232061, 281362, 213535, 152756, 165251, 265196, 207643, 140396, 181581, 238804, 218577, 187454, 213512, 167684, 210722, 299848, 209898, 187606, 358162, 248163, 4057255, 204099, 181912, 210699, 175865, 162552, 243111, 326918, 263962, 509902, 272654, 166392, 193675, 471312, 203452, 261433, 229507, 330906, 146236, 204535, 226076, 149824, 254441, 420232, 318556, 177406, 186138, 2972110, 232783, 194667, 276709, 223397, 213288, 207579, 215957, 224179, 174801, 171128, 207668, 235698, 202226, 192604],
  PauseTotalNs: 7290141109,
  StackInuse: 5406720,
  StackSys: 5406720,
  Sys: 5466495608,
  TotalAlloc: 6913671475392
}

**Comment by karalabe** [comment] 2019-02-18 12:01
You need to tell us a bit more about your setup. I'm seeing you're CPU mining, which might take a bit of resources. You've also raised the tx pool limits from the defaults, why? How much memory does your machine have? What block limits are you running with. Is your RPC post accessible to the public?

There are lots of reasons that might cause Geth to use more memory than needed. Please answer the above questions so we might figure it out.

**Comment by friends110110** [comment] 2019-02-19 07:36
1.You've also raised the tx pool limits from the defaults, why? 
For received more txs, do some performance test.
How much memory does your machine have? 
8G, and the geth take up 5G+.
What block limits are you running with. Is your RPC post accessible to the public?
RPC does not post to the public.

**Comment by AyushyaChitransh** [comment] 2019-04-30 10:11
@friends110110 Is this a possible duplicate of #19192

**Comment by holiman** [comment] 2019-06-25 09:03
This ticket seems abandoned, no new information came after Peter requested it

**Closed by holiman** 2019-06-25 09:03 UTC
