### ISSUE TITLE
miner.hashrate undefined

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#2591] opened 2016-05-21 16:55 UTC
https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#minerhashrate

Looks like its moved to web3.eth.hashrate on geth 1.4.3

**Comment by bas-vk** [comment] 2016-05-25 09:58
This was removed since it was a duplicate of `eth.hashrate` which is part of the official API.
This for reporting this, page has been updated.

**Closed by bas-vk** 2016-05-25 09:58 UTC
Labels: docs

**Comment by advectus** [comment] 2016-10-26 18:56
@bas-vk @aakilfernandes I've updated the master branch of a new go-ethereum-wiki repo that I've created where there was mention of this deprecated miner.hashrate property. Maybe go-ethereum deserves it's own wiki repo - or if these doc contributions are handled another way, please let me know.

**Comment by roolo** [comment] 2017-02-10 13:57
It is still here https://github.com/ethereum/go-ethereum/wiki/Mining
