### ISSUE TITLE
Bad block #446189 ... gas used error... Synchronisation failed: peer is unknown or unhealthy

### ISSUE THREAD

**Issue by MercStills** [ethereum/go-ethereum#1117] opened 2015-05-27 04:37 UTC
Using geth v0.9.25 (f5ce848cfe) on Ubuntu 14.04 LTS

Still unable to fully download blockchain and sync with peers since time of fork.  Stalls with download and gives bad block message.  Log below:

00:17:03.960978   12789 backend.go:256] Protocol Version: 60, Network Id: 0
I0527 00:17:03.961088   12789 backend.go:266] Blockchain DB Version: 3
I0527 00:17:03.962667   12789 chain_manager.go:257] Last block (#448512) b1736aa69cf3351f23b3ad5498f4ef5cb5029e7e31e17ba30f9b5082c1fed6a5 TD=940678707671302
I0527 00:17:04.783980   12789 cmd.go:137] Starting Geth/v0.9.25-f5ce848c/linux/go1.4.2
I0527 00:17:04.784245   12789 server.go:293] Starting Server
I0527 00:17:05.897558   12789 nat.go:95] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1
I0527 00:17:06.027014   12789 udp.go:189] Listening, enode://304de4f120325128ef8b2f1b440d0bd49c2597fd2c3065d0d3e6cb99173d717319e5cafdcc25256e80b7942f50ba3503e8a2887b30308f9ade80c8924f59b227@24.90.50.88:30303
I0527 00:17:06.027157   12789 backend.go:477] Server started
I0527 00:17:06.027223   12789 server.go:530] Listening on [::]:30303
I0527 00:17:06.095165   12789 nat.go:95] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-IP1
I0527 00:17:17.649885   12789 downloader.go:159] Block synchronisation started
I0527 00:17:30.052353   12789 worker.go:403] transaction(265f34bf) below gas price (tx=10 Shannon ask=10 Szabo). All sequential txs from this address(a8da6124) will be ignored
I0527 00:17:30.053012   12789 worker.go:403] transaction(94f43363) below gas price (tx=10 Shannon ask=10 Szabo). All sequential txs from this address(a8da6124) will be ignored
I0527 00:17:31.595356   12789 chain_manager.go:753] Bad block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0527 00:17:31.595534   12789 chain_manager.go:754] gas used error (44532 / 160116)
I0527 00:17:53.113002   12789 chain_manager.go:753] Bad block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0527 00:17:53.113062   12789 chain_manager.go:754] gas used error (44532 / 160116)
I0527 00:17:53.151068   12789 sync.go:121] Synchronisation failed: no peers available or all peers tried for block download process
I0527 00:19:41.509636   12789 sync.go:121] Synchronisation failed: peer is unknown or unhealthy
I0527 00:21:38.841704   12789 sync.go:121] Synchronisation failed: peer is unknown or unhealthy
I0527 00:22:08.841435   12789 downloader.go:141] Unregister failed: peer is not registered
I0527 00:22:08.841498   12789 handler.go:102] Removal failed: peer is not registered
I0527 00:22:57.335557   12789 downloader.go:141] Unregister failed: peer is not registered
I0527 00:22:57.335663   12789 handler.go:102] Removal failed: peer is not registered
I0527 00:25:35.545802   12789 chain_manager.go:753] Bad block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0527 00:25:35.545844   12789 chain_manager.go:754] gas used error (44532 / 160116)
I0527 00:25:35.654951   12789 sync.go:121] Synchronisation failed: block downloading cancelled (requested)

**Comment by karalabe** [comment] 2015-05-27 13:28
Although you should eventually be able to sync up, it could happen that you managed to connect to a lot of bad peers and those keep on going. I'm working on a fix to really drop bad peers, not just ignore them. IMHO that should solve this issue or at least significantly reduce the probability of this happening. Will ping you when it's ready.

**Comment by sontol** [comment] 2015-05-27 16:48
I wonder if this is related to the latest p2p dialer?

https://github.com/ethereum/go-ethereum/pull/1014

Seems like the network doesn't have consensus on the longest chain because at some point it stops downloading.

**Comment by karalabe** [comment] 2015-05-29 14:00
This should be fixed in the latest release. There was a disconnect bug that caused it, but we also had to implement some faster peer-dropping policy as there were so many bad peers in the network that those kept shadowing the valid ones. If this still persist by all means reopen, but it shouldn't :)

**Closed by karalabe** 2015-05-29 14:00 UTC

**Comment by ropod7** [comment] 2016-10-16 07:15
Same issue after 1,5 years:
E1016 10:13:25.094169 core/blockchain.go:1170] Bad block #2446183 (0x7a7499dd032df75ab05b942f1b460caa4282121decb2c1e6816668a395ca5b14)
E1016 10:13:25.094222 core/blockchain.go:1171]     gas used error (487080 / 486440)

Geth version is 1.14.18. Blockchain resync started with new release yesterday.

**Comment by 5chdn** [comment] 2016-10-18 11:44
> Geth version is 1.14.18. Blockchain resync started with new release yesterday.

Can reproduce this issue. @karalabe is it possible this was introduced with the EIP 150 fork pull request?

    1018 13:40:57.726646 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:40:59.022870 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:40:59.022889 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:41:01.795264 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
    1018 13:41:03.720926 eth/downloader/downloader.go:298] Synchronisation failed: state data download canceled (requested)
    1018 13:41:08.184917 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:41:08.184941 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:41:08.810956 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:41:18.377259 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:41:18.388097 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:41:20.137237 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:41:23.064424 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:41:28.865594 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
    1018 13:41:37.402925 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:41:37.402940 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:41:41.499420 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:41:41.499443 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:41:43.544543 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:41:48.236115 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
    1018 13:41:58.495638 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:42:02.167629 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:42:09.965485 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:42:09.965498 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:42:16.861561 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:42:16.861585 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:42:20.852566 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:42:28.500303 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
    1018 13:42:31.687554 eth/downloader/downloader.go:298] Synchronisation failed: state data download canceled (requested)
    1018 13:42:32.909598 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:42:36.956662 eth/downloader/downloader.go:298] Synchronisation failed: block body download canceled (requested)
    1018 13:42:38.342605 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:42:48.133377 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:42:59.400290 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:42:59.400305 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:43:00.964555 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
    1018 13:43:08.495097 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:43:10.887099 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:43:10.887114 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:43:13.006573 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
    1018 13:43:20.093865 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:43:20.093884 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:43:21.150458 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
    1018 13:43:21.150476 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
    1018 13:43:21.293969 eth/downloader/downloader.go:611] Peer aab61610f7040ffa [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 1.662819516s]: head header set (item 0) broke chain ordering: requested 1422137, got 1427898
    1018 13:43:22.436043 eth/downloader/downloader.go:298] Synchronisation failed: receipt download canceled (requested)
    CI1018 13:43:26.001649 cmd/utils/cmd.go:81] Got interrupt, shutting down...
    1018 13:43:26.001693 core/blockchain.go:578] Chain manager stopped
    1018 13:43:26.001703 eth/handler.go:225] Stopping ethereum protocol handler...
    1018 13:43:26.001814 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
    1018 13:43:27.045622 eth/handler.go:246] Ethereum protocol handler stopped
    1018 13:43:27.045662 core/tx_pool.go:172] Transaction pool stopped
    1018 13:43:27.045681 eth/backend.go:500] Automatic pregeneration of ethash DAG OFF (ethash dir: /home/user/.ethash)
    1018 13:43:27.191571 ethdb/database.go:176] closed db:/home/user/.ethereum/chaindata
    1018 13:43:27.191632 ethdb/database.go:176] closed db:/home/user/.ethereum/dapp

**Comment by 5chdn** [comment] 2016-10-18 11:46
https://github.com/ethereum/go-ethereum/pull/3111

**Comment by stvenyin** [comment] 2017-10-20 09:37
hao do soluation this questions?
i'm also happen this
ubuntu 16..04 
NFO [10-20|17:36:09] Imported new state entries               count=1157 elapsed=3.474ms   processed=809294 pending=4103  retry=0   duplicate=152 unexpected=715
INFO [10-20|17:36:12] Imported new state entries               count=1162 elapsed=4.068ms   processed=810456 pending=4009  retry=287 duplicate=152 unexpected=715
INFO [10-20|17:36:14] Imported new block headers               count=1536 elapsed=302.208ms number=612621 hash=bbff5c…387a69 ignored=0
INFO [10-20|17:36:15] Imported new state entries               count=1164 elapsed=6.025ms   processed=811620 pending=3822  retry=0   duplicate=152 unexpected=715
INFO [10-20|17:36:15] Imported new block receipts              count=2048 elapsed=115.015ms bytes=1870087 number=609264 hash=9ef28b…2c4b51 ignored=0
INFO [10-20|17:36:15] Imported new block receipts              count=1822 elapsed=60.485ms  bytes=814168  number=611086 hash=1e3f73…0d3906 ignored=0
INFO [10-20|17:36:15] Imported new block receipts              count=218  elapsed=37.265ms  bytes=167361  number=611304 hash=e94c5f…22b59b ignored=0
INFO [10-20|17:36:16] Imported new block receipts              count=177  elapsed=18.802ms  bytes=350878  number=611481 hash=2b8bd4…3f7f76 ignored=0
INFO [10-20|17:36:17] Imported new block headers               count=2048 elapsed=404.375ms number=614669 hash=2fcdd5…6e40b0 ignored=0
INFO [10-20|17:36:17] Imported new block headers               count=1216 elapsed=283.165ms number=615885 hash=5b47c6…015acb ignored=0
INFO [10-20|17:36:18] Imported new block receipts              count=1337 elapsed=69.648ms  bytes=1107884 number=612818 hash=5876d5…4c0e5a ignored=0
INFO [10-20|17:36:18] Imported new block headers               count=960  elapsed=211.593ms number=616845 hash=dcdf6a…e2153c ignored=0
INFO [10-20|17:36:20] Imported new state entries               count=1096 elapsed=2.866ms   processed=812716 pending=3290  retry=0   duplicate=152 unexpected=715
INFO [10-20|17:36:22] Imported new state entries               count=863  elapsed=1.509ms   processed=813579 pending=5094  retry=272 duplicate=152 unexpected=715
INFO [10-20|17:36:23] Imported new block headers               count=1728 elapsed=452.585ms number=618573 hash=878b24…d0afdb ignored=0
INFO [10-20|17:36:24] Imported new block headers               count=384  elapsed=90.481ms  number=618957 hash=a1cb35…482285 ignored=0
INFO [10-20|17:36:24] Imported new block headers               count=192  elapsed=49.480ms  number=619149 hash=3903f6…1cbe33 ignored=0
INFO [10-20|17:36:24] Imported new block receipts              count=2    elapsed=47.891ms  bytes=4109    number=612820 hash=28f5d7…0b58e7 ignored=0
INFO [10-20|17:36:26] Imported new state entries               count=1160 elapsed=2.475ms   processed=814739 pending=4828  retry=0   duplicate=152 unexpected=715
INFO [10-20|17:36:28] Imported new state entries               count=981  elapsed=3.329ms   processed=815720 pending=4335  retry=4   duplicate=152 unexpected=715
INFO [10-20|17:36:30] Imported new block receipts              count=797  elapsed=238.110ms bytes=359735  number=613617 hash=850094…b4570d ignored=0
INFO [10-20|17:36:30] Imported new block headers               count=2048 elapsed=550.901ms number=621197 hash=8a818b…810ba8 ignored=0
INFO [10-20|17:36:30] Imported new block headers               count=256  elapsed=59.363ms  number=621453 hash=023201…73a400 ignored=0
INFO [10-20|17:36:30] Imported new block headers               count=192  elapsed=91.837ms  number=621645 hash=491e78…c07d79 ignored=0
INFO [10-20|17:36:31] Imported new state entries               count=1153 elapsed=3.147ms   processed=816873 pending=3630  retry=4   duplicate=152 unexpected=715
INFO [10-20|17:36:32] Imported new block receipts              count=2048 elapsed=127.928ms bytes=1794789 number=615665 hash=7cffe3…ae5997 ignored=0
INFO [10-20|17:36:32] Imported new block receipts              count=2048 elapsed=163.457ms bytes=3320282 number=617713 hash=b15bfe…b674da ignored=0
INFO [10-20|17:36:32] Imported new block receipts              count=439  elapsed=15.553ms  bytes=246225  number=618152 hash=d22faa…edf648 ignored=0
INFO [10-20|17:36:34] Imported new block receipts              count=1954 elapsed=97.523ms  bytes=1599587 number=620106 hash=af23b8…1042ad ignored=0
INFO [10-20|17:36:34] Imported new block receipts              count=1037 elapsed=43.991ms  bytes=676733  number=621143 hash=63af87…893d2d ignored=0
INFO [10-20|17:36:35] Imported new block headers               count=2048 elapsed=435.561ms number=623693 hash=82e787…9b0b0f ignored=0
INFO [10-20|17:36:35] Imported new block headers               count=64   elapsed=21.659ms  number=623757 hash=e01621…0056e6 ignored=0
INFO [10-20|17:36:35] Imported new block receipts              count=502  elapsed=177.381ms bytes=587205  number=621645 hash=491e78…c07d79 ignored=0
INFO [10-20|17:36:35] Imported new block headers               count=960  elapsed=277.037ms number=624717 hash=631b8a…467441 ignored=0
INFO [10-20|17:36:35] Imported new state entries               count=1005 elapsed=3.311ms   processed=817878 pending=2917  retry=0   duplicate=152 unexpected=715
INFO [10-20|17:36:36] Imported new block headers               count=384  elapsed=77.563ms  number=625101 hash=28269c…f113be ignored=0
INFO [10-20|17:36:36] Imported new block receipts              count=435  elapsed=34.817ms  bytes=555908  number=622080 hash=7fcc40…50bcb0 ignored=0
INFO [10-20|17:36:37] Imported new block receipts              count=264  elapsed=31.751ms  bytes=131264  number=622344 hash=4a7102…48fe9c ignored=0
INFO [10-20|17:36:37] Imported new block headers               count=576  elapsed=144.658ms number=625677 hash=8daf44…dd335a ignored=0
INFO [10-20|17:36:38] Imported new block receipts              count=205  elapsed=15.773ms  bytes=89758   number=622549 hash=c2475e…6afc98 ignored=0
INFO [10-20|17:36:38] Imported new block headers               count=576  elapsed=126.655ms number=626253 hash=0e6b75…4f49ec ignored=0
INFO [10-20|17:36:38] Imported new block receipts              count=552  elapsed=65.381ms  bytes=374068  number=623101 hash=35688c…3a7686 ignored=0
INFO [10-20|17:36:38] Imported new block headers               count=192  elapsed=46.567ms  number=626445 hash=1221a7…2a57d7 ignored=0
INFO [10-20|17:36:39] Imported new state entries               count=1102 elapsed=4.070ms   processed=818980 pending=2945  retry=9   duplicate=152 unexpected=715
INFO [10-20|17:36:39] Imported new block headers               count=192  elapsed=36.754ms  number=626637 hash=e4f0f4…336597 ignored=0
INFO [10-20|17:36:39] Imported new block headers               count=576  elapsed=117.846ms number=627213 hash=c1b7e7…3b09a7 ignored=0
INFO [10-20|17:36:40] Imported new block receipts              count=1200 elapsed=100.253ms bytes=1221150 number=624301 hash=b88bcc…92197c ignored=0
INFO [10-20|17:36:40] Imported new block headers               count=384  elapsed=110.979ms number=627597 hash=afce3c…8e385b ignored=0
INFO [10-20|17:36:40] Imported new block receipts              count=515  elapsed=46.257ms  bytes=354830  number=624816 hash=f45c5a…f4e070 ignored=0
INFO [10-20|17:36:40] Imported new block receipts              count=270  elapsed=21.669ms  bytes=169368  number=625086 hash=eb04f6…76232b ignored=0
INFO [10-20|17:36:40] Imported new block headers               count=576  elapsed=119.200ms number=628173 hash=802c4d…de5d55 ignored=0
INFO [10-20|17:36:41] Imported new block headers               count=192  elapsed=39.030ms  number=628365 hash=d2a1b7…d0788f ignored=0
INFO [10-20|17:36:41] Imported new block receipts              count=688  elapsed=37.156ms  bytes=582063  number=625774 hash=edd9e1…0df96a ignored=0
INFO [10-20|17:36:42] Imported new block headers               count=576  elapsed=159.834ms number=628941 hash=97bdfb…e4f10e ignored=0
INFO [10-20|17:36:42] Imported new state entries               count=932  elapsed=3.859ms   processed=819912 pending=4311  retry=169 duplicate=152 unexpected=715
INFO [10-20|17:36:42] Imported new block receipts              count=1688 elapsed=104.358ms bytes=1563065 number=627462 hash=4c28a7…174ac0 ignored=0
INFO [10-20|17:36:42] Imported new block receipts              count=276  elapsed=13.816ms  bytes=154346  number=627738 hash=ac91ff…ca893b ignored=0

**Comment by stvenyin** [comment] 2017-10-20 09:38
config
geth --datadir data  --networkid 2999 --ipcdisable --port 8081 --rpc --rpcport 8888 --rpcapi "web3,eth,net,personal" --rpccorsdomain "*"--verbosity 3 console
geth --datadir data  --networkid 2999 --ipcdisable --port 8082 --rpc --rpcport 8889 --rpcapi "web3,eth,net,personal" --rpcport -rpcapi "web3,eth,net,personal" --rpccorsdomain "*"--verbosity 3 console

**Comment by karalabe** [comment] 2017-10-20 10:15
@stvenyin Seems nothing out of the ordinary. Your node is syncing.

**Comment by stvenyin** [comment] 2017-10-20 10:24
this is sysnc pictuer
but is sync too long 
envirnemnt:win10 profreesion wmware:12 ubuntu:16.04
![1](https://user-images.githubusercontent.com/32395964/31816694-d9c2cd74-b5c3-11e7-910d-f8edcf7fbd03.png)

**Comment by stvenyin** [comment] 2017-10-20 10:27
my genesis.json
{
    "config": {
        "chainId": 19,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "difficulty": "100000000",
    "gasLimit": "2100000",
    "alloc": {
        "7df9a875a174b3bc565e6424a0050ebc1b2d1d82": { "balance": "300000" },
        "f41c74c9ae680c1aa78f42e5647a62f353b7bdde": { "balance": "400000" }
    }
}
use the same file
