### ISSUE TITLE
Bad block #1422330 gas used error (2278520 / 2278360).

### ISSUE THREAD

**Issue by 5chdn** [ethereum/go-ethereum#3183] opened 2016-10-20 14:35 UTC
Reopening #1117 as requested in new ticket.
#### System information

Geth version: `geth 1.4.18`
OS & Version: Linux
#### Expected behaviour

Sync as desired.
#### Actual behaviour

```
E1016 10:13:25.094169 core/blockchain.go:1170] Bad block #2446183 (0x7a7499dd032df75ab05b942f1b460caa4282121decb2c1e6816668a395ca5b14)
E1016 10:13:25.094222 core/blockchain.go:1171] gas used error (487080 / 486440)
```
#### Steps to reproduce the behaviour

Sync a geth node which was not fully synced before #3111 was merged.
#### Backtrace

copied from #1117 :

> Geth version is 1.14.18. Blockchain resync started with new release yesterday.

Can reproduce this issue. @karalabe is it possible this was introduced with the EIP 150 fork pull request?

```
1018 13:40:57.726646 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:40:59.022870 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:40:59.022889 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:41:01.795264 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
1018 13:41:03.720926 eth/downloader/downloader.go:298] Synchronisation failed: state data download canceled (requested)
1018 13:41:08.184917 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:41:08.184941 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:41:08.810956 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:41:18.377259 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:41:18.388097 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:41:20.137237 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:41:23.064424 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:41:28.865594 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
1018 13:41:37.402925 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:41:37.402940 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:41:41.499420 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:41:41.499443 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:41:43.544543 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:41:48.236115 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
1018 13:41:58.495638 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:42:02.167629 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:42:09.965485 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:42:09.965498 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:42:16.861561 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:42:16.861585 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:42:20.852566 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:42:28.500303 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
1018 13:42:31.687554 eth/downloader/downloader.go:298] Synchronisation failed: state data download canceled (requested)
1018 13:42:32.909598 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:42:36.956662 eth/downloader/downloader.go:298] Synchronisation failed: block body download canceled (requested)
1018 13:42:38.342605 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:42:48.133377 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:42:59.400290 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:42:59.400305 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:43:00.964555 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
1018 13:43:08.495097 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:43:10.887099 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:43:10.887114 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:43:13.006573 eth/downloader/downloader.go:298] Synchronisation failed: header processing canceled (requested)
1018 13:43:20.093865 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:43:20.093884 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:43:21.150458 core/blockchain.go:1170] Bad block #1422330 (0xd18b0a5fc9e7c7c7aa4b3d8ebdebf5fcf91090379ff050f351df442888617d16)
1018 13:43:21.150476 core/blockchain.go:1171]     gas used error (2278520 / 2278360)
1018 13:43:21.293969 eth/downloader/downloader.go:611] Peer aab61610f7040ffa [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 1.662819516s]: head header set (item 0) broke chain ordering: requested 1422137, got 1427898
1018 13:43:22.436043 eth/downloader/downloader.go:298] Synchronisation failed: receipt download canceled (requested)
CI1018 13:43:26.001649 cmd/utils/cmd.go:81] Got interrupt, shutting down...
1018 13:43:26.001693 core/blockchain.go:578] Chain manager stopped
1018 13:43:26.001703 eth/handler.go:225] Stopping ethereum protocol handler...
1018 13:43:26.001814 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
1018 13:43:27.045622 eth/handler.go:246] Ethereum protocol handler stopped
1018 13:43:27.045662 core/tx_pool.go:172] Transaction pool stopped
1018 13:43:27.045681 eth/backend.go:500] Automatic pregeneration of ethash DAG OFF (ethash dir: /home/user/.ethash)
1018 13:43:27.191571 ethdb/database.go:176] closed db:/home/user/.ethereum/chaindata
1018 13:43:27.191632 ethdb/database.go:176] closed db:/home/user/.ethereum/dapp
```

There is @ropod7 also having this issue and at least one more guy on gitter right now.

**Comment by obscuren** [comment] 2016-10-20 19:37
How was this chain synced? Fast or regular? Did you run `develop` at any given time?

**Comment by obscuren** [comment] 2016-10-20 19:38
Since your database already appears to be broken, could you run the following command in the console (`geth console`): `debug.setHead("1422320")` and then restart.

**Comment by ropod7** [comment] 2016-10-20 19:46
1. Synced fast.
  - Probably this fault shown even run --jitvm mode
3. Never ran "develop" at any time.
Also I see that the fast synced database resets and starts syncing from 0 block after headers fully loaded. e.g. today.

**Comment by mrmunch** [comment] 2016-10-21 07:24
Same error for me, but I'm on the testnet.
Running via Docker: 
```
image: ethereum/client-go:alpine
command: "--fast --testnet --shh --ipcpath /root/geth-ipc/geth.ipc"
restart: always
```
Log:
```
E1021 07:20:21.661136 core/blockchain.go:1170] Bad block #1790252 (0x5b6a3b73339b74b9fd71f24e0666e6734d575a38742507c564fb6ef7c67b1f56)
E1021 07:20:21.661188 core/blockchain.go:1171]     gas used error (2358052 / 2359852)
```

**Comment by karalabe** [comment] 2016-10-21 12:41
The testnet gas usage error seems to be caused my some miners pushing the non forked chain and a ton of old non upgraded nodes propagating the blocks. This causes fast sync to sync to the non forked chain, then obviously fail doing anything as the gas rices are bad. We haven't implemented the same fork protections we did for the DAO as noone figured someone would push the old chain; but we haven't considered the testnet's tiny difficulty which allows pushing the old chain.

I'll look into adding an enforced hash for the fork block so fast syncing the testnet cannot diverge on a malicious chain.

---

Regarding mainnet, we haven't found the cause of this issue yet.

**Comment by porobov** [comment] 2016-10-25 13:14
I'm seeing `gas used error (129452 / 131252)` when trying to deploy a contract from truffle to testnet. 
It never happened with earlier Geths. 

Current Geth version: geth 1.4.18
OS & Version: Linux

Hope it helps))

**Comment by fjl** [comment] 2016-10-25 14:11
@porobov can you share the contract / truffle invocation?

**Comment by karalabe** [comment] 2016-10-25 14:20
Are you correctly synced to the testnet?

**Comment by chevdor** [comment] 2016-10-26 10:12
I see the exact same issue than @porobov with very similar context (truffle, testnet, ...).
See some output below:

```
I1026 11:59:14.586493 eth/api.go:1183] Tx(0xf911e75cdc1dca5cfe9695b7a258ddd785fe9d353555882b14d7fc81cb997123) created: 0x0e604b526ee497aea7633d635b9be09ecb429c61
I1026 11:59:14.793861 eth/api.go:1183] Tx(0xe0f907921a3f1df9c6d2a1b84427df38ad16cd131ad50e37c4a0f65f5e71b750) created: 0xfa4436d9194266a7c5cb33fd005f86e5a695854c
I1026 12:02:06.756559 eth/downloader/downloader.go:319] Block synchronisation started
E1026 12:02:11.613785 core/blockchain.go:1170] Bad block #1783000 (0x37d8ca5f8cbbb989c8b6da426a16b51d508fbf1402c44cdc0f2ac82bfd422be5)
E1026 12:02:11.613800 core/blockchain.go:1171]     gas used error (108116 / 109916)
> I1026 12:04:25.608067 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
I1026 12:05:10.789513 eth/downloader/downloader.go:611] Peer 82b19a66aa647500 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1805456, got 1805471
```

I am using Geth/v1.4.18-stable

I very likely synced fast. 
It is possible that develop 'touched' this chain. I cannot ensure that.

I also see in Mist 0.8.6 (started with`./Mist --rpc /Users/will/Library/Ethereum/testnet/geth.ipc`) the number of remaining blocks going up and down.

Currently seeing `Downloading block 1,805,648 of 1,810,996` ...

**Comment by inzhoop** [comment] 2016-11-17 08:56
Some error on testnet at 1870154 with Geth 1.5:

E1117 09:30:47.134048 core/blockchain.go:1212] Bad block #1870154 (0xe252f4186bce9e43b42ff037e6db1d3745ca646b210ea2c23bcc288a89f5ac62)
E1117 09:30:47.134364 core/blockchain.go:1213]     gas used error (749073 / 714783)

How could i resolve?

**Comment by karalabe** [comment] 2016-11-17 09:09
Hey. It was an unfortunate last minute bug (one config field was updated with the wrong value for the testnet). The develop branch was already fixed to avoid this, so running that is one alternative (develop it currently exactly the same as the stable branch, just has this tiny fix). Otherwise we're releasing a minor update to the stable release hopefully today that will have this included.

**Comment by inzhoop** [comment] 2016-11-17 09:13
I fell in a timely bug :-/

**Comment by ropod7** [comment] 2016-11-17 09:19
Hey,
Is here any one who have block differences between latest block numbers? Is this new coming up update helpful with it? I mean my current testnet block numder about 3000 less than on etherscan.io. My client running with support dao fork directive. And client is working well with blockchain.

**Comment by Levino** [comment] 2016-11-18 15:15
Has this fix been released in 1.5.2?

**Comment by 5chdn** [comment] 2016-11-21 11:18
Still having the same issue with the latest commit as of today (1.5.3-unstable 2c802399c3ebae86af6609c5c0a13058c1017810) on Ropsten testnet:

    I1121 12:17:01.345640 eth/downloader/downloader.go:326] Block synchronisation started
    E1121 12:17:03.493347 core/blockchain.go:1212] Bad block #8928 (0x91f03a6d201d24d69cd72b62a8ebebe30a28c948ef98aed933d4a77edb7d1299)
    E1121 12:17:03.493373 core/blockchain.go:1213]     gas used error (690198 / 689558)

**Comment by holiman** [comment] 2016-11-21 12:04
Could you please test with `loglevel=6`? That would print out the receipts generated by the transactions, and give more data about what the error comes from.

**Comment by 5chdn** [comment] 2016-11-21 17:56
flag provided but not defined: -loglevel

**Comment by 5chdn** [comment] 2016-11-21 18:23
Full log at https://gist.github.com/5chdn/90e10d0341be91387beba55af12c95fe (12MiB)

**Comment by holiman** [comment] 2016-11-21 20:05
Thanks a lot for the data. Somehow the gas usage is miscalculated, it would be great to find out how/where. Are you building from source? If so, I'd _very_ much appreciate if you could make the following changes, to add more logging to two places where gas is accounted: 

```
--- a/core/state_transition.go
+++ b/core/state_transition.go
@@ -101,6 +101,11 @@ func IntrinsicGas(data []byte, contractCreation, homestead bool) *big.Int {
                m.SetInt64(int64(len(data)) - nz)
                m.Mul(m, params.TxDataZeroGas)
                igas.Add(igas, m)
+
+               if glog.V(logger.Core) {
+                       glog.Infof("intrinsicGas ( %v)\n",  igas)
+               }
+
        }
        return igas
 }
@@ -163,6 +168,10 @@ func (self *StateTransition) useGas(amount *big.Int) error {
        }
        self.gas.Sub(self.gas, amount)
 
+       if glog.V(logger.Core) {
+               glog.Infof("useGas(- %v)\n",  amount)
+       }
+
        return nil
 }
```

If the logs are a bit too much, it's enough with logging from the "core" package.

**Comment by romanick** [comment] 2016-11-22 07:47
I have similar problems on 1.5.2:

Sync ok, but new blocks not accepted.

I1122 07:30:40.148062 core/blockchain.go:1042] imported 3 blocks,     0 txs (  0.000 Mg) in   4.597ms ( 0.000 Mg/s). #17748 [b47328a4… / b5d1fc54…]
I1122 07:30:40.148378 miner/worker.go:553] commit new work on block 17749 with 0 txs & 0 uncles. Took 215.71µs
E1122 07:30:40.583156 core/blockchain.go:1212] Bad block #17749 (0xa75f23ecfee7bf581e16f44f8dc7826a815a464fa7b4903af7db921cab475ebb)
E1122 07:30:40.583244 core/blockchain.go:1213]     gas used error (197270 / 500000)

**Comment by karalabe** [comment] 2016-11-22 09:01
@romanick Are you running a node with custom modifications? Because the "commit new work" log emitted by line 542 of the miner (https://github.com/ethereum/go-ethereum/blob/release/1.5/miner/worker.go#L542), not 553 as in your dump.

**Comment by 5chdn** [comment] 2016-11-22 10:49
A real heisenbug. @holiman Instrumented the code, built from source and can not reproduce it anymore. Will report back if the logs show anything.

**Comment by holiman** [comment] 2016-11-22 11:25
Ah, bummer. Well, the logs will be huuge now if you run, I thought/hoped it would stall on that block. Thanks for the effort, anyway!

**Comment by holiman** [comment] 2016-11-22 12:17
@5chdn follow-up, and sorry if you've already answered this somewhere... I find it interesting that you've run into this on both Ropsten and Mainnet, and both 1.4 and 1.5. Could you share a bit about your setup? 

You're running Linux, but is it a real box or virtualized ?  Any filesystem peculiarities? What distro and version? Amount of RAM?

**Comment by 5chdn** [comment] 2016-11-22 13:32
@holiman sure. no virtualization anywhere.

The first one is a headless, dedicated server. running Archlinux on lts kernel v4.4.31. geth stable release from community repository [0] v1.4.18. disks are 2x HDD, Type `Linux RAID`, filesystem `ext4`. Memory 16GB RAM.

The 2nd one is a laptop running Archlinux on mainline kernel v4.8.8. here, geth unstable is installed via user repository [1] which pulls the source from git and builds from source. disks are 2x SSD, Type `Linux`, filesystem `ext4`. 16GB RAM.

[0] https://www.archlinux.org/packages/community/x86_64/geth/
[1] https://aur.archlinux.org/packages/geth-git/

**Comment by SCBuergel** [comment] 2016-11-22 22:16
I just updated to [Geth 1.5.2](https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.5.2-c8695209.tar.gz) and I am now for the first time also running into this issue:
```
2675065 [343e6abb…] import failed: gas used error (1887680 / 1889040)
E1122 22:12:39.528551 core/blockchain.go:1212] Bad block #2675065 (0x343e6abbfe0ed45e00c89395b108335149ddcd3386c3d3bf3a05506b20a62aec)
E1122 22:12:39.528587 core/blockchain.go:1213]     gas used error (1887680 / 1889040)
```

**Comment by obscuren** [comment] 2017-01-26 10:31
This has been fixed. Please re-open if another such issue pops up.

**Closed by obscuren** 2017-01-26 10:31 UTC
