### ISSUE TITLE
CPUs suddenly maxing out, failing to keep up

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/go-ethereum#2090] opened 2015-12-22 17:40 UTC
I used `killall -QUIT geth` to get the debug information:

https://ipfs.io/ipfs/QmUfpQyc7C7trjzD4ZqFsrJEzJYMrrnjDyzosdGbwacAA1

**Comment by fjl** [comment] 2015-12-22 18:32
The trace has a LOT of txpool operations going on, and several pending requests for the pending block.
Can you provide any details about your setup, command line flags, etc.

**Comment by drupalnomad** [comment] 2015-12-22 18:44
`geth --maxpeers 2500 --shh --rpc --rpcapi db,eth,net,web3,shh 2>/root/.ethereum/logfile &`

2GB 2 core Linode in Singapore. Generally has about 200 connections.

**Comment by karalabe** [comment] 2015-12-28 08:32
Note, there has been two huge transaction spikes in the last week, one lasting about a day, the other one was a few hours yesterday. It would probably take its toll on weaker machines. Also if you have a ton of connections, then the transactions are potentially propagated by many nodes to you, so you need to verify and dedup much much more of them. Any particular reason for maintaining such a high connection pool?

**Comment by karalabe** [comment] 2015-12-28 08:33
@fjl Not sure if we looked at it in the end or not a while back, but it might be worth investigating how to reduce the transaction duplication / propagation for new connections?

**Comment by drupalnomad** [comment] 2015-12-28 09:25
I have a high connection pool to be a supernode in Asia and also to stress test the software.

**Comment by obscuren** [comment] 2015-12-28 11:58
In that case you'll have to deal with high load, especially during high transaction phases since all of your connected nodes will attempt to send you transactions or you are relaying them back.

@fjl the pending blocks is probably due to high lock retention on the to pool.

**Comment by obscuren** [comment] 2016-01-04 14:21
@karalabe @fjl This is likely due to the 5 digit pending transaction pool which is being rechecked after each block.

@drupalnomad have you run in to issues lately that caused similar behaviour?

**Comment by karalabe** [comment] 2016-01-04 14:22
Yeah, this should be imho fixed by the pending PR.

**Comment by karalabe** [comment] 2016-01-05 14:48
@drupalnomad Could you please check with the current hotfix release (https://www.reddit.com/r/ethereum/comments/3zkdwq/geth_133_breviceps_released_download_transaction/) if you're using master, or latest develop for the fixed code?

**Comment by datajerk** [comment] 2016-01-05 20:29
@karalabe I have the exact same problem and can reproduce easily.  We are using ARM devices and experimenting with blockchain for IOT.  As little as 9 TX in a single block and my CPUs spike and the chain is always behind.  We have to kill geth and restart it to fix.  We only have about 20 test devices.  IOT will have a millions.  We are trying to refactor our code to use as little of the blockchain as possible now.  But it'll still never scale.  One bad actor putting too many transactions on the blockchain and it creates a stall for all transactions.

**Comment by karalabe** [comment] 2016-01-12 12:46
Could you detail the hardware of those devices? I.e. CPU, RAM, disk type? The issue @drupalnomad was mentioning was caused by the network pingponging invalid transactions, which increased linearly with the number of peers you had (hence why he was hit hard with 200+ connections). In your case if you're using a private network, I don't the same issue holds. Could you open a new thread about it with all the details (so that this one which was fixed can be closed)?

**Closed by karalabe** 2016-01-12 12:46 UTC

**Comment by datajerk** [comment] 2016-01-12 16:02
RPI2 SD card.
