### ISSUE TITLE
ttl not working as expected in shh.post

### ISSUE THREAD

**Issue by Satavim** [ethereum/go-ethereum#16305] opened 2018-03-13 07:11 UTC
Hi ,

What do ttl parameter in **shh.post** signifies. Because if in a network one node is down and message is send to the network. When the nodes comes up it should receive the messge immediatly as ttl for the message was few seconds and the node came up within that time frame.

**Comment by gluk256** [comment] 2018-03-19 18:18
can you be more specific?
how can i reproduce this issue?

**Comment by gballet** [comment] 2019-02-26 09:39
Closing this issue since no steps to reproduce have been provided. If the issue still happens, please reopen it with relevant steps to reproduce it.

**Closed by gballet** 2019-02-26 09:39 UTC
Labels: need:steps-to-reproduce, status:wontfix
