### ISSUE TITLE
--fast option seems to override default --syncmode "fast" and put in --syncmode "full" mode

### ISSUE THREAD

**Issue by tonecas** [ethereum/go-ethereum#14461] opened 2017-05-11 12:23 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

geth.exe --fast --cache=512 --datadir path/to/datadir --ethash.dagdir path/to/datadir

#### What did you expect to see?

"Imported new chain segment." messages 
no deep validation of blocks.

correct behavior:
geth.exe --syncmode "fast" --cache 512 --datadir path/to/datadir --ethash.dagdir path/to/datadir

#### What did you see instead?

start getting blocks and checking them.
 
#### System details

Version: 1.6.1-stable
Go Version: go1.8.1
OS: windows

**Comment by fjl** [comment] 2017-05-13 00:52
I can't reproduce this. It might be that full sync came into effect in some other way, but it's not related to `--fast`. Closing this because we have plenty of issues about blockchain sync and there is no new info here.

**Closed by fjl** 2017-05-13 00:52 UTC

**Comment by FredCailloux** [comment] 2017-06-05 17:22
My previous experience seem to corroborate that issue. I've been trying to start a new Ethereum wallet and use `geth.exe --fast cache=2048` 
[https://ethereum.stackexchange.com/questions/17136/why-downloading-the-blockchain-with-geth-fast-is-still-very-slow](url)
Every attempt would engage in a very long predicted download time. 
After erasing everything and start anew with `geth.exe --syncmode "fast" --cache 2048` suddenly I am aiming for a somewhat 2 to 3 hours of download time for the whole blockchain instead of the previous attempts 35 to 45 days predicted.
Big improvement.  
More later when I finish the whole implementation process. 
`geth.exe --syncmode "fast" --cache 2048` seems to do the job pretty well, so far !

**Comment by DonRoberto123** [comment] 2017-12-15 05:28
i think u guys suck big time, if i put geth.exe --syncmode "fastest" everything jumps by the couple of percentages 3% 5% 7% ... .

and that is every couple of seconds ... .

... just wanted u guys too know, how u can sync the entire chain, in a couple of minutes

**Comment by DonRoberto123** [comment] 2017-12-15 05:31
geth syncmode "fastest"

**Comment by DonRoberto123** [comment] 2017-12-15 05:36
oooh yeah, u can also add --cache=2048
