### ISSUE TITLE
timed out dao fork-check dropping

### ISSUE THREAD

**Issue by whappshh** [ethereum/go-ethereum#3044] opened 2016-09-26 17:16 UTC
#### System information

Geth version: `1.4.13`
OS & Version: Windows 7
#### Expected behaviour

To mine ethereum as usual
#### Actual behaviour

Geth starts to show '' timed out dao fork-check dropping '',yesterday everything was fine until i shutted down geth and ethminer,tried some commands from same problem topics,nothing really helps. After removedb and updatedb it like wanted to work,but after few mins(about 5) h/s goes back to 0. Im new to mining and any useful tips would be appreciated,please try to explain as simple as possible. Thanks!

**Comment by bas-vk** [comment] 2016-09-29 12:35
>  timed out dao fork-check dropping

You can ignore these messages.

From the info you provided it is a bit hard to understand what goes back to 0. The block number? If you do `removedb` geth will remove the downloaded chain and will begin synchronising from block 0.

**Comment by ivands** [comment] 2016-10-03 09:43
Guys. why are we still saying does messages can be ignored........
This is a real problem because the blockchain will stop syncing and only receive does error messages after a while.
Almost every 2 days i have to delete the blockchain and redownload it.
Also sending transaction doesn't work when the blockchain is out of sync apparently.
Our customers are really getting annoyed for not receiving they ethers.
Could you guys please take this issue more seriously.
It's really annoying seeing people brush over this issue like it isn't a problem.

**Comment by scroll** [comment] 2016-10-03 18:43
I kind of wonder the same. I can't really sync with the network. How can I ignore those messages when it's the only ones I get?!

**Comment by porobov** [comment] 2016-10-03 19:29
Geth 1.4.15 same thing under Ubuntu 14.04. Got about 12 hours of these messages only. No sync at all.

**Comment by cenotaph** [comment] 2016-10-04 08:54
Yes, sync seems to work for a little while and then stops. Our application is stuck and we can't submit any transactions. Geth seems to crash every few minutes (it restarts via upstart). Also using 1.4.15, with Ubuntu 16.04. It doesn't seem to want to get past block 2376500.

**Comment by ivands** [comment] 2016-10-04 12:41
Im stuck at 2376500 aswell.
Geth will crash every min with the following error:
"fatal error: runtime: out of memory"

**Comment by Dynamo77** [comment] 2016-10-11 17:44
I'm also stuck at 2379560 for the past week now. Don't see much in the way of a resolution to this....

**Comment by andreasbogner** [comment] 2016-10-12 07:47
I do have the same issue. Just "timed out DAO fork-check" messages and then occasionally a few blocks that get imported. Right now I am at block 2378049. But this will never catch up with the blockchain if sync does not improve significantly.

**Comment by whappshh** [comment] 2016-10-12 09:30
Same here,stuck at 2377350 block,at this speed,as it's syncing it will take me probably few weeks,lol.

**Comment by cenotaph** [comment] 2016-10-12 09:47
Hey everyone, not sure if you've been following that there was some major DDoS attacks on Geth and the latest versions have it patched. I'm sure if you upgrade to 1.4.16 your sync problems will disappear. Mine did!

**Comment by andreasbogner** [comment] 2016-10-12 09:57
Sorry @cenotaph for contradicting: I have upgraded to 1.4.17 and the problem persists. I have also tried to use the parameters suggested by [Vitalik Buterin](https://blog.ethereum.org/2016/09/22/transaction-spam-attack-next-steps/) (`--cache 1024 --targetgaslimit 1500000 --gasprice 20000000000`). Did you do anything besides upgrading?

**Comment by Dynamo77** [comment] 2016-10-12 10:07
I'll try update now. I will also note though I only got to testing it on geth because the mist wallet itself would not sync. Now I couldn't find anything on here to assist someone who just wants their mist wallet to open up and sync......all this geth stuff is not for everyone. After all is the one of purpose's of all of this to reach the masses? Now even if I get geth to sync, I certainly would have preferred an update to wallet I could just install and continue with. Saying that, I'm am learning a lot, whether or not it will be useful to me in the future who knows...

**Comment by oneala** [comment] 2016-10-12 15:27
I am having the same issue on 2 computers, one gives an error and the other one is just stuck "timed-out dropping" stuff.. i just tried with the latest version but the problem is still there... any idea ?

**Comment by andreasbogner** [comment] 2016-10-13 10:20
I finally got the client running again by reinstalling it from scratch. Just throwing away the chaindata and downloading it again did not do the trick. Maybe its not a DoS problem but a problem of updating the list of peers?

**Comment by fjl** [comment] 2016-10-13 14:35
This message is harmless but confusing because it's the only output you see while geth is busy importing large batches of blocks. We have hidden this message on the develop branch and improved block import logging so that it prints more often while heavy blocks are imported. These enhancements will be part of the next release.

**Comment by fjl** [comment] 2016-11-15 16:56
Fix released in 1.5.0.

**Closed by fjl** 2016-11-15 16:56 UTC
Labels: fixed on develop
