### ISSUE TITLE
CPU miner stops has constant hashrate and stop finding main chain blocks

### ISSUE THREAD

**Issue by anthony-cros** [ethereum/go-ethereum#985] opened 2015-05-14 19:58 UTC
The log is here https://gist.github.com/anthony-cros/827b093c0ff8810bfa39

I can tell because miners that are working well have a hash rate that changes often, whereas this one didn't. It also corresponds to the red line that goes flat on this chart: http://imgur.com/IhZ32uq, and which tranlsates to "not finding main chain blocks" (or at least not being acknowledged as the one who found it). The other miners keep finding blocks, while this one (and another one) goes flat.

**Comment by anthony-cros** [comment] 2015-05-14 20:34
(sorry, mishap)

**Comment by anthony-cros** [comment] 2015-05-14 21:09
A similar issue was reported here as well: https://www.reddit.com/r/ethereum/comments/35xxkg/olympic_blocks_mined_ranking_by_account_from/cr9a1qr

**Comment by Rytiss** [comment] 2015-05-15 07:15
Same issue as in #979

**Comment by zelig** [comment] 2015-05-16 20:06
duplicate of #979

**Closed by zelig** 2015-05-16 20:06 UTC
Labels: duplicate
