### ISSUE TITLE
[Urgent][Rinkeby]No etherium address found to fund

### ISSUE THREAD

**Issue by Sahil123** [ethereum/go-ethereum#22993] opened 2021-06-03 18:42 UTC
P.S. Sorry for spamming issue but cannot reopen previous related [issue](https://github.com/ethereum/go-ethereum/issues/21166)
Any help is appreciated? Need 15-20 RETH please!!!!

This is the **public** facebook post: https://www.facebook.com/shashank.goel.10485/posts/316952033352943
<img width="1434" alt="Screenshot 2021-06-03 at 20 38 27" src="https://user-images.githubusercontent.com/8678429/120695603-df50d380-c4ab-11eb-8e05-4af669e1aec9.png">

**Comment by ryouxin** [comment] 2021-06-04 03:32
I have  same question ， plz give 3ETH to 0xfc813f0dac9dc5f1cb4c2a85361f12b854e08348

**Comment by karalabe** [comment] 2021-06-04 05:41
Facebook removed the old mechanism we relied on. We'll need to implement a new one, but there's no priority there, so it will take a while, sorry.

**Comment by karalabe** [comment] 2021-06-04 05:41
Closing the issue since we have a tracker for the root cause already.

**Closed by karalabe** 2021-06-04 05:41 UTC
Labels: type:bug

**Comment by Sahil123** [comment] 2021-06-04 06:04
@karalabe How we are supposed to get test ether than for Rinkeby network?

**Comment by holiman** [comment] 2021-06-04 07:33
For now, I think you'll have to use the twitter mechanism. It's unfortunate, but not much we can do right now
