### ISSUE TITLE
geth crashes just when starting -  SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fff2e297548

### ISSUE THREAD

**Issue by bowhead** [ethereum/go-ethereum#16294] opened 2018-03-09 23:31 UTC
#### System information

Go Version: 
`go version go1.10 darwin/amd64`

Geth version:
```
Version: 1.8.2-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: darwin
GOPATH=
GOROOT=/usr/local/opt/go/libexec
```

OS & Version: OSX
```
uname -a result
Darwin xxxxxxx.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

#### Expected behaviour
Geth should start without any problem.
Just to clarify things I tough that the problem was related with the OS thinking that probably some particular internal engine was involved on this failure so I performed a CLEAN new fresh install (meaning by that deletion of the HDD partition, reformat to APFS, installation from an USB)

#### Actual behaviour
This is the log just when trying to start geth
```
$ geth
INFO [03-09|16:51:32] Maximum peer count                       ETH=25 LES=0 total=25
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fff2e297548]

runtime stack:
runtime.throw(0x4aea81b, 0x2a)
	/usr/local/opt/go/libexec/src/runtime/panic.go:619 +0x81
runtime.sigpanic()
	/usr/local/opt/go/libexec/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall]:
runtime.cgocall(0x4851e8f, 0xc4204c25a8, 0x8)
	/usr/local/opt/go/libexec/src/runtime/cgocall.go:128 +0x64 fp=0xc4204c2568 sp=0xc4204c2530 pc=0x4004874
github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid._Cfunc_hid_enumerate(0x2c97, 0x0)
	_cgo_gotypes.go:244 +0x4e fp=0xc4204c25a8 sp=0xc4204c2568 pc=0x4576cde
github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid.Enumerate(0xc400002c97, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid/hid_enabled.go:82 +0xa0 fp=0xc4204c2688 sp=0xc4204c25a8 pc=0x45772a0
github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).refreshWallets(0xc420303540)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:138 +0xd0 fp=0xc4204c29d8 sp=0xc4204c2688 pc=0x45af4c0
github.com/ethereum/go-ethereum/accounts/usbwallet.newHub(0x4ac489f, 0x6, 0xc4204c2c97, 0xc4201d29b8, 0x2, 0x2, 0xffa0, 0x0, 0x4b50398, 0x0, ...)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:93 +0xf8 fp=0xc4204c2a10 sp=0xc4204c29d8 pc=0x45af208
github.com/ethereum/go-ethereum/accounts/usbwallet.NewLedgerHub(0xc42044c060, 0x28, 0x40000)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:71 +0x91 fp=0xc4204c2a80 sp=0xc4204c2a10 pc=0x45af001
github.com/ethereum/go-ethereum/node.makeAccountManager(0xc4200de240, 0x4ac212b, 0x4, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/node/config.go:424 +0x199 fp=0xc4204c2b58 sp=0xc4204c2a80 pc=0x45bedc9
github.com/ethereum/go-ethereum/node.New(0xc4200de240, 0xc420081578, 0x6, 0x0)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:102 +0x1b1 fp=0xc4204c2bf8 sp=0xc4204c2b58 pc=0x45bf5e1
main.makeConfigNode(0xc420114000, 0xc420080c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/config.go:128 +0x3c9 fp=0xc4204c34e8 sp=0xc4204c2bf8 pc=0x4832df9
main.makeFullNode(0xc420114000, 0xe)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/config.go:154 +0x82 fp=0xc4204c3d00 sp=0xc4204c34e8 pc=0x48332f2
main.geth(0xc420114000, 0x4b50cf8, 0xb2d05e00)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:218 +0x2b fp=0xc4204c3d28 sp=0xc4204c3d00 pc=0x4835b2b
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x494a7e0, 0x4b521b0, 0xc420114000, 0xc420114000, 0xc4204c3f48)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8 fp=0xc4204c3d50 sp=0xc4204c3d28 pc=0x44bfeb8
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420486000, 0xc4200a4190, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x5ee fp=0xc4204c3f28 sp=0xc4204c3d50 pc=0x44be18e
main.main()
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:208 +0x55 fp=0xc4204c3f88 sp=0xc4204c3f28 pc=0x4835a75
runtime.main()
	/usr/local/opt/go/libexec/src/runtime/proc.go:198 +0x212 fp=0xc4204c3fe0 sp=0xc4204c3f88 pc=0x402fbf2
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4204c3fe8 sp=0xc4204c3fe0 pc=0x405d471

goroutine 20 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc4200ba2d0)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_recursive.go:125 +0xc7
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newRecursiveTree
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_recursive.go:119 +0x149

goroutine 21 [syscall, locked to thread]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:214 +0x41
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.init.1.func1()
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:72 +0x62
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.init.1
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:65 +0x4e

goroutine 22 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/opt/go/libexec/src/runtime/sigqueue.go:139 +0xa7
os/signal.loop()
	/usr/local/opt/go/libexec/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/opt/go/libexec/src/os/signal/signal_unix.go:28 +0x41

goroutine 24 [select, locked to thread]:
runtime.gopark(0x4b52b10, 0x0, 0x4ac4d43, 0x6, 0x18, 0x1)
	/usr/local/opt/go/libexec/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc42004f750, 0xc42009b860)
	/usr/local/opt/go/libexec/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/local/opt/go/libexec/src/runtime/signal_unix.go:549 +0x1c6
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2361 +0x1

goroutine 27 [select]:
github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0xc420467bc0)
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:94 +0x4a0
created by github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
	/private/tmp/ethereum-20180309-1771-1oglv5q/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:52 +0x5d

```

#### Steps to reproduce the behaviour
I simply tried on both ways
```
1. - Installed go on the newest version by the pkg file
2.- Installed git client 
3.- Cloned go-ethereum 
4.- Performed the make instruction inside the clone
5.- Tried to execute the geth command on the compiled code
6.- Error was thrown
```
The other one:
```
1. - Installed homebrew
2.- Installed ethereum with brew instruction
3.- Tried to execute the geth command on the compiled code
4.- Error was thrown
```

Any help will be highly appreciated!
Thanks!

**Comment by fjl** [comment] 2018-11-27 10:06
I can't reproduce this issue. Is this still happening for you?

**Comment by fjl** [comment] 2018-11-28 20:07
Closing because this is being tracked in https://github.com/ethereum/go-ethereum/issues/15100

**Closed by fjl** 2018-11-28 20:07 UTC
Labels: area:macos, area:usb, more-information-needed
