### ISSUE TITLE
Bulk block downloading stops before max chain height

### ISSUE THREAD

**Issue by samlavery** [ethereum/go-ethereum#1358] opened 2015-06-29 19:35 UTC
The geth bulk downloader only targets the block height when it starts bulk downloading, and stops when it's hit that.  Meanwhile, the chain has grown n blocks depending on how long you were downloading.  It might be useful to check the current block height while downloading and stay in bulk mode until you are near the real top block.

**Comment by fjl** [comment] 2015-06-29 19:37
@karalabe please verify

**Comment by samlavery** [comment] 2015-06-30 00:28
By stop block I mean the block height geth grabs at startup, that's what it targets for bulk downloading.  Say the chain is at 700,000 when you fire up an old geth, it will bulk download until block 700,000, while the chain has grown to 720,000.  Once it hits 700,000, it goes into normal consensus mode, but a lot of nodes can't catch up fast enough in normal peer mode.  It shouldn't stop bulk until it's fully caught up.

**Comment by karalabe** [comment] 2015-06-30 07:11
The currently implemented protocol had a limitation by design/spec that only allowed backwards hash downloads. This meant that you pick the latest hash you know in the system, pull everything from there, then fill the blocks. This obviously could only pull blocks up until the origin hash you picked.

However, while you are importing the last 1024 blocks, the downloader already completes, and starts a fresh sync cycle, looking for a new hash to import from. So yes, downloading will be done in possibly multiple phases, but they should continue one another almost continuously. Geth will **not** do a single bulk download and then switch to a different strategy, but instead the downloader runs whenever geth sees that someone's ahead of it. Furthermore, blocks propagated that are close to your head are cached specifically to prevent this issue that the downloader cannot sync up to latest head fast enough.

I'm working on the eth/61 protocol, which should allow forward block retrievals, so this has the potential to make both transitioning smoother, as well as downloading in general more stable. But IMHO, the issue has nothing really to do with the downloader and everything to do with the system in general being overloaded. My geth is using 100%, all my cores when idling (i.e. in sync with the network, nothing to import).

So, all in all, this "stopping before head is reached" is by protocol design, will be fixed hopefully using a protocol update, but shouldn't matter much if the network wouldn't be fully overloaded. Let's see how the new protocol would behave after I write it.

**Comment by karalabe** [comment] 2015-07-03 12:51
Eth/61 was merged 1-2 days ago, please verify how sync works now with the develop branch. It should be much much stabler.

**Closed** 2015-08-09 22:12 UTC
