### ISSUE TITLE
Geth stops synchronising after a while

### ISSUE THREAD

**Issue by iFA88** [ethereum/go-ethereum#2835] opened 2016-07-19 16:25 UTC
Version: Geth/v1.5.0-unstable-c75d3b0e/linux/go1.6.2
Full debug log:
https://gist.github.com/iFA88/70f7ab4c1ee0e9cf0edce125f5db8295

Sorry for the description, but i can't say too much from this situation.

**Comment by bas-vk** [comment] 2016-07-20 15:48
What do you mean with hangs suddenly?

Can you still attach to the node with the console, or is the process entirely deadlocked? In the latter case can you start geth with the `--proff` flag? This enables a profiler. When geth is stuck post the contents of `http://localhost:6060/debug/pprof/goroutine?debug=2` in a gist here.

**Comment by iFA88** [comment] 2016-07-20 17:58
I run the Geth like a linux daemon. After few days the syncing stops. I can do anything and have set debug.verbosity to 6 after when i noticed the problem. I can use the geth RPC without any problem. Okay i will do!

**Comment by karalabe** [comment] 2016-07-22 15:08
I did find an issue in the downloader we've introduced in the EDGE release. https://github.com/ethereum/go-ethereum/pull/2855

**Comment by iFA88** [comment] 2016-07-22 17:14
@karalabe Nice! Thank you very much!

**Comment by karalabe** [comment] 2016-07-22 17:15
I'm not sure this was the cause, so I wouldn't close this issue just yet. Let's see that patch on develop and how it behaves first :)

**Comment by iFA88** [comment] 2016-07-22 17:20
@karalabe Hmokay, i still use Geth/v1.5.0-unstable-599e3c7b/linux/go1.6.2 on my server. When it stops then i can send some commands to geth what you recommend debug.stacks() or any else. Please reply for some instructions.

**Comment by iFA88** [comment] 2016-07-25 12:42
Geth hangs again.
debug.stacks():
https://gist.github.com/iFA88/6aa95232eb1eaeb42560b5ab1c577bb8
I can run other commands too, need only tell me and i run it.

**Comment by iFA88** [comment] 2016-07-25 13:03
debug.vmodule("downloader=6")
https://gist.github.com/iFA88/958c341489fe1c0a8509f8de2f2a54af

**Comment by karalabe** [comment] 2016-07-25 13:06
Should be fixed on develop by https://github.com/ethereum/go-ethereum/pull/2855 :)

**Closed by karalabe** 2016-07-25 13:06 UTC
