### ISSUE TITLE
Geth 1.10.4 high memory use - how to gather data

### ISSUE THREAD

**Issue by yorickdowne** [ethereum/go-ethereum#23195] opened 2021-07-11 11:35 UTC
From Geth Discord, by fjl - this is a quote, not my words:

I have seen quite a few reports of high memory usage with Geth v1.10.4 last couple days in here,
some people have even reported that there seems to be a leak, with used memory steadily rising.
If you are experiencing this problem, we would appreciate if you could do the following steps:

- enable the pprof server (debugging tool) by starting geth with the --pprof flag
- this will enable an HTTP server on port 6060 on localhost
- wait for it to reach high memory usage
- then go to http://127.0.0.1:6060/memsize
- click the Scan "node" button
- this operation will freeze the node for quite a while and perform an internal scan of used memory
- when it's done, post the resulting report to https://gist.github.com/, then link it here on [Geth Discord](https://discord.gg/VNnEHqsHMr)

**Note**: If your system is very low on memory, the memsize scan can crash your node (because the scanning also uses some extra memory). Also, the node will not be operational while it does the scanning.

If you are using grafana, or another metrics solution, please monitor the geth/system/cpu/goroutines.gauge metric.
This metric is the number of lightweight Go threads used by geth. If this number keeps going up, it's a goroutine leak. This kind of leak can happen when there is a bug, and it will usually manifest as memory usage increasing.
It's kind of good to monitor this metric in general.
On our nodes, with 50 peers, the goroutine count is ~600-650

https://discord.com/channels/482467812179181568/482467812816977921/862323752695103519
in https://discord.gg/VNnEHqsHMr

Note: If you are looking to access the pprof web page over the LAN, you'll also need `--pprof.addr=0.0.0.0` and port `6060/tcp` open on your host firewall, like ufw. Be careful not to expose the port to "Internet at large".

**Note**: Wait until Geth uses 11GiB+, ideally even 14GiB+ of RAM, before running a report. The initial increase up to 8-9 GiB might not be that instructive. Geth 1.10.3 used 8-9 GiB of RAM on mainnet with default settings, that level of use is expected.

**Comment by DanHenton** [comment] 2021-07-11 12:19
I restarted my node recently here is two scans that were taken a few minutes apart with increasing Bitmap sizes.

[First scan](https://gist.github.com/DanHenton/08e9c7edb42d674eb485c4239c5fff86)
[Second scan](https://gist.github.com/DanHenton/94c6ebcafedca3c564bdefd39adc2748)

VERSION:                                                                                                                                                                                     
   1.10.4-stable-aa637fd3 
 
Note: I'm running `mainnet` and `pyrmont` on one machine with 64GB my current average MEM usage is ~65% but was up over 80% before I restarted the machine.

**Comment by adrienlacombe** [comment] 2021-07-11 16:52
Approx 5G of RAM used by geth right now, 12 before restart
First report here: https://gist.github.com/adrienlacombe/a9d89abcf44d165f1ddf4af55076b8a1

**Comment by OdysLam** [comment] 2021-07-11 17:32
Tangiantely relevant, but if I enable the --pprof server, I can't enable the metrics server, since both use port 6060.  Port for metrics must be changed with `--metrics.port value  ` so that they both co-exist.

**Comment by DanHenton** [comment] 2021-07-11 23:11
Here is a scan roughly 12 hours later. still increasing in memory allocation

[12hr scan](https://gist.github.com/DanHenton/62a281a2e765d0130d515e7430bc3ea5)

Hope it helps :smile:

**Comment by MariusVanDerWijden** [comment] 2021-07-12 06:31
@adrienlacombe @DanHenton Thank you for providing so many data points!
Could you run `geth attach --exec debug.writeMemProfile\(\"memprofile\"\)` on your nodes? It creates a file `memprofile` which contains detailed information about where the memory is retained/allocated/etc.

**Comment by adrienlacombe** [comment] 2021-07-12 07:06
@MariusVanDerWijden thank you for your help! Here is the file.
[memprofile.zip](https://github.com/ethereum/go-ethereum/files/6799264/memprofile.zip)

**Comment by adrienlacombe** [comment] 2021-07-12 08:49
@MariusVanDerWijden debug.stacks results
[stacks.txt](https://github.com/ethereum/go-ethereum/files/6799937/stacks.txt)

**Comment by colorfulcoin** [comment] 2021-07-12 12:50
When I run, `sudo systemctl status geth`, it shows 21.5Gb. Here's the output.  The numbers look smaller in the report, but I'm not sure I am reading it correctly. 

Running my node with `geth --http --datadir /var/lib/goethereum --cache 10240 --maxpeers 50 --pprof`

[gethscan.txt](https://github.com/ethereum/go-ethereum/files/6801494/gethscan.txt)

**Comment by MariusVanDerWijden** [comment] 2021-07-12 13:21
@colorfulcoin Could you also run
`geth attach --exec debug.stacks\(\) > file` and 
`geth attach --exec debug.writeMemProfile\(\"memprofile\"\)` and paste the resulting files `memprofile` and `file` here

**Comment by colorfulcoin** [comment] 2021-07-12 13:58
@MariusVanDerWijden no problem, happy to help. When I run `geth attach http://127.0.0.1:8545 --exec debug.stacks\(\) > debugstacks.txt` and cat the file I get this. Is that the wrong endpoint to be running against or something?

```
ReferenceError: debug is not defined
	at <eval>:1:1(0)
```

**Comment by holiman** [comment] 2021-07-12 14:21
The debug namespace is by default not available over http, but should work if you attach to the ipc endpoint

**Comment by colorfulcoin** [comment] 2021-07-12 20:00
> @MariusVanDerWijden no problem, happy to help. When I run `geth attach http://127.0.0.1:8545 --exec debug.stacks\(\) > file` and cat file I get this. Any suggestions for what flags I need to be running to enable debug?
> 
> ```
> ReferenceError: debug is not defined
> 	at <eval>:1:1(0)
> ```

See attached. I ran a new scan as well. I was unable to get `sudo geth attach /var/lib/goethereum/geth.ipc --exec debug.writeMemProfile\(\"memprofile\"\)` to run. Getting:

```
Error: open memprofile: permission denied
	at web3.js:6357:37(47)
	at web3.js:5091:62(37)
	at <eval>:1:22(4)
```

[file.txt](https://github.com/ethereum/go-ethereum/files/6804077/file.txt)
[gethscan.txt](https://github.com/ethereum/go-ethereum/files/6804080/gethscan.txt)

**Comment by adrienlacombe** [comment] 2021-07-12 20:18
@colorfulcoin I had the same issue, try `sudo geth attach /var/lib/goethereum/geth.ipc --exec debug.writeMemProfile\(\"tmp/\memprofile\"\)`

**Comment by colorfulcoin** [comment] 2021-07-12 20:23
@adrienlacombe that outputs `null`. What is that command doing? I am assuming it outputs something somewhere.

**Comment by adrienlacombe** [comment] 2021-07-12 20:33
That's good, you should now have a file with name memprofile in /tmp/ folder @colorfulcoin

**Comment by colorfulcoin** [comment] 2021-07-12 20:35
@adrienlacombe It seems to be encoded/encrypted. Cat the file just leads a bunch of stuff like this `o�u24�Kٰ���d�.sI���Gc��Z�;��ު�{xN�C����H���n2����dN��hG�?` Not sure what the ask is here.

**Comment by adrienlacombe** [comment] 2021-07-12 20:52
This is fine @colorfulcoin upload the file here.

**Comment by colorfulcoin** [comment] 2021-07-12 20:57
ok I've modified my above comment to add it.

**Comment by fjl** [comment] 2021-07-12 21:23
@colorfulcoin The memprofile is a binary file. It contains information about objects in the memory used by geth. Specifically, it contains information about the place in the code where each object was created.

**Comment by OdysLam** [comment] 2021-07-13 11:35
@yorickdowne, regarding the goroutines issue you mentioned. I have found this GETH in the wild and apparently has about 1.5K goroutines:

http://167.71.245.14:7071/debug/metrics/prometheus

**Comment by yorickdowne** [comment] 2021-07-13 14:47
@fjl ^^

**Comment by SeaMonkey82** [comment] 2021-07-13 20:26
This isn't entirely necessary for helping troubleshoot this, but it's relevant and something I've been meaning to add to my monitoring solution anyhow.

[Monitoring Geth with InfluxDB and Grafana](https://ethereum.org/en/developers/tutorials/monitoring-geth-with-influxdb-and-grafana/)

**Comment by holiman** [comment] 2021-07-15 09:13
@yorickdowne sent info to you on how to investigate further, see discord

**Comment by begetan** [comment] 2021-07-16 10:39
I did a lot of snapshot syncing tests recently for the version of 1.10.4
In all configurations, I saw a Geth memory leak. It grows up around 1GB/per day.  Geth on a test node with 8GB RAM and `--cache=3072` was killed by the OOM killer after 4-5 days of uptime. 

I run a test node now sith disabled snapshot feature based on this [ticket](https://github.com/ethereum/go-ethereum/issues/23075) 

Here is the current measurement:

- 4,7 GB after sync completed
- 5,1 GB on day 1
- 5,3 GB on day 2
- 5,5 GB on day 3

I know we should wait until Geth grows up to 7-9Gb before any conclusion.

But I would suggest digging into this direction.

**Comment by jacobfrank250** [comment] 2021-07-16 17:54
I have been trying to sync, and geth will not run for more than 3 hours (often less) without stopping. I believe I am running out of memory. I only have 4 GB Ram, but I thought this was the base requirement. I generated files as suggested by @MariusVanDerWijden, by running  
./geth attach --exec debug.stacks\(\) > file and
./geth attach --exec debug.writeMemProfile\(\"memprofile\"\) 

Here are those files
[file.txt](https://github.com/ethereum/go-ethereum/files/6832564/file.txt)
[memprofile.txt](https://github.com/ethereum/go-ethereum/files/6832565/memprofile.txt)

**Comment by holiman** [comment] 2021-07-16 19:45
Seems that many of these reports concern snap sync. I'm doing a benchmark run of `1.10.3` vs `1.10.5` now, to see if we can repro it in our internal environments. 

If not, then another possibility might be that the "comomn ground" is the RPC load from being eth2 backends, and something has regressed in that department.

**Comment by holiman** [comment] 2021-07-17 08:16
During sync, `1.10.5` is indeed a bit higher in memory usage, which is a side-effect of it being faster downloading headers/block data. It achieves higher ingress speeds, and  competes that phase sooner: 

`1.10.5` is green, and `1.10.3` is yellow:  
![Screenshot_2021-07-17 Dual Geth - Grafana](https://user-images.githubusercontent.com/142290/126030778-597ed11c-4487-48a8-8ba8-5e8a9dba05c6.png)

![Screenshot_2021-07-17 Dual Geth - Grafana(1)](https://user-images.githubusercontent.com/142290/126030826-eb5e609b-cbc7-4d1a-9fe2-b80b87342a50.png)

Although the usage is a bit higher, I don't think it is high enough to be the culprit behind the bug reports.

**Comment by terorie** [comment] 2021-07-19 18:46
@holiman We have counted ~20 OOM kill events on about a dozen nodes using 1.10.4 with `--syncmode=snap --snapshot=true`. The OOM hard limit was set to 11 GB. Nodes would allocate memory over about a week. All of these nodes were upgraded from older Geth versions that were initially synced with `fast`.
![image](https://user-images.githubusercontent.com/21371810/126209106-97b5e32e-460c-478c-b8ea-c009264df7f4.png)

After searching for the root cause to no avail, this problem magically fixed itself two weeks later (still the same nodes on 1.10.4, no config changes).
![image](https://user-images.githubusercontent.com/21371810/126209787-8c4c2bfc-2e40-4e32-8fdb-9e07cfe3a05a.png)

We've spun up two 1.10.4 nodes as a test run:

**--syncmode=snap --snapshot=true** (Jul 12th)
9GB of memory used after 4.5 days of syncing. About 1GB/day growth.

**--syncmode=fast --snapshot=false** (Jul 19th)
5.5 GB of memory used after 6 days of syncing (from scratch). Memory usage is stable, no OOM kills.

**Comment by begetan** [comment] 2021-07-21 15:02
I have a concern about the snapshot mode support, not about initial sync.

I've changed snapshot settings for the same synced node twice (without cleaning up blockchain data) and always saw the same behavior. Geth process running with options `--syncmode=fast --snapshot=false` has no memory leak, while process without these options leaking with 0,8-1GB/per day.

**Comment by agro1986** [comment] 2021-07-24 10:47
Here's my memsize scan using 1.10.4, snapshotted when geth is using 12.8 GB of memory (per `sudo pmap $GETH_PID`)

https://gist.github.com/agro1986/4195473c093fa78704d1bf19c9de9518

As you can see below, since I upgraded to 1.10.4 in July 1st, geth will bring the available memory of my system down until it crashes or until I restart geth (in which the available memory will jump back again).

<img width="1776" alt="Screen Shot 2021-07-24 at 19 45 29" src="https://user-images.githubusercontent.com/6017531/126866113-d5008ff9-f44b-4b53-8645-a56e0465857d.png">

I launch geth using this

```
/usr/local/bin/geth --http --datadir /somewhere/geth --cache 2048 --maxpeers 40 --pprof --pprof.addr=0.0.0.0
```

**Comment by fjl** [comment] 2021-07-29 14:36
Thanks everyone for providing all this memory usage data. We have been checking it out, and have enough reports now. 

I've looked at a lot of these reports and found that the out-of-memory crashes cannot be explained using the information seen in memsize. In most reports, the top item are the 'cached trie nodes', which is expected.

**Comment by agro1986** [comment] 2021-07-30 06:16
As an additional info, I updated from 1.10.4 -> 1.10.6 and the issue still persists

**Comment by agro1986** [comment] 2021-08-03 14:30
It seems that memory usage is better after pruning (1.10.6). You can see on graph below, the after last restart I pruned and after that available memory doesn't drop as sharply as before. Might need to see how it behaves after several more days.

<img width="1453" alt="Screen Shot 2021-08-03 at 23 27 11" src="https://user-images.githubusercontent.com/6017531/128033001-5e0f5615-dac9-4d35-be4f-c31af6b16ea2.png">

**Comment by bassoy** [comment] 2021-08-19 15:07
> I have a concern about the snapshot mode support, not about initial sync.
> 
> I've changed snapshot settings for the same synced node twice (without cleaning up blockchain data) and always saw the same behavior. Geth process running with options `--syncmode=fast --snapshot=false` has no memory leak, while process without these options leaking with 0,8-1GB/per day.

Same here:
![image](https://user-images.githubusercontent.com/3994021/130092683-46ea690f-74cd-4b56-8812-7b050d5145c4.png)
Using geth version 1.10.6-stable-576681f2 with `--metrics --metrics.expensive --pprof --http --cache 1024`.

**Comment by yorickdowne** [comment] 2021-09-01 20:10
This has been hitting Bor ever since they rebased themselves on Geth 1.10.8. In their case it hits some, not all nodes, and seems to be related to P2P. Keep an eye on https://github.com/maticnetwork/bor/issues/179

**Comment by yorickdowne** [comment] 2021-09-19 10:17
So from the Polygon/Bor side of things: It's a lot worse with many (150-200) peers, and considerably more mellow with few (<=50) peers. Hopefully this gives the Geth team something to look for. It should be possible to reproduce this issue more rapidly by setting maxpeers to 200.

**Comment by StakeNoob** [comment] 2021-10-31 10:15
> We fixed an issue in v.1.10.9 here: [067084f](https://github.com/ethereum/go-ethereum/commit/067084fedab1d50e224e40e6442a7740fc53611a) which should fix a potential memory leak in the transaction pool. Are there any nodes experiencing the memory leak post 1.10.9?

I am on Geth 1.10.10 and get unclean shutdown every few hours, htop shows me it is because Geth takes all my RAM.  I have 16GB DDR4 3300Mhz on an Asus PN50.  When I run --pprof I get the following but I cannot establish a link to the address to scan the node.

![pprof](https://user-images.githubusercontent.com/93400763/139577818-614b424a-c523-4646-8ffd-ac71836e86ea.png)
![geth ram](https://user-images.githubusercontent.com/93400763/139577822-03995291-2efe-4ebb-9d80-9d7596a3761e.png)

**Comment by MariusVanDerWijden** [comment] 2021-11-01 06:44
Do you have two geth nodes running? `Error bind address already in use` only happens if some other process already servers port 30303 (which is usually another instance of geth)

**Comment by StakeNoob** [comment] 2021-11-01 20:55
> Do you have two geth nodes running? `Error bind address already in use` only happens if some other process already servers port 30303 (which is usually another instance of geth)

This is interesting because I did have to rebuild the database after my memory had less than <50gb for pruning- I followed instructions for removing the database and then letting it re-sync.  I followed Somer Esat guide for initial install.  Any tips to help figure this out?

**Comment by MariusVanDerWijden** [comment] 2021-11-02 13:59
` lsof -i :30303`

**Comment by StakeNoob** [comment] 2021-11-02 21:04
> ` lsof -i :30303`

This introduces the next command line and gives no information.  It has got me thinking though; Somer Esat Guide recommends a certain directory for geth which is what I have when I do geth status, but --pprof seems to show a different directory.  Could this mean 2 instances of Geth after all?


![--pprof geth](https://user-images.githubusercontent.com/93400763/139951315-9cc764b4-a6ab-4d09-865d-0c04f4b43724.png)
![somer geth](https://user-images.githubusercontent.com/93400763/139951317-09690d2c-ab90-48e9-b5ad-7628b0d18259.png)

**Comment by MariusVanDerWijden** [comment] 2021-11-03 14:37
It seems that this issue was fixed in v.1.10.9. A race condition resulted in transactions not getting deallocated and garbage collected correctly. If you are experience high memory usage with a version higher than v.1.10.9 please open a new issue! 
Thank you to everyone who helped us getting to the bottom of this!

**Closed by MariusVanDerWijden** 2021-11-03 14:37 UTC
Labels: type:bug
