### ISSUE TITLE
Propose a block that does not contain any transactions

### ISSUE THREAD

**Issue by artree222** [ethereum/go-ethereum#30033] opened 2024-06-20 14:08 UTC
On the mainnet, we are using the Prysm client to connect to the validator, but the validator proposed a block at slot 9297851 that did not contain any transactions. We hope the community can help us look into the reason for this.

The following is Prysm log:
```
time="2024-06-15 04:50:12" level=info msg="gRPC client connected to beacon node" addr="xx.xx.xx.xx:xx" prefix=rpc
time="2024-06-15 04:50:19" level=error msg="Could not handle p2p pubsub" error="could not validate blob data availability: context deadline waiting for blob sidecars slot: 9297847, BlockRoot: 0x70ee1d904f560baba0f959f07895ce14be2ec76a4a1d19672e4266976fed564a: context deadline exceeded" prefix=sync topic="/eth2/6a95a1a9/beacon_block/ssz_snappy"
time="2024-06-15 04:50:25" level=info msg="Synced new block" block=0x70ee1d90... epoch=290557 finalizedEpoch=290555 finalizedRoot=0x3ff7eb5d... prefix=blockchain slot=9297847
time="2024-06-15 04:50:25" level=info msg="Finished applying state transition" attestations=87 kzgCommitmentCount=4 payloadHash=0x27894e8867a6 prefix=blockchain slot=9297847 syncBitsCount=509 txCount=173
time="2024-06-15 04:50:26" level=info msg="Synced new block" block=0x407d5564... epoch=290557 finalizedEpoch=290555 finalizedRoot=0x3ff7eb5d... prefix=blockchain slot=9297848
time="2024-06-15 04:50:26" level=info msg="Finished applying state transition" attestations=128 kzgCommitmentCount=6 payloadHash=0x609356e79ce1 prefix=blockchain slot=9297848 syncBitsCount=510 txCount=212
time="2024-06-15 04:50:26" level=info msg="Synced new block" block=0x25d6d82f... epoch=290557 finalizedEpoch=290555 finalizedRoot=0x3ff7eb5d... prefix=blockchain slot=9297849
time="2024-06-15 04:50:26" level=info msg="Finished applying state transition" attestations=73 kzgCommitmentCount=6 payloadHash=0x75a8302f9c54 prefix=blockchain slot=9297849 syncBitsCount=508 txCount=191
time="2024-06-15 04:50:29" level=info msg="Synced new block" block=0x8f13baed... epoch=290557 finalizedEpoch=290555 finalizedRoot=0x3ff7eb5d... prefix=blockchain slot=9297850
time="2024-06-15 04:50:29" level=info msg="Finished applying state transition" attestations=72 kzgCommitmentCount=6 payloadHash=0x9f200f5067e3 prefix=blockchain slot=9297850 syncBitsCount=510 txCount=100
time="2024-06-15 04:50:35" level=info msg="Begin building block" prefix="rpc/validator" sinceSlotStartTime=23.423581ms slot=9297851
time="2024-06-15 04:50:35" level=warning msg="could not find tracked proposer index" headRoot=0x8f13baed2056ca9fb0628c9d62c1ca66bbea18dbccfc16664c71202cb5fe627b slot=9297851 validatorIndex=275839
time="2024-06-15 04:50:35" level=info msg="Finished building block" prefix="rpc/validator" sinceSlotStartTime=94.263226ms slot=9297851 validator=275839
time="2024-06-15 04:50:35" level=info msg="Synced new block" block=0x1426caa4... epoch=290557 finalizedEpoch=290555 finalizedRoot=0x3ff7eb5d... prefix=blockchain slot=9297851
time="2024-06-15 04:50:35" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x0ed10159339f prefix=blockchain slot=9297851 syncBitsCount=509 txCount=0
time="2024-06-15 04:50:50" level=info msg="Synced new block" block=0xcd282755... epoch=290557 finalizedEpoch=290555 finalizedRoot=0x3ff7eb5d... prefix=blockchain slot=9297852
time="2024-06-15 04:50:50" level=info msg="Finished applying state transition" attestations=128 kzgCommitmentCount=3 payloadHash=0xba5b04bbaaac prefix=blockchain slot=9297852 syncBitsCount=512 txCount=349
```

The following is Geth log:
```
INFO [06-15|04:50:26.147] Imported new potential chain segment     number=20,092,543 hash=609356..78ce57 blocks=1 txs=212  mgas=20.614 elapsed=255.104ms    mgasps=80.806  snapdiffs=6.97MiB  triedirty=1022.22MiB
INFO [06-15|04:50:26.220] Chain head was updated                   number=20,092,543 hash=609356..78ce57 root=511031..341251 elapsed=4.454392ms
INFO [06-15|04:50:26.431] Imported new potential chain segment     number=20,092,544 hash=75a830..e32222 blocks=1 txs=191  mgas=16.086 elapsed=145.673ms    mgasps=110.425 snapdiffs=7.02MiB  triedirty=1022.36MiB
INFO [06-15|04:50:26.530] Chain head was updated                   number=20,092,544 hash=75a830..e32222 root=d4a287..574610 elapsed=3.079023ms
INFO [06-15|04:50:29.738] Imported new potential chain segment     number=20,092,545 hash=9f200f..057d36 blocks=1 txs=100  mgas=6.230  elapsed=84.656ms     mgasps=73.594  snapdiffs=7.04MiB  triedirty=1022.67MiB
INFO [06-15|04:50:29.849] Chain head was updated                   number=20,092,545 hash=9f200f..057d36 root=6b68ff..7c5271 elapsed=1.375609ms
INFO [06-15|04:50:35.061] Starting work on payload                 id=0x03404ae851fd05ab
INFO [06-15|04:50:35.083] Stopping work on payload                 id=0x03404ae851fd05ab reason=delivery
INFO [06-15|04:50:35.184] Imported new potential chain segment     number=20,092,546 hash=0ed101..48ab7a blocks=1 txs=0    mgas=0.000  elapsed=28.942ms     mgasps=0.000   snapdiffs=7.02MiB  triedirty=1020.20MiB
INFO [06-15|04:50:35.308] Chain head was updated                   number=20,092,546 hash=0ed101..48ab7a root=8a4e78..43a5c9 elapsed="84.351µs"
INFO [06-15|04:50:49.584] Imported new potential chain segment     number=20,092,547 hash=ba5b04..b0264d blocks=1 txs=349  mgas=29.992 elapsed=338.006ms    mgasps=88.732  snapdiffs=7.10MiB  triedirty=1021.25MiB
INFO [06-15|04:50:50.962] Chain head was updated                   number=20,092,547 hash=ba5b04..b0264d root=b3abf4..c09bbd elapsed=5.953949ms
```

The following is Mev log:
```
time="2024-06-15T04:50:05.892+08:00" level=info msg="http: GET / 200" duration=0.000034 method=GET path=/ status=200 version=1.7
time="2024-06-15T04:50:09.19+08:00" level=debug msg="checking relay status" url="https://boost-relay.flashbots.net/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.19+08:00" level=debug msg="checking relay status" url="https://mainnet-relay.securerpc.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.19+08:00" level=debug msg="checking relay status" url="https://bloxroute.max-profit.blxrbdn.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.19+08:00" level=debug msg="checking relay status" url="https://agnostic-relay.net/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.19+08:00" level=debug msg="checking relay status" url="https://relay.ultrasound.money/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.19+08:00" level=debug msg="checking relay status" url="https://relay.edennetwork.io/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.19+08:00" level=debug msg="checking relay status" url="https://aestus.live/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.19+08:00" level=debug msg="checking relay status" url="https://bloxroute.regulated.blxrbdn.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.374+08:00" level=debug msg="relay status OK" url="https://agnostic-relay.net/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.408+08:00" level=debug msg="relay status OK" url="https://bloxroute.max-profit.blxrbdn.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.41+08:00" level=debug msg="relay status OK" url="https://relay.edennetwork.io/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.427+08:00" level=debug msg="relay status OK" url="https://relay.ultrasound.money/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.465+08:00" level=debug msg="relay status OK" url="https://boost-relay.flashbots.net/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.473+08:00" level=debug msg="relay status OK" url="https://bloxroute.regulated.blxrbdn.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.502+08:00" level=debug msg="relay status OK" url="https://aestus.live/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.893+08:00" level=debug msg="relay status OK" url="https://mainnet-relay.securerpc.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:09.893+08:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.702974 method=GET path=/eth/v1/builder/status status=200 version=1.7
time="2024-06-15T04:50:15.883+08:00" level=info msg="http: GET / 200" duration=0.000030 method=GET path=/ status=200 version=1.7
time="2024-06-15T04:50:25.908+08:00" level=info msg="http: GET / 200" duration=0.000038 method=GET path=/ status=200 version=1.7
time="2024-06-15T04:50:30.566+08:00" level=debug msg="checking relay status" url="https://boost-relay.flashbots.net/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.566+08:00" level=debug msg="checking relay status" url="https://mainnet-relay.securerpc.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.566+08:00" level=debug msg="checking relay status" url="https://relay.edennetwork.io/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.566+08:00" level=debug msg="checking relay status" url="https://relay.ultrasound.money/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.566+08:00" level=debug msg="checking relay status" url="https://aestus.live/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.566+08:00" level=debug msg="checking relay status" url="https://bloxroute.regulated.blxrbdn.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.566+08:00" level=debug msg="checking relay status" url="https://bloxroute.max-profit.blxrbdn.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.566+08:00" level=debug msg="checking relay status" url="https://agnostic-relay.net/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.757+08:00" level=debug msg="relay status OK" url="https://agnostic-relay.net/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.784+08:00" level=debug msg="relay status OK" url="https://relay.ultrasound.money/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.785+08:00" level=debug msg="relay status OK" url="https://bloxroute.max-profit.blxrbdn.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.787+08:00" level=debug msg="relay status OK" url="https://relay.edennetwork.io/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.837+08:00" level=debug msg="relay status OK" url="https://boost-relay.flashbots.net/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:30.876+08:00" level=debug msg="relay status OK" url="https://aestus.live/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:31.139+08:00" level=debug msg="relay status OK" url="https://bloxroute.regulated.blxrbdn.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:31.243+08:00" level=debug msg="relay status OK" url="https://mainnet-relay.securerpc.com/eth/v1/builder/status" version=1.7
time="2024-06-15T04:50:31.244+08:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.677619 method=GET path=/eth/v1/builder/status status=200 version=1.7
time="2024-06-15T04:50:35.881+08:00" level=info msg="http: GET / 200" duration=0.000040 method=GET path=/ status=200 version=1.7
time="2024-06-15T04:50:45.885+08:00" level=info msg="http: GET / 200" duration=0.000034 method=GET path=/ status=200 version=1.7
time="2024-06-15T04:50:55.883+08:00" level=info msg="http: GET / 200" duration=0.000033 method=GET path=/ status=200 version=1.7
time="2024-06-15T04:51:05.882+08:00" level=info msg="http: GET / 200" duration=0.000032 method=GET path=/ status=200 version=1.7
```

**Comment by MariusVanDerWijden** [comment] 2024-06-21 08:08
```
INFO [06-15|04:50:35.061] Starting work on payload                 id=0x03404ae851fd05ab
INFO [06-15|04:50:35.083] Stopping work on payload               id=0x03404ae851fd05ab reason=delivery
```

Looks like the CL only gave us 22ms to build a block. This is not enough time, so we return an empty block.
It also seems like the CL did not ask for a block from mev-boost.

**Comment by karalabe** [comment] 2024-06-27 08:54
I'm unsure

```
INFO [06-15|04:50:29.849] Chain head was updated                   number=20,092,545 hash=9f200f..057d36 root=6b68ff..7c5271 elapsed=1.375609ms
INFO [06-15|04:50:35.061] Starting work on payload                 id=0x03404ae851fd05ab
INFO [06-15|04:50:35.083] Stopping work on payload                 id=0x03404ae851fd05ab reason=delivery
```

Triggering a block build happens on forkchoiceUpdate, which did arrive 6 seconds earlier. So seems there was a 6s limbo in between.

**Comment by fjl** [comment] 2024-06-27 09:04
After some deeper investigation, this seems like a Prysm-related issue.

**Comment by karalabe** [comment] 2024-06-27 09:05
That said

```
time="2024-06-15 04:50:35" level=info msg="Begin building block" prefix="rpc/validator" sinceSlotStartTime=23.423581ms slot=9297851
```

Prysm has this strange log, which might mean that Prysm sent a forckchoiceupdate without requesting block production and later requested, but too late.

**Comment by potuz** [comment] 2024-06-27 10:41
Hi, thanks for the ping @MariusVanDerWijden . The issue is with Prysm here, the relevant line of log is this one

> time="2024-06-15 04:50:35" level=warning msg="could not find tracked proposer index" headRoot=0x8f13baed2056ca9fb0628c9d62c1ca66bbea18dbccfc16664c71202cb5fe627b slot=9297851 validatorIndex=275839

This indicates that Prysm had no idea that the beacon was following this validator and that therefore when it sent FCUs to geth it did so without any payload attributes. When the slot starts and the validator client requests a block from Prysm then the beacon is forced to produce one and then immediately requests one to geth by sending a new FCU with the payload attributes for this slot. Geth understandably cannot produce any transactions and the beacon also cannot set the fee recipient address since it seems to not be tracking this validator. 

Some questions for the user would be:

1. Was this validator key just activated/added to the validator client?
2. Was the beacon/validator client just restarted? 
3. How was the configuration for fee recipient done on the pair beacon/validator? Is there a default fee recipient set either in the VC config or the BN config? 

Even if everything fails, the fee recipient should be set to a default fallback, in this case is null so I assume that there is no default configured. 

Please feel free to ping me on the Prysm Discord channel to continue on this. It would be helpful if you run Prysm with Debug level logs instead of Info. To the geth owner, I think it's safe to close this issue as a Prysm/Operator issue rather than geth's

**Comment by MariusVanDerWijden** [comment] 2024-06-27 10:47
I'll close this issue for now, since it doesn't seem to be related to geth. 
Please follow up with @potuz, thanks for reporting!

**Closed by MariusVanDerWijden** 2024-06-27 10:47 UTC
Labels: type:docs
