### ISSUE TITLE
SOCKS5 proxy support for geth

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#17686] opened 2018-09-17 14:38 UTC

**Comment by peer2peer** [comment] 2018-09-28 15:28
Any solutions or workaround? 
My peer cannot access Internet directly but only can via a socks5 proxy.
Now I run a Geth node and add one peer of another existing ethereum node on Internet by addPeer, how to make it work?

**Comment by SjonHortensius** [comment] 2019-11-30 12:58
this is a duplicate of #1855

**Comment by tantrev** [comment] 2021-07-27 22:47
This would be super useful for adding [Nym](https://nymtech.net/) support to Geth.

**Comment by htjain** [comment] 2022-11-30 09:50
+1

**Comment by holiman** [comment] 2023-02-21 08:59
Duplicate of https://github.com/ethereum/go-ethereum/issues/1855

**Closed by holiman** 2023-02-21 08:59 UTC
Labels: type:feature
