### ISSUE TITLE
Issue with parsing arguments and/or environment variables

### ISSUE THREAD

**Issue by thevops** [ethereum/go-ethereum#28210] opened 2023-09-27 14:13 UTC
#### System information

Geth version: `v1.13.1`
CL client & version: prysm@v4.0.8
OS & Version: Linux
Environment: Kubernetes v1.26 (GKE)

#### Expected behaviour

I'm trying to upgrade Geth **v1.12.0** to **v1.13.1** without any changes.
I expected well working Geth as usual.

#### Actual behaviour

Geth is running in a private Kubernetes cluster. It is exposed using a NAT gateway.
It is configured using CLI arguments (works with v1.12.0):
```
"--authrpc.addr=0.0.0.0"
"--authrpc.jwtsecret=/mnt/secret/jwt.hex"
"--authrpc.port=8551"
"--authrpc.vhosts=*"
"--datadir=/mnt/data"
"--datadir.ancient=/mnt/ancient"
"--discovery.port=7306"
"--http"
"--http.addr=0.0.0.0"
"--http.api=eth,net,web3,personal"
"--http.corsdomain=*"
"--http.port=8545"
"--http.vhosts=*"
"--log.format=json"
"--mainnet"
"--metrics"
"--metrics.addr=0.0.0.0"
"--metrics.expensive"
"--metrics.port=6060"
"--nat=extip:aa.bb.cc.dd"
"--port=7305"
"--syncmode=snap"
"--txlookuplimit=0"
"--ws"
"--ws.addr=0.0.0.0"
"--ws.api=eth,net,web3,personal"
"--ws.origins=*"
"--ws.port=8546"
```

After updating Docker image to **v1.13.1** I got:
```
Incorrect Usage: could not parse "tcp://10.0.0.201:6060" as int value from environment variable "GETH_PORT" for flag port: strconv.ParseInt: parsing "tcp://10.0.0.201:6060": invalid syntax
	
NAME:	
   geth - the go-ethereum command line interface	
	
USAGE:
   geth [global options] command [command options] [arguments...]

VERSION:
   1.13.1-stable-3f40e65c

COMMANDS:
   account                Manage account
   attach                 Start an interactive JavaScript environment (connect to node)
....
...
..
```
and Geth closes. Kubernetes restarts it and so on in a loop.

#### Steps to reproduce the behaviour

I tried to run Docker image locally with v1.12.0, stop it, and re-run it with v1.13.1, but looks good. Geth is starting and trying to sync (I don't have synced data on my local computer).
I can't provide any scenario for reproducing.

**Comment by jsvisa** [comment] 2023-09-27 14:41
> Incorrect Usage: could not parse "tcp://10.0.0.201:6060" as int value from environment variable "GETH_PORT" for flag port: strconv.ParseInt: parsing "tcp://10.0.0.201:6060": invalid syntax


Seems you have an environment of `GETH_PORT=tcp://10.0.0.201:6060`

**Comment by ojeffg** [comment] 2023-09-28 02:21
I am seeing a similar issue.  Changing nothing but the geth version from 1.12.2 to 1.13.1, my helm chart ci testing is failing.  I do not have any env vars set, but suddenly GETH_PORT is getting set as ip:authrpc.port for some reason.  Here is a snippet from the logs.  Are we supposed to explicitly set GETH_PORT now with this release?  

```
>>> kubectl --request-timeout=30s get pods --no-headers --namespace geth-8ecqidrl2r --selector  --output jsonpath={.items[*].metadata.name}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> Description of pod geth-0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>> kubectl --request-timeout=30s describe pod geth-0 --namespace geth-8ecqidrl2r
Name:         geth-0
Namespace:    geth-8ecqidrl2r
Priority:     0
Node:         chart-testing-control-plane/172.18.0.2
Start Time:   Tue, 26 Sep 2023 10:54:07 +0000
Labels:       app.kubernetes.io/instance=geth-8ecqidrl2r
              app.kubernetes.io/name=geth
              controller-revision-hash=geth-754744bff5
              statefulset.kubernetes.io/pod-name=geth-0
Annotations:  <none>
Status:       Running
IP:           10.244.0.6
IPs:
  IP:           10.244.0.6
Controlled By:  StatefulSet/geth
Containers:
  geth:
    Container ID:  containerd://9a927f69be26a46e35ddf1f5fa5f940cebbf[60](https://github.com/RnodeC/helm-charts/actions/runs/6311602841/job/17135918184#step:8:61)cd4e5fec7c2f30e2cfeea824cf
    Image:         ethereum/client-go:v1.13.1
    Image ID:      docker.io/ethereum/client-go@sha256:fce6fd010daeb8c1d3544dde599df7ab959cf2430bf6d1ebca74fd68f4dac75b
    Ports:         30303/TCP, 30303/UDP, 8551/TCP, 8545/TCP
    Host Ports:    0/TCP, 0/UDP, 0/TCP, 0/TCP
    Command:
      geth
    Args:
      --mainnet
      --datadir=/chaindata
      --discovery.port=30303
      --port=30303
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts=*
      --authrpc.jwtsecret=/etc/eth2/jwt
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.vhosts=*
      --ipcdisable
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 26 Sep 2023 11:00:07 +0000
      Finished:     Tue, 26 Sep 2023 11:00:07 +0000
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:        1
      memory:     2Gi
    Liveness:     tcp-socket :tcppeer delay=60s timeout=1s period=120s #success=1 #failure=3
    Readiness:    tcp-socket :tcppeer delay=10s timeout=1s period=10s #success=1 #failure=3
    Startup:      tcp-socket :tcppeer delay=120s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /chaindata from chaindata (rw)
      /etc/eth2 from jwt (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-x4lrk (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  chaindata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  chaindata-geth-0
    ReadOnly:   false
  jwt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  geth-jwt
    Optional:    false
  kube-api-access-x4lrk:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  9m52s                   default-scheduler  Successfully assigned geth-8ecqidrl2r/geth-0 to chart-testing-control-plane
  Normal   Pulling    9m52s                   kubelet            Pulling image "ethereum/client-go:v1.13.1"
  Normal   Pulled     9m49s                   kubelet            Successfully pulled image "ethereum/client-go:v1.13.1" in 2.626617331s (2.626632931s including waiting)
  Normal   Created    8m56s (x4 over 9m49s)   kubelet            Created container geth
  Normal   Started    8m56s (x4 over 9m49s)   kubelet            Started container geth
  Normal   Pulled     8m56s (x3 over 9m48s)   kubelet            Container image "ethereum/client-go:v1.13.1" already present on machine
  Warning  BackOff    4m41s (x33 over 9m47s)  kubelet            Back-off restarting failed container geth in pod geth-0_geth-8ecqidrl2r(6144e5bf-a23f-4d92-9f4d-19b2443f6f41)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<== Description of pod geth-0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>> kubectl --request-timeout=30s get pods geth-0 --no-headers --namespace geth-8ecqidrl2r --output jsonpath={.spec.initContainers[*].name}
>>> kubectl --request-timeout=30s get pods geth-0 --no-headers --namespace geth-8ecqidrl2r --output jsonpath={.spec.containers[*].name}
------------------------------------------------------------------------------------------------------------------------
==> Logs of container geth-0
------------------------------------------------------------------------------------------------------------------------
>>> kubectl --request-timeout=30s logs geth-0 --namespace geth-8ecqidrl2r --container geth
Incorrect Usage: could not parse "tcp://10.96.42.237:8551" as int value from environment variable "GETH_PORT" for flag port: strconv.ParseInt: parsing "tcp://10.96.42.237:8551": invalid syntax

NAME:
   geth - the go-ethereum command line interface

USAGE:
   geth [global options] command [command options] [arguments...]

VERSION:
   1.13.1-stable-3f40ec

COMMANDS:
   account                Manage accounts 
   .......
```

**Comment by jsvisa** [comment] 2023-09-28 04:24
@ojeffg seems this is the same issue. BTW, which helm chart are you using, maybe they set the default environment of `GETH_PORT`

**Comment by jsvisa** [comment] 2023-09-28 04:36
> @ojeffg seems this is the same issue. BTW, which helm chart are you using, maybe they set the default environment of `GETH_PORT`

I found it, it's from https://github.com/RnodeC/helm-charts/actions/runs/6311602841/job/17135918464?pr=25

I don't know why helm/k8s/... will automatically set some environments.

**Comment by thevops** [comment] 2023-09-28 07:23
> > Incorrect Usage: could not parse "tcp://10.0.0.201:6060" as int value from environment variable "GETH_PORT" for flag port: strconv.ParseInt: parsing "tcp://10.0.0.201:6060": invalid syntax
> 
> Seems you have an environment of `GETH_PORT=tcp://10.0.0.201:6060`

I don't have any environment variables.
Anyway, I'm using `--port=7305`, so if GETH_PORT is required I should set it to `7305` not `6060` (which is for metric in my setup: `--metrics.port=6060`)

**Comment by holiman** [comment] 2023-09-28 07:46
> I don't have any environment variables.

For some reason, geth detects that you indeed do. 

> Anyway, I'm using --port=7305, so if GETH_PORT is required I should set it to 7305 not 6060 (which is for metric in my setup: --metrics.port=6060)

Using `--port=7305`, that should definitely override the env variable. That is very odd

**Comment by holiman** [comment] 2023-09-28 07:54
```
[user@work ~]$ GETH_PORT="NOT AN INT" geth --dev --port=12313 1>/dev/null
could not parse "NOT AN INT" as int value from environment variable "GETH_PORT" for flag port: strconv.ParseInt: parsing "NOT AN INT": invalid syntax

```
So, `--port` does take precedence, but even before the whole precedence-decision comes into it, the library tries to parse the flags, and errors on not being able to parse the env-flag as an integer. This is a bit unfortunate, since it means that env-flag cannot be _fully_ overridden (as in ignored) by command line flags.

**Comment by thevops** [comment] 2023-09-28 08:05
Hmm, maybe it is connected with the fact that Kubernetes sets some environment variables for internal use.
Everyone who has K8s, let's try `env |grep -i geth` inside container.

Kubernetes sets environment variables using the name of the Pod. In my case it's for example `geth-2`, so I have multiple such envs:
```
GETH_2_PORT_7305_TCP_ADDR=10.0.0.54
GETH_2_PORT_6060_TCP_PORT=6060
GETH_2_SERVICE_PORT_WS=8546
GETH_2_SERVICE_HOST=10.0.0.54
GETH_2_PORT_6060_TCP_PROTO=tcp
GETH_2_PORT_7305_TCP_PORT=7305
GETH_2_PORT_7306_UDP_ADDR=10.0.0.54
HOSTNAME=geth-2-0
GETH_PORT_6060_TCP=tcp://10.0.0.201:6060
...
```

**Comment by thevops** [comment] 2023-09-28 08:14
Yep, this is it.

I copied all env variables from my container with Geth v1.12.0 and I tried to load them locally in Docker, but using Geth v1.13.1 and got the same error:
```
Incorrect Usage: could not parse "tcp://10.0.0.201:6060" as int value from environment variable "GETH_PORT" for flag port: strconv.ParseInt: parsing "tcp://10.0.0.201:6060": invalid syntax
```

**Comment by holiman** [comment] 2023-09-28 08:16
```
$ GETH_PORT_LALA="NOT AN INT" geth --dev --port=12313 1>/dev/null
```
A flag named `GETH_PORT_XX..` should not matter, only the exact `GETH_PORT` env var.

**Comment by thevops** [comment] 2023-09-28 08:19
Yes, but:

If you deploy Geth in Kubernetes in a container named `geth` and you expose some ports, then Kubernetes creates some environment variables. 
The first exposed port will make the environment variable `GETH_PORT`. In my case, it's `GETH_PORT=tcp://10.0.0.201:6060`, because the first exposed port in my Kubernetes manifest is the port for metrics.

**Comment by karalabe** [comment] 2023-09-28 09:20
This clash is a bit unfortunate. I'm unsure what the best solution here is. The simplest way is to not have a Kubernetes container named geth, but I do understand that it's annoying to have special forbidden keywords.

**Comment by thevops** [comment] 2023-09-28 12:28
A solution can be disabling `enableServiceLinks: false` in Pod spec:
https://kubernetes.io/docs/tutorials/services/connect-applications-service/#environment-variables

**Comment by ojeffg** [comment] 2023-09-28 12:59
Confirming that @thevops solution works in my k8s environment.

**Comment by SeaMonkey82** [comment] 2023-10-06 01:11
This seems related.

If I attempt to run geth with 

`./go-ethereum/build/bin/geth --datadir /mnt/holesky/prysm-geth --http --http.port 8546 --http.api="engine,eth,web3,net,debug" --http.corsdomain "*" --holesky --syncmode=snap --authrpc.jwtsecret=/mnt/holesky/jwtsecret console --nat=extip:1.2.3.4 --port 23493 --authrpc.port 8557 --maxpeers 25 --state.scheme=path --metrics --metrics.port 6070`

it returns
```
Incorrect Usage: flag provided but not defined: -metrics
```

But if I move the `--metrics --metrics.port 6070` to the beginning of the flags

`./go-ethereum/build/bin/geth --metrics --metrics.port 6070 --datadir /mnt/holesky/prysm-geth --http --http.port 8546 --http.api="engine,eth,web3,net,debug" --http.corsdomain "*" --holesky --syncmode=snap --authrpc.jwtsecret=/mnt/holesky/jwtsecret console --nat=extip:1.2.3.4 --port 23493 --authrpc.port 8557 --maxpeers 25 --state.scheme=path`

it works fine.

**Comment by karalabe** [comment] 2023-10-06 05:02
@SeaMonkey82 Leave the `console` to the end. The flags in geth are meant to be set on the main command, not the subcommands. We made some flags work after the subcommands too where we felt that's the natural way to specify them, but in this specific case, the metrics flag isn't for the console, it's for geth.

**Comment by holiman** [comment] 2023-11-10 06:54
Closing this: the root cause for this to happen is described/tracked in https://github.com/ethereum/go-ethereum/issues/28216 .

**Closed by holiman** 2023-11-10 06:54 UTC
Labels: type:bug
