### ISSUE TITLE
after sendTransaction, immediate tx error: Known transaction

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1238] opened 2015-06-11 00:02 UTC
develop 979ebfc

I send a tx (gasprice0 or 1 if it matters) and it is confusing that immediately I get a number of ``tx error: Known transaction``
If it's not an issue, can the logging be improved, or behavior improved (example: if I broadcast a transaction, why do peers send the transaction back at me?)

(#662 may be related)

```
I0610 15:50:28.334384   14749 api.go:38] eth_sendTransaction [{"from": "0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826", "gas": "0xdbba0", "value": "0x0", "to": "0x4fcd57b507a237409e5a7bb2a244dd5206441642", "data": "0x13f955e1000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000190030000003322227c767e9ff193d252614dca8723c30febb9543ea607db923f04000000000b879651dcd41929b1533e31e4926fd7e5ce865b19510127ab6f1d36986303093c3e7655003e3b1cff90a65f03000000328f2c6bfd55db2f7678e0cb03db5fd8cfc047f6e7e2bb2ef917b30a000000003ebb117f1a60eca36ce8c8569295cd959565035ee9e2c4170931b7f6aa3e46f43d3e7655003e3b1c200b9f180300000008b592e93c97f3e59681b63a26cdcb587c155966880b4bb54ebeb4150000000064846efd5d82035902e0085d514fa216a9c27a79b0cfc3082ff97933ff5c14333c3e7655003e3b1ca623192803000000848466531799b9a5783f9f249d4354cae7ee28e1df3f43ddca02de3700000000a0ec652acf5cd0a51f7511b652fe2bf80ee10e963155650f209f908f6db0b755483e7655003e3b1c09885e1503000000786f534bf4e6a5cdf8d4e78360ad9eb533c400b0024ab0069b81fd270000000063f217a1995ddd8edd34ebc87062041fc18c64acf233a0a6f133ffb38d2ba0743d3e7655003e3b1c0ce6f29100000000000000000000000000000000", "gasPrice": "0x0"}]
I0610 15:50:28.337300   14749 transaction_pool.go:198] (t) 6364326133643966 => 4fcd57b5 (0x6aadf0) a38496bb348110fa0c3db6176deb4b1b51c2f976d3edcd74e5c9994f7710f13a
I0610 15:50:28.337739   14749 xeth.go:968] Tx(a38496bb348110fa0c3db6176deb4b1b51c2f976d3edcd74e5c9994f7710f13a) to: &4fcd57b507a237409e5a7bb2a244dd5206441642
I0610 15:50:28.337821   14749 http.go:149] Generated response: *rpc.RpcSuccessResponse &{0a2f8923-1552-4ff3-8b34-197ddcccfc9f 2.0 0xa38496bb348110fa0c3db6176deb4b1b51c2f976d3edcd74e5c9994f7710f13a}
I0610 15:50:28.337876   14749 http.go:160] Sending payload: {
	"id": "0a2f8923-1552-4ff3-8b34-197ddcccfc9f",
	"jsonrpc": "2.0",
	"result": "0xa38496bb348110fa0c3db6176deb4b1b51c2f976d3edcd74e5c9994f7710f13a"
}
I0610 15:50:28.386562   14749 transaction_pool.go:246] tx error: Known transaction (a38496bb)
I0610 15:50:28.450473   14749 transaction_pool.go:246] tx error: Known transaction (a38496bb)
I0610 15:50:28.524978   14749 transaction_pool.go:246] tx error: Known transaction (a38496bb)
I0610 15:50:28.575666   14749 transaction_pool.go:246] tx error: Known transaction (a38496bb)
I0610 15:50:28.581043   14749 transaction_pool.go:246] tx error: Known transaction (a38496bb)
I0610 15:50:28.780199   14749 transaction_pool.go:246] tx error: Known transaction (a38496bb)
```

**Comment by obscuren** [comment] 2015-06-11 08:37
I'm not entirely convinced you were on develop. Please try again and make sure you actually have latest

**Comment by obscuren** [comment] 2015-06-11 08:38
verify using `geth version`

**Comment by ethers** [comment] 2015-06-11 09:08
Here's the trace when I started Geth and it was 10 mins before the sendtx and tx errors:
```
I0610 15:40:33.241236   14749 backend.go:256] Protocol Version: 60, Network Id: 0
I0610 15:40:33.241503   14749 backend.go:266] Blockchain DB Version: 3
I0610 15:40:33.266961   14749 chain_manager.go:252] Last block (#564753) fe57eb10844ef8f6faaf40da31a3584958fb46a7b97c86fe7fbcd6e1d05310c5 TD=3436934181233792
I0610 15:40:43.161060   14749 cmd.go:148] Starting Geth/v0.9.29/linux/go1.4.2
I0610 15:40:43.161380   14749 server.go:293] Starting Server
I0610 15:40:43.831107   14749 udp.go:189] Listening, enode://c00c237f596543c7107a2a6f7683c823c3ba4b7852358c4a5c80f17511d8b40103f4c1b4091df11af079c2bd8fc959d794ef772a49ad883010867d7d4557a119@[::]:30304
I0610 15:40:43.831325   14749 backend.go:475] Server started
I0610 15:40:43.831304   14749 server.go:530] Listening on [::]:30304
```

geth version output:
```
Geth
Version: 0.9.29
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2
OS: linux
```

**Comment by veox** [comment] 2015-06-12 10:07
@ethers are you using a nightly build, a PPA package, or something like that? If you build straight from git, the version output includes a git commit line:

```
Geth
Version: 0.9.29
Git Commit: 4bb9a61049882f427e2742773c69b969849da1c2
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2
OS: linux
GOPATH=/home/user/go
GOROOT=/usr/lib/go
```

**Comment by ethers** [comment] 2015-06-12 17:54
@veox i was previously using godep to build straight from git, in case that was the cause.  I just switched to using ``make geth`` yesterday and now I do see the git commit line:

```
Git Commit: 6f5c6150b7060b6b2ee68ac95b30f46c5c2c7f90
```

**Comment by ethers** [comment] 2015-06-12 20:47
on Geth
Version: 0.9.29
Git Commit: 6f5c6150b7060b6b2ee68ac95b30f46c5c2c7f90
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2

still seeing:

```
I0612 13:44:57.910794   31517 api.go:38] eth_sendTransaction [{"value":"0x2f2f39fc6c540000","from":"0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826","gas":"0x7a120","to":"0x9fec21cff232687e6105b1a95f1cee47c493a5b1","data":"0x66f7e56c000000000000000000000000a0dc485fc3ade71be5e1b68397abded386c0adb70000000000000000000000000000000000000000000000002f2f39fc6c540000000000000000000000000000000000000000000000000000000012309ce54000"}]
I0612 13:44:57.943566   31517 transaction_pool.go:198] (t) 6364326133643966 => 9fec21cf (0x6a8b40) 3773184bf7f6c70002ed9653f244e27b45823fc6c9b6cfab2995e8ed0756460b
I0612 13:44:57.973048   31517 xeth.go:968] Tx(3773184bf7f6c70002ed9653f244e27b45823fc6c9b6cfab2995e8ed0756460b) to: &9fec21cff232687e6105b1a95f1cee47c493a5b1
I0612 13:44:57.973207   31517 http.go:149] Generated response: *rpc.RpcSuccessResponse &{%!s(float64=6) 2.0 0x3773184bf7f6c70002ed9653f244e27b45823fc6c9b6cfab2995e8ed0756460b}
I0612 13:44:57.973311   31517 http.go:160] Sending payload: {
	"id": 6,
	"jsonrpc": "2.0",
	"result": "0x3773184bf7f6c70002ed9653f244e27b45823fc6c9b6cfab2995e8ed0756460b"
}
I0612 13:44:58.075040   31517 transaction_pool.go:246] tx error: Known transaction (3773184b)
I0612 13:44:58.081610   31517 transaction_pool.go:246] tx error: Known transaction (3773184b)
I0612 13:44:58.152608   31517 transaction_pool.go:246] tx error: Known transaction (3773184b)
I0612 13:44:58.158986   31517 transaction_pool.go:246] tx error: Known transaction (3773184b)
```

**Comment by fjl** [comment] 2015-07-06 14:37
Duplicate of #662.

**Closed by fjl** 2015-07-06 14:37 UTC
