### ISSUE TITLE
SWARM: Common storage for multiple chains proposal.

### ISSUE THREAD

**Issue by Dexaran** [ethereum/go-ethereum#14891] opened 2017-08-03 13:10 UTC
# Abstract

I know that there are different chains that are using Ethereum protocol (The most known is ETC. UBQ and Expanse are Ethereum forks as well.) It means that it is possible to run SWARM with side chain nodes.

# Proposal

To be honest, I don't see any reason in running a separate version of the whole SWARM for each Ethereum chain branch (fork). All users can use the same addresses on all Ethereum chains. It would be great if SWARM nodes could use common storage (sync with each other) but have different incentivisation system.

It would be possible to run nodes that will operate with multiple chains (this nodes should accept payments in different currencies). If a SWARM node is running in `-classic` mode then an owner of this node will receive payments in ETH for providing a data that is paid with ETH. The owner of this node will also receive payments in ETC for providing a data that is paid with ETC. Fortunately the owner of the node can use the same hex address for all types of payments.

If the node only works in ETH mode, then it will lose the ability to receive payments in ETC to store data that will be paid by ETC.

If someone wants to upload data to SWARM then this person can choose what currency would be used. A SWARM node with matching currency support and closest address would be chosen to accept data.

**It is important to allow SWARM nodes to operate with multiple currencies at once.**

# Motivation

I think that everyone will benefit from this proposal. There is no real need to have multiple versions of exactly the same software running on different chains.

### SWARM adoption
The adoption of SWARM depends on how much it will be used. Ethereum CLassic community is 10% of the whole Ethereum community. Supporting ETC payments will instantly boost the adoption of the whole SWARM ecosystem by 10%.

### Immediately eliminate the competitor
If SWARM would be used only with the ETH network, it will only be a matter of time when SWARM CLassic would appear. This variant is not beneficial for the whole cryptocurrency community and users. It is not a good idea to have two copies of the SWARM for each chain.
I guess it's much better to merge the Ethereum community by one common storage. It will also instantly eliminate a possibility of competition between two different ecosystems.

### User friendly
If you accept several currencies as payment for a service, this is obviously more convenient than only one currency anyways.

**Comment by chrisfranko** [comment] 2017-08-23 12:29
Completely agree, we have been merging all the swarm stuff in lately with EXP and I thought the same thing.

**Comment by VoR0220** [comment] 2017-09-05 18:41
Can we make a duplicate of this issue for ENS as well? I think the sentiment applies just as equally to there. What say you @Arachnid ?

**Comment by Dexaran** [comment] 2017-09-05 18:45
@VoR0220 we can discuss crosschain ENS implementation here: https://github.com/Dexaran/ICO/issues/28

We are currently working on it.

**Comment by yaronvel** [comment] 2017-09-06 05:17
>All users can use the same addresses on all Ethereum chains.

Lost you there. It is much better not to use the same address in multiple chains.

**Comment by Dexaran** [comment] 2017-09-06 06:25
@yaronvel why not? What are your reasons to avoid using the same address in multiple chains?

**Comment by yaronvel** [comment] 2017-09-06 06:27
Replay attack.

**Comment by Dexaran** [comment] 2017-09-06 06:29
I've been using the same address in the ETH and ETC networks for a long time, and I was not hurt by replay attacks.
I think that it is time for user education.
We should tell users what the addresses are, how they work and how they can use the same address on multiple chains.

**Comment by yaronvel** [comment] 2017-09-06 06:35
1. ETH has some protection. But i am not sure about EXP and alike. I am pretty sure there is also no protection in ETC. Reason you were not replayed is mainly because the attack is not profitable most of the time. But also because you would have to hack parity code to perform it.

2. User education is important. But at least i dont assume thet are at this point. Some still send real eth to testnet addresses by mistake...

**Comment by Dexaran** [comment] 2017-09-06 07:03
> Some still send real eth to testnet addresses by mistake...

User education will solve this problem. They will know that it's not a problem if you send ETH into testnet address because you (or the person to whom you sent the transaction) can control testnet address on ETH mainnet. As the result you can access your funds in the testnet address and there is no danger of losing money.

It's not the key point of this proposal. At least it is potentially possible between ETH and ETC.
From the ideological point of view, it's better to have one storage instead of implementing SWARM for each of the Ethereum-based chains, I believe. This seems to be better solution for the entire crypto-currency ecosystem.

**Comment by yaronvel** [comment] 2017-09-06 07:03
On second read, why do you even require users to have the same address? Different logic will be needed anyway (at mininum, different prices).

**Comment by Dexaran** [comment] 2017-09-06 07:06
As I've said earlier, using the same addresses on multiple chains is not the key point here.

**Comment by chrisfranko** [comment] 2017-09-06 10:54
EXP has the same protections as eth and eth

**Comment by VoR0220** [comment] 2017-09-06 22:11
@yaronvel Chain IDs solve replay attacks. I believe Parity implements these.

**Comment by homotopycolimit** [comment] 2018-08-08 18:19
The SWAP protocol is strictly between two connected peers. They can settle their debts as they see fit using whatever chain they want.
This is also mentioned here: https://github.com/ethersphere/go-ethereum/issues/219#issuecomment-384689423

Long term storage incentives could be more difficult to manage as would things like proof-of-burn spam protections for which every node in the network would have to be able to validate the proof and thus be connected to the same chain.

 I suggest we move this discussion over to ethersphere where the Swap protocol is currently being (re)implemented. https://github.com/ethersphere/go-ethereum/labels/swap

**Closed by homotopycolimit** 2018-08-08 18:19 UTC
Labels: feature, swarm
