### ISSUE TITLE
Android Light client fails to connect private network

### ISSUE THREAD

**Issue by sumanxp** [ethereum/go-ethereum#3789] opened 2017-03-17 08:30 UTC
#### System information

Geth version: `geth 1.5.8`
OS & Version: Android
Commit hash : (if `develop`)

#### Expected behaviour

Android light client should connect private network
#### Actual behaviour

Not able to connect private network 
#### Steps to reproduce the behaviour
STEP 1: Set-up one private network and run one node as light server passing "--lightserv 25 --lightpeers 3" in geth as ETHEREUM OPTIONS
genesis I tried with 
a) 
```
{
    "nonce": "0x0000000000000042",
    "timestamp": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x0",
    "gasLimit": "0x8000000",
    "difficulty": "0x400",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "alloc": {
    }
}
```
b)
```
{
    "config": {
        "chainId": 7,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 10,
        "eip158Block": 10,
        "eip160Block": 10
    }
}
```

```
geth --datadir lightserver init genesis.json
geth --datadir lightserver --networkid 999 --port 31113 --identity lightnode --lightserv 25 --lightpeers 10 --verbosity 6 --rpc --rpcapi "eth,web3,net,admin" --rpcport 8545 --rpcaddr "0.0.0.0" --rpccorsdomain "*" --nodiscover console
```
STEP2: Configure the Android App to connect private network
``` code
        NodeConfig config = new NodeConfig();
        Enodes nodes = new Enodes(1);
        nodes.set(0, Geth.newEnode("<enode of the lightserver>"));
        config.setBootstrapNodes(nodes);
        config.setEthereumGenesis("<same genesis used in private network>");
        ChainConfig chainConfig = new ChainConfig();
        chainConfig.setEIP155Block(10);
        chainConfig.setEIP158Block(10);
        chainConfig.setChainID(PRIVATE_NETWORK_ID);//999
        config.setEthereumChainConfig(chainConfig);
        config.setEthereumNetworkID(PRIVATE_NETWORK_ID);//999
        config.setMaxPeers(25);
```
#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment] 2017-03-18 00:35
@zsfelfoldi Please look into this when you have time. It should be reproducible without a phone.

**Comment by sumanxp** [comment] 2017-03-29 14:13
@zsfelfoldi Did you get any chance to look into it?

**Comment by MondyWins** [comment] 2017-04-10 09:49
Hello Ethereum developers,

My name is Subhajit Mandal. I am a Director of Innovation at MetLife Innovation Centre, Singapore. Sekhar and his team are working with us on our project "insurechain". As far as I know, MetLife is the only Life Insurance company exploring the possibility of putting the DLT into customers' phones.
Any help will be highly appreciated. A successful project from a Fortune 50 company will get a lot of attention and prove value in the business case of B2C Insurance. 

I am ready with an insurance product to launch. All I am waiting is for the protocol to work!

Please assist. Thanks.

**Comment by berlinerwander** [comment] 2017-04-28 03:47
Hello @zsfelfoldi @fjl  are you that busy that you cannot reply to us? I am researching the same thing and i found the same bug! How long is the default timeout, why is it so low

**Comment by berlinerwander** [comment] 2017-05-03 03:36
@karalabe will your latest geth 1.6 resolve this issue?

**Comment by berlinerwander** [comment] 2017-05-03 03:39
@sumanxp please try ****upgrading to geth 1.6** and the config checklist is followed below  https://github.com/ethereum/go-ethereum/issues/3510 

-disabling topic discovery (--nodiscover) on both sides (light client and main node)
-add the main node manually with admin.addPeer('enode://...') on the light client side.
-both sides had the same genesis block.

**Comment by sekharkumarroy** [comment] 2017-05-03 05:15
@berlinerwander Issue is between Andriod light client with a light server. CLI version works well even in earlier releases(e.g 1.5.9). Are you experimenting with Android light client ?

**Comment by berlinerwander** [comment] 2017-05-10 02:35
@sekharkumarroy Yes experimenting. I just wanted to check there are no breaks when geth goes to 1.6 anyway

In #3510 you said '...facing challenges when connecting from an android device to a private light server using the android package (geth.aar). I'm doing experiment in an internet facing AWS server and all the required ports open. .'  

What is the result of your experiment? 

Does the problem lie within the design constraints https://blog.ethereum.org/2017/01/07/introduction-light-client-dapp-developers/

**Comment by gmerlino** [comment] 2017-06-01 10:36
Hello, we are trying to have a working Android light client node connecting to a private chain, but the problem is we cannot find a way to "add a peer" (no addPeer method available), in order to add the light server from the client (Android) side.

We are looking for that, as it seems this is the only way to do it (also when we try it out on test containers): the bootnodes switch seems to be useless (ignored).

**Comment by treste91** [comment] 2017-06-20 13:16
Same problem here! I can connect to 'ropsten' but not to private network lightserver! 
Any help would be appreciated..

**Comment by nmanchov** [comment] 2017-07-14 11:37
Any update on this one? Has anyone found a solution for this issue? I can see only ping messages in the log and it never trigers a sync.

**Comment by jellelicht** [comment] 2017-07-25 12:08
We are also having the same issue, any idea how to debug this issue?

**Comment by kelsos** [comment] 2017-07-25 14:21
@gmerlino You can supply a [static-nodes.json](https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network#static-nodes) on the android client this will work the same way as the addPeer method.

If you your data directory in android is something like ```"$filesDir/.ethereum"``` then the static-nodes.json must be under the ```$filesDir/.ethereum/GethDroid/static-nodes.json``` in order to get picked. I had some issues syncing with the Android with Ropsten and after adding the ```static-nodes.json``` with the peers it started syncing properly.

**Comment by DHOscar** [comment] 2017-08-13 20:09
@kelsos I am working on the iOS framework right now. Does your suggestion also work on iOS side?
 As so far I could not find any methods related to static-nodes.json.

**Comment by kelsos** [comment] 2017-08-16 15:59
@DHOscar I am not sure how the iOS counterpart works to be honest. There should not be any methods related. Since the mobile frameworks don't support the addPeer method, adding the static-nodes.json can be used as an alternative approach to supply the list of peers. You should check where the internal structure of the files and find where the GethDroid equivalent folder is in iOS.

**Comment by DHOscar** [comment] 2017-08-17 07:47
@kelsos Thx for the reply. Yes indeed as you said. I already checked file structure and there is a folder call iGeth which should be similar like GethDroid. The full path is `$filesDir/ethereum/iGeth`

**Comment by cat-cat** [comment] 2018-01-05 23:41
Was the problem solved? iOS and Android both cannot sync with the private blockchain. Checked with geth mobile 1.7.3

**Comment by cat-cat** [comment] 2018-01-09 12:17
still doesn't sync with geth mobile libraries 1.8

**Comment by ligi** [comment] 2019-02-28 22:30
OK will look into the issue.
I synced public chains with android with no problem.
Never used it with private chains and have to start quoting Bruce Schneier:

> Private blockchains are completely uninteresting. 

https://www.schneier.com/blog/archives/2019/02/blockchain_and_.html

That said - it should still work. Looking in the initial issue I see chainID 7 in the genesis and chainID 999 in the command line parameters.
If others face the same problem - the following things help:
 - full private chain configuration/setup
 - log output with high verbosity

**Comment by ligi** [comment] 2019-04-02 08:53
closing for now - please reopen when you have a problem like this and then please submit your config and log

**Closed by ligi** 2019-04-02 08:53 UTC
Labels: status:triage
