### ISSUE TITLE
Can not get the block

### ISSUE THREAD

**Issue by gasparyanyur** [ethereum/go-ethereum#18005] opened 2018-10-30 15:29 UTC
Hi there,
I want to get all transactions by block.

#### System information
Geth version: ` 1.8.17-stable`
OS & Version: `Ubuntu 18`

#### Expected behaviour
I want to get transaction by block .

#### Actual behaviour
everything returns null

#### Steps to reproduce the behaviour
To open console .`geth --testnet --syncmode "fast" --verbosity "0" console`

To get block `eth.getBlock(4332379)`

#### Backtrace

````
vagrant@homestead:~$ geth --testnet --syncmode "fast" --verbosity "0" console
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.17-stable-8bbe7207/linux-amd64/go1.10.1
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.getBlock(4332379)
null
> eth.getTransactionFromBlock(4332379)
null
>


````

**Comment by MartinDawson** [comment] 2018-11-12 22:17
Geth version: 1.8.17-stable
OS & Version: Ubuntu 18

I couldn't reproduce:

```
> eth.getBlock(4332379)
eth.getBlock(4332379)
{
  difficulty: 14156231664,
  extraData: "0x4246494720506f6f6c",
  gasLimit: 8000000,
  gasUsed: 7996662,
  hash: "0xb645e32207b2a3c1995db400bc197acadcd37bada32e6a826ed9f0384d301171",
  logsBloom: "0x..0",
  transactionsRoot: "0x60e4d94551fd5debaab2f402f92422af9d537497340fd984adb9f48b7a7c2999",
  uncles: ["0xfa2d777d35c4abe36e24705713717728c8c107a50c01005f8495a345a5b5d231"]
}

> eth.getTransactionFromBlock(4332379)
{
  blockHash: "0xb645e32207b2a3c1995db400bc197acadcd37bada32e6a826ed9f0384d301171",
  blockNumber: 4332379,
  from: "0x931faa9fb7cb67e0f9bedcc0621e2528b995b95a",
  gas: 163408,
  gasPrice: 2000000000000,
  hash: "0x58fe0fda21c2be5f3d39d4bdc6134234fb3d7a8138b2eddb8aff1b51b7a20661",
  input: "0xe7d3fe6b000000000000000000000000000000000000000000000000001240763cb360dd0000000000000000000000000000000000000000000000000000000000000003000000000000000000000000931faa9fb7cb67e0f9bedcc0621e2528b995b95a",
  nonce: 74790,
  r: "0xf0fc8b2d27346ee144d77c5db454a83d5a2052fe55842fa6f443687807797d41",
  s: "0x42b086fdf94fa0815df4900d4fc3ca4aa6393e63aa2542a8689e2f6a792841c",
  to: "0x103262f243e6f67d12d6a4ea0d45302c1fa4bb0a",
  transactionIndex: 0,
  v: "0x1b",
  value: 0
}
```

Are you sure that you have synced to the latest block, if you remove the --verbosity flag what is the latest block that you can see be outputted to the console?

**Comment by KursLabIgor** [comment] 2018-12-28 12:42
@MartinDawson i have a bit another problem
eth.getBlock(1000)
{
  difficulty: 5,
  extraData: "0x322e312e322f6c696e75782d616d6436342f676f312e31302e32000000000000",
  gasLimit: 210284448,
  gasUsed: 0,
  hash: "0x466ecb3ea37384ab82465c320add5bf40766e5751e4dfe4968331b0e46d205c5",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x3729d2e93e8037f87a2c9afe34cb84b7069e4dea",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 1000,
  parentHash: "0x3760455ec09a8c0ac6aa885cc843a43fd635304cec2583edf8007a9934f35615",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  signer: "0x78d5bfe08827b6b6ef7a623982011e307aa6aabaf1245b8aa508b0327dfadb690dfc0cee0fb357083f2e5821228fb9a8ce6aa15fd3f003345b02bb0dbfb8859b00",
  signers: [],
  size: 612,
  stateRoot: "0x0c3a92c84fd29ce5892f25dca3532619f3c16e576011e7ecba22564e39e78b32",
  timestamp: 1526438938,
  totalDifficulty: 4952,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: [],
  voters: []
}
eth.getTransactionFromBlock(1000)
null

i run 
./gochain --rpc --ws --wsorigins "*" --rpcapi eth,net,web3,debug --wsapi eth,net,web3,debug --syncmode "full" --datadir /mnt/sdb/mainnet/node --gcmode "archive"

**Comment by KursLabIgor** [comment] 2019-01-02 09:48
Any ideas ?

**Comment by holiman** [comment] 2019-12-12 11:13
@gasparyanyur I suspect your node was not fully synced. That block was mined `Oct-30-2018 03:01:32 PM +UTC`, the same day you opened the ticket. If you had provided `eth.getBlock("latest")` then it would be possible to say -- too late now :( (yeah, sorry about not responding earlier). 

As for @KursLabIgor , the block says `transactions: [],` -- and when you ask about the transactions you get nothing back. I don't see what you think is wrong? 
Also, you're using some off-brand code, we don't maintain `gochain`, and `difficulty` cannot ever be `5`: ethash has minimum `0x20000` on every block, and clique has `1` or `2` on every block. Closing this

**Closed by holiman** 2019-12-12 11:13 UTC
Labels: status:triage
