### ISSUE TITLE
debug_traceTransaction JavaScript-based tracing - TypeError

### ISSUE THREAD

**Issue by r001** [ethereum/go-ethereum#3382] opened 2016-11-30 01:22 UTC
#### System information

Geth version: 1.5.4-stable-b70acf3c
OS & Version: Linux

#### Expected behaviour
db.getBalance(log.account)  should return balance of account specified by log.account

#### Actual behaviour

returns the following error:
TypeError: can't convert from "GoArray" to "common.Address"

#### Steps to reproduce the behaviour
```
debug.traceTransaction("0xd2fb643810707f906ae7703f28246733f8175ab9d37a7d9cc9ad8e2ca19a5fa0", {tracer: '{data: [], step: function(log,db) { this.data.push(db.getBalance(log.account)); }, result: function() { return this.data; }}'});
```

**Comment by xuhcc** [comment] 2017-08-31 05:25
Problem still exists in Geth 1.6.7. Any update on this?

**Comment by riktimmondal** [comment] 2017-08-31 07:03
I am a beginner,can you guide me on this?

**Comment by holiman** [comment] 2017-08-31 09:56
Confirmed: 
``` 
> debug.traceTransaction("0x3fb08d7e713a6a17b504be01fa59f37f326828b083856ad03017ce4ad82d9d63", {tracer: '{data: [], step: function(log,db) { if(log.pc==0){this.data = db.getBalance(log.account) }}, result: function() { return this.data; }}'});
Error: TypeError: can't convert from "GoArray" to "common.Address"
    at <native code>
    at <anonymous>:1:64
    in server-side tracer function 'step'
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
```
The wrapper here expects a `common.Address` : https://github.com/ethereum/go-ethereum/blob/3c48a25762dfab9382791c33a2f5832466077ac3/internal/ethapi/tracer.go#L134 . @Arachnid  PTAL  ?

**Comment by tet32** [comment] 2017-10-06 17:35
Any update on this? Is there a way around this problem?

**Comment by Arachnid** [comment] 2017-11-13 13:53
You need to call `.String()` on the return value of `.getBalance()`

**Comment by tet32** [comment] 2017-11-13 15:26
@Arachnid 
On ropsten
```
debug.traceTransaction("0x3d41102b8a1d6cde7b351f4559eb66734cc19117fa3b89b96b0d9c705f7db6c1", {tracer: '{data: [], step: function(log,db) { if(log.pc==0){this.data = db.getBalance(log.account.toString()) }}, result: function() { return this.data; }}'});
```
I receive error
```
Error: TypeError: can't convert from "string" to "common.Address"
    at <native code>
    at <anonymous>:1:64
    in server-side tracer function 'step'
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

**Comment by Arachnid** [comment] 2017-11-13 15:32
`String` applies to the balance - the outer call - not the inner call.

**Comment by tet32** [comment] 2017-11-13 15:35
@Arachnid 
But there is a problem with the type of the argument on the GetBalance method, not that it returns getBalance

```
> debug.traceTransaction("0x3d41102b8a1d6cde7b351f4559eb66734cc19117fa3b89b96b0d9c705f7db6c1", {tracer: '{data: [], step: function(log,db) { if(log.pc==0){this.data = db.getBalance(log.account).toString() }}, result: function() { return this.data; }}'});
Error: TypeError: can't convert from "GoArray" to "common.Address"
    at <native code>
    at <anonymous>:1:64
    in server-side tracer function 'step'
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

```

**Comment by tet32** [comment] 2017-11-13 15:37
https://github.com/ethereum/go-ethereum/blob/3c48a25762dfab9382791c33a2f5832466077ac3/internal/ethapi/tracer.go#L133
`getBalance` wait `addr` as `common.Address`

**Comment by Arachnid** [comment] 2017-11-13 16:17
You're right; it looks like Otto is throwing away the type annotations from Go. :/

**Comment by karalabe** [comment] 2017-11-18 01:56
Fixed on master.

**Closed by karalabe** 2017-11-18 01:56 UTC
Labels: up-for-grabs
