### ISSUE TITLE
Error "peer connected on snap without compatible eth support" with a private network

### ISSUE THREAD

**Issue by GLAD-DE** [ethereum/go-ethereum#24083] opened 2021-12-08 11:56 UTC
#### System information

```bash
Geth
Version: 1.10.13-stable
Git Commit: 7a0c19f813e285516f4b525305fd73b625d2dec8
Architecture: amd64
Go Version: go1.17.2
Operating System: linux
GOPATH=
GOROOT=go
```

#### Expected behaviour

I have created a private network, with a genesis file created by ```puppeth``` and using a chainId that is not already in use. I expect the peers to be able to connect to each other.

#### Actual behaviour

Peers fail to connect with```Snapshot extension registration failed peer=af5dfeb7 err="peer connected on snap without compatible eth support"```

#### Steps to reproduce the behaviour

1. Take the attached genesis file and move it to a new directory
2. Run ```geth init --datadir "peer1" genesis.json``` and ```geth init --datadir "peer2" genesis.json``` to initiate the peer
3. In console 1 run ```geth --datadir "peer1" --networkid 1111 --port 30401 console 2>peer1.log```
4. In console 2 run ```geth --datadir "peer2" --networkid 1111 --port 30402 console 2>peer2.log```
5. In console 3 run ```tail -f peer1.log``` to see the error message

#### My attempted fixes

- Setting ```--snapshot=false``` produces the same error
- Changing the ```--syncmode``` to full, fast or light made no difference
- Adding the peers manually with ```admin.addPeer(${peer1.admin.nodeInfo.enode})``` returns true, however ```net.peerCount``` and ```admin.peers.length``` return 0
- Changing the ```chainId``` did not produce any different results
- Waiting did not help

#### Files

- [peer1.log](https://github.com/ethereum/go-ethereum/files/7675805/peer1.log)
- [peer2.log](https://github.com/ethereum/go-ethereum/files/7675806/peer2.log)
- [genesis.txt](https://github.com/ethereum/go-ethereum/files/7675809/genesis.txt) (uploaded as .txt since github does not support .json)

**Comment by ligi** [comment] 2021-12-09 10:10
the `Snapshot extension registration failed peer=af5dfeb7 err="peer connected on snap without compatible eth support"` is very likely unrelated - we see this often as there are nodes of forks of ethereum that get connected here and produce this output.

can you check if you can connect to the IP/Port you pass in ${peer1.admin.nodeInfo.enode} or if it is e.g. some firewall problem? addPeer returns true does not mean it is connected - just that it is added to the list

**Comment by GLAD-DE** [comment] 2021-12-09 12:47
It seems like I messed up when adding the peer by not replacing the IP with local host. With that change, the peers are able to connect to each other using ```admin.addPeer```.

Is there a way to make the peers discover and connect to each other without using a bootnode or adding them manually?

**Comment by dyktek** [comment] 2021-12-11 17:29
same problem here peer=af5dfeb7 err="peer connected on snap without compatible eth support"

**Comment by holiman** [comment] 2021-12-15 08:48
Seems the problem is solved, so I'm closing this. 

As far as 

> Is there a way to make the peers discover and connect to each other without using a bootnode or adding them manually? 

You can define static nodes in `nodes.json`, but that's just a version of adding them manually. As for discovery, you either need a bootnode they all connect to, or run your own crawler which publishes the enr entries over dns.. Which is a lot of work. 

The "peer connected on snap without compatible eth support" is what it says -- other peers connecting to you but not supproing the `eth` protocol. IIRC, it's optimism nodes which replaced `eth` with something else, but didn't replace `snap`, so they advertise `snap` but not eth, and it's been a cause of a not of noise.

**Closed by holiman** 2021-12-15 08:48 UTC
Labels: type:bug

**Comment by admcudo** [comment] 2022-01-10 12:13
I'm seeing this message as of today. Was this a software fix, or did the problem just solve itself, somehow ?

**Comment by coKauf** [comment] 2022-01-15 10:44
I have the same snapshot error even when replacing the IP address in 'peer1.admin.nodeInfo.enode' with local host.

**Comment by GLAD-DE** [comment] 2022-01-15 14:04
> I'm seeing this message as of today. Was this a software fix, or did the problem just solve itself, somehow ?

It seems like it was a user error on my side. However, I haven't had the time to extensively test the proposed solution.

**Comment by gcsfred2** [comment] 2022-02-14 02:35
I see the same error. It's not clear what the solution is. Running  `ethereum/client-go:v1.10.15` .

**Comment by BigSteel** [comment] 2022-06-30 12:32
I see the same error.  Running ethereum/client-go:v1.10.19

**Comment by wbt** [comment] 2022-07-06 00:32
I think originally there were two issues: the error message as reported in the subject, and peers not connecting.  The latter was caused by a user configuration issue and was the primary problem for OP, so it was closed.

The message itself is a separate issue.  I'm seeing it on v1.10.20-stable on both nodes of a private nonstandard-chain-id network, which firewall settings show as blocked from external communication.  The listed 'peer' (4-byte identifier) seems to vary randomly and I'm not sure what that field means, but it does seem confusing when each node should only report a single peer which supports exactly the same set of features (because it's running the same binary!).

**Comment by amirgamil** [comment] 2022-08-16 21:19
Facing the same issue on 1.10.17, any idea what's going on?

**Comment by Divide-By-0** [comment] 2022-08-29 07:30
Also facing this issue -- my node is stuck many blocks behind. Am not on any private network, am on eth mainnet.

**Comment by merlox** [comment] 2023-07-30 18:09
Dude why is geth full of so many errors? I've tried a million times and it's always some shit that doesn't work

**Comment by zjkal** [comment] 2024-03-08 10:56
I also encountered the same error
