### ISSUE TITLE
Wrong DNS configuration for ethdisco.net domain causes a lot of background errors during DNS queries

### ISSUE THREAD

**Issue by Neurone** [ethereum/go-ethereum#21454] opened 2020-08-16 19:10 UTC
#### System information

Geth version: `1.9.19`
OS & Version: Ubuntu 18.04

#### Expected behaviour

DNS server should always send messages compliant to [RFC 1035](https://tools.ietf.org/html/rfc1035). In particular, DNS should not send messages greater then **512 bytes** over UDP.

#### Actual behaviour

Geth **truncates DNS packets** while discovering new peers. This causes in the background a loop of DNS queries, all doomed to fail.

```bash
DEBUG[08-16|20:19:10.158] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
```

This issue was also previously reported (#20713) but it seemed to be a pi-hole related issue so it was closed without a solution. 

The problem is actually in the **DNS server configuration**:
1. DNS server sends 526 bytes when responding to queries like this YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net.
2. go DNS client follows [RFC 1035](https://tools.ietf.org/html/rfc1035) and [it truncates the message](https://github.com/golang/go/blob/8c39bbf9c93f773ab351bbddb4c3dd93e4fddc76/src/net/dnsclient_unix.go#L85) to 512 bytes and then [it goes in error while parsing](https://github.com/golang/go/blob/release-branch.go1.14/src/vendor/golang.org/x/net/dns/dnsmessage/message.go#L600-L603)
3. go DNS client [reports the error](https://github.com/ethereum/go-ethereum/blob/54add4255064f722b33fe1c13e46db0b875fe325/p2p/dnsdisc/client.go#L179-L183) to geth

The first query for the root is always fine because message size is **497 bytes** (check the last line **MSG SIZE rcvd**):

```bash
$ dig TXT all.mainnet.ethdisco.net                           

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> TXT all.mainnet.ethdisco.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49427
;; flags: qr rd ad; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;all.mainnet.ethdisco.net.      IN      TXT

;; ANSWER SECTION:
all.mainnet.ethdisco.net. 0     IN      TXT     "enrtree-root:v1 e=YT2KPIIE637MN76A2UTCOCZPFU l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=1320 sig=frVtmMBzg6wg4Ddhv6Fx1MJaUlWOG7YwskBUcAL7dFNbwo7gMzTeumaJLpPenKH_CFkDkTWs5H6aKOTGSwZFjAE"
ns-224.awsdns-28.com.   0       IN      A       205.251.192.224
ns-706.awsdns-24.net.   0       IN      A       205.251.194.194
ns-1441.awsdns-52.org.  0       IN      A       205.251.197.161
ns-1818.awsdns-35.co.uk. 0      IN      A       205.251.199.26
ns-224.awsdns-28.com.   0       IN      AAAA    2600:9000:5300:e000::1
ns-706.awsdns-24.net.   0       IN      AAAA    2600:9000:5302:c200::1

;; Query time: 0 msec
;; SERVER: 172.27.112.1#53(172.27.112.1)
;; WHEN: Sun Aug 16 19:21:34 CEST 2020
;; MSG SIZE  rcvd: 497
```
The second query to the actual ENR tree instead raises the issue:

```bash
$ dig TXT YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net 

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> TXT YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37600
;; flags: qr rd ad; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net. IN        TXT

;; ANSWER SECTION:
YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net. 0 IN TXT "enrtree-branch:EIJJYR2Y7HKP7GTBNSTTFDKISM,ZGIF73FX4IUMCY7SIF6AZ673EA,TE4PG4BD5CKZTCSQBCE45CMS2E,JZFQSASGA7S6GWOCXIEHNNY4NU,VT6KSVN7W3K4UF433DW2W6AVAU"
ns-224.awsdns-28.com.   0       IN      A       205.251.192.224
ns-706.awsdns-24.net.   0       IN      A       205.251.194.194
ns-1441.awsdns-52.org.  0       IN      A       205.251.197.161
ns-1818.awsdns-35.co.uk. 0      IN      A       205.251.199.26
ns-224.awsdns-28.com.   0       IN      AAAA    2600:9000:5300:e000::1
ns-706.awsdns-24.net.   0       IN      AAAA    2600:9000:5302:c200::1

;; Query time: 0 msec
;; SERVER: 172.27.112.1#53(172.27.112.1)
;; WHEN: Sun Aug 16 19:22:15 CEST 2020
;; MSG SIZE  rcvd: 526
```

#### How to solve the issue

Remove other records from the DNS response aside by `TXT`, in particular those not used like all `A`s and `AAAA`s.

I didn't check all other networks, but Ropsten for example is already configured in a correct way:

```bash
$ dig TXT 3EAZQHDTFVH6TTYVLEGGHUT5TM.all.ropsten.ethdisco.net

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> TXT 3EAZQHDTFVH6TTYVLEGGHUT5TM.all.ropsten.ethdisco.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1631
;; flags: qr rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;3EAZQHDTFVH6TTYVLEGGHUT5TM.all.ropsten.ethdisco.net. IN        TXT

;; ANSWER SECTION:
3EAZQHDTFVH6TTYVLEGGHUT5TM.all.ropsten.ethdisco.net. 0 IN TXT "enrtree-branch:XX4U4ZKXUCOWBHPUOGISEAIDJE,4ZR6DWAKZTWUEMTCN47N3KY7YE,NHRHUEAR5OY4K4O6TCL5LUTCLM,PDPBUM23QXC32GCRPCWBZBA2NU,N7NYW2XJCJZE22MXJMGI4HVJO4,I6VIAEOHT4RJC54AA2HFP6QJSI,M7YILXPTHZ7PUJZERM5T72PABA,TC22I752VVE6Y4DYYWG2VOV6PY,OGDOAVH7BVKLSNWTCM42WP" "4IEA,CYV3DOHCVAL43SK5RYQCDIK6EI"

;; Query time: 23 msec
;; SERVER: 172.27.112.1#53(172.27.112.1)
;; WHEN: Sun Aug 16 19:21:11 CEST 2020
;; MSG SIZE  rcvd: 418
```

#### Steps to reproduce the behaviour

Start geth from scratch with verbosity level 4

#### Backtrace

````
$ geth --verbosity 4
INFO [08-16|20:19:09.860] Starting Geth on Ethereum mainnet... 
INFO [08-16|20:19:09.860] Bumping default cache on mainnet         provided=1024 updated=4096
DEBUG[08-16|20:19:09.860] Sanitizing Go's GC trigger               percent=25
INFO [08-16|20:19:09.862] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-16|20:19:09.862] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
DEBUG[08-16|20:19:09.862] FS scan times                            list="28.5µs" set=700ns diff=800ns
INFO [08-16|20:19:09.862] Set global gas cap                       cap=25000000
INFO [08-16|20:19:09.862] Allocated trie memory caches             clean=1023.00MiB dirty=1024.00MiB
[...]
DEBUG[08-16|20:19:10.158] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:10.159] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:10.160] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:10.161] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:10.162] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:10.163] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:10.165] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:10.490] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:10.823] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:11.157] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:11.490] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:11.823] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:12.490] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:12.823] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:13.156] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:13.490] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:13.823] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:14.157] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:14.823] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:15.156] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:15.490] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:15.823] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:16.156] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:16.490] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
DEBUG[08-16|20:19:17.156] Error in DNS random node sync            tree=all.mainnet.ethdisco.net err="lookup YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net on 172.27.112.1:53: cannot unmarshal DNS message"
[...]
````

**Comment by fjl** [comment] 2020-08-17 11:27
Thanks for debugging this! We'll see how to disable this behavior on the server side.

**Comment by Aldekein** [comment] 2020-08-19 08:25
Just tried to run the `dig` from an AWS EC2 machine, and getting the following results:

```
$ dig TXT YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> TXT YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 17019
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net. IN	TXT

;; Query time: 11 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Aug 19 08:21:20 UTC 2020
;; MSG SIZE  rcvd: 80
```

and: 
```$ dig TXT all.mainnet.ethdisco.net

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> TXT all.mainnet.ethdisco.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4896
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;all.mainnet.ethdisco.net.	IN	TXT

;; ANSWER SECTION:
all.mainnet.ethdisco.net. 1347	IN	TXT	"enrtree-root:v1 e=WDF2TUTUUA2Y3QWK337W54HMWA l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=1329 sig=2bMfIuiDld1MoyqZKl63YD0msEixMlEs02mwE46z0d8ojeUbfUTKLGRpqsfDwhelcq2yqqx51tkfbH44xc9M9gE"

;; Query time: 1 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Aug 19 08:22:17 UTC 2020
;; MSG SIZE  rcvd: 240```

There's no extra AAAA and A records in response, the `YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net` and domain isn't resolved at all.

**Comment by Neurone** [comment] 2020-08-19 08:30
Second query ID (i.e. YT2KPIIE637MN76A2UTCOCZPFU.all.mainnet.ethdisco.net) is dynamic, it changes about every 10 minutes, you will get the correct ID from the first query, in your case WDF2TUTUUA2Y3QWK337W54HMWA

**Comment by fjl** [comment] 2020-08-19 09:37
ethdisco.net is hosted on Amazon Route53. We've done some checks on our configuration there and these extra records are not configured on the server in any way. This issue could also be a problem with a misbehaving intermediate resolver.

**Comment by fjl** [comment] 2020-08-19 09:41
A stable command to check for this issue is

```
./build/bin/devp2p --verbosity 5 dns sync enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
```

This will download all available nodes at the given name in the same way geth would.

**Comment by Neurone** [comment] 2020-08-19 12:48
@fjl I'll try as soon as possible. Have you tried to query the DNS also from a client outside EC2?

**Comment by Neurone** [comment] 2020-08-19 13:22
Tested on mobile phone via tmux and and DNS actually resolves TXT correctly without problems. Wierd. I'll be again at home in few days, I'll try again from there. Maybe some cached result from specific ISPs or regions? I experienced the problem connecting from Rome, Italy using Fastweb ISP.

**Comment by fjl** [comment] 2020-08-20 12:08
I tested outside of EC2 (don't have anything on EC2) and it works for me.

**Comment by fjl** [comment] 2020-08-23 19:41
Which resolver software are you using in your VM? It sounds like there is a bug there, would like to confirm this.

> Suggestion: maybe this discovery feature can be replaced with a more decentralized and less "client configuration dependent"? Maybe client can look at a specific address and tx, or to a smart contract, get hash of ENR tree from there and then download the client list from Swarm/IPFS?

The DNS-based discovery is the fallback option for the DHT, which is always enabled and is decentralized. We actually had the DHT first, the DNS-based discovery was added because not everyone can use the DHT.

**Comment by Neurone** [comment] 2020-08-24 01:40
I'm using a Ubuntu 18.04.5 distro under Windows 10 via WSL. The virtual NIC is an _Hyper-V Virtual Ethernet Adapter_

```bash
Ethernet adapter vEthernet (WSL):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : 00-15-5D-E5-A9-47
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::5d92:dde2:14c1:abf4%24(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.28.176.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 402658653
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-24-90-8D-94-C8-60-00-CA-E9-ED
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

It seems there are many unsolved DNS issues (i.e. https://github.com/microsoft/WSL/issues/4285, https://github.com/microsoft/WSL/issues/3268) for this configuration. I did other tests but the only way I can make geth works without problems is to set a _static_ DNS using this suggestion [Fix DNS resolution in WSL2](https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6).

I don't think this is an easy issue to solve, but maybe this workaround can be helpful for others.

**Comment by fjl** [comment] 2020-08-24 08:31
Thank you. Maybe we should create an issue in the WSL repo then.

**Comment by Neurone** [comment] 2020-08-25 01:22
> Thank you. Maybe we should create an issue in the WSL repo then.

Done :) I hope they can do something about it even if I fear it can be a problem with Windows ICS (netsvcs). I think Hyper-V Virtual Adapter redirects queries to that under the hood, but now we are in the field of closed source so I cannot easily investigate any further.

**Comment by fjl** [comment] 2020-08-25 20:54
Very very cool. Thanks again for the detailed debugging, it was very helpful to isolate the issue. I'll close this one because it looks like this reproduces also with other domains.

**Closed by fjl** 2020-08-25 20:54 UTC
