### ISSUE TITLE
1.10.23 fresh mainnet sync stalled

### ISSUE THREAD

**Issue by yorickdowne** [ethereum/go-ethereum#25596] opened 2022-08-25 00:18 UTC
#### System information

Geth version: `1.10.23`
OS & Version: Linux

#### What

Fresh sync on empty DB of Ethereum mainnet. Eventually stalls for about 3 hours, last log messages:

```
execution_1         | INFO [08-24|20:09:46.928] Imported new block receipts              count=442  elapsed=504.841ms   number=15,089,993 hash=741f72..f4ade1 age=1mo2w5d    size=68.28MiB
execution_1         | INFO [08-24|20:09:46.929] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=2665h49m35.199s
execution_1         | INFO [08-24|20:12:59.927] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=2711h43m55.893s
execution_1         | WARN [08-24|20:13:14.441] Snapshot extension registration failed   peer=327cb76d err="peer connected on snap without compatible eth support"
execution_1         | INFO [08-24|20:13:26.758] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=2718h7m47.399s
execution_1         | WARN [08-24|20:13:31.298] Snapshot extension registration failed   peer=6de3885d err="peer connected on snap without compatible eth support"
execution_1         | INFO [08-24|20:13:45.646] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=2722h37m9.802s
execution_1         | WARN [08-24|20:13:46.280] Dropping unsynced node during sync       id=e9de0878ad2242f7 conn=inbound addr=47.95.116.123:52658             type=Geth/v1.10.23-stable...
execution_1         | WARN [08-24|20:13:48.597] Snapshot extension registration failed   peer=decab1a9 err="peer connected on snap without compatible eth support"
execution_1         | INFO [08-24|20:14:01.764] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=2726h28m22.624s
execution_1         | INFO [08-24|21:02:48.376] Writing clean trie cache to disk         path=/var/lib/goethereum/geth/triecache      threads=1
execution_1         | INFO [08-24|21:02:48.376] Regenerated local transaction journal    transactions=0 accounts=0
execution_1         | INFO [08-24|21:02:48.392] Persisted the clean trie cache           path=/var/lib/goethereum/geth/triecache      elapsed=16.049ms
execution_1         | INFO [08-24|21:15:55.166] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=3609h56m37.427s
execution_1         | INFO [08-24|21:16:39.690] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=3620h31m53.779s
execution_1         | INFO [08-24|22:02:48.375] Writing clean trie cache to disk         path=/var/lib/goethereum/geth/triecache      threads=1
execution_1         | INFO [08-24|22:02:48.375] Regenerated local transaction journal    transactions=0 accounts=0
execution_1         | INFO [08-24|22:02:48.388] Persisted the clean trie cache           path=/var/lib/goethereum/geth/triecache      elapsed=12.659ms
execution_1         | INFO [08-24|23:02:48.376] Regenerated local transaction journal    transactions=0 accounts=0
execution_1         | INFO [08-24|23:02:48.376] Writing clean trie cache to disk         path=/var/lib/goethereum/geth/triecache      threads=1
execution_1         | INFO [08-24|23:02:48.391] Persisted the clean trie cache           path=/var/lib/goethereum/geth/triecache      elapsed=15.105ms
execution_1         | INFO [08-24|23:03:33.232] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=5146h23m1.367s
execution_1         | INFO [08-24|23:03:48.212] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=5149h56m16.576s
execution_1         | WARN [08-24|23:03:56.567] Dropping unsynced node during sync       id=87d9aace46398de2 conn=inbound addr=3.66.140.34:44640               type=
execution_1         | INFO [08-24|23:04:12.949] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=5155h50m57.204s
execution_1         | WARN [08-24|23:04:13.026] Dropping unsynced node during sync       id=24877dcb4101f157 conn=inbound addr=47.149.49.97:58824              type=besu/v22.7.1/linux-x...
execution_1         | INFO [08-24|23:04:23.220] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=5158h16m51.799s
execution_1         | WARN [08-24|23:04:35.321] Dropping unsynced node during sync       id=4d4380f0c12abda7 conn=inbound addr=18.142.232.3:53926              type=
execution_1         | WARN [08-24|23:04:50.023] Snapshot extension registration failed   peer=2df6ffae err="peer connected on snap without compatible eth support"
execution_1         | INFO [08-24|23:04:58.225] State sync in progress                   synced=0.12% state=149.97MiB accounts=385,037@49.68MiB slots=454,877@91.66MiB codes=3544@8.63MiB eta=5166h35m12.180s

execution_1         | INFO [08-25|00:02:48.375] Writing clean trie cache to disk         path=/var/lib/goethereum/geth/triecache      threads=1
execution_1         | INFO [08-25|00:02:48.375] Regenerated local transaction journal    transactions=0 accounts=0
execution_1         | INFO [08-25|00:02:48.389] Persisted the clean trie cache           path=/var/lib/goethereum/geth/triecache      elapsed=13.788ms
```

Restarting Geth had it grabbing receipts and headers again. After restart state sync progresses, which it didn't during the first run, and ETA is sane, around 3.5 hours for state sync. Sync did complete after this restart.

This is connected to a fully synced CL via Engine API, not that that should matter pre-merge.

**Comment by garyng2000** [comment] 2022-08-25 02:34
I am seeing similar stall too(after removedb but ancient data kept). the state sync stalked at 79% and the import header also stalled for about 30 minutes and lagged by a hundred or so blocks and counting. thinking if I should restart to see if it can continue but at the same time it seems to be doing db compaction as that message still periodically showing

**Comment by ryanschneider** [comment] 2022-08-26 16:00
In the past these stalls have often been caused by leveldb compaction, but there used to be a log at IIRC warning level when that happened.  Maybe .23 has a regression where the compaction warning isn't being output?

**Comment by yorickdowne** [comment] 2022-08-26 16:11
3 hours though? This is a baremetal machine with a "data center" NVMe. When it compacts DB that typically takes around 3 minutes, not 3 hours.

**Comment by holiman** [comment] 2022-12-20 14:28
This ticket is very old, and with a pretty old version. Closing this

**Closed by holiman** 2022-12-20 14:28 UTC
Labels: type:bug
