### ISSUE TITLE
Rinkeby faucet not working

### ISSUE THREAD

**Issue by nachikettapas** [ethereum/go-ethereum#17841] opened 2018-10-04 14:29 UTC
Hi there,

It seems that the Rinkeby faucet is not working. Even though the site is able to accept the request, the test ethers are not credited into the account.

#### System information

OS & Version: Windows

#### Expected behaviour

Ethers should be credited into the account.

#### Actual behaviour

Even though the request is accepted, the ethers are not credited into the account.

#### Steps to reproduce the behaviour

Post google+ link with ethereum account into the textbox and request ethers.

**Comment by karalabe** [comment] 2018-10-04 16:04
Should be fixed now. There's a light client sync issue which causes the faucet to lock up from time to time. Hopefully @zsfelfoldi can find the cause soonish.

**Closed by karalabe** 2018-10-04 16:04 UTC
