### ISSUE TITLE
debug.traceTransaction with reexec crashes

### ISSUE THREAD

**Issue by computerality** [ethereum/go-ethereum#17431] opened 2018-08-17 17:54 UTC
#### System information

Geth version: `geth version`
```
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.10.3.linux.amd64
```

OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
A trace returned 

#### Actual behaviour
geth crashes on a null deref

#### Steps to reproduce the behaviour
Run geth with `./geth --cache 2048  --syncmode=full --gcmode=archive`

Execute this in the geth attach console:
`debug.traceTransaction('0xf49e45d3ddc33432f14b156d9fd30fba52c17a6562ec57eaf1f2bcede94c8eb7', {reexec:6000000})`

#### Backtrace

````
[backtrace]
INFO [08-05|12:51:54.611] Regenerating historical state            block=2087976 target=2378876 elapsed=892ns
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x69d00e]

goroutine 2818 [running]:
github.com/ethereum/go-ethereum/trie.(*Database).reference(...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/database.go:423
github.com/ethereum/go-ethereum/trie.(*Database).Reference(0xc4efc03680, 0x28f3d621d5fc274b, 0xd5978f1247278fe9, 0xdda1357433f5cd0f, 0x77f4fbd53a73065c, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/database.go:412 +0x18e
github.com/ethereum/go-ethereum/eth.(*PrivateDebugAPI).computeStateDB(0xc422287420, 0xc47664da70, 0x5b8d80, 0x80342b59eeb74931, 0x3c9d831662bfd1ac, 0x244c7c)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/api_tracer.go:528 +0x4e9
github.com/ethereum/go-ethereum/eth.(*PrivateDebugAPI).computeTxEnv(0xc422287420, 0x5fcaba9a2e8d564e, 0x791342efca6fff4, 0x1dbae953d52f8df0, 0x9946cf265ea8a0b6, 0x8, 0x5b8d80, 0x5fcaba9a2e8d564e, 0x791342efca6fff4, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/api_tracer.go:629 +0x184
github.com/ethereum/go-ethereum/eth.(*PrivateDebugAPI).TraceTransaction(0xc422287420, 0x10c8a60, 0xc484094b10, 0x3234c3ddd3459ef4, 0xba0fd39f6d154bf1, 0xea57ec62657ac152, 0xb78e4ce9edbcf2f1, 0xc48996ce60, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/api_tracer.go:549 +0x16c
reflect.Value.call(0xc4275c9180, 0xc4275b90c8, 0x13, 0xf38b2d, 0x4, 0xc445f13da0, 0x4, 0x4, 0xc42036bd80, 0xc445f13da0, ...)
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc4275c9180, 0xc4275b90c8, 0x13, 0xc445f13da0, 0x4, 0x4, 0x2, 0x2, 0x941d31af3d)
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/reflect/value.go:308 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc4275e1060, 0x10c8a60, 0xc484094b10, 0x10cdd00, 0xc454a9db80, 0xc445f13d40, 0xc42036bf38, 0x43f799, 0x8)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:312 +0x676
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc4275e1060, 0x10c8a60, 0xc484094b10, 0x10cdd00, 0xc454a9db80, 0xc445f13d40)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:333 +0x1a6
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func2(0xc46cbc0a20, 0xc4275e1060, 0xc481a8f870, 0x10cdd00, 0xc454a9db80, 0xc49eeeaef8, 0x1, 0x1, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:207 +0xad
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:202 +0x2b7
````

**Comment by holiman** [comment] 2018-08-17 19:35
I suspect this is a duplicate of https://github.com/ethereum/go-ethereum/issues/17355 (which is fixed already)

**Closed** 2018-08-21 19:58 UTC
