### ISSUE TITLE
Native log broken for package consumers

### ISSUE THREAD

**Issue by synthmeat** [ethereum/go-ethereum#28738] opened 2023-12-26 16:26 UTC
`v1.13.6` introduced issue where it breaks `log` usage for package consumers.

```
$ go version
go version go1.21.5 darwin/arm64
```

Minimal code to reproduce, where expectation is to print anything to stderr. What happens is that it doesn't print anything at all. (`fmt` to either stdout or stderr works fine.)

`main.go`
```
package main

import (
        "log"

        "github.com/ethereum/go-ethereum/ethclient"
)

func main() {
        log.Println("shalala")
        _, err := ethclient.Dial("https://cloudflare-eth.com")
        if err != nil {
                log.Println(err)
        }
        log.Println("shalala")
}
```

`go.mod`
```
module gethrepro

go 1.21

require github.com/ethereum/go-ethereum v1.13.6

require (
        github.com/Microsoft/go-winio v0.6.1 // indirect
        github.com/StackExchange/wmi v1.2.1 // indirect
        github.com/bits-and-blooms/bitset v1.10.0 // indirect
        github.com/btcsuite/btcd/btcec/v2 v2.2.0 // indirect
        github.com/consensys/bavard v0.1.13 // indirect
        github.com/consensys/gnark-crypto v0.12.1 // indirect
        github.com/crate-crypto/go-kzg-4844 v0.7.0 // indirect
        github.com/deckarep/golang-set/v2 v2.1.0 // indirect
        github.com/decred/dcrd/dcrec/secp256k1/v4 v4.0.1 // indirect
        github.com/ethereum/c-kzg-4844 v0.4.0 // indirect
        github.com/go-ole/go-ole v1.2.5 // indirect
        github.com/gorilla/websocket v1.4.2 // indirect
        github.com/holiman/uint256 v1.2.4 // indirect
        github.com/mmcloughlin/addchain v0.4.0 // indirect
        github.com/shirou/gopsutil v3.21.4-0.20210419000835-c7a38de76ee5+incompatible // indirect
        github.com/supranational/blst v0.3.11 // indirect
        github.com/tklauser/go-sysconf v0.3.12 // indirect
        github.com/tklauser/numcpus v0.6.1 // indirect
        golang.org/x/crypto v0.15.0 // indirect
        golang.org/x/exp v0.0.0-20231110203233-9a3e6036ecaa // indirect
        golang.org/x/mod v0.14.0 // indirect
        golang.org/x/sync v0.5.0 // indirect
        golang.org/x/sys v0.14.0 // indirect
        golang.org/x/tools v0.15.0 // indirect
        rsc.io/tmplfunc v0.0.3 // indirect
)
```

**Comment by 0x0elliot** [comment] 2023-12-26 18:32
I would like to fix this. Can someone give me some context about this issue? :)
I am new to the geth ecosystem, and would like to contribute. This seems like a simple entrypoint!

**Comment by namiloh** [comment] 2023-12-26 18:40
Figuring out what happened and why is the large part of fixing any bug (mostly). Go for it, @0x0elliot !

**Comment by 0x0elliot** [comment] 2023-12-26 18:41
I will then! Let me get done with another PR I am working on and get to this. Kindly assign :)

**Comment by 0x0elliot** [comment] 2023-12-27 13:55
This seems like an intended breaking @synthmeat 

https://github.com/ethereum/go-ethereum/releases/tag/v1.13.6 in here it clearly states: 

```
In the absence of an 'official' Go logging framework, go-ethereum has, for a very long time, used a custom in-house logger. However, just such an 'official' Go logging framework has now arrived, with the [slog](https://go.dev/blog/slog) package.
```

and...

<img width="910" alt="For users of the github.com/ethereum/go-ethereum/log package: If you were using this package for your own project, you will need to change the initialization. If you previously did" src="https://github.com/ethereum/go-ethereum/assets/60684641/e2cc347b-df29-4f3b-9054-cab9c6f5a4c5">

@namiloh This seems intended. Is there still some optimisation you would want me to make to help out users?

**Comment by synthmeat** [comment] 2023-12-27 14:59
@0x0elliot But I'm not clearly using `github.com/ethereum/go-ethereum/log`, I'm using `log` from the Go's standard library. How is breaking stdlib "intended"?

**Comment by 0x0elliot** [comment] 2023-12-27 15:04
@synthmeat Right! I missed that. Let me look deeper.

**Comment by 0x0elliot** [comment] 2023-12-28 17:34
Interesting observation:
```golang
package main

import (
	"log/slog"
	"os"
	"fmt"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/log"
)

func main() {
	_, err := ethclient.Dial("https://mainnet.infura.io")
	if err != nil {
		fmt.Println("error")
	}

	slog.Info("(1) hello world")
	log.SetDefault(log.NewLogger(log.NewTerminalHandlerWithLevel(os.Stderr, log.LevelInfo, true))) // recommendation made
	slog.Info("(2) hello world")
}
```

<img width="739" alt="Screenshot 2023-12-28 at 11 01 08 PM" src="https://github.com/ethereum/go-ethereum/assets/60684641/779047b6-6154-46da-b75a-75177c81f76d">

That's extremely interesting. It seems like just by being directly even imported into the code (ethereum log library is imported by ethclient), without anything being initialised.

Same observation is made when I just import `"github.com/ethereum/go-ethereum/log"` into the code:

```golang
package main

import (
	"log/slog"
	"os"
	// "github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/log"
)

func main() {
	slog.Info("(1) hello world")
	log.SetDefault(log.NewLogger(log.NewTerminalHandlerWithLevel(os.Stderr, log.LevelInfo, true)))
	slog.Info("(2) hello world")
}
```

<img width="685" alt="Screenshot 2023-12-28 at 11 04 17 PM" src="https://github.com/ethereum/go-ethereum/assets/60684641/651c7aee-ecdf-48b3-8e05-682c2838644c">

**Comment by 0x0elliot** [comment] 2023-12-28 18:10
To summarise it @synthmeat, Technically, you're not using "github.com/ethereum/go-ethereum/log" but ethereum's ethclient uses it. @namiloh how should we proceed forward to fixing this because it is close to "intended behaviour".

More here: https://github.com/ethereum/go-ethereum/issues/28558#issuecomment-1820606613

> but the logs would silently disappear as we're be pushing them into an uninitialized slog

**Comment by namiloh** [comment] 2023-12-28 18:58
This behaviour seems wrong to me, I don't see why we should initiate slog with a default discard-handler. We could just leave it be whatever it already is.
Not sure. As it is, we force the 'main' to explicitly configure it, otherwise logs are discarded. It is a bit naughty behaviour for a library to do that, even though arguable the 'main' ought to configure it.

**Comment by fjl** [comment] 2023-12-28 20:11
This issue is about package `log` and not package `log/slog`. We need to make sure that our initialization of slog does not automatically redirect messages printed with `log`.

**Comment by namiloh** [comment] 2023-12-28 20:34
I assume golang authors decided to route log to slog...?

**Comment by 0x0elliot** [comment] 2023-12-28 20:39
they did that's why i went ahead and used slog. log and slog show similar behaviour in this context!

**Comment by fjl** [comment] 2023-12-28 23:06
The issue happens because we call `slog.SetDefault` from [an init function](https://github.com/ethereum/go-ethereum/blob/09e0208029ff96a9cda0c69dbaebfd3f31a39771/log/root.go#L12-L15). This will override the default output of package `log`. I think we can remove this init function.

**Comment by 0x0elliot** [comment] 2023-12-28 23:21
@fjl where will this overriding be done then next?

**Comment by namiloh** [comment] 2023-12-29 08:19
No we would just remove the init, not replace.

**Comment by 0x0elliot** [comment] 2023-12-29 08:26
well, i can make a small PR for that if it's that simple :) @namiloh

**Comment by fjl** [comment] 2023-12-29 22:27
Fixed by https://github.com/ethereum/go-ethereum/pull/28747

**Comment by fjl** [comment] 2023-12-30 20:16
It should be fixed on the master branch.

**Closed** 2023-12-30 20:16 UTC
Labels: type:bug
