### ISSUE TITLE
eth_getBlockByHash with the hash of the latest block

### ISSUE THREAD

**Issue by 1ee5c807** [ethereum/go-ethereum#27197] opened 2023-04-29 02:03 UTC
#### System information

Geth version: geth version 1.11.7-unstable-523fe430-20230428
CL client & version: prysm@v4.0.3
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
On an Ethereum client, after subscribing to geth, immediately after a new blockheader arrives, a lookup with eth_getBlockByHash using the block's hash should result in a lookup.

#### Actual behaviour
Returns not_found as the result.

#### Steps to reproduce the behaviour
1. Subscribe the NewHead to the Geth.
2. When a new header arrives, call eth_getBlockByHash with the hash of the arrived header.
3. Check for not_found.

#### Backtrace
N/A

#### Please Note Below
I have also conducted a test with a few code modification,  wherein I utilized the eth_getBlockByNumber method under the exact same circumstances as described above,
and it worked perfectly fine. 

And my code was working fine before, but it breaks with the latest version of geth.

I didn't analyze it in detail because I didn't have time. 

However, I strongly suspect that the bug is in the code that notifies the client of the arrival of a new blockheader before the code that maps the block hash to the block number and stores it.

I'm hoping that someone who is an expert on the issue will fix it soon.

**Comment by 0xall** [comment] 2023-05-02 18:09
Which node does it happen? Light node or full node?

**Comment by holiman** [comment] 2023-05-04 08:48
Thanks for the report, we'll investigate!

**Comment by s1na** [comment] 2023-08-31 12:34
I haven't been able to reproduce this issue. I have a subscription to newHeads running for a while and doing `getBlockByHash` of the result which works. Does it still persist for you on the latest version?

**Comment by jsvisa** [comment] 2023-09-18 07:36
Can't reproduce either, if someone is interested in this, here is a simple example:

```go
// issue https://github.com/ethereum/go-ethereum/issues/27197
// eth_getBlockByHash with the hash of the latest block
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"sync"
	"time"

	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/log"
)

var (
	provider = flag.String("rpc", "ws://localhost:8546", "RPC provider address in ws")
	workers  = flag.Int("worker", 20, "Number of workers")
)

func subscribeNewHead(wid string, provider string) {
	client, err := ethclient.Dial(provider)
	if err != nil {
		log.Crit("error creating client", "wid", wid, "err", err)
	}
	defer client.Close()

	ctx := context.Background()
	ch := make(chan *types.Header)
	sub, err := client.SubscribeNewHead(ctx, ch)
	if err != nil {
		log.Crit("Failed to subscribe NewHead event", "wid", wid, "err", err)
	}
	defer sub.Unsubscribe()

	log.Info("Success subscribe NewHead", "wid", wid)
LOOP:
	for {
		select {
		case err := <-sub.Err():
			log.Error("Subscribe error", "wid", wid, "err", err)
			break LOOP

		case e := <-ch:
			t := time.Unix(int64(e.Time), 0).Format("2006-01-02 15:04:05")
			log.Info("NewHeader", "wid", wid, "number", e.Number, "hash", e.Hash(), "time", t)
			_, err := client.BlockByHash(ctx, e.Hash())
			if err != nil {
				log.Error("BlockByHash", "wid", wid, "number", e.Number, "hash", e.Hash(), "err", err)
				continue
			}

		case err := <-ctx.Done():
			log.Error("context error", "wid", wid, "err", err)
			break LOOP
		}
	}
	close(ch)
}

func main() {
	flag.Parse()
	log.Root().SetHandler(log.LvlFilterHandler(log.LvlInfo, log.StreamHandler(os.Stdout, log.TerminalFormat(true))))

	var wg sync.WaitGroup
	for i := 0; i < *workers; i++ {
		i := i
		wg.Add(1)
		go func() {
			defer wg.Done()
			subscribeNewHead(fmt.Sprintf("%02d", i), *provider)
		}()
	}
	wg.Wait()
}
```

**Comment by holiman** [comment] 2023-12-04 15:19
Despite diligent efforts, this ticket seems not repdroducable. Closing

**Closed by holiman** 2023-12-04 15:19 UTC
Labels: type:bug, need:more-information
