### ISSUE TITLE
Geth Console blocks internet access

### ISSUE THREAD

**Issue by ginward** [ethereum/go-ethereum#14883] opened 2017-07-31 14:42 UTC
#### System information

Geth version: 

```
Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.8.3/libexec
```

OS & Version: 
`MAC OSX 10.12.5`

#### Expected behaviour
I should able to access internet via browsers or terminal after starting the geth client. 

#### Actual behaviour
However, after running `geth console` on terminal, all internet access on my browsers (Safari and Chrome) and pings (ping google.ca) are blocked. They hang for a while and returns nothing.

#### Steps to reproduce the behaviour
Run geth console on Mac terminal.

**Comment by Swader** [comment] 2018-04-26 06:31
Can reproduce, but have narrowed it down to geth nodes running and being connected, not consoles per se.

**Comment by holiman** [comment] 2019-04-02 09:09
The only reason I can imagine would be that the ISP detects the surge in traffic, or identifies the p2p erroneously as some 'illegal file sharing' and cuts it off. Other than that, it might be that the connection is saturated when geth is syncing. 
I'll close this, since I think the causes for this is outside of geth.

**Closed by holiman** 2019-04-02 09:09 UTC
Labels: status:triage
