### ISSUE TITLE
Official binary download packages unavailable for macOS/aarch64

### ISSUE THREAD

**Issue by tersec** [ethereum/go-ethereum#28472] opened 2023-11-07 03:41 UTC
# Rationale

macOS has been shifting from x86 to Aarch64, but https://geth.ethereum.org/downloads still has only x86 macOS builds. For a couple of years now, all new Macs have been natively Aarch64-only, with any x86 support via emulation. Therefore, if Geth release binaries are to remain most useful on macOS, there would be some benefit in targeting Apple's now-primary, and presumably in the medium-term future, only platform with supported release builds.

**Comment by karalabe** [comment] 2023-11-07 07:29
Good point. Though we do have a homebrew source which builds on demand, so that might be a better solution in general than pulling the binaries from the site.

**Comment by tersec** [comment] 2023-11-07 07:33
Nimbus uses Geth as part of its CI, and in general does not include Go(lang) build infrastructure in that. We currently use a separate repo (https://github.com/status-im/nimbus-simulation-binaries/) for this, but it's largely a workaround for the issue described here.

**Comment by karalabe** [comment] 2023-11-07 10:23
The issue is that our binaries are currently built on Travis and they don't support Apple Silicon. Cross building is a bit problematic because Geth uses C crypto libraries, so it's a can of worms to have everything work.

**Comment by karalabe** [comment] 2023-11-07 10:35
Maybe fixed by https://github.com/ethereum/go-ethereum/pull/28474, waiting for builds to complere.

**Comment by karalabe** [comment] 2023-11-07 11:26
@tersec Just published the arm64 builds for Geth v1.13.5 (the unstable table). Could you verify if they work as you'd expect?

**Comment by karalabe** [comment] 2023-11-07 13:42
Assuming it works, please comment otherwise.

**Closed by karalabe** 2023-11-07 13:42 UTC
Labels: type:feature

**Comment by tersec** [comment] 2023-11-07 13:43
Yeah testing in progress: https://github.com/status-im/nimbus-eth2/pull/5575

**Comment by tersec** [comment] 2023-11-07 13:57
https://gethstore.blob.core.windows.net/builds/geth-darwin-arm64-1.13.5-unstable-f20b334f.tar.gz (sha256 `58d6f4da2fc5b168373a4882d23734ef785a35ef443e6022f777c9df5274f168`) appears to contain an x86 executable, which leads to
```
[2023-11-07T13:48:48.997Z] ./scripts/start_geth_nodes.sh: line 25: /Users/jenkins/workspace/_platforms_macos_aarch64_PR-5575/build/downloads/geth: Bad CPU type in executable
```
in Nimbus's CI. But https://gethstore.blob.core.windows.net/builds/geth-darwin-arm64-1.13.5-unstable-f20b334f.tar.gz does not seem to contain an x86 executable (according to `file(1)`), so trying that.

**Comment by karalabe** [comment] 2023-11-07 14:02
```
geth-darwin-arm64-1.13.5-unstable-f20b334f % file geth                                       
geth: Mach-O 64-bit executable arm64
```

says for me

**Comment by tersec** [comment] 2023-11-07 14:09
Thus https://github.com/status-im/nimbus-eth2/pull/5575/commits/6dcecb53fb24e38ed2cb867cd2536d6f86b65c6f

**Comment by tersec** [comment] 2023-11-07 15:02
Looks like it's working.
