### ISSUE TITLE
Inferring database scheme via `readonly` fails for an empty `ancient` database

### ISSUE THREAD

**Issue by maoueh** [ethereum/go-ethereum#28112] opened 2023-09-13 18:48 UTC
#### System information

Geth version: `geth version 1.13.0`
CL client & version: Not important
OS & Version: OSX
Commit hash: 8d38b1fe62950e8675795abf63b7c978415ab7ba

#### Expected behaviour

No crash

#### Actual behaviour

Crash with:

```
INFO [09-13|14:27:01.772] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-13|14:27:01.776] Using leveldb as the backing database
INFO [09-13|14:27:01.776] Allocated cache and file handles         database=/app/geth/chaindata cache=512.00MiB handles=5120 readonly=true
INFO [09-13|14:27:01.778] Using LevelDB as the backing database
Chain metadata
  databaseVersion: <nil>
  headBlockHash: 0xc5902001cfab2bfb6cbfb5e752ab11be44af47d50dbd777a02f7098c169e780b
  headFastBlockHash: 0xc5902001cfab2bfb6cbfb5e752ab11be44af47d50dbd777a02f7098c169e780b
  headHeaderHash: 0xc5902001cfab2bfb6cbfb5e752ab11be44af47d50dbd777a02f7098c169e780b
  lastPivotNumber: <nil>
  len(snapshotSyncStatus): 0 bytes
  snapshotDisabled: false
  snapshotJournal: 0 bytes
  snapshotRecoveryNumber: <nil>
  snapshotRoot: 0x0000000000000000000000000000000000000000000000000000000000000000
  txIndexTail: <nil>
  fastTxLookupLimit: <nil>

Fatal: Could not open database: open /app/geth/chaindata/ancient/chain/headers.cidx: no such file or directory
```

#### Steps to reproduce the behaviour

Right now I have a data dir that looks like this:

```
├── LOCK
├── chaindata
│   ├── 000001.log
│   ├── CURRENT
│   ├── LOCK
│   ├── LOG
│   ├── MANIFEST-000000
│   └── ancient
│       └── chain
│           └── FLOCK
├── lightchaindata
│   ├── 000001.log
│   ├── CURRENT
│   ├── LOCK
│   ├── LOG
│   └── MANIFEST-000000
└── nodekey
```

Note that my `ancient` folder contains no tables, only `FLOCK`. On bootstrap of `geth`, there is the inference of the database scheme, which is done in `readonly` mode:

```go
	// Parse state scheme, abort the process if it's not compatible.
	chaindb := tryMakeReadOnlyDatabase(ctx, stack)
```

This will reach a some point the `newTable` inside `freezer_table.go` file which does this when `read-only`:

```
		// Will fail if table index file or meta file is not existent
		index, err = openFreezerFileForReadOnly(filepath.Join(path, idxName))
		if err != nil {
			return nil, err
		}
		meta, err = openFreezerFileForReadOnly(filepath.Join(path, fmt.Sprintf("%s.meta", name)))
		if err != nil {
			return nil, err
		}
```

So it crashes there because the ancient tables do not exists.

I must admit this geth's data dir was created a long time ago using I think `geth 1.9.23`. Not sure if it's normal that I have no ancient tables but I think it's actually valid. The write mode simply creates files if they do not exist, so I think it might be possible to have such case where no ancient tables is present.

Not sure if there is an easy fix here, if the ancient is not required to infer the scheme, maybe it could be refactored to only deal with the "current" data set and leave ancient out of the equation.

Another thing could be to update `newTable` in `freezer_table.go`to better deal with inexistent tables in readonly mode. The `Freezer.tables` map could then have no tables (or less tables). I'm not sure of the implications of such thing.

**Comment by maoueh** [comment] 2023-09-13 19:01
I've workaround for now adding the missing tables manually to my "cached" data dir. Just tested `geth init` also and it produces those ancient tables, so might not warrant a fix actually.

I'll let you guys decide, feel free to close if it's a won't fix.

**Comment by maoueh** [comment] 2023-09-13 19:05
This would actually happen also if someone deletes its `ancient` folder, not sure if this is common or not.

**Comment by maoueh** [comment] 2023-09-13 19:08
Also to add more info, if any expected files is missing, it will lead to such error. I had another test case where the ancient had tables but was missing a few `xxx.meta` files, it led to the same issue.

**Comment by rjl493456442** [comment] 2023-09-14 02:03
I can reproduce this issue, and it's quite an unusual scenario where the database is considered to exist while the 'ancient' data is missing.

In fact, if someone unintentionally deletes the 'ancient' folder, it can make geth inoperable in most cases due to an incomplete chain segment, even without this specific database error. The only exception is if the 'ancient' folder was originally empty, in which case deleting it wouldn't result in the loss of any chain segments. So, it raises the question of whether it's worthwhile to address this particular case."

Will discuss with team

**Comment by lrettig** [comment] 2023-09-27 17:24
I ran into this error as well when upgrading from v1.12.2 to v1.13.1:

```
> geth --config config.toml 
INFO [09-27|17:03:53.763] Starting Geth on Ethereum mainnet...
INFO [09-27|17:03:53.763] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [09-27|17:03:53.767] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-27|17:03:53.769] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-27|17:03:55.033] Using leveldb as the backing database
INFO [09-27|17:03:55.033] Allocated cache and file handles         database=/home/lane/.ethereum/geth/chaindata cache=2.00GiB handles=524,288 readonly=true
INFO [09-27|17:04:10.586] Using LevelDB as the backing database
Chain metadata
  databaseVersion: 8 (0x8)
  headBlockHash: 0xcbd6373ccc36ebc40a194e1c8ae7b143890a7e68aaafee37d5c18ad8d2ed7681
  headFastBlockHash: 0xcbd6373ccc36ebc40a194e1c8ae7b143890a7e68aaafee37d5c18ad8d2ed7681
  headHeaderHash: 0xcbd6373ccc36ebc40a194e1c8ae7b143890a7e68aaafee37d5c18ad8d2ed7681
  lastPivotNumber: 15498411 (0xec7cab)
  len(snapshotSyncStatus): 283 bytes
  snapshotDisabled: false
  snapshotJournal: 6792155 bytes
  snapshotRecoveryNumber: <nil>
  snapshotRoot: 0xd5019e00530eea1297d0d43b6e180c93ec1a68296f79964dfbd473e6963f56a7
  txIndexTail: 15878395 (0xf248fb)
  fastTxLookupLimit: 2350000 (0x23dbb0)
  SkeletonSyncStatus: {"Subchains":[{"Head":15555913,"Tail":15555913,"Next":"0xfea74bfe44ababa5c4715b0ede96ab5651a4749137a5bbb74d08047aad76de80"}]}


Fatal: Could not open database: open /home/lane/.ethereum/geth/chaindata/ancient/chain/headers.cidx: no such file or directory
> geth --config config-open.toml --state.scheme=hash
INFO [09-27|17:06:45.287] Starting Geth on Ethereum mainnet...
INFO [09-27|17:06:45.287] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [09-27|17:06:45.291] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-27|17:06:45.293] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-27|17:06:46.545] Using leveldb as the backing database
INFO [09-27|17:06:46.546] Allocated cache and file handles         database=/home/lane/.ethereum/geth/chaindata cache=2.00GiB handles=524,288 readonly=true
INFO [09-27|17:07:02.278] Using LevelDB as the backing database
Chain metadata
  databaseVersion: 8 (0x8)
  headBlockHash: 0xcbd6373ccc36ebc40a194e1c8ae7b143890a7e68aaafee37d5c18ad8d2ed7681
  headFastBlockHash: 0xcbd6373ccc36ebc40a194e1c8ae7b143890a7e68aaafee37d5c18ad8d2ed7681
  headHeaderHash: 0xcbd6373ccc36ebc40a194e1c8ae7b143890a7e68aaafee37d5c18ad8d2ed7681
  lastPivotNumber: 15498411 (0xec7cab)
  len(snapshotSyncStatus): 283 bytes
  snapshotDisabled: false
  snapshotJournal: 6792155 bytes
  snapshotRecoveryNumber: <nil>
  snapshotRoot: 0xd5019e00530eea1297d0d43b6e180c93ec1a68296f79964dfbd473e6963f56a7
  txIndexTail: 15878395 (0xf248fb)
  fastTxLookupLimit: 2350000 (0x23dbb0)
  SkeletonSyncStatus: {"Subchains":[{"Head":15555913,"Tail":15555913,"Next":"0xfea74bfe44ababa5c4715b0ede96ab5651a4749137a5bbb74d08047aad76de80"}]}


Fatal: Could not open database: open /home/lane/.ethereum/geth/chaindata/ancient/chain/receipts.cidx: no such file or directory
```

I was able to work around it by running geth with `--datadir.ancient` explicitly, which was never required before (the same directory is set in my config with `DatabaseFreezer`).

**Comment by karalabe** [comment] 2023-10-05 08:43
@lrettig Could you share some details about your config.toml, specifically around datadirs and ancient folders? The folder was moved a while back but it should still find it in your old place if you have it.

**Comment by lrettig** [comment] 2023-10-06 19:23
There isn't a whole lot in the config. Let me know if you need anything else!

```
[Eth]
NetworkId = 1
SyncMode = "snap"
NoPruning = false
NoPrefetch = false
LightPeers = 100
DatabaseCache = 2048
DatabaseFreezer = "/mnt/disks/geth-hdd/ethereum"
TrieCleanCache = 1023
TrieDirtyCache = 1024
TrieTimeout = 3600000000000
SnapshotCache = 0
Preimages = true
EnablePreimageRecording = false
RPCGasCap = 25000000
RPCTxFeeCap = 1e+00
...
[Node]
DataDir = "/home/lane/.ethereum"
```

**Comment by s1na** [comment] 2023-10-17 13:15
I believe this is fixed by https://github.com/ethereum/go-ethereum/pull/28313. Otherwise please feel free to re-open.

**Closed by s1na** 2023-10-17 13:15 UTC
Labels: type:bug, status:triage
