### ISSUE TITLE
Transaction dropped and replaced after geth restart with different transfer from pending list

### ISSUE THREAD

**Issue by Gbogdann93** [ethereum/go-ethereum#21581] opened 2020-09-18 12:11 UTC
#### System information
Geth version: instance: Geth/v1.9.15-stable-0f77f34b/linux-amd64/go1.14.4
OS & Version:  Debian GNU/Linux 9

#### Expected behaviour
After geth restart previous pending transfers should be  processed into network and not replace transfer nonce with another transfer which had higher nonce and it was still in pending state. 
First transfer should've been sent to network with nonce 1075 which was his original value, second transfer nonce shouldn't be replaced with the nonce of first transfer

#### Actual behaviour
geth was keeping transfers in pending state and won't sent them out until we restart geth (txid was invalid in block explorer) 
eth.pendingTransactions - got some transfers in pending state because gasPrice used was below network average price. 
Geth keeping this transfers in pending state even when network average was more below than our transfers gas price.
Restarted geth and after this restart transfers were processed but for some of them geth updated wrong the nonce and somehow initial transfer **was replaced with another transfer with different receiver and amount** 
Here is initial transfer which was in pending state before geth restart: (nonce was 1075)
https://etherscan.io/tx/0x37bc32d205bd29a855ab832ba7bfd629e3cce738bfdd6c9e35fa43b960271bff

After geth restart transfer was automatically replaced with another transaction which had different nonce before geth restart:
https://etherscan.io/tx/0xa53fe0ef5838676d2b50285cd0e71c32230fac73b2a3ca7c094093109f647e1d

Here is  output from pendingTransactions list with initial transfer nonce and  data: 

    blockHash: null,
    blockNumber: null,
    from: "0x7f80c92ec851109aa0fbd10012ce43a0ece057ee",
    gas: 21000,
    gasPrice: 405000000000,
    hash: "0x37bc32d205bd29a855ab832ba7bfd629e3cce738bfdd6c9e35fa43b960271bff",
    input: "0x",
    nonce: 1075,
    r: "0x897004c16ec6007548a4bb04b47a2be52adbc81969c175664c4f7862a46c898d",
    s: "0x33a6d90944f960d3b6fa941c5fb045822744a7c02a6166aabea38a51edd8eb6d",
    to: "0x5d778a67c7377ec96c7cadb77d80e3b6233994ad",
    transactionIndex: null,
    v: "0x25",
    value: 12586690830000000000

#### Steps to reproduce the behaviour
Tried to replicate on test env same behaviour but without success.

Please let me know what else is needed in order to figure out this issue. We have multiple transfers dropped and replaced with huge values and funds seems are not anymore on any of addresses (neither on sender/receiver for initial transfer and replaced transfer).

**Comment by holiman** [comment] 2020-10-01 08:33
More info: https://info.etherscan.com/transaction-dropped-replaced/

**Comment by holiman** [comment] 2020-10-01 08:33
The first tx had `405Gwei` gasPrice, and the second had `420Gwei`.

**Comment by karalabe** [comment] 2020-10-01 08:36
If the original transaction appears on etherscan, it means it was correctly pushed out into the network. If it wasn't mined, it was probably underpriced compared to others in the network. Geth does not auto resend or replace any transactions, so you or some wallet you are using sent it a new one with the same nonce.

Are you using some script to automatically sign and submit transactions?

**Comment by fjl** [comment] 2020-10-01 08:38
There might be an issue with geth here, but we need to know more about how you are using the API to pinpoint exactly what the problem is.

**Comment by Gbogdann93** [comment] 2020-10-01 08:47
@fjl I am using **eth_sendTransaction** 
This geth problem seems to be also confirmed by other users and there are no certain steps to replicate it.

If we're looing into txpool/pending transactions list is empty but after geth restart there are a lot of transfers in pending state. It seems geth is not processing transfers as expected and only after restart transfers and nonce is applied correct. 

Please notice that we're using same code to send transfers out using geth on multiple environments(~ 15 -20) for 3-4 years and only on one server we got this geth issue and it looks only geth restart is fixing temporary. After some time geth won't show anything in pending list/txpool and transfer nonce number for previous transfers are applied properly. 

https://github.com/ethereum/go-ethereum/issues/21385
https://github.com/ethereum/go-ethereum/issues/21459

**Comment by karalabe** [comment] 2020-10-08 09:02
We've seen it rarely on a few nodes that the txpool got full of non-executable transactions and for some reason didn't manage to build up the executable (pending) list correctly. That might explain this issue. We'll look into it, just not sure how to repro reliably.

**Comment by karalabe** [comment] 2020-10-09 08:19
Ah, so this was fixed in Geth v1.9.16 https://github.com/ethereum/go-ethereum/pull/21255

**Closed by karalabe** 2020-10-09 08:19 UTC
Labels: status:triage
