### ISSUE TITLE
Call by golang reverts unknown reason using hardhat-deploy in local env

### ISSUE THREAD

**Issue by Aliceonly** [ethereum/go-ethereum#28678] opened 2023-12-14 13:30 UTC
#### System information

I'm using "hardhat-deploy": "^0.11.44" and "@nomicfoundation/hardhat-toolbox-viem": "^2.0.0" libs
which are recommanded by hardhat official templates (with viem)
it automatically run deploy scripts when I run command "yarn hardhat node --hostname 0.0.0.0"
but calls to local hardhat network in golang seems reverted with no reason
It leads to hard to debug in local env
but it can call in online chains

#### Expected behaviour
Plz advise me some paths to debug with golang in local env using viem and hardhat-deploy
Check hardhat-deploy to fully support for Viem which recommands by hardhat official

#### Steps to reproduce the behaviour

running 'yarn hardhat node --hostname 0.0.0.0' , it deploy contracts before local accounts shows up and didn't cost (may be the problem)

generate go files with abis :
solc --abi contracts/${name} --include-path node_modules --base-path . -o goBuild/${fileName} --overwrite
abigen --abi=goBuild/${fileName}/${fileName}.abi --pkg=${fileName} --out goBuild/${fileName}/${fileName}.go

using generated abi in go to call methods but reverted with no reason (func sig error)
but it can successfully call in online chain but failed in hardhat node

#### Version

hardhat-deploy": "^0.11.44
@nomicfoundation/hardhat-toolbox-viem
"viem": "^1.19.11"
"hardhat": "^2.19.1"
go-ethereum

**Comment by MariusVanDerWijden** [comment] 2023-12-18 11:22
This is very hard to debug. Can you add your contracts?

**Comment by krzysztof-cywinski** [comment] 2023-12-26 12:30
Hi @Aliceonly and @MariusVanDerWijden 
I've just run into the same issue.

There seems to be a problem with function selector incompatibility between the hardhat node and the go-ethereum contract bindings.
Regular RPC calls to the hardhat node such as `eth_blockNumber` or `eth_chainId` work flawlessly and return correct values. It's only when you try to call a contract using the generated bindings when the issues start.

I've tested it on several contracts with both http and ws connections with and without forking. The contracts work, because their functions are callable both with a regular RPC call and with tools such as Laika with a Metamask connected to the local node.

Interestingly, there is no issue when using the bindings on public networks. For example, I can deploy a contract to a testnet and use it with the generated binding using a public RPC. The same binding fails when calling a local RPC using testnet forking with a local hardhat node. The call still works when the local hardhat fork is called through Metamask. It seems that the issue is somewhere between the go binding and the hardhat node, because both work well on their own.

Easiest way to test would be to generate a binding for IERC20, fork Ethereum mainnet with hardhat using:
`npx hardhat node --hostname 127.0.0.1 --fork https://ethereum.publicnode.com`

When you use the generated binding to get WETH total supply with the public RPC it works:
```
client, _ := ethclient.Dial("https://ethereum.publicnode.com")
weth, _ := contracts.NewIERC20(common.HexToAddress("0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"), client)
supply, err := weth.TotalSupply(nil)
if err != nil {
	log.Fatal(err)
}
log.Println("WETH total supply: ", supply.String())
```
but if you change the RPC to `http://127.0.0.1:8545` the total supply call fails with `abi: attempting to unmarshall an empty string while arguments are expected`

making a direct `eth_call` to the hardhat fork works
```
{
  "jsonrpc": "2.0",
  "method": "eth_call",
  "params": [
    {
      "from": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
      "to": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
      "gas": "0x76c0",
      "gasPrice": "0x9184e72a000",
      "value": "0x0",
      "data": "0x18160ddd"
    },
    "latest"
  ],
  "id": 1
}
```

Any idea what the issue could be and how to debug it?

**Comment by krzysztof-cywinski** [comment] 2023-12-26 18:58
I think I managed to finally get to the bottom of this issue.
When go-ethereum creates the request it uses an `input` param instead of a `data` param.
Most RPCs seem to accept either, but the hardhat node only seems to accept `data`.
The spec available [here](https://ethereum.github.io/execution-apis/api-documentation/) specifies an `input` param so I guess this is more of a hardhat issue than a go-ethereum issue.

@Aliceonly a hacky fix is to change line 650 in `~/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.5/ethclient/ethclient.go` from `arg["input"] = hexutil.Bytes(msg.Data)` to `arg["data"] = hexutil.Bytes(msg.Data)`

I'll open an issue in the hardhat repo.

**Comment by s1na** [comment] 2024-01-03 13:30
Thanks for looking into this @krzysztof-cywinski. Indeed we stopped accepting `data` param recently. This field was deprecated a looong time ago. Sorry for the inconvenience but it was time to stop this dual-use. I will close the issue here.

**Closed by s1na** 2024-01-03 13:30 UTC
Labels: type:bug
