### ISSUE TITLE
How to subscribe to entire tx objects?

### ISSUE THREAD

**Issue by ofarukcaki** [ethereum/go-ethereum#25173] opened 2022-06-26 10:43 UTC
I wanted to add the ability to subscribe to entire tx objects (not just hashes), via websockets for example, how could I go about that?

How can I modify this function so that it will return full tx object instead of just hashes?
```go
// NewPendingTransactions creates a subscription that is triggered each time a transaction
// enters the transaction pool and was signed from one of the transactions this nodes manages.
func (api *PublicFilterAPI) NewPendingTransactions(ctx context.Context) (*rpc.Subscription, error) {
	notifier, supported := rpc.NotifierFromContext(ctx)
	if !supported {
		return &rpc.Subscription{}, rpc.ErrNotificationsUnsupported
	}

	rpcSub := notifier.CreateSubscription()

	gopool.Submit(func() {
		txHashes := make(chan []common.Hash, 128)
		pendingTxSub := api.events.SubscribePendingTxs(txHashes)

		for {
			select {
			case hashes := <-txHashes:
				// To keep the original behaviour, send a single tx hash in one notification.
				// TODO(rjl493456442) Send a batch of tx hashes in one notification
				for _, h := range hashes {
					notifier.Notify(rpcSub.ID, h)
				}
			case <-rpcSub.Err():
				pendingTxSub.Unsubscribe()
				return
			case <-notifier.Closed():
				pendingTxSub.Unsubscribe()
				return
			}
		}
	})

	return rpcSub, nil
}
```

**Comment by collagely** [comment] 2022-06-26 20:05
You can't. It is not possible to get entire transaction details, you can get only headers. Don't waste your time, it's impossible with geth

**Comment by s1na** [comment] 2022-06-27 08:14
Duplicate of [#24542](https://github.com/ethereum/go-ethereum/issues/24524). I'll mark it for triage to discuss the possibility of adding this feature.

**Comment by s1na** [comment] 2022-06-27 09:48
Closing this in favor of the other one.

**Closed by s1na** 2022-06-27 09:48 UTC
Labels: type:docs
