### ISSUE TITLE
 AppVeyor: fatal error: out of memory 

### ISSUE THREAD

**Issue by slumber1122** [ethereum/go-ethereum#15162] opened 2017-09-19 03:06 UTC
Environment: GETH_ARCH=386, MSYS2_ARCH=i686, MSYS2_BITS=32, MSYSTEM=MINGW32, PATH=C:\msys64\mingw32\bin\;C:\Program Files (x86)\NSIS\;%PATH%

[00:11:11] fatal error: out of memory
[00:11:11] 
[00:11:11] runtime stack:
[00:11:11] runtime.throw(0x7b8c10, 0xd)
[00:11:11] 	C:/go/src/runtime/panic.go:605 +0x7c
[00:11:11] runtime.(*mcache).refill(0x350a14, 0x2c, 0x33a9783c)
[00:11:11] 	C:/go/src/runtime/mcache.go:125 +0xee
[00:11:11] runtime.(*mcache).nextFree.func1()
[00:11:11] 	C:/go/src/runtime/malloc.go:557 +0x28
[00:11:11] runtime.systemstack(0x1260a000)
[00:11:11] 	C:/go/src/runtime/asm_386.s:393 +0x5e
[00:11:11] runtime.mstart()
[00:11:11] 	C:/go/src/runtime/proc.go:1125

https://ci.appveyor.com/project/ethereum/go-ethereum/build/master.3933/job/632vxmg8kwnt8uu3

**Comment by ligi** [comment] 2017-09-19 11:27
Possibly duplicate of https://github.com/ethereum/go-ethereum/issues/15157

**Closed** 2017-10-24 01:31 UTC
