### ISSUE TITLE
Rinkeby Faucet Down

### ISSUE THREAD

**Issue by StacyNLaabs** [ethereum/go-ethereum#22401] opened 2021-03-01 17:01 UTC
Rinkeby Faucet is offline. Does anyone know when this will be back up?

I am in the middle of a project. 

Help can anyone space 19 Rinkeby Eth? 

0x6e952A32331ACF84fA9569Ee1dBa8c40ADaC7EEa

**Comment by htelsiz** [comment] 2021-03-02 02:32
Desperately need some Rinkeby eth. Can anyone help out? 

0xdDB4CB8F8860759a64872D4A59e3Aae4CEd8638B

**Comment by rymuff** [comment] 2021-03-02 09:35
Duplicate of #22390

**Comment by karalabe** [comment] 2021-03-02 13:36
Sorry, had to resync the bootnode and there was no other light server on Rinkeby. It's back up now.

**Closed by karalabe** 2021-03-02 13:36 UTC
Labels: type:bug
