### ISSUE TITLE
geth-1.10.25 after "The merge" event my syncmode light can't find peers.

### ISSUE THREAD

**Issue by aquynh1682** [ethereum/go-ethereum#25850] opened 2022-09-22 10:08 UTC
updated to the latest version: geth-linux-amd64-1.10.25-69568c55
and start geth like this:
`/usr/bin/geth --datadir "/opt/ethereum" --mainnet --ws --http --http.api="eth,web3,net,personal,miner" --http.addr 0.0.0.0 --http.port 8502 --authrpc.vhosts 0.0.0.0 --syncmode light --authrpc.jwtsecret=/opt/jwtsecret`

then shows as follows:

```
INFO [09-22|09:42:07.766] Gasprice oracle is ignoring threshold set threshold=2
WARN [09-22|09:42:07.766] Unclean shutdown detected                booted=2022-09-22T03:48:03+0000 age=5h54m4s
WARN [09-22|09:42:07.766] Catalyst mode enabled                    protocol=les
INFO [09-22|09:42:07.766] Starting peer-to-peer node               instance=Geth/v1.10.25-stable-69568c55/linux-amd64/go1.18.5
INFO [09-22|09:42:07.808] New local node record                    seq=1,663,771,439,010 id=adb48b4b86b0f512 ip=127.0.0.1 udp=30303 tcp=30303
INFO [09-22|09:42:07.809] IPC endpoint opened                      url=/opt/ethereum/geth.ipc
ERROR[09-22|09:42:07.809] Unavailable modules in HTTP API list     unavailable=[miner] available="[admin debug web3 eth txpool personal ethash net les vflux]"
INFO [09-22|09:42:07.809] Loaded JWT secret file                   path=/opt/jwtsecret crc32=0x8350073d
INFO [09-22|09:42:07.810] HTTP server started                      endpoint=[::]:8502 auth=false prefix= cors= vhosts=localhost
INFO [09-22|09:42:07.810] WebSocket enabled                        url=ws://127.0.0.1:8546
INFO [09-22|09:42:07.810] WebSocket enabled                        url=ws://127.0.0.1:8551
INFO [09-22|09:42:07.810] HTTP server started                      endpoint=127.0.0.1:8551 auth=true  prefix= cors=localhost vhosts=0.0.0.0
WARN [09-22|09:42:07.810] Light client mode is an experimental feature 
INFO [09-22|09:42:07.814] Started P2P networking                   self=enode://fe2689206a76c09489e5e0a219534fffa694c273ea3171a01c736efe475dc71c2cf09cb33ae2f4b63ac3653b32e0f766ea72f7699faea0bcae869c9e584af81e@127.0.0.1:30303
INFO [09-22|09:42:26.510] Looking for peers                        peercount=0 tried=3 static=0
INFO [09-22|09:42:37.660] Looking for peers                        peercount=0 tried=6 static=0
INFO [09-22|09:42:48.512] Looking for peers                        peercount=0 tried=4 static=0
INFO [09-22|09:42:58.751] Looking for peers                        peercount=0 tried=4 static=0
INFO [09-22|09:43:09.654] Looking for peers                        peercount=0 tried=7 static=0
INFO [09-22|09:43:20.098] Looking for peers                        peercount=0 tried=6 static=0
INFO [09-22|09:43:30.498] Looking for peers                        peercount=0 tried=5 static=0
INFO [09-22|09:43:41.516] Looking for peers                        peercount=0 tried=6 static=0
INFO [09-22|09:43:51.573] Looking for peers                        peercount=0 tried=4 static=0
INFO [09-22|09:44:01.582] Looking for peers                        peercount=0 tried=7 static=0
INFO [09-22|09:44:11.630] Looking for peers                        peercount=0 tried=6 static=0
INFO [09-22|09:44:22.595] Looking for peers                        peercount=0 tried=3 static=0
INFO [09-22|09:44:32.666] Looking for peers                        peercount=0 tried=6 static=0
INFO [09-22|09:44:42.676] Looking for peers                        peercount=0 tried=8 static=0
INFO [09-22|09:44:53.545] Looking for peers                        peercount=0 tried=5 static=0
INFO [09-22|09:45:03.667] Looking for peers                        peercount=0 tried=6 static=0
INFO [09-22|09:45:14.103] Looking for peers                        peercount=0 tried=5 static=0
INFO [09-22|09:45:24.151] Looking for peers                        peercount=0 tried=7 static=0
INFO [09-22|09:45:34.684] Looking for peers                        peercount=0 tried=4 static=0
INFO [09-22|09:45:45.028] Looking for peers                        peercount=0 tried=6 static=0
INFO [09-22|09:45:55.667] Looking for peers                        peercount=0 tried=5 static=0
INFO [09-22|09:46:05.703] Looking for peers                        peercount=0 tried=1 static=0
INFO [09-22|09:46:16.681] Looking for peers                        peercount=0 tried=7 static=0
INFO [09-22|09:46:20.735] New local node record                    seq=1,663,771,439,011 id=adb48b4b86b0f512 ip=58.186.90.122 udp=62601 tcp=30303
INFO [09-22|09:46:28.589] Looking for peers                        peercount=0 tried=11 static=0
INFO [09-22|09:46:38.726] Looking for peers                        peercount=0 tried=4  static=0
INFO [09-22|09:46:48.747] Looking for peers                        peercount=0 tried=5  static=0
INFO [09-22|09:46:59.689] Looking for peers                        peercount=0 tried=4  static=0
INFO [09-22|09:47:09.707] Looking for peers                        peercount=0 tried=3  static=0
INFO [09-22|09:47:19.718] Looking for peers                        peercount=0 tried=8  static=0
INFO [09-22|09:47:29.758] Looking for peers                        peercount=0 tried=6  static=0
INFO [09-22|09:47:39.771] Looking for peers                        peercount=0 tried=3  static=0
INFO [09-22|09:47:50.637] Looking for peers                        peercount=0 tried=4  static=0
INFO [09-22|09:48:01.779] Looking for peers                        peercount=0 tried=8  static=0
INFO [09-22|09:48:11.805] Looking for peers                        peercount=0 tried=4  static=0
INFO [09-22|09:48:22.771] Looking for peers                        peercount=0 tried=6  static=0
INFO [09-22|09:48:33.751] Looking for peers                        peercount=0 tried=11 static=0
INFO [09-22|09:48:43.837] Looking for peers                        peercount=0 tried=4  static=0
INFO [09-22|09:48:54.230] Looking for peers                        peercount=0 tried=3  static=0
INFO [09-22|09:49:04.245] Looking for peers                        peercount=0 tried=7  static=0
INFO [09-22|09:49:15.805] Looking for peers                        peercount=0 tried=4  static=0
INFO [09-22|09:49:25.820] Looking for peers                        peercount=0 tried=5  static=0
INFO [09-22|09:49:36.787] Looking for peers                        peercount=0 tried=4  static=0
INFO [09-22|09:49:46.804] Looking for peers                        peercount=0 tried=4  static=0
INFO [09-22|09:49:56.835] Looking for peers                        peercount=0 tried=6  static=0
INFO [09-22|09:50:07.848] Looking for peers                        peercount=0 tried=8  static=0
INFO [09-22|09:50:19.855] Looking for peers                        peercount=0 tried=2  static=0
INFO [09-22|09:50:29.855] Looking for peers                        peercount=0 tried=5  static=0
INFO [09-22|09:50:39.982] Looking for peers                        peercount=0 tried=7  static=0
INFO [09-22|09:50:50.319] Looking for peers                        peercount=0 tried=6  static=0
INFO [09-22|09:51:01.843] Looking for peers                        peercount=0 tried=4  static=0
INFO [09-22|09:51:11.972] Looking for peers                        peercount=0 tried=6  static=0
INFO [09-22|09:51:22.005] Looking for peers                        peercount=0 tried=3  static=0
INFO [09-22|09:51:32.780] Looking for peers                        peercount=0 tried=10 static=0
INFO [09-22|09:51:42.868] Looking for peers                        peercount=0 tried=6  static=0

>  net.peerCount
1
> net.listening
true
```
I tried the way like in this link: https://nimbus.guide/el-light-client.html. But still not working, please give me a hand. Thanks very much.

**Comment by s1na** [comment] 2022-09-23 09:46
Duplicate of #25623

**Closed** 2022-09-27 08:03 UTC
Labels: type:docs
