### ISSUE TITLE
Geth (since recently) RPC port can't be reached through an AWS load balancer - health check (dumb HTTP GET on /) is failing with 415

### ISSUE THREAD

**Issue by rangelife** [ethereum/go-ethereum#15490] opened 2017-11-15 14:22 UTC
Latest versions of geth can't be run behind an AWS load balancer. Their health checks send a HTTP GET to /, without a Content-Type: application/json header that's now required.

Some new code (https://github.com/ethereum/go-ethereum/blame/4fe30bf5ade8849bb3971a0edad95d17d99e8778/rpc/http.go) causes such requests to be rejected with a 415 (bad media type).

Hence the RPC port is never detected healthy and never becomes available (and in our case ECS kills the task too)

#### System information

Geth version: 1.7.3-unstable
OS & Version: Linux (docker on ECS)
Commit hash : 3ee86a57f328530707974288e9db87b7c05283f9

#### Expected behaviour

HTTP GET on / should not care about content type (particularly as there's no body anyway)

#### Actual behaviour

HTTP GET on / with no "Content-Type: application/json" fails with 415

#### Steps to reproduce the behaviour

Run a geth on an EC2 somewhere. Set up an ELB to point to it, with health check to HTTP /

#### Backtrace

n/a

**Comment by karalabe** [comment] 2017-11-15 14:25
This restriction was added in https://github.com/ethereum/go-ethereum/pull/15220. The reason is that without this check, a browser can create HTTP requests that circumvent the CORS checks.

**Comment by rangelife** [comment] 2017-11-15 14:49
Even GETs? Isn't the "real" functionality (given it's RPC) accessed only via POST?

**Comment by rangelife** [comment] 2017-11-15 14:58
It seems geth doesn't care which HTTP method you use, they all get serviced:

rob@Rob-Macbook:go-ethereum 1db4$ curl -X POST http://localhost:8545 --data-binary "{\"jsonrpc\":\"2.0\",\"id\":999,\"method\":\"eth_blockNumber\"}"
{"jsonrpc":"2.0","id":999,"result":"0x149cc"}
rob@Rob-Macbook:go-ethereum 1db4$ curl -X GET http://localhost:8545 --data-binary "{\"jsonrpc\":\"2.0\",\"id\":999,\"method\":\"eth_blockNumber\"}"
{"jsonrpc":"2.0","id":999,"result":"0x149cc"}
rob@Rob-Macbook:go-ethereum 1db4$ curl -X PUT http://localhost:8545 --data-binary "{\"jsonrpc\":\"2.0\",\"id\":999,\"method\":\"eth_blockNumber\"}"
{"jsonrpc":"2.0","id":999,"result":"0x149cc"}
rob@Rob-Macbook:go-ethereum 1db4$ curl -X DELETE http://localhost:8545 --data-binary "{\"jsonrpc\":\"2.0\",\"id\":999,\"method\":\"eth_blockNumber\"}"
{"jsonrpc":"2.0","id":999,"result":"0x149cc"}

**Comment by karalabe** [comment] 2017-11-15 15:00
Yeah, I think we were considering to forbid GET, but were afraid that people rely on it. PUT and DELETE should be disallowed imho altogether.

**Comment by karalabe** [comment] 2017-11-15 15:11
I'll think about this issue, it does seem an odd thing to break. Maybe we can add an explicit exception to cover this scenario.

**Comment by rangelife** [comment] 2017-11-15 17:21
either that or implement a specific health check GET endpoint '/healthz' or the like (but exactly what it takes for an instance of geth to consider itself "healthy" might be a bit of a pandora's box - synced? has peers? so probably best to respond with 200 just to prove geth is reachable and not jammed somehow)

**Comment by karalabe** [comment] 2017-11-16 11:56
@rangelife Could you try if this PR fixes the issue for you? https://github.com/ethereum/go-ethereum/pull/15496

**Comment by rangelife** [comment] 2017-11-16 12:21
Looks great, thanks for quick response.

I've since found out that you can tweak the health check to interpret particular status codes as "success", but expecting failure as a sign of success never feels good.

**Comment by karalabe** [comment] 2017-11-16 15:03
Should be fixed on master now.

**Closed by karalabe** 2017-11-16 15:03 UTC

**Comment by zhahaoyu** [comment] 2018-01-29 07:37
I ran `geth --testnet --syncmode "fast"` on EC2 and it does not sync with any block. Wonder if it is caused by the same issue.

**Comment by zhahaoyu** [comment] 2018-01-29 07:38
The weird thing is if seems to sync fine under regular mode, it is just not working on "fast" or "light"
