### ISSUE TITLE
`eth_getLogs` and other filter APIs not returning expected log entries.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/go-ethereum#15404] opened 2017-10-30 16:33 UTC
#### System information

Geth version: `Geth/v1.7.2-stable-1db4ecdc/darwin-amd64/go1.9.1`
OS & Version: OSX

#### Expected behaviour

Issue request over JSON RPC to `eth_getLogs` with params 

```
[{'address': '0x6090a6e47849629b7245dfa1ca21d94cd15878ef',
 'fromBlock': '0x3cfe4c',
 'toBlock': '0x3cfe56',
 'topics': ['0x0f0c27adfd84b60b6f456b0e87cdccb1e5fb9603991588d87fa99f5b6b61e670']}]
```

Expect to get the following log entry back (from https://etherscan.io/tx/0x05712456eca3acb77a524960757240088af05f0ddb2a4fb2a7cd6d8fb2a8880f).

```
[{'address': '0x6090a6e47849629b7245dfa1ca21d94cd15878ef',
  'blockHash': '0x3f4d8282bcdd2d2637ada6693ac8f2df498475223c2626ca33a16eb56f74e2e0',
  'blockNumber': '0x3cfe50',
  'data': '0x000000000000000000000000000000000000000000000000002386f26fc10000000000000000000000000000000000000000000000000000000000005961c025',
  'logIndex': '0x1d',
  'removed': False,
  'topics': ['0x0f0c27adfd84b60b6f456b0e87cdccb1e5fb9603991588d87fa99f5b6b61e670',
   '0x4981ae698e550a328ba9008e83467cf24b3ab26163ae47bad5d0d109a717fc45',
   '0x0000000000000000000000003fb14ab42b18736fc4b3ec9f88b80fe5829527fb'],
  'transactionHash': '0x05712456eca3acb77a524960757240088af05f0ddb2a4fb2a7cd6d8fb2a8880f',
  'transactionIndex': '0x1f'},
 {'address': '0x6090a6e47849629b7245dfa1ca21d94cd15878ef',
  'blockHash': '0x3f4d8282bcdd2d2637ada6693ac8f2df498475223c2626ca33a16eb56f74e2e0',
  'blockNumber': '0x3cfe50',
  'data': '0x000000000000000000000000000000000000000000000000002386f26fc10000000000000000000000000000000000000000000000000000000000005948d62a',
  'logIndex': '0x20',
  'removed': False,
  'topics': ['0x0f0c27adfd84b60b6f456b0e87cdccb1e5fb9603991588d87fa99f5b6b61e670',
   '0x7d4646bbc88eccd949cb3aeed6da58f399c61f33beaa210d19dc535f2485801a',
   '0x00000000000000000000000022786eb851d2172bbf8145e0f9a31d217ef19521'],
  'transactionHash': '0x085805dcf58263e9b3f78dfcb3fcfc2fdabd664a40040bf0d40870e846d5f57c',
  'transactionIndex': '0x22'}]
```

#### Actual behaviour

Instead of getting the expected log entry, I get back an empty list.

If instead, I change the filter params to be:

```
{'address': '0x6090a6e47849629b7245dfa1ca21d94cd15878ef',
 'fromBlock': '0x3cfe50',
 'toBlock': '0x3cfe50',
 'topics': ['0x0f0c27adfd84b60b6f456b0e87cdccb1e5fb9603991588d87fa99f5b6b61e670']}
```

Then I get back the expected log entry.

**Comment by vijayendrabvs** [comment] 2017-10-31 20:54
Looks like this may be related to https://github.com/ethereum/go-ethereum/issues/15359 . I'm new here, but can start off by taking this up if no one else is working on it.

**Comment by karalabe** [comment] 2017-11-15 12:37
This issue is a duplicate of https://github.com/ethereum/go-ethereum/issues/15309, and is fixed by https://github.com/ethereum/go-ethereum/pull/15489 . It's merged on master and will roll out into a stable release on Monday.

**Comment by karalabe** [comment] 2017-11-15 12:38
@pipermerriam Perhaps try to see if latest master does indeed fix it?

**Closed by karalabe** 2017-11-15 12:37 UTC
