### ISSUE TITLE
GetBlockHeaders [reverse = true, skip = 0, origin type = hash] duplicates genesis in response

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/go-ethereum#2076] opened 2015-12-15 16:01 UTC
E.g. when sending `GetBlockHeaders(Origin = blockHash, Amount = 1000, Skip = 1, Reverse = true)` (where `blockHash` is the block #4) I'm getting block headers `#4, #2, #0`
When sending with `Skip = 0` getting headers `#4, #3, #2, #1, #0, #0` (two zero blocks at the end)
The problem seems to be in that line:
https://github.com/ethereum/go-ethereum/blob/master/eth/handler.go#L421

**Comment by karalabe** [comment] 2015-12-15 17:06
Hmmm, indeed I've managed to reproduce it. The bug is not in that line of code, it's a side effect of using the query itself as an iterator. When we reach the root of the chain, the parent of the genesis block is the nil hash, which is interpreted in a special way in the code. I guess we haven't caught this issue because we don't use this type of queries currently in the code. Let me see how to cleanly solve this.

**Comment by karalabe** [comment] 2015-12-15 17:33
This should be fixed by the commit linked above. If you try it out yourself, please report back whether it worked or not. Otherwise is should be reviewed fairly quickly as it's a trivial fix and land the develop I guess by tonight.

**Comment by Nashatyrev** [comment] 2015-12-15 18:57
We are currently not using such messages as well, just accidentally found this problem. 
Thanks for prompt response!

**Comment by karalabe** [comment] 2015-12-18 14:08
Fixed and merged. Thanks for the report!

**Closed by karalabe** 2015-12-18 14:08 UTC
Labels: bug, in progress
