### ISSUE TITLE
"Nonce too low" error message on faucet.rinkeby.io

### ISSUE THREAD

**Issue by zceejkr** [ethereum/go-ethereum#16602] opened 2018-04-29 12:13 UTC
Hi,

Request ether via https://faucet.rinkeby.io/ throws an error message "Nonce too low" using both Twitter and G+. 

System information
OS & Version: Mac, Chrome(version 65) and Safari.

Expected behaviour
Requesting ether using Google+/Twitter URL should transfer ether.

Actual behaviour
Clicking "Give me ether" throws an error "Nonce too low". 

Steps to reproduce the behaviour
chrome-ether-rinkeby

<img width="623" alt="screen shot 2018-04-29 at 14 12 59" src="https://user-images.githubusercontent.com/1362446/39406470-74fbb664-4bb7-11e8-86a4-211542d46342.png">

Open Chrome (or Safari), input https://faucet.rinkeby.io/, and copy URL, and then click "give me ether".

**Comment by zceejkr** [comment] 2018-04-29 12:15
Also, since I am trying to follow a course where I need some ether on Rinkby to proceed, if anyone would be willing to send some to 0x51baB87c42d384d1cD3056d52D97C84ddaa65fe4, I would much appreciate it.

**Comment by ligi** [comment] 2018-04-29 14:11
I can confirm the error - just send you some rinkeby ETH (https://rinkeby.etherscan.io/tx/0xc37ff3be57a934cf3dffa78f6986b6f31ad51301fa6bd8df0fa247a88a3166ef)- let me know when you need more and ideally send some back when the faucet is working again.

**Comment by kristallizer** [comment] 2018-04-29 15:33
Hey, can you send some rinkeby ETH my way too? I'll send it back once the faucet is working again. Address: 0x16f02950941773F9a38A504F1d14293c42CdD026

**Comment by zceejkr** [comment] 2018-04-29 15:55
Thanks @ligi, will do.

**Comment by ligi** [comment] 2018-04-29 16:16
@kristallizer https://rinkeby.etherscan.io/tx/0x72fa1f12b4be27a60458c34aaeacc680f06822d1e5e7f3d3abfde3e2ecdb1154
@zceejkr great!

**Comment by hqthao** [comment] 2018-04-29 21:04
Wow. Looks like this is the recent issue. Please send me some ethers, I will send back later when everything normal again.
My address is: 0x627306090abaB3A6e1400e9345bC60c78a8BEf57

**Comment by ligi** [comment] 2018-04-29 21:14
https://rinkeby.etherscan.io/tx/0xbbe124098021eff74dc56b26d6bc983ac6b8420b9a7d92bddeec61daa532c0ad

**Comment by katiemusic** [comment] 2018-04-29 22:13
Same issue here! 0xbB0ab2Eb8c878259F8D39395D464fbE65a1f3585 if someone could send me some, that would be great!

**Comment by MheniMerz** [comment] 2018-04-30 01:15
Please Please send some - 0x0ab3012d3d9654a02743e5e083051187bc22b781 ill send it back when its back up again

**Comment by somangsu** [comment] 2018-04-30 02:04
following an etherium course need some Etherium on  Rinkeby i get nonce to low error , 
could some one please some ether to 0xAd0fCB235369194705473C7426d36FF6562A8C64

**Comment by Fariha1123** [comment] 2018-04-30 04:44
same error, if someone could send some to my address 0xfc788E41fF2405a6b032F18abA8A90bE45E335b6, it will be much appreciated !

**Comment by ArnoldoM23** [comment] 2018-04-30 04:54
same error, if someone could send me some to my address as well that would be much appreciated. 
My address 0xb70Cc93b57893eD8397e642f741dd808794Cf4DF

**Comment by hao33828** [comment] 2018-04-30 04:55
same error, if someone could send some to my address would be much appreciated!
`0xc935ad70657713f06152eadee95d9cf9eba8a525` thanks!!!

**Comment by p6sanders** [comment] 2018-04-30 05:14
same technical issues please send me some ether to my address 0x1Da5EF96a7A488E85A323fd0e5198d1Cc091Aeaf Thanks.

**Comment by AzurinesArt** [comment] 2018-04-30 05:15
Same problem. I could use some test funds, and I can return them when the faucet is fixed... 0x28BA9aF680bAdbC0AAaE2e522546e4D1b5a52351 Thank you.

**Comment by zsabbasi** [comment] 2018-04-30 05:27
Same here, hopefully will be resolved soon

**Comment by jeremyondrey** [comment] 2018-04-30 08:30
having the same error, if someone had some test ether that would be great. anybody know more about what the actual issue here is?
0x518af4d12f66f54f2f0855e3f03f7c6ea41d021c

**Comment by celavek** [comment] 2018-04-30 09:29
Same here. I think the requests are piling up ...
0x0629120d88E7380194170c602b9B6d6F00b2a6D5

**Comment by ligi** [comment] 2018-04-30 09:57
OK - send rinkeby Ether to all of you - please let me know when you need more - and please send some back once the faucet is working again - hope @karalabe can have a look into this soon

**Comment by ligi** [comment] 2018-04-30 11:37
Another round of rinkeby ether is out

**Comment by techamazed** [comment] 2018-04-30 11:49
thank you+ @ligi

**Comment by dalmiasiddharth** [comment] 2018-04-30 13:00
Hi, I am learning to dev apps using rinkeby network. Please send me some too, will send back once everything is fixed. Address: 0x284678812218ae11B1f06cE16405Eb2B1ddAFA2b. Thank you and really appreciate it.

**Comment by Nufflee** [comment] 2018-04-30 13:28
Same error here... could anyone send some my way? 0xAD7679737A729a1a9DF6915BB6223372aA138c19 Thanks in advance!

**Comment by marijndegen** [comment] 2018-04-30 13:41
Mhh... I just got my testether a couple of days ago, i only have 3 so i'm afraid i can't go around.. Please consider using another testnet, until this issue is fixed.
Ropsten
[Kovan](https://github.com/kovan-testnet/faucet)
Rinkeby

If you use are planning on using Kovan, you can get your first 5 testether over [here](https://gitter.im/kovan-testnet/faucet) , there will be a manual test of some kind. Hope this helps guys,

Pleace and love.

**Comment by und0ck3d** [comment] 2018-04-30 14:10
I'm trying to test a dapp, could someone send me at least 0.3 testeth plz?

Address: 0x4dfd7c0bB486d9A39cEBB805F1D5B1b51cAAa333

Thanks in advance, I'll send back as soon as the faucet is up again.

**Comment by uxpulser** [comment] 2018-04-30 14:54
Ahh im learning as well and need some rinkebys eth..

address: 0xe9c42eab864cbdc8a07a2361210372cf0464e189

Thanks much in advance!!!

**Comment by nexter101** [comment] 2018-04-30 15:14
Could anyone please send me some test ether at 0x5aF52ffeAFcC27AD59051c6Ce159f6BA33521531 I am stuck in a course because of it.

**Comment by bharat1438** [comment] 2018-04-30 15:50
can anyone  pls send some test ether at 0x96C06461c0cB5699AE945B6C13F702284Be4d04E 

appreciate if you can help me

**Comment by jlogelin** [comment] 2018-04-30 16:29
Hello I am trying to get some Rinkeby test ether and keep getting error 'nonce too low' - please help!

https://twitter.com/0xlodge/status/990990809922236422

**Comment by yompr** [comment] 2018-04-30 17:37
well. I hate to join the list.. but.. if anyone can send some to : 
0x0a83a5100aef2b48908a8585780315df0a79d768
that would be cool..

Thanks

**Comment by RonMath** [comment] 2018-04-30 17:46
Same issue here!
Two options:
- Someone please send me some small amount of Rinkeby ETH - highly appreciated !! 0xf1a777a93f504797c80c8e7f9306328879503578
- Please link me to a "how to" on transferring Rinkeby ETH from one wallet to another ...?

**Comment by gasiort** [comment] 2018-04-30 17:58
Appreciate any help !

0xcE3927353d48973a3C277E0958e8E3e6fFd39e02

Thanks much in advance!!!

**Comment by brushcode** [comment] 2018-04-30 18:05
The same problem with me...If anyone could send me some ETH at 0xF824be3afac20BA5511Af79951999E4A87A13249 I ll return when rinkeby faucet starts working again

**Comment by 0CD0** [comment] 2018-04-30 18:08
Appreciate any help!  
0x9e8904EC084612a0e2b7BDC9d65209FcCADDA12F 
Thanks you so much for helping me get some Eth! 
(I'm working on my final project QAQ and I'm about to run out of my eth for testing...)

**Comment by avraw** [comment] 2018-04-30 18:08
0xFF2576880c33de24fDf0448FD1a82f0A895a69f4
Please look into this ! thank!

**Comment by octrends** [comment] 2018-04-30 18:14
plz send me few ether too, will return once i get from rinkby, appreciate it.
0xe1f15De1390EC1B9482D277462dFd3B09acFC18e

**Comment by akhilnair003** [comment] 2018-04-30 18:16
Please send some ethers.
0xf978cd02e1e773c7aa7f476f26cda1fd8eae0af2

**Comment by romeokienzler** [comment] 2018-04-30 19:48
Same problem here, please send me some ETH if possible 0x644c04edAD2e8Fe52e6e12680A28Fbf18

**Comment by acrylix** [comment] 2018-04-30 20:09
Help! plese send rinkeby eth ! 0xbad1932f74359eaf486f24c9e96859657fb5139e THANKS

**Comment by POP24** [comment] 2018-04-30 20:50
0x52F0683472FfC82258DFc52Ef2834b853c74b599  can yo usend me some rinkeby eth please ? thx a lot !

**Comment by handregister** [comment] 2018-04-30 20:58
0x3C67AfC87ddE7cFEc3C89295AcFF2bec17253Aea

**Comment by jurgenfink** [comment] 2018-04-30 21:01
@zceejkr I have sent 10 rinkeby ETH - good luck
@POP24 I have sent 10 rinkeby ETH to you as well - good luck
@handregister  also  10 rinkeby ETH - good luck
I am private user, but I know how it is when gas is missing for testing -- good luck to all of you :+1:

**Comment by bharat1438** [comment] 2018-04-30 21:57
thanks @jurgenfink

**Comment by jurgenfink** [comment] 2018-04-30 21:59
@ligi  trying to help you

I have sent 10 rinkeby ETH to the following members each:
@p6sanders
@AzurinesArt
@kenesu
@jeremyondrey
@celavek
@betimbryma
@CryptoBeginner
@dalmiasiddharth
@Nufflee
@und0ck3d
@uxpulser
@nexter101
@techamazed
@bharat1438
@yompr
@RonMath
@gasiort
@brushcode
@0CD0
@avraw
@octrends
@akhilnair003

@romeokienzler  some characters missing in your address, please verify

**Comment by porkchop** [comment] 2018-04-30 22:00
If anyone has some extra rinkeby eth too spare, I could also use some. Thank you very kindly 0xb9da6dd6ed488ffcdad3e34b003a8e277f609c18

**Comment by handregister** [comment] 2018-04-30 22:05
porkchop, sent you 2

**Comment by porkchop** [comment] 2018-04-30 22:06
thank you @handregister !

**Comment by SerpicoDEV** [comment] 2018-04-30 22:06
Same problem here, please send me some ETH if possible... thanks.  0x5b234b816b6fbcAd04Cef58c0B503F8395F0f306

**Comment by handregister** [comment] 2018-04-30 22:09
SerpicoDEV, I sent you 1.5.

**Comment by GilbertHeywood** [comment] 2018-04-30 22:13
Could you also spare some to me? 10 would be great! Thanks! 0x26A2735035AC6c6c1e760167f35ac80753320760

**Comment by handregister** [comment] 2018-04-30 22:15
BTW, I have never seen anything more stupid in software, where fake money is preventing people from testing.  

I have been a software architect and developer for decades, and the goal of software was to enable people, not disable.

**Comment by RyouichiHatanaka** [comment] 2018-04-30 22:29
Hey everybody, I am experiencing the same issue - nonce too low. Could someone please send me some Ether to 0x345086e0a383a8694cb8090E955915BB15dF55a3?
Here is my Tweet: https://twitter.com/Sheizu_Rinkeby/status/991079070564868096

Thank you very much in advance!

**Comment by jurgenfink** [comment] 2018-04-30 22:35
@porkchop and here another 8 ETH, as @handregister has sent you 2 already ...
Teamwork, he he

**Comment by jurgenfink** [comment] 2018-04-30 22:39
10 rinkeby ETH sent to:

@GilbertHeywood
@SerpicoDEV

Now I am getting close to broke, he he he 
Good Luck to all of you and lucky testing and thanks to @ligi for all the good work.

**Comment by Manuel1337** [comment] 2018-04-30 22:40
Would be very kind, if anybody has some extra rinkeby eth too spare. I am getting the nonce to low error too.. 
Thanks!
0x6436511030Dd1Ad167bFC69a366e81308EB85b12

**Comment by porkchop** [comment] 2018-04-30 22:40
hey thanks a lot @jurgenfink !!!

**Comment by jurgenfink** [comment] 2018-04-30 22:47
Here you go @Manuel1337  10 ETH on your way :smirk:

**Comment by RyouichiHatanaka** [comment] 2018-04-30 22:50
hey @jurgenfink , mind if I beg for some ether from you too? :-)

**Comment by petergrubercom** [comment] 2018-04-30 23:00
I need a fee rinkeby ETH to teach a class ... please!
0xCa20f97aEcfF81EafBA37bf731E0b268b977B646

**Comment by jurgenfink** [comment] 2018-04-30 23:55
Sure @RyouichiHatanaka  10 rinkeby ETH on your way :smirk:

**Comment by jurgenfink** [comment] 2018-04-30 23:57
Sure @petergrubercom 10 rinkeby ETH on your way :smirk:  - good luck for your class ...

**Comment by fenglb** [comment] 2018-05-01 00:58
hi @jurgenfink, I need some rinkeby ETH to test my program, I also got the nonce too low error.
If you send me some, it would much appreciate it.
my address: 0x5c350c9bf0c2a62bd09c7b8b63e48fe90830c3d4

**Comment by JordoBrooks** [comment] 2018-05-01 01:07
Hoping to run some tests but getting the "nonce too low" error as well.
A Rinkeby ETH donation would be very appreciated! :)

0x67E2D29468002aBf7116A6CaE701c60861021c59

**Comment by thdaraujo** [comment] 2018-05-01 01:34
yeah, doesn't work for me either :(
I need some so I can do a presentation on how to deploy a contract. Could somebody send me some?
Here's my address: 0xb13e06510cBe05357D1D05EDfB67a12D5e0a2051

Thank you very much!

**Comment by nexter101** [comment] 2018-05-01 01:38
Thanks @jurgenfink!!

**Comment by heartziq** [comment] 2018-05-01 01:43
I exp the same error - nonce too low.

Can someone send me some Ether, pretty please =)

0x0F33430F1445f701737eac0fAD24691152DBf93D

**Comment by jurgenfink** [comment] 2018-05-01 01:48
Hey @fenglb  I have sent you 3 ETH (sorry, running low now ...), hope this helps :smirk:

**Comment by heartziq** [comment] 2018-05-01 01:50
how does one generate ETH on a test network?

sorry, I am new to blockchain :D

**Comment by ryanai3** [comment] 2018-05-01 01:57
@jurgenfink any chance you can send me 0.5 ETH? Need it for a DAO class project.
0x0fDa87B9746F9a810f74a478231d62F6e4c55735
I'll return it once the faucet is working again :)

**Comment by jurgenfink** [comment] 2018-05-01 01:58
@JordoBrooks  have sent you 3 ETH
@thdaraujo       have sent you 3 ETH
@heartziq         have sent you 3 ETH

Good Luck :smirk:

**Comment by thdaraujo** [comment] 2018-05-01 02:01
thank you @jurgenfink !

**Comment by seanahrens** [comment] 2018-05-01 02:34
Could you please send me some ETH? Same problem as above!

0x292ccc401E22966756f231146FB47ecC355991EE

**Comment by judson-douglas** [comment] 2018-05-01 02:50
Same issue as all above, please me ETH if you can? Thanks!
0x1f67BC0e33a069368E601c22a0B3eAF4B9b6ff83

**Comment by yesri** [comment] 2018-05-01 02:57
Same issue here. Please send me some ETH if possible. thanks! :) 0x80ec7c0055c829d7da7d3c6efac922b66bbfe3a2

**Comment by lqh1991** [comment] 2018-05-01 03:00
same issue, pls send me some ETH for test if possible. thanks!
0xaA53b23FEDAF33D88e83B799687088F00d21bdA6

**Comment by CoinzCollector** [comment] 2018-05-01 03:03
I day I finally decide to start experimenting... This doesn't work...

Please donate for my test...
0x9Ec782535628CE71D75aa053F9a0E49f1E91f2db

Thanks in Advance!!!

**Comment by jurgenfink** [comment] 2018-05-01 03:08
@seanahrens  have sent you 2 ETH
@judson-douglas have sent you 2 ETH
@yesri  have sent you 2 ETH
@lqh1991 have sent you 2 ETH
@CoinzCollector  have sent you 2 ETH (yes, it's Murphy's Law, ja ja ja :laughing:  )

**Comment by ajunge** [comment] 2018-05-01 03:08
Same issue here. Please send some eth here: 0x4E09359dfe3337eeAf54F993C15D10F104eF6AED

**Comment by CoinzCollector** [comment] 2018-05-01 03:08
Jajaja... Yes it is man... Thank you @jurgenfink

**Comment by ajunge** [comment] 2018-05-01 03:08
What's the error?

**Comment by jurgenfink** [comment] 2018-05-01 03:32
@ajunge  have sent you 2 ETH 
(don't know the error - I suppose they are working on it, normally they fix issues quickly, issue started on yesterday on Sunday ...)
@streetlist  have sent you 2 ETH

**Comment by ChenLi0830** [comment] 2018-05-01 04:48
The same issue here, could someone send ETH to this address? 0x8473d23aaaffb0ac586d6d45f77663b4dc2b6321

Thank you in advance

**Comment by jgmoises** [comment] 2018-05-01 05:26
Same Issue for me... please Rikneby ETH to: 0x046d6b110dd22265d1ecec915be96e617341c8a3

**Comment by birdca** [comment] 2018-05-01 06:54
same issue... :|
0xcf88ec5e21e5208edd778569b70aa7f46b597d35

**Comment by Direktor1** [comment] 2018-05-01 07:45
Same issue here, need some ETH for a project. Would greatly appreciate it and will return the favor once the faucet works again! 

Rinkeby Eth:   0x1a2863Cf99C1E67A03A018e892d844CF993D9573

**Comment by manojnetsmartz** [comment] 2018-05-01 09:06
Hi I am learning a course where I need some ether on Rinkby to proceed, if anyone would be willing to send some to 0xc5d69269C2F5DA4EA099cfF583e5ddA43311A1cc, Would return the same once done.

**Comment by grahamturk** [comment] 2018-05-01 09:14
Same issue- trying to test smart contract deployment but need some Ether. Some test tokens would be greatly appreciated! 0x37b2b5fc2c8ff3a8eabca7242291dd3c4378e2f1

**Comment by RonMath** [comment] 2018-05-01 10:10
Dear Jürgen,
Thank you so much, thats awesome!
Your Karma points are soaring :-) !
Have a vey nice day,
best
Ronald

**Comment by vinnyochy** [comment] 2018-05-01 11:05
could someone kindly assist me by sending test ether to 0x2D80fC3fF2a4c0Ea26201ddb5D833c74309d0196

**Comment by dangell7** [comment] 2018-05-01 11:07
Can someone explain why you cannot just switch to another test network?

**Comment by manojnetsmartz** [comment] 2018-05-01 11:27
@ligi Thanks.

**Comment by Kunal57** [comment] 2018-05-01 11:49
Need ETH for a project. Thank you!

0xb61bbAc149524fa364d1ac5d881Bd5765530eC61

**Comment by bladexxv** [comment] 2018-05-01 13:40
Could send some  on 0x9D5793Fd6be6c54831e73d3E01B8637F920B3de2? many thanks.

**Comment by k-vladyslav** [comment] 2018-05-01 14:09
@ligi @karalabe sorry guys for disturbance, but are there any news on fixing https://www.rinkeby.io/#faucet?
Or maybe you can suggest any verified alternatives?

**Comment by jurgenfink** [comment] 2018-05-01 14:17
@Kunal57   2 ETH sent
@bladexxv  2 ETH sent

**Comment by pgreze** [comment] 2018-05-01 14:41
Hi everyone, I would appreciate some ETH for my smart contract course :)

Address: 0x80F005D229Db9F74665946ce5070A752Abcdd43a

**Comment by deepcodersinc** [comment] 2018-05-01 14:50
Could someone send some ETH to 0x52cb69D6580f14282D192bC3EBF1F678712511DE
Thanks.

**Comment by jurgenfink** [comment] 2018-05-01 15:45
Hey @pgreze , I have sent you 2 ETH - good luck with the course :smirk:

**Comment by jurgenfink** [comment] 2018-05-01 15:48
@deepcodersinc
@carolinapeisch
@CD0x23
I have sent 1 ETH to each (sorry - running low now myself ....)

**Comment by phoxha** [comment] 2018-05-01 17:02
Just need a couple of ether to test. Please send me some: 0x5a56ff52EFE965e904fd928031df07A9C9a173cC

**Comment by Kanishka6996** [comment] 2018-05-01 17:25
Hey need couple of eathers for the project.. please can anyone send me?

My address : 0xC0dD915c031a8cd9FC5c39c773D4e0f6617Fb9eD

**Comment by chutium** [comment] 2018-05-01 17:45
same issue here, please send me some ethers for testing: 0x1FbEe6771494601Ee4915Ab542aC35F321B09e44

Thanks.

**Comment by motiondirector** [comment] 2018-05-01 17:47
I also need some eather.  Please send me some!
0xF6472b971D3e9dAa27c8B0285764e4F1C0117B5f

**Comment by Keith-CY** [comment] 2018-05-01 18:01
I encounter this error too and 1ether thx:
0xcF4F8d4d8eDb313D397a3ba7a03994b6C311d46B

**Comment by karalabe** [comment] 2018-05-01 18:10
Hey all, for some reason our bootnode went belly up and the faucet only has that single node set to boot from. I've no idea what's wrong with the bootnode, ever since we update to Ubuntu Artful 2 weeks ago the entire system freezes every second day. Trying to get it back online now, but still it's behaving very funky.

**Comment by jurgenfink** [comment] 2018-05-01 19:04
@phoxha  1 ETH sent
@Kanishka6996  1 ETH sent
@chutium  1 ETH sent
@motiondirector  1 ETH sent
@Keith-CY  1 ETH sent
@guoliu  1 ETH sent

@karalabe  thank's for your update on the status - good luck and we know that you are doing your best. Rinkeby works very fine by the way - congrats to you and your team - keep up the good work :+1:

**Comment by wbt** [comment] 2018-05-01 20:00
The issue now being reported is "Faucet offline: no suitable peers available" and the errors stack up:
![Multiple copies of "Faucet offline: no suitable peers available"](https://user-images.githubusercontent.com/563406/39490901-6ec5861a-4d58-11e8-9ef3-4301ad6c0c39.png)
I suspect it's a related issue to this one and am planting the exact message + picture to help with searching.

Thanks @karalabe for all your work on this!

**Comment by jurgenfink** [comment] 2018-05-01 20:31
@Annayelizarov  1 ETH sent meanwhile ....

**Comment by celavek** [comment] 2018-05-01 21:29
It's up and running. Thank you!

**Comment by dalmiasiddharth** [comment] 2018-05-02 05:54
Sent the other back. Thank you again!

**Comment by karalabe** [comment] 2018-05-02 06:45
Faucet is back, sorry for the past 3 days, was on holiday and it didn't occur to anyone to reboot the bootnode ;P

**Closed by karalabe** 2018-05-02 06:45 UTC

**Comment by phoxha** [comment] 2018-05-02 13:06
Thank you for the update and the good work.

Pari Hoxha
413.575.2366

**Comment by betimbryma** [comment] 2018-05-02 20:50
Hii,
Thank you so much @jurgenfink I have sent 10 eth back to you.
And thanks to @ligi too, I have sent 4.2 eth to you too.
You guys are awesome.

**Comment by ligi** [comment] 2018-05-02 20:59
@betimbryma you are very welcome! Hope some others follow your lead and return the rinkeby eth now that the faucet is working again ;-)

**Comment by ligi** [comment] 2018-05-02 21:07
YAY

**Comment by jurgenfink** [comment] 2018-05-02 23:34
Yiiippppi - long live @karalabe - Yiiiippppi .... 
Also @celavek 

Some returned the ETH (got some 30 back so far) - most important that everyone could continue their project and testing ... we all love rinkeby ... keep up the good work.

**Comment by guoliu** [comment] 2018-05-03 18:18
@jurgenfink Thank you so much! Which address should I return ETH to?

**Comment by karalabe** [comment] 2018-05-04 08:14
@ligi @jurgenfink Thank you both for holding my back while the faucet was down, sent both of you 250 Rinkeby Ether. Should cover your "losses" :) 

@ligi https://rinkeby.etherscan.io/tx/0x527985e4acf8dd426adc6c55604743dc61db22c8e47a338f515167a835c0f8c2
@jurgenfink https://rinkeby.etherscan.io/tx/0x35f6b3657aa715e9591d7bc5ae12952546cd644fdc30090d6fc858b3af653f58

**Comment by intizarabe** [comment] 2018-05-04 08:27
Sirs I am requesting support of Rinkeby
Checking comm channel.
Laptop seems almost dead, my parter last years ..

On 4 May 2018 14:15, "Péter Szilágyi" <notifications@github.com> wrote:

@ligi <https://github.com/ligi> @jurgenfink <https://github.com/jurgenfink>
Thank you both for holding my back while the faucet was down, sent both of
you 250 Rinkeby Ether. Should cover your "losses" :)

@ligi <https://github.com/ligi>
https://rinkeby.etherscan.io/tx/0x527985e4acf8dd426adc6c55604743dc61db22c8e47a338f515167a835c0f8c2
@jurgenfink <https://github.com/jurgenfink>
https://rinkeby.etherscan.io/tx/0x35f6b3657aa715e9591d7bc5ae12952546cd644fdc30090d6fc858b3af653f58

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/go-ethereum/issues/16602#issuecomment-386533532>,
or mute the thread

**Comment by ligi** [comment] 2018-05-04 09:17
@karalabe yay - this more than covers it. I am now a whale - a whale born from fail (much more of a rhyme when spoken out loud :) 

![](http://www.yiyinglu.com/wp-content/uploads/2013/11/lifting-a-dreamer-2009.jpg)

I can now pump and dump on rinkeby to bring up the value 1000 fold (which is even really easy there as 0==1000*0 - rinkeby FTW ,-)

**Comment by jurgenfink** [comment] 2018-05-04 17:25
@karalabe thanks a lot - I am glad we could help a little bit to calm the crowd - I like the test-net and it was sort of giving back to the community and contributing to the community, hence I immediately followed the good example of @ligi - very nice move - people appreciated it.
Again, thanks - I appreciate it

**Comment by vinod-neevsystems** [comment] 2018-09-06 09:17
Can you please send some ethers to my rinkeby account 0xe529a955da3bb34cc6657f67a65b065175a58d3e

**Comment by bumasoft** [comment] 2018-12-21 18:31
Could anyone send some ETH to 0x9222CA962AcE390453F2f8cB9bB4f8F7f1FeD5BD ? Not only is the faucet down, but it appears their whole website is down ( http://rinkeby.io )... Thank you!

**Comment by karalabe** [comment] 2018-12-22 11:45
@bumasoft Fixed, the disk got filled :P

**Comment by karalabe** [comment] 2018-12-22 11:46
I've locked this issue since it became a dumping ground for Rinkeby Faucet errors. Please open a new issue if you see something wrong.
