### ISSUE TITLE
SEGV on corrupt leveldb due to assumption of existence of headers. 

### ISSUE THREAD

**Issue by qdotme** [ethereum/go-ethereum#21421] opened 2020-08-06 23:11 UTC
Unsure if this is a reproducible issue, but casual examination of backtrace indicate that it does not safely recover from a failure to retrieve block headers from database. 

```
downloader.go:895			header := d.lightchain.GetHeaderByHash(h) // Independent of sync mode, header surely exists
```

#### System information

```
Geth
Version: 1.9.18-stable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.6
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
```

#### Expected behaviour

geth recovers from corrupted leveldb database

#### Actual behaviour

geth crashes with SEGV based on assumption of correctness of database records. 

#### Steps to reproduce the behaviour

Difficult to reproduce, however:

geth --snapshot was running, power failure corrupted the leveldb database structures. 

```
INFO [08-06|18:01:50.537] Loaded most recent local header          number=10606851 hash="7eb46e…c85c0e" td=16698299479001863122557 age=8h21m37s
INFO [08-06|18:01:50.538] Loaded most recent local full block      number=10588707 hash="389da9…953a1c" td=16653897119779575599936 age=3d3h34m
INFO [08-06|18:01:50.538] Loaded most recent local fast block      number=10606851 hash="7eb46e…c85c0e" td=16698299479001863122557 age=8h21m37s
```

#### Backtrace

```
INFO [08-06|17:59:27.469] Block synchronisation started 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xbccb23]

goroutine 461 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc000301180, 0xc014389950, 0xc0148098c0, 0x0, 0x0, 0xa)
        /var/tmp/portage/net-p2p/go-ethereum-1.9.18/work/go-ethereum-1.9.18/eth/downloader/downloader.go:895 +0x15d3
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc000301180, 0xc014389950, 0x5fd801a472a1918c, 0xeb92667a516feb9e, 0x5278299d8e0aa287, 0x8fbe0694b2a486f3, 0xc0149fbba0, 0x0, 0x0)
        /var/tmp/portage/net-p2p/go-ethereum-1.9.18/work/go-ethereum-1.9.18/eth/downloader/downloader.go:451 +0x3d9
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc000301180, 0xc001f66bb0, 0x10, 0x5fd801a472a1918c, 0xeb92667a516feb9e, 0x5278299d8e0aa287, 0x8fbe0694b2a486f3, 0xc0149fbba0, 0xc000000000, 0x0, ...)
        /var/tmp/portage/net-p2p/go-ethereum-1.9.18/work/go-ethereum-1.9.18/eth/downloader/downloader.go:414 +0x374
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc000301180, 0xc001f66bb0, 0x10, 0x5fd801a472a1918c, 0xeb92667a516feb9e, 0x5278299d8e0aa287, 0x8fbe0694b2a486f3, 0xc0149fbba0, 0xf00000000000000, 0x2000100000003, ...)
        /var/tmp/portage/net-p2p/go-ethereum-1.9.18/work/go-ethereum-1.9.18/eth/downloader/downloader.go:324 +0x8c
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).doSync(0xc000051500, 0xc01503f1c0, 0x12f52b0, 0xc0001afba0)
        /var/tmp/portage/net-p2p/go-ethereum-1.9.18/work/go-ethereum-1.9.18/eth/sync.go:312 +0x9f
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc0127bcf30, 0xc01503f1c0)
        /var/tmp/portage/net-p2p/go-ethereum-1.9.18/work/go-ethereum-1.9.18/eth/sync.go:288 +0x38
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
        /var/tmp/portage/net-p2p/go-ethereum-1.9.18/work/go-ethereum-1.9.18/eth/sync.go:288 +0x7a
```

**Comment by karalabe** [comment] 2020-08-07 07:04
We are aware of a family of bugs that are caused by crashes and strange repair attempts. I've recently opened a PR to try and write up *all* the corner cases and what the expected behavior is so we can have an extensive test suite. It might take a while to have everything fall into place.

As for this particular issue, it's a bit of a bummer, because there's no way to delete parts of the database that would allow to repair itself. That's what I'm working on now. If you need a solution *now*, your best/easiest bet is to nuke your `chaindata` folder **without** deleting the `ancients` within and do a fast sync. It will only download the stat, will keep the locally available chain.

**Comment by holiman** [comment] 2020-09-03 08:51
This ticket is rather old, and since this ticket was made,the PR @karalabe mentioned has been merged to master. I'd prefer closing this ticket, and instead use https://github.com/ethereum/go-ethereum/issues/21496 to continue any investigation (it has a similar cause, but relating to the new code).

**Closed by holiman** 2020-09-03 08:51 UTC
Labels: status:triage
