### ISSUE TITLE
Failed to start smart card hub & Use admin.addPeer doesn't work in windows version

### ISSUE THREAD

**Issue by darkcandy** [ethereum/go-ethereum#19582] opened 2019-05-15 16:53 UTC
Hi~
I tried to make two nodes and I got the same problems while I made both of them :
node 1 command:
![image](https://user-images.githubusercontent.com/29693123/57793329-9ff3a500-7773-11e9-9fc2-a2b0150f7b86.png)
node 1 warning:
![image](https://user-images.githubusercontent.com/29693123/57793238-6cb11600-7773-11e9-9ddd-f34c7a0f050d.png)
### Failed to start mart card hub
node 1 info :
![image](https://user-images.githubusercontent.com/29693123/57793402-d03b4380-7773-11e9-94d5-09bef8b74216.png)

### and then I tried to use admin.addPeer("..") to build my private network
I got this
![image](https://user-images.githubusercontent.com/29693123/57793493-0678c300-7774-11e9-9a8b-1d4d6e74c62c.png)
### my peers are empty
I tried every geth version I can get online, and It still not work.
In this case, I didn't put any [::] in my encode URL, and I also turned off my firewall.
Please help me, thank you!

**Comment by ligi** [comment] 2019-05-20 09:47
cc @gballet

**Comment by gballet** [comment] 2019-05-20 15:55
This is redundant with https://github.com/ethereum/go-ethereum/issues/19469, which is waiting for https://github.com/ethereum/go-ethereum/pull/19439 to be merged. It's not related to your peer problem.

Regarding the reason why your peers are empty is, presumably you need to specify a bootnode if you are specifying your own network ID. Please provide the command line for both nodes if you want us to reproduce the issue.

**Comment by karalabe** [comment] 2019-05-28 09:00
So, you are running a local ephemeral developer chain `--dev`. That generates a random genesis, random starting allocations, and disables networking. `--dev` is meant to be used as a single node instance. If you want to run a multi-node network, you need to create your own genesis config and initialize your nodes explicitly.

`puppeth` might be able to help generate a starting clique genesis.

**Closed by karalabe** 2019-05-28 09:00 UTC
Labels: area:private-network, area:windows, need:more-information, status:triage
