### ISSUE TITLE
Transaction stats report failed

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#16540] opened 2018-04-20 15:53 UTC
#### System information

Geth version: `Geth/v1.8.4-stable-2423ae01/linux-amd64/go1.10`
OS & Version: Ubuntu 16.04

Ever since I updated from v1.8.2 to v1.8.4 my Geth node has struggled to maintain sync.

It will run for a while then it just seems to stop syncing. Below is the error I see right before it stops syncing

```
INFO [04-20|09:31:00] Imported new chain segment               blocks=1  txs=42   mgas=7.948   elapsed=137.716ms mgasps=57.715 number=5474614 hash=6feee1…15292d cache=104.64mB
WARN [04-20|09:31:58] Head headers broke chain ordering        peer=a7519e429e51bc32 index=0 requested=5474422 received=5474615
WARN [04-20|09:31:58] Synchronisation failed, dropping peer    peer=a7519e429e51bc32 err="retrieved hash chain is invalid"
INFO [04-20|09:32:34] Imported new chain segment               blocks=2  txs=311  mgas=13.408  elapsed=5.020s    mgasps=2.671  number=5474616 hash=c5987b…bd2fef cache=105.39mB
INFO [04-20|09:32:39] Imported new chain segment               blocks=1  txs=254  mgas=7.980   elapsed=5.173s    mgasps=1.543  number=5474617 hash=49c19f…af8271 cache=106.01mB
INFO [04-20|09:32:43] Imported new chain segment               blocks=1  txs=178  mgas=7.976   elapsed=3.721s    mgasps=2.143  number=5474618 hash=1136a3…5412b1 cache=106.28mB
INFO [04-20|09:32:46] Imported new chain segment               blocks=1  txs=241  mgas=7.988   elapsed=3.146s    mgasps=2.538  number=5474618 hash=3e2f1c…2e919b cache=106.68mB
INFO [04-20|09:32:46] Imported new chain segment               blocks=1  txs=135  mgas=6.699   elapsed=241.133ms mgasps=27.782 number=5474618 hash=c9fe13…7b0686 cache=106.84mB
WARN [04-20|09:39:26] Failed to decode stats server message    err=EOF
WARN [04-20|09:39:42] Transaction stats report failed          err="tls: use of closed connection"
```

**Comment by NNagato** [comment] 2018-04-21 17:02
I used geth version 1.7.3, my node was working fine until yesterday - 20/04, I got the same issue with you. Besides almost all rpc methods call to my node take too long time to response. Especial, time response of estimateGas always up to 60s. I tried to upgrade geth to version 1.8.3 but nothing better.
But today, everything is getting better. I don't know what happened, I didn't do anything.

**Comment by holiman** [comment] 2018-04-23 07:04
> Ever since I updated from v1.8.2 to v1.8.4 my Geth node has struggled to maintain sync.

I suspect this is a duplicate of https://github.com/ethereum/go-ethereum/issues/16539 , and `Transaction stats report failed` is unrelated.

**Closed** 2018-04-23 07:05 UTC
