### ISSUE TITLE
Geth 1.9.x returns zero for non-zero storage variables in any contracts

### ISSUE THREAD

**Issue by D-Nice** [ethereum/go-ethereum#19145] opened 2019-02-20 21:51 UTC
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: Geth/v1.9.0-unstable-5b8ae788/linux-amd64/go1.11.5 under Docker using ethereum/client-go:latest
OS & Version: Ubuntu 16.04

#### Expected behaviour

Reading storage via a constant function call and getting non-zero result for something that is non-zero.

#### Actual behaviour

Getting zero as the result, for something in storage that is non-zero, breaking a number of internal scripts. (Oddly restarting these script many times over, like 20 or so, it sometimes yields the result, same issue encountered with varying web3s from 0.14 to 0.18 to whatever remix/metamask use). 

#### Steps to reproduce the behaviour

Deploy a contract on Remix, with a function where you can set a public storage variable. After deployment, and subsequently setting it in another transaction, try reading it, and it will be 0. Use stable geth, and you get its non-zero value (e.g. 3), switch back to unstable, and it's 0 again. Tested using metamask with custom RPC set to geth stable and unstable running Goerli. Same issues apply with local js scripts for any other contract that read storage, using stable. Only tested on Goerli.

**Comment by xiaods** [comment] 2019-02-24 06:26
no sample func, can't easily reproduce this bug.

**Comment by ESchouten** [comment] 2019-03-05 15:43
Had the same issue querying a list of addresses in a smart contract, sometimes returning the addresses, but most of the time an empty response.
Downgrading to 1.8.23 resolved this issue, which was an inconvenience since 1.9 upgrades the database, making it incompatible with 1.8.x.

**Comment by holiman** [comment] 2019-06-24 08:55
I believe this has been fixed by #19737, and that the underlying cause was internal timeout. With the changes, an internal timeout will return an error instead of an empty result. Please reopen if it persists even after the changes.

**Closed by holiman** 2019-06-24 08:55 UTC

**Comment by D-Nice** [comment] 2019-06-25 16:35
thanks, will give new geth a try again at some point, and report here if similar issues end up being encountered!
