### ISSUE TITLE
Generated contract bindings don't allow specifying call block number.

### ISSUE THREAD

**Issue by nostdm** [ethereum/go-ethereum#16838] opened 2018-05-30 01:26 UTC
#### System information

Geth version: `1.8.9`

#### Desired behaviour

The ability to call a contract method for a specific block number:

    balance, err := token.BalanceOf(&bind.CallOpts{}, account, big.NewInt(25402))

#### Actual behaviour

The bound contract `Call` method always sets the block number to `nil` (i.e. `latest`) and the generated bindings don't allow you to specify the block number.

    balance, err := token.BalanceOf(&bind.CallOpts{}, account)

#### Notes

I'm currently forced to use the `CallContract` method directly on the Ethereum client by manually encoding the contract method signature:

    packed, err := tokenABI.Pack("balanceOf", address)
    rsp, err := client.CallContract(ctx, ethereum.CallMsg{
        To:   token,
        Data: packed,
    }, big.NewInt(25402))

But this is a very manual process which defeats the purpose of generating Go bindings in the first place.

Are there any plans to add this functionality to the `abigen` generated code?

**Comment by favadi** [comment] 2018-09-27 09:41
I'm taking a look if this feature can be added without breaking current generated codes.

**Comment by favadi** [comment] 2018-09-27 10:29
I created #17770 to allow passing block number when using abigen generated codes.

**Comment by gballet** [comment] 2019-06-18 13:00
This should have been fixed with #17942. Please check with a more recent version of `geth` and reopen if the issue is still present.

**Closed by gballet** 2019-06-18 13:00 UTC
