### ISSUE TITLE
gas oracle is broken on 1.10.8

### ISSUE THREAD

**Issue by geomad** [ethereum/go-ethereum#23452] opened 2021-08-24 14:13 UTC
#### System information

Geth version: 1.10.8-stable
OS & Version: Linux

This issue started after updating to 1.10.8-stable. Gas oracle doesn't return the expected results when parameters are different than the defaults (both setting IgnorePrice or/and MaxPrice will break it). Works as expected without the .toml setting below

.toml settings:
````
[Eth.GPO]
IgnorePrice = 2000000000
````
eth_feeHistory arguments provided with the call:
````
("0x1", "latest", null)
````

#### Expected behaviour

eth_feeHistory returns the expected values

#### Actual behaviour

eth_feeHistory returns
````
{ oldestBlock: '0x0', gasUsedRatio: null }
````

on geth console I read this log:
````
WARN  Sanitizing fee history length            requested=1 truncated=0
````

**Comment by MrLouzao** [comment] 2021-08-24 14:17
Same here. We are suffering the same problem with same version and OS. We are building our own images to run the code base. If we revert to 1.10.7 is working again, this only happens on 1.10.8.

Our image: `Geth/v1.10.8-stable-26675454/linux-amd64/go1.16.5`

However, Infura service is working with that new version, returning data as usual.

**Comment by vogelito** [comment] 2021-08-24 15:23
Infura runs their own version of go-ethereum called Omnibus according to their [blog](https://blog.infura.io/infura-mainnet-outage-post-mortem-2020-11-11/):

> We run a custom patched version of Geth we internally call “Omnibus” which includes several performance, stability, and monitoring enhancements tailored to our cloud native architecture

**Comment by holiman** [comment] 2021-08-24 16:19
I tested this like so: 
```
geth --dev --dev.period  5 --gpo.ignoreprice=2000000000
```
And in another console: 
```
> eth.feeHistory("0x1", "latest", null)
{
  baseFeePerGas: ["0x2da282a8", "0x27ee3253"],
  gasUsedRatio: [0],
  oldestBlock: "0x2"
}
> eth.feeHistory("0x1", "latest", null)
{
  baseFeePerGas: ["0x2da282a8", "0x27ee3253"],
  gasUsedRatio: [0],
  oldestBlock: "0x2"
}
```

So, as far as reproducing it, I've failed so far...

**Comment by holiman** [comment] 2021-08-24 16:34
Yeah, I think I know what the cause is. Your toml config is omitting some values, causing them to be left at zero. 
```
[Eth.GPO]
Blocks = 20
Percentile = 60
MaxHeaderHistory = 1024
MaxBlockHistory = 1024
MaxPrice = 500000000000
IgnorePrice = 2
```
Try adding these default-values -- modify the ones you want, but leave the others. In this particular case, I think it's the `MaxHeaderHistory` which becomes `0` when omitted. That should work as a work-around, but yeah, it should also be fixed on our end.

**Closed** 2021-11-18 18:20 UTC
Labels: type:bug, help wanted, good first issue
