### ISSUE TITLE
BAD BLOCK - Error: invalid receipt root hash 

### ISSUE THREAD

**Issue by zincoshine** [ethereum/go-ethereum#15265] opened 2017-10-09 14:57 UTC
#### System information

Geth version: `1.7.0-stable-6c6c7b2a`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
geth doesn't sync on Rinkeby

#### Actual behaviour
ERROR[10-09|20:25:13] 
########## BAD BLOCK #########
Chain config: {ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: true EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 9223372036854775807 Engine: clique}

Number: 1035301
Hash: 0x9e673f84fa096626d50440cbb7c71ec891fd42993be3d99f87c826b43842c592
	receipt{med=a95f1fbd2fa6589acd708d187dfefab5944c64f5eb8eec1c32eb73a8d36a8b88 cgas=27183 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}

Error: invalid receipt root hash (remote: 85f374e1457eb09d56bf61c66cc7222a7e88167919d5574d3ca132499d06242b local: af3e081c339f29de5d63806d0f04bd152e65c725eb0f2746be748ee041b3e80b)
##############################

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment] 2017-10-09 16:01
The block for byzantium looks wrong - should be 1035301 - but you state 9223372036854775807
Where is your genesis from? You can take: 9223372036854775807

**Comment by jdextraze** [comment] 2017-10-09 17:52
I have the same issue. Didn't specify any genesis, just started `geth` with `--rinkeby`. Looking at https://www.rinkeby.io/ shows 3 nodes blocked at 1035300 too.

**Comment by ligi** [comment] 2017-10-09 18:01
1035300 is the last block before byzantium - here @karalabe gave a hint to stuck nodes: https://gist.github.com/karalabe/1a91daaca517f39c42135f88da848696

**Comment by smalaichami** [comment] 2017-10-09 18:04
Hi, 

1. You will have  to install new geth 1.7.1 and 
2. run  geth --rinkeby 

I had similar problems.. and fixed now.. it's due to the update...

Regards
Saravana

**Comment by smalaichami** [comment] 2017-10-09 18:06
For more information, please go through this.. 
https://github.com/ethereum/go-ethereum/releases

This is a maintenance release that fixes regressions in the 1.7.0 release.

This release enables the Byzantium hard fork transition at block number 4370000 (~17th October) on the mainnet and block number 1035301 (~9th October) on the Rinkeby test network. Please update well before these dates to ensure a smooth transition.

**Closed** 2017-10-10 09:10 UTC

**Comment by zincoshine** [comment] 2017-10-22 06:39
Thanks all, I upgraded to geth 1.7.2 and the issue is now resolved.

**Comment by Hu4F00d** [comment] 2017-11-20 14:02
I tried multiple times to resync from scratch with geth --rinkeby using geth 1.7.2 but I kept having the same problem and my bizantium block was 9223372036854775807 instead of 1035301 as well.

The solution was to explicitly state the genesis block following the instructions of this blog post: this blog post: http://blog.jaumesola.com/setting-up-an-ethereum-node-on-the-rinkeby-testnet

`mkdir /path/to/rinkeby`
`cd /path/to/rinkeby`
`curl -O https://www.rinkeby.io/rinkeby.json`
`geth --datadir=. init rinkeby.json`
`geth --networkid=4 --datadir=. --ethstats='yournode:Respect my authoritah!@stats.rinkeby.io' --bootnodes=enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303?discport=30304 --cache=1024`
