### ISSUE TITLE
How does the geth source receive the response?

### ISSUE THREAD

**Issue by ajaxcom** [ethereum/go-ethereum#24730] opened 2022-04-21 09:17 UTC
```
const (
	// HashLength is the expected length of the hash
	HashLength = 32
	// AddressLength is the expected length of the address
	AddressLength = 20
)

```
```
`type Hash [HashLength]byte

type Header struct {
	ParentHash  common.Hash    `json:"parentHash"       gencodec:"required"`
	UncleHash   common.Hash    `json:"sha3Uncles"       gencodec:"required"`
	Coinbase    common.Address `json:"miner"`
	Root        common.Hash    `json:"stateRoot"        gencodec:"required"`
	TxHash      common.Hash    `json:"transactionsRoot" gencodec:"required"`
	ReceiptHash common.Hash    `json:"receiptsRoot"     gencodec:"required"`
	Bloom       Bloom          `json:"logsBloom"        gencodec:"required"`
	Difficulty  *big.Int       `json:"difficulty"       gencodec:"required"`
	Number      *big.Int       `json:"number"           gencodec:"required"`
	GasLimit    uint64         `json:"gasLimit"         gencodec:"required"`
	GasUsed     uint64         `json:"gasUsed"          gencodec:"required"`
	Time        uint64         `json:"timestamp"        gencodec:"required"`
	Extra       []byte         `json:"extraData"        gencodec:"required"`
	MixDigest   common.Hash    `json:"mixHash"`
	Nonce       BlockNonce     `json:"nonce"`
}`

```

If this code to receive value from json

I don't understand a bit here. Generally, this is how I handle it. :

```
type Header {
    blockHash string
    blockNumber string
    x2 string
    x3 string
    x4 string
}

```
```
body, _ := ioutil.ReadAll(resp.Body)
json.Unmarshal(body, &Header) // 0x105824217e0b6cc74b2fae5a68fd16818d37c6bad72e7efb80d4749cad085f70

// data conversion
func (h *Header) ToDecimal *Header{
    //.......
    return h
}

```

```
// when i call
Header.x1 // 0x105824217e0b6cc74b2fae5a68fd16818d37c6bad72e7efb80d4749cad085f70
Header.ToDecimal().blockNumber  // 123456 blockNumber  

```
Here are a few questions？

1. Why should Header be defined as common.Hash? Is it any good for use?
2. My writing method is the same for each field type of Header
3. How do I convert this data internally?
`

**Comment by s1na** [comment] 2022-04-21 12:18
I'm not sure I understand what you're trying to do. Is it that you sent an RPC request to get a block body and then unmarshal the JSON into a custom struct you defined?

**Comment by holiman** [comment] 2022-04-26 09:40
I don't understand anything. 

I'll close this ticket, but feel free to open it up again if you can provide additional information so we can figure out what the goal and the problem is here.

**Closed by holiman** 2022-04-26 09:40 UTC
Labels: type:docs
