### ISSUE TITLE
go dev 1.4.0-unstable 915SNAPSHOT20160303191316 JSON error

### ISSUE THREAD

**Issue by mshiso** [ethereum/go-ethereum#2299] opened 2016-03-06 21:21 UTC
{"jsonrpc":"2.0","error":{"code":-32700,"message":"json: cannot unmarshal string into Go value of type int64"}}

when trying to deploy this solc code:
contract greeter {
	uint256 public num;
	address owner;
   function greeter (uint256 _num) public {
      num=_num;
		owner=msg.sender;
   }
	function verify(uint256 vnum) public {
		if (num == vnum) {
				owner.send(3999999999999999918);
		}	
	}
	function kill() public{
		suicide(msg.sender);
	}
}

**Comment by mshiso** [comment] 2016-03-06 21:39
Downgraded to 1.3.5 resolved issue

**Comment by karalabe** [comment] 2016-03-07 08:47
Possible duplicate of https://github.com/ethereum/go-ethereum/issues/2270 ?

**Closed** 2016-03-07 22:15 UTC
Labels: duplicate
