### ISSUE TITLE
geth ignores crtl-c if too early 

### ISSUE THREAD

**Issue by aeronbuchanan** [ethereum/go-ethereum#1207] opened 2015-06-08 21:22 UTC
not a biggie

aeron@computer:~$ geth
I0608 23:15:00.394226   13673 backend.go:255] Protocol Version: 60, Network Id: 0
I0608 23:15:00.394281   13673 backend.go:265] Blockchain DB Version: 3
I0608 23:15:00.398939   13673 chain_manager.go:246] Last block (#549613) d65de85bd0fa5ffb30d8f981816a30a024e168d7add61839422145ea342036ae TD=3124728535076524
**^C**I0608 23:15:09.005264   13673 cmd.go:60] Shutting down (interrupt) ... 
I0608 23:15:14.335651   13673 cmd.go:148] Starting Geth/v0.9.27/linux/go1.4.2
etc...

**Comment by karalabe** [comment] 2015-06-10 12:46
This is a duplicate of #1017.

**Closed by karalabe** 2015-06-10 12:46 UTC
Labels: duplicate
