### ISSUE TITLE
Can't install Geth on Ubuntu 18.04.2

### ISSUE THREAD

**Issue by PeHo89** [ethereum/go-ethereum#19726] opened 2019-06-17 09:18 UTC
Hy there,

unfortunately I can't install geth on ubuntu. I followed the steps from the installation section but when I am executing 'sudo apt-get install ethereum' it states that no package with this name can be located. I added ethereum and ethereum-dev repositories via 'sudo -E add-apt-repository ppa:ethereum/ethereum' and 'sudo -E add-apt-repository ppa:ethereum/ethereum-dev'. Then I executed 'sudo apt-get update'. In the list of repositories the two ethereum repositories shows up, but when installing package ethereum can't be located.

I also tried to re-installing the ca-certficates 'sudo apt-get install --reinstall ca-certificates'. Unfortunatley nothing changed.

Has anybody an idea, what the problem could be? I would like to install geth via ppa and not downloading and building it.

Many thanks and greets
Peter

**Comment by gballet** [comment] 2019-06-18 15:20
@PeHo89 could you please:

  * Point to the documentation that you are following
  * Tell us what the output of `apt search ethereum` is
  * Tell us what happens if you try to install `geth` instead: `sudo -E apt install geth` ?
  * Tell us what happens if you run the previous two steps without adding `ppa:ethereum/ethereum-dev` to your repository list ?

I have just tried the method you describe, on the same version of ubuntu, and `geth` installs without a hitch.

**Comment by PeHo89** [comment] 2019-06-18 17:27
Hy,

many thanks for your response! I followed the documentation on https://geth.ethereum.org/install-and-build/Installing-Geth#install-on-ubuntu-via-ppas.

This is the shell output with ethereum-dev ppa added:
![shell_withDevPpa](https://user-images.githubusercontent.com/26039145/59705539-e28b2000-91fe-11e9-86fc-e127d48cabb2.png)

This is the shell output without ethereum-dev ppa:
![shell_withoutDevPpa](https://user-images.githubusercontent.com/26039145/59705598-ff275800-91fe-11e9-8f03-b1c374c5daeb.png)

Thanks again for your help!

Greets
Peter

**Comment by gballet** [comment] 2019-06-18 22:55
That's strange. Could you also show the output of `sudo apt update` ?

**Comment by PeHo89** [comment] 2019-06-19 05:44
I also absolutely do not understand the problem here.

I am running this on Ubuntu 18.04.2 server. Maybe it has to to with the server edition?

That's the output:
![shell](https://user-images.githubusercontent.com/26039145/59739706-fae25580-9265-11e9-94b4-1f2b2c0ca650.png)

Many thanks!

**Comment by gballet** [comment] 2019-06-19 08:01
Are you only using windows 10 or a full install of ubuntu ? I thought Windows's Linux support was about to be completed, but not quite there yet? Not that it matters anyway: I just tried the same thing on my windows 10/ubuntu install and it works like a charm.

Using this `Dockerfile`, I can reproduce a clean Ubuntu install:
```
FROM ubuntu:18.04

RUN apt update -y && apt install -y software-properties-common
RUN add-apt-repository ppa:ethereum/ethereum
RUN apt update -y && apt install geth

CMD bash
```

It works. So your configuration is clearly somehow part of the problem. What happens if you try `apt install --fix-missing` ?

**Comment by gballet** [comment] 2019-06-19 08:25
Actually, while you're at it, please also run `apt upgrade` just in case some weird dependecy isn't updated.

**Comment by PeHo89** [comment] 2019-06-19 08:35
Just to clarify: I want to install ethereum / geth on a RaspberryPi 3B+ running Ubuntu 18.04.2 server on it. I connected one time from an Ubuntu machine and one time from a Windows machine via ssh to it.

I always executed 'apt upgrade' and 'apt update' one after each other. Also 'apt install --fix-missing' didn't solve the issue.

Any other ideas what the problem could be? Thanks!

**Comment by gballet** [comment] 2019-06-19 08:55
Ah, that's the kind of info that matters indeed ;) The problem is that the PPA only contains i386 and amd64 releases. The Raspberry PI 3B+ is on the lower limit of what is able to reasonably run `geth` (see https://github.com/ethereum/go-ethereum/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+raspberry for a non-exhaustive list of issues) I'm planning to spend some time in Q3 getting more powerful ARM boards like those at friendlyElec to work, in which case adding it to the PPA would make sense. Until then, it's only going to cause trouble for us maintainers and help exactly zero user.

If you still want to try it, don't build on the rpi itself (it probably wouldn't work). You should cross-compile on your desktop machine and then move the standalone binary to your rpi. The instructions to do so are: https://geth.ethereum.org/developers/Cross-compiling-Ethereum and the method is straightforward.

I'm closing this issue, as no arm binaries will be added to the PPA in the forseeable future.

**Closed by gballet** 2019-06-19 08:55 UTC
Labels: area:build

**Comment by PeHo89** [comment] 2019-06-19 09:39
Many many thanks for your answer and your time trying to help me. I thought of using the RespberryPi as an light node. I will try it the way you recommended. Anyway, I should have given all the details at the beginning. I will notice that for the next time. Thanks!
