### ISSUE TITLE
RPC API: method net_version does not exist/is not available

### ISSUE THREAD

**Issue by baxterjfinch** [ethereum/go-ethereum#22057] opened 2020-12-22 18:52 UTC
Running:
Machine - Linux Ubuntu 20.04
Docker container - ethereum/client-go (supported docker image)

Geth version: `v1.9.26`
OS & Version: Linux

Running Geth with the following api's enabled:
"db,eth,net,web3,admin,personal,miner"

From my host machine or from within the docker container, running the curl command after geth is started:

curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' http://localhost:8545

Expecting a valid response with current net_version

#### Actual behaviour
Receiving 
```
{"jsonrpc":"2.0","id":67,"error":{"code":-32601,"message":"the method net_version does not exist/is not available"}}

```

Geth log error showing:
```
WARN [12-22|10:38:31.374] Served net_version                       conn=127.0.0.1:59600 reqid=3 t="35.221µs" err="the method net_version does not exist/is not available"

```

Startup details:
```
INFO [12-22|10:38:30.865] Starting peer-to-peer node               instance=Geth/v1.9.26-unstable-61469cfe-20201221/linux-amd64/go1.15.6
INFO [12-22|10:38:30.869] Initialized state bloom                  items=12 errorrate=0.000 elapsed=7.707ms
INFO [12-22|10:38:30.871] New local node record                    seq=1 id=94b82260db33e63d ip=127.0.0.1 udp=30303 tcp=30303
INFO [12-22|10:38:30.872] Started P2P networking                   self=enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@127.0.0.1:30303
INFO [12-22|10:38:30.873] IPC endpoint opened                      url=/root/.ethereum/devchain/geth.ipc
ERROR[12-22|10:38:30.873] Unavailable modules in HTTP API list     unavailable=[db] available="[admin debug web3 eth txpool personal ethash miner net]"
INFO [12-22|10:38:30.873] HTTP server started                      endpoint=[::]:8545 cors=* vhosts=*
INFO [12-22|10:38:30.873] GraphQL enabled                          url=http://[::]:8545/graphql
INFO [12-22|10:38:30.873] GraphQL UI enabled                       url=http://[::]:8545/graphql/ui
INFO [12-22|10:38:30.873] WebSocket enabled                        url=ws://[::]:8546
INFO [12-22|10:38:31.238] Etherbase automatically configured       address=0x007CcfFb7916F37F7AEEf05E8096ecFbe55AFc2f

```

**Comment by ligi** [comment] 2020-12-22 19:21
duplicate of #22034

**Closed** 2020-12-23 12:43 UTC
Labels: type:bug

**Comment by maoaixiao1314** [comment] 2021-08-16 08:40
How to solve this problem
