### ISSUE TITLE
Section processing failed  error="chain reorged during section processing"

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#15301] opened 2017-10-14 23:52 UTC
#### System information

Geth version: `geth 1.7.2-stable'
OS & Version: Windows server 2016 standard x64
Commit hash : (if `develop`)

#### Expected behaviour
Receiving error messages during full sync: chain reorged during section processing,
I didn't received this message when I run geth 1.7.1

#### Actual behaviour
ERROR[10-15|08:49:56] Section processing failed                type=bloombits error="chain reorged during section processing"

**Comment by philejmath** [comment] 2017-10-24 18:27
same issue on the Mac 1.7.2

**Comment by photonxp** [comment] 2017-11-27 14:11
Could this issue be due to the hard-fork of blockchain?

**Comment by akudo7** [comment] 2017-12-11 04:02
Any update so far?
Can we ignore this message?
Any information appreciate.

**Comment by zhaodehua1988** [comment] 2018-08-13 10:18
Can we ignore this message?

**Comment by adamschmideg** [comment] 2019-05-14 08:57
Closing as duplicate of #17227 and it contains more information

**Closed by adamschmideg** 2019-05-14 08:57 UTC
