### ISSUE TITLE
ubuntu ppa 1.10.2 version error

### ISSUE THREAD

**Issue by caiqinghua** [ethereum/go-ethereum#22657] opened 2021-04-12 23:53 UTC
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

1.10.2

#### Actual behaviour
1.9.25

#### Steps to reproduce the behaviour
apt install ethereum
Reading package lists... Done
Building dependency tree
Reading state information... Done
ethereum is already the newest version (1.10.2+build25719+bionic).
The following packages were automatically installed and are no longer required:
  libopts25 sntp
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 255 not upgraded.

geth version
Geth
Version: 1.9.25-stable
Git Commit: e7872729012a4871397307b12cc3f4772ffcbec6
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: linux
GOPATH=
GOROOT=go

#### Backtrace

````
[backtrace]
````

**Comment by swissarmybox** [comment] 2021-04-13 02:37
I encountered this as well.

**Comment by MariusVanDerWijden** [comment] 2021-04-13 07:43
Weird, I can not repro this. Just downloaded 1.10.2 from ppa and it worked fine.
Maybe you have some old version installed from somewhere else?
I setup a fresh vm for that.

**Comment by caiqinghua** [comment] 2021-04-13 13:28
> Weird, I can not repro this. Just downloaded 1.10.2 from ppa and it worked fine.
> Maybe you have some old version installed from somewhere else?
> I setup a fresh vm for that.

First, apt remove ethereum, second, apt install ethereum. geth version also show 1.9.25

apt remove ethereum
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  abigen bootnode clef evm geth libopts25 puppeth rlpdump sntp
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  ethereum
0 upgraded, 0 newly installed, 1 to remove and 255 not upgraded.
After this operation, 8192 B disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 124098 files and directories currently installed.)
Removing ethereum (1.10.2+build25719+bionic) ...



~# apt install ethereum
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libopts25 sntp
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  ethereum
0 upgraded, 1 newly installed, 0 to remove and 255 not upgraded.
Need to get 1620 B of archives.
After this operation, 8192 B of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 ethereum amd64 1.10.2+build25719+bionic [1620 B]
Fetched 1620 B in 2s (1027 B/s)
Selecting previously unselected package ethereum.
(Reading database ... 124095 files and directories currently installed.)
Preparing to unpack .../ethereum_1.10.2+build25719+bionic_amd64.deb ...
Unpacking ethereum (1.10.2+build25719+bionic) ...
Setting up ethereum (1.10.2+build25719+bionic) ...


~# geth version
Geth
Version: 1.9.25-stable
Git Commit: e7872729012a4871397307b12cc3f4772ffcbec6
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: linux
GOPATH=
GOROOT=go

**Comment by caiqinghua** [comment] 2021-04-13 13:30
@fjl Please help

**Comment by fjl** [comment] 2021-04-14 13:41
I cannot reproduce this. In a fresh Ubuntu 20.10 VM, when I run

```
sudo apt-add-repository ppa:ethereum/ethereum
sudo apt install ethereum
geth version
```

it prints `Version: 1.10.2-stable`

**Comment by fjl** [comment] 2021-04-14 13:42
@caiqinghua are you sure that there is no other geth version installed in a different location? What does `which geth` print for you?

**Comment by karalabe** [comment] 2021-04-14 20:00
https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages There's no trace of 1.9.25 on our PPAs.

**Comment by caiqinghua** [comment] 2021-04-14 21:54
> @caiqinghua are you sure that there is no other geth version installed in a different location? What does `which geth` print for you?

 which geth
/usr/bin/geth

ls -l /usr/bin/geth
Dec 11 17:11 /usr/bin/geth

rm /usr/bin/geth
apt remove ethereum
apt install ethereum
ls -l /usr/bin/geth
ls: cannot access '/usr/bin/geth': No such file or directory

uname -a
Linux xxx 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by caiqinghua** [comment] 2021-04-14 21:59
add-apt-repository -y ppa:ethereum/ethereum
Cannot add PPA: 'ppa:~ethereum/ubuntu/ethereum'.
ERROR: '~ethereum' user or team does not exist.
root@ubuntu:~# uname -a
Linux ubuntu 5.4.0-70-generic #78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by caiqinghua** [comment] 2021-04-14 22:10
The problem is fixed by following cmd.

apt-get install ethereum-unstable
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libopts25 sntp
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  abigen-unstable bootnode-unstable clef-unstable evm-unstable geth-unstable puppeth-unstable rlpdump-unstable
The following packages will be REMOVED:
  abigen bootnode clef ethereum evm geth puppeth rlpdump
The following NEW packages will be installed:
  abigen-unstable bootnode-unstable clef-unstable ethereum-unstable evm-unstable geth-unstable puppeth-unstable rlpdump-unstable
0 upgraded, 8 newly installed, 8 to remove and 250 not upgraded.
Need to get 31.2 MB of archives.
After this operation, 16.6 MB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 abigen-unstable amd64 1.10.3+build25783+bionic [4171 kB]
Get:2 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 bootnode-unstable amd64 1.10.3+build25783+bionic [4267 kB]
Get:3 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 clef-unstable amd64 1.10.3+build25783+bionic [6979 kB]
Get:4 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 evm-unstable amd64 1.10.3+build25783+bionic [4260 kB]
Get:5 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 geth-unstable amd64 1.10.3+build25783+bionic [7699 kB]
Get:6 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 puppeth-unstable amd64 1.10.3+build25783+bionic [3244 kB]
Get:7 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 rlpdump-unstable amd64 1.10.3+build25783+bionic [557 kB]
Get:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 ethereum-unstable amd64 1.10.3+build25783+bionic [1644 B]
Fetched 31.2 MB in 20s (1589 kB/s)
(Reading database ... 124098 files and directories currently installed.)
Removing ethereum (1.10.2+build25719+bionic) ...
Removing abigen (1.9.25+build24398+bionic) ...
Removing bootnode (1.9.25+build24398+bionic) ...
Removing clef (1.9.25+build24398+bionic) ...
Removing evm (1.9.25+build24398+bionic) ...
Removing geth (1.9.25+build24398+bionic) ...
Removing puppeth (1.9.25+build24398+bionic) ...
Removing rlpdump (1.9.25+build24398+bionic) ...
Selecting previously unselected package abigen-unstable.
(Reading database ... 124060 files and directories currently installed.)
Preparing to unpack .../0-abigen-unstable_1.10.3+build25783+bionic_amd64.deb ...
Unpacking abigen-unstable (1.10.3+build25783+bionic) ...
Selecting previously unselected package bootnode-unstable.
Preparing to unpack .../1-bootnode-unstable_1.10.3+build25783+bionic_amd64.deb ...
Unpacking bootnode-unstable (1.10.3+build25783+bionic) ...
Selecting previously unselected package clef-unstable.
Preparing to unpack .../2-clef-unstable_1.10.3+build25783+bionic_amd64.deb ...
Unpacking clef-unstable (1.10.3+build25783+bionic) ...
Selecting previously unselected package evm-unstable.
Preparing to unpack .../3-evm-unstable_1.10.3+build25783+bionic_amd64.deb ...
Unpacking evm-unstable (1.10.3+build25783+bionic) ...
Selecting previously unselected package geth-unstable.
Preparing to unpack .../4-geth-unstable_1.10.3+build25783+bionic_amd64.deb ...
Unpacking geth-unstable (1.10.3+build25783+bionic) ...
Selecting previously unselected package puppeth-unstable.
Preparing to unpack .../5-puppeth-unstable_1.10.3+build25783+bionic_amd64.deb ...
Unpacking puppeth-unstable (1.10.3+build25783+bionic) ...
Selecting previously unselected package rlpdump-unstable.
Preparing to unpack .../6-rlpdump-unstable_1.10.3+build25783+bionic_amd64.deb ...
Unpacking rlpdump-unstable (1.10.3+build25783+bionic) ...
Selecting previously unselected package ethereum-unstable.
Preparing to unpack .../7-ethereum-unstable_1.10.3+build25783+bionic_amd64.deb ...
Unpacking ethereum-unstable (1.10.3+build25783+bionic) ...
Setting up abigen-unstable (1.10.3+build25783+bionic) ...
Setting up rlpdump-unstable (1.10.3+build25783+bionic) ...
Setting up bootnode-unstable (1.10.3+build25783+bionic) ...
Setting up clef-unstable (1.10.3+build25783+bionic) ...
Setting up evm-unstable (1.10.3+build25783+bionic) ...
Setting up puppeth-unstable (1.10.3+build25783+bionic) ...
Setting up geth-unstable (1.10.3+build25783+bionic) ...
Setting up ethereum-unstable (1.10.3+build25783+bionic) ...

which geth
/usr/bin/geth
~# geth version
Geth
Version: 1.10.3-unstable
Git Commit: a50251e6cbfecfaf26040d42c70d2812bc422a4a
Architecture: amd64
Go Version: go1.16
Operating System: linux
GOPATH=
GOROOT=go

apt-get install ethereum
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libopts25 sntp
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  abigen bootnode clef evm geth puppeth rlpdump
The following packages will be REMOVED:
  abigen-unstable bootnode-unstable clef-unstable ethereum-unstable evm-unstable geth-unstable puppeth-unstable rlpdump-unstable
The following NEW packages will be installed:
  abigen bootnode clef ethereum evm geth puppeth rlpdump
0 upgraded, 8 newly installed, 8 to remove and 250 not upgraded.
Need to get 31.2 MB of archives.
After this operation, 9216 B disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 abigen amd64 1.10.2+build25719+bionic [4172 kB]
Get:2 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 bootnode amd64 1.10.2+build25719+bionic [4266 kB]
Get:3 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 clef amd64 1.10.2+build25719+bionic [6987 kB]
Get:4 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 evm amd64 1.10.2+build25719+bionic [4263 kB]
Get:5 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 geth amd64 1.10.2+build25719+bionic [7700 kB]
Get:6 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 puppeth amd64 1.10.2+build25719+bionic [3243 kB]
Get:7 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 rlpdump amd64 1.10.2+build25719+bionic [557 kB]
Get:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 ethereum amd64 1.10.2+build25719+bionic [1620 B]
Fetched 31.2 MB in 24s (1319 kB/s)
(Reading database ... 124098 files and directories currently installed.)
Removing ethereum-unstable (1.10.3+build25783+bionic) ...
Removing abigen-unstable (1.10.3+build25783+bionic) ...
Removing bootnode-unstable (1.10.3+build25783+bionic) ...
Removing clef-unstable (1.10.3+build25783+bionic) ...
Removing evm-unstable (1.10.3+build25783+bionic) ...
Removing geth-unstable (1.10.3+build25783+bionic) ...
Removing puppeth-unstable (1.10.3+build25783+bionic) ...
Removing rlpdump-unstable (1.10.3+build25783+bionic) ...
Selecting previously unselected package abigen.
(Reading database ... 124060 files and directories currently installed.)
Preparing to unpack .../0-abigen_1.10.2+build25719+bionic_amd64.deb ...
Unpacking abigen (1.10.2+build25719+bionic) ...
Selecting previously unselected package bootnode.
Preparing to unpack .../1-bootnode_1.10.2+build25719+bionic_amd64.deb ...
Unpacking bootnode (1.10.2+build25719+bionic) ...
Selecting previously unselected package clef.
Preparing to unpack .../2-clef_1.10.2+build25719+bionic_amd64.deb ...
Unpacking clef (1.10.2+build25719+bionic) ...
Selecting previously unselected package evm.
Preparing to unpack .../3-evm_1.10.2+build25719+bionic_amd64.deb ...
Unpacking evm (1.10.2+build25719+bionic) ...
Selecting previously unselected package geth.
Preparing to unpack .../4-geth_1.10.2+build25719+bionic_amd64.deb ...
Unpacking geth (1.10.2+build25719+bionic) ...
Selecting previously unselected package puppeth.
Preparing to unpack .../5-puppeth_1.10.2+build25719+bionic_amd64.deb ...
Unpacking puppeth (1.10.2+build25719+bionic) ...
Selecting previously unselected package rlpdump.
Preparing to unpack .../6-rlpdump_1.10.2+build25719+bionic_amd64.deb ...
Unpacking rlpdump (1.10.2+build25719+bionic) ...
Selecting previously unselected package ethereum.
Preparing to unpack .../7-ethereum_1.10.2+build25719+bionic_amd64.deb ...
Unpacking ethereum (1.10.2+build25719+bionic) ...
Setting up bootnode (1.10.2+build25719+bionic) ...
Setting up puppeth (1.10.2+build25719+bionic) ...
Setting up clef (1.10.2+build25719+bionic) ...
Setting up evm (1.10.2+build25719+bionic) ...
Setting up abigen (1.10.2+build25719+bionic) ...
Setting up rlpdump (1.10.2+build25719+bionic) ...
Setting up geth (1.10.2+build25719+bionic) ...
Setting up ethereum (1.10.2+build25719+bionic) ...

geth version
Geth
Version: 1.10.2-stable
Git Commit: 97d11b0187b4695ccf44e3b71b54155fe405a36f
Architecture: amd64
Go Version: go1.16
Operating System: linux
GOPATH=
GOROOT=go

**Comment by fjl** [comment] 2021-04-14 22:16
I don't know why your apt install did not work. It works for me and @MariusVanDerWijden.

**Comment by fjl** [comment] 2021-04-14 22:16
But good to hear you got it fixed now.

**Comment by caiqinghua** [comment] 2021-04-14 22:48
> But good to hear you got it fixed now.

fix another one by:
apt install ethereum-unstable
apt install ethereum

**Closed** 2021-04-14 23:38 UTC
Labels: type:bug

**Comment by swissarmybox** [comment] 2021-04-15 17:51
I just download it directly from website, untar it and just use that one.

**Comment by CryptoFewka** [comment] 2022-10-06 18:59
Hey all we came across this recently it it looks like the actual cause for this issue may not have been caught. The package "ethereum" is a metapackage. (See the output from `apt info ethereum` for the description at the bottom, and a bit above that the list of dependencies)

Geth itself is installed because it is a dependency of the ethereum metapackage. Updating the metapackage does not update its dependencies if they are already present. Dependencies like geth (`apt info geth`) will stay behind unless updated specifically.

You can tell geth to update itself to the latest version with `sudo apt install geth`, or you can update every dependency of the ethereum metapackage using the one-liner command below which is just a fancy way of updating ethereum, and the list of dependencies the ethereum metapackage has. Only do this if you understand what it is doing though because you shouldn't trust code on the internet. If you run `sudo apt update && sudo apt install geth` it will get the geth job done.

Update everything in the ethereum metapackage:
 `apt install ethereum $(dpkg-query -Wf '${Depends}' ethereum | sed 's/ *\(([^()]*)\)\? *[,|] */\n/g')`
