### ISSUE TITLE
geth 0.9.31 fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1317] opened 2015-06-22 19:29 UTC
I looked through the both open and closed issues and did not find this.

geth was just running and it crashed:

http://paste.ubuntu.com/11758673/

**Comment by fjl** [comment] 2015-06-22 19:31
@zsfelfoldi looks like goroutine leak in GasPriceOracle

**Comment by zsfelfoldi** [comment] 2015-06-23 17:14
I don't think it's a goroutine leak. My debug shows that my GPO goroutine runs in only one instance as intended. This out of memory happens in the database RLE decompressor, which might have been caused by a corrupted db.

**Comment by linagee** [comment] 2015-06-23 18:28
I got a slightly different OOM during initial block sync: http://paste.ubuntu.com/11763724/

**Comment by fjl** [comment] 2015-06-23 19:01
@zsfelfoldi in the first trace, there are 2128 goroutines running `GasPriceOracle.listenLoop`. I'm not saying this is the issue, just wanted to tell you about it.

**Comment by jorisbontje** [comment] 2015-06-24 08:14
Another out of memory datapoint, `geth 0.9.33` on a Raspberry Pi2:

https://gist.githubusercontent.com/jorisbontje/a0a9a95cbfad8429b5ab/raw/808b022907ab97424d18833d8b9508ce50d159aa/gistfile1.txt

**Comment by obscuren** [comment] 2015-06-30 00:02
This has been fixed in https://github.com/obscuren/go-ethereum/commit/5d9df7348d80fbd5de9a92d7f6abe6c02646c24d

**Comment by fjl** [comment] 2015-10-23 19:45
Or not: https://gist.github.com/fivedogit/364501ff7ae1a98fb2c1

**Comment by fivedogit** [comment] 2015-10-24 03:21
Caught the panic of my crash this time. Not sure if it's related to this bug or not. I can't make heads or tails of the logs.

https://gist.github.com/fivedogit/affae092725c749a4fd7

**Comment by karalabe** [comment] 2015-11-26 10:11
Should be fixed. Please reopen if it's not the case.

**Closed by karalabe** 2015-11-26 10:11 UTC
Labels: in progress
