### ISSUE TITLE
multiple keys match address

### ISSUE THREAD

**Issue by 401825317** [ethereum/go-ethereum#19575] opened 2019-05-15 03:32 UTC
#### System information

Geth version: `geth-linux-amd64-1.8.27-4bcc0a37`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
sync block 

#### Actual behaviour
```
WARN [05-15|11:29:31.432] Failed account unlock attempt            address=0xFE3DD72c9C5d62c35647306fb71EA0B56202897e err="multiple keys match address (/ecomdata/eth/prodchain/keystore/UTC--2019-05-07T16-56-27.109751293Z--fe3dd72c9c5d62c35647306fb71ea0b56202897e, /ecomdata/eth/prodchain/keystore/UTC--2019-05-07T16-56-27.618440402Z--fe3dd72c9c5d62c35647306fb71ea0b56202897e)"
WARN [05-15|11:29:31.691] Failed account unlock attempt            address=0x9261f95c7C5AC4a0083007f9c592B1CB1B4AC8Be err="multiple keys match address (/ecomdata/eth/prodchain/keystore/UTC--2019-05-07T16-56-26.656864283Z--9261f95c7c5ac4a0083007f9c592b1cb1b4ac8be, /ecomdata/eth/prodchain/keystore/UTC--2019-05-07T16-56-27.739480102Z--9261f95c7c5ac4a0083007f9c592b1cb1b4ac8be)"
WARN [05-15|11:29:33.037] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
WARN [05-15|11:29:35.070] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
WARN [05-15|11:29:36.081] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
WARN [05-15|11:29:37.115] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
WARN [05-15|11:29:38.053] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
WARN [05-15|11:29:39.047] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
WARN [05-15|11:29:40.126] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
WARN [05-15|11:29:41.141] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
INFO [05-15|11:29:41.357] Imported new chain segment               blocks=2 txs=173 mgas=8.007 elapsed=17.511s mgasps=0.457 number=7279885 hash=b2cb00…1ea6d3 age=2mo2w1d cache=1.14mB
WARN [05-15|11:29:42.215] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
WARN [05-15|11:29:43.138] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
WARN [05-15|11:29:44.171] Failed account unlock attempt            address=0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50 err="could not decrypt key with given passphrase"
```
Excuse me, what's the matter?

**Comment by holiman** [comment] 2019-05-21 09:12
The problem is that 

- These files both correspond to address  `fe3dd72c9c5d62c35647306fb71ea0b56202897e`:
  - `UTC--2019-05-07T16-56-27.618440402Z--fe3dd72c9c5d62c35647306fb71ea0b56202897e`
  - `UTC--2019-05-07T16-56-27.109751293Z--fe3dd72c9c5d62c35647306fb71ea0b56202897e`

And similarly for `9261f95c7c5ac4a0083007f9c592b1cb1b4ac8be`. They have different timestamps which is a bit odd (only differ in milliseconds). Any idea how they wound up like that? 
Secondly, someone (you?) is trying to decrypt the key for `0xD34ADB435Af9dCaA248C4dc568AaA77bD799aA50`, but failing. 

This is not really a bug report, it's merely a question, so I'll close this now that it's answered. Please reopen if you have an actual bug to report.

**Comment by ilyalesokhin-starkware** [comment] 2020-04-12 13:41
When personal_importRawKey is called with the same private key in a small time window, the account is registered twice.

$ curl -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"personal_importRawKey","params":["6767676767676767676767676767676767676767676767676767676767676767", ""],"id":83}' --url 127.0.0.1:8545 & curl -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"personal_importRawKey","params":["6767676767676767676767676767676767676767676767676767676767676767", ""],"id":83}' --url 127.0.0.1:8545
[1] 6012
{"jsonrpc":"2.0","id":83,"result":"0x5c0fe4435ba32d64fb96ed1c37e6fc1f72641d22"}
{"jsonrpc":"2.0","id":83,"result":"0x5c0fe4435ba32d64fb96ed1c37e6fc1f72641d22"}

After the above happens personal_unlockAccount calls fail.
$ curl -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"personal_unlockAccount","params":["0x5c0fe4435ba32d64fb96ed1c37e6fc1f72641d22", ""],"id":83}' --url 127.0.0.1:8545
{"jsonrpc":"2.0","id":83,"error":{"code":-32000,"message":"multiple keys match address (/geth_data/keystore/UTC--2020-04-12T13-35-52.683226421Z--5c0fe4435ba32d64fb96ed1c37e6fc1f72641d22, /geth_data/keystore/UTC--2020-04-12T13-35-52.683619802Z--5c0fe4435ba32d64fb96ed1c37e6fc1f72641d22)"}}

The expected behavior is to have one of the personal_importRawKey calls fail with: "account already exists" error.

**Comment by MariusVanDerWijden** [comment] 2020-04-14 09:20
Confirmed this bug, there's a race condition between two separate calls to `keystore.ImportECDSA`

**Closed** 2020-04-22 09:52 UTC
Labels: status:in-progress
