### ISSUE TITLE
 import chaindata without --fast goes really really slow, is that normal?

### ISSUE THREAD

**Issue by modong** [ethereum/go-ethereum#14436] opened 2017-05-07 15:51 UTC
#### System information

Geth version: `Version: 1.6.1-stable`
OS & Version: `Ubuntu 1404`
CPU: `Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz`
#### Expected behaviour

I initially synced with `--fast` option. However, as I need to call `eth_getBalance` RPC call, it is returning me errors saying trie node cannot be found. I googled a bit and found that this is because I used `--fast`. So, I followed this advice:

https://ethereum.stackexchange.com/questions/3474/after-fast-sync-in-geth-is-there-a-way-to-rebuild-the-old-states

I exported my current chaindata and started to import it.

I used `--cache 32640` option hoping to speed things up (I have 64G mem)

#### Actual behaviour

After 24 hours, I am only at block ~2400000 (still 1200000 to go). What worries me is that from the look of the log, I am importing something like 1 block per 3 seconds (very rough number). With that speed, I need approximately 1 month to sync the rest of the stuff....

So I just wanted to ask how long approximately will it take to do a sync without `--fast` and is this speed I am seeing normal

Many thanks!

```
INFO [05-07|10:45:46] Imported new chain segment               blocks=4  txs=57   mgas=2.944 elapsed=19.464s mgasps=0.151 number=2423491 hash=796df1…e97737
INFO [05-07|10:45:59] Imported new chain segment               blocks=8  txs=73   mgas=4.133 elapsed=13.243s mgasps=0.312 number=2423499 hash=704a13…bbad7d
INFO [05-07|10:46:14] Imported new chain segment               blocks=7  txs=47   mgas=2.959 elapsed=14.819s mgasps=0.200 number=2423506 hash=72567f…8270d2
INFO [05-07|10:46:23] Imported new chain segment               blocks=23 txs=112  mgas=4.377 elapsed=9.292s  mgasps=0.471 number=2423529 hash=2f4129…fc905c
INFO [05-07|10:46:35] Imported new chain segment               blocks=6  txs=29   mgas=1.414 elapsed=12.424s mgasps=0.114 number=2423535 hash=c20c18…76b912
INFO [05-07|10:46:50] Imported new chain segment               blocks=6  txs=40   mgas=2.595 elapsed=14.916s mgasps=0.174 number=2423541 hash=2357dc…ead6c9
INFO [05-07|10:47:06] Imported new chain segment               blocks=21 txs=137  mgas=6.056 elapsed=15.348s mgasps=0.395 number=2423562 hash=109839…654c51
INFO [05-07|10:47:19] Imported new chain segment               blocks=2  txs=25   mgas=1.417 elapsed=13.613s mgasps=0.104 number=2423564 hash=7f9a16…b5c074
INFO [05-07|10:47:29] Imported new chain segment               blocks=17 txs=102  mgas=5.111 elapsed=9.518s  mgasps=0.537 number=2423581 hash=35c480…ac9fad
INFO [05-07|10:47:39] Imported new chain segment               blocks=10 txs=63   mgas=3.511 elapsed=10.154s mgasps=0.346 number=2423591 hash=04ba4d…7880f4
INFO [05-07|10:47:48] Imported new chain segment               blocks=7  txs=41   mgas=2.775 elapsed=9.627s  mgasps=0.288 number=2423598 hash=668ec0…c3a5a6
```

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment] 2017-05-07 19:17
`eth_getBalance` will work fine for recent blocks, only not for historical blocks from long ago. Do you really need to query the blockchain's state from way past?

**Comment by modong** [comment] 2017-05-07 20:25
@karalabe correct sir,  that's precisely when I encounter the issue.

**Comment by modong** [comment] 2017-05-07 22:56
@karalabe I guess this is because of the earlier spam attack in Oct 2016 and I have to wait it out for that block interval and once I cross that, I should be back on the fast track?

**Comment by karalabe** [comment] 2017-05-08 10:32
Yes, there are two extremely slow parts (DOS + DOS cleanup). Outside of those it should progress slowly forward.

**Comment by karalabe** [comment] 2017-05-10 19:45
Closing this as "working as intended". We have a few ideas how we could try and speed things up, but that's a long term commitment.

**Closed by karalabe** 2017-05-10 19:45 UTC
