### ISSUE TITLE
nocgo not compiles

### ISSUE THREAD

**Issue by MasterDimmy** [ethereum/go-ethereum#30192] opened 2024-07-19 12:17 UTC
#### System information

Geth version: - 
go-ethereum v1.14.7
OS & Version: Windows 10 x64

#### Expected behaviour
build ok

#### Actual behaviour

D:\gopath\pkg\mod\github.com\ethereum\go-ethereum@v1.14.7\crypto\signature_nocgo.go:91:14: assignment mismatch: 2 variables but btc_ecdsa.SignCompact returns 1 value             

#### Steps to reproduce the behaviour
gox -os="linux" -arch="amd64" --ldflags="-s"

**Comment by fjl** [comment] 2024-07-22 21:42
Closing as duplicate of #30188. See https://github.com/ethereum/go-ethereum/issues/30188#issuecomment-2237649266 for workaround.

**Closed by fjl** 2024-07-22 21:42 UTC
Labels: type:bug
