### ISSUE TITLE
ether disappearing from account

### ISSUE THREAD

**Issue by bitBac** [ethereum/go-ethereum#23513] opened 2021-08-31 18:57 UTC
#### System information

Geth version: `Geth
Version: 1.10.8-stable
Git Commit: 26675454bf93bf904be7a43cce6b3f550115ff90
Architecture: amd64
Go Version: go1.16.4
Operating System: linux
GOPATH=
GOROOT=go
`
OS & Version: Linux 

#### Bug

https://etherscan.io/address/0x11754f088d2c1d679d49d89db402b87c609bab08 - it's transactions of my node account, and there is very strange behaviour, I get money on this account in txid `0xb619e30d8989298de0b20fecc060ed5406c20a83cf61ff6ce6523eedeb586c52` and somehow was created new out transaction
`0xbab5be723631647aa0844c8aab40daaab33675459a7f12e8a015409c49fcd173` and it was not inited by me, looks loke money was stolen becouse address not belong to me.
 

#### Backtrace

````
 Aug 31 16:44:03 wvds131262 kernel: [166671.869353] [UFW BLOCK] IN=enp3s0 OUT= MAC=00:16:3e:21:92:5e:7c:ad:74:bc:25:3c:08:00 SRC=3.236.112.103 DST=**.**.94.32 LEN=40 TOS=0x08 PREC=0x20 TTL=239 ID=0 DF PROTO=TCP SPT=35728 DPT=30303 WINDOW=0 RES=0x00 RST URGP=0 
Aug 31 16:44:11 wvds131262 kernel: [166680.426831] [UFW BLOCK] IN=enp3s0 OUT= MAC=00:16:3e:21:92:5e:a4:93:4c:80:0f:7c:08:00 SRC=135.181.160.215 DST=**.**.94.32 LEN=308 TOS=0x00 PREC=0x00 TTL=53 ID=53395 DF PROTO=TCP SPT=60474 DPT=30303 WINDOW=501 RES=0x00 ACK PSH FIN URGP=0 
Aug 31 16:44:19 wvds131262 kernel: [166688.185846] [UFW BLOCK] IN=enp3s0 OUT= MAC=00:16:3e:21:92:5e:a4:93:4c:80:0f:7c:08:00 SRC=147.182.198.128 DST=**.**.94.32 LEN=40 TOS=0x00 PREC=0x00 TTL=241 ID=10582 PROTO=TCP SPT=32766 DPT=56845 WINDOW=1024 RES=0x00 SYN URGP=0 
Aug 31 16:44:19 wvds131262 geth[831]: INFO [08-31|16:44:19.747] Imported new chain segment               blocks=1    txs=361     mgas=29.998  elapsed=441.845ms   mgasps=67.892  number=13,134,469 hash=38955c..6f2f1e dirty=1.97GiB
Aug 31 16:44:19 wvds131262 geth[831]: INFO [08-31|16:44:19.749] Unindexed transactions                   blocks=1    txs=143     tail=10,784,470 elapsed=2.621ms
Aug 31 16:44:27 wvds131262 geth[831]: INFO [08-31|16:44:26.999] Imported new chain segment               blocks=1    txs=124     mgas=10.967  elapsed=178.862ms   mgasps=61.316  number=13,134,470 hash=662e12..a4fc92 dirty=1.97GiB
Aug 31 16:44:27 wvds131262 geth[831]: INFO [08-31|16:44:27.003] Unindexed transactions                   blocks=1    txs=141     tail=10,784,471 elapsed=2.903ms
Aug 31 16:44:29 wvds131262 geth[831]: INFO [08-31|16:44:29.694] Imported new chain segment               blocks=1    txs=105     mgas=8.765   elapsed=338.812ms   mgasps=25.869  number=13,134,471 hash=bab879..55daff dirty=1.97GiB
Aug 31 16:44:30 wvds131262 geth[831]: INFO [08-31|16:44:30.066] Unindexed transactions                   blocks=1    txs=227     tail=10,784,472 elapsed=368.929ms
Aug 31 16:44:34 wvds131262 kernel: [166702.744967] [UFW BLOCK] IN=enp3s0 OUT= MAC=00:16:3e:21:92:5e:a4:93:4c:80:0f:7c:08:00 SRC=3.236.112.103 DST=**.**.94.32 LEN=40 TOS=0x08 PREC=0x20 TTL=238 ID=0 DF PROTO=TCP SPT=54446 DPT=30303 WINDOW=0 RES=0x00 RST URGP=0 
Aug 31 16:44:39 wvds131262 kernel: [166708.114793] [UFW BLOCK] IN=enp3s0 OUT= MAC=00:16:3e:21:92:5e:7c:ad:74:bc:25:3c:08:00 SRC=147.182.198.128 DST=**.**.94.32 LEN=40 TOS=0x00 PREC=0x00 TTL=240 ID=14257 PROTO=TCP SPT=32766 DPT=5883 WINDOW=1024 RES=0x00 SYN URGP=0 
Aug 31 16:44:42 wvds131262 geth[831]: INFO [08-31|16:44:42.127] Imported new chain segment               blocks=1    txs=195     mgas=15.039  elapsed=171.017ms   mgasps=87.939  number=13,134,472 hash=169512..6f9fe1 dirty=1.97GiB
Aug 31 16:44:42 wvds131262 geth[831]: INFO [08-31|16:44:42.129] Unindexed transactions                   blocks=1    txs=116     tail=10,784,473 elapsed=2.307ms
Aug 31 16:44:42 wvds131262 kernel: [166710.890937] [UFW BLOCK] IN=enp3s0 OUT= MAC=00:16:3e:21:92:5e:a4:93:4c:80:0f:7c:08:00 SRC=135.181.160.215 DST=**.**.94.32 LEN=308 TOS=0x00 PREC=0x00 TTL=53 ID=53396 DF PROTO=TCP SPT=60474 DPT=30303 WINDOW=501 RES=0x00 ACK PSH FIN URGP=0 
Aug 31 16:44:47 wvds131262 geth[831]: INFO [08-31|16:44:47.871] Imported new chain segment               blocks=1    txs=8       mgas=0.793   elapsed=44.032ms    mgasps=18.008  number=13,134,473 hash=501e38..ee0c13 dirty=1.97GiB
Aug 31 16:44:47 wvds131262 geth[831]: INFO [08-31|16:44:47.877] Unindexed transactions                   blocks=1    txs=195     tail=10,784,474 elapsed=5.776ms
Aug 31 16:44:47 wvds131262 geth[831]: INFO [08-31|16:44:47.893] Deep froze chain segment                 blocks=6    elapsed=68.902ms    number=13,044,472 hash=1a19bf..00661b
Aug 31 16:44:52 wvds131262 geth[831]: INFO [08-31|16:44:52.593] Imported new chain segment               blocks=1    txs=262     mgas=24.123  elapsed=242.525ms   mgasps=99.467  number=13,134,474 hash=e6a74c..43597e dirty=1.98GiB
Aug 31 16:44:52 wvds131262 geth[831]: INFO [08-31|16:44:52.596] Unindexed transactions                   blocks=1    txs=114     tail=10,784,475 elapsed=2.045ms
Aug 31 16:44:55 wvds131262 geth[831]: INFO [08-31|16:44:55.910] Imported new chain segment               blocks=1    txs=69      mgas=4.200   elapsed=138.633ms   mgasps=30.295  number=13,134,475 hash=946d76..f5940f dirty=1.97GiB
Aug 31 16:44:55 wvds131262 geth[831]: INFO [08-31|16:44:55.916] Unindexed transactions                   blocks=1    txs=168     tail=10,784,476 elapsed=6.053ms
Aug 31 16:44:59 wvds131262 geth[831]: INFO [08-31|16:44:59.465] Imported new chain segment               blocks=1    txs=140     mgas=11.878  elapsed=144.877ms   mgasps=81.989  number=13,134,476 hash=aecd31..080588 dirty=1.97GiB
Aug 31 16:44:59 wvds131262 geth[831]: INFO [08-31|16:44:59.468] Unindexed transactions                   blocks=1    txs=176     tail=10,784,477 elapsed=2.991ms
Aug 31 16:44:59 wvds131262 kernel: [166728.582410] [UFW BLOCK] IN=enp3s0 OUT= MAC=00:16:3e:21:92:5e:a4:93:4c:80:0f:7c:08:00 SRC=142.93.236.178 DST=**.**.94.32 LEN=60 TOS=0x00 PREC=0x00 TTL=52 ID=38134 DF PROTO=TCP SPT=49387 DPT=8545 WINDOW=28800 RES=0x00 SYN URGP=0 
````
it's log in minute when out transaction was created
General logic: when I get new income transaction(confirmed) I am creating out transaction to main account(in same node).
The situation is third on this node, other situations was on other accounts. Can someone explain me wtf going on?

**Comment by bitBac** [comment] 2021-08-31 19:12
also want to add that server is secured with ufw and only `30303                      ALLOW IN    Anywhere`

**Comment by holiman** [comment] 2021-08-31 19:54
Interesting. The theft seems to be 'blind' : maybe you once exposed the api with unlocked account, and someone generated a bunch of signed txs, just waiting for you to get some money in there. In that case, the attacker would generate different values for each nonce, and later select whichever fits best. What command do you use to run geth? Exact parameters?It may also be some malware, possibly. From the logs it doesn't look like the tx was made right there right then though.

**Comment by bitBac** [comment] 2021-08-31 19:59
--syncmode=full --cache=8096 --http --ws --ws.origins * --ws.addr 0.0.0.0 --http.addr 0.0.0.0 --http.corsdomain * --http.api web3,personal,admin,debug,db,net,eth,miner,rpc,txpool --datadir /mnt/eth/eth/ --allow-insecure-unlock

**Comment by bitBac** [comment] 2021-08-31 19:59
> Interesting. The theft seems to be 'blind' : maybe you once exposed the api with unlocked account, and someone generated a bunch of signed txs, just waiting for you to get some money in there. In that case, the attacker would generate different values for each nonce, and later select whichever fits best. What command do you use to run geth? Exact parameters?It may also be some malware, possibly. From the logs it doesn't look like the tx was made right there right then though.

`--syncmode=full --cache=8096 --http --ws --ws.origins * --ws.addr 0.0.0.0 --http.addr 0.0.0.0 --http.corsdomain * --http.api web3,personal,admin,debug,db,net,eth,miner,rpc,txpool --datadir /mnt/eth/eth/ --allow-insecure-unlock`

**Comment by bitBac** [comment] 2021-08-31 20:01
I am understand that my node runned with `--allow-insecure-unlock` but I don't find other way for unlocking account before make withdraw

**Comment by ligi** [comment] 2021-09-02 07:24
can you elaborate what your use case is and why you really need `--allow-insecure-unlock` - pretty sure this is the problem here - did you look into clef?

**Comment by holiman** [comment] 2021-09-02 07:57
Even if you don't use clef, you can supply the password explicitly each time you want to sign something, over the `personal` api. That is still insecure (geth doesn't do TLS, so it'll be plaintext over the wire, unless you provide tls tunnel yourself). But unlocking an account is obviously very insecure, hence why we've named it `--allow-insecure-unlock`, in order to make people think twice before using it.

**Comment by holiman** [comment] 2021-09-02 07:59
So most likely someone found your unlocked account (even if it was just a small window of time) and made a bunch of transactions. 
Your ip logs show that someone is still attempting to call your RPC endpoint (I guess the ipfilter is a recent addition?)

You should consider that account to be compromised, and ensure that no incoming funds land there -- but goes into a brand new account instead.

**Comment by bitBac** [comment] 2021-09-02 08:25
> can you elaborate what your use case is and why you really need `--allow-insecure-unlock` - pretty sure this is the problem here - did you look into clef?

I need to make money transfer from one account to another(main) account, all income transactions(deposits) i am sending to one wallet and I do it with code, so before sending money I need to unlock account and I can't do it becouse it's not allowed by node, that is why I am using `--allow-insecure-unlock`. I don't using clef.

**Comment by holiman** [comment] 2021-09-02 08:53
> so before sending money I need to unlock account and I can't do it becouse it's not allowed by node

You're setting up the account for being emptied by some malicious bot. You should not use this approach, and as I said, consider the account compromised. 

Closing this now, as I think we've found the root cause.

**Closed by holiman** 2021-09-02 08:53 UTC
