### ISSUE TITLE
Feature - better snapshot eta estimation

### ISSUE THREAD

**Issue by yorickdowne** [ethereum/go-ethereum#22430] opened 2021-03-04 11:06 UTC
# Rationale

Current snapshot eta is wildly off in the early stages. On a barebones server with 28,9k read / 9.6k write IOPS, it estimated just over 2000 hours after 4.5h of snapshot generation, then settled down to an estimate of 135h after around 10h. On a low-performing VPS with 3k read / 1k write IOPS, early estimation was over 3150h after 7h of snapshot generation, and ~400h after around 12h.

A better snapshot eta would calm user nerves ... it's also entirely cosmetic.

**Comment by MariusVanDerWijden** [comment] 2021-03-05 10:07
(I misread your question first, so there's a bonus chapter about snap sync now :D )

### snap generation
The current algorithm for snap generation estimation is the following:
- Calculate how many keys have been generated (`done = currentKey - start`)
- Estimate how many need to be generated (`left = maxUint64 - currentKey`)
- Calculate speed (`done / elapsedTime`) 
- Estimate time needed to generate (`left / speed`)

The problem here is that we estimate the items left as if all items up to maxUint64 have to be generated. This is not the case since some of these keys are empty. Thus the estimation incurs a large error margin in the beginning. Maybe it would be better to estimate it as follows:
- Calculate how many accounts have been generated (`gs.accounts`)
- Calculate how much many keys have been generated (`done = currentKey - start`)
- Calculate how many percent of the keyspace was filled (`fillPercentage = gs.accounts / done)
- Estimate how many items need to be generated `left = (maxUint64 - currentKey) * fillPercentage`)
- Calculate speed (`done / elapsedTime`) 
- Estimate time needed to generate (`left / speed`)

### snap sync
The current algorithm for snap sync estimation is the following:
- Calculate how many accounts need to be synced (`accountGaps`)
- Calculate how many accounts are synced (`accountFills = allaccounts - accountGaps`)
- Estimate the number of bytes needed to sync all remaining accounts (`(syncedBytes * allAccounts) / accountFills`) 
- Estimate the time needed to sync all remaining accounts (`(elapsed / syncedBytes) * estimatedBytes`)

I think the problem is that in the beginning the amount of accounts that are not synced is huge, most of these accounts are empty, but we don't know that yet.

**Comment by yorickdowne** [comment] 2021-03-10 20:07
Time travel :)

State sync in progress                   synced=99.56% state=79.48GiB   accounts=122779736@22.27GiB slots=405199341@55.44GiB codes=363044@1.77GiB    eta=-9.464s

**Comment by karalabe** [comment] 2021-03-11 10:11
There's not much we can do wrt better estimation. We don't know in advance how large the state is, so we just start iterating it and see how large it is. If there's a huge contract at the beginning, the generator will think that the state is super saturated and will estimate a large number. Then later when it goes through lots of small contracts, it corrects the guess. It tries to make the best guess, but the more data, the better the guess.

That time travel is a similar fluke :D

**Comment by s1na** [comment] 2021-03-11 17:12
@karalabe is there any state statistics we can hardcode as checkpoints (kinda like chts) which can be used for better eta estimation? maybe like total number of nodes/leaves. Not sure worthwhile the complexity for a once-off process though.

**Comment by holiman** [comment] 2021-03-25 08:56
Closing this, the estimator eventually settles on a reasonable guess, not much else we can do. Hardcoding some numbers is just a never-ending game.

**Closed by holiman** 2021-03-25 08:56 UTC
Labels: type:feature
