### ISSUE TITLE
Sync block problem

### ISSUE THREAD

**Issue by 90hacker** [ethereum/go-ethereum#21825] opened 2020-11-11 11:36 UTC
Sync block is always failing

Error: invalid merkle root (remote: 57cc91ee8b91b956592a27b14386abc2aba723b5f4f9e5d3181ace6b5d3cd433 local: 1f9ee59bfa683a25c7a15b626995a3ad7c58c571b40df96eea31e5c5eed9732d)
##############################

ERROR[11-11|15:08:37.772]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7
280000 Istanbul: 9069000, Muir Glacier: 9200000, Engine: ethash}

Number: 11234873
Hash: 0xd307c642087f1e143e0c7c766e47f77af13e496c8267a55b644bfc86b6f184c7
         0: cumulative: 56209 gas: 56209 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x413e13facc3c6e287746616a34deec0ba55356beb8f3f28f8cc4e3522c3a76c5 logs
: [0xc0244c00b0] bloom: 00000000000000000000000000040000000002000000000000000000000000000000000000000000000000020000010000000000000000000000000000000000000000000000000000000008000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000010000000000000010000001000000000000
2000000080000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
state:

![image](https://user-images.githubusercontent.com/15024497/98807042-0cc52980-2455-11eb-8033-482a78629917.png)

Geth
Version: 1.9.23-stable
Git Commit: 8c2f271528f9cccf541c6ea1c022e98407f26872
Git Commit Date: 20201015
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.3
Operating System: linux
GOPATH=
GOROOT=go

**Comment by holiman** [comment] 2020-11-11 11:42
Please provide the full message (preferrably as text instead of image), and double-check the version number

**Comment by Har01d** [comment] 2020-11-11 11:42
If you’ve just upgraded to the latest release try to run debug.setHead(11234872) or debug.setHead('0xAB6E38')
See https://twitter.com/nikzh/status/1326465592841351168

**Comment by peterlayke** [comment] 2020-11-11 12:19
Tried this keeps stopping at block 11234899. Any other ideas?

**Comment by Crypto2** [comment] 2020-11-11 12:23
Make sure you are on the latest geth version, we had this happen too on the same block on one of our older nodes even though no releases have been marked as mandatory since then.

**Comment by holiman** [comment] 2020-11-11 12:50
> Make sure you are on the latest geth version

^ this

**Comment by peterlayke** [comment] 2020-11-11 13:25
Thanks all, problem was after setting using setHead I had to restart the client. I had just used the command and let it run the first time.

**Comment by 90hacker** [comment] 2020-11-11 13:34
> 谢谢，问题出在使用setHead设置后，我不得不重新启动客户端。我刚刚使用了该命令，并使其第一次运行。

After restarting, I can’t get the latest block number

> eth.syncing
{
  currentBlock: 11236515,
  highestBlock: 11236588,
  knownStates: 410761626,
  pulledStates: 410761233,
  startingBlock: 11234872
}
> eth.blockNumber
0
>

**Comment by play0** [comment] 2020-11-11 21:04
Upgraded to 1.9.23-Stable, rolled back blocks. now I get to the below and my node just resets and winds back blocks. 
This fork has caused a lot of damage, how do I fix this without blowing the whole chain away for days?

{
  currentBlock: 11234913,
  highestBlock: 11238641,
  knownStates: 411108293,
  pulledStates: 411108293,
  startingBlock: 11238340
}

**Comment by play0** [comment] 2020-11-11 21:27
https://blog.infura.io/infura-mainnet-outage-post-mortem-2020-11-11/

When can we get this patch publicly? My production workloads are down until there is a resolution.

**Comment by peterlayke** [comment] 2020-11-11 22:22
![image](https://user-images.githubusercontent.com/47314267/98871148-8e09d400-24c8-11eb-8d13-58103b3f247c.png)

**Comment by randydu** [comment] 2020-11-11 22:43
My two nodes running geth v1.9.16 suffered from this issue today, I applied the debug.setHead(xxx) trick and restart the geth node, it does not work at all, so I have to upgrade the geth version to the latest v1.9.23, and applied the magic "debug.setHead(xxx)' trick again. restart the geth nodes, 

Now one node has finished syncing and works again, another node shows weird behavior as following:

```
 eth.syncing
{
  currentBlock: 11238944,
  highestBlock: 11239046,
  knownStates: 364999353,
  pulledStates: 364881536,
  startingBlock: 11236671
}
> eth.blockNumber
0
```
The syncing messages are:

```
INFO [11-11|22:39:50.893] Imported new state entries               count=384  elapsed="3.079µs"    processed=364881152 pending=117354 trieretry=0   coderetry=0 duplicate=0 unexpected=0

INFO [11-11|22:39:51.349] Initializing fast sync bloom             items=1319333915 errorrate=0.009 elapsed=1h17m15.792s

INFO [11-11|22:39:59.349] Initializing fast sync bloom             items=1321994903 errorrate=0.009 elapsed=1h17m23.792s

INFO [11-11|22:40:04.648] Imported new state entries               count=384  elapsed="3.3µs"      processed=364881536 pending=117817 trieretry=0   coderetry=0 duplicate=0 unexpected=0

INFO [11-11|22:40:07.354] Initializing fast sync bloom             items=1325379313 errorrate=0.009 elapsed=1h17m31.796s

INFO [11-11|22:40:15.354] Initializing fast sync bloom             items=1328175729 errorrate=0.009 elapsed=1h17m39.796s

INFO [11-11|22:40:16.847] Imported new block headers               count=1    elapsed=6.888ms      number=11239047 hash="8d4f9e…9fc8f1" age=1m9s

INFO [11-11|22:40:17.733] Imported new state entries               count=384  elapsed="55.74µs"    processed=364881920 pending=118287 trieretry=0   coderetry=0 duplicate=0 unexpected=0

INFO [11-11|22:40:19.882] Imported new block headers               count=2    elapsed=10.675ms     number=11239049 hash="9e2bb0…0293e7"

INFO [11-11|22:40:23.354] Initializing fast sync bloom             items=1331746356 errorrate=0.009 elapsed=1h17m47.796s

INFO [11-11|22:40:25.937] Imported new state entries               count=288  elapsed="736.253µs"  processed=364882208 pending=118623 trieretry=0   coderetry=0 duplicate=0 unexpected=0

INFO [11-11|22:40:28.954] Imported new block headers               count=1    elapsed=7.441ms      number=11239050 hash="885a53…1a593d"

INFO [11-11|22:40:29.973] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=164.75KiB throttle=398

INFO [11-11|22:40:31.354] Initializing fast sync bloom             items=1334752284 errorrate=0.009 elapsed=1h17m55.796s

INFO [11-11|22:40:36.381] Imported new state entries               count=384  elapsed="129.972µs"  processed=364882592 pending=119062 trieretry=0   coderetry=0 duplicate=0 unexpected=0

INFO [11-11|22:40:38.069] Imported new block headers               count=1    elapsed=27.943ms     number=11239051 hash="c74e9d…4af702"

INFO [11-11|22:40:39.357] Initializing fast sync bloom             items=1337630821 errorrate=0.009 elapsed=1h18m3.799s

INFO [11-11|22:40:41.096] Imported new block headers               count=1    elapsed=6.639ms      number=11239052 hash="3c9210…f1c63b"

INFO [11-11|22:40:47.357] Initializing fast sync bloom             items=1341269535 errorrate=0.009 elapsed=1h18m11.799s

INFO [11-11|22:40:52.734] Imported new state entries               count=493  elapsed="220.964µs"  processed=364883085 pending=119628 trieretry=0   coderetry=0 duplicate=0 unexpected=0

INFO [11-11|22:40:55.358] Initializing fast sync bloom             items=1344203501 errorrate=0.009 elapsed=1h18m19.801s

INFO [11-11|22:40:56.222] Imported new block headers               count=1    elapsed=10.524ms     number=11239053 hash="970b84…26b4ec"

INFO [11-11|22:41:02.118] Imported new state entries               count=384  elapsed="134.762µs"  processed=364883469 pending=120074 trieretry=0   coderetry=0 duplicate=0 unexpected=0

INFO [11-11|22:41:03.362] Initializing fast sync bloom             items=1347454987 errorrate=0.009 elapsed=1h18m27.805s

INFO [11-11|22:41:08.304] Imported new block headers               count=1    elapsed=6.700ms      number=11239054 hash="eabd85…046b3c"

INFO [11-11|22:41:11.363] Initializing fast sync bloom             items=1351124513 errorrate=0.009 elapsed=1h18m35.805s

INFO [11-11|22:41:12.373] Imported new state entries               count=384  elapsed="139.643µs"  processed=364883853 pending=120526 trieretry=0   coderetry=0 duplicate=0 unexpected=0

```

I will run it for a while to see if it can finish syncing by itself, most likely its blockchain data integrity is already corrupted.

**Comment by 90hacker** [comment] 2020-11-12 03:17
> My two nodes running geth v1.9.16 suffered from this issue today, I applied the debug.setHead(xxx) trick and restart the geth node, it does not work at all, so I have to upgrade the geth version to the latest v1.9.23, and applied the magic "debug.setHead(xxx)' trick again. restart the geth nodes,
> 
> Now one node has finished syncing and works again, another node shows weird behavior as following:
> 
> ```
>  eth.syncing
> {
>   currentBlock: 11238944,
>   highestBlock: 11239046,
>   knownStates: 364999353,
>   pulledStates: 364881536,
>   startingBlock: 11236671
> }
> > eth.blockNumber
> 0
> ```
> 
> The syncing messages are:
> 
> ```
> INFO [11-11|22:39:50.893] Imported new state entries               count=384  elapsed="3.079µs"    processed=364881152 pending=117354 trieretry=0   coderetry=0 duplicate=0 unexpected=0
> 
> INFO [11-11|22:39:51.349] Initializing fast sync bloom             items=1319333915 errorrate=0.009 elapsed=1h17m15.792s
> 
> INFO [11-11|22:39:59.349] Initializing fast sync bloom             items=1321994903 errorrate=0.009 elapsed=1h17m23.792s
> 
> INFO [11-11|22:40:04.648] Imported new state entries               count=384  elapsed="3.3µs"      processed=364881536 pending=117817 trieretry=0   coderetry=0 duplicate=0 unexpected=0
> 
> INFO [11-11|22:40:07.354] Initializing fast sync bloom             items=1325379313 errorrate=0.009 elapsed=1h17m31.796s
> 
> INFO [11-11|22:40:15.354] Initializing fast sync bloom             items=1328175729 errorrate=0.009 elapsed=1h17m39.796s
> 
> INFO [11-11|22:40:16.847] Imported new block headers               count=1    elapsed=6.888ms      number=11239047 hash="8d4f9e…9fc8f1" age=1m9s
> 
> INFO [11-11|22:40:17.733] Imported new state entries               count=384  elapsed="55.74µs"    processed=364881920 pending=118287 trieretry=0   coderetry=0 duplicate=0 unexpected=0
> 
> INFO [11-11|22:40:19.882] Imported new block headers               count=2    elapsed=10.675ms     number=11239049 hash="9e2bb0…0293e7"
> 
> INFO [11-11|22:40:23.354] Initializing fast sync bloom             items=1331746356 errorrate=0.009 elapsed=1h17m47.796s
> 
> INFO [11-11|22:40:25.937] Imported new state entries               count=288  elapsed="736.253µs"  processed=364882208 pending=118623 trieretry=0   coderetry=0 duplicate=0 unexpected=0
> 
> INFO [11-11|22:40:28.954] Imported new block headers               count=1    elapsed=7.441ms      number=11239050 hash="885a53…1a593d"
> 
> INFO [11-11|22:40:29.973] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=164.75KiB throttle=398
> 
> INFO [11-11|22:40:31.354] Initializing fast sync bloom             items=1334752284 errorrate=0.009 elapsed=1h17m55.796s
> 
> INFO [11-11|22:40:36.381] Imported new state entries               count=384  elapsed="129.972µs"  processed=364882592 pending=119062 trieretry=0   coderetry=0 duplicate=0 unexpected=0
> 
> INFO [11-11|22:40:38.069] Imported new block headers               count=1    elapsed=27.943ms     number=11239051 hash="c74e9d…4af702"
> 
> INFO [11-11|22:40:39.357] Initializing fast sync bloom             items=1337630821 errorrate=0.009 elapsed=1h18m3.799s
> 
> INFO [11-11|22:40:41.096] Imported new block headers               count=1    elapsed=6.639ms      number=11239052 hash="3c9210…f1c63b"
> 
> INFO [11-11|22:40:47.357] Initializing fast sync bloom             items=1341269535 errorrate=0.009 elapsed=1h18m11.799s
> 
> INFO [11-11|22:40:52.734] Imported new state entries               count=493  elapsed="220.964µs"  processed=364883085 pending=119628 trieretry=0   coderetry=0 duplicate=0 unexpected=0
> 
> INFO [11-11|22:40:55.358] Initializing fast sync bloom             items=1344203501 errorrate=0.009 elapsed=1h18m19.801s
> 
> INFO [11-11|22:40:56.222] Imported new block headers               count=1    elapsed=10.524ms     number=11239053 hash="970b84…26b4ec"
> 
> INFO [11-11|22:41:02.118] Imported new state entries               count=384  elapsed="134.762µs"  processed=364883469 pending=120074 trieretry=0   coderetry=0 duplicate=0 unexpected=0
> 
> INFO [11-11|22:41:03.362] Initializing fast sync bloom             items=1347454987 errorrate=0.009 elapsed=1h18m27.805s
> 
> INFO [11-11|22:41:08.304] Imported new block headers               count=1    elapsed=6.700ms      number=11239054 hash="eabd85…046b3c"
> 
> INFO [11-11|22:41:11.363] Initializing fast sync bloom             items=1351124513 errorrate=0.009 elapsed=1h18m35.805s
> 
> INFO [11-11|22:41:12.373] Imported new state entries               count=384  elapsed="139.643µs"  processed=364883853 pending=120526 trieretry=0   coderetry=0 duplicate=0 unexpected=0
> ```
> 
> I will run it for a while to see if it can finish syncing by itself, most likely its blockchain data integrity is already corrupted.

My problem is the same as yours. The block number is always 0.
Can you share the machine you can work with

**Comment by randydu** [comment] 2020-11-12 03:31
The *bad* node with sync.blockNumber == 0  still cannot sync after many hours, there should be a bug somewhere or the blockchain data is already broken. Fortunately I don't have to resync the whole blockchain, making a copy of block data from the good node should work.

**Comment by randydu** [comment] 2020-11-12 03:44
> My problem is the same as yours. The block number is always 0.
> Can you share the machine you can work with

Sorry, my geth nodes are private and only reserved for internal api services.

**Comment by holiman** [comment] 2020-11-12 07:49
>  making a copy of block data from the good node should work.

Yes, if you have two machines, it's perfectly valid to (when both nodes are shut down) copy the chaindata from one machine to the other. "Sync via scp".

**Comment by randydu** [comment] 2020-11-12 07:57
> The _bad_ node with sync.blockNumber == 0 still cannot sync after many hours, there should be a bug somewhere or the blockchain data is already broken. Fortunately I don't have to resync the whole blockchain, making a copy of block data from the good node should work.

The good news is: the _bad_ node has healed itself before I give up:

```
> eth.syncing
false
> eth.blockNumber
11241586
> 

```
So we must be __patient__ when dealing with eth blockchain ;-)

**Comment by randydu** [comment] 2020-11-12 08:07
> > making a copy of block data from the good node should work.
> 
> Yes, if you have two machines, it's perfectly valid to (when both nodes are shut down) copy the chaindata from one machine to the other. "Sync via scp".

Before rsync or scp the _good_ data to overwrite the _bad_ data, please make sure to backup the nodekey file ( geth/nodekey ), it should be unique for each eth node, otherwise you will have twins with the same identity.

**Comment by AtomicLemon** [comment] 2020-11-12 10:34
Having this exact problem.

**Comment by AtomicLemon** [comment] 2020-11-14 05:36
Confirming that upgrading to Geth-v.1.9.24-stable and then running `debug.setHead('0xAB6E38')` in the console, then restarting geth will fix the issue.

**Comment by ChuckNorrison** [comment] 2020-11-18 09:29
Iam currently upgraded to geth 1.9.24-stable-cc05b050 cause of this issue. Upgraded to M2.SSD without success, even the sync to the root issue is much faster

> eth.blockNumber
> 0

Some Warnings i observed related to that:

> 
> Nov 18 10:25:06 geth-main geth[202068]: WARN [11-18|10:25:06.348] Header broke chain ancestry              peer=6b45efdf39775dc4 number=11278776 hash="0d73de…fde582"
> Nov 18 10:25:11 geth-main geth[202068]: WARN [11-18|10:25:11.184] Rewinding blockchain                     target=11276712
> Nov 18 10:25:11 geth-main geth[202068]: WARN [11-18|10:25:11.309] Rolled back chain segment                header=11278761->11276712 fast=11276508->11276508 block=0->0 reason="syncing canceled (requested)"
> Nov 18 10:25:11 geth-main geth[202068]: WARN [11-18|10:25:11.309] Synchronisation failed, dropping peer    peer=46776dff2667d129 err=timeout
> Nov 18 10:25:11 geth-main geth[202068]: WARN [11-18|10:25:11.415] Synchronisation failed, dropping peer    peer=6b45efdf39775dc4 err="action from bad peer ignored: no pivot included along head header"
> Nov 18 10:25:21 geth-main geth[202068]: WARN [11-18|10:25:21.590] Invalid header encountered               number=11280112 hash="a7c055…44e42a" parent="eba9c9…12e0a2" err="invalid mix digest"
> Nov 18 10:25:21 geth-main geth[202068]: WARN [11-18|10:25:21.591] Rewinding blockchain                     target=11276763
> Nov 18 10:25:21 geth-main geth[202068]: WARN [11-18|10:25:21.717] Rolled back chain segment                header=11278812->11276763 fast=11276526->11276526 block=0->0 reason="invalid mix digest"
> Nov 18 10:25:21 geth-main geth[202068]: WARN [11-18|10:25:21.717] Synchronisation failed, dropping peer    peer=0106da03098626f5 err="retrieved hash chain is invalid: invalid mix digest"
>

**Comment by holiman** [comment] 2020-11-26 08:14
Afaict this can now be closed?

**Closed by holiman** 2020-11-26 08:14 UTC

**Comment by ChuckNorrison** [comment] 2020-11-27 04:53
I reproduced this issue with reverting my chaindata. After deleting ethash here again, the sync makes progress. So ethash is sometimes corrupted and does not match to the chaindata.

**Comment by elsampsa** [comment] 2021-01-02 20:01
I had the same problem.  Updated to 1.9.24, cleared ethhas & restarted.  Seems to work now.

**Comment by jayboy-mabushi** [comment] 2021-08-24 14:03
@Har01d I have having the same issue. and will like to try your suggestions but I am not sure how to run that command.

is it geth debug.setHead(11234872) and should I stop geth first before running it?

Error: invalid merkle root (remote: 2aab9430b0e4f85bcaf8d8214aa9eecd9382110229d0f5a70e838d83c8fab2fb local: 9ffb7df423de5f7307643d05a9522360064c584547b669331fc94d522430                                                                     7a91)
##############################

WARN [08-24|05:06:43.691] Synchronisation failed, dropping peer    peer=48fe5cb55e1e738350754207e2bd14dc093e5847d63cf33307311f9ed5648203 err="retrieved hash chain is in                                                                     valid: invalid merkle root (remote: 2aab9430b0e4f85bcaf8d8214aa9eecd9382110229d0f5a70e838d83c8fab2fb local: 9ffb7df423de5f7307643d05a9522360064c584547b669331fc94d522430                                                                     7a91)"
INFO [08-24|05:06:51.178] Importing heavy sidechain segment        blocks=948  start=13,066,685 end=13,067,632
INFO [08-24|05:06:51.340] Skip duplicated bad block                number=13,066,685 hash=31adab..310947
ERROR[08-24|05:06:51.349]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Pe                                                                     tersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Engine: ethash}

Number: 13066685
Hash: 0x31adab16d72c479c1b5afba06fbf46835eef40f8a299cc1f3938bd3daa310947
         0: cumulative: 234565 gas: 234565 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xb146396b9416f470f8342303f5c993b9b48f241a6af14fcd32a6192a                                                                     25e63df1 logs: [0xc0f7538160 0xc0f75382c0 0xc0f75384d0 0xc0f7538840 0xc0f7538a50 0xc0f7538bb0 0xc0f7538e70 0xc0f7538fd0 0xc0f7539080 0xc0f7539130 0xc0f75391e0 0xc0f7539                                                                     290 0xc0f7539340] bloom: 00000800000400000200000000801000000000000000000000000000000000000000000000000000000002000000000000000000000000000000040000000000002000000100000                                                                     048000008001000000001020000000000040000000280000000008000000000000020000000000040000000000000000000000030000000400000000000000000000080000800000200000080010000000004000                                                                     000000000000000000000200000000000000000000018000000000002000101000008002000100002010000000000000080000004000000000100000000000000000000040010000050000000800000000000440                                                                     004000000000000000004020000000000 state:
         1: cumulative: 344777 gas: 110212 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x75bd39b56f51940b25005dc90f6b8d961fb9e6323a71e2a4fbeec1d8                                                                     bb6f871e logs: [0xc0f75393f0 0xc0f75394a0 0xc0f7539550 0xc0f7539600] bloom: 00200000000000000000000080000000000000000000000000010000000000000000000000000000400000000000                                                                     010002000000080000000000000000000000000000000000000000000008000000200000000000000000000000400040000000000000000000000000000000000000000000000000000000000010000000000800                                                                     800000000000004000000000000000000000000000080000004000100000000000000000000000000080001000000000000100000000000000000000000000000002000000000000000000000000000000000002                                                                     001000000000000020000000200000000000000004000000000000000000000000000000000000000000 state:
         2: cumulative: 519110 gas: 174333 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x1fbba47cedab1f9e78859c248037fbd7983cb3cb550b4dea38a650b0                                                                     2f3e3995 logs: [0xc0f75396b0 0xc0f7539760 0xc0f7539810 0xc0f75398c0 0xc0f7539970 0xc0f7539a20 0xc0f7539ad0] bloom: 00200000000000000000000080000000000000000001000000010                                                                     000000000000000000000000000400001000000010002000000080000000000008000000000000000000000000000000008000000200000000000100000000000400040000000000001000000000000000000000                                                                     000000000000000000000000010000000000800800000000000004000000000000000002000800000080000004000100000000000000000000000000080000000000000000000000000000000000000040000000                                                                     002000000000000000000000000000000000104001000000004000020000000200000000000000004000000000000000000000000000000000000000000 state:
         3: cumulative: 641450 gas: 122340 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x3e4b9379a0f845de88284417e44b08edd1f84e533048f63c6e3f464b                                                                     852118c9 logs: [0xc0f7539c30 0xc0f7539ce0 0xc0f7539d90 0xc0f7539e40 0xc0f7539ef0 0xc084c86840 0xc084c869a0] bloom: 00200000000000000000000080000000000000000100000000000                                                                     000000000000000000000000000000000000000000002000000080000000000008000000000808000000000000000000008000000200000000000100000000000000000000000000001000000000000000000080                                                                     000800400000000000000000010000000000000000000000000200000000000000000000000800000080000004000000000000000000000000000000000000000000000000000000000000000000000040000000                                                                     002000000000000000000000000000000000104001000000004000000080000200000000000000000000000000000000000100000000000000000000000 state:
         4: cumulative: 730762 gas: 89312 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xd7d2d630d8bf14e6358307aee03aac2ba12d20eb4806468b41ed10c29                                                                     04ef84b logs: [0xc084c86b00 0xc084c86c60 0xc084c86dc0 0xc084c86f20] bloom: 002001000000000000000020800000000000000000000000000010000000000000000000000100000000000000000                                                                     000020000800800000000000000000000000000000000000000000000080000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000400100000000100000                                                                     000000000000000000000000000000000000000000800000040000000000000000000000000000000000000000000000000000002040000000000000000000000020080000000000000000000000000002000000                                                                     01000000000000000000000200000000000000000000000000000000000000000000000010000000000 state:
         5: cumulative: 822430 gas: 91668 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x7f5652c03827274389b696780272152a049cc5712126a5ffe89419882                                                                     7257053 logs: [0xc084c87080 0xc084c874a0 0xc084c87810 0xc084c87b80 0xc084da2000] bloom: 00200100000000000000000080000000000000000000000000011000000000000000000000010000                                                                     000000000000000002000080080000000000000000000000000000000000000000000008000000200000000000000000000000008000000000000000000000000000000000000000000000100000000000000010                                                                     000000010000000000000000004000000000000000000001000000080000004000000000000000000000000000000000000000000000000000000200000000000000000000000002008000000000000000040000                                                                     000000200000001000000000000020000000200000000000000000000000000000000000000000420000010000000000 state:
         6: cumulative: 901326 gas: 78896 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x982218aa4dada518b747fce6d8092a8ac931788bb8b3028f3b95d2639                                                                     78bca73 logs: [0xc084da22c0 0xc084da2580 0xc084da26e0 0xc084da2840] bloom: 002001000000000000000020800000000000000000000000000010000000000000000000000100000000000000000                                                                     000020000800800000000000000000000000000000000000000000000080000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000400100000000100000                                                                     000000000000000000000000000000000000000000800000040000000000000000000000000000000000000000000000000000002040000000000000000000000020080000000000000000000000000002000000                                                                     01000000000000000000000200000000000000000000000000000000000000000000000010000000000 state:
         7: cumulative: 1130238 gas: 228912 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x1040cab06b2dce29e185922d5b9cc71208b0eb4eac6e8739d9e0c5d                                                                     554690b84 logs: [0xc084da29a0 0xc084da2c60 0xc084da2dc0 0xc084da2f20 0xc084da3080 0xc084da31e0 0xc084da3340 0xc084da34a0] bloom: 002000000100000000010010800000000000000                                                                     0002000000000000004000000000000000000000000000800000000000200000009002000000000000000000000000000000000080800000a0000002000000000000000000000000000000010000000000000000                                                                     000000000000020000000000000000000000000100008000000000000000000000021000000000000000000000100000800000040000000000000000000002040000000000000010000000000000000000020000                                                                     00028000000000002400000000000000000000000000000000000001000000000000080000000200000000000008010000000000000000000000000010010000000000000 state:
         8: cumulative: 1411852 gas: 281614 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x1d2ebd447c5f3405ea674ee115f17ab22499641f07a2d039487dc3f                                                                     3825c12fe logs: [0xc084da3600 0xc084da3760 0xc084da3ce0 0xc085020160 0xc0850202c0 0xc085020420] bloom: 00010000000000000100000000004000000001000000000000000000000000000                                                                     000000100000000000000000000000002000000080020000040000000002000000000000001000800000208000000000000000000000000000000008000000000080000000002000000000000000000020000000                                                                     000000000000010000800000020000000000000000000000000000000000003000000000000000000000000010000000000000000000000000000800000400000000000000000000000000000000002000000000                                                                     000008000000000000000000000200000000000000000000000200000000000000000000000000000200000080000400000000000000000 state:
         9: cumulative: 1623147 gas: 211295 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xe66b9797678384a7c202fc0c6fd1240f29884116e90fe825e5814a9                                                                     69fff1e9f logs: [0xc0850206e0 0xc085020840 0xc085020a50 0xc085020bb0 0xc085020d10 0xc085020e70 0xc085020fd0 0xc08504a0b0 0xc08504a2c0] bloom: 00210000000000000000000080                                                                     000000004020000000005000000000000020000000000000000800000000000000010002000000080020000000080000000000000000000000000800000008000000200004000000000000000010000000000000                                                                     000000000000000000000000040000000020000000000000000090000800000000000000000000000000000000000010000000000000080400004000100000000000000000000000001080000000000000000000                                                                     000000000004000000000000000002000000000000000000000000100000000000001000001000000000001000200000000000000000000000000000000000000080000008001001000000 state:
         10: cumulative: 2085684 gas: 462537 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x47d50927b13afa4c5a99b0ca8f2a3817114eb76d4d29b15b31ef7f                                                                     63a1207dba logs: [0xc08504a6e0 0xc08504ab00 0xc08504b290 0xc08504b3f0 0xc08504b550 0xc08504b6b0 0xc08504b810 0xc08504ba20 0xc08504bce0 0xc08507a000 0xc08507a2c0 0xc0850                                                                     7a580 0xc08507a840 0xc08507a9a0 0xc08507ab00 0xc08507ad10 0xc08507afd0 0xc08507b1e0 0xc08507b4a0 0xc08507b760] bloom: 00200800001040010000204080000000000000050000000000                                                                     000000000020000000000000800800002000000000000002000000080000000040040000000000000000000000000000000008002000200000000020400000040000400280080008008000020000000c20001000                                                                     100800008080000000040000000011010200000000000000000000000000000000000000000104000000080810004000000000000040800000000000000000000000000010000000002002000100000008100100                                                                     020002110000002000100000000000020000000100001800020002001020000010600010200000800000800200440000002000000000000008020040000000 state:
         11: cumulative: 2106684 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xaecea1e38abdef0de3a794d626bd651ef7dfded1820f665c030ba7e                                                                     a4721d29e logs: [] bloom: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                     000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                     000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                     0000000000000000000000000000000000 state:
         12: cumulative: 2127684 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x1dd68d6eee614c3924261ff3a66bedbbb081933a91c45439cdc2f03                                                                     785e1b710 logs: [] bloom: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                     000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                     000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                     0000000000000000000000000000000000 state:
         13: cumulative: 2148684 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x5c8ffc542b61b6cd3d3c378f72f808f46182bffba36281374f90f6c                                                                     a42dd5e2a logs: [] bloom: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                     000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                     000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                     0000000000000000000000000000000000 state:
