### ISSUE TITLE
  need to connect go ethereum in my tools which working RPC with python config. ini file, 

### ISSUE THREAD

**Issue by tamazib243** [ethereum/go-ethereum#26260] opened 2022-11-26 18:44 UTC
hello when i try to connect to geth my rpc config.ini file i got error, ,, IPC / RPC error: 403 ,, and ,, error: no suitable peers available'}} ,, how i can solve which command can i use ? thanks

**Comment by ligi** [comment] 2022-11-26 20:37
You need to provide more details. 
e.g. do you use light client? Which chain? ..

**Comment by tamazib243** [comment] 2022-11-27 06:07
Yes,i used light client, anyway i got error goerli and mainnet

**Comment by ligi** [comment] 2022-11-27 06:09
duplicate of #25623

**Closed by ligi** 2022-11-27 06:09 UTC
Labels: type:docs, need:more-information

**Comment by tamazib243** [comment] 2022-11-27 06:12
![image](https://user-images.githubusercontent.com/34917942/204121866-5fff0879-deb8-49ab-b462-587cc37a5a03.png)

**Comment by tamazib243** [comment] 2022-11-27 06:15
I will explain how this tool works, I tested this on ganache, this tool sends the transaction automatically, Without any consent, only by command... Now I want to test goerli and mainnet, It also receives calls in the back.. I want to do the same on the mainnet via go ethereum

**Comment by ligi** [comment] 2022-11-27 06:32
you cannot use light mode for now

**Comment by tamazib243** [comment] 2022-11-27 07:22
> you cannot use light mode for now

What can I use instead? Can i use --syncmode fast?
