### ISSUE TITLE
TX failing even though correct amount of gas was supplied.

### ISSUE THREAD

**Issue by vogelito** [ethereum/go-ethereum#2878] opened 2016-07-28 21:43 UTC
I have an account that I want to sweep. I want to sweep to a funds splitting contract (ETC/ETH). I'm only interested in sweeping the ETH balance and my goal is for the account to end up with a balance of *zero* (e.g. no dust).

This is the fund splitting contract I'm trying to use: [0x1e143b2588705dfea63a17f2032ca123df995ce0](http://etherscan.io/address/0x1e143b2588705dfea63a17f2032ca123df995ce0#code)

It seems as if the gas required for this operation is 29,717. For example, here is a sample transaction I sent to the contract, which according to etherscan.io required that amount of gas: [0x7cd52325c0945d0de975a6713abdc50659c0c62ef523a1a99f2ad2a2d4128a8f](http://etherscan.io/tx/0x7cd52325c0945d0de975a6713abdc50659c0c62ef523a1a99f2ad2a2d4128a8f)

However, if I send a transaction and limit the amount of gas to 29,717, my transaction fails. For example, here is a sample transaction I sent to the contract with a gas limit of 29,717, which failed: [0xcd31481b4dd9410daa22c8a47f9a4b29ef4a305877174eb346433bb4e6b03089](http://etherscan.io/tx/0xcd31481b4dd9410daa22c8a47f9a4b29ef4a305877174eb346433bb4e6b03089)

I discovered the minimum amount of gas that I need to specify for one of these transfers to work is 31,991.
Transaction with 31,991 gas which worked: [0x7cd52325c0945d0de975a6713abdc50659c0c62ef523a1a99f2ad2a2d4128a8f](http://etherscan.io/tx/0x7cd52325c0945d0de975a6713abdc50659c0c62ef523a1a99f2ad2a2d4128a8f)
Transaction with 31,990 gas which failed: [0x8c92fde3cf07b3cdbf4dcc54ed6ccfb072f22933ab556612f3d23317a2466280](http://etherscan.io/tx/0x8c92fde3cf07b3cdbf4dcc54ed6ccfb072f22933ab556612f3d23317a2466280)

However, when the tx goes through, it seems as if it only used 29,717 gas. For example:
Account [0x19d90f1106c600bd8a70b5775776b4ecdc7a945b](http://etherscan.io/address/0x19d90f1106c600bd8a70b5775776b4ecdc7a945b) had a balance of `0.01282711 ETH` (at block `1964300`).

I sent transaction [0xb57c8b5aede3070e2fb80ea9a21ec43293cb5c7392ccb36357388422e9055509](http://etherscan.io/tx/0xb57c8b5aede3070e2fb80ea9a21ec43293cb5c7392ccb36357388422e9055509) with the following details:
* Value: `0.01218729 ETH`
* Gas: `31991`
* Gas Price: `20000000000 Wei`

So:
* Balance before TX: `0.01282711 ETH`
* Amount to send: `0.01218729 ETH`
* Supposed cost of TX: `Gas` * `Price` = `0.00063982 ETH`
* Balance - Amount to send - Supposed cost of TX = *ZERO!*

However, as you can see, account [0x19d90f1106c600bd8a70b5775776b4ecdc7a945b](http://etherscan.io/address/0x19d90f1106c600bd8a70b5775776b4ecdc7a945b) has a balance of `0.00004548 ETH`, meaning the cost of the TX was actually `0.00059434 ETH`, which at a gas price of `20000000000 Wei`, would mean the gas used was: `29717` (which we already knew of course)!

So the question is:
- Why are the transactions which specify a gas limit of `29717` failing?

#### System information

Geth version: 1.4.10-stable-c2eea630
OS & Version: Linux

#### Expected behaviour
Transaction 0x19d90f1106c600bd8a70b5775776b4ecdc7a945b should've been successful.

#### Actual behaviour
Transaction 0x19d90f1106c600bd8a70b5775776b4ecdc7a945b failed due to lack of gas.

#### Steps to reproduce the behaviour
Use the `transfer(address)` function of contract `0x1e143b2588705dfea63a17f2032ca123df995ce0` by sending some amount and limit the amount of gas to `29717`

#### Backtrace

````
[backtrace]
````

**Comment by obscuren** [comment] 2016-07-29 11:56
Input makes the gas consumption variable. What does `ClassicCheck` do and how is it implemented? There might be a reason why it works with some and doesn't work with other txs.

**Comment by vogelito** [comment] 2016-07-29 17:12
hi @obscuren - thanks for getting back to me.

When the contact was deployed, it invoked (this contract)[http://etherscan.io/address/0x882fb4240f9a11e197923d0507de9a983ed69239#code], which in turn checks whether the balance of (the DAO withdrawal contract)[http://etherscan.io/address/0xbf4ed7b27f1d666546e30d74d50d173d20bca754] was more than 1,000,000 ETH and stored that in the variable `isClassic`, which `ClassicCheck` returns.

What this effectively accomplishes is checking whether you're living in ETC or ETH world.

My transactions **always** work when I set the tx gas to `31991` and it **always** consumes *exactly* `29717` gas. But it **always** fails when I set the tx gas lower than `31991`

**Comment by trapp** [comment] 2016-07-30 21:29
It possible has to do with the gas stipend that the send function gets, 2300 gas when I recall correctly. The sending account needs to have funds for this stipend but it doesn't use all 2300 of it. This means you will have to have more funds available as you will end up paying for gas with the end result that you cannot sweep the whole balance of an account into this contract.

**Comment by obscuren** [comment] 2016-07-30 22:15
@trapp is correct.

**Comment by karalabe** [comment] 2016-09-02 17:11
Closing as working as intended.

**Closed by karalabe** 2016-09-02 17:11 UTC

**Comment by vogelito** [comment] 2016-09-02 17:24
Thanks @karalabe. The intended behavior is unfortunate, but understood.

**Comment by karalabe** [comment] 2016-09-03 15:54
There could be other more exotic use cases too. For example if a contract behaves differently based on how much gas it's given, it may actually be impossible to make a meaningful gas estimation as it may run on a completely different code path.

So in general, sweeping from/to contracts may not be so obvious or even possible depending on their implementation :)

**Comment by vogelito** [comment] 2016-09-03 17:37
Sure - but if that's the case then how would you *ever* know how big the gas stipend should be?

Shouldn't a tx *only* fail if `gas used > gas limit`? In this case it fails even though `gas used <= gas limit`.
