### ISSUE TITLE
How to get right value from "address(this).balance" in local private geth

### ISSUE THREAD

**Issue by daenamkim** [ethereum/go-ethereum#20804] opened 2020-03-24 03:39 UTC
#### System information

Geth version: `geth version`
```sh
Geth
Version: 1.9.12-stable
Git Commit: b6f1c8dcc058a936955eb8e5766e2962218924bc
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14
Operating System: darwin
GOPATH=/Users/daenamkim/go
GOROOT=/usr/local/opt/go/libexec
```
OS & Version: Windows/Linux/OSX
![image](https://user-images.githubusercontent.com/16159767/77385675-1fa6c300-6dcc-11ea-9ad7-31735b829442.png)

#### Expected behaviour
Return right value from `address(this).balance`

#### Actual behaviour
Return always 0 from `address(this).balance`

#### Steps to reproduce the behaviour
https://gist.github.com/daenamkim/d064bb1ed874d5e2477b179a97a89e93

**Comment by karalabe** [comment] 2020-03-24 08:51
You mentioned that you deployed this on testnets too and they behave the same? Can you send us a contract address on Goerli? Would be super easy to repro that way and verify what's going wrong?

**Comment by daenamkim** [comment] 2020-03-25 06:04
Things that I have tested on TestNet (Ropsten, Rinkeby) were fine but local private node with genesis file in https://gist.github.com/daenamkim/d064bb1ed874d5e2477b179a97a89e93

So I just want to know about some missing configs when I run geth or wrong part of genesis file

**Comment by karalabe** [comment] 2020-03-25 09:04
Aaah, I see. You might be missing the Petersburg hard fork `"petersburgBlock": 0`. Solidity might use some features introduced in that. See https://github.com/ethereum/go-ethereum#defining-the-private-genesis-state for all the forks

**Comment by daenamkim** [comment] 2020-03-25 11:25
Thanks! but even I added `"petersburgBlock": 0` and tried access `address(this).balance`, it still returned `abi: attempting to unmarshall an empty string while arguments are expected` 😢

**Comment by shoenseiwaso** [comment] 2020-03-31 14:51
@karalabe leaving the new genesis block question aside for now, is there a way to specify the petersburg block for a private PoA network, without resetting the entire network?

Also, the `--override.muirglacier` and `--override.istanbul` options do not appear to work for private chains:

```
$ geth --datadir test <snip> override.istanbul 12 --override.muirglacier 13 console
INFO [03-31|23:01:33.196] Maximum peer count                       ETH=50 LES=0 total=50
INFO [03-31|23:01:33.223] Starting peer-to-peer node               instance=Geth/v1.9.12-stable-b6f1c8dc/darwin-amd64/go1.14
INFO [03-31|23:01:33.223] Allocated trie memory caches             clean=512.00MiB dirty=0.00B
INFO [03-31|23:01:33.223] Allocated cache and file handles         database=./test/geth/chaindata cache=512.00MiB handles=5120
INFO [03-31|23:01:33.312] Opened ancient database                  database=./test/geth/chaindata/ancient
INFO [03-31|23:01:33.313] Initialised chain configuration          config="{ChainID: 25846 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: <nil> Istanbul: <nil>, Muir Glacier: <nil>, Engine: clique}"
```

Note the `Petersburg: <nil> Istanbul: <nil>, Muir Glacier: <nil>` despite the `override.istanbul 12 --override.muirglacier 13` being passed on the command line.

Is this expected? If so, how can we "upgrade" a currently-running PoA local blockchain?

**Comment by shoenseiwaso** [comment] 2020-03-31 15:21
@karalabe ok, partially resolved this with #20841: the sample genesis state omits both Istanbul and Muir Glacier blocks, which need to be set for this to work.

**Comment by shoenseiwaso** [comment] 2020-04-03 13:53
@karalabe any comment on the [note above](https://github.com/ethereum/go-ethereum/issues/20804#issuecomment-606676690) about the intended behaviour of `--override.istanbul`? Is it intended to work on private networks? It would be useful to avoid resetting chain data when a fork occurs.

**Comment by holiman** [comment] 2020-08-13 08:37
I'm going to close this, reasoning: 
- The `balance(self)` is compiled into `SELFBALANCE`, an opcode introduced in petersburg, 
- Remaining issue `abi: attempting to unmarshall...` is something else, and it would be better to open a separate ticket if that still is unresolved

**Comment by holiman** [comment] 2020-08-13 08:38
re `--override.istanbul`, it's supposed to be used _before_ istanbul, to postpone the built-in schedule. Not meant for custom configurations.

**Closed by holiman** 2020-08-13 08:37 UTC
Labels: status:triage
