### ISSUE TITLE
eth同步越来越慢

### ISSUE THREAD

**Issue by yzn5555** [ethereum/go-ethereum#21822] opened 2020-11-11 09:03 UTC
今天发现eth节点同步速度越来越慢，差了300个块，官方浏览器上显示平均出块速度13s左右一个块，节点同步速度变成大约1min一个块，为什么突然出现这个情况了，
eth本地节点部署版本：v1.9.9版本，官方最新稳定版本为：v1.9.22 是否是升级到9.22版本可以解决这个问题。

**Comment by hadv** [comment] 2020-11-11 10:04
@holiman google translate :)

```
Today, I found that the synchronization speed of the eth node is getting slower and slower, with a difference of 300 blocks. The official browser shows that the average block generation speed is about 13s, and the node synchronization speed has become about 1 minute. Why does this happen suddenly?
eth local node deployment version: v1.9.9 version, the latest official stable version is: v1.9.22. Whether it is upgraded to version 9.22 can solve this problem?
```

**Comment by yzn5555** [comment] 2020-11-11 10:21
我刚才已经把版本升级到v1.9.22版本了，解决了同步块卡顿问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ethereum/go-ethereum"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月11日(星期三) 晚上6:04
收件人:&nbsp;"ethereum/go-ethereum"<go-ethereum@noreply.github.com&gt;;
抄送:&nbsp;"1076813060"<1076813060@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ethereum/go-ethereum] eth同步越来越慢 (#21822)





 
@holiman google translate :)
 Today, I found that the synchronization speed of the eth node is getting slower and slower, with a difference of 300 blocks. The official browser shows that the average block generation speed is about 13s, and the node synchronization speed has become about 1 minute. Why does this happen suddenly? eth local node deployment version: v1.9.9 version, the latest official stable version is: v1.9.22. Whether it is upgraded to version 9.22 can solve this problem?

**Comment by Vasilisck** [comment] 2020-11-11 10:25
Got same error, but currently can't update daemon to new version. Is there any way to fix this without updating? Currently version is v1.9.11.

**Comment by yzn5555** [comment] 2020-11-11 10:28
这个我不知道在不更新版本的情况下解决卡顿问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ethereum/go-ethereum"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月11日(星期三) 晚上6:26
收件人:&nbsp;"ethereum/go-ethereum"<go-ethereum@noreply.github.com&gt;;
抄送:&nbsp;"1076813060"<1076813060@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ethereum/go-ethereum] eth同步越来越慢 (#21822)





 
Got same error, but currently can't update daemon to new version. Is there any way to fix this without updating? Currently version is v1.9.11.

**Comment by holiman** [comment] 2020-11-11 10:35
I don't know if this is the root cause, but today at block `11234873`, one of the transactions hit a consensus issue in older geth-versions. In order to get around that, we recommend using a more recent version of geth, e.g. `1.9.20` or higher. Also, tomorrow we're releasing `1.9.24` which will address a critical DoS issue: https://mobile.twitter.com/go_ethereum/status/1326448260949684228

**Comment by Har01d** [comment] 2020-11-11 11:37
Upgrade the node to the latest version: https://twitter.com/nikzh/status/1326465592841351168

**Comment by rjl493456442** [comment] 2020-11-12 09:14
I will close it now. Upgrade the Geth should fix it(the consensus issue). Feel free to reopen it if it's still not working.

**Closed by rjl493456442** 2020-11-12 09:14 UTC
