### ISSUE TITLE
geth export does not work

### ISSUE THREAD

**Issue by hievan2016** [ethereum/go-ethereum#2749] opened 2016-06-28 13:32 UTC
System information

Geth
Version: 1.4.5-stable-27df30f3
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.4
OS: linux

Expected behaviour

geth export <filename> dumps chain from datadir to filename

Actual behaviour

/mnt/vdb/ethereum_code/go-ethereum/build/bin/geth export aaa 0 100
I0628 21:27:58.306040 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/ubuntu/.ethereum/chaindata
I0628 21:27:58.338974 core/blockchain.go:206] Last header: #0 [d4e56740…] TD=17179869184
I0628 21:27:58.339041 core/blockchain.go:207] Last block: #0 [d4e56740…] TD=17179869184
I0628 21:27:58.339059 core/blockchain.go:208] Fast block: #0 [d4e56740…] TD=17179869184
I0628 21:27:58.339132 cmd/utils/cmd.go:199] Exporting blockchain toaaa
I0628 21:27:58.339207 core/blockchain.go:401] exporting 101 blocks...
Fatal: Export error: export failed on #1: not found

------>>> specified block range does not work

ubuntu@VM-14-43-ubuntu:/mnt/vdb/hdchain$ /mnt/vdb/ethereum_code/go-ethereum/build/bin/geth export aaa
I0628 21:29:16.788478 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/ubuntu/.ethereum/chaindata
I0628 21:29:16.834694 core/blockchain.go:206] Last header: #0 [d4e56740…] TD=17179869184
I0628 21:29:16.852534 core/blockchain.go:207] Last block: #0 [d4e56740…] TD=17179869184
I0628 21:29:16.852608 core/blockchain.go:208] Fast block: #0 [d4e56740…] TD=17179869184
I0628 21:29:16.852700 cmd/utils/cmd.go:185] Exporting blockchain toaaa
I0628 21:29:16.852788 core/blockchain.go:401] exporting 1 blocks...
I0628 21:29:16.853113 cmd/utils/cmd.go:194] Exported blockchain toaaa

Export done in 3.063256msubuntu@VM-14-43-ubuntu:/mnt/vdb/hdchain$ ll aaa
-rwxrwxr-x 1 ubuntu ubuntu 540 Jun 28 21:29 aaa*

------>>> if block range is not specified, seems only one block is exported, while there are over 10000 blocks.

Reproduce

geth export <filename>   start_block   end_block

**Comment by karalabe** [comment] 2016-06-29 09:26
The logs state that your chain is empty:

```
I0628 21:29:16.834694 core/blockchain.go:206] Last header: #0 [d4e56740…] TD=17179869184
I0628 21:29:16.852534 core/blockchain.go:207] Last block: #0 [d4e56740…] TD=17179869184
I0628 21:29:16.852608 core/blockchain.go:208] Fast block: #0 [d4e56740…] TD=17179869184
```

Hence why export can only export the genesis block. There doesn't seem to be anything else in there. Please check that you try to export from the correct data directory.

**Comment by karalabe** [comment] 2016-06-30 09:46
Closing as `works as intended`. Please reopen with more information if you believe there still is an issue and not just a slight user (datadir) error.

**Closed by karalabe** 2016-06-30 09:46 UTC

**Comment by hievan2016** [comment] 2016-07-03 08:16
do I need to specify the datadir when running 'geth export', I got error when doing that 

./geth export backup 0 100 --datadir /mnt/vdb/hdchain/data
Incorrect Usage.

export [arguments...]

There should be some other block, I can see them from the console


> eth.getBlock(1)
{
  difficulty: 4,
  extraData: "0xd783010405844765746887676f312e352e34856c696e7578",
  gasLimit: 2249600790429697,
  gasUsed: 0,
  hash: "0x64e4340b048ccef5c1af02bce3fd9b9b5173d49e90d7ff797e979004bfe0d624",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0xbeea68bdaf616ce3aaa4152e836130c26ff84d0d",
  nonce: "0x4d89933f0101028c",
  number: 1,
  parentHash: "0x94fc65c38695cfbe9904ba8b0eda2581c603b7818a2e2c4a57634aebeb649943",
  receiptRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 536,
  stateRoot: "0x9e6e6f29a3294f6529fd05096c460d86345c8246b331b8fa269f9d638e37f159",
  timestamp: 1467532641,
  totalDifficulty: 8,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
