### ISSUE TITLE
get eth_getLogs error  "code": -32000,  "message": "context canceled"

### ISSUE THREAD

**Issue by 1099223026** [ethereum/go-ethereum#19146] opened 2019-02-21 09:32 UTC
Hello, I have a problem in the geth private chain.
Postman Request the following:
![image](https://user-images.githubusercontent.com/22950089/53158235-1ada7300-35fe-11e9-86fd-83be650a6401.png)

How should I solve this problem?

**Comment by xiaods** [comment] 2019-02-23 10:26
hi @1099223026 you need pasted geth version and specified the block correctly.

**Comment by 1099223026** [comment] 2019-02-25 02:36
Thank you for your reply.

Geth version 1.9.0 - unstable

Backup the previous private chain block data to other directories, rebuild the private chain on the local virtual machine and start mining. Everything is normal, and the eth_getLogs method can be accessed, as shown in the figure:
![image](https://user-images.githubusercontent.com/22950089/53310392-a64a5180-38e7-11e9-9425-a45294b4d3fc.png)

However, as long as I put the previous block data into the private chain data directory of the local virtual machine, the following figure will appear:
![image](https://user-images.githubusercontent.com/22950089/53310444-eb6e8380-38e7-11e9-9e65-0897e556927a.png)

I suspect it's the books themselves.
Because the log file is too large, this is the truncated part of the log:
`nohup: ignoring input and appending output to 'nohup.out'
INFO [02-12|11:09:30.628] Maximum peer count                       ETH=25 LES=0 total=25
WARN [02-12|11:09:30.630] Found deprecated node list file /root/eth_sync/private-chain/static-nodes.json, please use the TOML config file instead. 
INFO [02-12|11:09:30.630] Starting peer-to-peer node               instance=Geth/v1.9.0-unstable-e726d836/linux-amd64/go1.10.1
INFO [02-12|11:09:30.630] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [02-12|11:09:30.630] Allocated cache and file handles         database=/root/eth_sync/private-chain/geth/chaindata cache=512.00MiB handles=32767
INFO [02-12|11:09:30.698] Initialised chain configuration          config="{ChainID: 5 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Constantinople: <nil>  ConstantinopleFix: <nil> Engine: unknown}"
INFO [02-12|11:09:30.698] Disk storage enabled for ethash caches   dir=/root/eth_sync/private-chain/geth/ethash count=3
INFO [02-12|11:09:30.698] Disk storage enabled for ethash DAGs     dir=/root/.ethash                            count=2
INFO [02-12|11:09:30.699] Initialising Ethereum protocol           versions="[63 62]" network=19303
WARN [02-12|11:09:30.771] Head state missing, repairing chain      number=2422 hash=adb7c5…7e7a1a
INFO [02-12|11:09:30.839] Rewound blockchain to past state         number=162  hash=9e13c6…9db691
INFO [02-12|11:09:30.839] Loaded most recent local header          number=2422 hash=adb7c5…7e7a1a td=12195356368 age=2m50s
INFO [02-12|11:09:30.839] Loaded most recent local full block      number=162  hash=9e13c6…9db691 td=820405728   age=19h5m39s
INFO [02-12|11:09:30.839] Loaded most recent local fast block      number=2422 hash=adb7c5…7e7a1a td=12195356368 age=2m50s
INFO [02-12|11:09:30.839] Loaded local transaction journal         transactions=0 dropped=0
INFO [02-12|11:09:30.839] Regenerated local transaction journal    transactions=0 accounts=0
WARN [02-12|11:09:30.839] Blockchain not empty, fast sync disabled 
INFO [02-12|11:09:30.849] New local node record                    seq=4 id=10c2a2e9fe101147 ip=127.0.0.1 udp=0 tcp=61916
INFO [02-12|11:09:30.849] Started P2P networking                   self="enode://c6578cfd8b76a2638c45774d975d7a7542729fd7fa704499e1a139c60a172638aa71df56dad9dd361f150b646bcd4df042ffc4e146e1f965a41b086f646b16f0@127.0.0.1:61916?discport=0"
INFO [02-12|11:09:30.850] IPC endpoint opened                      url=/root/eth_sync/private-chain/geth.ipc
INFO [02-12|11:09:30.851] HTTP endpoint opened                     url=http://0.0.0.0:6704                   cors=* vhosts=localhost
INFO [02-12|11:09:50.849] Block synchronisation started 
INFO [02-12|11:09:50.951] Importing heavy sidechain segment        blocks=2048 start=163 end=2210
INFO [02-12|11:09:51.315] Imported new chain segment               blocks=2048 txs=1 mgas=0.052 elapsed=364.004ms mgasps=0.144 number=2210 hash=812677…79298c age=1h55m31s dirty=53.80KiB
INFO [02-12|11:09:51.321] Importing sidechain segment              start=2211 end=2422
INFO [02-12|11:09:51.356] Imported new chain segment               blocks=212  txs=0 mgas=0.000 elapsed=34.761ms  mgasps=0.000 number=2422 hash=adb7c5…7e7a1a age=3m11s    dirty=53.80KiB
INFO [02-12|11:10:55.833] Etherbase automatically configured       address=0x64fa0C93Bf9fe94E472aff8746B08E56005FEd72
INFO [02-12|11:11:02.987] Updated mining threads                   threads=4
INFO [02-12|11:11:02.987] Transaction pool price threshold updated price=1000000000
INFO [02-12|11:11:02.988] Commit new mining work                   number=2423 sealhash=d8f2fe…10e778 uncles=0 txs=0 gas=0 fees=0 elapsed=185.69µs
INFO [02-12|11:12:15.515] Successfully sealed new block            number=2423 sealhash=d8f2fe…10e778 hash=e8039e…021740 elapsed=1m12.527s
INFO [02-12|11:12:15.515] 🔨 mined potential block                  number=2423 hash=e8039e…021740
INFO [02-12|11:12:15.515] Commit new mining work                   number=2424 sealhash=de67c0…4807c2 uncles=0 txs=0 gas=0 fees=0 elapsed=194.979µs
INFO [02-12|11:12:20.486] Successfully sealed new block            number=2424 sealhash=de67c0…4807c2 hash=d2c1da…146a64 elapsed=4.971s
INFO [02-12|11:12:20.486] 🔨 mined potential block                  number=2424 hash=d2c1da…146a64
INFO [02-12|11:12:20.487] Commit new mining work                   number=2425 sealhash=b8d89a…2a567f uncles=0 txs=0 gas=0 fees=0 elapsed=197.213µs
INFO [02-12|11:12:30.255] Served eth_subscribe                     conn=183.67.61.93:37351 reqid=74 t=16.291µs err="notifications not supported"
INFO [02-12|11:12:31.916] Served eth_subscribe                     conn=183.67.61.93:37351 reqid=74 t=24.235µs err="notifications not supported"
INFO [02-12|11:13:07.687] Successfully sealed new block            number=2425 sealhash=b8d89a…2a567f hash=9b4051…95d31f elapsed=47.200s
INFO [02-12|11:13:07.687] 🔨 mined potential block                  number=2425 hash=9b4051…95d31f
INFO [02-12|11:13:07.688] Commit new mining work                   number=2426 sealhash=a154de…5bc7fa uncles=0 txs=0 gas=0 fees=0 elapsed=150.677µs
INFO [02-12|11:13:14.746] Successfully sealed new block            number=2426 sealhash=a154de…5bc7fa hash=a22aed…9ced42 elapsed=7.058s
INFO [02-12|11:13:14.746] 🔨 mined potential block                  number=2426 hash=a22aed…9ced42
INFO [02-12|11:13:14.746] Commit new mining work                   number=2427 sealhash=b70f54…bbe7c8 uncles=0 txs=0 gas=0 fees=0 elapsed=135.167µs
INFO [02-12|11:13:51.982] Successfully sealed new block            number=2427 sealhash=b70f54…bbe7c8 hash=3bd0c1…7fa545 elapsed=37.235s
INFO [02-12|11:13:51.982] 🔨 mined potential block                  number=2427 hash=3bd0c1…7fa545
INFO [02-12|11:13:51.983] Commit new mining work                   number=2428 sealhash=35eea4…5d0074 uncles=0 txs=0 gas=0 fees=0 elapsed=190.887µs
INFO [02-12|11:13:55.914] Successfully sealed new block            number=2428 sealhash=35eea4…5d0074 hash=376512…b90914 elapsed=3.931s
INFO [02-12|11:13:55.914] 🔨 mined potential block                  number=2428 hash=376512…b90914
INFO [02-12|11:13:55.915] Commit new mining work                   number=2429 sealhash=9c03fc…5aab78 uncles=0 txs=0 gas=0 fees=0 elapsed=176.169µs
INFO [02-12|11:14:19.770] Successfully sealed new block            number=2429 sealhash=9c03fc…5aab78 hash=b68e84…84b4a9 elapsed=23.855s
INFO [02-12|11:14:19.770] 🔨 mined potential block                  number=2429 hash=b68e84…84b4a9
INFO [02-12|11:14:19.770] Commit new mining work                   number=2430 sealhash=a0e3cc…ce495b uncles=0 txs=0 gas=0 fees=0 elapsed=127.918µs
INFO [02-12|11:14:46.962] Successfully sealed new block            number=2430 sealhash=a0e3cc…ce495b hash=9c1ae0…176b9c elapsed=27.192s
INFO [02-12|11:14:46.963] 🔗 block reached canonical chain          number=2423 hash=e8039e…021740
INFO [02-12|11:14:46.963] 🔨 mined potential block                  number=2430 hash=9c1ae0…176b9c
INFO [02-12|11:14:46.963] Commit new mining work                   number=2431 sealhash=fb93db…472130 uncles=0 txs=0 gas=0 fees=0 elapsed=202.207µs
nohup: ignoring input and appending output to 'nohup.out'
INFO [02-12|11:15:43.948] Maximum peer count                       ETH=25 LES=0 total=25
WARN [02-12|11:15:43.949] Found deprecated node list file /root/eth_sync/private-chain/static-nodes.json, please use the TOML config file instead. 
INFO [02-12|11:15:43.949] Starting peer-to-peer node               instance=Geth/v1.9.0-unstable-e726d836/linux-amd64/go1.10.1
INFO [02-12|11:15:43.949] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [02-12|11:15:43.949] Allocated cache and file handles         database=/root/eth_sync/private-chain/geth/chaindata cache=512.00MiB handles=32767
INFO [02-12|11:15:44.011] Initialised chain configuration          config="{ChainID: 5 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Constantinople: <nil>  ConstantinopleFix: <nil> Engine: unknown}"
INFO [02-12|11:15:44.011] Disk storage enabled for ethash caches   dir=/root/eth_sync/private-chain/geth/ethash count=3
INFO [02-12|11:15:44.011] Disk storage enabled for ethash DAGs     dir=/root/.ethash                            count=2
INFO [02-12|11:15:44.011] Initialising Ethereum protocol           versions="[63 62]" network=19303
WARN [02-12|11:15:44.083] Head state missing, repairing chain      number=2430 hash=9c1ae0…176b9c
INFO [02-12|11:15:44.152] Rewound blockchain to past state         number=162  hash=9e13c6…9db691
INFO [02-12|11:15:44.152] Loaded most recent local header          number=2430 hash=9c1ae0…176b9c td=12235621680 age=1m25s
INFO [02-12|11:15:44.152] Loaded most recent local full block      number=162  hash=9e13c6…9db691 td=820405728   age=19h11m53s
INFO [02-12|11:15:44.152] Loaded most recent local fast block      number=2430 hash=9c1ae0…176b9c td=12235621680 age=1m25s
INFO [02-12|11:15:44.152] Loaded local transaction journal         transactions=0 dropped=0
INFO [02-12|11:15:44.152] Regenerated local transaction journal    transactions=0 accounts=0
WARN [02-12|11:15:44.152] Blockchain not empty, fast sync disabled 
INFO [02-12|11:15:44.163] New local node record                    seq=5 id=10c2a2e9fe101147 ip=127.0.0.1 udp=0 tcp=61916
INFO [02-12|11:15:44.163] Started P2P networking                   self="enode://c6578cfd8b76a2638c45774d975d7a7542729fd7fa704499e1a139c60a172638aa71df56dad9dd361f150b646bcd4df042ffc4e146e1f965a41b086f646b16f0@127.0.0.1:61916?discport=0"
INFO [02-12|11:15:44.164] IPC endpoint opened                      url=/root/eth_sync/private-chain/geth.ipc
INFO [02-12|11:15:44.165] HTTP endpoint opened                     url=http://0.0.0.0:6704                   cors=* vhosts=localhost
INFO [02-12|11:15:54.162] Block synchronisation started 
INFO [02-12|11:15:54.261] Importing heavy sidechain segment        blocks=2048 start=163 end=2210
INFO [02-12|11:15:54.613] Imported new chain segment               blocks=2048 txs=1 mgas=0.052 elapsed=352.211ms mgasps=0.149 number=2210 hash=812677…79298c age=2h1m34s   dirty=53.80KiB
INFO [02-12|11:15:54.620] Importing sidechain segment              start=2211 end=2430
INFO [02-12|11:15:54.655] Imported new chain segment               blocks=220  txs=0 mgas=0.000 elapsed=34.824ms  mgasps=0.000 number=2430 hash=9c1ae0…176b9c age=1m35s     dirty=53.80KiB
INFO [02-12|11:16:20.488] Updated mining threads                   threads=4
INFO [02-12|11:16:20.489] Transaction pool price threshold updated price=1000000000
INFO [02-12|11:16:20.489] Etherbase automatically configured       address=0x64fa0C93Bf9fe94E472aff8746B08E56005FEd72
INFO [02-12|11:16:20.489] Commit new mining work                   number=2431 sealhash=ef0acd…f0d863 uncles=0 txs=0 gas=0 fees=0 elapsed=171.068µs
INFO [02-12|11:16:53.525] Successfully sealed new block            number=2431 sealhash=ef0acd…f0d863 hash=515356…55f2e8 elapsed=33.035s
INFO [02-12|11:16:53.525] 🔨 mined potential block                  number=2431 hash=515356…55f2e8
INFO [02-12|11:16:53.525] Commit new mining work                   number=2432 sealhash=bcab39…ca352d uncles=0 txs=0 gas=0 fees=0 elapsed=157.929µs
INFO [02-12|11:17:53.700] Successfully sealed new block            number=2432 sealhash=bcab39…ca352d hash=0aec43…d8f213 elapsed=1m0.174s
INFO [02-12|11:17:53.700] 🔨 mined potential block                  number=2432 hash=0aec43…d8f213
INFO [02-12|11:17:53.700] Commit new mining work                   number=2433 sealhash=63c4ec…f1ace6 uncles=0 txs=0 gas=0 fees=0 elapsed=180.577µs
INFO [02-12|11:18:12.938] Successfully sealed new block            number=2433 sealhash=63c4ec…f1ace6 hash=b9855a…3d4028 elapsed=19.237s
INFO [02-12|11:18:12.938] 🔨 mined potential block                  number=2433 hash=b9855a…3d4028
INFO [02-12|11:18:12.938] Commit new mining work                   number=2434 sealhash=c03430…42984a uncles=0 txs=0 gas=0 fees=0 elapsed=198.012µs
INFO [02-12|11:19:30.580] Successfully sealed new block            number=2434 sealhash=c03430…42984a hash=4a838b…0d527e elapsed=1m17.641s
INFO [02-12|11:19:30.580] 🔨 mined potential block                  number=2434 hash=4a838b…0d527e
INFO [02-12|11:19:30.580] Commit new mining work                   number=2435 sealhash=a95fe4…106f29 uncles=0 txs=0 gas=0 fees=0 elapsed=138.075µs
INFO [02-12|11:19:32.089] Successfully sealed new block            number=2435 sealhash=a95fe4…106f29 hash=140fed…57169c elapsed=1.509s
INFO [02-12|11:19:32.090] 🔨 mined potential block                  number=2435 hash=140fed…57169c
INFO [02-12|11:19:32.090] Commit new mining work                   number=2436 sealhash=9458fb…f4c9c4 uncles=0 txs=0 gas=0 fees=0 elapsed=162.764µs
INFO [02-12|11:19:34.230] Successfully sealed new block            number=2436 sealhash=9458fb…f4c9c4 hash=ccdd3f…73801d elapsed=2.139s
INFO [02-12|11:19:34.230] 🔨 mined potential block                  number=2436 hash=ccdd3f…73801d
INFO [02-12|11:19:34.230] Commit new mining work                   number=2437 sealhash=c41d8f…9e8d5c uncles=0 txs=0 gas=0 fees=0 elapsed=110.887µs
INFO [02-12|11:20:20.234] Successfully sealed new block            number=2437 sealhash=c41d8f…9e8d5c hash=7de753…deddf1 elapsed=46.004s
INFO [02-12|11:20:20.234] 🔨 mined potential block                  number=2437 hash=7de753…deddf1
INFO [02-12|11:20:20.235] Commit new mining work                   number=2438 sealhash=c7bc93…bc31e0 uncles=0 txs=0 gas=0 fees=0 elapsed=167.863µs
INFO [02-12|11:21:02.475] Successfully sealed new block            number=2438 sealhash=c7bc93…bc31e0 hash=bf623c…315581 elapsed=42.240s
INFO [02-12|11:21:02.475] 🔗 block reached canonical chain          number=2431 hash=515356…55f2e8
INFO [02-12|11:21:02.475] 🔨 mined potential block                  number=2438 hash=bf623c…315581
INFO [02-12|11:21:02.475] Commit new mining work                   number=2439 sealhash=4ccb37…0dca1e uncles=0 txs=0 gas=0 fees=0 elapsed=148.945µs
INFO [02-12|11:21:02.480] Successfully sealed new block            number=2439 sealhash=4ccb37…0dca1e hash=11df0d…cc24a5 elapsed=4.989ms
INFO [02-12|11:21:02.480] 🔗 block reached canonical chain          number=2432 hash=0aec43…d8f213
INFO [02-12|11:21:02.480] 🔨 mined potential block                  number=2439 hash=11df0d…cc24a5
INFO [02-12|11:21:02.480] Commit new mining work                   number=2440 sealhash=4e8bf7…84c949 uncles=0 txs=0 gas=0 fees=0 elapsed=115.249µs
INFO [02-12|11:21:30.247] Successfully sealed new block            number=2440 sealhash=4e8bf7…84c949 hash=fdc98e…f9d982 elapsed=27.767s
INFO [02-12|11:21:30.247] 🔗 block reached canonical chain          number=2433 hash=b9855a…3d4028
INFO [02-12|11:21:30.247] 🔨 mined potential block                  number=2440 hash=fdc98e…f9d982
INFO [02-12|11:21:30.248] Commit new mining work                   number=2441 sealhash=9f6672…960d4d uncles=0 txs=0 gas=0 fees=0 elapsed=170.762µs
INFO [02-12|11:23:40.121] Successfully sealed new block            number=2441 sealhash=9f6672…960d4d hash=3270c9…fd744c elapsed=2m9.873s
INFO [02-12|11:23:40.121] 🔗 block reached canonical chain          number=2434 hash=4a838b…0d527e
INFO [02-12|11:23:40.121] 🔨 mined potential block                  number=2441 hash=3270c9…fd744c
INFO [02-12|11:23:40.121] Commit new mining work                   number=2442 sealhash=47edff…5ea0f2 uncles=0 txs=0 gas=0 fees=0 elapsed=261.873µs
INFO [02-12|11:24:05.352] Successfully sealed new block            number=2442 sealhash=47edff…5ea0f2 hash=aa3f58…8e6ba3 elapsed=25.231s
INFO [02-12|11:24:05.353] 🔗 block reached canonical chain          number=2435 hash=140fed…57169c
INFO [02-12|11:24:05.353] 🔨 mined potential block                  number=2442 hash=aa3f58…8e6ba3
INFO [02-12|11:24:05.353] Commit new mining work                   number=2443 sealhash=82f9ea…33f665 uncles=0 txs=0 gas=0 fees=0 elapsed=189.726µs
nohup: ignoring input and appending output to 'nohup.out'
INFO [02-12|11:24:33.672] Maximum peer count                       ETH=25 LES=0 total=25
WARN [02-12|11:24:33.674] Found deprecated node list file /root/eth_sync/private-chain/static-nodes.json, please use the TOML config file instead. 
INFO [02-12|11:24:33.674] Starting peer-to-peer node               instance=Geth/v1.9.0-unstable-e726d836/linux-amd64/go1.10.1
INFO [02-12|11:24:33.674] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [02-12|11:24:33.674] Allocated cache and file handles         database=/root/eth_sync/private-chain/geth/chaindata cache=512.00MiB handles=32767
INFO [02-12|11:24:33.736] Initialised chain configuration          config="{ChainID: 5 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Constantinople: <nil>  ConstantinopleFix: <nil> Engine: unknown}"
INFO [02-12|11:24:33.737] Disk storage enabled for ethash caches   dir=/root/eth_sync/private-chain/geth/ethash count=3
INFO [02-12|11:24:33.737] Disk storage enabled for ethash DAGs     dir=/root/.ethash                            count=2
INFO [02-12|11:24:33.737] Initialising Ethereum protocol           versions="[63 62]" network=19303
WARN [02-12|11:24:33.809] Head state missing, repairing chain      number=2442 hash=aa3f58…8e6ba3
INFO [02-12|11:24:33.878] Rewound blockchain to past state         number=162  hash=9e13c6…9db691
INFO [02-12|11:24:33.879] Loaded most recent local header          number=2442 hash=aa3f58…8e6ba3 td=12296019648 age=53s
INFO [02-12|11:24:33.879] Loaded most recent local full block      number=162  hash=9e13c6…9db691 td=820405728   age=19h20m42s
INFO [02-12|11:24:33.879] Loaded most recent local fast block      number=2442 hash=aa3f58…8e6ba3 td=12296019648 age=53s
INFO [02-12|11:24:33.879] Loaded local transaction journal         transactions=0 dropped=0
INFO [02-12|11:24:33.879] Regenerated local transaction journal    transactions=0 accounts=0
WARN [02-12|11:24:33.879] Blockchain not empty, fast sync disabled 
INFO [02-12|11:24:33.890] New local node record                    seq=6 id=10c2a2e9fe101147 ip=127.0.0.1 udp=0 tcp=61916
INFO [02-12|11:24:33.890] Started P2P networking                   self="enode://c6578cfd8b76a2638c45774d975d7a7542729fd7fa704499e1a139c60a172638aa71df56dad9dd361f150b646bcd4df042ffc4e146e1f965a41b086f646b16f0@127.0.0.1:61916?discport=0"
INFO [02-12|11:24:33.891] IPC endpoint opened                      url=/root/eth_sync/private-chain/geth.ipc
INFO [02-12|11:24:33.892] HTTP endpoint opened                     url=http://0.0.0.0:6704                   cors=* vhosts=localhost
INFO [02-12|11:24:33.892] WebSocket endpoint opened                url=ws://[::]:8546
INFO [02-12|11:24:53.890] Block synchronisation started 
INFO [02-12|11:24:53.989] Importing heavy sidechain segment        blocks=2048 start=163 end=2210
INFO [02-12|11:24:54.348] Imported new chain segment               blocks=2048 txs=1 mgas=0.052 elapsed=358.069ms mgasps=0.146 number=2210 hash=812677…79298c age=2h10m34s  dirty=53.80KiB
INFO [02-12|11:24:54.354] Importing sidechain segment              start=2211 end=2442
INFO [02-12|11:24:54.392] Imported new chain segment               blocks=232  txs=0 mgas=0.000 elapsed=37.422ms  mgasps=0.000 number=2442 hash=aa3f58…8e6ba3 age=1m14s     dirty=53.80KiB
INFO [02-12|11:31:43.122] Setting new local account                address=0x64fa0C93Bf9fe94E472aff8746B08E56005FEd72
INFO [02-12|11:31:43.123] Submitted transaction                    fullhash=0x5f4b98ece6a8aaa8e8269a7edf5858dcf1faa98acb8a9319ef678edc7e10a37c recipient=0x3B3582348B6C4b2e1F8Ef2f3c4e5755c0A454873
INFO [02-12|11:32:40.372] Submitted transaction                    fullhash=0x2c33b88f12cffd45d49b7c48d7f77441a620a3af1f76b3615e5d57ed5750c57f recipient=0x2F4D29506D602eE29bB82BC50f95b0d4AAF6d083
INFO [02-12|11:40:15.290] Submitted transaction                    fullhash=0x7b119653dec94515f7dae93ba43972dab86a487fffcc457104ed4057178514a6 recipient=0x4686432976E69D76c902Ab9Bd054028b44f5e8c8
......

WARN [02-21|15:13:57.259] Blockchain not empty, fast sync disabled 
INFO [02-21|15:13:57.270] New local node record                    seq=8 id=10c2a2e9fe101147 ip=127.0.0.1 udp=0 tcp=61916
INFO [02-21|15:13:57.270] Started P2P networking                   self="enode://c6578cfd8b76a2638c45774d975d7a7542729fd7fa704499e1a139c60a172638aa71df56dad9dd361f150b646bcd4df042ffc4e146e1f965a41b086f646b16f0@127.0.0.1:61916?discport=0"
INFO [02-21|15:13:57.271] IPC endpoint opened                      url=/root/eth_sync/private-chain/geth.ipc
INFO [02-21|15:13:57.272] HTTP endpoint opened                     url=http://0.0.0.0:6704                   cors=* vhosts=localhost
INFO [02-21|15:14:38.668] Served eth_getLogs                       conn=183.67.63.231:9574 reqid=74 t=251.769µs err="context canceled"
INFO [02-21|15:16:42.858] Etherbase automatically configured       address=0x64fa0C93Bf9fe94E472aff8746B08E56005FEd72
INFO [02-21|15:16:52.019] Updated mining threads                   threads=3
INFO [02-21|15:16:52.019] Transaction pool price threshold updated price=1000000000
INFO [02-21|15:16:52.019] Commit new mining work                   number=163   sealhash=0aa38b…b5dfaa uncles=0 txs=0 gas=0 fees=0 elapsed=296.579µs
INFO [02-21|15:16:54.030] Successfully sealed new block            number=163   sealhash=0aa38b…b5dfaa hash=f2194a…e2fbbf elapsed=2.010s
INFO [02-21|15:16:54.030] 🔨 mined potential block                  number=163   hash=f2194a…e2fbbf
INFO [02-21|15:16:54.030] Commit new mining work                   number=164   sealhash=9610f1…7a7612 uncles=0 txs=0 gas=0 fees=0 elapsed=167.685µs
INFO [02-21|15:17:17.269] Block synchronisation started 
INFO [02-21|15:17:17.269] Mining aborted due to sync 
INFO [02-21|15:17:41.997] Successfully sealed new block            number=164   sealhash=9610f1…7a7612 hash=5bf7cf…b2507d elapsed=47.966s
INFO [02-21|15:17:41.997] 🔨 mined potential block                  number=164   hash=5bf7cf…b2507d
WARN [02-21|15:18:58.509] Synchronisation failed, retrying         err="block body download canceled (requested)"
INFO [02-21|15:18:58.509] Commit new mining work                   number=165   sealhash=fb9a9e…64d463 uncles=0 txs=0 gas=0 fees=0 elapsed=176.92µs
......

INFO [02-12|11:54:40.661] Successfully sealed new block            number=2444 sealhash=e924bf…83419f hash=222c65…f7a61b elapsed=18.731s
INFO [02-12|11:54:40.661] 🔨 mined potential block                  number=2444 hash=222c65…f7a61b
INFO [02-12|11:54:40.661] Commit new mining work                   number=2445 sealhash=6aecf7…9fa644 uncles=0 txs=0 gas=0     fees=0          elapsed=248.598µs
WARN [02-12|11:54:42.545] Failed transaction send attempt          from=0x64fa0C93Bf9fe94E472aff8746B08E56005FEd72 to=0xF448b79008A225cc8151783DC53Dc4CC0Cb19124 value=0 err="could not decrypt key with given passphrase"
INFO [02-12|11:54:42.545] Served personal_sendTransaction          conn=183.67.61.93:37819 reqid=personal_sendTransaction_1549943692 t=1.602673234s err="could not decrypt key with given passphrase"
INFO [02-12|11:55:07.514] Submitted transaction                    fullhash=0x2f9f182f03459e2e0f08cd828dc46275d22af5df14ab13b12fff667ca32af5d8 recipient=0xF448b79008A225cc8151783DC53Dc4CC0Cb19124
INFO [02-12|11:55:07.808] Commit new mining work                   number=2445 sealhash=2433a6…371a0a uncles=0 txs=1 gas=52331 fees=5.2331e-05 elapsed=667.158µs
INFO [02-12|11:55:21.866] Submitted transaction                    fullhash=0xda8a2d5615ef0603624d8788cbb44cc48dcba457ca1f03cfd1c7d657d0a4f7b4 recipient=0x4686432976E69D76c902Ab9Bd054028b44f5e8c8
......
`

Looking forward to your reply.
Thank you.

**Comment by xiaods** [comment] 2019-02-27 12:17
yes, i think so,  the block data is disrupted. you need rebuild the data then it works like a charm.

**Comment by 1099223026** [comment] 2019-03-07 07:46
@xiaods Thank you for your reply. Even though I re-created the private chain and started mining, it did not solve my problem.It is ok at the beginning, but so far more than 30000 blocks have been affected by the same problem. Other RPC interface functions can be accessed normally, but only 'eth_getLogs' cannot be accessed. The error message is as follows:
![image](https://user-images.githubusercontent.com/22950089/53940167-f5666280-40ef-11e9-91fc-b5cc6bf7c186.png)

I have been puzzled by this problem for a long time, I hope it can be solved, please

**Comment by Frankeyfeng** [comment] 2019-04-04 05:55
Same error.

**Comment by offerm** [comment] 2019-04-05 06:56
I face the same error

**Comment by xiaods** [comment] 2019-04-05 08:10
hi all, i think this is very regression bug, can't figure out what reason caused that. so please waiting  2.9.x version. hope can bypass this issue.

**Comment by cyberfab007** [comment] 2019-04-06 00:43
Same issue here , I am building a token explorer for my private network and am getting this error,

**Comment by xiaods** [comment] 2019-04-06 13:16
oops. maybe this is bug.

**Comment by Troodi** [comment] 2019-04-09 15:03
Fix it please!

**Comment by LefterisJP** [comment] 2019-04-16 16:57
@karalabe Raiden users also started getting this. Is it possible to get some answer/acknowledgement as to the nature of the problem? Any way we can help you guys debug?

**Comment by Troodi** [comment] 2019-04-16 19:58
I can suggest using the parity client for now, there is no such problem. And the functionality is the same. I decided it that way.

**Comment by karalabe** [comment] 2019-04-17 07:30
What version is everyone here using? We've fixed one potential issue on master (stable should be working). Can anyone provide us a repro?

**Comment by karalabe** [comment] 2019-04-17 07:31
It also helps to know whether it's a full node or light node.

**Comment by offerm** [comment] 2019-04-17 08:51
@karalabe I was using 1.9.0-unstable.
Build from master a few weeks back.

I can confirm that after pull from master and `make geth` the problem is now resolved.

Many thanks!!!!

**Comment by karalabe** [comment] 2019-04-17 09:36
Closing this issue. This error never happened on stable, only on unstable master branch. AFAIK it was fixed about 1-2 weeks ago there too. If it still persists or appears on latest master, please open a new issue. Thank you for the reports! Keep them coming.

**Closed by karalabe** 2019-04-17 09:36 UTC

**Comment by ferittuncer** [comment] 2019-12-04 13:55
Having the same issue with `1.9.8`
