### ISSUE TITLE
Interrupted block-sync finishing with panic error

### ISSUE THREAD

**Issue by fzzr-** [ethereum/go-ethereum#3503] opened 2017-01-01 15:06 UTC
#### System information

Geth version: `1.5.5-stable`
OS & Version: OSX 10.11.6 (15G1108) on the MBA (13-inch, Late 2010)

#### Expected behaviour

Normal (without any errors) shutting down when got `ctrl+c` interrupt event.

#### Actual behaviour

Panic error when finishing block synchronisation after user's interrupt event (`ctrl+c`).

#### Steps to reproduce the behaviour

1. `geth`
1. wait full initialisation & start (line like `Block synchronisation started`)
1. `^C` (ctrl+c)
1. boom!

#### Backtrace

````
I0101 03:13:22.556662 core/blockchain.go:1047] imported 24 blocks,   334 txs ( 23.755 Mg) in    8.150s ( 2.915 Mg/s). #1743892 [42896f81… / 43e13fa6…]
^CI0101 03:13:24.806115 cmd/utils/cmd.go:83] Got interrupt, shutting down...
I0101 03:13:24.851444 node/node.go:373] IPC endpoint closed: /Users/ak/Library/Ethereum/geth.ipc
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 14304 [running]:
panic(0x486e3a0, 0xc42395e920)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
sync.(*WaitGroup).Wait(0xc420220308)
	/usr/local/opt/go/libexec/src/sync/waitgroup.go:133 +0xfe
github.com/ethereum/go-ethereum/core.(*BlockChain).Stop(0xc420220240)
	/private/tmp/ethereum-20161230-26629-jkf72d/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:590 +0x9b
github.com/ethereum/go-ethereum/eth.(*Ethereum).Stop(0xc4201141c0, 0xc4246e2480, 0xc420dc1f28)
	/private/tmp/ethereum-20161230-26629-jkf72d/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:439 +0x40
github.com/ethereum/go-ethereum/node.(*Node).Stop(0xc4203d0480, 0x0, 0x0)
	/private/tmp/ethereum-20161230-26629-jkf72d/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:509 +0x1fb
created by github.com/ethereum/go-ethereum/cmd/utils.StartNode.func1
	/private/tmp/ethereum-20161230-26629-jkf72d/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:84 +0x1cf
````

#### Full log

````
~/.ethash > geth
I0101 03:07:41.331842 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/ak/Library/Ethereum/chaindata
I0101 03:07:41.433782 ethdb/database.go:176] closed db:/Users/ak/Library/Ethereum/chaindata
I0101 03:07:41.434486 node/node.go:176] instance: Geth/v1.5.5-stable-ff07d548/darwin/go1.7.4
I0101 03:07:41.434522 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/ak/Library/Ethereum/chaindata
I0101 03:07:41.550969 eth/backend.go:191] Protocol Versions: [63 62], Network Id: 1
I0101 03:07:41.552273 eth/backend.go:219] Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}
I0101 03:07:41.555163 core/blockchain.go:219] Last header: #1741077 [6111dcab…] TD=29337543666694264879
I0101 03:07:41.555190 core/blockchain.go:220] Last block: #1741077 [6111dcab…] TD=29337543666694264879
I0101 03:07:41.555205 core/blockchain.go:221] Fast block: #1741077 [6111dcab…] TD=29337543666694264879
I0101 03:07:41.558204 p2p/server.go:342] Starting Server
I0101 03:07:43.713207 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv2-IP1
I0101 03:07:43.737881 p2p/discover/udp.go:227] Listening, enode://dc6a0114744c78dfbccbc52bf983418aa62cb2c047ae3731ed5590cea975796e38459c843ef44c1b2012fb046ff29c2009daf482a2bda55515bfc3aa4255387d@192.168.28.198:30303
I0101 03:07:43.740297 node/node.go:341] IPC endpoint opened: /Users/ak/Library/Ethereum/geth.ipc
I0101 03:07:43.740781 p2p/server.go:610] Listening on [::]:30303
I0101 03:07:43.756658 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv2-IP1
I0101 03:08:20.942549 eth/downloader/downloader.go:326] Block synchronisation started
I0101 03:08:26.566860 core/blockchain.go:1047] imported 4 blocks,    46 txs (  1.399 Mg) in    4.197s ( 0.333 Mg/s). #1741081 [66ca9659… / db08afad…]
I0101 03:08:34.820185 core/blockchain.go:1047] imported 51 blocks,   342 txs ( 21.093 Mg) in    8.095s ( 2.606 Mg/s). #1741132 [181739d7… / b9980a1f…]
I0101 03:08:42.857712 core/blockchain.go:1047] imported 84 blocks,   353 txs ( 33.178 Mg) in    8.037s ( 4.128 Mg/s). #1741216 [b9980a1f… / a0b8e51d…]
I0101 03:08:50.934024 core/blockchain.go:1047] imported 131 blocks,   414 txs ( 23.784 Mg) in    8.076s ( 2.945 Mg/s). #1741347 [a0b8e51d… / adedcdab…]
I0101 03:08:59.086276 core/blockchain.go:1047] imported 94 blocks,   645 txs ( 23.525 Mg) in    8.152s ( 2.886 Mg/s). #1741441 [adedcdab… / a7fd1727…]
I0101 03:09:07.137582 core/blockchain.go:1047] imported 120 blocks,   838 txs ( 34.259 Mg) in    8.051s ( 4.255 Mg/s). #1741561 [a7fd1727… / c1b97b35…]
I0101 03:09:15.155664 core/blockchain.go:1047] imported 108 blocks,   935 txs ( 33.829 Mg) in    8.018s ( 4.219 Mg/s). #1741669 [c1b97b35… / 187ec63a…]
I0101 03:09:23.232958 core/blockchain.go:1047] imported 87 blocks,   677 txs ( 35.693 Mg) in    8.077s ( 4.419 Mg/s). #1741756 [187ec63a… / 54a9d360…]
I0101 03:09:31.431928 core/blockchain.go:1047] imported 8 blocks,    82 txs ( 19.426 Mg) in    8.198s ( 2.369 Mg/s). #1741764 [54a9d360… / dd192589…]
I0101 03:09:39.991579 core/blockchain.go:1047] imported 8 blocks,   105 txs ( 22.010 Mg) in    8.559s ( 2.571 Mg/s). #1741772 [dd192589… / e13adb5f…]
I0101 03:09:48.424776 core/blockchain.go:1047] imported 5 blocks,    72 txs ( 17.740 Mg) in    8.433s ( 2.104 Mg/s). #1741777 [e13adb5f… / 8454b73c…]
I0101 03:09:56.548611 core/blockchain.go:1047] imported 73 blocks,   465 txs ( 30.914 Mg) in    8.123s ( 3.805 Mg/s). #1741850 [8454b73c… / b2eff690…]
I0101 03:10:04.759206 core/blockchain.go:1047] imported 128 blocks,   441 txs ( 25.908 Mg) in    8.210s ( 3.155 Mg/s). #1741978 [b2eff690… / aa80d937…]
I0101 03:10:12.834185 core/blockchain.go:1047] imported 24 blocks,  1222 txs ( 28.089 Mg) in    8.074s ( 3.478 Mg/s). #1742002 [aa80d937… / eaf7dce8…]
I0101 03:10:21.011875 core/blockchain.go:1047] imported 53 blocks,   798 txs ( 25.710 Mg) in    8.177s ( 3.144 Mg/s). #1742055 [eaf7dce8… / 837554d3…]
I0101 03:10:29.108036 core/blockchain.go:1047] imported 71 blocks,   838 txs ( 32.224 Mg) in    8.096s ( 3.980 Mg/s). #1742126 [837554d3… / 7cd53e93…]
I0101 03:10:37.199660 core/blockchain.go:1047] imported 108 blocks,   601 txs ( 26.122 Mg) in    8.091s ( 3.228 Mg/s). #1742234 [7cd53e93… / 5bc32775…]
I0101 03:10:45.417105 core/blockchain.go:1047] imported 135 blocks,   686 txs ( 37.981 Mg) in    8.217s ( 4.622 Mg/s). #1742369 [5bc32775… / 5a51cb33…]
I0101 03:10:53.479667 core/blockchain.go:1047] imported 127 blocks,   704 txs ( 25.809 Mg) in    8.062s ( 3.201 Mg/s). #1742496 [5a51cb33… / 723bdf8d…]
I0101 03:11:01.932372 core/blockchain.go:1047] imported 144 blocks,   767 txs ( 33.362 Mg) in    8.452s ( 3.947 Mg/s). #1742640 [723bdf8d… / e0400ed5…]
I0101 03:11:11.911987 core/blockchain.go:1047] imported 84 blocks,  1185 txs ( 31.678 Mg) in    9.979s ( 3.174 Mg/s). #1742724 [e0400ed5… / 66a9f4e1…]
I0101 03:11:20.052772 core/blockchain.go:1047] imported 44 blocks,  1268 txs ( 31.304 Mg) in    8.140s ( 3.845 Mg/s). #1742768 [66a9f4e1… / 53b72dc4…]
I0101 03:11:25.882337 core/blockchain.go:1047] imported 103 blocks,   448 txs ( 19.449 Mg) in    5.829s ( 3.336 Mg/s). #1742871 [53b72dc4… / 437941bb…]
I0101 03:11:34.401551 core/blockchain.go:1047] imported 114 blocks,   332 txs ( 15.132 Mg) in    8.031s ( 1.884 Mg/s). #1742985 [6cc25c20… / 48f1c65d…]
I0101 03:11:42.620183 core/blockchain.go:1047] imported 96 blocks,   606 txs ( 25.255 Mg) in    8.218s ( 3.073 Mg/s). #1743081 [48f1c65d… / a43fb55c…]
I0101 03:11:50.700974 core/blockchain.go:1047] imported 131 blocks,   779 txs ( 36.024 Mg) in    8.080s ( 4.458 Mg/s). #1743212 [a43fb55c… / df44b7ab…]
I0101 03:11:59.398526 core/blockchain.go:1047] imported 123 blocks,   625 txs ( 24.064 Mg) in    8.697s ( 2.767 Mg/s). #1743335 [df44b7ab… / b6b98c1c…]
I0101 03:12:07.553976 core/blockchain.go:1047] imported 110 blocks,   611 txs ( 27.781 Mg) in    8.155s ( 3.406 Mg/s). #1743445 [b6b98c1c… / cd836861…]
I0101 03:12:15.928232 core/blockchain.go:1047] imported 67 blocks,  1040 txs ( 27.834 Mg) in    8.374s ( 3.324 Mg/s). #1743512 [cd836861… / c5783fda…]
I0101 03:12:24.298433 core/blockchain.go:1047] imported 71 blocks,  1308 txs ( 28.171 Mg) in    8.370s ( 3.366 Mg/s). #1743583 [c5783fda… / 2b4a8b6a…]
I0101 03:12:32.343023 core/blockchain.go:1047] imported 110 blocks,   599 txs ( 32.799 Mg) in    8.044s ( 4.077 Mg/s). #1743693 [2b4a8b6a… / 410ead89…]
I0101 03:12:40.420626 core/blockchain.go:1047] imported 88 blocks,   449 txs ( 22.254 Mg) in    8.077s ( 2.755 Mg/s). #1743781 [410ead89… / 8a9a36de…]
I0101 03:12:48.877570 core/blockchain.go:1047] imported 17 blocks,   208 txs ( 14.824 Mg) in    8.456s ( 1.753 Mg/s). #1743798 [8a9a36de… / 86de1c40…]
I0101 03:12:57.488909 core/blockchain.go:1047] imported 26 blocks,   398 txs ( 28.160 Mg) in    8.611s ( 3.270 Mg/s). #1743824 [86de1c40… / f6d05875…]
I0101 03:13:05.806308 core/blockchain.go:1047] imported 24 blocks,   384 txs ( 26.010 Mg) in    8.317s ( 3.127 Mg/s). #1743848 [f6d05875… / 4691f9cb…]
I0101 03:13:14.406637 core/blockchain.go:1047] imported 20 blocks,   229 txs ( 18.612 Mg) in    8.600s ( 2.164 Mg/s). #1743868 [4691f9cb… / 42896f81…]
I0101 03:13:22.556662 core/blockchain.go:1047] imported 24 blocks,   334 txs ( 23.755 Mg) in    8.150s ( 2.915 Mg/s). #1743892 [42896f81… / 43e13fa6…]
^CI0101 03:13:24.806115 cmd/utils/cmd.go:83] Got interrupt, shutting down...
I0101 03:13:24.851444 node/node.go:373] IPC endpoint closed: /Users/ak/Library/Ethereum/geth.ipc
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 14304 [running]:
panic(0x486e3a0, 0xc42395e920)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
sync.(*WaitGroup).Wait(0xc420220308)
	/usr/local/opt/go/libexec/src/sync/waitgroup.go:133 +0xfe
github.com/ethereum/go-ethereum/core.(*BlockChain).Stop(0xc420220240)
	/private/tmp/ethereum-20161230-26629-jkf72d/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:590 +0x9b
github.com/ethereum/go-ethereum/eth.(*Ethereum).Stop(0xc4201141c0, 0xc4246e2480, 0xc420dc1f28)
	/private/tmp/ethereum-20161230-26629-jkf72d/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:439 +0x40
github.com/ethereum/go-ethereum/node.(*Node).Stop(0xc4203d0480, 0x0, 0x0)
	/private/tmp/ethereum-20161230-26629-jkf72d/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:509 +0x1fb
created by github.com/ethereum/go-ethereum/cmd/utils.StartNode.func1
	/private/tmp/ethereum-20161230-26629-jkf72d/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:84 +0x1cf
~/.ethash > geth
I0101 03:13:35.223733 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/ak/Library/Ethereum/chaindata
I0101 03:13:35.728175 ethdb/database.go:176] closed db:/Users/ak/Library/Ethereum/chaindata
I0101 03:13:35.729170 node/node.go:176] instance: Geth/v1.5.5-stable-ff07d548/darwin/go1.7.4
I0101 03:13:35.729207 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/ak/Library/Ethereum/chaindata
I0101 03:13:35.876042 eth/backend.go:191] Protocol Versions: [63 62], Network Id: 1
I0101 03:13:35.878589 eth/backend.go:219] Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}
I0101 03:13:35.884125 core/blockchain.go:219] Last header: #1743897 [745d0f0d…] TD=29477997882842306767
I0101 03:13:35.884157 core/blockchain.go:220] Last block: #1743897 [745d0f0d…] TD=29477997882842306767
I0101 03:13:35.884173 core/blockchain.go:221] Fast block: #1743897 [745d0f0d…] TD=29477997882842306767
I0101 03:13:35.894073 p2p/server.go:342] Starting Server
I0101 03:13:38.040469 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv2-IP1
I0101 03:13:38.112729 p2p/discover/udp.go:227] Listening, enode://dc6a0114744c78dfbccbc52bf983418aa62cb2c047ae3731ed5590cea975796e38459c843ef44c1b2012fb046ff29c2009daf482a2bda55515bfc3aa4255387d@192.168.28.198:30303
I0101 03:13:38.115782 p2p/server.go:610] Listening on [::]:30303
I0101 03:13:38.116791 node/node.go:341] IPC endpoint opened: /Users/ak/Library/Ethereum/geth.ipc
I0101 03:13:38.170815 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv2-IP1
I0101 03:13:58.117443 eth/downloader/downloader.go:326] Block synchronisation started
I0101 03:14:05.840805 core/blockchain.go:1047] imported 6 blocks,    40 txs (  2.822 Mg) in    5.292s ( 0.533 Mg/s). #1743903 [f87769a9… / 1713befb…]
I0101 03:14:14.260722 core/blockchain.go:1047] imported 25 blocks,   256 txs ( 23.026 Mg) in    8.338s ( 2.761 Mg/s). #1743928 [a3ece1b7… / 9a9424f7…]
I0101 03:14:22.493884 core/blockchain.go:1047] imported 31 blocks,   346 txs ( 29.800 Mg) in    8.233s ( 3.620 Mg/s). #1743959 [9a9424f7… / 8a1526ac…]
^CI0101 03:14:27.013045 cmd/utils/cmd.go:83] Got interrupt, shutting down...
I0101 03:14:27.013235 node/node.go:373] IPC endpoint closed: /Users/ak/Library/Ethereum/geth.ipc
I0101 03:14:27.506030 core/blockchain.go:592] Chain manager stopped
I0101 03:14:27.506412 eth/handler.go:230] Stopping ethereum protocol handler...
I0101 03:14:27.602160 eth/handler.go:251] Ethereum protocol handler stopped
I0101 03:14:27.602222 core/tx_pool.go:197] Transaction pool stopped
I0101 03:14:27.602243 eth/backend.go:521] Automatic pregeneration of ethash DAG OFF (ethash dir: /Users/ak/.ethash)
I0101 03:14:27.664351 eth/downloader/downloader.go:305] Synchronisation failed: block body download canceled (requested)
I0101 03:14:27.730508 ethdb/database.go:176] closed db:/Users/ak/Library/Ethereum/chaindata
~/.ethash > geth version
Geth
Version: 1.5.5-stable
Git Commit: ff07d54843ea7ed9997c420d216b4c007f9c80c3
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.4
OS: darwin
GOPATH=/Users/ak/Developer/Golang
GOROOT=/usr/local/Cellar/go/1.7.4_1/libexec
~/.ethash > 
````

**Comment by karalabe** [comment] 2017-01-03 07:42
Yeah, that's a spurious issue that rarely occurs during shutdown. It's mostly harmless, just scary and ugly. Would be nice to fix, alas noone found the time to work on it.

**Comment by fjl** [comment] 2017-01-10 11:36
dupe of #1816

**Closed by fjl** 2017-01-10 11:36 UTC
