### ISSUE TITLE
signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0xacc4fa

### ISSUE THREAD

**Issue by niklasf119** [ethereum/go-ethereum#23637] opened 2021-09-24 19:51 UTC
#### System information

Geth version: `1.10.8-stable`
OS & Version: `Ubuntu 20.04.3 LTS`

#### Expected behaviour
geth stays in sync and runs flawlessly

#### Actual behaviour
geth crashes

#### Steps to reproduce the behaviour
unclear as of now

#### Backtrace

I can not tell which of this information is relevant so here is the entire dump which is quite long
[geth-error.log](https://github.com/ethereum/go-ethereum/files/7228096/geth-error.log)

**Comment by holiman** [comment] 2021-09-24 20:34
Relevant part: 
```
INFO [09-23|19:06:34.900] Generating state snapshot                root=922523..f065b5 in=35b159..1bba9e at=473b0b..777d5f accounts=30,784,102 slots=129,531,186 storage=10.80GiB elapsed=8h35m41.710s eta=51h26m51.675s
INFO [09-23|19:06:42.885] Aborting state snapshot generation       root=922523..f065b5 in=35b159..1bba9e at=551848..ca8de8 accounts=30,784,102 slots=129,555,807 storage=10.81GiB elapsed=8h35m49.695s eta=51h27m39.472s
INFO [09-23|19:06:42.885] Resuming state snapshot generation       root=584485..18b3be in=35b159..1bba9e at=551848..ca8de8 accounts=30,784,102 slots=129,555,807 storage=10.81GiB elapsed=8h35m49.695s eta=51h27m39.472s
INFO [09-23|19:06:42.926] Imported new chain segment               blocks=1   txs=287     mgas=28.231  elapsed=250.606ms    mgasps=112.651 number=13,283,224 hash=23b05d..591a37 dirty=1023.90MiB
INFO [09-23|19:06:42.928] Unindexed transactions                   blocks=1   txs=206     tail=10,933,225 elapsed=2.173ms
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0xacc4fa]

goroutine 56906718 [running]:
runtime.throw(0x15866dd, 0x5)
	runtime/panic.go:1117 +0x72 fp=0xc06a0e3d58 sp=0xc06a0e3d28 pc=0x455d92
runtime.sigpanic()
	runtime/signal_unix.go:741 +0x268 fp=0xc06a0e3d90 sp=0xc06a0e3d58 pc=0x46d608
github.com/ethereum/go-ethereum/p2p.(*Peer).run(0x4000c0afc0f380, 0x12fa780, 0xc12be97480, 0x0)
	github.com/ethereum/go-ethereum/p2p/peer.go:272 +0x19a fp=0xc06a0e3eb8 sp=0xc06a0e3d90 pc=0xacc4fa
github.com/ethereum/go-ethereum/p2p.(*Server).runPeer(0xc000264280, 0xc0afc0f380)
	github.com/ethereum/go-ethereum/p2p/server.go:1039 +0x1de fp=0xc06a0e3fd0 sp=0xc06a0e3eb8 pc=0xad629e
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc06a0e3fd8 sp=0xc06a0e3fd0 pc=0x48ff81
created by github.com/ethereum/go-ethereum/p2p.(*Server).launchPeer
	github.com/ethereum/go-ethereum/p2p/server.go:1022 +0xc5

goroutine 1 [chan receive, 515 minutes]:
github.com/ethereum/go-ethereum/node.(*Node).Wait(...)
	github.com/ethereum/go-ethereum/node/node.go:420
main.geth(0xc00029e2c0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:321 +0x157
gopkg.in/urfave/cli%2ev1.HandleAction(0x134dd40, 0x166f248, 0xc00029e2c0, 0xc000034b40, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0005009c0, 0xc00011a150, 0x3, 0x3, 0x0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:260 +0x55
```

Seems to crash here: https://github.com/ethereum/go-ethereum/blob/v1.10.8/p2p/peer.go#L272 -- very odd place to crash. @fjl any thoughts?

**Comment by fjl** [comment] 2021-09-30 09:05
We cannot fix this crash because there is no way to debug it after-the-fact. The crash happens because SIGSEGV arrives to the process unexpectedly. This may be cause by memory issue, weird cgo memory corruption, or even a hardware issue. There is no way to know what the issue is from the stack trace.

@niklasf119 Please open another issue if you get more crashes like this. I will close this one for now because there is no way for us to act.

Please also consider running memtest.

**Closed by fjl** 2021-09-30 09:05 UTC
Labels: type:bug
