### ISSUE TITLE
Disclaimer of Liabilites [sic] and Warranties acceptance doesn't get persisted on geth account list

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#1512] opened 2015-07-23 14:18 UTC
```
$ geth --datadir="/tmp/embark" account list

=======================================
Disclaimer of Liabilites and Warranties
=======================================

THE USER EXPRESSLY KNOWS AND AGREES THAT THE USER IS USING THE ETHEREUM PLATFORM AT THE USER’S SOLE
RISK. THE USER REPRESENTS THAT THE USER HAS AN ADEQUATE UNDERSTANDING OF THE RISKS, USAGE AND
INTRICACIES OF CRYPTOGRAPHIC TOKENS AND BLOCKCHAIN-BASED OPEN SOURCE SOFTWARE, ETH PLATFORM AND ETH.
THE USER ACKNOWLEDGES AND AGREES THAT, TO THE FULLEST EXTENT PERMITTED BY ANY APPLICABLE LAW, THE
DISCLAIMERS OF LIABILITY CONTAINED HEREIN APPLY TO ANY AND ALL DAMAGES OR INJURY WHATSOEVER CAUSED
BY OR RELATED TO RISKS OF, USE OF, OR INABILITY TO USE, ETH OR THE ETHEREUM PLATFORM UNDER ANY CAUSE
OR ACTION WHATSOEVER OF ANY KIND IN ANY JURISDICTION, INCLUDING, WITHOUT LIMITATION, ACTIONS FOR
BREACH OF WARRANTY, BREACH OF CONTRACT OR TORT (INCLUDING NEGLIGENCE) AND THAT NEITHER STIFTUNG
ETHEREUM NOR ETHEREUM TEAM SHALL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY OR
CONSEQUENTIAL DAMAGES, INCLUDING FOR LOSS OF PROFITS, GOODWILL OR DATA. SOME JURISDICTIONS DO NOT
ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR CERTAIN
TYPES OF DAMAGES. THEREFORE, SOME OF THE ABOVE LIMITATIONS IN THIS SECTION MAY NOT APPLY TO A USER.
IN PARTICULAR, NOTHING IN THESE TERMS SHALL AFFECT THE STATUTORY RIGHTS OF ANY USER OR EXCLUDE
INJURY ARISING FROM ANY WILLFUL MISCONDUCT OR FRAUD OF STIFTUNG ETHEREUM.

Do you accept this agreement? [y/N] y

Fatal: Could not list accounts: no keys in store
```

next run of `geth account list` it shows the same disclaimer again. Expected is that this acceptance is persisted.

Bonus point for fixing the typo "Liabilites"

**Comment by iurimatias** [comment] 2015-07-23 14:19
suggestion: a flag to bypass this would be great something like --accept

**Comment by tgerring** [comment] 2015-07-23 14:22
The disclaimer is intended to only display when the data directory does not yet exist, as this will coincide with most instances of "first run".

**Comment by jorisbontje** [comment] 2015-07-23 14:34
workaround: `mkdir -p /tmp/embark/keystore` before the first run

**Comment by obscuren** [comment] 2015-07-23 14:36
Oh you cheeky bastards :)

**Comment by tgerring** [comment] 2015-07-23 14:40
Closing this issue, since intended behaviour is working as expected. Please open a new issue if https://github.com/ethereum/go-ethereum/issues/1512#issuecomment-124122509 is not valid.

**Closed by tgerring** 2015-07-23 14:40 UTC
