### ISSUE TITLE
Rinkeby faucet not work!

### ISSUE THREAD

**Issue by ph0ly** [ethereum/go-ethereum#22090] opened 2020-12-30 06:15 UTC
Rinkeby faucet not work again, could you please send 18.75 ETH to address  0x699DB98B976BC6B42c7E0F35f283f62656dC5A86  for the Rinkeby test net
Thank u very much!

**Comment by okuma10** [comment] 2020-12-30 13:34
I'm having the same issue for few days now.
I'm trying to get some ETH but the faucet keeps saying that there is no ETH address in the link. I tried with the twitter template from the faucet, as well as having only my ETH address in the tweet. Both gave error that there is no ETH address to send the test ETH to.

**Comment by dvdsm** [comment] 2021-01-01 12:44
Can't get any ETH from the Rinkeby Faucet. Can someone please send some to 0x965eE3C36a6C7D512142949351a2372FFB96221E
Thanks!

**Comment by ligi** [comment] 2021-01-02 23:35
@ph0ly @dvdsm you both have rinkeby eth now

**Comment by ligi** [comment] 2021-01-02 23:40
closing as duplicate of #22062

**Comment by DGKSK8LIFE** [comment] 2021-01-02 23:42
please do @ligi

**Closed** 2021-01-02 23:43 UTC
Labels: type:docs

**Comment by DGKSK8LIFE** [comment] 2021-01-03 00:01
thanks

**Comment by ph0ly** [comment] 2021-01-14 08:59
thanks!
