### ISSUE TITLE
issue unmarshaling single parameter events from abigen generated go code

### ISSUE THREAD

**Issue by dt665m** [ethereum/go-ethereum#16208] opened 2018-02-27 16:53 UTC
#### System information

Geth version: `1.8.x`
OS & Version: OSX
Commit hash : b574b5776695eb30e034fd8c7a468b3f03d4c6b9

#### Expected behaviour

abigen generated go code should be able to handle contract events defined with a single parameter

#### Actual behaviour

abigen generated go code fails to marshal event for events defined with a single parameter

#### Steps to reproduce the behaviour

https://gist.github.com/dt665m/dc3ab4347aa5340905ac84810ce52201

@karalabe, as we discussed on gitter, I created a simple contract to demonstrate the behavior I'm seeing.  I'm opening up the issue here to further discuss how best to approach a fix.  The issue is in the different reflection methods used to unpack multiple parameters vs single parameter events here https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/argument.go#L133.  function unpackTuple will iterate on Fields when interface == reflect.Struct while unpackAtomic doesn't expect a packaged struct.

Suggested fix would be to add some checks in unpackAtomic to get the correct field.  In the meantime, I've also added this specific test case to https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/bind_test.go#L571, which is what generated the gist linked above and could be bundled into a PR.  Cheers!

**Comment by karalabe** [comment] 2018-03-05 12:22
@jpeletier started working on this :)

**Comment by karalabe** [comment] 2018-03-05 12:30
Hmm, there's this PR open currently. https://github.com/ethereum/go-ethereum/pull/16107 

If it addresses the same issue, might make sense to combine that with the tests from this one.

**Comment by jpeletier** [comment] 2018-03-05 12:35
Looks like the tests are similar (add an event with just one argument). The PR looks good to me. My only question/concern is if `unpackAtomic()` should be aware of structs as as a destination (`v` parameter) or not.

**Comment by jpeletier** [comment] 2018-03-05 15:28
The above PR in my opinion does not fix the root cause: `unpackAtomic` does not accept struct lvalue. This PR #16256 attempts to fix the issue by adding this functionality to `unpackAtomic`

**Comment by dt665m** [comment] 2018-03-05 15:33
@jpeletier thats very similar to what I have on my side.  Cheers and thanks!

**Comment by jpeletier** [comment] 2019-03-06 17:10
@holiman This issue should be closed since the associated PR has been merged fixing it.

**Comment by holiman** [comment] 2019-03-06 18:11
thanks!

**Closed by holiman** 2019-03-06 18:11 UTC
