### ISSUE TITLE
Geth doesn't honor timeout parameter of debug_traceTransaction

### ISSUE THREAD

**Issue by Helios-vmg** [ethereum/go-ethereum#14506] opened 2017-05-24 01:18 UTC
#### System information

Geth version: `1.6.1`
OS & Version: Windows
Commit hash : v1.6.1

#### Expected behaviour
If a timeout value is provided to debug_traceTransaction, Geth should abort the trace and respond to the request immediately, so the client can take appropriate actions.

#### Actual behaviour
Geth appears to continue the trace to the end, and merely reports that the timeout has been exceeded. For example, if a timeout value of 1 second is provided, the trace may still take several minutes.

#### Steps to reproduce the behaviour
Do a PUT against geth with the following body:
```{"id":1,"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x7e97df329e38dcd4c89d0c215bf24588b2b7c0b58e69618138e96eea349a332d",{"disableStorage":true,"disableMemory":false,"disableStack":false,"fullStorage":false,"timeout":"1s","tracer":"{step:function(log){},result:function(){return{};}}"}]}```
Geth needs to have been started with --rpc --rpcaddr 0.0.0.0 --rpcapi "debug"

Warning: I believe 0x7e97df329e38dcd4c89d0c215bf24588b2b7c0b58e69618138e96eea349a332d is a DDoS transaction. This request may take several minutes to complete.

**Comment by karalabe** [comment] 2017-05-24 09:55
Thanks for reporting this!

**Comment by karalabe** [comment] 2017-05-24 09:56
Ah wait, I'm not sure you can pass `"1s"` as the timeout value. That should really blow up and not even be accepted as a valid argument. @Arachnid Any idea what the timeout parameter format is?

**Comment by Helios-vmg** [comment] 2017-05-24 14:32
The documentation claims it's a valid value:

https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_tracetransaction
> timeout: STRING. Overrides the default timeout of 5 seconds for JavaScript-based tracing calls. Valid values are described here.

https://golang.org/pkg/time/#ParseDuration

> A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

**Comment by OrdonTeam** [comment] 2018-06-15 10:43
Hi,
I were unable to reproduce this issue with geth 1.8. Timeout behaves as expected.

**Comment by holiman** [comment] 2019-03-05 10:25
Thanks for checking @OrdonTeam , closing

**Closed by holiman** 2019-03-05 10:25 UTC
