### ISSUE TITLE
Geth v.1.13.1 - BAD BLOCK - Invalid merkle root - Error when I make a transaction

### ISSUE THREAD

**Issue by Alessandro-Cavaliere** [ethereum/go-ethereum#28154] opened 2023-09-19 08:13 UTC
I'm running my own 3 node PoA private blockchain and trying to notarize on the blockchain some hashes. It worked fine before, but when I reached about 30 blocks this strange error started popping up that I had never seen before...

The even stranger thing is that the tx is processed by one block, but by the others it is put in pending and is no longer resolved. it's as if the blocks don't sync somehow.

Below I try to give as much information as possible:

**genesis.json**
```
{
  "config": {
    "chainId": 10001,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "berlinBlock": 0,
    "clique": {
      "period": 0,
      "epoch": 30000
    }
  },
  "difficulty": "1",
  "gasLimit": "8000000",
  "extradata": "0x0000000000000000000000000000000000000000000000000000000000000000C7157684459e99ba5046185e421ab51A96EDeD8D6f2f4eed9970E70F23f3e51B8511D8967d72ACE849A7e812AA2B459241a375f546D2434C7213A94c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "alloc": {
    "C7157684459e99ba5046185e421ab51A96EDeD8D": { "balance": "100000000000000000000" },
    "6f2f4eed9970E70F23f3e51B8511D8967d72ACE8": { "balance": "100000000000000000000" },
    "49A7e812AA2B459241a375f546D2434C7213A94c": { "balance": "100000000000000000000" }
  }
}
```

**node start command**
`geth --datadir node1 --networkid 10001 --allow-insecure-unlock --unlock $PUB_ADDR --http --port 30313 --http.addr $PRIVATE_IP_ADDR --http.port 8546 --http.corsdomain '*' --http.vhosts '*' --authrpc.port 8552 --http.api admin,eth,miner,net,txpool,personal,web3 --syncmode full --ipcdisable --mine --miner.etherbase $PUB_ADDR --preload $FILENAME_JS --password "psw.txt" console`

**JS file in preload**
```
admin.addPeer("enode://7e8175b0e31200c0f09b3141432b357981e5c15db2056b99a10f8fe11dc477ac0a7f2ac77b1e056df3ed8a31458a3d6fdd6daa80bdff09c0aa4905a55dd71538@<myip>:30313")

admin.addPeer("enode://e5ce2f1f5d377eb61201d81ceecd400642cd4db5e393bb3f488b4870f2472b73720d69443c28aaed6014480a476ca35d1319c82a0bc95ee9e35f6773181029d0@<myip>:30314")

admin.addPeer("enode://981ccfafb0edd3ec899b4f9f447c0f32a9956af1834c8dd91161fc8d5b5c4babd24e39d1feb8aa978219b8feb91e80116f2cb7be32defe1672faded630f3796b@<myip>:30315")

admin.addTrustedPeer("enode://7e8175b0e31200c0f09b3141432b357981e5c15db2056b99a10f8fe11dc477ac0a7f2ac77b1e056df3ed8a31458a3d6fdd6daa80bdff09c0aa4905a55dd71538@<myip>:30313")

admin.addTrustedPeer("enode://e5ce2f1f5d377eb61201d81ceecd400642cd4db5e393bb3f488b4870f2472b73720d69443c28aaed6014480a476ca35d1319c82a0bc95ee9e35f6773181029d0@<myip>:30314")

admin.addTrustedPeer("enode://981ccfafb0edd3ec899b4f9f447c0f32a9956af1834c8dd91161fc8d5b5c4babd24e39d1feb8aa978219b8feb91e80116f2cb7be32defe1672faded630f3796b@<myip>:30315")
```

**The Error**
```
########## BAD BLOCK #########
Block: 31 (0x6e8f0dc4ee61f8b69506a727d0689ead2709d03e546a8b8725979bf3581ee57e)
Error: invalid merkle root (remote: 202c0300a9f213a2cdcc46fede91dbdc1921c872bc46d9608a8d877b16df62ed local: a2f5f31b7e2b7f9e45fd45adb7740e9d549a49186942aeb97ae6f5d5e9f59b95) dberr: %!w(<nil>)
Platform: geth (devel) go1.21.1 amd64 linux
VCS: 3f40e65c-
Chain config: &params.ChainConfig{ChainID:10001, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:<nil>, BerlinBlock:0, LondonBlock:<nil>, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(nil), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(0xc000786250), IsDevMode:false}
Receipts:
  0: cumulative: 215222 gas: 215222 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x1596136cf33cfb487786ddc8cb26bb85d1c9e58eac9cab4234ef696d3c4b9c80 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:
##############################
```

Can anyone tell me how to resolve this error?

```[tasklist]
### Tasks
```

**Comment by holiman** [comment] 2023-09-19 08:31
Do you know which node mined the block? And what software version is that node using?

**Comment by Alessandro-Cavaliere** [comment] 2023-09-19 10:03
Yes, I know which block was mined and the software that this node uses is always version 1.13.1

**Comment by Alessandro-Cavaliere** [comment] 2023-09-19 15:15
@holiman ??

**Comment by Alessandro-Cavaliere** [comment] 2023-09-19 16:43
I print out the logs, here the outputs:

**Node 1 (the node that mined the block)**

```
> debug.standardTraceBlockToFile("0x4e4b6fc248906c0fc3b7231f5063b774a97ec22543cd270e72bec24bbecb3129")
INFO [09-19|16:36:59.171] Wrote standard trace                     file=/tmp/block_0x4e4b6fc2-0-0x7c7977f3-3227586541
["/tmp/block_0x4e4b6fc2-0-0x7c7977f3-3227586541"]
```

**Node 2 and Node 3 (the nodes where the bad block error came out)**

```
> debug.standardTraceBlockToFile("0x4e4b6fc248906c0fc3b7231f5063b774a97ec22543cd270e72bec24bbecb3129")
WARN [09-19|16:36:18.749] Served debug_standardTraceBlockToFile    reqid=18 duration="112.65µs"  err="block 0x4e4b6fc248906c0fc3b7231f5063b774a97ec22543cd270e72bec24bbecb3129 not found"
Error: block 0x4e4b6fc248906c0fc3b7231f5063b774a97ec22543cd270e72bec24bbecb3129 not found
        at web3.js:6365:9(39)
        at send (web3.js:5099:62(29))
        at <eval>:1:31(3)
```

** Node 1 Trace file**  (Other nodes do not generate the file)

[](https://gist.github.com/Alessandro-Cavaliere/979c9f0116dffdae870a9e133e531d97)

**Comment by holiman** [comment] 2023-09-19 17:05
The nodes require different commands (check what I wrote above).

**Comment by Alessandro-Cavaliere** [comment] 2023-09-19 17:44
Sorry,

Below is what I did wrong and the logs for the node that returned the error using the method `debug.standardTraceBadBlockToFile()`:
here the updated outputs:


**Node 2  (the node where the bad block error came out)**

[https://gist.github.com/Alessandro-Cavaliere/183f615fb0bee52e8249a1be84f19cb7](https://gist.github.com/Alessandro-Cavaliere/183f615fb0bee52e8249a1be84f19cb7)

**Comment by holiman** [comment] 2023-09-20 16:12
> How can I solve this problem with systemctl ?

systemctl is not the problem here. For sure, if you do not allow sufficient time during shutdown, then that may definitely be problematic, since a mere 30 blocks will not have flushed anything to disk. 

But it's very odd that a block which contains one transaction, identical trace both as `bad` and `regular`, and differing post-block stateroot.

**Comment by holiman** [comment] 2023-09-20 16:15
If you want to, you can upload the genesis and blocks somewhere, and I can take a closer look. The blocks can be exported with `geth export blocks.rlp.gz 0 31` iirc

**Comment by rjl493456442** [comment] 2023-09-21 05:44
Which state scheme are you using.

**Comment by holiman** [comment] 2023-09-21 07:31
> If you want to, you can upload the genesis and blocks somewhere

Actually, might be even simpler to upload the datadir for the node which _accepts_ the block. They should be fairly small. Note, however, that if the signing-keys or other keys in the keystore of the testnet are confidential, it is safer to just export the blocks.

**Comment by Alessandro-Cavaliere** [comment] 2023-09-21 07:55
[blocks.all.gz](https://github.com/ethereum/go-ethereum/files/12681796/blocks.all.gz)

I am using this command to export all blocks from node1: `geth export blocks.all.gz`. I think it's fine, let me know...

**Comment by holiman** [comment] 2023-09-21 08:59
```
$ geth --datadir /tmp/fooxbax init ./genesis.json; geth --datadir /tmp/fooxbax  import ./blocks.all.gz
...
invalid block 28: invalid merkle root (remote: c483e99bb2c3f0c881099ff0a1c985bf7b9826f8c5562656aa04a380549e0a6e local: 9ce45c7ab39ce7d9b58ff2bb71449652853ed6f192c2e59eb8f4df3e8f700a96) dberr: %!w(<nil>)

```
As far as I can tell, the node which generated this block (block 28) is corrupt. Perhaps you should do a disk-check and/or a RAM-check.

**Comment by Alessandro-Cavaliere** [comment] 2023-09-21 09:52
> Hm, this is what I get -- I don't even reach the same block
> 
> ```
> ########## BAD BLOCK #########
> Block: 28 (0xf21aeec5ec4982f0693f61048813f0829ead7eada38f61278a213a3fb18b4176)
> Error: invalid merkle root (remote: c483e99bb2c3f0c881099ff0a1c985bf7b9826f8c5562656aa04a380549e0a6e local: 9ce45c7ab39ce7d9b58ff2bb71449652853ed6f192c2e59eb8f4df3e8f700a96) dberr: %!w(<nil>)
> Platform: geth (devel) go1.20.1 amd64 linux
> VCS: c6454cd6-20230914
> Chain config: &params.ChainConfig{ChainID:10001, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:<nil>, BerlinBlock:0, LondonBlock:<nil>, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(nil), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(0xc000454500), IsDevMode:false}
> Receipts: 
>   0: cumulative: 260452 gas: 260452 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x83692ef807db25d0ae74bd32422334fa08233116232b3f2660462d32e190a325 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: 
> ##############################
> ```

Is very strange... I understand that block 28 is not corrupt. I also tried deleting all the nodes as I said and recreating the network, but nothing.

**Comment by holiman** [comment] 2023-09-21 10:01
Please try running those two commands, init+import, using a fresh temporary datadir, on all three machines. Let me know what they report.

**Comment by holiman** [comment] 2023-09-21 11:56
> I also tried deleting all the nodes as I said and recreating the network, but nothing.

Well, if you delete everything, you will produce new blocks. Perhaps that is why `28` was bad this time, not `31`. 
Just try this on all machines (assuming `/tmp/fooxbax` does not exist): 

```
geth --datadir /tmp/fooxbax init ./genesis.json; geth --datadir /tmp/fooxbax  import ./blocks.all.gz
```
They should all reject block `28`.

**Comment by Alessandro-Cavaliere** [comment] 2023-09-22 09:48
yes they all reject block 28..

**Comment by holiman** [comment] 2024-05-15 06:57
Closing, seems abandoned

**Closed by holiman** 2024-05-15 06:57 UTC
Labels: type:bug

**Comment by lichuang2015** [comment] 2024-12-29 04:47
Hi @holiman and @Alessandro-Cavaliere , could share what was the root cause and solutions?
