### ISSUE TITLE
Slowest Production Block (Execution Layer or Consensus Layer?)

### ISSUE THREAD

**Issue by avenbreaks** [ethereum/go-ethereum#28051] opened 2023-09-01 21:48 UTC
I have a small testnet but why is my blockchain producing blocks very slowly? ETH1 produces blocks in 12s but I feel this is very long.. is it like this? in CL and EL there are no errors or insufficient peers, everything is normal, I have 2 CL (Lighthouse) 2 VN (Lighthouse) 2 EL (Geth)

is there an error in my EL (Geth)?

config: 
```
nohup geth \
	  --http \
	  --http.port 8545 \
	  --http.api=eth,net,web3,admin,engine,txpool,debug,personal\
	  --http.addr=0.0.0.0 \
	  --http.vhosts=*\
	  --http.corsdomain=* \
	  --ws\
	  --ws.api=eth,net,web3,admin,engine,txpool,debug,personal \
	  --ws.port 8546 \
	  --ws.addr=0.0.0.0 \
	  --ws.origins=* \
	  --rpc.allow-unprotected-txs \
	  --rpc.batch-request-limit 1000 \
	  --rpc.batch-response-max-size 25000000 \
	  --txlookuplimit 0 \
	  --light.maxpeers 5\
	  --maxpeers 5 \
	  --bloomfilter.size 2048 \
	  --gcmode=archive\
	  --cache 1024 \
	  --crypto.kzg "gokzg" \
	  --pprof\
	  --pprof.addr "127.0.0.1" \
	  --pprof.port "6060" \
	  --networkid 1122 \
	  --datadir "/mnt/testnet/database/geth/1" \
	  --authrpc.port 8551 \
	  --authrpc.addr="localhost" \
	  --authrpc.vhosts="localhost" \
	  --authrpc.jwtsecret=/mnt/testnet/testnet/output/el/jwtsecret \
	  --port 30303\
	  --discovery.port 30303\
	  --verbosity 3 \
	  --syncmode full \
	  --log.rotate \
	  --log.compress \
	  --log.debug \
	  --log.maxsize 100 \
	  --log.maxage 5 \
	  --log.maxbackups 10 \
	  > /mnt/testnet/testnet/logs/geth-1.log &
```

![image](https://github.com/ethereum/go-ethereum/assets/93043826/dda8758e-95fd-4c3d-aa27-3149c13ef2cd)

**Comment by holiman** [comment] 2023-09-05 09:05
Geth stats working on a payload (because CL tells it to), and some time later, it stops, because the CL node fetches it (`reason=delivery`). 
In the screenshot,looks like `4` seconds. I think that is by design. Why do you think that is a problem?

**Comment by holiman** [comment] 2023-09-05 09:06
Closing this, because I'm fairly sure nothing is wrong here. Let's reopen in case I'm wrong

**Closed by holiman** 2023-09-05 09:06 UTC
Labels: type:docs
