### ISSUE TITLE
[BUG] geth contract cannot return types in state changing contract methods

### ISSUE THREAD

**Issue by SethVgr** [ethereum/go-ethereum#2882] opened 2016-08-01 14:46 UTC
# Checklist
- [done ] built geth 1.4.10
- [done ] installed it over previous version (1.3.5.) (`sudo cp geth /usr/bin/geth`)
- [done ] compiled  and deployed the following contract:

```
contract C {
    
     uint[] numbers;
     
     function initNumbers() {
         numbers.push(1);
         numbers.push(2);
     }
     
     function stateChanger(uint a) returns (bool) {
         for(uint i = 0; i < numbers.length; i++) {
             if(numbers[i] == a)
             return false;
         }
         numbers.push(a);
         return true;
     }
     
     function getNumber(uint index) constant returns (uint) {
         if(index >= numbers.length)
            return 0;
         else
            return numbers[index];
     }
}
```
The contract was compiled using [browser solidity](https://ethereum.github.io/browser-solidity/#version=soljson-latest.js) and deployed on a private test net running a single **geth** node of version 1.4.10

## System/environment

- OS: debian 8.3 Jessie x64, kernel version 3.16.0-4-amd64, virtual machine, running on VirtualBox, host machine Win7 x64, NAT network settings used

## Expected behaviour

After deployment, upon calling method **stateChanger()** a true or false value should be returned after each call.

## Observed behaviour

Instead of the expected boolean values the transaction hash is returned:

```
> c.initNumbers({from:web3.eth.accounts[0],gas:4000000000});
"0xdf82b0204b2c5151ce909d63a3d68314a0c8e4d7204ee5b52c5753212943c020"
> c.stateChanger(3, {from:web3.eth.accounts[0],gas:4000000000});
"0x714e13b11c41144036334b38b144d81f05c7b9e8d22703153e0de6b6a3a9ec45"
> c.stateChanger(4, {from:web3.eth.accounts[0],gas:4000000000});
"0x4f2fa772a7bfd39f419e001e73827f95f21034618febc44f99731bd353f493e7"
> c.stateChanger(5, {from:web3.eth.accounts[0],gas:4000000000});
"0xf28bff66ce439c4f05eea1629131750efaba4e115ea30b610f1404dde9c94fed"
> c.getNumber(0);
1
> c.getNumber(1);
2
> c.getNumber(2);
3
> c.getNumber(3);
4
> c.stateChanger(2, {from:web3.eth.accounts[0],gas:4000000000});
"0x68e3c169b2a063764888a42da92dd0bdd3aaa3dd70f25be089a1c4811d416d59"

```

For the first calls of **stateChanger()** true should have been returned while on the last call false.

**Comment by bas-vk** [comment] 2016-08-04 09:15
`getNumber` is marked as constant. Therefore it cannot change the state and sending a transaction to it doesn't make sense. If you load the ABI into web3 (I assume you did in you example) and execute a constant function web3 will send a `eth_call` to the node and the node will send the results back. In this case an uint256.

The other functions are not marked as constant. If you execute one of these function web3 sends a transaction. Therefore you will receive a transaction hash. Since it outcome of the function cannot be known until it is mined you don't get a result back.

**Comment by SethVgr** [comment] 2016-08-05 13:44
Thanks. I did manage to get passed the transaction/call issue.

**Comment by fjl** [comment] 2016-08-05 18:25
I'm closing this because it is working as intended. The return value of the top level call of a transaction is always discarded. Note that you can call stateChanger from another contract in a transaction and use the return value.

**Closed by fjl** 2016-08-05 18:25 UTC
