### ISSUE TITLE
contract is sent and gets an address, but eth.getCode returns 0x

### ISSUE THREAD

**Issue by kobigurk** [ethereum/go-ethereum#842] opened 2015-04-30 20:40 UTC
I'm trying to deploy the following contract on the testnet :
contract metaCoin {	
	mapping (address => uint) balances;
	function metaCoin() {
		balances[msg.sender] = 10000;
	}
	function sendCoin(address receiver, uint amount) returns(bool sufficient) {
		if (balances[msg.sender] < amount) return false;
		balances[msg.sender] -= amount;
		balances[receiver] += amount;
		return true;
	}
}

compiling it with both https://chriseth.github.io/cpp-ethereum/ and solc yields same bytecode.

I'll describe a particular instance:
1. I send the transaction, and get an address - 0x59115f7ac4cfdaf06f5351439065d51be8341f48
2. I then wait for the next blocks to appear (this one was either on 212238 or 212239).
3. I try eth.getCode('0x59115f7ac4cfdaf06f5351439065d51be8341f48') - and get '0x'.
4. also, trying to get the balance returns 0 - evidence the contract didn't actually run.
5. also, weird - these long lines show there are 2 transactions on 212238
I0430 23:36:44.813656   10256 chain_manager.go:613] imported 1 block(s) 0 queued in 3.730538ms. #212237 [bab0c4c1 / bab0c4c1]
I0430 23:36:44.826512   10256 worker.go:324] commit new work on block 212238 with 2 txs & 0 uncles
I0430 23:36:54.887148   10256 chain_manager.go:613] imported 1 block(s) 0 queued in 4.593829ms. #212238 [b31d9c9b / b31d9c9b]
I0430 23:36:54.899101   10256 worker.go:324] commit new work on block 212239 with 2 txs & 0 uncles

but this is the output of getBlock :
> eth.getBlock(212238)
{
  stateRoot: '0x283b9b92e259d3decbba6592eed8af45b3c0aaa6040ce9ef56c1ceed447a9c20',
  gasUsed: 0,
  nonce: '0x0b0c5f5d8142569e',
  difficulty: '10866176',
  size: 514,
  timestamp: 1430426198,
  uncles: [ ],
  number: 212238,
  hash: '0xb31d9c9b5c7da65b441086abf0b5dc2ed236867b6e8a3cba06b037055143c592',
  sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  miner: '0x7e7e8d8dea43ebf4887b91752e43c7588733b6b7',
  totalDifficulty: '1993356855536',
  transactions: [ ],
  parentHash: '0xbab0c4c153743edccfd6a7044ee4645683bd8b42933aea5f2ceabf7c54c15b5f',
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  extraData: '0x',
  gasLimit: 3141592
}
> eth.getBlock(212239)
{
  gasUsed: 115738,
  hash: '0xbace7bc59f8d7c3834c1ccb41c98f74a73aa0502d68402b5663c81eda26eef18',
  nonce: '0x185b5f1a549326cc',
  difficulty: '10860871',
  gasLimit: 3141592,
  totalDifficulty: '1993367716407',
  extraData: '0x',
  transactions: ['0x1df94a6d9b1f136c2c2425743c817c8ad0efd3e9f8f7cabfbf2dc77e68b63dc8', '0x080b308e672464ba1e91e416d0df93ec64ef576051c1e151daf6608d77419d4c' ],
  number: 212239,
  parentHash: '0xb31d9c9b5c7da65b441086abf0b5dc2ed236867b6e8a3cba06b037055143c592',
  sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  transactionsRoot: '0x98389fdae7c326f1298c6d50d2c9808cd7a4b91be55558ff50bcb8a48e5ae0b0',
  stateRoot: '0xf67566d6deb6978fb9235474bd04250ae833cbb401d5bdeacc00b573e934f3a0',
  miner: '0xcb26a56f091fe7a442b0b5cbfbd8975779629e83',
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  size: 1424,
  timestamp: 1430426217,
  uncles: [ ]
}
>

**Comment by kobigurk** [comment] 2015-04-30 20:47
OK, this is the transaction itself :
> eth.getTransaction('0x1df94a6d9b1f136c2c2425743c817c8ad0efd3e9f8f7cabfbf2dc77e68b63dc8')
{
  blockNumber: 212239,
  value: '0',
  gasPrice: '10000000000000',
  input: '0x73ffffffffffffffffffffffffffffffffffffffff33166000908152602081905260408120612710905560bb908190603790396000f3007c0100000000000000000000000000000000000000000000000000000000600035046390b98a118114602d57005b73ffffffffffffffffffffffffffffffffffffffff331660009081526020819052604081205460a79160043591602435919082901060b1575b5073ffffffffffffffffffffffffffffffffffffffff33811660009081526020819052604080822080548590039055918416815220805482019055600160b5565b8060005260206000f35b5060005b9291505056',
  hash: '0x1df94a6d9b1f136c2c2425743c817c8ad0efd3e9f8f7cabfbf2dc77e68b63dc8',
  nonce: 4,
  blockHash: '0xbace7bc59f8d7c3834c1ccb41c98f74a73aa0502d68402b5663c81eda26eef18',
  transactionIndex: 0,
  from: '0x1928199a03da24f3a8a3b3f231e082a9567eb842',
  to: Error: ,
  gas: 90000
}

**Comment by kobigurk** [comment] 2015-04-30 20:55
Also, it happens only on some contracts and not others.

**Comment by zelig** [comment] 2015-05-01 08:33
Hah, getting an address actually doesn't mean your contract is created.
In fact that you get 0 for code proves that it wasn't. 
The two transactions are then obviously failing.
Make sure your contract creation tx is picked up and is sufficiently funded.


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by kobigurk** [comment] 2015-05-01 09:20
thanks @zelig , I'm a clown.
it was a not enough gas issue!

**Comment by obscuren** [comment] 2015-05-01 14:03
Is this, or is this not an issue?

**Comment by kobigurk** [comment] 2015-05-01 14:44
the issue now is boiled down to - how to understand that the error was "Gas not enough".
in the transaction itself, the error field existed but was empty.

**Comment by obscuren** [comment] 2015-05-21 10:08
I'm closing this issue since `sendTransaction` is going to stop returning addresses.

**Closed by obscuren** 2015-05-21 10:08 UTC

**Comment by alexvandesande** [comment] 2015-08-07 17:18
@kobigurk use eth.getTransactionReceipt(txHash) to get the result and see how much gas was spent. Testing on a private net the greeter cost 221184 gas to deploy, so it should be enough to deploy it now. But you should really test on private networks, so you don't need to spend real ether for learning.

**Comment by gaetanocaruana** [comment] 2016-02-07 11:02
this was very very helpful. Thank you.

The problem is that most devs will be using solidity browser and they face this issue again and again until there is a very easy way that will allow you to send more gas through it

**Comment by jacobvincent** [comment] 2017-05-24 06:55
Hi **Kobi**,

Have you found a solution for this problem? As you have mentioned in one of your comments that, it boils down to shortage of gas. where did you increase your gas amount?
I do get a gas estimate for the transaction, however, it does not complete my contract address creation with the gas which was estimated by **web3.eth.estimateGas**.
As you have mentioned in the steps above, I also get a contract address, but the **getCode()** returns "0x"(Ideally it should return the bytecode file which i had supplied for the contract address creation) when I pass the transaction hash from the transaction receipt.

I tried increasing the gas limit in the solidity browser and created the contract. The contract does get created, however, the functions in the code does not return any value (i.e. it is not writing any data to the block). I assume, this again comes down to the insufficient gas problem. The question is, how/where do i increase the gas? Why isnt my gasEstimate giving a proper estimate sufficient enough to execute the contract?

Would appreciate your advise.

Thanks,
Jacob

**Comment by Bobavince** [comment] 2018-10-19 13:34
Don't know if it can help out, but I had the same issue and in my wrapped compiled solidity script, it was : 

    private static final String BINARY = "[{\"constant\":true,\"inputs\":[],\"name\":\"chars\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}, ( ... )se,\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"}]";

instead of : 

    private static final String BINARY = "608060405234801561001057600080fd5b5060008054600160a060020a0319163317815560015561027f806100356000 (...) ffffffffffffffffffff163314156102515760005473ffffffffffffffffffffffffffffffffffffffff16ff5b5600a165627a7a72305820545e60010ee0d4b8f1315f9743499c370f058e1ab280aab90d9795cd074ff9e60029";

Which means, that web3j or solidity compiler does not correctly do its job. 
Personal issue, but it was not obvious.
