### ISSUE TITLE
golang ethclient recieve gzip response

### ISSUE THREAD

**Issue by 0127abcd** [ethereum/go-ethereum#26337] opened 2022-12-09 04:11 UTC
I used ethclient(https) to call BlockNumber and more interface, but i found the Accept-Encoding  header of https request always was gzip, it cause a error, how should i config it?

**Comment by 0127abcd** [comment] 2022-12-09 04:20
code:
	httpClient, err := ethclient.Dial("https://xxxx.xxx.xx")
	if err != nil {
		logger.LOG.Error("connect eth http node error", zap.Error(err))
		return
	}

	block, err := httpClient.BlockByNumber(context.Background(), big.NewInt(int64(Height)))
	if err != nil {
		logger.LOG.Error("get BlockByNumber err", zap.Error(err))
		return
	}

**Comment by s1na** [comment] 2022-12-09 12:08
I can reproduce this if I explicitly set `Accept-Encoding: gzip`, i.e.:

```go
     cl, err := rpc.DialContext(ctx, path)
     if err != nil {
         fmt.Errorf("err: %v\n", err)
         return
     }
     cl.SetHeader("Accept-Encoding", "gzip")
     ecl := ethclient.NewClient(cl)
     num, err := ecl.BlockNumber(context.Background())
```

Interestingly if I don't set the header, the request will look exactly the same over the wire, but somehow there is no error. 

The gzip write was modified in #25457 but this issue doesn't seem to stem from there. It seems to have existed before.

**Comment by s1na** [comment] 2022-12-09 12:24
> https request always was gzip, it cause a error, how should i config it?

BTW to configure the headers you can use my example from above and change this line:

```go
    cl.SetHeader("Accept-Encoding", "identity")
```

**Comment by 0127abcd** [comment] 2022-12-09 12:29
> > https request always was gzip, it cause a error, how should i config it?
> 
> BTW to configure the headers you can use my example from above and change this line:
> 
> ```go
>     cl.SetHeader("Accept-Encoding", "identity")
> ```

Thanks for your help, that's useful！

**Comment by s1na** [comment] 2022-12-09 12:53
I read somewhere that if we manually set `Accept-Encoding: gzip` the go http client won't decompress the result automatically. That explains why my example returns an error.

I still don't understand the cause of error for you. Can you explain how is the RPC server setup? geth doesn't support HTTPS API so it seems you have a custom setup.

**Comment by 0127abcd** [comment] 2022-12-12 03:12
> 
I use geth's ethclient but it doesn't set any headers. But by capturing the network packets, I found that it automatically adds the header `Accept-Encoding: gzip` to the client request. As you said, I use  Amazon Managed Blockchain as my RPC server.

**Comment by holiman** [comment] 2022-12-19 15:04
> this was i recieved : H4sIAAAAAAAA/6pWyirOzysqSFayUjLSM1DSUcpMUbIy1FEqSi0uzSlRslIyqEgzM7W0MFWq5QIEAAD//zIR804tAAAA


I'm not convinced it has anything to do with `gzip`, what you have there is base64-encoded data. I think the problem might be with that remote server, rather than the client? 

@s1na when you reproed the problem, did your data also look like base64 data?

**Comment by holiman** [comment] 2022-12-20 09:49
`invalid character '\x1f' looking for beginning of value` means you are actually getting some binary data, namely the character `1F`. The `gzip` header starts with `1f 8b`, so you are definitely seeing gzip. 

However, the original reporter @0127abcd is not having gzip problems, but rather problems with base64. (Which, incidentally, is how golang by default would encode a `[]byte` response over rpc. )

**Comment by holiman** [comment] 2022-12-20 10:34
> I read somewhere that if we manually set Accept-Encoding: gzip the go http client won't decompress the result automatically. That explains why my example returns an error.

That makes sense, and yes, it fully explains the behaviour @s1na is seeing. With that, I think we can close this, because the original error does not seem to be an error in the go-ethereum codebase.

**Closed by holiman** 2022-12-20 10:34 UTC
Labels: type:docs
