### ISSUE TITLE
Very slow syncing on Hard Drive

### ISSUE THREAD

**Issue by SleepingShell** [ethereum/go-ethereum#14895] opened 2017-08-04 01:49 UTC
#### System information

Geth version: `Geth/v1.6.7-stable-ab5646c5/linux-amd64/go1.8.1`
OS & Version: Linux (Debian)

#### Expected behaviour
Sync the most recent 30,000 blocks at a rate of at least 1 block a second.

#### Actual behaviour
I used to sync the ethereum blockchain on an SSD. The syncing would always be fine and I would be able to catch up after being offline for a few days within 20-30 minutes. However, my SSD no longer has room. So I set up a symlink from the ~/.ethereum/chaindata folder to /blockchain/ethereum/chaindata, which is a separate HDD mounted at /blockchain. I copied the chaindata folder to that location, and geth/Mist recognize the blocks there. However, now when I sync, it syncs VERY slowly. Due to security reasons, I do not want to move the whole datadir to the HDD. 

I have also tried running the geth client with --cache=1024, 2048, 4096. None of these options help. I recognize that ethereum can be intense with its read/writes, however I don't see why it should be this slow to sync blocks. I am connected to plenty of peers so I am unsure why this is happening.

I have done the same process with Bitcoin and it works completely fine. I do NOT want to use a different mode of syncing, as I would like to host the whole history of the chain, I don't believe that should have to be a workaround.

#### Steps to reproduce the behaviour
Setup a symlink from the ~/.ethereum/chaindata folder to a separate HDD.

#### Backtrace

````
[backtrace]
````

![image](https://user-images.githubusercontent.com/9204264/28950879-5589e3dc-7895-11e7-9d47-bf725cb85909.png)

**Comment by AlisaHevic** [comment] 2017-08-04 17:31
Windows 7 pro, 100% disk usage, but only 10 Mb/s read-write (my hdd can 180 Mb/s). System is very, very slow. It is impossible to use browser or play games when geth is syncing ... ![geth1 6 6 hdd](https://user-images.githubusercontent.com/30731697/28979213-a48a2d22-7951-11e7-8060-0d433f029e7a.png)

**Comment by nathanph** [comment] 2017-08-06 04:08
Having this exact same issue. And when I eventually get close to finishing syncing it won't sync the last 200-600 blocks.

**Comment by w0nnapl4y** [comment] 2017-08-11 16:03
Commenting here, because I came to search for a solution for this exact phenomenon.

**Comment by jlippuner** [comment] 2017-08-23 03:17
I'm experiencing the same problem. I used to have the blockchain on my SSD but it became too big. So I moved it to a HDD (moved the geth dir inside ~/.ethereum to HDD and made a symlink) and now the block sync is extremely slow. I'm using geth version `1.6.5-stable-cf87713d`.

**Comment by bblboy54** [comment] 2017-08-23 14:06
Very similar scenario for me except that I did the symlinking to an HDD long before having serious issues.  What really did me in was I went on vacation the first full week of August and my laptop sat in it's bag... when I returned I was expecting a lot of syncing being needed but it NEVER catches up...  This weekend was a long weekend for me so I figured it would be the solution because I was able to start the sync on Friday afternoon and let it run clear until this morning.... last night I was still extremely far behind and blocks are being generated faster than my node is syncing them.  What is really perplexing to me is that geth is only using around 10% CPU on average but my HDD is pegged.....    I did some experimenting with cache sizes last night and I've found that if I use a higher cache size like 2048 the process never wants to quit even if I tell it to shutdown.....

I'm using the ethereum wallet package for 64bit linux (installed from deb) with the latest version and I'm using the geth that is packaged with it which is 1.6.6-stable-10a45cb5 and the system is running Ubuntu 16.04.3 LTS with an i7-4760HQ CPU and 8GB of RAM.

Again, I moved everything over to my HDD and added the symlink probably a month before I went on vacation and I didn't have any issues if I left ethereum closed for a few days and opened it up -- it always seemed to catch up within an hour or so but after I returned from vacation on August 13th it's been a nightmare....  This weekend it was running for more than 3 days straight without interruption and it came nowhere close to catching up.

This HDD access thing is of the biggest concern.... why is it pegging my HDD while not really using much CPU and even less bandwidth....  And a valid solution isn't going to be move it to an SSD because it was working on the HDD acceptably before and after seeing how much drive activity is going on I wouldn't want that much wear on a SSD.

**Comment by AlisaHevic** [comment] 2017-08-26 07:32
So, SSD is response for this problem?

**Comment by lyricalpolymath** [comment] 2017-08-27 20:53
what is an average time for each group of blocks that you see in the logs?
Is it taking minutes or just seconds?

**Comment by DimaLg** [comment] 2017-08-28 11:27
On my system (windows 7, intel core i5, 8 Gb ram, WD green 1 Tb) ~ 20 seconds per chain segment. In chain segment usually 1-2 blocks.

**Comment by bblboy54** [comment] 2017-08-28 16:03
It varies quite a bit.... I'd say the average is about 30-40 seconds per block....  occasionally I see some come in around 10 seconds but I also see some come in at 1-2mins

**Comment by maxgillett** [comment] 2017-09-12 17:52
I have the same issue. Ubuntu 16.04 with WD 2TB drive. Copied my synced chaindata to an external drive, and now it's impossible to catch up to the latest block.

**Comment by bassmaster187** [comment] 2017-09-13 19:27
same problem here.

**Comment by EchebKeso** [comment] 2017-11-10 20:04
Another +1, I moved from an SSD to a decent speed HDD (a write rate of 120MB/s as opposed to 400MB/s on the SSD) - and now it can't ever catch up after missing just one day! It takes longer than 10 seconds per block right now on average (per "Imported new chain segment x 1").

**Comment by fridaynext** [comment] 2017-11-19 14:41
Same here - flawless performance on my 2014 MacBook Pro 512GB SSD, but only downloads about 1% per day on my WD 5TB MyBook external USB3 drive. Blockchain is too big for my SSD, but I can't reliably use the wallet when the blockchain won't ever sync.

**Comment by dangero** [comment] 2017-12-12 21:49
Things that affected the performance:
-External HD partition format
-Geth Cache Size
It appears this performance issue is caused by Geth's interaction with the Leveldb chaindata files.

**Comment by ddeputy1** [comment] 2017-12-13 15:43
Is having the DAG and the chain data on different drives, as I do, causing this issue?  Anybody have other ideas or resolution?

**Comment by DavidCWebs** [comment] 2017-12-13 22:08
Another + 1 here. Ubuntu 16.04 running geth 1.7.3-stable. I switched from an SSD to a (new) HDD when chaindata started getting too large. Symlinked to chaindata on the HDD from the default `~/.ethereum/geth` directory on the SSD. Looks like it isn't going to catch up to the latest block.

**Comment by gasan050** [comment] 2017-12-15 10:02
+ same here, Ubuntu, symlinks to HDD, and the sync is extremely slow!

**Comment by dangero** [comment] 2017-12-18 18:43
I just setup an external USB SSD to compare, and this solved the issue. Syncing is roughly 30 times faster after switching to an SSD hard drive.

**Comment by jgostylo** [comment] 2018-01-03 23:09
Yes, any type of answer at all would be nice.  Even if it is to say that we are kind of screwed at the moment but here are some solutions...  One might be the ability to span the blockchain across drives.  This seems doable since the chaindata files are already separated.  Then you could operate the latest blocks on a small portion of your SSD and relegate the majority of the chain to a large HDD.

Blockchain size is up to 420GB.  That is not very palatable getting a single SSD that will last to the end of the year.

**Comment by jtktam** [comment] 2018-01-28 02:17
I went from a 256gb drive to a 512gb in a last month and it's filling up quickly.. i wonder if the older files can be moved to "cold" hdd and/or symbolic link back to the main chaindata?

**Comment by dslip** [comment] 2018-02-07 22:51
+1 here

**Comment by holiman** [comment] 2018-02-08 08:44
As of earlier this week, we merged https://github.com/ethereum/go-ethereum/pull/15857. This should considerably improve the syncing experience. Some notes: 

* It fixes some bugs in the p2p/networking, which previously caused peer churn and caused sync to stop. 
* It does in-memory pruning of state, and considerably lessens the state-growth after fast-sync has completed. 

We're hoping that this will resolve _most_ issues with sync, but users with HDD instead of SSD may still experience problems. I'll close this ticket, since it's becoming rather old -- originally reported on `Geth/v1.6.7-stable-ab5646c5/linux-amd64/go1.8.1`. For sync problems with latest master(not yet released), please open a new ticket.

**Closed by holiman** 2018-02-08 08:44 UTC

**Comment by lostmsu** [comment] 2018-07-03 05:52
As of today, this issue does not seem to be solved yet. Block download rate is in 20-40 second interval.

**Comment by wupeaking** [comment] 2018-08-16 10:00
+1 here

**Comment by wupeaking** [comment] 2018-08-16 11:17
+1 here

**Comment by stelloxx** [comment] 2018-08-21 05:51
What is the "knownStates" value for those experiencing sync issues on this thread? I am on 197,323,466 after about 7 days of fastsync with geth (rig: quad 3.4 Xeon, 16GB RAM, HDD on Ubuntu latest)

**Comment by krismasIsUnreal** [comment] 2021-08-13 18:15
Same problem. New Toshiba 8 Tb
