### ISSUE TITLE
geth not getting more blocks

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1270] opened 2015-06-15 20:39 UTC
Geth
Version: 0.9.31
Git Commit: dfd18d245af37344f8e6fadca55f22a639d7f1ba
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2

Geth is stuck at block 0x9458f
(The behavior is looking like cpp issue https://github.com/ethereum/cpp-ethereum/issues/2162)

```
I0615 13:32:31.592606   14770 downloader.go:212] Synchronisation already in progress
I0615 13:32:32.084291   14770 api.go:38] eth_blockNumber []
I0615 13:32:32.084334   14770 http.go:149] Generated response: *rpc.RpcSuccessResponse &{%!s(float64=1) 2.0 0x9458f}
I0615 13:32:32.084363   14770 http.go:160] Sending payload: {
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x9458f"
}
I0615 13:32:32.454594   14770 sync.go:136] Scheduling 1 hash announcements from 654b2c5c931fe8fc
I0615 13:32:32.830661   14770 api.go:38] eth_blockNumber []
I0615 13:32:32.830703   14770 http.go:149] Generated response: *rpc.RpcSuccessResponse &{%!s(float64=1) 2.0 0x9458f}
I0615 13:32:32.830735   14770 http.go:160] Sending payload: {
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x9458f"
}
I0615 13:32:32.985990   14770 sync.go:173] Explicitly fetching 1 blocks from 654b2c5c931fe8fc
I0615 13:32:33.057658   14770 downloader.go:536] Peer 654b2c5c931fe8fc [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:33.472518   14770 api.go:38] eth_blockNumber []
I0615 13:32:33.472628   14770 http.go:149] Generated response: *rpc.RpcSuccessResponse &{%!s(float64=1) 2.0 0x9458f}
I0615 13:32:33.472702   14770 http.go:160] Sending payload: {
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x9458f"
}
I0615 13:32:34.212740   14770 api.go:38] eth_blockNumber []
I0615 13:32:34.212813   14770 http.go:149] Generated response: *rpc.RpcSuccessResponse &{%!s(float64=1) 2.0 0x9458f}
I0615 13:32:34.212869   14770 http.go:160] Sending payload: {
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x9458f"
}
I0615 13:32:34.364115   14770 sync.go:136] Scheduling 1 hash announcements from 654b2c5c931fe8fc
I0615 13:32:34.366365   14770 sync.go:136] Scheduling 1 hash announcements from 654b2c5c931fe8fc
I0615 13:32:34.427766   14770 sync.go:136] Scheduling 1 hash announcements from 654b2c5c931fe8fc
I0615 13:32:34.790092   14770 sync.go:136] Scheduling 1 hash announcements from 654b2c5c931fe8fc
I0615 13:32:34.885986   14770 sync.go:173] Explicitly fetching 2 blocks from 654b2c5c931fe8fc
I0615 13:32:34.986026   14770 sync.go:173] Explicitly fetching 1 blocks from 654b2c5c931fe8fc
I0615 13:32:35.385886   14770 downloader.go:205] Attempting synchronisation: 5e8737cbfccfa52c, 0x2fa495817d189934f2c7a0111f3f30d338d4a9e7d926135ae442e297febee467
I0615 13:32:35.385945   14770 downloader.go:212] Synchronisation already in progress
I0615 13:32:35.386004   14770 sync.go:173] Explicitly fetching 1 blocks from 654b2c5c931fe8fc
I0615 13:32:35.593248   14770 downloader.go:536] Peer 654b2c5c931fe8fc [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:35.885939   14770 downloader.go:536] Peer 654b2c5c931fe8fc [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:36.090760   14770 downloader.go:536] Peer 654b2c5c931fe8fc [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:36.757702   14770 api.go:38] eth_blockNumber []
I0615 13:32:36.757753   14770 http.go:149] Generated response: *rpc.RpcSuccessResponse &{%!s(float64=1) 2.0 0x9458f}
I0615 13:32:36.757784   14770 http.go:160] Sending payload: {
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x9458f"
}
I0615 13:32:36.915866   14770 sync.go:136] Scheduling 1 hash announcements from 654b2c5c931fe8fc
I0615 13:32:37.486454   14770 sync.go:173] Explicitly fetching 1 blocks from 654b2c5c931fe8fc
I0615 13:32:37.497501   14770 api.go:38] eth_blockNumber []
I0615 13:32:37.497558   14770 http.go:149] Generated response: *rpc.RpcSuccessResponse &{%!s(float64=1) 2.0 0x9458f}
I0615 13:32:37.497600   14770 http.go:160] Sending payload: {
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x9458f"
}
I0615 13:32:37.839401   14770 downloader.go:536] Peer 654b2c5c931fe8fc [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:38.116047   14770 api.go:38] eth_blockNumber []
I0615 13:32:38.116087   14770 http.go:149] Generated response: *rpc.RpcSuccessResponse &{%!s(float64=1) 2.0 0x9458f}
I0615 13:32:38.116115   14770 http.go:160] Sending payload: {
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x9458f"
}
I0615 13:32:38.842798   14770 api.go:38] eth_blockNumber []
I0615 13:32:38.842859   14770 http.go:149] Generated response: *rpc.RpcSuccessResponse &{%!s(float64=1) 2.0 0x9458f}
I0615 13:32:38.842902   14770 http.go:160] Sending payload: {
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x9458f"
}
I0615 13:32:40.286389   14770 sync.go:136] Scheduling 1 hash announcements from 326bf5f061fb5f75
I0615 13:32:40.886064   14770 sync.go:173] Explicitly fetching 1 blocks from 326bf5f061fb5f75
I0615 13:32:41.374806   14770 downloader.go:536] Peer 326bf5f061fb5f75 [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:42.094033   14770 sync.go:136] Scheduling 1 hash announcements from 5e8737cbfccfa52c
I0615 13:32:42.685973   14770 sync.go:173] Explicitly fetching 1 blocks from 5e8737cbfccfa52c
I0615 13:32:42.777737   14770 downloader.go:536] Peer 5e8737cbfccfa52c [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:44.171139   14770 sync.go:136] Scheduling 1 hash announcements from f86a89edaa6d21ea
I0615 13:32:44.685929   14770 sync.go:173] Explicitly fetching 1 blocks from f86a89edaa6d21ea
I0615 13:32:44.860005   14770 downloader.go:536] Peer f86a89edaa6d21ea [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:45.385943   14770 downloader.go:205] Attempting synchronisation: 5e8737cbfccfa52c, 0x4f3609e20a14a972b97a7af082d025365247bc9e98e114c26678e3e0f786477b
I0615 13:32:45.386072   14770 downloader.go:212] Synchronisation already in progress
I0615 13:32:46.213900   14770 downloader.go:194] Unregistering peer 2b02981cd4cb2a06
I0615 13:32:48.082786   14770 sync.go:136] Scheduling 1 hash announcements from 326bf5f061fb5f75
I0615 13:32:48.585983   14770 sync.go:173] Explicitly fetching 1 blocks from 326bf5f061fb5f75
I0615 13:32:48.751253   14770 downloader.go:536] Peer 326bf5f061fb5f75 [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:50.081618   14770 transaction_pool.go:215] (t) 3965656638626133 => 00fc5725 (0x6a9b50) 4e9fc9bfba6274acbd22b80bd489e7a4f559fc2d3b9898f344638956cbba628c
I0615 13:32:50.089493   14770 transaction_pool.go:266] tx 4e9fc9bf
I0615 13:32:50.586582   14770 transaction_pool.go:215] (t) 3937306634663965 => 00fc5725 (0x6a9b50) da2605956225734bcfb556cb9632c55021840757c581c3cbae519080ab0f549f
I0615 13:32:50.596755   14770 transaction_pool.go:266] tx da260595
I0615 13:32:50.648667   14770 transaction_pool.go:215] (t) 3937306634663965 => 00fc5725 (0x6a9b50) be8b11d5f4dba1701f100b80b7d954a6bbe27f90b9240650aabb99e3499e91aa
I0615 13:32:50.662693   14770 transaction_pool.go:266] tx be8b11d5
I0615 13:32:50.766354   14770 sync.go:136] Scheduling 1 hash announcements from 5e8737cbfccfa52c
I0615 13:32:51.285929   14770 sync.go:173] Explicitly fetching 1 blocks from 5e8737cbfccfa52c
I0615 13:32:51.324733   14770 sync.go:136] Scheduling 1 hash announcements from 5e8737cbfccfa52c
I0615 13:32:51.500445   14770 downloader.go:536] Peer 5e8737cbfccfa52c [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:51.706972   14770 sync.go:136] Scheduling 1 hash announcements from 654b2c5c931fe8fc
I0615 13:32:51.886294   14770 sync.go:173] Explicitly fetching 1 blocks from 5e8737cbfccfa52c
I0615 13:32:51.981675   14770 downloader.go:536] Peer 5e8737cbfccfa52c [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:32:55.090289   14770 sync.go:136] Scheduling 1 hash announcements from 326bf5f061fb5f75
I0615 13:32:55.385975   14770 downloader.go:205] Attempting synchronisation: 5e8737cbfccfa52c, 0xcea535ae232a860994771e37da5690bf7ad5cce0cffc58d72c9c25b92ce11477
I0615 13:32:55.386066   14770 downloader.go:212] Synchronisation already in progress
I0615 13:32:58.049967   14770 transaction_pool.go:215] (t) 3965656638626133 => 00fc5725 (0x6a9b50) 6694084f2e55386b1adb61cd1368b7888cd05ea04275ff70e13919ffdcedb3be
I0615 13:32:58.059823   14770 transaction_pool.go:266] tx 6694084f
I0615 13:32:58.061107   14770 transaction_pool.go:215] (t) 3965656638626133 => 00fc5725 (0x6a9b50) 8c24df85495f4497b38ced3c0a64ea7a4b78059e9e2c8faba39a53c27cf9f205
I0615 13:32:58.071419   14770 transaction_pool.go:266] tx 8c24df85
I0615 13:32:58.208085   14770 transaction_pool.go:215] (t) 3965656638626133 => 00fc5725 (0x6a9b50) e611ad9735b1c26cde26ab2b22ff9e2eb2027eadec5f61a48eced4722ee57845
I0615 13:32:58.218230   14770 transaction_pool.go:266] tx e611ad97
I0615 13:32:59.258344   14770 transaction_pool.go:215] (t) 3937306634663965 => 00fc5725 (0x6a9b50) 998e6c3e42b44697a78b52c34753ce56669571ad9be88f5950cbef6702c91355
I0615 13:32:59.268059   14770 transaction_pool.go:266] tx 998e6c3e
I0615 13:32:59.274245   14770 transaction_pool.go:215] (t) 3937306634663965 => 00fc5725 (0x6a9b50) 1736c44ab9affaac03e8285e3328a63e895e44f410b0601516fca7000ac9922a
I0615 13:32:59.282745   14770 transaction_pool.go:266] tx 1736c44a
I0615 13:32:59.418441   14770 transaction_pool.go:215] (t) 3937306634663965 => 00fc5725 (0x6a9b50) 4700d986cb78601b39ef3ad6cee13a6a976aa44f0ea2ca91736fc9e720e6232a
I0615 13:32:59.431539   14770 transaction_pool.go:266] tx 4700d986
I0615 13:32:59.432989   14770 transaction_pool.go:215] (t) 3937306634663965 => 00fc5725 (0x6a9b50) b4bfa0487dba790d2dded91e92118776bbe2fe0e218f7fee105fd2c84536fa9b
I0615 13:32:59.445703   14770 transaction_pool.go:266] tx b4bfa048
I0615 13:32:59.446897   14770 transaction_pool.go:215] (t) 3937306634663965 => 00fc5725 (0x6a9b50) ead674d9dfd34c67cd11f9eab047ebe7357a8de885e8805480cc378fcc2de03e
I0615 13:32:59.456574   14770 transaction_pool.go:266] tx ead674d9
I0615 13:33:01.612292   14770 downloader.go:205] Attempting synchronisation: 5e8737cbfccfa52c, 0xeb4a0b92d8bb3c9795690c98e36eef1e15f6ec7a1d8b844e6289de4311f6cb58
I0615 13:33:01.612339   14770 downloader.go:212] Synchronisation already in progress
I0615 13:33:01.612364   14770 sync.go:136] Scheduling 1 hash announcements from 5e8737cbfccfa52c
I0615 13:33:02.186027   14770 sync.go:173] Explicitly fetching 1 blocks from 5e8737cbfccfa52c
I0615 13:33:02.288980   14770 downloader.go:536] Peer 5e8737cbfccfa52c [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:33:02.775478   14770 api.go:38] eth_blockNumber []
I0615 13:33:02.775653   14770 http.go:149] Generated response: *rpc.RpcSuccessResponse &{%!s(float64=1) 2.0 0x9458f}
I0615 13:33:02.775761   14770 http.go:160] Sending payload: {
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x9458f"
}
I0615 13:33:04.014004   14770 sync.go:136] Scheduling 1 hash announcements from 5e8737cbfccfa52c
I0615 13:33:04.171295   14770 sync.go:136] Scheduling 1 hash announcements from f86a89edaa6d21ea
I0615 13:33:04.585962   14770 sync.go:173] Explicitly fetching 1 blocks from 5e8737cbfccfa52c
I0615 13:33:04.685952   14770 sync.go:173] Explicitly fetching 1 blocks from f86a89edaa6d21ea
I0615 13:33:04.865876   14770 downloader.go:536] Peer 5e8737cbfccfa52c [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:33:05.023311   14770 downloader.go:536] Peer f86a89edaa6d21ea [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:33:05.385879   14770 downloader.go:205] Attempting synchronisation: f86a89edaa6d21ea, 0x224a08f8c778b36b1670854488beb027172bf1a4856c23f4030b759dc10c26ca
I0615 13:33:05.385923   14770 downloader.go:212] Synchronisation already in progress
I0615 13:33:07.565325   14770 sync.go:136] Scheduling 1 hash announcements from 326bf5f061fb5f75
I0615 13:33:08.340784   14770 sync.go:136] Scheduling 1 hash announcements from 326bf5f061fb5f75
I0615 13:33:08.886192   14770 sync.go:173] Explicitly fetching 1 blocks from 326bf5f061fb5f75
I0615 13:33:09.004738   14770 sync.go:136] Scheduling 1 hash announcements from 5e8737cbfccfa52c
I0615 13:33:09.358565   14770 downloader.go:536] Peer 326bf5f061fb5f75 [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:33:09.585997   14770 sync.go:173] Explicitly fetching 1 blocks from 5e8737cbfccfa52c
I0615 13:33:09.773494   14770 downloader.go:536] Peer 5e8737cbfccfa52c [reputation   0, capacity   1, ignored    0]: out of bound delivery
I0615 13:33:12.047571   14770 downloader.go:205] Attempting synchronisation: 5e8737cbfccfa52c, 0x27f107eec9e1474e56a9e4685e09a3fb5b8c1597fb5095daae89cb7e1de98e88
I0615 13:33:12.047731   14770 downloader.go:212] Synchronisation already in progress
I0615 13:33:12.874670   14770 sync.go:136] Scheduling 1 hash announcements from 654b2c5c931fe8fc
I0615 13:33:13.385979   14770 sync.go:173] Explicitly fetching 1 blocks from 654b2c5c931fe8fc
I0615 13:33:13.652947   14770 downloader.go:536] Peer 654b2c5c931fe8fc [reputation   0, capacity   1, ignored    0]: out of bound delivery
```

**Comment by karalabe** [comment] 2015-06-19 07:48
Could you try the latest develop? We've fixed two lockups in the downloader, as well as polish the propagation/announcement based block synchronization, so there should be much fewer issues in this aspect.

**Comment by ethers** [comment] 2015-06-20 08:58
on commit 53e042f0c47242afa3e13cfebb35becdacdc69c0
Geth
Version: 0.9.31
Git Commit: 53e042f0c47242afa3e13cfebb35becdacdc69c0
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2

geth is getting stuck on block "0x9f349"

**Comment by ethers** [comment] 2015-06-23 01:26
Geth
Version: 0.9.31
Git Commit: 9cf7913c61c6f9c1f36a44778a75e6a91a741be4
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2

stuck on
```
> eth.blockNumber
679348
```

```
I0623 01:17:11.172016   10983 chain_manager.go:677] [1435022231171991520] inserted block #679345 (2 TXs 0 UNCs) (da45afb5...). Took 18.181
28ms
I0623 01:17:11.172403   10983 chain_manager.go:700] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 18.549477ms. #679345 [da45
afb5 / da45afb5]
I0623 01:17:11.314861   10983 downloader.go:594] Peer cf2336ebf5c5cf92 [reputation  48, capacity   1, ignored    0]: requesting 1 blocks
I0623 01:17:11.315069   10983 downloader.go:594] Peer 3200911b77b0fc12 [reputation  26, capacity   1, ignored    0]: requesting 1 blocks
I0623 01:17:11.315197   10983 downloader.go:594] Peer e014ceab3d2fbe72 [reputation   1, capacity   1, ignored    0]: requesting 1 blocks
I0623 01:17:11.315317   10983 downloader.go:594] Peer e58050b209e5df1e [reputation   0, capacity   1, ignored    0]: requesting 1 blocks
I0623 01:17:11.315439   10983 downloader.go:594] Peer 7ac0ea51b676ee8f [reputation   0, capacity   1, ignored    0]: requesting 1 blocks
I0623 01:17:11.390733   10983 downloader.go:530] Peer e014ceab3d2fbe72 [reputation   2, capacity   2, ignored    0]: delivered 1 blocks
I0623 01:17:11.768944   10983 downloader.go:530] Peer 3200911b77b0fc12 [reputation  27, capacity   2, ignored    0]: delivered 1 blocks
I0623 01:17:11.827430   10983 downloader.go:530] Peer cf2336ebf5c5cf92 [reputation  49, capacity   2, ignored    0]: delivered 1 blocks
I0623 01:17:11.827767   10983 downloader.go:761] Inserting chain with 3 blocks (#679344 - #679346)
I0623 01:17:12.147776   10983 chain_manager.go:677] [1435022232147755088] inserted block #679346 (121 TXs 1 UNCs) (f2d3f214...). Took 971.058654ms
I0623 01:17:12.148795   10983 chain_manager.go:700] imported 1 block(s) (0 queued 0 ignored) including 121 txs in 972.044648ms. #679346 [f2d3f214 / f2d3f214]
I0623 01:17:12.226196   10983 chain_manager.go:700] imported 0 block(s) (0 queued 3 ignored) including 0 txs in 23.954142ms. #679346 [1fc09c26 / f2d3f214]
I0623 01:17:12.259291   10983 chain_manager.go:677] [1435022232259271256] inserted block #679347 (2 TXs 1 UNCs) (e33db19b...). Took 32.8497ms
I0623 01:17:12.259693   10983 chain_manager.go:700] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 33.230534ms. #679347 [e33db19b / e33db19b]
I0623 01:17:13.123349   10983 chain_manager.go:677] [1435022233123328939] inserted block #679348 (114 TXs 0 UNCs) (e39f0d45...). Took 831.207375ms
I0623 01:17:13.124237   10983 chain_manager.go:700] imported 1 block(s) (0 queued 0 ignored) including 114 txs in 832.075068ms. #679348 [e39f0d45 / e39f0d45]
I0623 01:17:20.355513   10983 downloader.go:571] Peer e58050b209e5df1e [reputation   0, capacity   1, ignored    0]: block delivery timeout
I0623 01:17:20.355736   10983 downloader.go:571] Peer 7ac0ea51b676ee8f [reputation   0, capacity   1, ignored    0]: block delivery timeout
I0623 01:17:20.355867   10983 downloader.go:594] Peer cf2336ebf5c5cf92 [reputation  49, capacity   2, ignored    0]: requesting 2 blocks
I0623 01:17:20.555901   10983 downloader.go:530] Peer cf2336ebf5c5cf92 [reputation  50, capacity   4, ignored    0]: delivered 2 blocks
I0623 01:17:20.556162   10983 downloader.go:761] Inserting chain with 2 blocks (#679347 - #679348)
I0623 01:17:20.561894   10983 downloader.go:618] Downloaded block(s) in 9.522808873s
I0623 01:17:20.562437   10983 downloader.go:299] Synchronization completed
I0623 01:17:20.562545   10983 downloader.go:211] Synchronisation completed
I0623 01:17:20.607047   10983 chain_manager.go:700] imported 0 block(s) (0 queued 2 ignored) including 0 txs in 50.717826ms. #679348 [e33db19b / e39f0d45]
I0623 01:17:26.069255   10983 downloader.go:185] Registering peer 5cbf894354687622
I0623 01:17:26.073174   10983 sync.go:76] Peer 5cbf894354687622 54.174.75.126:30303: sending 8 transactions (4.16 kB)
I0623 01:17:59.789351   10983 downloader.go:196] Unregistering peer 5cbf894354687622
I0623 01:17:59.894194   10983 chain_manager.go:700] imported 1 block(s) (0 queued 0 ignored) including 114 txs in 1.369316081s. #679348 [68e39e9b / 68e39e9b]
I0623 01:18:31.801956   10983 downloader.go:185] Registering peer 5cbf894354687622
I0623 01:18:31.806042   10983 sync.go:76] Peer 5cbf894354687622 54.174.75.126:30303: sending 8 transactions (4.16 kB)
I0623 01:18:34.058967   10983 downloader.go:196] Unregistering peer 5cbf894354687622
I0623 01:19:08.837005   10983 downloader.go:185] Registering peer 5cbf894354687622
I0623 01:19:08.840583   10983 sync.go:76] Peer 5cbf894354687622 54.174.75.126:30303: sending 8 transactions (4.16 kB)
I0623 01:19:17.496766   10983 downloader.go:196] Unregistering peer e014ceab3d2fbe72
I0623 01:19:37.540240   10983 downloader.go:196] Unregistering peer 5cbf894354687622
I0623 01:20:11.032729   10983 downloader.go:185] Registering peer 5cbf894354687622
I0623 01:20:11.036194   10983 sync.go:76] Peer 5cbf894354687622 54.174.75.126:30303: sending 8 transactions (4.16 kB)
I0623 01:20:21.493216   10983 downloader.go:196] Unregistering peer 5cbf894354687622
I0623 01:20:44.090538   10983 downloader.go:185] Registering peer 5cbf894354687622
I0623 01:20:44.094063   10983 sync.go:76] Peer 5cbf894354687622 54.174.75.126:30303: sending 8 transactions (4.16 kB)
I0623 01:21:12.878246   10983 downloader.go:196] Unregistering peer 5cbf894354687622
I0623 01:21:45.632016   10983 downloader.go:185] Registering peer 5cbf894354687622
I0623 01:21:45.643505   10983 sync.go:76] Peer 5cbf894354687622 54.174.75.126:30303: sending 8 transactions (4.16 kB)
```

**Comment by ethers** [comment] 2015-06-23 01:27
related to #1303 ?

**Comment by karalabe** [comment] 2015-06-23 07:32
If this occurs again, could you please paste a bit more logs in both directions? It not enough to really figure out what's going on inside geth. Additionally - if you're brave enough to risk a db corruption - if geth is stuck, can you send it a SIGABRT message to produce a crash dump so I could see where the goroutines are? (`kill -SIGABRT <geth pid>`)

**Comment by ethers** [comment] 2015-06-24 02:47
ok.  here is a log from the start.  i didn't want to risk db corruption right now.  i will try to provide more information as I continue (surprised if not much other people are seeing the same issue)

http://paste.ubuntu.com/11765655/
`--verbosity 3 --vmodule=chain_manager=5,api=5,rpc=5,http=6,transaction_pool=5,sync=6,downloader=6`
Version: 0.9.33
Git Commit: 22c7ce0162f2d14a7340e00e93697780c91d2087
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2

**Comment by karalabe** [comment] 2015-06-24 07:06
I don't see what the issue is. Could you point it out? To me it seems you have fully synced.

**Comment by karalabe** [comment] 2015-06-24 07:07
Ah, could you add `fetcher=6` in there? Those were the logs I'm missing :D

**Comment by ethers** [comment] 2015-06-24 08:42
The issue was after 
```
I0624 02:22:31.946846   19398 chain_manager.go:700] imported 0 block(s) (0 queued 2 ignored) including 0 txs in 80.033309ms. #689510 [ced66646 / 7bc31622]
```
geth stopped getting blocks; I let it run for 7 minutes and killed it (will make it clearer next time)

I am now running with fetcher=6 and will post more info when I see

**Comment by fjl** [comment] 2015-08-09 21:45
A lot of fixes have happened and this was an Olympic issue. I'll close it now because Olympic is in the past. If anything like this happens again, please open another issue.

**Closed by fjl** 2015-08-09 21:45 UTC
