### ISSUE TITLE
Suggestion: advanced version of eth_call with which you can simulate multiple transactions in a row and see how they would affect the blockchain together.

### ISSUE THREAD

**Issue by degengalahad** [ethereum/go-ethereum#26187] opened 2022-11-15 20:31 UTC
# Rationale

Why should this feature exist?

So I'm a crypto trader and sometimes there are certain tokens which you can buy but you can't sell, we call them honeypots, it would be cool to be able to simulate a transaction to buy and then one to sell to check if it's a honeypot or not before actually buying the token and risking losing money.

What are the use-cases?

For traders:
- Check if a token is a honeypot or not.
- Check how much taxes it has.
- Check the max amount of tokens you can buy. 

# Implementation

Do you have ideas regarding the implementation of this feature?

Tbh I'm kinda a noob on golang, so not really, just giving my idea :D

Are you willing to implement this feature?

Maybe in a month or two when I get better at golang.

**Comment by ligi** [comment] 2022-11-16 00:26
looks like a duplicate of #24089

**Closed** 2022-11-17 09:22 UTC
Labels: type:feature
