### ISSUE TITLE
geth stops working once the Server is restarted or the Command line closes down

### ISSUE THREAD

**Issue by jthak052** [ethereum/go-ethereum#23589] opened 2021-09-16 15:57 UTC
I am running Geth on Command line and Geth stops working after server restarts or the Command line closes down. I am using windows so cant use Tmux or anything.

and can I connect the geth with IIS or something ? or I have to forward the port so I can access the RPC from metamask from outsode

**Comment by verheesj** [comment] 2021-09-17 06:35
> I am running Geth on Command line and Geth stops working after server restarts or the Command line closes down. I am using windows so cant use Tmux or anything.
> 
> and can I connect the geth with IIS or something ? or I have to forward the port so I can access the RPC from metamask from outsode

Windows does not support this natively. I am aware of a freeware software (but haven't tested - use at your own risk), https://www.nirsoft.net/utils/nircmd.html

You can try and run geth via a .bat script?

1. Create a file named geth.bat 
2. The file should contain the full path to geth and any passed arguments (example: `C:/go-etherum/build/bin/geth --syncmode=.....` 
3. `CTRL + R` or Run...
4. `nircmd exec hide "c:\path\to\geth.bat"`

Let us know how you get on.

**Comment by holiman** [comment] 2021-09-17 07:43
@jthak052 you can use windows services, where you run something as a background service instead of as a CLI process.  I'm not up to speed with how to configure that on windows, I haven't used windows for several years unfortunately.

**Comment by holiman** [comment] 2021-09-17 07:44
Closing this, since it's not a bug in geth. It's a windows thing, so just google how to configure a background service in Windows.

**Closed** 2021-09-17 07:44 UTC
Labels: type:docs
