### ISSUE TITLE
Broken apt on Ubuntu 18.04

### ISSUE THREAD

**Issue by talvbansal** [ethereum/go-ethereum#17354] opened 2018-08-08 13:00 UTC
Just tried to update my Ubuntu 18.04 installation and ive got this:

```
sudo apt update

....

E: The repository 'http://ppa.launchpad.net/ethereum/ethereum-qt/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Then when running and upgrade:

```
sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies.
 ethereum : Depends: ethereum-swarm but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

Running the recommended fix gives this:

```
sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  libmpcdec6 swarm
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  ethereum-swarm
The following NEW packages will be installed
  ethereum-swarm
0 to upgrade, 1 to newly install, 0 to remove and 32 not to upgrade.
96 not fully installed or removed.
Need to get 0 B/5,561 kB of archives.
After this operation, 22.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 252282 files and directories currently installed.)
Preparing to unpack .../ethereum-swarm_0.3.1+build14601+bionic_amd64.deb ...
Unpacking ethereum-swarm (0.3.1+build14601+bionic) ...
dpkg: error processing archive /var/cache/apt/archives/ethereum-swarm_0.3.1+build14601+bionic_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/swarm', which is also in package swarm 2.2.2+dfsg-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/ethereum-swarm_0.3.1+build14601+bionic_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

My apt install is now in an inconsistent state. I've tried removing the file from apt cache and tried again but get the same results again.

Has anyone else seen this or have a fix?

Many thanks

**Comment by homotopycolimit** [comment] 2018-08-08 13:17
try `apt-get purge swarm` and then `apt-get install ethereum-swarm`

**Comment by nonsense** [comment] 2018-08-08 13:25
Closing as this is a duplicate of https://github.com/ethereum/go-ethereum/issues/17295

**Closed by nonsense** 2018-08-08 13:25 UTC

**Comment by nonsense** [comment] 2018-08-08 13:28
@talvbansal just so that you don't have to search through the other issue, try removing `swarm`, and then installing `ethereum`.

```
apt-get --purge remove ethereum
apt-get --purge remove swarm
apt-get install ethereum
```

**Comment by talvbansal** [comment] 2018-08-09 11:47
thanks @nonsense :+1:
