### ISSUE TITLE
http: Accept error: accept tcp IP too many open files

### ISSUE THREAD

**Issue by Phistr90** [ethereum/go-ethereum#1549] opened 2015-07-29 16:40 UTC
Setup: Ubuntu 15, geth 0.9.38, 10 maxpeers, rpc, farm-recheck 500

Error output/log: https://gist.github.com/Phistr90/364d7d6d506fc4fae5d4

Tried to set:
net.ipv4.tcp_fin_timeout=30
net.ipv4.tcp_tw_recycle=1
net.ipv4.tcp_tw_reuse=1
 but that didnt help me.

and limits:
*	soft	nofile	999999

*	hard	nofile	999999

root 	soft 	nofile 	65536

root 	hard nofile 	65536

Stephan had this problem with running 250 peers. But I got only 10 peers and 6 GPUs with farm-recheck 500. https://github.com/ethereum/go-ethereum/issues/1460

**Comment by fjl** [comment] 2015-07-29 18:48
I think I have a clue about what is causing this.

**Comment by obscuren** [comment] 2015-07-29 19:05
I've also seen this happen when ethminer hammers the RPC

**Comment by Phistr90** [comment] 2015-07-29 19:34
farm-recheck is just 500, so there isnt that much load...

**Comment by Phistr90** [comment] 2015-07-30 02:10
I would be really happy, if you could find the bug fjl. Well, arent the rpc requests from ethminer. because i had 4 gpu with 500ms before.

**Comment by obscuren** [comment] 2015-07-30 10:36
It depends on whether `ethminer` closes the connection. If connections aren't properly closed you'll eventually end up with the **Too many files open** error. I'm not claiming this **is** the issue, just something that should be investigated.

**Comment by fjl** [comment] 2015-07-31 21:13
I have looked into it and neither ethminer nor the RPC seem to be at fault. ethminer uses a single socket
and HTTP/1.1 keep-alive as expected. Will investigate further.

**Comment by drupalnomad** [comment] 2015-08-02 15:17
I also had this problem:
https://gist.github.com/drupalnomad/936809d1c9546b28d477

I am on ubuntu. I had about 200 peers, was not mining, and was using pm2.

I think this may be related to switching to another wifi access point.

**Comment by etherninja** [comment] 2015-08-03 00:11
Could this be a ephemeral port range limitation? Each new call creates a new rpc port. These are limited by 30,000 by default and should produce the open file error when exhausted. Maybe check "netstat -an | grep TIME_WAIT | wc -l" 

In theory, the system can only guarantee using defaults no more than  ((61000 - 32768) / 60 = 470) ports at any given time.

**Comment by fjl** [comment] 2015-08-03 15:13
I still haven't been able to reproduce this issue, even with netstats hammering the node for 10h+.
Release 1.0.1 will log statistics about open files every 15s. This should help us track down the issue.

**Comment by fjl** [comment] 2015-08-05 16:37
The issue has been identified. Unfortunately, due to timing constraints, the fix won't be in 1.0.1.
We will make the fix available for testing on the develop branch as soon as possible.

**Comment by fjl** [comment] 2015-08-19 19:37
The fix above will be in `1.0.2`.

**Comment by fjl** [comment] 2015-09-17 20:54
The fix has been released.

**Closed** 2015-09-17 20:54 UTC
Labels: bug, need fix, RPC
