### ISSUE TITLE
SubscribeFilterLogs "Removed" events out of order.

### ISSUE THREAD

**Issue by ksedgwic** [ethereum/go-ethereum#16190] opened 2018-02-25 22:19 UTC
#### System information

    Geth
    Version: 1.7.3-stable
    Architecture: amd64
    Protocol Versions: [63 62]
    Network Id: 1
    Go Version: go1.8.3
    Operating System: linux
    GOPATH=
    GOROOT=/usr/lib/golang

Command Line:
```
/usr/local/src/go-ethereum/build/bin/geth --ws --wsorigins="*" --rpc --config /etc/geth/config.toml
```

Config:
```
[Node]
HTTPPort = 9545
WSPort = 9546

[Node.P2P]
ListenAddr = ":40404"
DiscoveryV5Addr = ":40405"
```

OS:

    CentOS Linux release 7.4.1708 (Core) 

#### Expected behaviour

Add and Removed events for the same transaction should occur in the
correct order.  Here is an example of correct ordering:

    2018/02/23 20:45:15.916539 tracker.go:483: ADDED Transfer {"From":"0x0681d8db095565fe8a346fa0277bffde9c0edbbf","To":"0xa023514ce835eb7d3f54ac997e70f86f8ea3aa71","Value":829601000000000000,"BlockNumber":5144026,"TxHash":"0x1d3959c9f2b4d2efdfba3711e72b052ab12869ffb16c17b90ba34b3e1cb26293","Tstamp":"2018-02-23T20:45:06Z"}
    2018/02/23 20:45:18.126551 tracker.go:481: REMOVED Transfer {"From":"0x0681d8db095565fe8a346fa0277bffde9c0edbbf","To":"0xa023514ce835eb7d3f54ac997e70f86f8ea3aa71","Value":829601000000000000,"BlockNumber":5144026,"TxHash":"0x1d3959c9f2b4d2efdfba3711e72b052ab12869ffb16c17b90ba34b3e1cb26293","Tstamp":"0001-01-01T00:00:00Z"}
    2018/02/23 20:45:18.149459 tracker.go:483: ADDED Transfer {"From":"0x0681d8db095565fe8a346fa0277bffde9c0edbbf","To":"0xa023514ce835eb7d3f54ac997e70f86f8ea3aa71","Value":829601000000000000,"BlockNumber":5144026,"TxHash":"0x1d3959c9f2b4d2efdfba3711e72b052ab12869ffb16c17b90ba34b3e1cb26293","Tstamp":"2018-02-23T20:45:06Z"}

#### Actual behaviour

Sometimes the final ADDED event is missing:

    2018/02/23 18:39:37.383092 tracker.go:483: ADDED Transfer {"From":"0xd311111d44c20d30f755f5a0934da7242a6d5c8b","To":"0x8e8b49ef032daacb142de55d747cdee012c9337d","Value":11072917340000000000,"BlockNumber":5143459,"TxHash":"0x8e14b5394d91de449688e0860aaa1c1d5a5d82de8f00ba289eae5ff7bea701fd","Tstamp":"2018-02-23T18:39:28Z"}
    2018/02/23 18:39:54.743614 tracker.go:481: REMOVED Transfer {"From":"0xd311111d44c20d30f755f5a0934da7242a6d5c8b","To":"0x8e8b49ef032daacb142de55d747cdee012c9337d","Value":11072917340000000000,"BlockNumber":5143459,"TxHash":"0x8e14b5394d91de449688e0860aaa1c1d5a5d82de8f00ba289eae5ff7bea701fd","Tstamp":"0001-01-01T00:00:00Z"}
    <no further event for 0x8e14b5394d9...>

Etherscan shows the event should have been re-added:
https://etherscan.io/tx/0x8e14b5394d91de449688e0860aaa1c1d5a5d82de8f00ba289eae5ff7bea701fd

Sometimes there are several cycles with a missing final ADD:

    2018/02/23 18:57:00.369952 tracker.go:483: ADDED Transfer {"From":"0x001243dc61962963840f137b50b641edee7dee25","To":"0xc1d018bceffc7f6ddcc9843bcbf399a49811baad","Value":189429000000000000000,"BlockNumber":5143535,"TxHash":"0x7de30d5307198a8ad41c5f9eae3063547cd70a4e1d97cc6fd8214b4ba7cda453","Tstamp":"2018-02-23T18:56:53Z"}
    2018/02/23 18:57:03.098854 tracker.go:481: REMOVED Transfer {"From":"0x001243dc61962963840f137b50b641edee7dee25","To":"0xc1d018bceffc7f6ddcc9843bcbf399a49811baad","Value":189429000000000000000,"BlockNumber":5143535,"TxHash":"0x7de30d5307198a8ad41c5f9eae3063547cd70a4e1d97cc6fd8214b4ba7cda453","Tstamp":"0001-01-01T00:00:00Z"}
    2018/02/23 18:57:03.099059 tracker.go:483: ADDED Transfer {"From":"0x001243dc61962963840f137b50b641edee7dee25","To":"0xc1d018bceffc7f6ddcc9843bcbf399a49811baad","Value":189429000000000000000,"BlockNumber":5143535,"TxHash":"0x7de30d5307198a8ad41c5f9eae3063547cd70a4e1d97cc6fd8214b4ba7cda453","Tstamp":"2018-02-23T18:56:53Z"}
    2018/02/23 18:57:06.992149 tracker.go:481: REMOVED Transfer {"From":"0x001243dc61962963840f137b50b641edee7dee25","To":"0xc1d018bceffc7f6ddcc9843bcbf399a49811baad","Value":189429000000000000000,"BlockNumber":5143535,"TxHash":"0x7de30d5307198a8ad41c5f9eae3063547cd70a4e1d97cc6fd8214b4ba7cda453","Tstamp":"0001-01-01T00:00:00Z"}
    <no further event for 0x7de30d53071...>

https://etherscan.io/tx/0x7de30d5307198a8ad41c5f9eae3063547cd70a4e1d97cc6fd8214b4ba7cda453

Sometimes there are extra removes:

    2018/02/23 20:10:18.589166 tracker.go:483: ADDED Transfer {"From":"0x50c6e9dcea48e61f3ce47dd7f9c69fb3e12cd79c","To":"0x31b9207d8e54e3c66099dc2872fd75b5cc4666c5","Value":2394852350000000000,"BlockNumber":5143855,"TxHash":"0x703dadd417c17b1ee09cd75f07a9ebe3d5844d7e561d8e0ec08102f14e55f923","Tstamp":"2018-02-23T20:10:03Z"}
    2018/02/23 20:10:20.463732 tracker.go:481: REMOVED Transfer {"From":"0x50c6e9dcea48e61f3ce47dd7f9c69fb3e12cd79c","To":"0x31b9207d8e54e3c66099dc2872fd75b5cc4666c5","Value":2394852350000000000,"BlockNumber":5143855,"TxHash":"0x703dadd417c17b1ee09cd75f07a9ebe3d5844d7e561d8e0ec08102f14e55f923","Tstamp":"0001-01-01T00:00:00Z"}
    2018/02/23 20:10:20.615665 tracker.go:483: ADDED Transfer {"From":"0x50c6e9dcea48e61f3ce47dd7f9c69fb3e12cd79c","To":"0x31b9207d8e54e3c66099dc2872fd75b5cc4666c5","Value":2394852350000000000,"BlockNumber":5143855,"TxHash":"0x703dadd417c17b1ee09cd75f07a9ebe3d5844d7e561d8e0ec08102f14e55f923","Tstamp":"2018-02-23T20:10:03Z"}
    2018/02/23 20:10:32.414740 tracker.go:481: REMOVED Transfer {"From":"0x50c6e9dcea48e61f3ce47dd7f9c69fb3e12cd79c","To":"0x31b9207d8e54e3c66099dc2872fd75b5cc4666c5","Value":2394852350000000000,"BlockNumber":5143855,"TxHash":"0x703dadd417c17b1ee09cd75f07a9ebe3d5844d7e561d8e0ec08102f14e55f923","Tstamp":"0001-01-01T00:00:00Z"}
    2018/02/23 20:10:33.616201 tracker.go:481: REMOVED Transfer {"From":"0x50c6e9dcea48e61f3ce47dd7f9c69fb3e12cd79c","To":"0x31b9207d8e54e3c66099dc2872fd75b5cc4666c5","Value":2394852350000000000,"BlockNumber":5143855,"TxHash":"0x703dadd417c17b1ee09cd75f07a9ebe3d5844d7e561d8e0ec08102f14e55f923","Tstamp":"0001-01-01T00:00:00Z"}
    2018/02/23 20:10:33.616282 tracker.go:438: SKIPPING REMOVE, CAN'T FIND MATCHING TX IN ACCOUNT 0x50c6e9DceA48E61f3CE47dD7F9C69FB3E12cd79c
    2018/02/23 20:10:33.616303 tracker.go:438: SKIPPING REMOVE, CAN'T FIND MATCHING TX IN ACCOUNT 0x31B9207d8e54E3C66099DC2872fD75B5Cc4666c5
    2018/02/23 20:10:53.935090 tracker.go:481: REMOVED Transfer {"From":"0x50c6e9dcea48e61f3ce47dd7f9c69fb3e12cd79c","To":"0x31b9207d8e54e3c66099dc2872fd75b5cc4666c5","Value":2394852350000000000,"BlockNumber":5143855,"TxHash":"0x703dadd417c17b1ee09cd75f07a9ebe3d5844d7e561d8e0ec08102f14e55f923","Tstamp":"0001-01-01T00:00:00Z"}
    2018/02/23 20:10:53.935190 tracker.go:438: SKIPPING REMOVE, CAN'T FIND MATCHING TX IN ACCOUNT 0x50c6e9DceA48E61f3CE47dD7F9C69FB3E12cd79c
    2018/02/23 20:10:53.935244 tracker.go:438: SKIPPING REMOVE, CAN'T FIND MATCHING TX IN ACCOUNT 0x31B9207d8e54E3C66099DC2872fD75B5Cc4666c5
    <no further event for 0x703dadd417...>

https://etherscan.io/tx/0x703dadd417c17b1ee09cd75f07a9ebe3d5844d7e561d8e0ec08102f14e55f923

#### Steps to reproduce the behaviour

1. Subscribe to contract address 0xd26114cd6EE289AccF82350c8d8487fedB8A0C07.

2. Print "Transfer" events, keep track of seen transactions.

#### Backtrace

NA

**Comment by krogla** [comment] 2018-04-02 09:56
the same issue when listening events via web3 v1.0, there is no expected event after 'removed'

**Comment by 2opremio** [comment] 2018-04-12 20:44
I have also been experience this issue

**Comment by Deams51** [comment] 2018-04-13 04:48
Would love to hear back on this one.
Still happening on 1.8.3

**Comment by 2opremio** [comment] 2018-05-20 18:25
Possible duplicate of #14630

**Comment by ksedgwic** [comment] 2018-07-22 06:12
Any news?

**Comment by rjl493456442** [comment] 2018-12-17 08:36
Hi guys, could you please try with this patch #18322?

**Closed** 2019-09-17 09:20 UTC
Labels: status:triage
