### ISSUE TITLE
JSON-RPC over IPC should envelope messages.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/go-ethereum#3702] opened 2017-02-23 05:37 UTC
Crossposted https://github.com/ethcore/parity/issues/4647, since this is a systemic ecosystem issue.

When receiving JSON-RPC requests over WS or HTTP, the underlying protocol deals with ensuring that messages are well separated and that the connection can gracefully recover from bad bytes put onto the wire.  While domain sockets/named pipes will deal with ordering and guaranteeing arrival, they do not do anything to separate messages.  This leads to a sort of cascade of problems.  The first being that the developer wanting to utilize the IPC needs to write code that can identify end of one message and beginning of another.  Unfortunately, the only way to correctly deal with this is to write or use a streaming JSON parser that can stop when it reaches the end of an object.  Unfortunately, most off-the-shelf parsers will error indicating malformed JSON if you try to parse a byte stream that has multiple separate JSON payloads concatenated together (such as the JSON-RPC over IPC protocol).

Even if the user writes a fully JSON compliant streaming parser, it also needs to deal with the fact that JSON is UTF-8 which means a surrogate pair may cross buffer boundaries.  This means that not only does the user have to deal with the fact that messages themselves may cross buffer boundaries, but it also needs to deal with the fact that individual characters may cross message boundaries.  This is a solvable problem but it introduces a lot of complexity for the developer to deal with.

I think most critically is the fact that I don't _believe_ there is a *recoverable* way to write an end-on-end JSON parser without some kind of enveloping.  Imagine someone sent this over HTTP, WS and IPC:
```
{ jsonrpc: "2.0", id: 5, method: "truncat
{ jsonrpc: "2.0", id: 6, method: "complete", params: "}{" }
```
With HTTP and WS, the channel would remain open and the receiver would be able to respond with an appropriate error message indicating one of the messages was malformed.  For IPC however, there is *no correct way* to deal with this.  As far as the receiver is concerned, it is in the middle of parsing a JSON string until it receives the next quote, at which point it will see some invalid JSON following it.  Unfortunately, the parser doesn't know where to read up to in order to "skip to the next message" and start over.  It could try looking for something like `}{`, but as you can see in this example the `}{` would be in the middle of another message (inside a string) but the parser doesn't know that, so it would fail again.  Hypothetically you could keep repeating this process (look for some sort of boundary character sequence) until you find a valid message, but that is incredibly complex and I'm not entirely certain there isn't an edge case that would 

Proposal
----
I propose that a version 2 (or are we up to 3?) of the JSON-RPC over IPC be built that envelopes messages with a sentinel header and a length prefix.  The length prefix would allow parsers to simply wait until they have the whole message before trying to process any JSON and if the JSON or UTF-8 inside the envelope is invalid it can throw away the whole message without any trouble.  The sentinel would be a special byte sequence that would need to be escaped if found anywhere in the payload (could be as little as one byte, but that would require more frequent escaping) and would allow the channel to recover cleanly from malformed input by simply reading until the next sentinel.

Re: sentinel, is a `0` byte valid anywhere in a JSON string?  If not, then the null byte could be used as the sentinel without need for escaping.

Notes
----
There are several Ethereum JSON-RPC over IPC clients that I know of at this point (Geth, Parity, Web3, Ethrpc) and so far I haven't seen anyone fully solve this problem.  I'm not entirely certain what Geth is doing since it appears to be relying on something from go-lang, but I would be mildly surprised if it correctly deals with all of the problems associated with un-enveloped IPC payloads.

**Comment by MicahZoltu** [comment] 2017-02-23 05:43
It should be noted that this problem makes it much easier for attackers to write injection attacks since writing a good parser is so difficult.  The current `web3.js` implementation, for example, currently is open to an injection attack if the attacker can get a `}{` into the payload of a message (I suspect not hard).

**Comment by bas-vk** [comment] 2017-02-23 08:57
> The first being that the developer wanting to utilize the IPC needs to write code that can identify end of one message and beginning of another. 

If you want to use the streaming feature it means you need to have support for streaming json messages on the client. If you don't want to use streaming messages it is possible to open multiple IPC connections and use the request/reply pattern just like http. This is up to the client. To be complete, geth also supports pipelining. Therefore responses can be returned out of order and clients needs to keep track of req/res ids.

> Even if the user writes a fully JSON compliant streaming parser, it also needs to deal with the fact that JSON is UTF-8 which means a surrogate pair may cross buffer boundaries.

In the Ethereum world this is not an issue because data is transferred hex encoded. As long as the client uses ascii for the id, jsonrpc and method fields you are fine with a naive implementation that assumes 1 char equals 1 byte.

> For IPC however, there is no correct way to deal with this.

Correct, geth responds with an error indication that the request was invalid and closes the connection since this is a non recoverable situation. This makes it explicit for the client that something went horribly wrong.


> I propose that a version 2 (or are we up to 3?) of the JSON-RPC over IPC be built that envelopes messages with a sentinel header and a length prefix.

I think this solves a really small problem. Most clients that use IPC will probably use something like Mist that takes case of these situations (Mist has a custom "dechuncker"). DApps that connect directly to the IPC endpoint are probably specialised applications that have access to a good streaming decoder. Or can use the simple req/res pattern with multiple IPC connections or fallback to the http/ws interface.

Second, it is a custom protocol that only makes sense for IPC connections. Clients that want to use this will need to write their own encoders/decoders instead of using some default library. If we move towards such a protocol we will make either the majority of client developers unhappy or need to support both protocols.

**Comment by karalabe** [comment] 2017-02-23 12:27
As I mentioned in the chat channel, I don't see how message corruption can occur. HTTP, WS are TCP based, IPC is backed by unix sockets or windows pipes; all take care of data chunking, ordering, retransmits, etc. Client and server side you should have a single thread reading a data stream and similarly either a single thread writing it or one that multiple ones properly synchronized. There is literally no way to corrupt a data stream.

Regarding the proposal, the data transport we are currently using is a standard JSON stream. It is a well understood and commonly used protocol. I'm certain any decent programming language is able to process it either out of the box or there are a number of libraries to do it. Converting it into a custom stream would only worsen the scenario, with everyone needing to implement our "new standard".

:-1:

**Comment by karalabe** [comment] 2017-02-23 12:31
>  I'm not entirely certain what Geth is doing since it appears to be relying on something from go-lang, but I would be mildly surprised if it correctly deals with all of the problems associated with un-enveloped IPC payloads.

I would be extremely surprised if it didn't work flawlessly. There are no problems with un-enveloped IPC payloads. It is called a plain data stream.

**Comment by frozeman** [comment] 2017-02-24 08:35
I do agree with @MicahZoltu here. The current IPC streaming is error prone and not clearly defined. Thats also the reason why i had to come up with this quirk: https://github.com/ethereum/web3.js/blob/develop/lib/web3/ipcprovider.js#L84-L89

I together with @bas-vk implemented the IPC, and i do remember bringing up the possibility to properly send END characters, tho i came then with that workaround and we never looked at it again.

@bas-vk The issue is that when you receive a JSON object which is larger than the buffer of the socket, so that it comes in chunks. Then receiving and parsing becomes problematic. Thats the reason why i had to come up with that dechunker.

Tho i do agree that this can become an issue and we should solve it. @karalabe you see that here many JS and client developer are stating this to be an issue. I think that means this IS important for those people.

As you can see all JSON streaming libs use `/n` as a separator, which is a valid way to separate the incoming json.

So my proposal is that we end JSON objects by `/n`, which is already supported by Mist since 8 versions and i think already like this in geth. BUT we need to make sure that any /n inside a result object now or in the future (of method results and notifications) is properly escaped `\/n`.

This would give us backwards compatibility in mist, is a small change and prevent future hacks to break the stream.
At the same time this will reduce the parsing Mist and others have to do with the current try-to-parse implementation.

**Comment by holiman** [comment] 2017-02-24 09:25
> So my proposal is that we end JSON objects by /n, which is already supported by Mist since 8 versions and i think already like this in geth. BUT we need to make sure that any /n inside a result object now or in the future (of method results and notifications) is properly escaped \/n.

That's a requirement in JSON, failure to encode `\n` means that it's invalid JSON.

**Comment by holiman** [comment] 2017-02-24 09:37
The `\n` character should _not_ be used as any kind of meaningful separator in the json response, since json is well defined as is. A proper JSON streaming parser does not need to rely on `\n`.

**Comment by karalabe** [comment] 2017-02-24 09:42
https://github.com/ethcore/parity/issues/4647#issuecomment-282247655

**Closed by karalabe** 2017-02-24 09:42 UTC
