### ISSUE TITLE
graphql: graphiql interface not available on localhost:8547

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/go-ethereum#20083] opened 2019-09-17 20:14 UTC
#### System information

Geth version: `Geth/v1.9.3-stable/darwin-amd64/go1.12.9`
OS & Version: OSX

#### Expected behaviour
GraphiQL interface appears on localhost:8547 when `--graphql` flag is used.

#### Actual behaviour
Prompt for downloading a gzip file:
<img width="793" alt="Screen Shot 2019-09-17 at 1 36 56 PM" src="https://user-images.githubusercontent.com/3621728/65075718-b180cf80-d954-11e9-97b8-ff6d5a821a7d.png">

#### Steps to reproduce the behaviour
Download latest geth from homebrew on OSX and run `geth --graphql`

#### Backtrace

````
INFO [09-17|13:36:38.253] GraphQL endpoint opened                  url=http://127.0.0.1:8547
````

**Comment by evertonfraga** [comment] 2019-09-17 20:25
Seems to be have been fixed in https://github.com/ethereum/go-ethereum/commit/49b86a28590917eebf43bce213a2e0586db58755#diff-20e0563f6a9130cd973b1946c27d6ff8R55.

Now waiting for the release.

**Comment by karalabe** [comment] 2019-09-18 09:15
Yeah, there was a regression when enabling gzip encoding but not setting content-type. Fixed on master.

**Closed by karalabe** 2019-09-18 09:15 UTC
