### ISSUE TITLE
diffMode: true doesn't work with preState tracer

### ISSUE THREAD

**Issue by alsofter** [ethereum/go-ethereum#26513] opened 2023-01-17 10:27 UTC
#### System information

Geth version: 1.10.26-stable
CL client & version: Prysm/v3.2.0
OS & Version: Centos 8

#### Expected behaviour
Getting a list of traced states with "pre" and "post" keys as described in docs.

E.G. (from docs):
{
  post: {
    0x35a9f94af726f07b5162df7e828cc9dc8439e7d0: {
      nonce: 1135
    }
  },
  pre: {
    0x35a9f94af726f07b5162df7e828cc9dc8439e7d0: {
      balance: "0x7a48429e177130a",
      nonce: 1134
    }
  }
}

#### Actual behaviour
Getting a list of prestates only (as I dont' use flag diffMode: true)
For example something like this:
{
    0x35a9f94af726f07b5162df7e828cc9dc8439e7d0: {
      balance: "0x7a48429e177130a",
      nonce: 1134
}

#### Steps to reproduce the behaviour

Sending a curl request:
curl -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceTransaction","params":["0x126591de271bf2c17fc8eebdf2b74883fa728dc3f78418bf6307875449cdd76d", {"tracer": "prestateTracer", "tracerConfig": {"diffMode": true}}],"id":15295,"jsonrpc":"2.0"}' http://localhost:8545

**Comment by s1na** [comment] 2023-01-17 11:13
I updated the docs before the change was released, sorry for the confusion. The `diffMode` is slated for v1.11.0 which doesn't have a clear release date as of now. If you really need this feature I suggest you use `master`.

I will close the issue as it is not a bug. If you had further questions don't hesitate to ask.

**Closed by s1na** 2023-01-17 11:13 UTC
Labels: type:bug
