### ISSUE TITLE
Panic on "Looking for peers"

### ISSUE THREAD

**Issue by voronindev** [ethereum/go-ethereum#21496] opened 2020-08-28 11:01 UTC
Hi there,

I'm using the latest build, but one of them (I've got 2) are crashing periodically.

#### System information

Geth version: `1.9.20 ethereum/client-go`
Digest: `sha256:9e14d7cdf4f610e0b0f4edeb6e1ef218ae1114dcd819d62bb2d2949e4aa4e333`
OS & Version: `NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`
Docker CMD: `--testnet  --cache 10000 --syncmode "fast" --nousb --rpcapi debug,eth,web3,personal,net --rpc --rpcaddr "0.0.0.0" --rpcvhosts="*" --ws --wsaddr "0.0.0.0" --wsorigins="*" --port 30303 --wsport 8546 --rpcport 8545`
Commit hash : (if `develop`)

#### Expected behaviour
No panic

#### Actual behaviour
Panics while trying to sync

#### Steps to reproduce the behaviour
Idk, how to reproduce that. I have 2 different nodes, on different machines, but with the same configuration and docker compose image. One of them are crashing periodically. (Every 2-3 mins)

#### Backtrace

````
geth_1  | WARN [08-28|10:50:27.300] Switch sync mode from fast sync to full sync 
geth_1  | INFO [08-28|10:50:27.301] Starting peer-to-peer node               instance=Geth/v1.9.20-stable-979fc968/linux-amd64/go1.15
geth_1  | INFO [08-28|10:50:27.709] New local node record                    seq=9065 id=e5666364e47fd534 ip=127.0.0.1 udp=30303 tcp=30303
geth_1  | INFO [08-28|10:50:27.710] IPC endpoint opened                      url=/root/.ethereum/testnet/geth.ipc
geth_1  | INFO [08-28|10:50:27.711] HTTP server started                      endpoint=[::]:8545 cors= vhosts=*
geth_1  | INFO [08-28|10:50:27.711] WebSocket enabled                        url=ws://[::]:8546
geth_1  | INFO [08-28|10:50:27.711] Started P2P networking                   self=enode://61bc478a98c152250dcfa78ff8fb3677ad21b33f5bd3de4e72b4d5158df28f72198ccc8b5dcc960a7b8e8d357762f3ae0bd2e3836d5b9e040beca441914bc10d@127.0.0.1:30303
geth_1  | INFO [08-28|10:50:37.865] Looking for peers                        peercount=0 tried=60 static=0
geth_1  | INFO [08-28|10:50:39.072] New local node record                    seq=9066 id=e5666364e47fd534 ip=159.69.196.55 udp=30303 tcp=30303
geth_1  | INFO [08-28|10:50:47.926] Looking for peers                        peercount=1 tried=60 static=0
geth_1  | INFO [08-28|10:50:58.023] Looking for peers                        peercount=0 tried=43 static=0
geth_1  | INFO [08-28|10:51:08.170] Looking for peers                        peercount=0 tried=59 static=0
geth_1  | INFO [08-28|10:51:18.181] Looking for peers                        peercount=0 tried=59 static=0
geth_1  | INFO [08-28|10:51:19.629] Block synchronisation started 
geth_1  | INFO [08-28|10:51:28.186] Looking for peers                        peercount=2 tried=77 static=0
geth_1  | panic: runtime error: invalid memory address or nil pointer dereference
geth_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc2cfd0]
geth_1  | 
geth_1  | goroutine 1843 [running]:
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc01be781c0, 0xc073984c30, 0xc074a0cb40, 0x0, 0x0, 0xa)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:906 +0x1670
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc01be781c0, 0xc073984c30, 0xe03473da4c4bee10, 0x7be4e15229ec19b7, 0xe71161f77a60e4ee, 0x5f4eb7d0d41fc283, 0xc026b0a840, 0x0, 0x0)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:460 +0x3da
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc01be781c0, 0xc073b3a880, 0x10, 0xe03473da4c4bee10, 0x7be4e15229ec19b7, 0xe71161f77a60e4ee, 0x5f4eb7d0d41fc283, 0xc026b0a840, 0x0, 0x0, ...)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:423 +0x390
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc01be781c0, 0xc073b3a880, 0x10, 0xe03473da4c4bee10, 0x7be4e15229ec19b7, 0xe71161f77a60e4ee, 0x5f4eb7d0d41fc283, 0xc026b0a840, 0xf1d9d2e00000000, 0x1000200000003, ...)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:333 +0x8c
geth_1  | github.com/ethereum/go-ethereum/eth.(*ProtocolManager).doSync(0xc071356f00, 0xc07cc100c0, 0x135e1f8, 0xc01be6e9a0)
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:322 +0xa5
geth_1  | github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc085877e00, 0xc07cc100c0)
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:298 +0x38
geth_1  | created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:298 +0x76
root_geth_1 exited with code 2
````

**Comment by holiman** [comment] 2020-08-28 11:28
```
geth_1  | WARN [08-28|10:50:27.300] Switch sync mode from fast sync to full sync 
```
That's odd. Any more logs before that?

**Comment by holiman** [comment] 2020-08-28 11:30
In particular, it should output info about latest header, latest block etc during the bootstrap phase

**Comment by holiman** [comment] 2020-08-28 11:34
How are you supplying the datadir to the node? are you using docker mounts to mount a host-volume? And if so, are you by any chance using that same host-folder with another process?

**Comment by voronindev** [comment] 2020-08-28 11:45
The full log here:
```
geth_1  | INFO [08-28|11:05:28.035] Starting Geth on Ropsten testnet... 
geth_1  | WARN [08-28|11:05:28.036] The --testnet flag is ambiguous! Please specify one of --goerli, --rinkeby, or --ropsten. 
geth_1  | WARN [08-28|11:05:28.036] The generic --testnet flag is deprecated and will be removed in the future! 
geth_1  | WARN [08-28|11:05:28.036] Sanitizing cache to Go's GC limits       provided=10000 updated=5220
geth_1  | INFO [08-28|11:05:28.039] Maximum peer count                       ETH=50 LES=0 total=50
geth_1  | WARN [08-28|11:05:28.039] The flag --rpc is deprecated and will be removed in the future, please use --http 
geth_1  | WARN [08-28|11:05:28.039] The flag --rpcaddr is deprecated and will be removed in the future, please use --http.addr 
geth_1  | WARN [08-28|11:05:28.039] The flag --rpcport is deprecated and will be removed in the future, please use --http.port 
geth_1  | WARN [08-28|11:05:28.039] The flag --rpcapi is deprecated and will be removed in the future, please use --http.api 
geth_1  | WARN [08-28|11:05:28.039] The flag --rpcvhosts is deprecated and will be removed in the future, please use --http.vhosts 
geth_1  | WARN [08-28|11:05:28.039] The flag --wsaddr is deprecated and will be removed in the future, please use --ws.addr 
geth_1  | WARN [08-28|11:05:28.039] The flag --wsport is deprecated and will be removed in the future, please use --ws.port 
geth_1  | WARN [08-28|11:05:28.039] The flag --wsorigins is deprecated and will be removed in the future, please use --ws.origins 
geth_1  | WARN [08-28|11:05:28.039] Using the deprecated `testnet` datadir. Future versions will store the Ropsten chain in `ropsten`. 
geth_1  | INFO [08-28|11:05:28.039] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
geth_1  | INFO [08-28|11:05:28.040] Set global gas cap                       cap=25000000
geth_1  | INFO [08-28|11:05:28.041] Allocated trie memory caches             clean=1.27GiB dirty=1.27GiB
geth_1  | INFO [08-28|11:05:28.041] Allocated cache and file handles         database=/root/.ethereum/testnet/geth/chaindata cache=2.55GiB handles=524288
geth_1  | INFO [08-28|11:05:28.858] Opened ancient database                  database=/root/.ethereum/testnet/geth/chaindata/ancient
geth_1  | INFO [08-28|11:05:28.875] Persisted trie from memory database      nodes=355 size=50.41KiB time=2.435348ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
geth_1  | INFO [08-28|11:05:28.876] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Petersburg: 4939394 Istanbul: 6485846, Muir Glacier: 7117117, YOLO v1: <nil>, Engine: ethash}"
geth_1  | INFO [08-28|11:05:28.876] Disk storage enabled for ethash caches   dir=/root/.ethereum/testnet/geth/ethash count=3
geth_1  | INFO [08-28|11:05:28.876] Disk storage enabled for ethash DAGs     dir=/root/.ethash                       count=2
geth_1  | INFO [08-28|11:05:28.876] Initialising Ethereum protocol           versions="[65 64 63]" network=3 dbversion=8
geth_1  | INFO [08-28|11:05:31.493] Loaded most recent local header          number=8479627 hash="9400e7…b1acfc" td=31290068525054253 age=2w2d2h
geth_1  | INFO [08-28|11:05:31.493] Loaded most recent local full block      number=8479627 hash="9400e7…b1acfc" td=31290068525054253 age=2w2d2h
geth_1  | INFO [08-28|11:05:31.493] Loaded most recent local fast block      number=8479627 hash="9400e7…b1acfc" td=31290068525054253 age=2w2d2h
geth_1  | INFO [08-28|11:05:31.515] Loaded local transaction journal         transactions=0 dropped=0
geth_1  | INFO [08-28|11:05:31.515] Regenerated local transaction journal    transactions=0 accounts=0
geth_1  | WARN [08-28|11:05:31.515] Switch sync mode from fast sync to full sync 
geth_1  | INFO [08-28|11:05:31.516] Starting peer-to-peer node               instance=Geth/v1.9.20-stable-979fc968/linux-amd64/go1.15
geth_1  | INFO [08-28|11:05:31.829] New local node record                    seq=9099 id=e5666364e47fd534 ip=127.0.0.1 udp=30303 tcp=30303
geth_1  | INFO [08-28|11:05:31.831] IPC endpoint opened                      url=/root/.ethereum/testnet/geth.ipc
geth_1  | INFO [08-28|11:05:31.831] HTTP server started                      endpoint=[::]:8545 cors= vhosts=*
geth_1  | INFO [08-28|11:05:31.831] WebSocket enabled                        url=ws://[::]:8546
geth_1  | INFO [08-28|11:05:31.831] Started P2P networking                   self=enode://61bc478a98c152250dcfa78ff8fb3677ad21b33f5bd3de4e72b4d5158df28f72198ccc8b5dcc960a7b8e8d357762f3ae0bd2e3836d5b9e040beca441914bc10d@127.0.0.1:30303
geth_1  | INFO [08-28|11:05:41.862] Looking for peers                        peercount=1 tried=57 static=0
geth_1  | INFO [08-28|11:05:46.439] New local node record                    seq=9100 id=e5666364e47fd534 ip=159.69.196.55 udp=1042  tcp=30303
geth_1  | INFO [08-28|11:05:51.862] Looking for peers                        peercount=1 tried=55 static=0
geth_1  | INFO [08-28|11:05:59.177] Block synchronisation started 
geth_1  | INFO [08-28|11:06:02.863] Looking for peers                        peercount=2 tried=47 static=0
geth_1  | panic: runtime error: invalid memory address or nil pointer dereference
geth_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc2cfd0]
geth_1  | 
geth_1  | goroutine 1099 [running]:
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc00013cc40, 0xc019c47b30, 0xc0006bb8c0, 0x0, 0x0, 0xa)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:906 +0x1670
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc00013cc40, 0xc019c47b30, 0x6c9ba7e358cb325d, 0xe0b11fefaa91e8d6, 0xc50144752a187f32, 0xe5d5b296cd118145, 0xc01a3b4540, 0x0, 0x0)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:460 +0x3da
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc00013cc40, 0xc019079d20, 0x10, 0x6c9ba7e358cb325d, 0xe0b11fefaa91e8d6, 0xc50144752a187f32, 0xe5d5b296cd118145, 0xc01a3b4540, 0x0, 0x0, ...)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:423 +0x390
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc00013cc40, 0xc019079d20, 0x10, 0x6c9ba7e358cb325d, 0xe0b11fefaa91e8d6, 0xc50144752a187f32, 0xe5d5b296cd118145, 0xc01a3b4540, 0x0, 0x0, ...)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:333 +0x8c
geth_1  | github.com/ethereum/go-ethereum/eth.(*ProtocolManager).doSync(0xc000843100, 0xc01d2ed380, 0x3, 0xc019fef140)
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:322 +0xa5
geth_1  | github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc00084fd10, 0xc01d2ed380)
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:298 +0x38
geth_1  | created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:298 +0x76
```
Using following docker-compose config:
```
version: "2"
services:
  geth:
    image: ethereum/client-go:stable
    volumes:
      - /usr/lib/ethereum:/root/.ethereum
    command: --testnet  --cache 10000 --syncmode "fast" --nousb --rpcapi debug,eth,web3,personal,net --rpc --rpcaddr "0.0.0.0" --rpcvhosts="*" --ws --wsaddr "0.0.0.0" --wsorigins="*" --port 30303 --wsport 8546 --rpcport 8545
    ports:
      - 30303:30303
      - 8545:8545
      - 8546:8546
    restart: always
```
Only one node per host. This volume used by single instance.

**Comment by voronindev** [comment] 2020-08-28 11:59
I've restart a host, and and following problem repeated (truncated log):
```
geth_1  | INFO [08-28|11:56:04.965] New local node record                    seq=9192 id=e5666364e47fd534 ip=159.69.196.55 udp=30303 tcp=30303
geth_1  | INFO [08-28|11:56:06.907] Looking for peers                        peercount=1 tried=61 static=0
geth_1  | INFO [08-28|11:56:16.908] Looking for peers                        peercount=1 tried=58 static=0
geth_1  | INFO [08-28|11:56:30.907] Looking for peers                        peercount=1 tried=44 static=0
geth_1  | INFO [08-28|11:56:40.907] Looking for peers                        peercount=1 tried=73 static=0
geth_1  | INFO [08-28|11:56:50.922] Looking for peers                        peercount=2 tried=59 static=0
geth_1  | INFO [08-28|11:57:01.205] Looking for peers                        peercount=1 tried=165 static=0
geth_1  | INFO [08-28|11:57:11.262] Block synchronisation started 
geth_1  | INFO [08-28|11:57:11.417] Looking for peers                        peercount=2 tried=52  static=0
geth_1  | INFO [08-28|11:57:21.417] Looking for peers                        peercount=2 tried=80  static=0
geth_1  | panic: runtime error: invalid memory address or nil pointer dereference
geth_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc2cfd0]
geth_1  | 
geth_1  | goroutine 3053 [running]:
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc0000dce00, 0xc01e933c20, 0xc01f143d40, 0x0, 0x0, 0xa)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:906 +0x1670
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc0000dce00, 0xc01e933c20, 0x2145bf608fec33ca, 0x7338955df07d77ae, 0xca4d880a62b5f122, 0xdb9e4d61a7fa8575, 0xc01eaced00, 0x0, 0x0)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:460 +0x3da
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc0000dce00, 0xc01e9e4a70, 0x10, 0x2145bf608fec33ca, 0x7338955df07d77ae, 0xca4d880a62b5f122, 0xdb9e4d61a7fa8575, 0xc01eaced00, 0xc000000000, 0x0, ...)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:423 +0x390
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc0000dce00, 0xc01e9e4a70, 0x10, 0x2145bf608fec33ca, 0x7338955df07d77ae, 0xca4d880a62b5f122, 0xdb9e4d61a7fa8575, 0xc01eaced00, 0x0, 0xc0001b9900, ...)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:333 +0x8c
geth_1  | github.com/ethereum/go-ethereum/eth.(*ProtocolManager).doSync(0xc00066f600, 0xc01eade1c0, 0xd189992ee7b0c77a, 0xfcacb18289bd092d)
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:322 +0xa5
geth_1  | github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc0006958f0, 0xc01eade1c0)
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:298 +0x38
geth_1  | created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:298 +0x76
```

**Comment by holiman** [comment] 2020-08-28 13:41
So, one thing I'm curious about, is if you can start it, and then stop it before it talks to any peers.  The stop portion should write out some additional info about the blocks, e.g: 
```
INFO [08-28|11:53:18.087] HTTP server stopped                      endpoint=[::]:8546
INFO [08-28|11:53:18.088] IPC endpoint closed                      url=/eth/geth.ipc
INFO [08-28|11:53:18.147] Deallocated fast sync bloom              items=355 errorrate=0.000
INFO [08-28|11:53:18.148] Loaded most recent local header          number=784     hash="7a964e…587cf2" td=721311419 age=3y9mo3w
INFO [08-28|11:53:18.148] Loaded most recent local full block      number=0       hash="419410…ca4a2d" td=1048576   age=51y4mo3w
INFO [08-28|11:53:18.148] Loaded most recent local fast block      number=0       hash="419410…ca4a2d" td=1048576   age=51y4mo3w
INFO [08-28|11:53:18.148] Loaded last fast-sync pivot marker       number=8570973
WARN [08-28|11:53:18.148] Rolled back chain segment                header=784->784 fast=527->0 block=0->0 reason="syncing canceled (requested)"
```

You can achieve this by adding `--nodiscover --maxpeers=0` to the command line, and just let it run for a few seconds before you shut it down.

**Comment by voronindev** [comment] 2020-08-28 14:04
I'm not sure, that it's what you are curious about, but a done as you wrote:
```
geth_1  | INFO [08-28|14:01:40.001] HTTP server stopped                      endpoint=[::]:8545
geth_1  | INFO [08-28|14:01:40.502] HTTP server stopped                      endpoint=[::]:8546
geth_1  | INFO [08-28|14:01:40.502] IPC endpoint closed                      url=/root/.ethereum/testnet/geth.ipc
geth_1  | INFO [08-28|14:01:40.502] Ethereum protocol stopped 
geth_1  | INFO [08-28|14:01:40.502] Transaction pool stopped 
geth_1  | INFO [08-28|14:01:40.502] Writing cached state to disk             block=8479627 hash="9400e7…b1acfc" root="21660a…2c8eae"
geth_1  | INFO [08-28|14:01:40.502] Persisted trie from memory database      nodes=0   size=0.00B    time="9.55µs"   gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
geth_1  | INFO [08-28|14:01:40.502] Writing cached state to disk             block=8479626 hash="aa27d9…979a04" root="b0d505…fcd9f0"
geth_1  | INFO [08-28|14:01:40.502] Persisted trie from memory database      nodes=0   size=0.00B    time="1.807µs"  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
geth_1  | INFO [08-28|14:01:40.503] Writing cached state to disk             block=8479500 hash="a542f7…736a9a" root="9beb29…5ce501"
geth_1  | INFO [08-28|14:01:40.503] Persisted trie from memory database      nodes=0   size=0.00B    time="2.681µs"  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
geth_1  | INFO [08-28|14:01:40.503] Writing clean trie cache to disk         path=/root/.ethereum/testnet/geth/triecache threads=4
geth_1  | INFO [08-28|14:01:41.840] Looking for peers                        peercount=0 tried=56 static=0
geth_1  | INFO [08-28|14:01:42.048] Persisted the clean trie cache           path=/root/.ethereum/testnet/geth/triecache elapsed=1.545s
geth_1  | INFO [08-28|14:01:42.048] Blockchain stopped 
root_geth_1 exited with code 0
```

**Comment by holiman** [comment] 2020-09-01 07:48
Yes, that was what I was curious about. So essentially: 
startup:
```

geth_1  | INFO [08-28|11:05:31.493] Loaded most recent local header          number=8479627 hash="9400e7…b1acfc" td=31290068525054253 age=2w2d2h
geth_1  | INFO [08-28|11:05:31.493] Loaded most recent local full block      number=8479627 hash="9400e7…b1acfc" td=31290068525054253 age=2w2d2h
geth_1  | INFO [08-28|11:05:31.493] Loaded most recent local fast block      number=8479627 hash="9400e7…b1acfc" td=31290068525054253 age=2w2d2h
```
shutdown:
```
geth_1  | INFO [08-28|14:01:40.502] Writing cached state to disk             block=8479627 hash="9400e7…b1acfc" root="21660a…2c8eae"
geth_1  | INFO [08-28|14:01:40.502] Writing cached state to disk             block=8479626 hash="aa27d9…979a04" root="b0d505…fcd9f0"
geth_1  | INFO [08-28|14:01:40.503] Writing cached state to disk             block=8479500 hash="a542f7…736a9a" root="9beb29…5ce501"
```
But if it talks to some network peer, we hit 
```
geth_1  | panic: runtime error: invalid memory address or nil pointer dereference
geth_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc2cfd0]
geth_1  | 
geth_1  | goroutine 3053 [running]:
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc0000dce00, 0xc01e933c20, 0xc01f143d40, 0x0, 0x0, 0xa)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:906 +0x1670
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc0000dce00, 0xc01e933c20, 0x2145bf608fec33ca, 0x7338955df07d77ae, 0xca4d880a62b5f122, 0xdb9e4d61a7fa8575, 0xc01eaced00, 0x0, 0x0)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:460 +0x3da
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc0000dce00, 0xc01e9e4a70, 0x10, 0x2145bf608fec33ca, 0x7338955df07d77ae, 0xca4d880a62b5f122, 0xdb9e4d61a7fa8575, 0xc01eaced00, 0xc000000000, 0x0, ...)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:423 +0x390
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc0000dce00, 0xc01e9e4a70, 0x10, 0x2145bf608fec33ca, 0x7338955df07d77ae, 0xca4d880a62b5f122, 0xdb9e4d61a7fa8575, 0xc01eaced00, 0x0, 0xc0001b9900, ...)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:333 +0x8c
geth_1  | github.com/ethereum/go-ethereum/eth.(*ProtocolManager).doSync(0xc00066f600, 0xc01eade1c0, 0xd189992ee7b0c77a, 0xfcacb18289bd092d)
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:322 +0xa5
geth_1  | github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc0006958f0, 0xc01eade1c0)
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:298 +0x38
geth_1  | created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:298 +0x76
```
This is very curious indeed.

**Comment by holiman** [comment] 2020-09-01 12:37
@karalabe any ideas how to diagnose this?

**Comment by voronindev** [comment] 2020-09-02 10:05
Looks like #21505 got the same problem

**Comment by karalabe** [comment] 2020-09-02 13:13
That's unrelated

**Comment by karalabe** [comment] 2020-09-02 13:23
Pasting from discord.

---

```go
                var known bool
                switch mode {
                case FullSync:
                    known = d.blockchain.HasBlock(h, n)
                case FastSync:
                    known = d.blockchain.HasFastBlock(h, n)
                default:
                    known = d.lightchain.HasHeader(h, n)
                }
                if !known {
                    end = check
                    break
                }
                header := d.lightchain.GetHeaderByHash(h) // Independent of sync mode, header surely exists
                if header.Number.Uint64() != check {
```

it crashes in the last line
but we just checked that it exists right above that
unless we lost the hash->number mapping
because above we check with the number included, so we don't do the extra inde xlookup
but ByHash does it. if th eindex is missing, header will be nil

**Comment by karalabe** [comment] 2020-09-02 13:25
@voronindev Do you have an unclean shutdown / crash log from before this thing started happening?

**Comment by karalabe** [comment] 2020-09-02 13:34
@voronindev My suggestion to fix it quickly is to

1. **Back up your entire data directory somewhere.**
2. Start your node with `--maxpeers=0` to prevent it from crashing.
3. Run `debug.setHead("0x813DF0")` to roll back the chain to block 8470000.
4. Restart Geth normally.

The last command should clean up the head of the database from any leftovers and hopefully the issue is not too deep in the chain and it can just pick up from that older block.

**Again, please back up your datadir first, using `setHead` is not without danger**.

**Comment by karalabe** [comment] 2020-09-02 13:34
If you can upload your `chaindata` dir somewhere so we could poke at it, that would be even more awesome.

**Comment by voronindev** [comment] 2020-09-02 20:35
Ok, i'll try to rollback header to the following height. Before this error happened, I've updating my node from 1.9.19 to 1.9.20, like this::
```
docker-compose pull
docker-compose up -d
```
When I received latest version (1.9.20), and tried to look through the logs, I've reached this error. That's is all.

**Comment by voronindev** [comment] 2020-09-02 21:06
It's quite difficult to share `chaindata`, but I did as you said, first I saw (after `debug_setHead("0x813DF0")`):
```
geth_1  | WARN [09-02|20:46:19.452] Rewinding blockchain                     target=0
```
Then, after graceful stop and run:
```
eth_1  | INFO [09-02|20:59:49.871] Initialising Ethereum protocol           versions="[65 64 63]" network=3 dbversion=8
geth_1  | INFO [09-02|20:59:49.873] Loaded most recent local header          number=7719961 hash="854d85…ea87d4" td=30281157352637171 age=4mo2w6d
geth_1  | INFO [09-02|20:59:49.873] Loaded most recent local full block      number=7624435 hash="cdea42…94e28c" td=30215657987996072 age=5mo5d12h
geth_1  | INFO [09-02|20:59:49.873] Loaded most recent local fast block      number=7719961 hash="854d85…ea87d4" td=30281157352637171 age=4mo2w6d
geth_1  | ERROR[09-02|20:59:49.898] Truncating ancient chain                 from=7719961 to=7624435
geth_1  | INFO [09-02|21:00:26.516] Loaded most recent local header          number=7624435 hash="cdea42…94e28c" td=30215657987996072 age=5mo5d12h
geth_1  | INFO [09-02|21:00:26.516] Loaded most recent local full block      number=7624435 hash="cdea42…94e28c" td=30215657987996072 age=5mo5d12h
geth_1  | INFO [09-02|21:00:26.516] Loaded most recent local fast block      number=7624435 hash="cdea42…94e28c" td=30215657987996072 age=5mo5d12h
geth_1  | INFO [09-02|21:00:26.520] Loaded local transaction journal         transactions=1 dropped=1
geth_1  | INFO [09-02|21:00:26.521] Regenerated local transaction journal    transactions=0 accounts=0
geth_1  | INFO [09-02|21:00:26.522] Starting peer-to-peer node               instance=Geth/v1.9.20-stable-979fc968/linux-amd64/go1.15
geth_1  | INFO [09-02|21:00:26.587] New local node record                    seq=20292 id=e5666364e47fd534 ip=127.0.0.1 udp=30303 tcp=30303
geth_1  | INFO [09-02|21:00:26.587] Started P2P networking                   self=enode://61bc478a98c152250dcfa78ff8fb3677ad21b33f5bd3de4e72b4d5158df28f72198ccc8b5dcc960a7b8e8d357762f3ae0bd2e3836d5b9e040beca441914bc10d@127.0.0.1:30303
geth_1  | INFO [09-02|21:00:26.588] IPC endpoint opened                      url=/root/.ethereum/testnet/geth.ipc
geth_1  | INFO [09-02|21:00:26.589] HTTP server started                      endpoint=[::]:8545 cors= vhosts=*
geth_1  | INFO [09-02|21:00:26.589] WebSocket enabled                        url=ws://[::]:8546
geth_1  | INFO [09-02|21:00:36.664] Looking for peers                        peercount=1 tried=59 static=0
geth_1  | INFO [09-02|21:00:42.815] New local node record                    seq=20293 id=e5666364e47fd534 ip=159.69.196.55 udp=1033  tcp=30303
geth_1  | INFO [09-02|21:00:46.828] Looking for peers                        peercount=1 tried=56 static=0
geth_1  | INFO [09-02|21:00:56.895] Looking for peers                        peercount=0 tried=52 static=0
geth_1  | INFO [09-02|21:01:00.557] Block synchronisation started 
geth_1  | INFO [09-02|21:01:03.980] Downloader queue stats                   receiptTasks=0 blockTasks=153 itemSize=613.96B throttle=8192
geth_1  | INFO [09-02|21:01:06.903] Looking for peers                        peercount=2 tried=52 static=0
geth_1  | INFO [09-02|21:01:07.098] Imported new chain segment               blocks=2 txs=27 mgas=2.327 elapsed=3.117s mgasps=0.746 number=7624437 hash="996fd3…c0b479" age=5mo5d12h dirty=231.98KiB
geth_1  | INFO [09-02|21:01:15.159] Imported new chain segment               blocks=126 txs=2561 mgas=266.571 elapsed=8.056s mgasps=33.086 number=7624563 hash="2c8fa3…0d47da" age=5mo5d12h dirty=15.52MiB
geth_1  | INFO [09-02|21:01:16.943] Looking for peers                        peercount=2 tried=70 static=0
geth_1  | INFO [09-02|21:01:23.161] Imported new chain segment               blocks=21  txs=547  mgas=140.040 elapsed=8.002s mgasps=17.499 number=7624584 hash="bb3e3a…7c7971" age=5mo5d11h dirty=27.68MiB
geth_1  | INFO [09-02|21:01:23.762] Imported new chain segment               blocks=20  txs=284  mgas=21.258  elapsed=600.489ms mgasps=35.402 number=7624604 hash="92ee60…6def85" age=5mo5d11h dirty=28.09MiB
geth_1  | INFO [09-02|21:01:23.763] Downloader queue stats                   receiptTasks=0 blockTasks=3525 itemSize=5.93KiB throttle=8192
geth_1  | INFO [09-02|21:01:27.228] Looking for peers                        peercount=3 tried=68 static=0
geth_1  | INFO [09-02|21:01:31.957] Imported new chain segment               blocks=161 txs=2629 mgas=295.146 elapsed=8.177s    mgasps=36.093 number=7624765 hash="d2f901…bf7558" age=5mo5d11h dirty=31.84MiB
geth_1  | INFO [09-02|21:01:37.504] Looking for peers                        peercount=3 tried=107 static=0
geth_1  | INFO [09-02|21:01:40.049] Imported new chain segment               blocks=118 txs=2932 mgas=408.865 elapsed=8.092s    mgasps=50.526 number=7624883 hash="275ad0…890e1a" age=5mo5d10h dirty=43.71MiB
geth_1  | INFO [09-02|21:01:47.526] Looking for peers                        peercount=3 tried=64  static=0
geth_1  | INFO [09-02|21:01:48.062] Imported new chain segment               blocks=229 txs=4009 mgas=486.746 elapsed=8.012s    mgasps=60.749 number=7625112 hash="3a914e…718905" age=5mo5d9h  dirty=44.68MiB
```

**Comment by rjl493456442** [comment] 2020-09-08 08:40
It seems after rewinding the HEAD, the chain is syncing correctly.

**Comment by holiman** [comment] 2020-09-08 08:49
Thanks for working with us, we're closing this now since it seems that the cause was older code crashing, and the reworked setHead solved the issue, allowing geth to continue syncing.

**Closed by holiman** 2020-09-08 08:49 UTC
Labels: status:triage
