### ISSUE TITLE
Sometimes, why is the response "gas" value from eth_estimateGas API lower than actual gas?

### ISSUE THREAD

**Issue by TerrySimon** [ethereum/go-ethereum#23400] opened 2021-08-14 16:38 UTC
**System Information**
  - Geth version: 1.16.4
  - OS & Version: Linux

**Expected behavior**
  - It should respond to the same "gas" value

**Actual behavior**
  - Sometimes, it responds to the difference "gas" value although the same input param
  - Evidence
     - TxHash: https://etherscan.io/tx/0x47a8baaa9512a5f8684e6d3c6fab35a823146ccb782349b01381615584e4828e

**Steps to reproduce the behavior**
  - Run "eth_estimateGas" API many times (about 15-25 calls) in the MainNet environment with params
`{
    "jsonrpc": "2.0",
    "method": "eth_estimateGas",
    "params": [
        {
            "from": "0x9696f59e4d72e237be84ffd425dcad154bf96976",
            "to": "0xdac17f958d2ee523a2206206994597c13d831ec7",
            "data": "0xa9059cbb00000000000000000000000045a4c50c683aea78c0f02e05598ec3a4e0339cef0000000000000000000000000000000000000000000000000000000046a1aa40"
        }
    ],
    "id": 1
}`
  - Returned gas
     - 0xb41d (= 46109)  ==> Success when using this returned gas in Transaction
     - 0x94dd (= 38109)  ==> Error "out_of_gas" occurs when using this returned gas in Transaction

**Other Error Cases**
     - TxHash: https://etherscan.io/tx/0xcabbcf8d85a3125a67fc070890eed314554166e766ca5dc0926066f2c538ac84
     - TxHash: https://etherscan.io/tx/0xf41301458f8701a0b0816d345a66cd81a3bace48a49da33705262e5f8e47550c

**Comment by Sunset17** [comment] 2021-08-14 17:05
Is there anyway I can get my Etherium back so etherscan emailed me saying they took back 26 Etherium from the scammer and it was put on my address but then sushi swap took it all. It looks like they may be holding it but I ain’t That good at this. Then I got 2nd email from etherscan and they took the rest of the scammers Etherium and put it on my address and again I couldn’t get mine back. I just want my 1.5 Etherium back that’s it. Any help please.

**Comment by ligi** [comment] 2021-08-14 17:07
The calculated gas value depends on the current state of the chain - so your expected behavior of always returning the same gas is not possible.
I suggest you multiply the result by 1.5 - this is what most wallets are doing.

**Comment by Sunset17** [comment] 2021-08-14 17:13
Even if it has been like 3 days


Sent from Yahoo Mail for iPhone


On Saturday, August 14, 2021, 1:08 PM, ligi ***@***.***> wrote:




The calculated gas value depends on the current state of the chain - so your expected behavior of always returning the same gas is not possible.
I suggest you multiply the result by 1.5 - this is what most wallets are doing.

**Comment by Sunset17** [comment] 2021-08-14 17:13
And do I use the parent chain 


Sent from Yahoo Mail for iPhone


On Saturday, August 14, 2021, 1:08 PM, ligi ***@***.***> wrote:




The calculated gas value depends on the current state of the chain - so your expected behavior of always returning the same gas is not possible.
I suggest you multiply the result by 1.5 - this is what most wallets are doing.

**Comment by TerrySimon** [comment] 2021-08-14 17:21
- Thanks for the reply. Because, I do "transfer token" Transaction for USDT contract so gas value depends only on the state (Address's amount token > 0 or = 0) of Address's From or To in the storage contract. Therefore, I think "eth_estimateGas" should return at least 46109 but sometimes, it returns 38109 lower than 46109. At the time it returns 38109, it means that the "transfer" function (USDT contract) is successfully executed with that value (38109) but in fact, there is not exist a Transaction that successfully executes with that gas value (38109) => contradictory!!

**Comment by karalabe** [comment] 2021-08-17 10:33
Can you double check your Geth version. The one you quoted does not exist.

To me gas estimation seems to be stable and return 46109 independent how many times I call it.

**Comment by karalabe** [comment] 2021-08-17 10:34
Is your node by any chance overloaded? Do you see any errors stating that there aren't enough file descriptors.

**Comment by TerrySimon** [comment] 2021-08-17 13:14
Thank you for your feedback
  - I mistakenly typed. **Geth version**: Geth/v1.10.5-stable-33ca98ec/linux-amd64/go1.16.4
  - My node doesn't overload and I haven't seen any errors stating that there aren't enough file descriptors yet in the log file
  - Currently, my node still handles/receives transactions and blocks normally. However, when I make an "eth_estimateGas" API call, I still stumbled into the above issue and caused me to I did fail many transactions. I still can't understand the reason! Thank you for your help

**Comment by lxex** [comment] 2021-08-23 05:43
If you transfer usdt to a new account, the gas will more than 46109

**Comment by TerrySimon** [comment] 2021-09-10 07:43
Hi @karalabe!
  - The document (https://eth.wiki/json-rpc/API) claims that: "**eth_estimateGas**: Generates and returns an estimate of how much gas is necessary to allow the transaction to complete. The transaction will not be added to the blockchain. **Note that the estimate may be significantly more than the amount of gas actually used by the transaction, for a variety of reasons including EVM mechanics and node performance**". Could you please explain why the value of estimateGas tends to rise (bold paragraph)? Because the value of estimateGas tends to be smaller than the value of gasUsed (as evidenced by my question above). Thank you very much!

**Comment by holiman** [comment] 2021-11-03 15:26
> Because I've noticed that the value of estimateGas is usually lower than the value of gasUsed (as evidenced by my question above). 

I would guess that it depends heavily on what you do. If you e.g. send a tx to take some bid in an auction or a defi trade, then there might be other players who are frontrunning you transactions, which could cause the state against which you interact in-block to be different compared to when it was evaluated locally. 

So most differences, I think, would arise from state-changes between estimation and inclusion. Can't really think of any other reason for discrepancies, off the top of my head. 

Anywyay, I think the question is answered? Closing this

**Closed by holiman** 2021-11-03 15:26 UTC
Labels: type:docs
