### ISSUE TITLE
Failing to unlock account after key import

### ISSUE THREAD

**Issue by scottzer0** [ethereum/go-ethereum#941] opened 2015-05-12 22:02 UTC
i followed the `gethkey` export instructions and exported my key, updated to 0.9.20, and then imported the key (it asked me for a new password and repeated oddly).

when i run `geth --unlock primary` or even `geth --unlock <account_address>`, i get:

```Fatal: Unlock account failed 'open /Users/zero/Library/Ethereum/keystore/3137653064383532313930313631616535336163/3137653064383532313930313631616535336163: no such file or directory'
Fatal: Unlock account failed 'open /Users/zero/Library/Ethereum/keystore/3137653064383532313930313631616535336163/3137653064383532313930313631616535336163: no such file or directory'```

**Comment by Gustav-Simonsson** [comment] 2015-05-13 08:09
Duplicate of https://github.com/ethereum/go-ethereum/issues/945

**Closed by Gustav-Simonsson** 2015-05-13 08:09 UTC
Labels: duplicate
